alphagov/notifications-api

- scripts/run_multi_worker_app_paas.sh
Our application servers and celery workers write logs both to a
file that is shipped to CloudWatch and to stdout, which is picked
up by CloudFoundry and sent to Logit Logstash.
This works with gunicorn and single-worker celery deployments, however
celery multi daemonizes worker processes, which detaches them from
stdout, so there's no log output in `cf logs` or Logit.
To fix this, we start a separate tail process to duplicate logs written
to a file to stdout, which should be picked up by CloudFoundry.
> Stream delivery worker logs to stdout when running on PaaS

- app/celery/letters_pdf_tasks.py
- app/letters/utils.py
- tests/app/celery/test_letters_pdf_tasks.py
You can replay one at a time by sending in the file name. Or all the messages in the error folder.
> Added a method to reply letters that are in the error folder on S3.

- app/__init__.py
- app/dao/notifications_dao.py
- app/dao/services_dao.py
- app/platform_stats/platform_stats_schema.py
- app/platform_stats/rest.py
- app/service/rest.py
- app/service/statistics.py
- tests/app/dao/notification_dao/test_notification_dao.py
- tests/app/dao/test_services_dao.py
- tests/app/platform_stats/test_rest.py
- tests/app/service/test_rest.py
- tests/app/service/test_statistics.py
Added in a new endpoint and DAO function to provide the data for the new
platform admin statistics page. The new DAO method gets different data from
the Notifications / NotificationHistory table and also groups it differently.
The old endpoint has not been deleted yet to allow the numbers on the
old and new pages to be compared.
> New endpoint for the updated platform admin stats page

- app/dao/notifications_dao.py
- app/template_statistics/rest.py
- tests/app/dao/notification_dao/test_notification_dao_template_usage.py
By adding the service id, the query performance has improved greatly. It went from 6200ms to 0.04ms.
This should stop the 500s when a template is deleted.
> Improve the performance of the query to get the last template usage.

- app/dao/notifications_dao.py
- tests/app/dao/notification_dao/test_notification_dao.py
Now using `start_date` to determine which table to query.
> Fix aggregate stats DAO function to use start_date

- app/v2/notifications/post_notifications.py
- tests/app/v2/notifications/test_post_notifications.py
We are getting 500 errors when a POST notification has characters that can not be decoded or the json is malformed.
The exception is wrapped and a sensible error message is returned to the client.
> Wrap exception to return a sensible message to the client

- app/dao/date_util.py
- app/dao/fact_notification_status_dao.py
- app/dao/services_dao.py
- app/service/rest.py
- app/service/statistics.py
- tests/app/dao/test_fact_notification_status_dao.py
- tests/app/dao/test_services_dao.py
- tests/app/db.py
- tests/app/service/test_rest.py
- tests/app/service/test_statistics.py
- tests/app/service/test_statistics_rest.py
gets historical data from ft_notification_status table, grouped by month. It returns data in the format:
```{ 'YYYY-MM' : {'template_type': {'status_1': 1, 'status_2': 823}}}```
Note that all relevant months will be there, all template types will be there, but if there is no data statuses will be omitted (so months with no data will still have sms, email, letter, but each one will be an empty dict).
If you request for this year it'll only return months up until today - and today's data will be retrieved from the notifications table and combined with the data from the ft_notification_status table. the ft_notification_status table won't be updated with these numbers - leave that for the nightly job.
> Monthly statuses page from ft_notification_status

- app/config.py
The periodic task to populate ft_notification_status was calling the wrong task, this fixes that.
> Fix task name for notification status updates

- app/complaint/complaint_rest.py
- app/dao/complaint_dao.py
- tests/app/complaint/test_complaint_rest.py
- tests/app/dao/notification_dao/test_notification_dao.py
- tests/app/dao/test_complaint_dao.py
Updated the function which gets all complaints to be paginated. The endpoint which uses this DAO function has been updated to take a page number as a query parameter.
> Paginate complaints

- migrations/versions/0202_fix_old_incomplete_jobs.py
We have a few old jobs which don’t have a `processing_started` date. This means that they always sort to the top of the jobs list in admin, no matter how old they are. We think this is due to an old bug where jobs would not be updated if a deploy was in progress.
This commit backfills the `processing_started` data for these jobs, which will be roughly accurate. Complete accuracy is not the goal; having these jobs not sort to the top of the list is.
This will affect 5 jobs across 3 services on production:
```sql
select
service_id, job_status, created_at, updated_at, processing_started, processing_finished, notification_count, notifications_sent, notifications_delivered, notifications_failed
from
jobs
where
processing_started is null
and
job_status = 'in progress'
;
```
```
service_id …
```
> Clean up old, incomplete jobs

- app/dao/services_dao.py
- app/template_statistics/rest.py
- tests/app/dao/test_services_dao.py
- tests/app/job/test_rest.py
- tests/app/template_statistics/test_rest.py
Three things that take dates on the dashboard. They should all return between seven and eight days. On a monday morning, they should show all of the previous week, including last monday, from monday 00:00.
A couple of months ago they were adjusted down to 6-7 days by accident, to line up with template preview. Corrected that, and updated tests.
Since the shift to redis, only returned 6-7 days. Corrected that, and updated tests. I thought the `limit_days` variable might have confused things, so changed it to read `whole_days`, because we always want seven whole days of data (plus change)
Always showed 7-8 days. Updated the test to confirm this.
> Sort out the dashboard day limits

- app/dao/service_data_retention_dao.py
- app/models.py
- app/service/rest.py
- app/service/service_data_retention_schema.py
- tests/app/dao/test_service_data_retention_dao.py
- tests/app/db.py
- tests/app/service/test_service_data_retention_rest.py
Some of our services need to have the data around for longer than a day. 
In this PR, new endpoints have been added to manage the number of day to retain the data for each change. 
Endpoints created to:
- create service data retention
- modify service data retention
- get all data retention for service
- get data retention for service by id of data retention
> Flexible data retention

- app/celery/scheduled_tasks.py
- app/commands.py
- app/dao/service_callback_api_dao.py
- app/notifications/notifications_ses_callback.py
- app/notifications/process_client_response.py
- migrations/versions/0206_assign_callback_type.py
- tests/app/dao/test_service_callback_api_dao.py
- tests/app/db.py
2nd part of work for this ticket: https://www.pivotaltracker.com/story/show/159003296
We:
- created a migration to assign callback_type "delivery_status" to existing service callback api's
- modified 'get_service_callback_api_for_service' function to only return service callback api's with type "delivery_status"
> Send complaints to service teams

- migrations/versions/0207_set_callback_history_type.py
We've updated the current service callbacks to add callback types
in #1964, but since the table is versioned we also need to add a
type to the history records.
Even though they're not used anywhere at the moment this might make
it easier to restore from a history callback record in the future.
> Add callback_type to service callback history records

- app/models.py
- tests/app/test_model.py
- tests/app/v2/notifications/test_get_notifications.py
The `serialize` method of the Notification model now includes the
`created_by_name`. If a notification was sent as a one-off message this
value will now be the name of the person who sent the notification. If
a notification was sent through the API or by a CSV upload we don't
record the id of the sender, so `created_by_name` will be `None`.
This change affects the data that gets returned from these endpoints:
* /v2/notifications/<notification_id>
* /v2/notifications
[Pivotal story](https://www.pivotaltracker.com/story/show/158970584)
> Include the notification sender name when serializing notifications

- app/celery/scheduled_tasks.py
- app/celery/service_callback_tasks.py
- app/dao/service_callback_api_dao.py
- app/notifications/notifications_ses_callback.py
- app/notifications/process_client_response.py
- tests/app/celery/test_scheduled_tasks.py
- tests/app/celery/test_service_callback_tasks.py
- tests/app/notifications/test_notifications_ses_callback.py
- tests/app/notifications/test_process_client_response.py
Pivotal ticket: https://www.pivotaltracker.com/n/projects/1443052
Part of the work for this story has already been done here:
Add callback_type column to service_callback_api table: https://github.com/alphagov/notifications-api/pull/1958
Create a migration to assign callback_type "delivery_status" to existing service callback api's: https://github.com/alphagov/notifications-api/pull/1964
Add callback_type to service callback history records: https://github.com/alphagov/notifications-api/pull/1966
> Add and call task to send complaints on to service callback APIs

- app/celery/reporting_tasks.py
- app/celery/tasks.py
- tests/app/celery/test_ftp_update_tasks.py
- tests/app/celery/test_reporting_tasks.py
Log exception if the billing counts for letters are different in the dvla response file than what we collected.
> Increase the number of days we calculate billing from 3 to 10 days.

- requirements-app.txt
- requirements.txt
Fixes some issues with the email template in various versions of Outlook.
Full description is here: https://github.com/alphagov/notifications-utils/pull/499
Intention is to help an issue one of our users has with Outlook 2016 on Windows 10. We can't replicate it but hopefully these fixes for similar problems will have an impact. 
Related issue: https://www.pivotaltracker.com/story/show/158835491
> Brings in spacing changes to the email template

- app/commands.py
- app/dao/fact_billing_dao.py
- tests/app/dao/test_ft_billing_dao.py
if the billing data was incorrect and needs to be rebuilt, we should remove old rows. Previously we were only upserting new rows, but old no-longer-relevant rows were staying in the database. This commit makes the flask command remove *all* rows for that service and day, before inserting the rows from the original notification data after.
This commit doesn't change the existing nightly task, nor does it change the upsert that happens upon viewing the usage page. In normal usage, there should never be a case where the number of billable units for a rate decreases. It should only ever increase, thus, never need to be deleted
> make rebuild-ft-billing-for-day remove unused rows

- migrations/versions/0210_remove_monthly_billing.py
Two migration files had the same number. This pull request fixes it.
> Fix migration version numbering

- manifest-delivery-base.yml
- runtime.txt
- tests/test_manifest_delivery_base.py
Celery prints its own stuff to stderr in a non-json format.
These get picked up by syslog drain and are shipped to
logstash together with the normal json-formatted logs resulting in
duplicate information and reducing the usability of the logs.
> Celery dev null

- app/aws/s3.py
- app/dao/notifications_dao.py
- app/dao/service_data_retention_dao.py
- app/letters/utils.py
- tests/app/celery/test_letters_pdf_tasks.py
- tests/app/dao/notification_dao/test_notification_dao.py
- tests/app/dao/notification_dao/test_notification_dao_delete_notifications.py
- tests/app/dao/test_service_data_retention_dao.py
- tests/app/letters/test_letter_utils.py
Update method to delete notifications that are a week old, to look at the days of retention set for the service.
If the service does not have the days of retention set, then use 7 days.
Added a method to get days of retention for a service and notificaiton type
> Use days of retention when deleting notifications in the nightly job.

- app/models.py
- migrations/versions/0212_remove_caseworking.py
What became ‘caseworking view’ is now available to all services.
***
Depends on:
> Remove caseworking permission

- requirements-app.txt
- requirements.txt
Brings in a fix for a bug in the email template:
https://github.com/alphagov/notifications-utils/pull/513
> Bump utils to 29.3.6

- app/dao/services_dao.py
- app/service/rest.py
- tests/app/dao/test_services_dao.py
- tests/app/service/test_service_data_retention_rest.py
Allows getting notification counts for a given number of days to support services with custom data retention periods (admin dashboard page should still display counts for the last 7 days, while the notifications page displays all stored notifications).
Admin app needs to get the service data retention for the specified notification type, so to avoid iterating through the list of all existing service data retention settings we restore the endpoint to get the individual data retention period.
> Get service data retention by notification type

- app/models.py
- migrations/versions/0213_brand_colour_domain_.py
- tests/app/email_branding/test_rest.py
There is a requirement for the colour of the banner to be different to the single id colour. In order to accomodate that we are adding two new columns for that data.
These columns will be updated manually and not done with a data migration.
A new column called domain has been added. This will be used as a default domain, if the user that creates the service has a matching domain this email brand will be set for the service.
This PR only adds the new columns to the model and db.
https://www.pivotaltracker.com/story/show/159660295
> New columns for EmailBranding.

- app/delivery/send_to_providers.py
- app/email_branding/email_branding_schema.py
- tests/app/db.py
- tests/app/delivery/test_send_to_providers.py
- tests/app/email_branding/test_rest.py
Add banner_colour, single_id_colour, and domain to email_branding_schema.
The Admin app can now be updated to send the new columns to update/create email_branding
> Add banner_colour, single_id_color and domain to email_branding.

- app/config.py
This header was introduced to ensure that no traffic was being
directed straight to the .cloudapps.digital domain. This was especially
useful for the non-production environments where access to the proper
domains is allowed for specific IP addresses while the cloudapps.digital
ones are open.
Moving to paas custom domains [1] will allow us to stop using the paas
proxies and, as a result, unbind the cloudapps.digital domain from our
apps.
This means that the X-Custom-Forwarder will become obsolete since all
our requests will be coming directly to our domain (albeit through
cloudfront) so any IP restriction can be implemented with a route
service [2].
1: https://docs.cloud.service.gov.uk/deploying_services.html#set-up-a-custom-domain-using-the-cdn-route-service
2: …
> Disable header check on preview

- app/delivery/send_to_providers.py
- migrations/versions/0217_default_email_branding.py
- tests/app/delivery/test_send_to_providers.py
https://www.pivotaltracker.com/story/show/159986276
We are now setting the type of branding on the branding itself, not on the service.
This PR switches over from looking in the old place (on the service) to looking in the new place (on the branding).
***
It also sets `brand_type` to `org` if it’s `null` so later we can:
- make it non-nullable
- remove `govuk` as an option
This migration is mostly for people’s local databases, the manual work here has been done on production already.
It’s already impossible to create a new branding without setting a value for `brand_type`.
> Look in email_branding for brand_type, not service 

- migrations/versions/0219_default_email_branding.py
Same as a0deef06e23e4c81e55d83afb63d4bbab1bdaaa5 but with `is null` not `= null` 🤦🏻‍
> Set branding_type to org if it’s none

- tests/app/dao/test_users_dao.py
I noticed there weren't any unit tests for the Users DAO create_secret_code function (used for generating 2FA codes I believe), so I thought I would add some. Feel free to suggest others that may be useful.
`make test` passed locally.
> Add unit tests for the Users DAO create_secret_code function

- app/celery/letters_pdf_tasks.py
- app/letters/utils.py
- tests/app/celery/test_letters_pdf_tasks.py
- tests/app/letters/test_letter_utils.py
Notify antivirus, on success, calls the process_virus_scan_passed task.
* update status to created (or delivered for test keys)
* copy the file from the scan bucket to either the live or test bucket based on the results
* delete the old file in the scan bucket
* download file from scan bucket
* sanitise PDF using new template-preview functionality
* if sanitise failed, set to new status "validation-failed" and save the pdf somewhere.
* send new pdf to live/test bucket
* update status to created (or delivered for test keys)
* delete the original file in the scan bucket
* download file from scan bucket
* sanitise PDF using new template-preview functionality
* if sanitise failed, just log.
* send OLD pdf to live/test bucket
* update status to created (or delivered for test keys)
* delete the …
> Sanitise precompiled pdfs after virus scan

- migrations/versions/0220_email_brand_type_non_null.py
We’ve already removed all the `null` values, and made it impossible to add new brandings with a `null` brand type.
Making it a database constraint just gives us extra safety.
> Make branding type non-nullable

- app/delivery/send_to_providers.py
- app/models.py
- app/schemas.py
- migrations/versions/0221_nullable_service_branding.py
- tests/app/dao/test_services_dao.py
- tests/app/db.py
- tests/app/delivery/test_send_to_providers.py
- tests/app/email_branding/test_rest.py
- tests/app/service/test_rest.py
We want to drop this column. First we have to stop using it anywhere.
Needs to be made nullable so we can insert/update services without having to write a value to it.
‘GOV.UK’ doesn’t make sense as a type of brand. It only made sense as a type of branding that a service had.
Since we’ve:
- deprecated the service branding column
- made sure it’s not used as a value in the email branding table
we can remove this value from the table of possible brand types.
This will affect 0 services on production:
```
=> select distinct(brand_type) from email_branding;
brand_type
------------
org
org_banner
both
(3 rows)
```
…but we still need to do it in case people have this value set in their local databases.
> Deprecate service branding and `govuk` brand type

- requirements-app.txt
- requirements.txt
Brings in:
---
Changes: https://github.com/alphagov/notifications-utils/compare/30.1.1...30.2.0
> Bump utils to start sending email preheaders

- app/dao/email_branding_dao.py
- app/email_branding/rest.py
- app/models.py
- migrations/versions/0223_add_domain_constraint.py
- tests/app/dao/test_email_branding_dao.py
- tests/app/email_branding/test_rest.py
Reverts https://github.com/alphagov/notifications-api/pull/2080
---
Also stops updating email branding domains with empty string values.
Columns with multiple `null`s can have a uniqueness constraint. Columns with multiple empty string values are not considered unique.
So this PR also:
- removes any duplicate empty string values
- casts empty strings to null string any time these columns are updated
> Add domain constraint 2

- app/celery/tasks.py
Fix problem with invalid seconds in the timestamp of the dvla response file.
We got a file that had 60 for the seconds in the timestamp, which is not valid (0-59). This ignores the seconds in the timestamp to get around that.
> Fix date conversion bug

- app/schemas.py
For the NotificationWithTemplateSchema exclude the scheduled_notifications so we do not query that table.
The scheduled_notifications is not used as of yet.
Also, I am not sure if this will improve the performance. But I do know this will not query scheduled_notifications for n notifications in the resultset
> Don't join to scheduled_notifications

- app/celery/letters_pdf_tasks.py
- app/celery/scheduled_tasks.py
- app/config.py
- app/dao/notifications_dao.py
- tests/app/celery/test_letters_pdf_tasks.py
- tests/app/celery/test_scheduled_tasks.py
- tests/app/dao/notification_dao/test_notification_dao.py
In this PR we remove trigger-letter-pdfs-for-day scheduled task and just call collate_letter_pdfs_for_day instead.
There was a datetime bug in the query which resulted in files not being sent to the postal provider.
The trigger-letter-pdfs-for-day task is no longer needed, so rather than fix the query just call collate_letter_pdfs_for_day directly.
Less code is always better.
Deployment considerations: I realized this is strictly not backwards compatible if the scheduled job is in progress and a task is on the queue that no longer exists. This is ok since we will deploy this well before 17:50.
> Remove trigger-letter-pdfs-for-day

- app/models.py
- tests/app/celery/test_tasks.py
Sets the updated_at to current time when the NotificationHistory is modified (which happens occasionally for example to set status to returned letter).
> Change NotificationHistory.updated_at on update

- app/celery/letters_pdf_tasks.py
This is because we can't tell when the letters are passing.
> Added an info log message when the precompiled pdf is successful.

- app/dao/services_dao.py
- app/models.py
- migrations/versions/0227_postage_constraints.py
- tests/app/dao/test_services_dao.py
Added constraints to services.postage: not nullable and can only constraint "first" or "second".
I've removed the default values from services_dao.create_service and update_service, because the constraint will take care of that.
> Add constraints to services.postage

- manifest-api-base.yml
This was introduced in #1811 as a way to avoid sending traffic to newly
created apps where gunicorn had not started yet, such as the case during
a scaling event. These days we depend mostly on scheduled scaling and we
rarely need to scale above the scheduled values.
Yesterday we had an event where (during a traffic spike) the healthcheck
failed causing the instance to be killed and sending a 5XX response code
to all the connections that this instance was handling at the time.
However, this instance was not unhealthy and was serving traffic. The
problem stems from a combination of using async workers, having to limit
the number of database connections and a thread holding onto a db
connection for the entire duration of the request.
Specifically, we end up having requests queued up in …
> Remove http healthcheck for api instances

- app/config.py
- app/dao/fact_billing_dao.py
- migrations/versions/0226_new_letter_rates.py
- migrations/versions/0229_new_letter_rates.py
- tests/app/celery/test_reporting_tasks.py
- tests/app/dao/test_ft_billing_dao.py
Work done:
- insert new rates into the letter_rates table
- use post_class to filter the rates, for now hard-coded as second class
- update existing tests
- write a test for filtering by post_class
- in config, move inbound MMG credentials for local environment from Test class to Development class
- TODO: tests for filtering rates by start date
Pivotal ticket: https://www.pivotaltracker.com/story/show/160229653
> Introduce new letter rates, valid from 01.10.2018

- app/models.py
- migrations/versions/0230_noti_postage_constraint.py
- tests/app/celery/test_reporting_tasks.py
- tests/app/performance_platform/test_total_sent_notifications.py
- tests/app/test_model.py
A not valid constraint only checks against new rows, not existing rows. We can call VALIDATE CONSTRAINT against this new constraint to check the old rows (which we know are good, having run the command from 7496178). Adding a normal constraint acquires an ACCESS EXCLUSIVE lock, but validate constraint only needs a SHARE UPDATE EXCLUSIVE lock.
see 9d4b896 and 0a50993 for more information on marking constraints as not valid.
> Postage constraint

- app/celery/tasks.py
- tests/app/celery/test_ftp_update_tasks.py
Sometimes the page counts from DVLA do not match our page counts. Our counts have always been right. This PR does not update notification with the DVLA page count but does still let us know the difference happened.
> Do not update billable_units if page count does not match postal provider

- requirements-app.txt
- requirements.txt
awscli has a requirement of a new version of botocore
moto has a requirement of an old version of boto3, which requires an
old version of botocore
We had to pin boto to an older version, because of the moto issues.
this commit pins awscli to the version currently deployed on prod, so
that it plays nice with that older version of boto/botocore
> fix awscli botocore dependency

- migrations/versions/0233_updated_first_class_dates.py
We want to bring the start dates for first class letter rates forward by
a month so that we don't see billing errors when sending first class letters now.
(The feature will still go live at the planned time - this is to let us test things
beforehand.)
> Update first class letter rate start dates

- tests/app/celery/test_reporting_tasks.py
Removed the occasionally failing test to check how ft_billing upserts postage data. This test will be re-added soon once the postage column has been added to the primary key.
> Remove test

- app/dao/fact_billing_dao.py
- app/models.py
- migrations/versions/0235_add_postage_to_pk.py
- tests/app/celery/test_reporting_tasks.py
Added a migration to make the `postage` column part of the composite primary key for the `ft_billing` table. There should be no null values in the postage column since this column was backfilled in a previous migration.
Also started to use the real postage data when inserting rows into `ft_billing`, instead of hard-coding 'second'.
[Pivotal story](https://www.pivotaltracker.com/story/show/160660570)
> Add postage to ft_billing primary key

- app/billing/billing_schemas.py
- app/dao/fact_billing_dao.py
- tests/app/billing/test_billing.py
- tests/app/dao/test_ft_billing_dao.py
We were already returning the month, notification_type, billing_units and rate from the /monthly-usage billing endpoint. This adds in the postage too so that we can display postage details on the usage page of notifications-admin.
[Pivotal story](https://www.pivotaltracker.com/story/show/160660570)
> Return postage from the monthly-usage endpoint

- app/models.py
- migrations/versions/0237_add_filename_to_dvla_org.py
Added a filename column to the `dvla_organisation` table and populated it
with the filenames that are currently hard-coded in template-preview.
The filenames for letter logos are going to be stored in the database,
instead of in template-preview.
[Pivotal story](https://www.pivotaltracker.com/story/show/159991865)
> Add filename to dvla_organisation table

- app/schemas.py
- tests/app/service/test_rest.py
Added the filename of a service's letter logo to the service schema. We want
this in the schema so that it is possible to call `current_service.letter_logo_filename`
from notifications-admin and to pass this value through to template-preview.
[Pivotal story](https://www.pivotaltracker.com/story/show/159991865)
> Update service schema to add letter_logo_filename

- app/celery/letters_pdf_tasks.py
- app/template/rest.py
- tests/app/celery/test_letters_pdf_tasks.py
We now pass `filename`, the filename of the letter logo to use, through
to Template Preview in addition to the `dvla_org_id`. Once Template
Preview has been updated to only use the `filename` we will stop
sending the `dvla_org_id`.
[Pivotal story](https://www.pivotaltracker.com/story/show/159991865)
> Send letter filename to template preview

- requirements-app.txt
- requirements.txt
Brings in accessibility fixes for the email template:
https://github.com/alphagov/notifications-utils/pull/542
> Bump utils to 3.5.5

- app/celery/letters_pdf_tasks.py
- app/celery/service_callback_tasks.py
- app/celery/tasks.py
it includes task args, which might contain PII. And we don't need to know where the retry exception came from - it came from the line above
> don't log exception info for retries

- requirements-app.txt
- requirements.txt
itsdangerous v1 uses sha512 instead of sha1 to sign and unsign its strings. Pin to 0.24 until we figure a migration plan, since it's used in a few places (In the DB, in email tokens, and sending blobs to celery at least).
> pin itsdangerous to v0.24

- app/celery/service_callback_tasks.py
- app/dao/notifications_dao.py
- app/notifications/process_client_response.py
- tests/app/dao/notification_dao/test_notification_dao.py
- tests/app/notifications/test_process_client_response.py
- Updated notifications_dao.update_notification_status_by_id with an optional parameter to set the sent_by, this will eliminate a separate update to notifcaitons.
- Added the callback url to the log message, that way we can see if it's the same url failing.
- Stop sending the status callbacks for PENDING status.
> Some minor refactoring

- app/models.py
- migrations/versions/0239_add_edit_folder_permission.py
This is a temporary permission to allow some services to see and edit folders before the feature is turned on for everyone.
[Pivotal story](https://www.pivotaltracker.com/story/show/161176936)
> Add edit_folders service permission

- app/models.py
- migrations/versions/0240_dvla_org_non_nullable.py
If either of these fields are null, previewing a letter template now won't work.
[Pivotal story](https://www.pivotaltracker.com/story/show/159991865)
> Make name and filename fields of DVLAOrganisation non-nullable

- app/__init__.py
- app/dao/template_folder_dao.py
- app/models.py
- app/schema_validation/definitions.py
- app/template_folder/rest.py
- app/template_folder/template_folder_schema.py
- tests/app/db.py
- tests/app/template_folder/test_template_folder_rest.py
* create template folder
* rename template folder
* get list of template folders for service (not nested/presented in any
particular way)
* delete template folder
Also removed `lazy=dynamic` from the `template_folder.templates` relationship. lazy=dynamic returns a query object (which you can then filter further). We just want to return the entire fetched list, at least for now.
> add template folder CRUD

- app/notifications/process_notifications.py
- app/service/send_notification.py
- tests/app/notifications/test_process_notification.py
- tests/app/service/test_send_one_off_notification.py
This pull request modifies the code paths the admin app uses to send one off emails and text messages to also accept letters.
It seems to work running locally, but I could do with some help to:
- check it’s doing all the required tasks/database updates
- write some good tests (all I’ve done is modify the existing ones so they pass)
> Allow the admin app to send one-off letters

- app/dao/fact_notification_status_dao.py
- app/service/rest.py
- tests/app/dao/test_fact_notification_status_dao.py
- tests/app/service/test_rest.py
- tests/app/service/test_statistics_rest.py
Pivotal ticket: https://www.pivotaltracker.com/story/show/161176498
We spotted an issue recently: big blue statistics on the service dashboard have been showing numbers that are slightly off for services with default data retention policy (7 days), and completely off if retention policy was changed to a shorter period.
This is because:
- when it comes to retention policy of 7 days or more, the cause is in time zones mix up when querying Notification table. So the query did not cover the first hour of the 7 days period or something like that.
- when it comes to retention policy period shorter than 7 days, querying Notification table would always give us only those notifications that are within the retention period, so less than seven days.
To mitigate those issues, we decided to query …
> Fix notification statistics on dashboard

- app/dao/template_folder_dao.py
- app/template_folder/rest.py
- tests/app/template_folder/test_template_folder_rest.py
Since template folders are only linked by ID to their parent we need to check that the parent folder belongs to the same service as the one being created. Otherwise, admin users could modify parent ID to create a folder outside their service.
Ideally, this check would be performed by a DB constraint, but since parent_id can be nullable this is only possible to express using DB triggers.
Instead, we perform the check in the API endpoint code.
Currently there aren't any permission checks based on folder IDs in the admin app or the API, so it's possible for a user to modify the folder ID to perform operations on folders outside their service.
Our usual way to avoid this is to always use service_id filter when fetching objects from the database.
> Check parent folder belongs to the same service

- app/dao/templates_dao.py
- app/models.py
- app/schema_validation/__init__.py
- app/template/rest.py
- app/template/template_schemas.py
- requirements-app.txt
- requirements.txt
- tests/app/template/test_rest.py
- Using jsonschema for create_template. Updated jsonschema to Draft7, this allowed a conditional validation on subject, if template_type == 'email' or 'letter' then subject is required.
This version is backward compatible with Draft4.
When creating TemplateRedacted, I've built the dict depending on if the created_by or created_by_id exists.
- Update model and controller to handle parent_folder_id when creating a template. If the parent_folder_id then check if the folder exists and is for the same service. If it is add the folder to the template model object, the relationship will be persisted when the template is saved. If the folder does not exist or is for a different service, then return a ResultNotFound error.
> Add parent id for create template

- app/celery/reporting_tasks.py
- app/commands.py
- app/config.py
- app/dao/fact_notification_status_dao.py
- tests/app/celery/test_reporting_tasks.py
We spotted a discrepancy in how the ft_notification_status table is updated. New records for a day were overwriting on top of older version of data for that date. Hence, if a pending notification has failed on a different date, it was not overwritten but recorded as a separate event and hence it was in the table twice. 
This pull request fixes that problem by:
- rearranging nightly tasks
- updating 'create_nightly_notification_status' task to include 4 days worth of data
- changing the way data in ft_notification_status table gets updated (now we delete the old version of data before we update the table with new version of data)
- updating existing records in the table
> Rearrange nightly tasks and update ft_notification_status table

- app/dao/templates_dao.py
- tests/app/dao/test_templates_dao.py
When a template is archived, it should no longer belong to any folder.
If we don’t do this it will make it very hard to delete folders later
(because folders can only be deleted if they have no templates or folders
inside them).
We originally tried to check if the link between a template and folder
should be removed with
`if template.archived and template.folder:`
instead of using `if template.archived:`. However, this caused issues
because checking `template.folder` flushes the session. Since the
session is no longer dirty, the versioning decorator doesn't work as
expected and doesn't create a new row in `TemplateHistory`.
> Remove relationship to folder when archiving a template

- app/models.py
- app/template_folder/rest.py
- app/template_folder/template_folder_schema.py
- scripts/run_tests.sh
- tests/app/db.py
- tests/app/template_folder/test_template_folder_rest.py
- tests/app/test_model.py
new endpoints:
/services/<service_id>/move-to-folder
/services/<service_id>/move-to-folder/<target_template_folder_id>
* takes in a dict containing lists of `templates` and `folders` uuids.
* sets parent of templates and folders to the folder specified in the
URL. Or None, if there was no id specified.
* if any template or folder has a differen service id, then the whole
update fails
* if any folder is an ancestor of the target folder, then the whole
update fails (as that would cause a cyclical folder structure).
* the whole function is wrapped in a single `transactional` decorator,
so in case of error nothing will be saved.
> Move folders and templates to other folders

- app/celery/tasks.py
- tests/app/celery/test_tasks.py
Deleted unused parameters from the save_email and save_sms jobs - These both had default arguments of `api_key_id` and `key_type` which were never being passed in.
Started passing `sender_id` to the `save_email`, `save_sms` and `process_job` tasks, with a default value of `None`. If `sender_id` is provided, the `save_email` and `save_sms` tasks will use it to determine the reply-to email address or the SMS sender for the notifications in the job. The `process_job` task will start using the value in another commit.
[Pivotal story](https://www.pivotaltracker.com/story/show/161176428)
> Pass sender_id argument to tasks

- app/celery/tasks.py
- app/job/rest.py
- tests/app/celery/test_tasks.py
- tests/app/job/test_rest.py
The `save_email` and `save_sms` jobs were updated previously to take an
optional `sender_id` and to use this if it was available. This commit
now gets the `sender_id` from the S3 metadata if it exists and passes it
through the the tasks which save the job notifications. This means SMS
and emails sent through jobs can use a specified `sender_id` instead of
the default.
[Pivotal story](https://www.pivotaltracker.com/story/show/161176428)
>  Get and use sender_id from S3 metadata

- app/template_folder/rest.py
- app/template_folder/template_folder_schema.py
- tests/app/template_folder/test_template_folder_rest.py
It was initialy called "rename" which does not comply with
RESTful CRUD (create, update, read, delete) naming practice.
We remove the 'rename' operation in favour of template folder
resource update endpoint as it allows us to extend it with other
attributes.
> Change name of update method for template folder

- app/notifications/validators.py
- app/utils.py
- tests/app/v2/notifications/test_post_letter_notifications.py
- tests/app/v2/notifications/test_post_notifications.py
Update the error message when a service does not have permission to send a notification type.
> Update error message to be more descriptive

- app/letters/utils.py
- tests/app/letters/test_letter_utils.py
use the same function that we use when uploading, to ensure consistency (that fn is also well tested already)
> look in correct bucket for letters sent after 5:30pm

- app/notifications/validators.py
- requirements-app.txt
- requirements.txt
Brings in changes from https://github.com/alphagov/notifications-utils/pull/553
Services reaching rate limits are triggering our alerts and make it hard to find actual exceptions in the logs.
As far as the API is concerned this is not an exceptional state, so we shouldn't log it as such.
> Lower service rate limit log level to INFO

- app/__init__.py
By default, SQLAlchemy will start a transaction with an
existing connection without checking that the connection
is still valid.
Enabling "pre-ping" makes the ORM send a `SELECT 1` when
acquiring a connection, which should help avoid some errors
caused by connections breaking during a DB failover.
The added statement has a constant overhead for all transactions,
so we should only keep it enabled when we're planning to switch
or upgrade the database server.
https://docs.sqlalchemy.org/en/latest/core/pooling.html#disconnect-handling-pessimistic
> Enable pessimistic DB connection disconnect handling

- app/service/send_notification.py
- tests/app/service/test_send_one_off_notification.py
Letters should always have a reference, because that’s what DVLA use to tell us when they’ve sent a letter.
If a letter has a reference of `None` then DVLA say they’ve sent a letter with a reference of `'None'`. This means we can never reconcile the letter, which means it stays in `created`, which means it never
gets billed.
We don’t think this has affected any real letters yet, just ones that we’ve sent as tests.
> Add reference to one off letters

- app/models.py
- tests/app/job/test_rest.py
- tests/app/test_model.py
- Add sender email on `serialize_for_csv` method on Notification class
- change date formatting on the same method so it is more machine-readable while still remaining human-readable
- Update tests accordingly
PR that uses those changes on admin: https://github.com/alphagov/notifications-admin/pull/2565
Pivotal ticket: https://www.pivotaltracker.com/story/show/162310203
> Add sender email and change date formatting on Notification's serialize_for_csv

- app/dao/notifications_dao.py
We are adding an index to Notifications to optimize the get_notifications_for_service. We need to build the index concurrently which can not be run inside a transaction block so the index will need to be run on the db directly.
CREATE INDEX CONCURRENTLY ix_notifications_service_created_at ON notifications (service_id, created_at);
DROP INDEX CONCURRENTLY ix_notifications_service_created_at
> Remove the join to TemplateHistory.

- app/celery/scheduled_tasks.py
- app/dao/notifications_dao.py
- tests/app/celery/test_scheduled_tasks.py
Work done:
- uncomment the code that actually switches providers
- log the ratio of slow notifications each time it is checked and there are any notifications
This is a 2nd pull request for this story: https://www.pivotaltracker.com/story/show/162170074
This was the 1st PR: https://github.com/alphagov/notifications-api/pull/2250
> Switch providers on slow delivery goes live

- app/dao/fact_notification_status_dao.py
- app/dao/notifications_dao.py
- app/platform_stats/rest.py
- tests/app/dao/notification_dao/test_notification_dao.py
- tests/app/dao/test_fact_notification_status_dao.py
- tests/app/platform_stats/test_rest.py
This change will allow platform admin users to query the platform-admin page for historical data. At the moment the query times out for a big date range.
> Improve performance of platform stats page

- migrations/versions/0246_notifications_index.py
Add an index on notifications for (service_id, created_at) to improve the performance of the notification queries.
We've already performed this update on production since you need to create the index concurrently, which is not allowed from the alembic script. For that reason we are checking if the index exists.
> New index for  notifications

- app/dao/fact_notification_status_dao.py
- app/dao/jobs_dao.py
- app/job/rest.py
- tests/app/conftest.py
- tests/app/dao/test_fact_notification_status_dao.py
- tests/app/dao/test_jobs_dao.py
- tests/app/db.py
- tests/app/job/test_rest.py
the dashboard gets a list of all jobs. for each job, it gets the statistics of which notifications have been used. Previously this would go to the `notification_history` table, separately for each job. We can look at the ft_notifiation_status stats table instead, going to notifications table for jobs that are still active
read commit by commit to separate my large test refactors (to stop using conftest fixtures as functions) from my code changes (all in the last commit)
> stop dashboard reading notification_history

- app/job/rest.py
- tests/app/job/test_rest.py
otherwise scheduled jobs will be viewed as old, and we'll pull stats from the statistics tables, even if they might have not even started yet
> base job start of processing_started rather than created_at

- app/celery/letters_pdf_tasks.py
- tests/app/celery/test_letters_pdf_tasks.py
We want to send two new headers, `ServiceId` and `NotificationId` to the
template preview `/precompiled/sanitise` endpoint. This is to allow us to log
errors from this endpoint in template preview with all the information needed,
instead of needing to pass the information back to notifications-api and
to log it there.
Part of [this pivotal story](https://www.pivotaltracker.com/story/show/162310239)
> Send extra headers to Template Preview /precompiled/sanitise endpoint

- app/notifications/process_notifications.py
- app/template/rest.py
- app/template/template_schemas.py
- app/v2/template/template_schemas.py
- tests/app/conftest.py
- tests/app/dao/test_templates_dao.py
- tests/app/db.py
- tests/app/notifications/test_process_notification.py
- tests/app/template/test_rest.py
- tests/app/v2/notifications/test_post_letter_notifications.py
Work done:
- Don't allow to set postage per template if no service permission
- Choose postage when persisting a notification
- Update v2 template schema to include postage
- Include postage in checking if template changed
Pivotal ticket: https://www.pivotaltracker.com/story/show/160231772
> Choose postage on template

- app/dao/notifications_dao.py
- app/notifications/notifications_ses_callback.py
- app/notifications/process_client_response.py
Previously, we logged a warning containing the notification reference and new status. However it wasn't a great message - this new one includes the notification id, the old status, the time difference and more.
This also separates out logs for callbacks for notifications we don't know (error level) and duplicates (info level).
> log more info when we receive multiple delivery callbacks

- app/dao/fact_notification_status_dao.py
- app/service/rest.py
- app/service/statistics.py
- tests/app/service/test_statistics.py
a query for notifications was filtering on FtNotificationStatus - we aren't joining to that table in the query, so sqlalchemy added a cross join between ft_notification_status (3.7k rows) and Notifications (3.9m rows), resulting in a 1.3 trillion row materialised table. This query took 17 hours and pending.
Also, remove orders from querys other than the outer one, since we're grouping anyway.
now that we're reading from two tables (ft_notification_status and notifications) for stats, we'll get a couple of rows for each notification type. If a service doesn't have any rows in one of those tables, the query will return a row with nulls for the notification types and counts. Some services will have history but no stats from today, others will have data from today but no history.
This commit …
> Platform admin fix

- app/dao/notifications_dao.py
- app/schemas.py
- app/service/rest.py
- requirements-app.txt
- requirements.txt
- tests/app/dao/notification_dao/test_notification_dao.py
- tests/app/service/test_rest.py
Flask-SQLAlchemy paginate function issues a separate query to get the total count of rows for a given filter. This query (with filters used by the API integration Message log page) is slow for services with large number of notifications.
Since Message log page doesn't actually allow users to paginate through the response (it only shows the last 50 messages) we can use limit instead of paginate, which requires passing in another flag from admin to the dao method.
`count` flag has been added to `paginate` in March 2018, however there was no release of flask-sqlalchemy since then, so we need to pull the dev version of the package from Github.
> Don't return pagination links for API Message log requests

- app/service/statistics.py
- tests/app/service/test_statistics.py
Pivotal ticket: https://www.pivotaltracker.com/story/show/162310324
> Cancelled notifications don't show as failures in statistics

- app/celery/tasks.py
- app/notifications/process_letter_notifications.py
- app/notifications/process_notifications.py
- app/notifications/rest.py
- app/schema_validation/__init__.py
- app/service/send_notification.py
- app/v2/notifications/notification_schemas.py
- tests/app/notifications/test_process_notification.py
- tests/app/service/test_send_one_off_notification.py
- tests/app/v2/notifications/test_post_letter_notifications.py
This PR enables adding optional 'postage' attribute to a POST request to 'post_precompiled_letter_notification' endpoint and sets notification postage based on this attribute if it's present. The attribute value needs to be either 'first' or 'second'.
Pivotal ticket: https://www.pivotaltracker.com/story/show/160231957
> Choose postage on POST request for precompiled letters

- app/dao/services_dao.py
- tests/app/dao/test_services_dao.py
Remove dao_fetch_monthly_historical_stats_by_template, a query using NotificationHistory that is no longer used.
> Remove unused query

- manifest-delivery-base.yml
- scripts/run_multi_worker_app_paas.sh
In 4427827b2ff7cc790d1e3400a9eeca7b8c22b991 and celery monitoring was
changed from using PID files to actually looking at processes.
If celery workers get OOM killed (for instance) the container init
script would not restart them, this is because `get_celery_pids` would
not contain any processes that contained the string celery. This would
cause the pipe to fail (-o pipefail). APP_PIDS would not get updated but
the script would continue to run. This caused the script to not restart
the celery processes.
We think the correct behaviour when celery processes are killed (i.e.
there are no more celery processes running in a container) is to kill
the container. The PaaS should then schedule new ones which may
remediate the cause of the celery processes being killed.
Upon detection of no celery …
> Exit if celery processes are not running

- manifest-api-base.yml
- manifest-delivery-base.yml
They are the busiest services and if we don't deploy often to rotate
them they tend to fill their disk space.
> Bump available disk space for API, sender and receipts workers

- app/dao/services_dao.py
- tests/app/dao/test_services_dao.py
- tests/app/service/test_rest.py
Step 1 of 2 of turning on folders for all services.
We think it’s a feature which will be useful for the majority of services, and we think we’ve done enough research to know that it’s mature enough to release to all services.
***
Depends on:
> Give folders to new services by default

- app/dao/notifications_dao.py
When we get a callback from SES, we identify the notification by the SES reference that we set on the notification after sending. When we wrote the log message, we assumed that we'd always have a notification for every callback, so if one couldn't be found we would raise an error log. This isn't the case for a few reasons:
* We might receive a callback before the sender worker has persisted the reference to the database.
* We might have deleted the notification, especially if the service has a short data retention period
* We sometimes receive callbacks for references that we have no record of whatsoever (this is quite alarming but we don't know why this happens)
The error logs were happening pretty frequently, and we don't have a real way to solve them at the moment, so lets cut down on …
> downgrade error to info for notification not found for callback

- app/utils.py
- app/v2/template/template_schemas.py
- tests/app/v2/template/test_post_template.py
- tests/app/v2/template/test_template_schemas.py
If you’re trying to show what a Notify email will look like in your caseworking system all the API gives you at the moment is raw markdown (with the placeholders replaced).
This isn’t that useful if your caseworkers have no idea what markdown is. If we also give teams the HTML then they can embed this in their systems, and the people using those systems will be able to see how headings, bulleted lists, etc. look.
***
The first users of this are working in Java. They’ve said they’re happy to update the client to add this new field.
> Return rendered HTML when previewing a template

- app/dao/letter_branding_dao.py
- tests/app/service/test_rest.py
when creating a service, the api accepts a `service_domain` field that it uses to populate the letter branding - if the service domain is known to match an existing letter branding option, use that
automatically. However, the admin currently doesn't know about this field yet so doesn't pass anything through - the api erroneously searches the DB for letter branding with a domain of None - which they currently all have.
This meant that when services were created, their letter branding was set to the most recent row in the DB (that matched None).
> fix new services being assigned to wrong letter branding

- app/dao/templates_dao.py
When this method was invoked, 'postage' value disappeared from TemplateHistory for template it was invoked for. This PR fixes it.
> dao_update_template_reply_to maintains postage in TemplateHistory

- app/celery/letters_pdf_tasks.py
- app/schemas.py
- app/template/rest.py
- tests/app/celery/test_letters_pdf_tasks.py
- tests/app/service/test_rest.py
- tests/app/template/test_rest.py
The template preview app now accepts a null value for the `filename` parameter. If a service doesn't have a letter branding option set,  previously we defaulted to their dvla_organisation (probably HM  Government). Now, we pass through None, so that we generate letters without any logo or branding.
Tested by checking file on s3.
> Don't fallback to dvla_organisation if letter branding unset

- app/models.py
- migrations/versions/0260_service_volumes.py
- migrations/versions/0261_service_volumes.py
- tests/app/service/test_rest.py
When a service go live we ask people for their estimated sending volumes. At the moment we only put this in the ticket, and store it in a spreadsheet.
This means that a service can
- say they want to go live
- say they are sending 100,000 emails per year
- not have created any email templates
- still see ‘create templates’ as ‘completed’ in the go live checklist
If we store this data against the service we can collect it earlier, and then use it to determine automatically what kind of templates the user needs to create before their go live checklist can be considered complete.
> Add fields to record a service’s estimated volumes

- migrations/versions/0262_remove_edit_folders.py
Removing a permission that easy, made a little more difficult by the redis cache on the admin app. 
This PR removes all the edit_folder permissions in the service_permission table. 
NOTE: is has followed on from the previous branch only change here is the migration file.
> Remove edit folder permission

- app/celery/scheduled_tasks.py
- app/dao/notifications_dao.py
- tests/app/dao/notification_dao/test_notification_dao.py
Currently we switch if:
* status = delivered and updated_at - sent_at > threshold
* status = sending and now - sent_at > threshold
firetext can leave notifications in the pending state, which is
equivalent to sending in terms of how we should handle it, so this
commit changes the second case to allow pending as well as sending.
> allow pending notifications to influence switchover.

- app/celery/process_ses_receipts_tasks.py
- app/notifications/notifications_ses_callback.py
- tests/app/celery/test_process_ses_receipts_tasks.py
- tests/app/notifications/test_notifications_ses_callback.py
We've seen errors caused by what we suspect is a race condition when
SES callback processing tries to look up the notification before the
sender worker has saved notification reference from the SES POST
response to the database.
This adds a retry for SES callback task if the notification was not
found and the message is less than 10 minutes old and removes the
error log message for notifications older than 3 days (since they
might no longer exist in the notifications table and would've been
marked as failure by then either way).
In order to be able to call retry and silence the error log based on
notification time this change inlines `process_ses_response` and
`update_notification_by_reference` functions into the celery task.
It also removes a lot of defensive error-handling that doesn't …
> Add retries for SES callbacks for recent notifications

- app/celery/process_ses_receipts_tasks.py
Celery `self.retry` raises an exception to communicate that the task
needs to be retried. Since our ses task is wrapped in a catch-all
except block it logs that exception as an error before retrying.
Handling Retry class separately allows us to raise it without logging
the traceback.
> Allow retry exception to propagate from ses callback task

- app/celery/scheduled_tasks.py
- app/dao/notifications_dao.py
provider switching is a process that can happen as often as we like without disrupting the flow of the system - however, there are some reasons why we might not want to switch. One problem we've seen is when a provider is having an issue, we might switch away from them manually only for the app to automatically switch back to them again and again.
Long term we'd like to have a system better suited for sharing the load equally between our two sms providers, but short term, by increasing the threshold for switching from 10% (of messages sent are slow) to 20%, we hope to make switching happen less often.
A notification is considered slow if it was sent in the last ten minutes, on the current provider, and is either
* still in sending or pending after 4 minutes
* in delivered, but took at …
> move slow sms provider threshold from 10% to 20%

- app/user/rest.py
- tests/app/user/test_rest.py
The data posted to the `set_permissions` endpoint is currently sent as a list of permissions:
`[{'permission': MANAGE_SETTINGS}, {'permission': MANAGE_TEMPLATES}]`.
This endpoint is going to also be used for both `permissions` and `user_folder_permissions`, so the data now needs to be nested:
`{'permissions': [{'permission': MANAGE_SETTINGS}, {'permission': MANAGE_TEMPLATES}]}`
This changes the `set_permissions` endpoint to accept data in either format. Once admin is sending data in the new format, the code here can be updated to only accept data in the new format.
> Change permissions endpoint to accept data in new format

- app/celery/letters_pdf_tasks.py
- app/config.py
- app/v2/notifications/post_notifications.py
antivirus is sometimes tough to get running locally - now in dev antivirus is skipped unless `ANTIVIRUS_ENABLED=1` is set on the command line. on all other environments it is always enabled.
> stub out antivirus in dev

- app/dao/service_user_dao.py
- app/dao/services_dao.py
- app/models.py
- app/user/rest.py
- app/user/users_schema.py
- migrations/versions/0266_user_folder_perms_table.py
- tests/app/dao/test_services_dao.py
- tests/app/dao/test_template_folder_dao.py
- tests/app/template_folder/test_template_folder_rest.py
- tests/app/user/test_rest.py
* Added a `user_folder_permissions` table which contains the `service_id`, `user_id` and `template_folder_id`. Also changed the `user_to_service` mapping table into a model, `ServiceUser`, since we're often only interested in the users for a given service.
* Allow user folder permissions to be updated
* Include list of `users_with_permission` in all folders response
* Delete user folder permissions when a user is removed from a service
[Pivotal story](https://www.pivotaltracker.com/story/show/164050120)
> Add user folder permissions

- app/models.py
- migrations/versions/0277_consent_to_research_null.py
- tests/app/service/test_rest.py
It should be nullable so we can tell whether someone has answered the question already or not.
No real users have entered data into this column yet, so it’s fine to wipe it.
> Make `consent_to_research` nullable

- app/celery/process_ses_receipts_tasks.py
- tests/app/celery/test_process_ses_receipts_tasks.py
The timestamps available in the SES receipt don't always correspond
to the time the notification has been sent. We've seen callbacks with
a current timestamp in both 'mail' and 'bounce' objects that referenced
a notification sent a week ago, which means we can't rely on it to skip
archived notifications.
One possible approach would be to look up the notification reference in
the notification_history table, but this goes against our plans to stop
relying on it in the future.
This changes the SES receipts logic to retry missing notifications once
(if the callback timestamp is within the last 5 minutes the task will
retry after a 5 minute delay) to capture callbacks arriving before the
notification reference has been persisted to the DB. Otherwise, we log
the missing notification as a …
> Downgrade log level for missing notifications in SES receipt

- app/celery/nightly_tasks.py
- app/dao/inbound_sms_dao.py
- app/dao/notifications_dao.py
- tests/app/celery/test_nightly_tasks.py
- tests/app/dao/notification_dao/test_notification_dao.py
- tests/app/dao/notification_dao/test_notification_dao_delete_notifications.py
- tests/app/dao/test_inbound_sms_dao.py
- tests/app/db.py
previously would always delete after 7 days. Now it looks at your services' data retention. Similar to how we delete notifications
* get all custom SMS data retention for services with an `inbound_number`
* for each service: delete inbound_sms where older than days of retention and service_id matches
* delete all inbound SMS where service_id isn't in the list above, and is older than 7 days
also renamed some functions so they don't refer to 7 days so we don't forget about retention in future 🤞
> Inbound sms now deletes according to data retention

- app/dao/organisation_dao.py
- app/dao/services_dao.py
- app/models.py
- migrations/versions/0278_add_more_stuff_to_orgs.py
- tests/app/dao/test_organisation_dao.py
- tests/app/dao/test_services_dao.py
- tests/app/db.py
- tests/app/organisation/test_rest.py
- tests/app/service/test_rest.py
Currently we have
- a thing in the database called an ‘organisation’ which we don’t use
- the idea of an organisation which we derive from the user’s email address and is used to set the default branding for their service and determine whether they’ve signed the MOU
We should make these two things into one thing, by storing everything we know about an organisation against that organisation in the database. This will be much less laborious than storing it in a YAML file that needs a deploy every time it’s updated.
An organisation can now have:
- domains which we can use to automatically associate services with it (eg anyone whose email address ends in `dwp.gsi.gov.uk` gets services they create associated to the DWP organisation)
- default letter branding for any new services
- default …
> Use ‘organisations‘ table to store info about organisations (not YAML)

- app/models.py
- migrations/versions/0278_remove_fk_to_users.py
- migrations/versions/0279_remove_fk_to_users.py
The relationship is not used and it prevents us from deleting users. It would be good to delete users that are never activated.
> Removing the foreign from to users from Notification_history.

- app/dao/service_user_dao.py
- app/template_folder/rest.py
- tests/app/template_folder/test_template_folder_rest.py
If the new folder has a parent folder, it inherits user permissions
from its parent. Else if the new folder is at root level, all users
will have a permission to view it.
Pivotal ticket: https://www.pivotaltracker.com/story/show/164050421
> Set user permissions when creating a folder

- app/dao/services_dao.py
When triggered by an admin request `dao_remove_user_from_service`
raised an IntegrityError since the user_to_service delete query was
issued before the folder permissions one, violating the foreign key
constraint on the folder permissions table.
For some reason this isn't caught by the tests in test_services_dao
that check that folder permissions are removed properly.
> Change dao_remove_user_from_service query to avoid IntegrityError

- app/service/rest.py
couldn't think of a good way to test it because the problem was it was suppressing actual 500 internal server errors
> fix constraint name check in service error handler

- app/celery/scheduled_tasks.py
make it less likely to switch on slow messages to allow more manual control of provider balance
> lower provider switch threshold from 20% to 30%

- app/service/rest.py
- tests/app/service/test_rest.py
The data posted to the `add_user_to_service` endpoint is currently sent as a list of permissions:
`[{'permission': MANAGE_SETTINGS}, {'permission': MANAGE_TEMPLATES}]`.
This endpoint is going to also be used for folder permissions, so the data now needs to be nested:
`{'permissions': [{'permission': MANAGE_SETTINGS}, {'permission': MANAGE_TEMPLATES}]}`
This changes the `add_user_to_service` endpoint to accept data in either format. Once admin is sending data in the new format, the code can be simplified.
Part 1 of this [Pivotal story](https://www.pivotaltracker.com/story/show/163756170)
> Allow add_user_to_service endpoint to accept new data format

- app/celery/letters_pdf_tasks.py
- tests/app/celery/test_letters_pdf_tasks.py
previously ftp would name the files itself by giving them a timestamp when uploading. we ran into issues with tasks being picked up multiple times and as such, uploading duplicate files. By naming the file before creating the task, we can avoid this issue.
Files are now named `NOTIFY.YYYY-MM-DD.###.ZIP` where the number is a counter that increments with each task we've issued in that run of collate-letter-pdfs-for-day
> pass upload filename to notify-ftp

- app/celery/letters_pdf_tasks.py
- tests/app/celery/test_letters_pdf_tasks.py
if we partially retry a day, we would create new zip files, containing different letters (if some were processed succesfully). We need these files to have different filenames to earlier zip files so that we can avoid overwriting log data in zips_sent.
Hashing the filename means that we'll only overwrite if it was the same file containing the same content.
> add a hash of letter filenames to the dvla zip file name

- app/dao/services_dao.py
- app/dao/template_folder_dao.py
- app/models.py
- app/schemas.py
- app/service/rest.py
- migrations/versions/0280_invited_user_folder_perms.py
- tests/app/accept_invite/test_accept_invite_rest.py
- tests/app/conftest.py
- tests/app/dao/test_invited_user_dao.py
- tests/app/dao/test_services_dao.py
- tests/app/db.py
- tests/app/invite/test_invite_rest.py
- tests/app/service/test_rest.py
This is a JSONB column that is currently nullable, but will be backfilled and made non-nullable at a later stage.
This was expecting data in either of 2 formats until the [relevant changes were made to admin](https://github.com/alphagov/notifications-admin/pull/2846). We can simplify this now to only expect data in the new format. This also allows us to remove a Marshmallow schema.
This sets the folder permissions for a user when adding them to a service. If a user is being added to a service after accepting an invite, we need to account for the possibility that the folders we are trying to add them to have been deleted before they accepted the invite.
[Pivotal story](https://www.pivotaltracker.com/story/show/163756170)
> Add folder permissions to invited users

- app/models.py
- migrations/versions/0281_non_null_folder_permissions.py
Now that notifications-admin is always sending through
folder_permissions, the folder_permissions column of the `invited_user`
table can be made non-nullable. The migration also backfills the column
(to `[]`) to account for existing null values.
Needs to be merged after https://github.com/alphagov/notifications-admin/pull/2850
[Pivotal story](https://www.pivotaltracker.com/story/show/163756170)
> Make invited_users folder_permissions column non-nullable

- app/dao/organisation_dao.py
- app/models.py
- tests/app/organisation/test_rest.py
We need this so we can disply them in the admin app.
The domains for an organisation should only be updated (or wiped) if a new list is explicitly passed in by the admin app.
> Return an organisation’s domains and fix a bug where the domains were getting wiped when updating other attributes

- app/dao/services_dao.py
- tests/app/service/test_rest.py
When creating a service it should inherit it’s organisation’s branding, if that organisation has branding.
This wasn’t working because we were referring to the ID of the branding when making the association, not the branding itself.
> Fix automatic inheritance of org’s branding

- app/dao/services_dao.py
- app/models.py
- migrations/versions/0282_add_count_as_live.py
- migrations/versions/0283_platform_admin_not_live.py
- tests/app/service/test_rest.py
Sometimes we have to make a few services for what really is one service, for example GOV.UK Pay and GOV.UK Pay Direct Debit. We also have our own test services which aren’t included in the count of live
services. We currently count these as one service by not including them in the beta partners spreadsheet.
This PR
- adds a column to mark such services as ‘not counted’, which can later be used to exclude them from reporting
- marks new and existing services created by a platform admin user as not counted by default (because they’re probably some kind of test service)
***
https://www.pivotaltracker.com/n/projects/1443052
> Allow excluding services from live services count

- migrations/versions/0284_0283_retry.py
The [previous migration](https://github.com/alphagov/notifications-api/pull/2417) didn’t work because the `created_by_id` column in services references the user who created the _version_ of the service, not who created the service originally. 
For most live services the user who created the most recent version will be the one who made the service live, ie the a platform admin user.
This commit runs another migration to wipe all the data, and replace it using an operation that looks at the first version of the service in the history table, which will reference the user who actually created the service.
> Retry making services created by platform admin users not counted in the list of live services

- app/celery/tasks.py
- app/commands.py
- app/notifications/notifications_letter_callback.py
- tests/app/celery/test_ftp_update_tasks.py
- tests/app/notifications/rest/test_callbacks.py
In this PR the action to update letter statuses and count the daily sorted counts has been separated. 
There is also a new command to go through each file sent by DVLA and record the daily sorted counts.
> Split task for updating letters

- app/dao/inbound_sms_dao.py
- app/inbound_sms/rest.py
- tests/app/dao/test_inbound_sms_dao.py
- tests/app/inbound_sms/test_rest.py
also, it should default to last 7 days, not last 6 days. also change count_inbound_sms to have the days passed in, so that it's more explicit at the endpoint that we only return 7 days regardless of your service's data retention
> make inbound sms page respect data retention

- manifest-api-base.yml
We've seen the SQLAlchemy "could not acquire connection" error in
production during heavy traffic. Since we have more gunicorn eventlet
workers than we have DB connections available some workers need to
wait for a DB connection to become available before they can proceed
with the request. There's a timeout set on how long a worker would
wait and if that timeout is exceeded the above exception is raised.
Currently, we're using at most 1000 out of 5000 max DB connections,
40% peak CPU usage on the DB instance and an average of 60% CPU on
API instances during heavy load. The number of DB connections is
proportionally similar in preview and staging.
This slightly increases the number of max DB connections per API
instance. This should improve our utilization of API instances by
increasing the …
> Increase DB connection pool size for API instances

- app/dao/fact_notification_status_dao.py
- app/dao/notifications_dao.py
- app/performance_platform/total_sent_notifications.py
- tests/app/celery/test_nightly_tasks.py
- tests/app/dao/notification_dao/test_notification_dao.py
- tests/app/dao/test_fact_notification_status_dao.py
- tests/app/performance_platform/test_total_sent_notifications.py
Update the nightly task that send performance platform statistics to use ft_notification_status rather than notification_history.
The previous query was including all notifications regardless of notification_status. This is okay because the performance platform is reporting how many notifications Notify is dealing with. 
I also need to remove the query that's no longer being used.
> Use ft_notification_status instead of notification_history

- app/celery/nightly_tasks.py
- tests/app/billing/test_billing.py
- tests/app/celery/test_nightly_tasks.py
Changed the query to get the performance platform stats from ft_notification_status. But the date used for the query needed to be a date, not datetime so the equality worked.
> Fix date bug for performance platform

- app/inbound_sms/rest.py
- tests/app/inbound_sms/test_rest.py
query args from GET requests are put into our logs, and we should avoid personal data (eg phone numbers) in them. Remove this old GET now that it's not used by the admin app anymore
> remove get for inbound sms by phone number

- app/celery/nightly_tasks.py
- app/clients/performance_platform/performance_platform_client.py
- app/performance_platform/processing_time.py
- app/performance_platform/total_sent_notifications.py
- tests/app/celery/test_nightly_tasks.py
- tests/app/performance_platform/test_processing_time.py
- tests/app/performance_platform/test_total_sent_notifications.py
- tests/app/test_utils.py
We had a bug caused by passing a date object in to a function that expected a datetime.
To help reduce confusion around this, we've cleaned up usage of dates/datetimes in performance platform tasks:
* call variables less ambiguous things like `start_time` or `bst_date` to reduce risk of passing in the wrong thing
* simplify the count_dict object - remove nested dict and start_date fields as superfluous
* use static datetime objects in tests rather than calculating them each time
> Fix performance platform date bug

- app/celery/reporting_tasks.py
- app/dao/fact_billing_dao.py
- app/dao/fact_notification_status_dao.py
- tests/app/celery/test_reporting_tasks.py
- tests/app/dao/test_fact_notification_status_dao.py
the create_nightly_notification_status task runs at 00:30am UK time, however this means that in summer datetime.today() will return the wrong date as the server (which runs on UTC) will run the task at 23:30 (populating the wrong row in the table).
fix this to use nice tz aware functions
timezones how do they work? 🕙 😭
> fix nightly ft stats tables task to respect BST

- app/dao/fact_billing_dao.py
- tests/app/celery/test_ftp_update_tasks.py
- tests/app/celery/test_reporting_tasks.py
- tests/app/dao/test_ft_billing_dao.py
- tests/app/db.py
- tests/conftest.py
the `get_rate` function tries to compare the parameter `date` to a datetime field in the DB.
However we're now passing a `datetime.date` object in instead, so were getting errors. Tests used this fn as a boundary so didn't flag this up.
> fix create_nightly_billing date bug

- app/celery/letters_pdf_tasks.py
```
This celery task was not decorated with the cronitor decorator so never
checked in with cronitor.
Adding the decorator will ensure this task is monitored.
The requisite cronitor key is in the credentials repository already.
Signed-off-by: Toby Lorne <toby.lornewelch-richards@digital.cabinet-office.gov.uk>
```
What
---
Ensure that the `collate-letter-pdfs-for-day` task checks in with Cronitor
How to review
---
- Code review
- Ensure that the `collate-letter-pdfs-for-day` cronitor key is in the production paas environment variables credentials file in the creds repo.
> Add Cronitor decorator collate-letter-pdfs-for-day

- app/organisation/rest.py
- tests/app/organisation/test_rest.py
We need this in the admin app while we still have pages that:
- talk about the data sharing and financial agreement
- but aren’t within a service (so can’t look at the service’s organisation)
This is a `GET`, but it deliberately won’t work if you pass it an email address, in order not to put personally identifying information in our logs.
> Add a method to guess organisation from a domain

- app/dao/organisation_dao.py
- tests/app/dao/test_organisation_dao.py
Update the dao_get_organisation_by_email_address to ignore `.gsi` in the email address.
> Ignore gsi in email address when searching for organisation

- migrations/versions/0285_default_org_branding.py
Currently when someone creates a service we match them to an organisation. Then if the organisation has a default branding set, their service gets that branding.
However none of the organisations yet have a default branding set up. This commit migrates the data about the relationship between an organisation and its branding from being inferred from the `domain`
field on the branding, to being a proper database relationship.
> Set default branding for all organisations

- app/commands.py
The active flag wasn't always used, plus a service should always be active on the first version of the service.
> The active flag in the query was excluding some services.

- app/dao/notifications_dao.py
- tests/app/dao/notification_dao/test_notification_dao_performance_platform.py
Update the query that gets the number of notifications that have been sent under 10 seconds to use Notifications rather than NotificationHistory.
Also removed a test that is not useful
> Switch table in query to Notification from NotificationHistory

- app/organisation/rest.py
- tests/app/organisation/test_rest.py
Previously this error would return a 500. Now we return a 400, with a useful message
> Return a useful message if the domain is a duplicate.

- app/clients/sms/firetext.py
- app/config.py
- tests/app/clients/test_firetext.py
- tests/app/clients/test_mmg.py
- tests/app/conftest.py
Similar to MMG, there's a new env variable FIRETEXT_URL that can be
used to override the Firetext api URL.
This will be used to stub out both providers during the load test or
can be used to run a local API against a fake provider endpoint.
> Make Firetext URL configurable through the application environment

- app/dao/email_branding_dao.py
- app/dao/letter_branding_dao.py
- app/dao/services_dao.py
- app/utils.py
- tests/app/dao/test_services_dao.py
The NHS is a special case because it’s not one organisation, but it does have one consistent brand. So anyone working for an NHS organisation should have their default branding set when they create a service, even if we know nothing about their specific organisation.
> Set default branding for NHS services

- app/letters/utils.py
- app/template/rest.py
- tests/app/template/test_rest.py
Has to go after this template-preview PR: https://github.com/alphagov/notifications-template-preview/pull/315
Part of this story: https://www.pivotaltracker.com/story/show/164798738
> Precompiled request preview with overlay when validation fails

- app/letter_branding/letter_branding_schema.py
So the admin is free to stop passing it in.
> Don’t require a domain when updating the letter branding

- app/dao/letter_branding_dao.py
- app/dao/services_dao.py
- app/email_branding/email_branding_schema.py
- app/email_branding/rest.py
- app/letter_branding/letter_branding_rest.py
- app/letter_branding/letter_branding_schema.py
- app/models.py
- app/service/rest.py
- tests/app/dao/test_email_branding_dao.py
- tests/app/dao/test_letter_branding_dao.py
- tests/app/dao/test_services_dao.py
- tests/app/db.py
- tests/app/email_branding/test_rest.py
- tests/app/letter_branding/test_letter_branding_rest.py
- tests/app/service/test_rest.py
This relationship is via the `Organisation` now; we don’t use this column to fudge a relationship based on the user’s email address and the matching something in these columns.
***
Depends on:
> Stop updating or reading domain columns on branding table

- migrations/versions/0287_drop_branding_domains.py
This relationship is via the `Organisation` now; we don’t use this column to fudge a relationship based on the user’s email address and the matching something in these columns.
***
Depends on:
> Remove domain columns from branding table

- app/dao/dao_utils.py
- app/dao/services_dao.py
- app/dao/templates_dao.py
- tests/app/dao/test_services_dao.py
This is fiendishly difficult problem to discover on your own.
It’s caused when, during the creation of a row in the database, you run a query on the same table, or a table that joins to the table you’re inserting into. What I think is happening is that the database is forced to flush the session before running the query in order to maintain consistency.
This means that the session is clean by the time the history stuff comes to do its work, so there’s nothing for it to copy into the history table, and it silently fails to record history.
Hopefully raising an exception will:
- prevent this from failing silently
- save whoever comes across this issue in the future a whole load of time
> Raise exception if history can’t be written

- app/models.py
- app/schemas.py
- migrations/versions/0287_add_go_live_user.py
- migrations/versions/0288_add_go_live_user.py
- tests/app/db.py
- tests/app/service/test_rest.py
Adding go_live_user and go_live_at columns to Services table. 
When the `request to go live` link is clicked, we will record the user that requested to go live. 
When the service is marked live we will record that date. 
Include the new columns in the return for get service.
> Go live data recorded for service

- manifest.yml.j2
This points MMG and Firetext on staging to a stub service run on
PaaS to avoid text message costs during the load test.
> Stub out SMS providers on staging for the perf tests

- app/template/rest.py
- tests/app/template/test_rest.py
The bug treated all pages of png preview as if they were all first
page, showing overlay for address bar.
has to go after: https://github.com/alphagov/notifications-template-preview/pull/326
Pivotal ticket: https://www.pivotaltracker.com/story/show/165569388
Preview after fixing:
> Fix bug in precompiled preview with overlay

- app/celery/tasks.py
- requirements-app.txt
- requirements.txt
Bumped utils to version 31.2.5, which changes when the rows of a RecipientCSV get created.
Switched to using `.get_rows()` from RecipientCSV (a generator) instead of the `.rows` property (which builds a list of the rows in memory).
Details about the utils change: https://github.com/alphagov/notifications-utils/pull/602
[Pivotal story](https://www.pivotaltracker.com/story/show/165021246)
> Bump utils to bring in changes to RecipientCSV rows

- requirements_for_test.txt
The next available version of pytest-xdist is 1.28.0, which [requires pytest>=4.4](https://github.com/pytest-dev/pytest-xdist/blob/master/CHANGELOG.rst#pytest-xdist-1280-2019-04-02). We currently have Pytest pinned to version 3.
> Make pyup ignore pytest-xdist

- runtime.txt
3.5.5 is removed in the next version of python-buildpack
> unpin patch version of python

- app/dao/date_util.py
- app/dao/services_dao.py
- app/service/rest.py
- tests/app/dao/test_services_dao.py
- tests/app/service/test_rest.py
Adds get_live_services_data endpoint to services rest and a related query to services_dao.
The query gets data about live services from multiple tables (Service, User, Organisation, FactBilling) and then serialises it so it can be pulled by admin app to create a csv report for our platform admins.
Needed for this story: https://www.pivotaltracker.com/story/show/164829877
Needs to be deployed before this PR: https://github.com/alphagov/notifications-admin/pull/2934
> Add get_live_services_data endpoint and related query

- app/dao/services_dao.py
- tests/app/dao/test_services_dao.py
Earlier filter was insufficient so now additional filters checking if service
is not in trial mode and if it's active have been added.
> Only show live services in live services query

- app/dao/notifications_dao.py
- tests/app/dao/notification_dao/test_notification_dao_delete_notifications.py
We want to stop inserting and updating NotificationHistory each time we insert/update Notification.
This PR adds a function to upsert (insert or update if exists) NotificationHistory all the rows from Notification that we are about to delete in the nightly task. This will happen just before the delete function. Since it is a upsert query the function can be called more than once.
This should allow us remove all the insert/updates to NotificationHistory.
However, there is a concern that this will double the length of time the tasks take. So do we do these upserts in a separate task or in the same one?
> Insert/update NotificationHistory just before we delete from Notifications

- app/dao/provider_details_dao.py
- app/provider_details/rest.py
- tests/app/dao/test_provider_details_dao.py
- tests/app/provider_details/test_rest.py
In addition to the existing provider data, we also want return the number of billable units (multiplied by the rate multiplier) that each SMS provider sent this month. This will be used on the platform admin providers page.
Since we can no longer get all the information we need from the provider details schema, this makes a new DAO function to get all the data for the endpoint.
[Pivotal story](https://www.pivotaltracker.com/story/show/165382068)
> Change get_providers endpoint to return no of SMS sent by each provider

- app/delivery/send_to_providers.py
- tests/app/celery/test_provider_tasks.py
- tests/app/delivery/test_send_to_providers.py
If we try to send an SMS to the provider and the provider throws an exception
(because they return a 503 status code) the notification should retry. But if
we get a callback from the provider before the notification has been retried, the
notification will have no billable units or provider set.
To avoid this, we now set billable_units and provider even if there has been
an exception from our provider.
> Ensure notifications have billable units and provider set if sending fails

- app/models.py
- migrations/versions/0290_org_go_live_notes.py
- tests/app/organisation/test_rest.py
This column will be used to stores extra notes that should go in the
Zendesk ticket when a service belonging to that organisation requests to
go live.
[Pivotal story](https://www.pivotaltracker.com/story/show/165790477)
> Add request_to_go_live_notes column to Organisation table

- requirements-app.txt
- requirements.txt
Version 32.0.0 of notifications-utils changes how SMS fragment count is calculated. Certain Welsh characters will cause the SMS to be encoded in unicode encoding (instead of GSM) so the fragment counts will be lower.
[Pivotal story](https://www.pivotaltracker.com/story/show/165672985)
Needs to be merged after:
> Bump utils to bring in new fragment count for unicode SMS

- manifest.yml.j2
If not specified, healthcheck is set to `port` by cloudfoundry - we've seen some issues with upgrading the deployment from v2 to v3 when using port - it adds apps to load balancer when they're not ready, which can result in 404s. by setting healthcheck to http it'll wait for the `/status` endpoint to return 200, which will wait for flask to get everything up and running properly
> add routes for all apps

- Makefile
- app/commands.py
- migrations/versions/0291_remove_unused_index.py
primary key provides the same control. also catch the right exception in the related command
mainly opening this PR to make sure zdt deploy flow doesn't go weird with migrations. It shouldn't, because we're still using the old `cf push` command for migrations, but make sure we don't create instances or map routes.
> remove unnecessary unique index

- Makefile
--no-start doesn't actually stage, which we need to get the files containing the new migrations.
> Can't use --no-start flag on migration

- migrations/versions/0292_give_users_folder_perms.py
This will be done just before we turn on folder permissions to all services to ensure that all users start with all the permissions.
Pivotal ticket: https://www.pivotaltracker.com/story/show/164051002
> Give existing users all folder permissions

- app/celery/reporting_tasks.py
- tests/app/celery/test_reporting_tasks.py
It's not necessary to calculate longer than 4 days. Cronitor lets us know if the job fails.
> Reduce the number of days to recalculate billing. 

- app/notifications/receive_notifications.py
This is probably a temporary log message, to make sure our new inbound numbers are working.
> Add logging for inbound numbers not associated to a service.

- app/celery/tasks.py
- app/dao/notifications_dao.py
- migrations/versions/0293_drop_complaint_fk.py
- tests/app/dao/test_provider_details_dao.py
- tests/app/notifications/test_notifications_ses_callback.py
Prepare to stop inserting NotificationHistory at the time of inserting a notification.
Remove foreign key to complaints.
Make sure if getting Notification.id we look to both tables.
> Look for notification in both tables for complaints

- app/delivery/send_to_providers.py
- tests/app/delivery/test_send_to_providers.py
Refactor send_to_providers. 
- Remove some redundant code for research mode.
- The international parameter in update_notification_to_sending is not needed.
- Update unit tests and removed duplicates
> Refactor update notifications

- Makefile
- manifest.yml.j2
- scripts/run_app_paas.sh
- scripts/run_multi_worker_app_paas.sh
- We are running statsd exporter as an app with a public route for
Prometheus to scrape
- This updates preview to send statsd metrics over the CF internal
networking to the statsd exporter
- Removes the sidecar statsd exporters too
> AUTO-413: Use an internal app for statsd preview

- app/delivery/send_to_providers.py
- tests/app/delivery/test_send_to_providers.py
The notification status happened in the wrong order - this resolved that.
This meant notifications sent with a test key never got a 'delivered' status.
> Fix a bug introduced when refactoring some code. 

- manifest.yml.j2
- We've been seeing an issue when traffic spikes of the http health
checks taking over 1s and PaaS killing the app
- Port health checks won't care about being stuck in a queue so should
continue to work even at high loads
- We have functional tests to catch if a deployment brings up the app
(and so passes port health check) but then doesn't work
> BAU: Use port health checks for API

- app/celery/letters_pdf_tasks.py
the celery decorator should always be on the outside so that all other decorators will be captured within the celery task. We had problems with cronitor not reporting, and only for this task.
> ensure cronitor decorator is inside the notify_task wrapper

- app/dao/notifications_dao.py
- app/notifications/process_notifications.py
- tests/app/celery/test_ftp_update_tasks.py
- tests/app/celery/test_tasks.py
- tests/app/dao/notification_dao/test_notification_dao.py
- tests/app/dao/notification_dao/test_notification_dao_delete_notifications.py
- tests/app/dao/test_ft_billing_dao.py
- tests/app/dao/test_services_dao.py
- tests/app/db.py
- tests/app/notifications/test_notifications_ses_callback.py
- tests/app/notifications/test_process_notification.py
- tests/app/v2/notifications/test_post_letter_notifications.py
This PR is the final step to make NotificationHistory truly an archive table. 
After this NotificationHistory is only inserted when the Notification is deleted. A join to NotificationHistory on id is added to the delete query to insure we have the history row before deleting the Notification.
> Don't insert notification history

- manifest.yml.j2
- We are running a statsd exporter on tools to collect all our statsd
metrics for scraping by Prometheus
- Update preview to point there instead of at the local one which has
issues with redeployment and DNS changing
> AUTO-413: Point preview statsd at tools

- app/dao/notifications_dao.py
- tests/app/celery/test_nightly_tasks.py
- tests/app/dao/notification_dao/test_notification_dao_delete_notifications.py
- tests/app/dao/test_inbound_sms_dao.py
- tests/app/dao/test_service_data_retention_dao.py
- tests/app/db.py
- tests/app/inbound_sms/test_rest.py
- tests/app/service/test_service_data_retention_rest.py
previously it was adding things to themselves multiple times and really going hog wild.
eg 
```deleted 8897093018183901804503167975743100526342834682089857387079868612907012634424730830727689561993171968844289082070435096154190598432362764954020570291922069530332692896342948663140136678066776721672101163552277149206250016680160446366416325768473892391086546941208444858318992685023719151460752551966348178575390119812536450367224270641914272569606028365201143364371593501435353383291340039094977818444972405845291157347296916635614451037767262796611984009092506556364885795133454108419782775398809172814175637118892609069429181007861988265980197609484135102265756310694433665868183103155954498371537014752039687360272315922303827257384030343309490299844231851101498011475469952377385263895020148039 …
```
> Fix delete count

- requirements-app.txt
- requirements.txt
This updates requirements and brings in the change to preserve trailing semicolons on URLs.
> Bump utils to 32.0.1

- app/dao/permissions_dao.py
- app/dao/service_user_dao.py
- app/dao/users_dao.py
- app/models.py
- app/user/rest.py
- tests/app/conftest.py
- tests/app/dao/test_users_dao.py
- tests/app/db.py
- tests/app/user/test_rest.py
Added a new `/user/<user_id>/archive` endpoint to allow a user to be archived and a new DAO function to archive a user.
Users can only be archived if all of their services have at least one other active team member with the `manage-settings` permission.
To archive a user we remove them from all services and organisations, remove all their permissions and change some of their details:
- `email_address` will start with `_archived_<date>`
- the `current_session_id` is changed (to sign them out of their current session)
- `mobile_number` is removed (so we also need to switch their auth type to `email_auth`)
- password is changed to a random UUID
- state is changed to `inactive`
If any of the steps fail, we rollback all changes.
[Pivotal …
> Add endpoint and DAO function to archive user

- app/models.py
- migrations/versions/0295_api_key_constraint.py
- tests/app/dao/test_api_key_dao.py
Update the unique constraint for the name of an api_key so that it only looks at api_keys that are not expired (or expiry_date is null).
This will allow clients to create a new api key with the same name.
> Allow api_keys names to be reused

- gunicorn_config.py
- Gunicorn can give us some interestings stats about what it is doing
that might prove useful when trying to work out the
gunicorn/eventlet/sqlalchemy kind of bottlenecking issues
- We already ship these env vars to the app so this is a pretty easy
change to make
- Uses statsd which is UDP so it shouldn't have any performance impact
on gunicorn
> AUTO: Get gunicorn stats

- manifest.yml.j2
- We want to do some load testing so we want to use the Prometheus
metrics for observing the system
- Roll out the statsd exporter work to staging too
> AUTO: Enable statsd exporter on staging

- app/models.py
- app/user/rest.py
- tests/app/organisation/test_rest.py
- tests/app/user/test_rest.py
The admin app now needs to know a few extra things about organisations and services in order to list them. At the moment it does this by making multiple API calls. See https://github.com/alphagov/notifications-admin/pull/3008 for more details.
This commit adds extra fields to the existing response. Once the admin app is using this fields we’ll be able to remove:
- `reponse['services_without_organisations']`
- `reponse['organisations']['services']`
> Return all required information about a user’s organisations and services

- app/models.py
- migrations/versions/0296_agreement_signed_by_person.py
- tests/app/organisation/test_rest.py
This is changing because we’re going to introduce accepting contracts and MoUs online.
https://www.pivotaltracker.com/story/show/166497058
Previously
---
We had one column for who signed the agreement, which is foreign key’d to the user table. This is still relevant, because there will always be a user who is clicking the button.
Now
---
We add two new fields for the name and email address of the person on whose behalf the agreement is being accepted. This person:
- is different from the one signing the agreement
- won’t necessarily have a Notify account
- is optional – sometimes the person signing the agreement is doing so on their own behalf
> Add columns for on whose behalf agreement signed

- app/celery/letters_pdf_tasks.py
- app/celery/scheduled_tasks.py
- app/config.py
- app/dao/notifications_dao.py
- tests/app/celery/test_letters_pdf_tasks.py
- tests/app/celery/test_scheduled_tasks.py
Added logging for letters which have been in `pending-virus-check` or `created` state for too long.
The `process_virus_scan_passed` task now catches S3 errors - if these occur, it logs an exception and puts the letter in a `technical-failure` state. We don't retry the task, because the most common reason for failure would be the letter not being in the expected S3 bucket, in which case retrying would make no difference.
Added a task which runs twice a day on weekdays and checks for letters that have been in the state of `pending-virus-check` for over 90 minutes. This is just logging an exception for now, not trying to fix things, since we will need to manually check where the issue was.
Added a scheduled task to run once a day and check if there were any letters from before 17.30 that …
> More logging and retrying for letters

- app/dao/templates_dao.py
- tests/app/v2/template/test_get_template.py
New trigger creates template_redacted row after insert to template
table
This here PR needs to be deployed before following PR: https://github.com/alphagov/notifications-api/pull/2537
> Ensure dao_create_template doesn't clash with new trigger

- app/delivery/send_to_providers.py
- requirements-app.txt
- requirements.txt
- tests/app/delivery/test_send_to_providers.py
notifications-utils version 33.0.0 adds alt text to email branding - the `HTMLEmailTemplate` now initializes slightly differently as a result (with both `branding_name` and `branding_text`).
[Pivotal story](https://www.pivotaltracker.com/story/show/166089275)
> Bump utils to add alt text to email branding

- app/celery/service_callback_tasks.py
This is because that error is caused by our providers and we
cannot do anything about it but it can make our logs hard to read
and actionable errors harder to spot
> Degrade MaxRetriesExceededError to warning status in logger

- migrations/versions/0041_email_template_.py
- migrations/versions/0057_change_email_template.py
- migrations/versions/0082_add_golive_template.py
- migrations/versions/0134_add_email_2fa_template_.py
- migrations/versions/0171_add_org_invite_template.py
- migrations/versions/0265_add_confirm_edit_templates.py
- migrations/versions/0294_add_verify_reply_to_.py
- migrations/versions/0296_template_redacted_fix.py
- migrations/versions/0297_template_redacted_fix.py
- Create template_redacted rows for templates created by migration, so that we can edit those templates
- Add commented out code to past migrations so when somebody is copying those migrations they remember about template_redacted insert
- Add missing statements to downgrades for past migrations
> Add rows in template_redacted where they are missing and help remember to insert them in the future

- app/dao/jobs_dao.py
- app/job/rest.py
- requirements-app.txt
- requirements.txt
- tests/app/dao/test_jobs_dao.py
- tests/app/job/test_rest.py
In this PR:
- create a rest endpoint cancel_letter_job
- check if letter job can be cancelled
- if yes, cancel letter job and return how many notifications have been cancelled
- if not, return a 'forbidden' error and a message explaining why the letter job can't be cancelled
Others in this series :)
utils: https://github.com/alphagov/notifications-utils/pull/621
admin: https://github.com/alphagov/notifications-admin/pull/3026
> Cancel letter job

- app/models.py
- app/organisation/rest.py
- app/user/rest.py
- tests/app/db.py
- tests/app/organisation/test_rest.py
- tests/app/user/test_rest.py
Once the admin app has started using the new fields returned in #2539 these fields won’t be needed any more.
> Remove old fields from organisations and services

- app/config.py
- app/dao/notifications_dao.py
- app/dao/organisation_dao.py
- tests/app/dao/test_organisation_dao.py
The organisation_type of a service should match the organisation_type of the service's organisation (if there is one). This changes `dao_update_organisation` and `dao_add_service_to_organisation` to set the `organisation_type` of any services when adding / updating an org.
Also removes some unused fixtures and deletes some unused code.
Part of [this story](https://www.pivotaltracker.com/story/show/166293397)
>  Set org_type of a service when adding/updating org org type

- requirements-app.txt
- requirements.txt
This brings in validation for the length of the local part of email addresses.
[Pivotal story](https://www.pivotaltracker.com/story/show/167170104)
> Bump utils to 33.2.3

- app/celery/reporting_tasks.py
- app/dao/fact_billing_dao.py
- app/dao/fact_notification_status_dao.py
- tests/app/celery/test_reporting_tasks.py
- tests/app/dao/test_fact_notification_status_dao.py
We found a problem with the report tasks that populate the fact tables (or statistic tables). It is possible that the notification status can change for notifications after 4 days.
This PR updates those queries to look in either Notification or NotificationHistory. Since the data does not exist in both tables at the same time we can do with and not worry about the data retention.
The query will iterate over each service, then each notification type and query the data if no results then try the history table.
> Bug fix for report tasks (stat tables)

- app/dao/jobs_dao.py
- tests/app/dao/test_jobs_dao.py
This content was first done without help of content designer so now it is improved with the help of one. New content is more in line with the content in the admin app and more human-readable and following GOV.UK standard.
> Change content of error messages when letter job can't be cancelled.

- app/dao/fact_notification_status_dao.py
- app/service/rest.py
- tests/app/dao/test_fact_notification_status_dao.py
- tests/app/service/test_rest.py
This adds a dao function and an endpoint to get the data needed for a new report for the engagement team. This report will be added to `/platform-admin/reports` in notifications-admin.
[Pivotal story](https://www.pivotaltracker.com/story/show/166495005)
> Add endpoint with data for report for the engagement team

- app/dao/services_dao.py
- app/models.py
- app/schemas.py
- migrations/versions/0300_migrate_org_types.py
- tests/app/dao/test_services_dao.py
- tests/app/organisation/test_rest.py
- tests/app/service/test_rest.py
- tests/conftest.py
- Migrate all orgs and services onto new organisation types
- Remove all mentions of generic `'nhs'` organisation type.
Part of this story: 
https://www.pivotaltracker.com/story/show/166666407
> Migrate org types

- app/commands.py
Updated the `populate-organisations-from-file` command to include a default email and letter branding column. The name of brand is used to look up the brand id and set it in the Organisation model. Also works if the columns are empty.
> Add email and letter branding to the add organisation command 

- app/config.py
There's a bug in pysftp that appears to cause quadratic performance loss. See https://github.com/paramiko/paramiko/issues/1141 for more details.
As a temporary band-aid fix, lower the size of the files we're sending.
> Lower the max dvla zip size from 500mb to 40mb

- .gitignore
- app/commands.py
- pytest.ini
- requirements-app.txt
- requirements.txt
also remove the `read().splitlines()` pattern from csv.reader usage, as it's redundant. also add .vscode to gitignore to accomodate my hipster IDE choices, and add some lines to pytest.ini so just running `py.test` uses some useful flags
> bump utils

- manifest.yml.j2
- We are running the statsd-exporter on the PaaS now so we can use the
internal UDP route to talk to it
- Only update in preview and staging still so that we can get the
dashboards fully up to date before switching prod
> REP-340: Use PaaS statsd exporter

- app/dao/jobs_dao.py
- pytest.ini
- tests/app/dao/test_jobs_dao.py
If a job was created 7 days ago but scheduled to send 2 days later, the csv file will be deleted from S3 two days early.
For example if a file is uploaded on Aug 1, but scheduled for Aug 3, the csv file will be deleted 2 days before the notifications.
This will cause an error for on the jobs pages if the download report link is clicked.
This PR uses the scheduled_for date is it exists otherwise the created_at date when deciding if the job is 7 days old.
> Use scheduled_for datetime for purging CSV files

- app/celery/provider_tasks.py
- tests/app/celery/test_provider_tasks.py
If the `deliver_sms` catches an exception when trying to send an SMS, we want the first retry to happen immediately (because we will have switched providers), then every retry after that to happen at the standard intervals.
[Pivotal story](https://www.pivotaltracker.com/story/show/166575127)
>  Retry deliver_sms task immediately if sending fails

- app/celery/provider_tasks.py
- tests/app/celery/test_provider_tasks.py
This reverts commit 51716fbaf8364aa41d34aac91d17d7c4a979507b.
Instead of relying on catching SES errors we will convert all email addresses to punycode before sending instead.
> Revert "Change email status to permanent-failure if SES raises InvalidParameterValue"

- app/config.py
was a `,`, not a `:`, so 'options' was a set rather than a dictionary, causing beat to crash
> fix typo in config

- manifest.yml.j2
- requirements-app.txt
- requirements.txt
Also bump the utils version to include a fix on the error handling logic
when we fail to send a metric.
> Enable statsd exporter for production

- app/dao/organisation_dao.py
- app/dao/services_dao.py
- app/models.py
- migrations/versions/0303_populate_services_org_id.py
- tests/app/dao/test_organisation_dao.py
- tests/app/dao/test_services_dao.py
This is the second commit in the series to add organisation_id to Service.
- Data migration to update services.organisation_id from data in organisation_to_service
(The rollback will lose any updates to organisation unless the script is updated to set organistion_to_service from service.organisation_id )
- Update Service.organisation relationship to a ForeignKey relationship to Organisation.
- Update Organisation.services to a backref relationship to Service.
> Add organisation_id to Service.

- app/celery/reporting_tasks.py
- app/config.py
- tests/app/celery/test_reporting_tasks.py
the nightly tasks need to run after the create nightly notification status task - so that test notifications are still there to record stats for, and to stop the risk of deleting notificaitons part-way through recording stats for them.
> trigger nightly delete tasks from the create notification status task

- app/__init__.py
- app/models.py
- migrations/versions/0304_remove_org_to_service.py
This table is no longer used or referenced in the code.
We can remove this mapping table now that the organisation to service relationship is handled by the foreign key in Services.
> Remove the organisation_to_service table.

- app/dao/services_dao.py
- app/models.py
- migrations/versions/0305_add_gp_org_type.py
- tests/app/dao/test_services_dao.py
- tests/app/organisation/test_rest.py
Although their allowances are the same as what we call `nhs_local` it makes more sense to store them separately because:
- we already present them as two separate choices to the user
- we may want to handle them differently in the future, eg in terms of what branding choices are available to them
> Add ‘GP’ as an org type

- app/billing/rest.py
- app/commands.py
- app/dao/date_util.py
- app/dao/fact_billing_dao.py
- app/platform_stats/rest.py
- tests/app/dao/test_date_utils.py
- tests/app/dao/test_ft_billing_dao.py
- tests/app/db.py
- tests/app/platform_stats/test_rest.py
New billing report for all services. 
There is a command to populate the missing annual billing - the report will miss wrong for those missing rows. You'll need to run the `flask command populate-annual-billing -y 2019`
After the task is done the count of active services should match the count of services in annual billing for 2019.
`select count(*) from services where active=true`
equals
`select count(*) from annual_billing where financial_year_start=2019`
> Billing for all services

- app/dao/fact_billing_dao.py
- tests/app/dao/test_ft_billing_dao.py
- tests/app/db.py
The sheet count was not calculated properly (it should be billable_units/notifications_sent).
And it turns out the sheet count is not required for the report. This PR takes out the columns to resolve the group by error.
> Fix grouping on the usage for all services report

- app/letters/utils.py
- tests/app/letters/test_letter_utils.py
Using the created at date for the folder is not always going to work because the pdf created_at date could be just before the cut off date but virus scan and validation has yet to happen. By the time the letters is in the created state, the letter goes into the next days bucket.
It can also happen if the letters is stuck in `pending-virus-scan` and we need to restart the task, and the letters is in a different folder.
It might be worth trying to reduce the complexity of these methods.
> Fix the folder returned for a pdf letter.

- app/models.py
- tests/app/organisation/test_rest.py
This will let us do some filtering of this list in the admin. It’s better to do it there because it means the admin can use the same cached response from Redis each time.
***
Will require flushing the Redis cache after deploying.
> Return org_type in list of all organisations

- app/celery/letters_pdf_tasks.py
- app/letters/utils.py
- tests/app/celery/test_letters_pdf_tasks.py
- tests/app/letters/test_letter_utils.py
This is done so that we can see why no matches are found sometimes during the redaction procedure
Needs this PR to work: https://github.com/alphagov/notifications-template-preview/pull/369
> Copy original file to redaction_failure folder when redaction fails

- app/celery/letters_pdf_tasks.py
- app/letters/utils.py
- app/models.py
- app/v2/errors.py
- app/v2/notifications/get_notifications.py
- app/v2/notifications/post_notifications.py
- tests/app/letters/test_letter_utils.py
- tests/app/v2/notifications/test_get_notifications.py
- tests/app/v2/notifications/test_post_letter_notifications.py
a new endpoint (`/v2/notifications/<id>/pdf`) that returns a PDF for a letter notification
If the notification's pdf is available, it returns that, as a raw file. If the pdf is not available, it returns 400.
The pdf won't be available if the notification's status is:
* pending-virus-scan
* virus-scan-failed
The pdf will be retrieved from the correct s3 bucket based on its type. To make sure the pdf is available, we now create PDFs for templated test pdfs too (previously we just marked them as delivered).
> add api endpoint to get pdf for letter

- app/celery/letters_pdf_tasks.py
- tests/app/celery/test_letters_pdf_tasks.py
People send test letters with name only in address block, and then our redaction tool finds too many matches. Yet those redaction failures do not matter as they are not representative of real letters.
So it would be good to only log real letters that failed redaction.
> Don't log address redaction failure when letter sent with test key

- tests/app/celery/test_ftp_update_tasks.py
- tests/app/celery/test_letters_pdf_tasks.py
- tests/app/celery/test_nightly_tasks.py
- tests/app/celery/test_provider_tasks.py
- tests/app/conftest.py
- tests/app/dao/test_services_dao.py
- tests/app/db.py
- tests/app/delivery/test_send_to_providers.py
- tests/app/notifications/test_process_notification.py
- tests/app/platform_stats/test_rest.py
- tests/app/test_schemas.py
Code that is within a `with Python.raises(...)` context manager but comes after the line that raises the exception doesn't get evaluated. We had some assertions that we never being tested because of this, so this ensures that they will always get run and fixes them where necessary.
> Make a few fixtures Pytest 4 compliant and fix tests with errors

- app/dao/organisation_dao.py
- tests/app/dao/test_organisation_dao.py
When a service asks for branding I often go and:
- set the branding on the organisation as well
- set the branding on all the organisation’s services
The latter can be quite time consuming, but it does save effort since existing services from the same organisation won’t have to request branding. It also improves the consistency of the communications that users are receiving.
This commit automates that process by applying the branding update to any services belonging to the organisation, if those services don’t already have their own custom branding set up.
> Update the branding of services branding when updating their organisation’s branding

- app/dao/notifications_dao.py
- app/job/rest.py
- tests/app/dao/notification_dao/test_notification_dao.py
- tests/app/job/test_rest.py
When we cancel a job, we need to check if all notifications are already in the database.
So far, we were querying for serialised notification objects in the database and counting them in admin app, which runs into pagination problems for large jobs, and could time out for very large jobs.
Admin part: https://github.com/alphagov/notifications-admin/pull/3130
Bug: https://www.pivotaltracker.com/story/show/168734905
> Return count of notifications in the database for a job

- app/models.py
We have a table for datetime dimension that we no longer use and
I believe can be dropped.
First step is to remove the model and release the change. The next
step will be to then add a database migration to drop the actual
table. I believe we need to do it in this order and it can't
be done as a single PR.
> Drop datetime dimension model

- migrations/versions/0307_delete_dm_datetime.py
No longer needed
See https://github.com/alphagov/notifications-api/pull/2625 which has already gone out to remove the related sqlalchemy model first
> Delete dm_datetime database table

- app/dao/notifications_dao.py
- tests/app/dao/notification_dao/test_notification_dao_delete_notifications.py
The nightly job to delete email notifications was failing because it was timing out (`psycopg2.errors.QueryCanceled: canceling statement due to statement timeout`).
This adds a query limit to the query which inserts or updates notification history so that it only updates a maximum of 10,000 rows at a time.
> Update insert_update_notification_history to take a query limit

- manifest.yml.j2
deploys take up to five minutes, during which notify-paas-autoscaler can't scale the app. We saw 502s due to a large volume of traffic coming in during that time, and we couldn't react cos we were deploying.
scale up to 25 instances, the autoscaler won't be able to downscale until after the deploy has finished.
> scale up api to 25 instances before deploy on production

- Makefile
5 minutes isn't long enough to scale api at load, leading to failed deploys
> set startup timeout to 10 minutes

- app/celery/letters_pdf_tasks.py
- app/letters/utils.py
- app/service/send_notification.py
- tests/app/celery/test_letters_pdf_tasks.py
So it can be used by admin app to tell the user why the letter has failed validation.
Attention! This PR can only be merged when Katie's PR in admin is ready so we can make sure our approaches to metadata are harmonised
> Put pdf letter validation failed message in S3 metadata

- app/celery/nightly_tasks.py
- tests/app/celery/test_nightly_tasks.py
this took way longer than it should have.
DVLA now only send second class letters on Mon/Wed/Thurs. we still send to them every day as per previous operation.
This means that a letter sent to DVLA on monday evening might not be sent until weds afternoon, so we shouldn't check for whether it was sent or not on tuesday afternoon.
there's a days grace we put in the query because we found we weren't getting response files in time. I don't know how that'll interact with DVLA skipping days. IE: if they don't send response files on Weds for a weds print run, will they do it on thurs instead, even though they're not doing a print run then? we'll just have to ship it and see
> Letter alert

- app/service/send_notification.py
- tests/app/service/test_send_pdf_letter_notification.py
This adds an api check that the service is not in trial mode when someone tries to send an uploaded letter.
> Check service is not in trial mode for uploaded letters

- gunicorn_config.py
All our requests identify the web server they were served with via the `server` response header. This opens us up to potential attackers who might be crawling the internet looking for specific versions with known vulnerabilities. As our dependencies are open source, this doesn't affect any targeted attacks as they can just look at our repos on github, but this theoretically will marginally improve security.
Regardless, the header isn't useful [1], we're not the first people to want to get rid of it, and gunicorn are in the process of at least amending it to remove the version information [2].
This shouldn't have any impact on us, though an empty string will be passed through to debug information in event of a crash. That's fine though, as we already know what version we're running.
[1] …
> remove gunicorn server header from responses

- app/celery/tasks.py
Trying to add more logs for jobs. 
We are seeing a weird problem where one row in the csv is being skipped. Is the job taking too long to process then getting picked up by another thread - seems unlikely given the safe guard at the top of the process-job task. 
What other logs would be useful?
> Add more logging for process_job

- app/celery/celery.py
- app/v2/notifications/post_notifications.py
- requirements-app.txt
- requirements.txt
- requirements_for_test.txt
**Requirement bumps**
Bumped Utils to bring in changes to logging the request_id (https://github.com/alphagov/notifications-utils/pull/658). Freezing requirements updated a few other dependencies too, including Werkzeug from version 0.15.5 to 0.16.0, which required a small change to an import (https://github.com/pallets/werkzeug/blob/master/CHANGES.rst#version-0160).
**Passing the `request_id` to tasks if available**
We want to pass the `request_id` to Celery tasks if the task is called from an HTTP request, so that we can log it. This change overwrites `apply_async` to add the `request_id` to the kwargs if available. When we call the task, we then add the `request_id` to `g` on Flask's application context.
Tasks called from `send_task` won't have a `request_id` for now, and this change …
> Add request_ids to some Celery tasks

- app/service/rest.py
- app/service/send_notification.py
- app/service/send_pdf_letter_schema.py
- tests/app/service/test_rest.py
- tests/app/service/test_send_pdf_letter_notification.py
https://www.pivotaltracker.com/story/show/167534014
- Require postage key for API calls to send an uploaded PDF letter
- Set postage in the DB as sent from API call
- Use JSON schema validation for requests to this endpoint
This will lay the groundwork for https://github.com/alphagov/notifications-admin/pull/3144 to be finished off
I've tested this against 
- https://github.com/alphagov/notifications-admin/pull/3144
- notifications-admin master
> Set postage

- scripts/run_app_paas.sh
- scripts/run_multi_worker_app_paas.sh
What
----
When Cloud Foundry applications are to be rescheduled from one cell to
another, or they are stopped, they are sent a SIGTERM signal and 10
seconds later, a SIGKILL signal.
Currently the scripts trap the POSIX defined EXIT handler, rather than
the signal directly.
In order for the signal to properly be propagated to celery, and the
celery workers, the script should call the on_exit function when
receiving a TERM signal.
How to review
----
- [link to helpful page](https://www.linuxjournal.com/content/bash-trap-command)
- `cf t -s preview`
- `cf v3-ssh notify-delivery-worker-letters`
- `ps auxf | grep run_app_paas.sh`
- `kill -15 PID` using PID from above
- Observe that `Terminating application process with pid` is printed to the logs in Kibana/AWS
Work done by
----
Becca, Toby
> Catch the TERM signal in the run_app_*paas scripts

- scripts/paas_app_wrapper.sh
- scripts/run_app_paas.sh
By adding `exec` to the entrypoint bash script for the application, we can trap an EXIT from the script and execute our custom `on_exit` method with checks if the application process is busy before terminating, waiting up to 10 seconds. We don't need to trap `TERM` so that's been removed again.
Written by:
@servingupaces
@tlwr
> Change how the bash script is started.

- requirements_for_test.txt
- tests/app/celery/test_ftp_update_tasks.py
- tests/app/celery/test_letters_pdf_tasks.py
- tests/app/clients/test_mmg.py
- tests/app/conftest.py
- tests/app/dao/test_services_dao.py
- tests/app/db.py
- tests/app/invite/test_invite_rest.py
- tests/app/notifications/rest/test_callbacks.py
- tests/app/notifications/rest/test_send_notification.py
- tests/app/notifications/test_rest.py
- tests/app/notifications/test_validators.py
- tests/app/service/test_api_key_endpoints.py
- tests/app/service/test_rest.py
Changed the code to be Pytest 5 compatible by
- stopping fixtures being called like functions (almost all of the changes in this PR)
- changing how we check for error messages of exceptions
`conftest.py` can be tidied up as a separate PR - the fixtures there don't need any parameters (since they can't be called as functions anymore). There are also some fixtures in the file which aren't being used anywhere, so can be deleted.
> Upgrade to Pytest 5 😅

- app/letters/utils.py
- app/template/rest.py
- app/v2/notifications/get_notifications.py
- tests/app/celery/test_letters_pdf_tasks.py
- tests/app/letters/test_letter_utils.py
- tests/app/template/test_rest.py
- tests/app/v2/notifications/test_get_notifications.py
Also use this metadata to decide whether preview pages need
overlay or not. So far we have always added overlay when validation
has failed. Now we will only show it when validation failed due to
content being outside of printable area.
> Grab metadata when getting pdf letter preview from S3

- tests/app/conftest.py
- **Remove unused fixtures**
- **Remove parameters from fixtures**
Since Pytest 4, we can't call fixtures as if they were functions anymore. This change removes the parameters from the fixtures (since we can't use them), except for when the parameter is another fixture.
> Tidy fixtures after Pytest 5 upgrade

- app/dao/jobs_dao.py
- tests/app/dao/test_jobs_dao.py
This is only necessary because there is currently a job that is old, but had 1 row created a couple days later. So now there is 1 notifications for the job where the rest have been purged.
> Added a filter to restrict jobs older than a day from coming back.

- app/dao/fact_billing_dao.py
- tests/app/dao/test_ft_billing_dao.py
The group by for the query was wrong which would result in 2 rows with different totals but the same unique key, so the second row would update the first row. Meaning we had incorrect numbers for the billing data.
Because some of the data had null for the sent_by column, the select would turn the Null --> dvla, but that same function was not used in the group by. So any time we had missing sent_by data we would end up with 2 rows where one would overwrite the other.
> Fix query to populate ft_billing table.

- app/aws/s3.py
- app/celery/scheduled_tasks.py
- app/celery/tasks.py
- tests/app/celery/test_scheduled_tasks.py
- tests/app/celery/test_tasks.py
When a job is created the user can select a sender id (if there is more than one). When the sender id is selected it is added to the metadata of the file. However, there are three other cases were we process data from the CSV: 
- scheduled jobs
- a job that has bee restarted (if an app that is processing a job is stopped before the job is done, then we have a check that will look for this and restart the job)
- there is an odd occurrence where a row from the file is skipped, we have a check for this and will process the missing row.  
For each of these cases the sender id is not used. 
This PR uses the sender id from the CSV file meta data. This will make the need for passing the sender_id into the `process_job` task redundant and can be removed in the next PR.
> Get sender id from metadata 

- app/schema_validation/__init__.py
- app/v2/notifications/post_notifications.py
- app/v2/template/post_template.py
- app/v2/utils.py
- tests/app/v2/notifications/test_post_notifications.py
- tests/app/v2/template/test_post_template.py
We require the POST data to be in JSON format and that the content-type header be set to application/json.
This PR does that validation and returns a decent message. Previously the error message was a None type error which is not helpful to anyone.
Thank you to @bambrp for bring this to our attention. I've closed your PR, https://github.com/alphagov/notifications-api/pull/2652, in favour of this one as I have included some unit tests and updated the post_template endpoint because it had to be handled specially since the data can be empty for that request.
> Add validation for missing content-type header

- README.md
We now run python 3.6 in production and there are issues with marshmallow-sqlalchemy using 3.5.
> Update README about python to use

- app/notifications/validators.py
- requirements-app.txt
- requirements.txt
- tests/app/notifications/test_validators.py
Validate against a message with no content for one off messages.
Needs to go in after this is merged: https://github.com/alphagov/notifications-utils/pull/671
> Validate against messages with no content

- app/celery/scheduled_tasks.py
- app/dao/notifications_dao.py
- tests/app/celery/test_scheduled_tasks.py
Add an alert when a letter is created but doesn't have a file in S3 for sending. We can tell this is the case because there is no updated_at and billable units are still 0.
It is safe to run the app.celery.letters_pdf_tasks.create_letters_pdf task again even if the letter is already in the S3 bucket. Which also means we could shorten the time we wait before check the letter. 
I've reduced the amount of time that we wait before replaying the task to send or create pdf for the notification. This is possible because the tasks can be run twice without harm.
> Alert if a letter doesn't make it past created status

- app/celery/scheduled_tasks.py
- app/celery/tasks.py
- app/dao/notifications_dao.py
- app/dao/provider_details_dao.py
- app/delivery/send_to_providers.py
- tests/app/celery/test_provider_tasks.py
- tests/app/celery/test_scheduled_tasks.py
- tests/app/dao/notification_dao/test_notification_dao.py
- tests/app/dao/test_provider_details_dao.py
- tests/app/delivery/test_send_to_providers.py
- tests/app/provider_details/test_rest.py
- tests/app/test_schemas.py
- tests/conftest.py
* exclusively use one provider at a time
* if a provider has been "slow" over a recent period of time, switch to the other one
* if a provider returns 5xx or times out, switch to the other one
* if we accidentally DOS a provider with high load, we'll switch and then we might accidentally DOS the other provider (this actually happened and was the reason we prioritised this story)
* randomly pick a provider when sending an sms, taking the `priority` field as a weighting
* if a provider has been "slow", reduce its weight (and bump up the other weight to make it easier to read/reason about)
* if a provider has a 500, reduce its weight and bump the other
* don't adjust weights if they've been changed in the last 10 minutes (to stop 10 500s at once taking something from working to switched off …
> Distribute sms between providers

- app/config.py
- requirements-app.txt
- requirements.txt
- tests/app/delivery/test_send_to_providers.py
note: this includes updating the MMG api url to their v2a api. Their previous API doesn't include support for capital o with grave accent (`Ò`).
MMG have confirmed that there are no other changes to the API endpoint other than the encoding fix for that one character.
> update utils to bring in full welsh diacritics range

- app/config.py
- manifest.yml.j2
these URLs never change, and it lead to surprising issues where an updated default MMG_URL wasn't actually respected on PaaS. These urls aren't private and don't need to be stored in credentials.
By not defining them in the manifest, we expect them to use the default unless `cf set-env` has been specifically used to modify them in an app.
> don't define MMG_URL and FIRETEXT_URL in manifest

- app/celery/reporting_tasks.py
- app/commands.py
- app/dao/fact_notification_status_dao.py
- tests/app/celery/test_reporting_tasks.py
- tests/app/dao/test_fact_notification_status_dao.py
- tests/app/dao/test_services_dao.py
Separate this refactoring PR from the actual logic change that is coming soon™ (to make it rebuild for letters more often). Just splitting up the task by notification_type - it now requires type all the time. This is fine to merge provided that the task isn't running as it deploys, but given that it runs nightly at 4am or something that's probably fine
This also allows us to rebuild historical data by type, rather than for all three notification types.
And it makes the command just call through to the task, rather than re-implementing it.
> split create_nightly_notification_status by notification type

- app/celery/reporting_tasks.py
- app/commands.py
- tests/app/celery/test_reporting_tasks.py
sms and emails have a very predictable 72 hour lifecycle. letters, on the other hand, have ridiculously complex lifecycles - they might not get sent because it's a weekend, they might not get sent because they're second class and are only processed on alternate days, they might not get sent because a different letter in the same batch had an error that we didn't know about. Either way, it's apparent that four days is definitely not enough time to guarantee that letters have gone from sending to delivered.
Extend the amount of days we process for letters to 10 days. Keep emails and sms down at 4 to keep run-times shorter
We're deliberately not thinking about returned letters here at all.
> process letters for 10 days when updating ft_notification_status

- app/celery/scheduled_tasks.py
- tests/app/celery/test_scheduled_tasks.py
Trying to concatenate uuid onto a string was throwing an error.
> Use .format instead of concatenation to avoid type issues

- app/authentication/auth.py
- requirements-app.txt
- requirements.txt
- tests/app/authentication/test_authentication.py
Instead of letting it go uncaught and causing an error, we now show the
user an appropriate error message.
Requires https://github.com/alphagov/notifications-python-client/pull/155
> Catch `TokenAlgorithmError`

- app/celery/reporting_tasks.py
log lines didn't make sense because the arguments were the wrong way round.
As an experiment to try and clean up some of our code a bit, this commit adds f-strings. f-strings were added in python 3.6, as a way to clean up, simplify, and improve the performance of `str.format`. They're used by just prefixing a string with `f` (like you would r for raw or b for bytes), and then curly braces work largely like str.format, but looking at all available variables. It's pretty similar to `"...".format(**locals())`. You can still use number formatting just fine with the same colon syntax (eg `{x:04}` to left pad to four characters with zeroes or `{x:,}` to comma separate thousands). You can do complex function calls and operations (eg `f"{foo['x'].get_thing()}"`).
Interested in knowing people's …
> fix log line typo

- app/celery/tasks.py
- app/dao/returned_letters_dao.py
- app/models.py
- app/service/rest.py
- migrations/versions/0310_returned_letters_table_.py
- tests/app/celery/test_tasks.py
- tests/app/dao/test_returned_letters_dao.py
- tests/app/db.py
- tests/app/service/test_rest.py
The services do not have a way to get returned letters from the app. 
Create a table to store the notification_id, reported_at date and service_id for each returned letters. Adding the notification_id to this table allows us to join to notification_history by the primary key which will mean the query should be fast. 
When the returned letters are uploaded via the UI, the task will also update the returned_letters table. 
There is an endpoint to return the summary data, a count of letter per report date, typically there is one per month. 
Pending is another endpoint to return the data required by the service as described in https://www.pivotaltracker.com/story/show/167920694
> Add returned letters table

- app/dao/notifications_dao.py
- app/service/rest.py
- tests/app/dao/notification_dao/test_notification_dao.py
We have a team who want to find emails that might have been sent to an incorrect address. Therefore they can’t search by the correct address, because it won’t match.
What they do have is the reference number of the user’s application, which is also stored in the `client_reference` field on the notification.
So when a user is searching we should also look at the client reference, as well as the recipient, allowing the user to enter either in the search box.
> Allow searching notifications by reference as well as recipient

- app/celery/scheduled_tasks.py
- tests/app/celery/test_scheduled_tasks.py
We don't need to log this as an exception. It's not an exception, it's
behaviour that is not ideal but is still expected so therefore I've
changed it to warn. Also it removes the email we get for the exception
which is not needed as we get the zendesk ticket instead.
I've also fixed the multiline string meaning the link to the runbook is
included in the zendesk ticket.
> Improve developer experience for zendesk ticket

- app/celery/letters_pdf_tasks.py
- app/config.py
- app/letters/utils.py
- tests/app/celery/test_letters_pdf_tasks.py
- tests/app/letters/test_letter_utils.py
The current `process_virus_scan_passed` task will be split into three separate tasks so that we can validate letters asynchronously. These new tasks are, in order:
Added in this PR. This calls the template preview task with details of the letter to be sanitised.
Added to template preview [here](https://github.com/alphagov/notifications-template-preview/pull/399). This sanitises the letter and calls the third task with the results.
Added in this PR. This moves the files into the relevant S3 buckets and update the notification
Once deployed, the new tasks won't be used until notifications-antivirus is updated to call `sanitise_letter` instead of `process_virus_scan_passed`.
[Pivotal story](https://www.pivotaltracker.com/story/show/169148522)
> Add new tasks for processing letters which have passed virus scan

- manifest.yml.j2
This was after we saw an instance of the API failing it's healthcheck
even though it was still healthy enough to serve requests to users.
This follows the change we've also made to template-preview and admin of
upping the health check timeout. Unlike those where we set it to be 10
seconds, we have been less allowing here and only chosen 2.5 seconds.
This was at suggestion of Toby from PaaS as the api should generally
have quicker response times and more annoyance might be created for
users if we let an instance stick around for 10 seconds where it was
unable to serve requests successfully.
> Up API health check timeout to 2.5 seconds

- manifest.yml.j2
Not allowed to be a non integer so have upped to 3 rather than going to
2 (fairly arbitrary choice).
> Set healthcheck timeout as integer

- app/__init__.py
- app/dao/returned_letters_dao.py
- app/models.py
- app/schemas.py
- app/service/rest.py
- migrations/versions/0311_populate_returned_letters.py
- migrations/versions/0312_populate_returned_letters.py
- tests/app/dao/test_returned_letters_dao.py
- tests/app/db.py
- tests/app/service/test_rest.py
Once a month the postal provider sends a report of all the returned letters. At the moment, the services do not have a way to consume this information. 
This PR has a db migration script to populate a new table called `returned_letters` which captures the notification id of the letter that has been returned. 
There is a new query to get a summary of the data and an endpoint to show each report for a given service. 
There is a new query and endpoint to return the report for a given service and report date.
> Populate returned letters

- requirements.txt
- requirements_for_test.txt
- tests/app/test_cloudfoundry_config.py
- tests/app/test_config.py
- tests/conftest.py
test_config manipulates os.environ. os.environ is an `environ` object, which acts like a dict but isn't in some subtle unknowable ways. The `reload_config` fixture would create a dict copy of the env, and then just call `os.environ = old_env` afterwards.
Boto3 would then complain that it couldn't load credentials (despite us using the mock_s3 fixture and also not having creds in the environment in the first place). Not entirely sure why this happens, but it does. For some reason, it being a `dict` instead of an `environ` object causes the mocking of boto3 to fail.
The solution is to not overwrite os.environ entirely, rather, use the standard dictionary setitem syntax to update the values to their previous values. Use `clear` to empty the environment too.
> Test isolation fix

- app/models.py
- tests/app/job/test_rest.py
Add client_reference to the serialised notification returned for the CSV reports.
We want to add the client reference to the report, precompiled letters require a client reference.
> Add client reference to notification reponse

- app/config.py
These alerts are sent to our postal provider. And it usually arrives as they are getting ready to go home for the day or the weekend.
Which means they get missed/overlooked. They have agreed to get the alert an hour earlier, perhaps that will improved the response time.
> Send the alert for `letters-still-sending` an hour earlier.

- app/celery/letters_pdf_tasks.py
- app/service/send_notification.py
- app/service/send_pdf_letter_schema.py
- app/v2/notifications/post_notifications.py
- tests/app/celery/test_letters_pdf_tasks.py
- tests/app/service/test_rest.py
- tests/app/service/test_send_pdf_letter_notification.py
When a precompiled letter is sent via the admin app, we now pass in the address which can be set in the Notifications.to field.
Once a precompiled letters sent by the API has passed validation we can set the address in Notifications.to field. The template-preview app returns the address is the http request to sanitise the letter. 
Save recipient address in the "to" field of a notification
The celery tasks to validate precompiled letters sent by the API will be done in another PR.
> Put address in to field for precompiled

- app/celery/scheduled_tasks.py
- app/dao/services_dao.py
- tests/app/celery/test_scheduled_tasks.py
We were just ignoring the errors and our users were not fixing things.
Given that 500 texts cost approx £8 it's not the end of the world.
In the long run we may decide to just stop letting people try and send
messages to TV numbers but this is a quick fix to stop emails coming in
which we ignore.
> Up threshold for sms to telephone numbers

- app/clients/document_download.py
- app/v2/notifications/get_notifications.py
- tests/app/clients/test_document_download.py
- tests/app/db.py
- tests/app/v2/notifications/test_get_notifications.py
if doc download returns a 403, that's a screw-up on our side. it's not helpful to a notify user for that to be passed on. the only thing they should care about is if it's a 400, because they uploaded a filetype we don't allow.
Everything else should return 500 internal server error.
> handle document download errors properly

- requirements-app.txt
- requirements.txt
v20 brings in a host of changes, including a fix for https://github.com/benoitc/gunicorn/issues/1847, which was stopping us upgrading before.
TODO: understand a bit more about what the issue was before with eventlet, and go through the rest of the changelog to understand the risk.
> bump gunicorn to v20

- app/dao/notifications_dao.py
- app/template_statistics/rest.py
- tests/app/dao/notification_dao/test_notification_dao_template_usage.py
- tests/app/template_statistics/test_rest.py
The existing endpoint returned a whole notification for the last time the template was used. But this only takes into account data in the last week. This new methods allows us to be specific about when the template was last used if ever but looking into the ft_notification_status table as well.
> Added a new endpoint to return the last used date for a template.

- app/aws/s3.py
- app/celery/nightly_tasks.py
- app/config.py
- tests/app/aws/test_s3.py
- tests/app/celery/test_nightly_tasks.py
We no longer puts files in these s3 buckets (and have in fact deleted
the buckets) therefore this task is redundant and can be removed.
> Remove task that no longer runs

- app/models.py
- app/user/rest.py
- tests/app/user/test_rest_verify.py
when verifying the code is correct. This way if user has sms_auth
and we send them verification code to validate their email access,
and they click the link in the email, their access will be validated
correctly.
- Format email_access_validated_at when serializing
This is to bring it in line with other serialized dates in User
model, like logged_in_at and password_changed_at.
- Also get rid of check if password_changed_at has value, as
it is a non-nullable column, so it needs to always have value.
- Also set a default value for email_access_validated_at, to bring
it in line with other non-nullable columns.
> Validate email access based on code_type and not auth_type

- app/dao/notifications_dao.py
- requirements-app.txt
- requirements.txt
We aren't aware of any reason we need to use our fork of boto anymore.
We therefore swap to use `celery[sqs]` which brings in the original
version of boto and we can remove our use of the fork.
This has been tested by running the celery app and seeing it connect to
sqs and grab messages off a queue.
We already use boto3 for our interaction with s3. Therefore if an expection is
thrown it will be thrown from the botocore library (which boto3 is built
on top of). This fixes an incorrect catching of a boto exception.
I have copied
app/aws/s3.py::file_exists for an example of this exception catching.
> use original `boto`

- app/models.py
- app/notifications/process_notifications.py
- app/v2/notifications/post_notifications.py
- migrations/versions/0315_document_download_count.py
- tests/app/db.py
- tests/app/v2/notifications/test_post_notifications.py
create a new `document_count` field in the Notification and NotificationHistory table. When someone posts with a document (or multiple documents), set it to a non-zero value. If someone posts without any documents, keep it set to null
There's an assumption that this will never be set to zero.
> Docs in the db

- app/authentication/auth.py
- app/errors.py
- requirements.txt
- tests/app/authentication/test_authentication.py
- tests/app/v2/notifications/test_post_notifications.py
Best reviewed commit by commit
For further context see https://github.com/alphagov/notifications-python-client/pull/156
- improves some of our error messages
- improves code comments of this pretty confusing section of our code
- adds some todos for bugs which I would like to fix in the future
I previously added functionality to the python client to give error messages which link to our REST api guidance
https://github.com/alphagov/notifications-python-client/pull/156/files#diff-e4bd66cc2ec07db666fac1080662df81R12
My mistake was that I assumed once the client had been bumped in the API, these new pretty messages would be shown to users. That is not the case as we don't actually pass through the exceptions message from the python client but instead write our own in here. Now I've had time …
> Catch uncaught JWT exceptions

- app/dao/dao_utils.py
we don't need it here - as exceptions are re-raised, they will be logged additionally by error handlers further up. All this exception logger tells us is that service names are already in use, which isn't something we're really interested in.
> remove error log from dao_utils

- app/authentication/auth.py
- app/config.py
- manifest.yml.j2
- tests/__init__.py
- tests/app/authentication/test_authentication.py
https://www.pivotaltracker.com/story/show/171352263 - but just does the admin client secret to start small, we can do the other as separate PRs once we are happy with this
https://github.com/alphagov/notifications-credentials/pull/143 to be merged first
Pull down this branch
In `app/config.py` change your development config to
`ADMIN_CLIENT_SECRETS = json.loads(os.environ.get('ADMIN_CLIENT_SECRETS', '[]'))`
```
export ADMIN_CLIENT_SECRETS='["key1", "key2"]'
./scripts/run_app.sh
```
Then open the admin app code and change the following
https://github.com/alphagov/notifications-admin/blob/master/app/config.py#L106
to be
`ADMIN_CLIENT_SECRET="key1"`.
Spin up your apps and log into the admin app, this will validate that it can talk using `key1`.
Then quit the admin app, change …
> Allow multiple keys for the `ADMIN_CLIENT_SECRET`

- app/aws/s3.py
- app/celery/letters_pdf_tasks.py
- app/config.py
- app/dao/notifications_dao.py
- tests/app/celery/test_letters_pdf_tasks.py
https://www.pivotaltracker.com/n/projects/1443052
Previously, when running the `collate_letter_pdfs_for_day` task, we
would only send letters that were created between 5:30pm yesterday and
5:30 today.
Now we send letters that were created before 5:30pm today and that are
still waiting to be sent. This will help us automatically attempt to
send letters that may have fallen through the gaps and not been sent the
previous day when they should have been.
Previously we solved the problem of letters that had fallen the gap by
having to run the task with a date parameter for example
`collate_letter_pdfs_for_day('2020-02-18'). We no longer need this date
parameter as we will always look back across previous days too for
letters that still need sending.
Note, we have to change from using the …
> Look at all previous days when sending letters

- tests/app/job/test_rest.py
At [some point](https://github.com/alphagov/notifications-api/pull/711) we moved from being able to schedule a job for up to 24 hours to 96 hours. The test was not renamed accordingly.
> Fix misnamed test

- app/dao/uploads_dao.py
- app/schemas.py
- app/upload/rest.py
- tests/app/dao/test_uploads_dao.py
- tests/app/job/test_rest.py
- tests/app/upload/test_rest.py
This is so we can display letter jobs in a different way on the admin app (because it doesn’t make sense for them to have failed/delivered counts like it does for email and text message jobs).
As elsewhere we use `fields.Method` to avoid serializing the whole template object.
> Return template type for jobs

- app/dao/fact_billing_dao.py
- app/dao/organisation_dao.py
- app/organisation/rest.py
- app/status/healthcheck.py
- tests/app/dao/test_ft_billing_dao.py
- tests/app/db.py
- tests/app/organisation/test_rest.py
- tests/app/platform_stats/test_rest.py
Add queries to handle returning usage for all services associated to a given organisation.
Only data for live services are returned. 
Added an endpoint to retrieve the organisation usage data. The endpoint may need to change, but I'd like to test it on a real data set. Once we are happy with the performance, I'll come back for validate the dataset has everything it needs and write all the tests. 
We were populating ft_billing for "yesterday" and "today", but I have decided to remove "yesterday". The only reason to include "yesterday" is so that the reports are accurate after midnight and before 02:00, but I think the performance gain is more important than the off chance someone is going to use the report that early in the morning
> Organisation usage

- app/dao/fact_billing_dao.py
- app/notifications/process_notifications.py
- tests/app/dao/test_ft_billing_dao.py
The dict is initialised for all live services, but if the organisation has trial mode services they cause a key error.
> Fix bug on organisation-usage page.

- app/notifications/validators.py
- app/v2/notifications/post_notifications.py
- tests/app/notifications/test_validators.py
- tests/app/v2/notifications/test_post_notifications.py
This PR changes validation away from `upload_document` service permission and towards checking if service has provided contact details for the feature.
Connected to PR: https://github.com/alphagov/notifications-admin/pull/3307 (they should go out around the same time)
Story ticket: https://www.pivotaltracker.com/story/show/171254127
> All services can send files by email if they have set contact_link

- app/dao/uploads_dao.py
- app/upload/rest.py
- tests/app/dao/test_uploads_dao.py
- tests/app/upload/test_rest.py
If your caseworking system always spits out files with the same name it will be hard to differentiate them when looking at the uploads page.
Seeing who the letter was sent to will help you differentiate them.
We can’t do this until the API returns the recipient.
> Return recipient for letter uploads

- app/service/send_notification.py
- tests/app/service/test_send_pdf_letter_notification.py
Soon enough every service will have this permission, and they won’t be able to switch it off. So we should clean up our codebase and make it so there’s no dependancy on a row existing in the permissions table.
This is the first step of that process for the API. Before we can remove it, we have to stop checking from it. Next step will be to stop inserting the permission, then finally remove it from the database.
We can actually ship this before #2726 and #2727 if we want to, the order doesn’t really matter.
> Remove check on permission to upload letters

- app/dao/services_dao.py
- tests/app/dao/test_services_dao.py
- tests/app/service/test_rest.py
This will switch on this feature for new services.
After this we will:
- give existing services this permission with a database migration
- remove this permission from the codebase entirely so that everyone has this feature and can’t switch it off
> Give new services the upload letters permission

- app/config.py
- gunicorn_config.py
- manifest.yml.j2
We moved from sending statsd metrics to hosted graphite to sending to
one that is running on the paas. Therefore we no longer need to send
statsd metrics to a particular prefix at the statsd app as it is only
receiving statsd metrics from our apps (not other users like would have
been the case with HostedGraphite).
This should change no behaviour as the only place the environment
variable was being used was in the gunicorn config and it was an empty
string which is the default behaviour anyway as per:
https://docs.gunicorn.org/en/stable/settings.html#statsd-prefix
Will test by deploying to preview and then checking metrics are being sent to statsd OK and no errors in logs
> Remove unused statsd_prefix variable

- app/dao/returned_letters_dao.py
- app/service/rest.py
- tests/app/dao/test_returned_letters_dao.py
- tests/app/service/test_rest.py
Currently the dashboard in the admin app pull the entire returned letter summary for a service to calculate how many letters have been returned in the last seven days.
Adding a separate endpoint for this purpose is better because:
- it’s a more efficient query
- it’s less data to send down the pipe
- it gives us a place to return the complete datetime, so the dashboard can be more precise about when the most recent report was
> Add an endpoint to return returned letter stats

- app/template/rest.py
- tests/app/template/test_rest.py
https://www.pivotaltracker.com/story/show/171130095
As suggested by the story, 'The code path for the notifications page goes via the API (whereas the upload page goes straight to the template preview app). We should probably investigate if it still needs to do this. It would be nice if the viewnotification page called the TemplatePreview.from(in)valid_pdf functions. '
I did look into this here which is a very rough draft:
https://github.com/alphagov/notifications-admin/compare/template-preview-page?expand=1
I managed to get it working but it seemed like it would be more work and this is all fairly complex already so didn't want to change too much in one go. Would potentially involve moving a bunch of functionality into utils or having things not very DRY. This PR instead seems like a …
> Only add overlay for pages which are invalid for precompiled letters uploaded via the API

- app/authentication/auth.py
- app/notifications/rest.py
- app/notifications/validators.py
- requirements-app.txt
- requirements.txt
- tests/app/notifications/rest/test_send_notification.py
- tests/app/notifications/test_validators.py
- tests/app/service/test_send_one_off_notification.py
- update check_sms_content_char_count to use the SMSTemplate.is_message_too_long function, and updated the error message to align with the message returned by the admin app.
- Update the the code used by version 1 of the api to use the validate_template method.
- I did find a couple of services still using the old api, however, this change should not affect them as I checked the messages being sent and they are not too long.
- We will be sending a message to them to see if they can upgrade.
- Update the log message for authenication to include the URL - makes it easier to track if a service is using version 1 of the api.
> Update validators to use is_message_too_long()

- app/dao/uploads_dao.py
- tests/app/dao/test_uploads_dao.py
This PR limits uploads we pass to Uploads page (both jobs and uploaded letters) to those within service data retention period for that notification type.
Story ticket: https://www.pivotaltracker.com/story/show/171623239
> Find only uploads within service data retention period

- app/organisation/invite_rest.py
- tests/app/organisation/test_invite_rest.py
We want to start granting access to the org page. But it will be a bit weird if the invites come from us personally, since the people we’re inviting don’t know us.
It makes more sense, and sounds more official if the invites appear to come from the ‘GOV.UK Notify team’ instead.
***
How this will look in the email:
> Let the Notify team invite people to an organisation

- app/template/rest.py
- tests/app/template/test_rest.py
https://github.com/alphagov/notifications-api/pull/2742/files#diff-d9a6761afaff4a491e60b64f6063654fL265
introduced a change in behaviour which causes template preview to 500
for a precompiled letter that is invalid but not because the content is
outside the printable area.
The changes it back to the previous behaviour, where we b64encode and
utf-8 decode for a page that is invalid for reasons that are not content
outside the printable area, for example a non portrait a4 letter.
I didn't end up writing a unit test for this because I really can't
figure out the existing behaviour we expect for this use case. This
method is too big and complex but I'm confident by looking at the change
in the commit mentioned above that this puts behaviour back to how it
was. Manual testing also confirms the …
> Undo bug for previewing precompiled letters

- migrations/versions/0317_uploads_for_all.py
This gives the feature to all existing users.
Depends on: 
After this we will:
- remove this permission from the codebase entirely so that everyone has this feature and can’t switch it off
> Give existing services upload letters permission

- app/dao/service_contact_list_dao.py
- app/models.py
- app/service/rest.py
- app/service/service_contact_list_schema.py
- migrations/versions/0318_service_contact_list.py
- tests/app/dao/test_service_contact_list_dao.py
- tests/app/db.py
- tests/app/service/test_service_contact_list_rest.py
Services want to be able to send emergency messages to their staff. This feature will allow the service to upload a csv file with a list of phone numbers or email address. The csv file is stored in S3, the service will then be able to send a templated email/sms to that list. 
- Table to store meta data for the emergency contact list for a service.
- Endpoint for fetching contact lists for service
- Endpoint for saving contact list for service.
> New table and endpoints for service contact lists

- app/dao/jobs_dao.py
- app/job/rest.py
- app/schemas.py
- tests/app/job/test_rest.py
A new feature to allow services to upload emergency contact list has been built. This adds the new contact_list_id to the schema, so it can be updated and returned from the endpoints, to created and get job.
> Update jobs contact list

- app/celery/scheduled_tasks.py
- tests/app/celery/test_scheduled_tasks.py
Fix serialisation error when creating the `create_letters_pdf` in `resend_created_notifications_older_than`
> Fix serialisation error

- app/celery/letters_pdf_tasks.py
- tests/app/celery/test_letters_pdf_tasks.py
The idea is to log the exception but keep going. That way the "good" files still get sent and we can investigate why a file failed.
> Add a try/except around the code to get the files.

- app/celery/tasks.py
- requirements-app.txt
- requirements.txt
- tests/app/celery/test_tasks.py
Story ticket: https://www.pivotaltracker.com/story/show/171622677
We are formatting the postcode here, because if we did it in template
preview, that could break flows like API and admin one-off, since
we are not validating postcode there yet, and format_postcode
needs a nice validated postcode.
We are not doing it in admin, as then we would have to either
rewrite the CSV file or pass data differently to API. First would
be nasty, second is a lot of overhead.
In the long run we might want to move postcode formatting to
template preview so that the postcode in letter preview looks the same
before and after user sends it, but now to get it out quickly it's better
to format the postcode here in the task (if we did it in template preview now,
it would also try to format postcode for API flow …
> Format postcode for CSV letter rows

- app/celery/process_sms_client_response_tasks.py
- app/config.py
- app/notifications/notifications_sms_callback.py
- app/notifications/process_client_response.py
- scripts/paas_app_wrapper.sh
- tests/app/notifications/rest/test_callbacks.py
- tests/app/notifications/test_process_client_response.py
- tests/app/test_config.py
This moves the code from the `process_sms_client_response` function to a new `process_sms_client_response` task. The task will use a new queue, `sms-callbacks`, which the `delivery-worker-receipts` will watch.
The task essentially does the same things, with one or two minor differences, e.g. since the work is being done in a task, we can no longer return a success message from the `/notifications/sms/firetext` and `/notifications/sms/mmg` endpoints.
https://www.pivotaltracker.com/story/show/171791142
> Add a task to handle SMS responses

- manifest.yml.j2
This should add an extra 1000 connections maximum, which will not tip us over the allowable 5000 db connections. And it may help with the queue pool connection errors.
> Increase the queue pool size to 30.

- app/dao/notifications_dao.py
insert/update, and then delete notifications in hourly batches. This
means that if the task gets interrupted part-way through, we'll have at
least something to show for it. Previously we would insert and update
into the history table but might not delete from the notification table
properly.
Keeping the offsets and limits for confidence around reliability and
queries timing out.
Keeping the join to notification_history to ensure we don't delete
anything prematurely while our DB is in a bit of a weird state with lots
of these tasks failing over the last week.
> Delete stmt order by and hour separate

- app/dao/notifications_dao.py
- tests/app/dao/notification_dao/test_notification_dao_delete_notifications.py
- tests/app/db.py
Refactor delete_notifications_older_than_retention_by_type to use a new strategy.
The insert_notification_history_delete_notifications function uses a temp table to store the data to insert and delete. This will save extra queries while performing the insert and delete operations.
The function is written in such a way that if the task is stop while processing when it's started up again it will just pick up where it left off.
I've made a decision to delete all test data in one query, I don't anticipate a problem with that.
The performance of this might also be better than last nights test because we are inserting everything we need for the NotificationHistory insert, so we don't need the join to Notifications to perform the insert.
> Refactor delete_notifications_older_than_retention_by_type 

- app/aws/s3.py
- app/config.py
- app/dao/jobs_dao.py
- app/dao/service_contact_list_dao.py
- app/models.py
- app/service/rest.py
- migrations/versions/0319_contact_list_archived.py
- tests/app/dao/test_service_contact_list_dao.py
- tests/app/db.py
- tests/app/job/test_rest.py
- tests/app/service/test_service_contact_list_rest.py
This was one of things we de-scoped when we first shipped this feature.
In order to safely delete a list, we first need to make sure any jobs aren’t referencing it.
Then we can remove the CSV file itself from S3.
> Add an endpoint to delete a contact list

- app/celery/process_ses_receipts_tasks.py
- app/celery/tasks.py
- app/dao/notifications_dao.py
- app/notifications/notifications_ses_callback.py
- tests/app/celery/test_process_ses_receipts_tasks.py
- tests/app/dao/notification_dao/test_notification_dao.py
- tests/app/dao/notification_dao/test_notification_dao_delete_notifications.py
Delete notifications for all notification_status types.
This will ensure the whole day has been deleted. The stats table could get the wrong updates if there is partial data for a day.
Why?
If there is partial data for a day the reporting tasks for a service can be off. This corrects that by deleting an entire day. 
Also in the PR is a refactor of process_ses_receipt.
Why?
It is possible a service has data retention that is smaller than the time it takes to get a delivery receipt.
This PR refactors process_ses_receipt to update NotificationHistory if the Notification has already been purged.
Also removed some logging, I don't recall ever looking for `SES delivery failed: notification id` log message. It doesn't tell me anything that I can't get from the db.
Also removed a duplicate log in …
> Fix report and delete tasks

- app/commands.py
- app/dao/services_dao.py
- tests/app/dao/test_services_dao.py
* it doesn't delete service email reply to or letter contacts, or contact lists. I don't think the contact lists will ever be an issue but it doesn't hurt to add it to the list of things to remove.
* it doesn't remove users from organisations before deleting the users
there may be more tables that link to Service that should be deleted, but for now just add these ones that I could spot.
> fix purge functional test data task

- app/dao/organisation_dao.py
"if you want something done right, then do it yourself"
The ORM was building a weird and inefficient query to get all the users for a given organisation_id:
old query:
```sql
SELECT users.*
FROM users
WHERE (
EXISTS (
SELECT 1
FROM user_to_organisation, organisation
WHERE users.id = user_to_organisation.user_id AND
organisation.id = user_to_organisation.organisation_id AND
organisation.id = '63b9557c-22ea-42ac-bcba-edaa50e3ae51'
)
) AND
users.state = 'active'
ORDER BY users.created_at
```
Note the cross join on users_to_org and org, there are a lot of users in organisations on preview, as one is added every functional test run. Even though they're all filtered out and the query returns the correct data, it still does the nested loop under the hood.
new query:
```sql
SELECT users.*
FROM …
```
> fix the sql

- app/service/rest.py
- tests/app/service/test_rest.py
This is a more accurate error code. It also means we are sure that we get the right error in admin without checking the error message first.
Needs this PR to go in first: https://github.com/alphagov/notifications-admin/pull/3389
Story ticket: https://www.pivotaltracker.com/story/show/171785534
> Change error code for duplicate reply-to address to 409 meaning conflict

- migrations/versions/0320_optimise_notifications.py
Dropping unnecessary indexes on Notification and Notification_History
Create new composite indexes that should give queries better performance
Drop and create new indexes.
We are not running this migration on production because we want to run each one at a time.
Run this on staging then start run some load tests
> Optimise indexes

- app/dao/notifications_dao.py
- tests/app/dao/notification_dao/test_notification_dao_delete_notifications.py
Add team key to the notifications to delete/insert into notifications/notification_history
notifications created with team keys have not been moved and purged.
> Add team key to query

- app/dao/notifications_dao.py
The original intention was to increase the limit to 50K, which takes about 48seconds. 
10K rows takes 11 seconds.
> Increase default query limit to 50,000 from 10,000

- app/v2/errors.py
- app/v2/notifications/post_notifications.py
- tests/app/v2/notifications/test_post_letter_notifications.py
Validate and format postcode of a letter that we got through API POST request.
Story ticket: https://www.pivotaltracker.com/story/show/171622677
Should go in after: https://github.com/alphagov/notifications-api/pull/2748 as we are pulling in new version of utils there. Tests will fail until that PR is merged, too.
> Validate and format postcode for the API letter sending flow.

- tests/app/service/test_rest.py
As new financial year came, this test started failing, because it had no freezetime and billing stopped being for the right year.
> Add missing freezetime to a test

- Makefile
as it takes longer with 35 minimum instances
> Increase startup timeout to 15 minutes

- app/aws/s3.py
- app/celery/nightly_tasks.py
- app/celery/scheduled_tasks.py
- app/dao/notifications_dao.py
- tests/app/aws/test_s3.py
- tests/app/celery/test_nightly_tasks.py
- tests/app/celery/test_scheduled_tasks.py
- tests/app/dao/notification_dao/test_notification_dao.py
These tasks were not being used (1 had never been used). This deletes them and the functions that were used only used by these tasks.
> Delete two tasks that weren't being used

- app/celery/letters_pdf_tasks.py
- app/letters/utils.py
- app/v2/notifications/post_notifications.py
- tests/app/celery/test_letters_pdf_tasks.py
- tests/app/letters/test_letter_utils.py
This has been replaced by a new task, `sanitise-letter`, so this deletes the old task and ensures that when antivirus is not enabled locally we are calling `sanitise-letter`.
> Delete old 'process-virus-scan-passed-task'

- app/celery/tasks.py
- app/commands.py
- app/models.py
- app/notifications/process_notifications.py
- app/notifications/rest.py
- app/template/rest.py
- app/v2/notifications/post_notifications.py
- app/v2/template/post_template.py
- tests/app/celery/test_tasks.py
- tests/app/notifications/test_process_notification.py
- tests/app/v2/notifications/test_post_letter_notifications.py
- tests/app/v2/template/test_get_template.py
Text messages have placeholders in their body.
Emails have them in their subject line too.
Letters have them in their body, subject line and contact block.
We were only looking in the the body and subject when processing a job, therefore the thing assembling the letter was not looking in all the CSV columns it needed to, because it hadn’t been told about any placeholders in the contact block.
Fixing this means always making sure we use the correct `Template` instance for the type of template we’re dealing with. Which we were already doing in a different part of the codebase. So it makes sense to reuse that.
Turns out we fixed the same bug for email subjects over 3 years ago: 3ed9715
---
This commit also updates the API to check the contact block when validating the placeholders for …
> Look in all parts of a letter template to find placeholders

- app/v2/template/template_schemas.py
- tests/app/v2/template/test_post_template.py
The `body` field of the ‘preview a template’ endpoint should contain the content of the template with the placeholders replaced.
It should not be rendered into a plain text email, which does stuff like normalising newlines (so `\r\n` becomes `\n`). However the object that the `create_post_template_preview_response` function receives is an instance of `PlainTextEmailTemplate`. So we can’t just call `str()` on
it. Instead we need to call the `__str__` method of `WithSubjectTemplate` which gives us the result we want.
We were already doing this the right way in the V1 endpoint<sup>1</sup> but forgot to do it here too.
***
1. https://github.com/alphagov/notifications-api/blob/0108749daa9885e000ad0ea222692b799ff59338/app/template/rest.py#L181-L184
> Ensure correct object renders V2 template preview

- app/models.py
- app/schema_validation/__init__.py
- migrations/versions/0321_update_postage_constraint_1.py
- migrations/versions/0322_update_postage_constraint_2.py
- migrations/versions/0323_update_postage_constraint_3.py
- tests/app/service/test_rest.py
- tests/app/v2/notifications/test_post_letter_notifications.py
The `notifications`, `notification_history`, `templates` and `templates_history`
tables all had a check constraint on the postage column which specified
that the postage had to be `first` or `second` if the notification or
template was a letter. We now have two more options for postage -
`Europe` and `rest of world`.
It's not possible to alter a check constraint, so the constraints have
to be dropped then recreated. We are not recreating the constraint on
the `notification_history` table since values here are always copied
from the `notifications` table.
The constraints get added as `NOT VALID` at first - this stage will lock
the tables, so updating the `notification` table and `templates` and
`templates_history` are done in separate migrations so that we don't lock
all tables at the same …
> Update postage db constraints for international letters

- app/celery/tasks.py
- app/schema_validation/definitions.py
- app/v2/notifications/notification_schemas.py
- app/v2/notifications/post_notifications.py
- requirements-app.txt
- requirements.txt
- tests/app/celery/test_tasks.py
- tests/app/v2/notifications/test_post_letter_notifications.py
This is part of moving away from `postcode` and towards `address line 7`
We think it will be easier for people to map their existing data to our API if we let them fill in any 3 lines, instead of requiring at least 1, 2, and postcode specifically.
***
This pull request also removes the reformatting of the postcode. We’re going to let template preview handle this when it’s rendering the PDF.
It’s better (and less code) to store what people give us, so we can give them back the same thing.
***
Depends on:
> Allow any three lines in the address for templated letters

- app/config.py
We are seeing issues with one of our providers. Move all traffic to the
other. We have done this with the provider load balancer, however this
will be reverted back 10 percent every hour to these resting points,
which we want to stop happening until we are confident our provider has
fixed their issues.
In the long run, we should add functionality to pause our load balancer
behaviour.
> Move provider resting balance as temporary measure

- app/models.py
- app/notifications/rest.py
- app/schemas.py
- app/template/rest.py
- app/utils.py
- app/v2/notifications/post_notifications.py
- app/v2/template/template_schemas.py
- requirements-app.txt
- requirements.txt
- tests/app/test_model.py
We’ve added some new properties to the templates in utils that we can use instead of doing weird things like `WithSubjectTemplate.__str__(another_instance)`
Depends on:
> Use new properties of utils Templates

- app/config.py
We temporarily updated the provider resting points in https://github.com/alphagov/notifications-api/pull/2804. This puts the provider resting points back to their original value now that both providers seem to be functioning well.
> Restore provider resting points

- app/celery/letters_pdf_tasks.py
- app/template/rest.py
- tests/app/celery/test_letters_pdf_tasks.py
We bumped version of utils here: https://github.com/alphagov/notifications-template-preview/pull/441
What we did not realise is that now template preview would require more information from API.
This PR fixes that omission.
Before:
After:
> Fix bug where preview for templated letters would not show

- app/celery/process_sms_client_response_tasks.py
- app/clients/sms/firetext.py
- app/dao/notifications_dao.py
- app/notifications/notifications_sms_callback.py
- tests/app/notifications/rest/test_callbacks.py
- tests/app/notifications/test_process_client_response.py
Currently, when we get first pending status, then permanent failure status from Firetext, we class it as temporary failure. But this is not always right. 
Hence, when we receive that succession of statuses, we will check for a code that tells us exactly what happened, so we know the status for sure.
Story ticket: https://www.pivotaltracker.com/story/show/171742892
Questions:
- maybe we would like to defer to the code every time we receive a failure from firetext?
- Since each code has a detailed explanation for failure, how about exposing those to our users? They often ask why messages failed, so more detailed explanation might help them with their work.
> Use firetext response code to see if temporary or permanent failure if available

- app/__init__.py
- gunicorn_config.py
- manifest.yml.j2
- requirements-app.txt
- requirements.txt
- tests/app/test_route_authentication.py
As per instructions https://github.com/alphagov/gds_metrics_python
The celery workers don't have an HTTP endpoint so no point in trying to
get prometheus to scrape them.
> Add GDSMetrics package

- app/clients/sms/firetext.py
- app/dao/notifications_dao.py
- tests/app/notifications/test_process_client_response.py
We should check error code on failure only, because if we get an
error code on pending code, we should still set the notification
to pending status.
> Check failure code on failure only.

- app/celery/scheduled_tasks.py
- tests/app/celery/test_scheduled_tasks.py
create-letters-pdf-tasks is for contacting template preview (synchronous web requests).
letters-tasks is for doing other things around letters (including putting things on template preview queue)
> make create_letters_pdf always use right queue

- app/celery/celery.py
- app/config.py
- manifest.yml.j2
The reporting worker tasks fetch large amounts of data from the db, do some processing then store back in the database. As the reporting worker only processes the create nightly billing/stats table tasks, which aren't high performance or high volume, we're fine with the performance hit from restarting the worker between every task (which based on limited local testing takes about a second or so).
This causes some real funky shit with the app_context (used for accessing current_app.logger). To access flask's global state we use the standard way of importing `from flask import current_app`. However, processes after the first one don't have the current_app available on shut down (they're fine during the actual task running), and are unable to call `with current_app.app_context()` to create …
> restart reporting worker after each task

- app/celery/tasks.py
- app/dao/notifications_dao.py
- app/notifications/process_letter_notifications.py
- app/notifications/process_notifications.py
- tests/app/celery/test_tasks.py
- tests/app/dao/notification_dao/test_notification_dao.py
- tests/app/service/test_rest.py
Like we have search by email address or phone number, finding an individual letter is a common task. At the moment users are having to click through pages and pages of letters to find the one they’re looking for.
We have to search in the `to` and `normalised_to` fields for now until we’ve been storing the normalised version for a few weeks.
At the moment we’re not consistent:
**Precompiled (API and one-off)**
`to` has the whole address
`normalised_to` has nothing
**Templated (API, CSV and one off)**
`to` has the first line of the address
`normalised_to` has nothing
This pull request makes us consistently store the whole address in the `to` field. We think that people might want to search by postcode, not just first line of the address.
This commit also starts to populate the …
> Let users search for letters

- app/celery/reporting_tasks.py
We've seen only some of these reporting tasks happen but with no log messages to indicate what happened and no app crashes. 
For example, here you can only see 10 log lines from our `create-nightly-notification-status-for-day` tasks but we are expecting 18 (10 days for letters, 4 days for text messages, 4 days for emails). 
https://kibana.logit.io/s/9423a789-282c-4113-908d-0be3b1bc9d1d/app/kibana#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-04-26T22:46:17.785Z',mode:absolute,to:'2020-04-27T08:15:23.893Z'))&_a=(columns:!(message,router.response_time,access.response_code,syslog_proc),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'logstash-*',key:cf.app,negate:!f,type:phrase,value:notify-delivery-worker-reporting),query:(match:(cf.app:( …
> Add in lots of logging to our reporting tasks

- app/notifications/receive_notifications.py
- tests/app/notifications/test_receive_notification.py
When we get an inbound message from MMG, the function format_mmg_date time was converting the date to UTC, however, the provider date is already in UTC format.
> Fix provider date for inbound SMS

- app/dao/fact_notification_status_dao.py
- tests/app/dao/test_fact_notification_status_dao.py
The '/service/monthly-data-by-service' endpoint which is used for the
'Monthly notification statuses for live services' Platform Admin report
did not including `pending` notifications. This updates the DAO function
that the endpoint calls to group `pending` and `sending` notifications together.
[Pivotal story](https://www.pivotaltracker.com/story/show/172474572)
> Include pending notifications in monthly data by service report

- app/user/rest.py
- pytest.ini
- tests/app/user/test_rest_verify.py
we're seeing issues with email clients sniffing links, and causing them to expire before the user gets a chance to click on them. Temporarily disable the expiry while we work on a more permanent solution.
NB: The link will still expire after twenty four hours.
> don't expire email sign in codes on use

- app/user/rest.py
- tests/app/user/test_rest_verify.py
reverts 789112a31f386c1db2378b2dcee8d16e31224735 (https://github.com/alphagov/notifications-api/pull/2831/)
however, keeps the changes to the tests as they were an improvement
> restore email sign in code expiry functionality

- app/celery/letters_pdf_tasks.py
- app/celery/tasks.py
- app/v2/notifications/post_notifications.py
- requirements-app.txt
- requirements.txt
- tests/app/celery/test_letters_pdf_tasks.py
- tests/app/celery/test_tasks.py
- tests/app/v2/notifications/test_post_letter_notifications.py
Changes:
- code change to how the `RecipientCSV` class should be instantiated
- functional changes to start applying different address validation if letters are allowed to be sent internationally
Depends on:
> Bump utils to 39.0.0

- app/dao/notifications_dao.py
- tests/app/dao/notification_dao/test_notification_dao.py
We were doing this temporarily while the `normalised_to` field was not populated for letters. Once we have a week* of data in the `normalised_to` field we can stop looking in the `to` field. This should improve performance because:
- it’s one `WHERE` clause not two
- we had to do `ilike` on the `to` field, because we don’t lowercase its  contents – even if the two where clauses are somehow parallelised it’s is slower than a `like` comparison, which is case-sensitive
I checked on production and no real services have custom data retention for letters.
***
Depends on:
> Stop searching the to field

- app/dao/notifications_dao.py
- app/service/rest.py
- tests/app/dao/notification_dao/test_notification_dao.py
- tests/app/service/test_rest.py
Things could get ugly if you use a short search string on a service with lots of notifications…
> Limit search by recipient to 50 results

- app/notifications/receive_notifications.py
- tests/app/notifications/test_receive_notification.py
This morning we raise a ParseError for a bad date format for the DateReceived attribute on the /notifications/receive/mmg request.
This PR tries to parse the date, if that throws an error return now as the DateReceived. This will at least allow the message to be persisted. Typically the DateReceived, provider_date, and the created_at date in the inbound_sms table are within a second of each other.
> Ignore Parse error in receive notifications endpoint

- app/clients/document_download.py
- app/v2/notifications/post_notifications.py
- tests/app/v2/notifications/test_post_notifications.py
This addresses the second & third piece in the change proposed to support sending `.csv` files in email notifications here: https://github.com/alphagov/notifications-python-client/issues/164
The first piece for this has already been merged: https://github.com/alphagov/document-download-api/pull/122
> Add support for CSV files

- app/dao/uploads_dao.py
- app/upload/rest.py
- tests/app/dao/test_uploads_dao.py
- tests/app/upload/test_rest.py
Some teams have started uploading quite a lot of letters (in the hundreds per week). They’re also uploading CSVs of emails. This means the uploads page ends up quite jumbled.
This is because:
- there’s just a lot of items to scan through
- conceptually it’s a bit odd to have batches of things displayed alongside individual things on the same page
So instead this pull request starts grouping together uploaded letters into pseudo-jobs. It does this by the date on which we ‘start’ printing them, or in other words the time at which they can no longer be cancelled.
This feels like a natural grouping, and it matches what we know about people’s mental models of ‘batches’ and ‘runs’ when talking about printing.
The code for this is a bit gnarly because:
- timezones
- the print cutoff doesn’t …
> Group letter uploads by printing day

- app/dao/jobs_dao.py
- app/job/rest.py
- app/models.py
- app/schemas.py
- tests/app/dao/test_jobs_dao.py
- tests/app/job/test_rest.py
- tests/app/service/test_service_contact_list_rest.py
At the moment jobs created from contact lists are ‘copied’. They appear as duplicates on the jobs page, but have count of sending/failed/delivered rather than just an overall count.
The only thing tying them back to the original contact list is the filename (even though  we store a relationship in the database).
It feels a bit richer to be able to see, for a given contact list, what messages (that is to say jobs) have been sent to that group of people. This pul request implements the extra arguments and fields the API needs to accept and return in order to display the jobs for a given contact list on that contact list’s page.
> Allow jobs to be grouped by contact list 

- app/models.py
- app/schema_validation/__init__.py
- migrations/versions/0321_update_postage_constraint_1.py
- migrations/versions/0322_update_postage_constraint_2.py
- migrations/versions/0323_update_postage_constraint_3.py
- tests/app/service/test_rest.py
- tests/app/v2/notifications/test_post_letter_notifications.py
_This is the same as https://github.com/alphagov/notifications-api/pull/2747, which was reverted except that it does not drop the constraint on `notification_history` in production since that has been done manually._
**Update postage db constraints for international letters**
The `notifications`, `notification_history`, `templates` and `templates_history`
tables all had a check constraint on the postage column which specified
that the postage had to be `first` or `second` if the notification or
template was a letter. We now have two more options for postage -
`europe` and `rest-of-world`.
It's not possible to alter a check constraint, so the constraints have
to be dropped then recreated. We are not recreating the constraint on
the `notification_history` table since values here are always …
> Update postage constraint (take 2)

- migrations/versions/0321_update_postage_constraint_1.py
- migrations/versions/0322_update_postage_constraint_2.py
The assumption that a commit is issued in between migration files was false. This will force the db connection to commit, the alter table commands will complete and the alembic version updated.
> Adding a commit at the end of each migration file.

- app/dao/services_dao.py
- app/dao/users_dao.py
- app/utils.py
- tests/app/service/test_archived_service.py
We were prefixing the service `name` and `email_reply_to` with `_archived_` when a service was archived. Since there are unique constraints on both these columns, this meant that archiving a service with the same name twice would cause an error.
This change copies what we do when archiving a user by prefixing these values with `_archived_{date}` instead. We would still see an error if a service with the same name gets archived more than once on the same day, but the chance of this happening is very low.
https://www.pivotaltracker.com/story/show/172955194
> Allow service to be archived if service with the same name has already been archived

- Makefile
- paas-failwhale/README.md
- paas-failwhale/manifest.yml
- paas-failwhale/nginx.conf
for use when we don't want API to serve any traffic, but paas is still running. It's a simple nginx_buildpack app that is pushed separately, and then two makefile commands that toggle the routes (and also stop/start the nginx app).
For all endpoints/methods it returns a 503, with the response body.
TODO: Some simple load testing - it's one instance with 256mb ram - is this enough to return simple messages to a high load of API users?
```
{
"status_code": 503,
"errors": [
{
"error": "PlannedMaintenanceError",
"message": "We’re performing some essential updates. Notify will be back shortly. Please check https://status.notifications.service.gov.uk/ for more details"
}
]
}
```
NB: If you hit `/` it'll still return 404 - as this is defined in the paas-proxy instance on aws.
> add api-paas-failwhale

- app/clients/email/aws_ses.py
- app/clients/sms/firetext.py
- app/clients/sms/mmg.py
we're using statsd to monitor how long provider requests are taking. However, there's lots of busy work that happens inside our statsd metrics timing window. Things like json dumping and loading, building headers, exception handling, etc. I'm worried that our metrics might not be telling us the true story of where slowness is.
for firetext/mmg, the response object from requests has an elapsed property [1], which captures from sending raw data to parsing the response headers. for ses, it's a bit trickier, but boto3 exposes a few event hooks [2]. it's hard to find them without stepping through the code, but the interesting ones are before-call, after-call, after-call-error, request-created, and response-received. The before-call and after-call involve some marshalling, built-in retrying, …
> add raw request timings to provider send functions

- requirements-app.txt
- requirements.txt
https://github.com/alphagov/notifications-utils/pull/742
We had been seeing phone numbers making it through in jobs containing
this no-break space which were then causing errors as we could not
process the job as it thought it was an invalid number. This should
solve the problem and strip that special character.
> Bump utils to 39.4.2 to fix whitespace strip bug

- app/celery/process_sms_client_response_tasks.py
- app/clients/sms/firetext.py
- app/clients/sms/mmg.py
- app/dao/notifications_dao.py
- app/notifications/notifications_sms_callback.py
- tests/app/clients/test_firetext.py
- tests/app/clients/test_mmg.py
- tests/app/notifications/rest/test_callbacks.py
- tests/app/notifications/test_process_client_response.py
This PR starts logging detailed delivery status for MMG. 
This is a good start, but I think we should do more (in a separate PR):
1. we should add a `detailed_status` for notifications in the database and save this additional info there.
2. we should then see what is the break down of delivery errors we get. There are a few errors in particular that we should look out for:
- "2053": "Source address blacklisted" <--- could mean us or MMG are on some blacklist
- "29": "Invalid delivery report" <--- we don't really know if message has been delivered or not
- "11": "Sender id not registered" <--- I don't think this one is very likely, the full description is: "Your account is set to accept only registered sender IDs, and the sender ID defined in the
request has not been registered on your …
> Capture detailed delivery receipt status from MMG

- app/celery/process_sms_client_response_tasks.py
- tests/app/notifications/test_process_client_response.py
This is done to see if lack of detailed status is us not recognising a code or provider not having sent the detailed status.
It seems like Firetext is sometimes sending us permanent-failure without detailed status. It could be due to:
- them really not sending any detailed status
- them sending a status code we don't recognise
- them sending 000 code that means 'no errors', which we ignore
To see which one it is, and to debug such issues quicker in the future, this PR adds status and detailed status codes to the logs.
> Put status codes in logs 

- app/__init__.py
- app/celery/process_ses_receipts_tasks.py
- app/clients/email/aws_ses_stub.py
- app/config.py
If we set a value for `SES_STUB_URL` environment variable, we can stub out calls to SES and send
them to our own stub app. If the environment variable is not set, things
work as normal.
To be used alongside
https://github.com/alphagov/notifications-email-provider-stub/pull/1
How to test:
1. Run the email stub locally - https://github.com/alphagov/notifications-email-provider-stub/tree/email-stub
2. Then run this app
```SES_STUB_URL=http://localhost:6301/ses ./scripts/run_celery.sh``` plus the HTTP API server and the admin app
3. Visit http://localhost:6012/ and trigger the admin app to send an email.
4. Check the notification just created in your DB now has a UUID set as it's reference (it's the one generated by the email provider stub).
When `SES_STUB_URL` is not set, the app should work …
> Stub SES email client to avoid hitting SES during load testing

- app/config.py
This is done to avoid sending real email and sms and incurring
unnecessary charges while we run the soak tests.
> Point API for staging at email and sms stubs for the soak tests.

- app/config.py
To check if it was our congestion point for the soak test.
(Email stub is a bit slower to respond than Amazon SES, and the difference could lead to us having to many connections to db open as we wait for response from the stub)
I'm only commenting it out as we are continuing soak testing and may turn it back on, and we can delete it fully when we are getting rid of the variables for sms provider stub.
> Turn off email stub on staging

- app/schemas.py
- tests/app/service/test_rest.py
By default Marshallow includes unknown properties when serialising a model to JSON. This means every time a new property is added to the service model it gets included in the JSON-serialised response sent to the admin app.
This is particuarly bad because it means that for returned letters the ID of every returned letter. So the JSON stored in Redis for the Check Your State Pension service is 86kb.
Similarly the JSON stored in Redis for a big user of inbound text messaging is 458kb(!!!) because it has the ID of every received text message. That’s ~8,500 UUIDs.
Luckily the admin app tells us exactly which keys it’s using here: https://github.com/alphagov/notifications-admin/blob/5952d9c26da749e39d761e0d37dd72876e59fa6d/app/models/service.py#L31-L52
- `active`
- `contact_link`
- …
> Serialise less stuff from the service model

- app/notifications/process_notifications.py
- app/v2/notifications/create_response.py
- app/v2/notifications/post_notifications.py
- tests/app/notifications/test_process_notification.py
- tests/app/v2/notifications/test_post_notifications.py
In the effort to reduce the number of queries to the database this PR removes the need to fetch the notification and service after the commit when persisting the notification, this releases the db connection back to the connection pool.
If you look at the queries made during the POST /notification/email or sms you should see no new queries made after the insert into notifications transaction.
The letter flow will need some more work in order to remove the need for the db after the notification insert. This PR prioritises the email and sms flow first.
> Reduce the use of db connections

- app/config.py
We have seen bad latency across all apps in the last week. After running
a canary with statsd turned off we have seen these issues dissapear on
that canary instance. We therefore will turn off statsd for all
instances of the API. We will still need to investigate tomorrow what
exactly changed or is causing the issue with statsd as we hadn't made
any changes to it ourself.
Note, this keeps statsd on for all the other apps but this will be a
first step. We will also need to check performance of the other apps
after releasing this.
> Turn off statsd for the API in all environments

- app/notifications/process_letter_notifications.py
- app/notifications/process_notifications.py
- app/v2/notifications/post_notifications.py
- tests/app/v2/notifications/test_post_letter_notifications.py
In the effort to reduce the number of database connections I introduced a small bug. This only affected the test templated letter flow, a None type error would happen when trying to creathe `completed_at` timestamp for a `delivered` message.
In the previous PR I removed the `update_notification` method to reduce the need for another update query. However, that meant the notification was marked as delivered without an updated_at timestamp.
It is weird to set the updated_at when we create the notification. So is this a better fix? Or do I put the update back now?
I recommend we push this fix now.
> Fix error for get_notification_by_id when the updated_at is None for a delivered test message

- app/config.py
- requirements-app.txt
- requirements.txt
see https://github.com/alphagov/notifications-utils/pull/752 for implementation details. Cache DNS for 15 seconds. Note: This cache is per eventlet, so concurrent requests will handle their requests separately, but the cache does persist between sequential requests.
re-enable statsd for all environments.
> re-enable statsd (and cache statsd DNS lookup)

- app/template/rest.py
- app/template/template_schemas.py
- app/v2/template/template_schemas.py
- tests/app/template/test_rest.py
- tests/app/v2/template/test_template_schemas.py
We will remove the postage constraint from the `templates` and `templates_history` tables to be consistent with the `notifications` and `notification_history` tables. Before we can do this we need to validate postage in the code. This adds a JSON schema to the update template endpoint and updates the existing schemas which had postage in to check that postage is in the right format.
> Update template schemas to validate postage

- app/models.py
- app/schema_validation/__init__.py
- migrations/versions/0321_drop_postage_constraints.py
- tests/app/dao/test_templates_dao.py
- tests/app/service/test_rest.py
- tests/app/template/test_rest.py
- tests/app/v2/notifications/test_post_letter_notifications.py
We've decided to drop the postage constraints, so this adds a migration to do that (the constraint on notifications and notification_history has already been dropped in production and preview).
Also removes a few tests that are no longer needed and updates the JSON schemas for the new postage values we want to allow.
> Drop postage constraints

- app/notifications/rest.py
- app/notifications/validators.py
- requirements-app.txt
- requirements.txt
- tests/app/notifications/rest/test_send_notification.py
- tests/app/notifications/test_process_notification.py
In this PR we make sure that people without international sms permission can send to crown dependencies after we start treating those numbers as international here: https://github.com/alphagov/notifications-utils/pull/749
A Jersey (tv) number, and my (standard UK) number, both sent to successfully, from a service without international sms permission, and with correct flags resulting in correct providers used:
TODO: Import this version utils once they are merged: https://github.com/alphagov/notifications-utils/pull/749
Tests will fail without it.
> Make sure people without international sms permission can send to crown dependencies

- app/schemas.py
- app/template/rest.py
- tests/app/template/test_rest.py
Content and subject are user-submitted so are effectively unbounded in size. And we’re serialising them for every template when sending the list of templates to the admin app.
For the service with the most templates this results in a 1.3Mb blob of JSON going over the wire, and being cached in Redis.
And then the admin app completely ignores these fields, because it does not show template content until you’ve clicked into a single template.
This commit adds a new query parameter, `detailed`, that the admin app can set to `False`. When it does only the fields needed to render the `/templates` page are returned.
This is done with a new parameter so as not to break the V1 API. Although I looked in Kibana and it doesn’t seem like anyone external is using this endpoint we’ve come this far …
> Exclude unneeded fields from all templates response 

- app/schemas.py
We were already excluding `created_by`, but in a different branch we renamed the property on the schema to `created_by_id`: https://github.com/alphagov/notifications-api/pull/2873/files#diff-691350bfe8029e08252edaad69e871b9R346-R348
We need to rename it in the exclude list to make sure that this assertion still passes:
https://github.com/alphagov/notifications-api/blob/14e7b6b87e4f525d1363a28e2b91882423d513b1/tests/app/template/test_rest.py#L555-L560
> Exclude created_by_id from TemplateSchemaNoDetail

- app/schemas.py
- app/serialised_models.py
- tests/app/v2/notifications/test_post_notifications.py
This pull request caches just the serialised template object or dictionary in memory and Redis respectively.
It should improve performance for high volume services by releasing the DB connection more quickly.
> Cache serialised template in Redis and in memory

- app/serialised_models.py
- tests/app/v2/notifications/test_post_notifications.py
For some reason our V1 get template response wraps the whole template in a dictionary with one key, `'data'`:
https://github.com/alphagov/notifications-api/blob/0d990338893cd0e82e7415e424669f150297be0c/app/template/rest.py#L166
That means when the admin app caches the response it also caches it in this format.
The API needs to do the same, otherwise it will be cacheing data with a schema that the admin app isn’t expecting, and vice-versa.
> Ensure templates are cached with correct schema

- app/schemas.py
The admin app doesn’t use them: https://github.com/alphagov/notifications-admin/search?q=letter_contact_block&unscoped_q=letter_contact_block
Instead it requests them separately when needed: https://github.com/alphagov/notifications-admin/blob/2f1e8b104b0f8c76e14ba0d0159d0fcaf95a7046/app/models/service.py#L349-L351
Removing this from the response means one fewer database query.
Depends on:
> Don’t return letter contact blocks in service JSON

- app/__init__.py
- app/dao/notifications_dao.py
- app/models.py
- app/notifications/process_notifications.py
- app/notifications/validators.py
- app/v2/notifications/create_response.py
- app/v2/notifications/post_notifications.py
- tests/app/dao/notification_dao/test_notification_dao.py
- tests/app/db.py
- tests/app/notifications/test_process_notification.py
- tests/app/v2/notifications/test_get_notifications.py
- tests/app/v2/notifications/test_post_notifications.py
Years ago we started to implement a way to schedule a notification. We hit a problem but we never came up with a good solution and the feature never made it back to the top of the priority list.
This PR removes the code for scheduled_for. There will be another PR to drop the scheduled_notifications table and remove the schedule_notifications service permission
Unfortunately, I don't think we can remove the `scheduled_for` attribute from the notification.serialized method because out clients might fail if something is missing. For now I have left it in but defaulted the value to None.
> Remove the use of schedule_for in post_notifications

- app/authentication/auth.py
- app/config.py
- app/notifications/process_notifications.py
- app/notifications/validators.py
- app/schemas.py
- app/serialised_models.py
- app/service/send_notification.py
- app/service/utils.py
- app/template/rest.py
- app/v2/notifications/post_notifications.py
- requirements-app.txt
- requirements.txt
- tests/app/authentication/test_authentication.py
- tests/app/notifications/test_validators.py
- tests/app/v2/notifications/test_post_notifications.py
Similar to the approach we’ve taken for templates, which has shown some performance improvement when we’re under load (red dotted line is when the caching of templates was deployed):
– | Serialise after fetching | Cache in Redis | Cache in memory 
---|---|---|---
**Templates** | Done | Done | Done
**Services** | This PR | This PR | This PR
**API keys** | This PR | Nope<sup>1</sup> | This PR
***
1. We’re not comfortable putting the API key secrets in Redis. In the future we might try encrypting them so it’s safe to do so, but have decided not to for now because we don’t have an existing pattern in the codebase for doing symmetric encryption.
> Serialise and cache services and API keys

- app/authentication/auth.py
- app/notifications/process_notifications.py
- app/notifications/validators.py
- app/serialised_models.py
- app/service/send_notification.py
- app/service/utils.py
- app/template/rest.py
- app/v2/notifications/post_notifications.py
- tests/app/authentication/test_authentication.py
- tests/app/notifications/test_validators.py
- tests/app/v2/notifications/test_post_notifications.py
By serialising these straight away we can:
- not go back to the database later, potentially closing the connection sooner
- potentially cache the serialised data, meaning we don’t touch the database at all
Branched off, and using the same techniques as:
> Serialise service, API keys and permissions at start of post notifications endpoint

- app/serialised_models.py
We changed `app/auth.py` to import from `app/serialised_models.py` here: https://github.com/alphagov/notifications-api/pull/2887/files#diff-77cbb1e03185c7319f0311371c438b0cR11
So:
- `app/auth.py` imports from `app/serialised_models.py`
- `app/serialised_models.py` imports from `app/dao/templates_dao.py`
- `app/dao/templates_dao.py` imports from `app/dao/users_dao.py`
- `app/dao/users_dao.py` imports from `app/errors.py`
- `app/errors.py` imports from `app/auth.py`
- …and the circle is complete 💥
For some reason this caused the Celery workers to crash on startup, but not the app. Which I guess is why the integration tests didn’t catch this?
Check that the app and Celery workers start up OK when running locally.
> Fix circular import

- app/authentication/auth.py
- app/config.py
- app/notifications/process_notifications.py
- app/notifications/validators.py
- app/schemas.py
- app/serialised_models.py
- app/service/send_notification.py
- app/service/utils.py
- app/template/rest.py
- app/v2/notifications/post_notifications.py
- requirements-app.txt
- requirements.txt
- tests/app/authentication/test_authentication.py
- tests/app/notifications/test_validators.py
- tests/app/service/test_rest.py
- tests/app/v2/notifications/test_post_notifications.py
We need to ensure that `rate_limit` is in the serialised service before we start using it to power the `POST` notifications endpoint.
> Revert serialisation changes

- app/commands.py
A command to get letter data based on a list of filenames provided by DVLA.
This is done so that we could try to help narrow down what is causing failed print runs at DVLA
> Get letter data for provided filenames

- app/authentication/auth.py
- app/config.py
- app/notifications/process_notifications.py
- app/notifications/validators.py
- app/schemas.py
- app/serialised_models.py
- app/service/send_notification.py
- app/service/utils.py
- app/template/rest.py
- app/v2/notifications/post_notifications.py
- requirements-app.txt
- requirements.txt
- tests/app/authentication/test_authentication.py
- tests/app/notifications/test_validators.py
- tests/app/v2/notifications/test_post_notifications.py
This PR brings back https://github.com/alphagov/notifications-api/pull/2887
It also adds `rate_limit` and `message_limit` to SerialisedService because the API needs these to check whether a service can send a notification.
These fields will be in the Redis-cached service after https://github.com/alphagov/notifications-api/pull/2903 is deployed to production and the cache is cleared.
This PR also updates all the tests in `test_validators.py` to take a serialised service, not a database object, which is why we missed this problem the first time around.
> Validate from serialised model

- app/schemas.py
- tests/app/v2/inbound_sms/test_get_inbound_sms.py
Because the IDs of our callback and inbound SMS APIs were stored in lists instead of directly on the serialised model they weren’t getting cast to a string before trying to JSONify them. And JSON doesn’t know what to do with a UUID object.
For some reason this was only affecting the endpoint for fetching inbound SMS.
> Fix serialisation of callbacks

- app/schemas.py
- tests/app/template/test_rest.py
This PR reverts commit 58a9862, which tried to optimise the fetch template query by not doing a separate select from the users table.
However it had the side effect of making Marshmallow ignore `created_by` when loading the JSON in the post request. So the field on the model was never being updated, just copied from the original template.
The quick way of getting things to work again is to revert this optimisation.
There’s probably some Marshmallow magic we could use to avoid the extra query and still have created_by not be ignored.
It does mean we’re introducing an extra query, but I’m not too fussed about that since the caching seems to be working well.
The test I’ve added fails with the existing code that’s on master:
> Fix template history created by

- app/notifications/validators.py
- tests/app/service/test_send_one_off_notification.py
This was broken because sometimes `service.permissions` is a list of strings (when we’ve caching the service object) and sometimes it’s a list of permission objects (when we’re dealing with ORM objects).
Because the validator code is shared, the least-messy way to fix it is to make sure it can handle both types.
It can’t just take a list of permissions as argument, because it uses other fields on the service.
It would be messy to rewrite the endpoint to use a serialised service because the tests all expect to be dealing with database objects, so it would be a faff to change what they’re mocking.
> Fix sending one-off international text messages

- app/delivery/send_to_providers.py
- tests/app/delivery/test_send_to_providers.py
This prevents a race condition when we get delivery receipt before updating notification to sending, and so the sending status would supersede the delivered status, and the notification would time out as temporary-failure after three days.
> Do not update notification to sending if the status is already final

- app/dao/templates_dao.py
- app/models.py
- app/schemas.py
- app/serialised_models.py
- app/service/statistics.py
- app/utils.py
- app/v2/notifications/notification_schemas.py
- app/v2/template/get_template.py
- app/v2/templates/get_templates.py
- migrations/versions/0323_broadcast_message.py
- tests/app/template/test_rest.py
- tests/app/test_model.py
- tests/app/v2/template/test_get_template.py
- tests/app/v2/template/test_post_template.py
- tests/app/v2/templates/test_get_templates.py
- tests/app/v2/templates/test_templates_schemas.py
this is the trickiest bit of this PR, if only because lots of places refer to template_type all over the place. I think I've caught everywhere, but not sure. This also involved resurrecting enum migration code from https://github.com/alphagov/notifications-api/blob/master/migrations/versions/0060_add_letter_template_type.py
this'll contain everything that we need to save on templates for a broadcast message. We don't know what that is yet, so it's just a jsonb field
BroadcastMessage model. A broadcast has a bunch of states - see the commit message for the proposed state diagram. I've tried to add as many timestamps/user ids in to the model, I wanted to avoid using an `updated_at` to refer to different things based on the state.
> Broadcast DB models

- app/serialised_models.py
ALLOWED_PROPERTIES is a list containing fields that it will attempt to deserialize into the returned object. If a field isn't present on the underlying data source (whether that's a dump from a marshmallow schema, a blob retrieved from redis, or anything else), then SerialisedModel will raise an exception. However, SerialisedModel isn't involved when setting the cache, so with that said the correct flow for adding a column to a cached database model:
PR #1
* add new column to DB
* add new column to model, and to template_schema (because that schema is used to create the dict that goes in to redis). New redis keys start getting populated.
Deploy that through, and then clear redis
PR #2
* add new column to SerialisedTemplate.ALLOWED_PROPERTIES. this means that it'll start reading that value …
> remove broadcast_data from SerialisedTemplate.ALLOWED_PROPERTIES

- app/broadcast_message/rest.py
- app/celery/broadcast_message_tasks.py
- app/config.py
- app/dao/broadcast_message_dao.py
- app/models.py
- tests/app/broadcast_message/test_rest.py
- tests/app/celery/test_broadcast_message_tasks.py
A new `send_broacast_message` task, triggered when a user hits approve (or send as it currently reads). doesn't trigger on cancellation yet.
the task takes a brodcast_message_id, and makes a post to the cbc-proxy for now, hardcode the url to the notify stub. the stub requires template as the admin/api get it, so use the marshmallow schema to json dump it. Note - this also required us to tweak the BroadcastMessage.serialize function so that it converts uuids in to ids - flask's jsonify function does that for free but requests.post doesn't sadly.
if the request fails (either 4xx or 5xx) just raise an exception and let it bubble up for now - in the future we'll add retry logic
> Send broadcast

- app/celery/letters_pdf_tasks.py
This will help us better understand how far through the task has got if
it gets interrupted halfway (as was the case this morning and we
struggled to understand).
> Add better logging to starting collate-letter-pdfs-to-be-sent

- app/config.py
- app/dao/fact_billing_dao.py
- app/dao/fact_notification_status_dao.py
- app/dao/inbound_sms_dao.py
- app/dao/jobs_dao.py
- app/dao/notifications_dao.py
- app/dao/services_dao.py
- manifest.yml.j2
- tests/app/dao/notification_dao/test_notification_dao.py
- tests/app/dao/test_jobs_dao.py
- tests/app/dao/test_services_dao.py
In this PR:
- remove statsd http api decorators (in effect those with namespace dao). We decided we do not use metrics for those endpoints at the moment so we can get rid of them, and reintroduce in Prometheus-friendly manner if there is such a need in the future.
- leave be statsd decorators for functions run by celery apps (those in app/celery folder and those in app/clients folder)
- turn statsd back on for all apps except notify-api, where it will remain turned off (the approach for doing this has been tested by deploying notify-api and one of the workers to preview and checking if the `STATSD_HOST` variable is set to None for notify-api and to host address for the worker)
> Remove statsd http api decorators and turn statsd back on for celery apps

- app/models.py
- tests/app/db.py
- tests/app/v2/template/test_get_template.py
This attribute has been requested by a user, and we have not been
serializing it so far.
Story ticket: https://www.pivotaltracker.com/story/show/173511626
> Add contact block to serialize template for v2

- app/celery/scheduled_tasks.py
- app/v2/errors.py
- tests/app/celery/test_scheduled_tasks.py
- tests/app/v2/test_errors.py
We have a scheduled task to check that all the jobs have completed, this will catch if an app is shut down and the job is complete yet, we only wait 10 seconds before forcing the app to shut down.
The task was raising a JobIncompleteError, yet it is not an error the task is performing correctly and calling the appropriate task to restart the job.
Also used apply_sync to create the task instead of send_task.
> Stop raising error in scheduled task

- app/models.py
- tests/app/service/test_service_contact_list_rest.py
At the moment we return a count of recent jobs for contact lists, where recent is defined as being within the service’s data retention period.
This lets us write nice bits of UI copy like ‘used 3 times in the last 7 days’. But it’s hard to write the copy for when the count is 0, because this could be for one of two reasons:
- the contact list has never been used
- the contact list has been used, but not within the data retention period for that channel
At the moment we can’t know which of those reasons is the case, so we can’t write nice clear content like ‘never been used’.
This commit adds a property to contact lists which says whether they’ve ever been used.
It also renames the existing, as-yet-unused property to make clear that it’s only counting within the data retention (so can …
> Add property to contact lists to say if they’ve ever been used

- app/broadcast_message/rest.py
- app/models.py
- tests/app/broadcast_message/test_rest.py
- tests/app/db.py
Review commit by commit.
* forbid editing after broadcast message goes live …
* refactor status updating into its own function …
* enforce kwargs when creating user in tests …
* allow platform admins to approve their own messages …
* reject approvals from people outside your service …
> Broadcast crud validation

- app/dao/broadcast_message_dao.py
- app/models.py
- app/utils.py
- migrations/versions/0326_broadcast_event.py
- tests/app/dao/test_broadcast_message_dao.py
- tests/app/db.py
- tests/conftest.py
It's clear that we need a way to track updates to a broadcast message. It's also clear that we'll need some kind of audit log that captures exactly what was sent out in a message.
This commit adds a new database table, `broadcast_event`, which maps 1:1 with CAP XML sent to the CBCs. We'll create one of these just before sending out.
The main driver for this was that cancel and update messages need to contain a list of references of all previous messages that they're amending. This is of format `{sender},{identifier},{sent_timestamp}`, and the identifier itself needs to be unique for each message.
--------
I've left lots of questions/thoughts in the comments
```python
broadcast_message = BroadcastMessage(
service_id=template.service_id,
template_id=template.id, …
```
> add broadcast_event table

- migrations/versions/0327_idx_notification_history.py
There are a few indexes that we still need to drop from prod notification_history. Indexes on prod can take too long to run in a migration so we need to run them manually.
Indexes on prod have been updated as of July 30
> This migration will bring all environments in line with the prod

- app/v2/notifications/post_notifications.py
- requirements-app.txt
- requirements.txt
- tests/app/v2/notifications/test_post_letter_notifications.py
These characters `@ ( ) = [ ] ” \ / ,` can't be used at the start of address lines
because they cause issues for DVLA. A method to check for these characters
was added here https://github.com/alphagov/notifications-utils/pull/771
This PR brings in the new version of utils and uses the method to add
validation for templated letters sent through the API.
[Pivotal story](https://www.pivotaltracker.com/story/show/173892353)
> Check for invalid characters in letter addresses

- app/service/rest.py
- tests/app/service/test_service_guest_list.py
The admin app will soon use the newer, `…/guest-list` URLs, so we can remove the older, deprecated, `…/whitelist` ones.
***
Depends on:
> Remove whitelist from URLs

- app/broadcast_message/rest.py
- tests/app/broadcast_message/test_rest.py
we won't let trial mode services send real broadcasts, and it's helpful for users to see the flow of messages without having to have a second person with them
> allow trial mode service users to approve their own broadcasts

- app/celery/letters_pdf_tasks.py
- app/celery/tasks.py
- app/notifications/process_letter_notifications.py
- app/notifications/process_notifications.py
- app/notifications/rest.py
- app/notifications/validators.py
- app/service/send_notification.py
- app/v2/notifications/post_notifications.py
- tests/app/celery/test_letters_pdf_tasks.py
- tests/app/notifications/rest/test_send_notification.py
- tests/app/notifications/test_process_notification.py
- tests/app/notifications/test_validators.py
- tests/app/service/test_send_one_off_notification.py
- tests/app/v2/notifications/test_post_letter_notifications.py
Make sure to set the postage and international flag correctly for all letters. 
There are many ways to send a letter with Notify:
1. send one-off templated letter
2. upload CSV for a templated letter
3. send template letter via the API
4. send PDF letter via the API
5. upload PDF via the UI
Possible postage types are first | second | europe | rest-of-world.
> Set international postage and international flag for international letters

- app/celery/tasks.py
- app/notifications/validators.py
- tests/app/celery/test_tasks.py
If the letter is outside of the United Kingdom, set the postage and international flag.
> Set postage and international for letters uploaded with a CSV

- app/accept_invite/rest.py
- tests/app/accept_invite/test_accept_invite_rest.py
- tests/app/test_config.py
The error message for when an invitation to Notify had expired was displaying in admin with square brackets round it because admin is not expecting the message to be a list (https://github.com/alphagov/notifications-admin/blob/a85134ee227a89fbe13ee470a7b74b69e01ad7e2/app/models/user.py#L500)
Before:
> Fix error message when invitation has expired

- app/celery/provider_tasks.py
- app/clients/email/aws_ses.py
- tests/app/celery/test_provider_tasks.py
- tests/app/clients/test_aws_ses.py
We have hit throttling limits from SES approximately once a week during
a spike of traffic from GOV.UK. The rate limiting usually only lasts a
couple of minutes but generates enough exceptions to cause a p1 but with
no potential action for the responder.
Therefore we downgrade the warning for this case to a warning and assume
traffic will level back out such that the problem resolves itself.
Note, we will still get exceptions if we go over our daily limit, rather
than our per minute sending limit, which does require immediate action
by someone responding.
If we were to continually go over our per second sending rate for a long
continous period of time, then there is a chance we may not be aware but
given the risk of this happening is low I think it's an acceptable risk
for the moment.
In …
> Log warning for SES send rate throttling rather than exception

- app/broadcast_message/rest.py
- app/celery/broadcast_message_tasks.py
- app/dao/broadcast_message_dao.py
- app/dao/dao_utils.py
- app/models.py
- requirements-app.txt
- requirements.txt
- tests/app/broadcast_message/test_rest.py
- tests/app/celery/test_broadcast_message_tasks.py
- tests/app/db.py
Now sends cancel messages.
When you click broadcasting or cancel, it creates new BroadcastEvents, and then sends them using the new send_broadcast_event task.
> Send events

- app/template/rest.py
- tests/app/template/test_rest.py
We were asking for the latest version of a letter template rather than
the version that the notification was sent with. This mean that if you
previewed a letter and had made edits to the template since it was sent
you would be shown an incorrect preview.
https://www.notifications.service.gov.uk/services/4493cb7d-b8c7-4fae-bc68-fc4619c71841/notification/ea1cc66e-8ea8-4456-a4fe-f4687ee29d7f
Was sent with template version 7 but we are trying to display it with the most recent template
> Fix bug with missing template version param

- app/invite/rest.py
- app/organisation/invite_rest.py
- tests/app/invite/test_invite_rest.py
- tests/app/organisation/test_invite_rest.py
We want to display flash messages in admin when invites have been
cancelled. This message needs to display the user's email address, so
this commit adds endpoints to GET a single invited service user and org
user so that we can look up the email address of a cancelled user.
[Pivotal story](https://www.pivotaltracker.com/story/show/174294749)
> Add endpoints to get invited users

- app/dao/fact_billing_dao.py
- tests/app/dao/test_ft_billing_dao.py
`international` for letters in `ft_billing` was always False. Now that letters can be international, this changes the column value to the value of `international` for the notification.
> Set 'international' for letters in ft_billing

- app/dao/services_dao.py
- tests/app/dao/test_services_dao.py
- tests/app/service/test_rest.py
Add international letters as a default permission when creating a new service.
To be followed up by https://github.com/alphagov/notifications-api/pull/2951. 
These are separate PRs because we need to add the default permission for new services before the data migration to catch any services being created between the data migration and code deployment.
> Default international_letters for service permissions.

- migrations/versions/0328_international_letters_perm.py
Add international_letters service permission for all services that have the letter permission.
This is part 2 of 2 PRs to allow all services to have the international letter service permission.
> Add international letter service permissions for all services

- app/dao/organisation_dao.py
- tests/app/dao/test_organisation_dao.py
When the organisation updates the crown attribute it should update all the services associated with that organisation too.
> Fix update organisations

- app/dao/notifications_dao.py
- tests/app/dao/notification_dao/test_notification_dao.py
Our code was assuming that any notifications with `international` set to `True` were text messages. It was then trying to look up delivery information for a notification which wasn’t sent to a phone number, causing an exception.
***
Need to cancel this letter after deploying: https://www.notifications.service.gov.uk/services/d6aa2c68-a2d9-4437-ab19-3ae8eb202553/notification/6420f6d8-0fc8-4574-8e30-7beda9abb86b
> Allow international letters to be cancelled

- migrations/versions/0331_add_broadcast_org.py
keep the ID the same as the existing prod broadcast org to keep things simple.
Move all services with a broadcast permission across to this new service. Note that we'll need to clear the service and organisation cache after deploying this.
> add broadcast org

- manifest.yml.j2
we might need to deal with a potential large volume of SMS delivery receipts. These receipts are POSTed to oru public api to two URLs. The actual endpoint just parses the response body and puts a task on an SQS queue - no database connections are required or anything like that.
Split up this traffic from other traffic, so that any increase in volume of callbacks won't affect the scaling/load/etc of the main api apps. We've hard coded instance counts to 10 on prod for now until we get an idea of load.
This is deployed on preview already if you want to test that it works properly.
> add notify-api-sms-callbacks app

- requirements-app.txt
- requirements.txt
Increases CSV row limit from 50,000 to 100,000
Changes: https://github.com/alphagov/notifications-utils/compare/42.0.0...42.2.0
> Bump utils to 42.2.0

- app/dao/jobs_dao.py
- tests/app/celery/test_scheduled_tasks.py
- tests/app/dao/test_jobs_dao.py
Since we’ve doubled the number of rows in a job, jobs can take twice as long to insert all the notifications. We don’t check for missing rows until we’re pretty confident that the original tasks have finished processing. This means we need to double the time we wait to still be as sure.
> Allow 20 minutes before checking for missing rows

- app/celery/scheduled_tasks.py
- tests/app/celery/test_scheduled_tasks.py
Adding reference to message for "precompiled letters have been pending-virus-check for over 90 minutes"
This saves having to go to the db to get it.
> Add reference to log message

- app/celery/letters_pdf_tasks.py
- app/dao/notifications_dao.py
- app/letters/utils.py
- app/service/send_notification.py
- tests/app/celery/test_letters_pdf_tasks.py
- tests/app/letters/test_letter_utils.py
Had a little bit of a headache trying to read the get_folder_name function the other day.
Key things here are:
* Moving decision around whether a folder exists outside of `get_folder_name`
* renaming `sending_date` to `created_at`, because that's what it's always set to, even if the letter was sent many days later due to technical issues with us or with dvla
> Make letter folder name code readable

- app/dao/jobs_dao.py
- app/job/rest.py
- tests/app/job/test_rest.py
At the moment we display the count of scheduled jobs on the dashboard by sending all the scheduled jobs to the admin app and letting it work out the stats.
This is inefficient and, because the get jobs response has a page size of 50, becomes incorrect if a service schedules more than 50 jobs.
This commit adds a separate endpoint which gives the admin app the stats it needs directly and correctly.
> Add an endpoint for stats about scheduled jobs

- app/config.py
This changes that scheduled task to run at the top of the hour, 15, 30, and 45 minutes past
> On the crazy weekend we checked for scheduled jobs every minute.

- app/models.py
- tests/app/broadcast_message/test_rest.py
This will let us show the content of the broadcast message in places we can’t at the moment.
> Serialise content in broadcast message response

- app/user/rest.py
- tests/app/user/test_rest.py
This is so when users reset their password they are still redirected to pages they were meant to visit.
This change was done specifically so everyone who is meant to see broadcast tour sees it, but it will improve lives of all users who wanted to visit a page on Notify but then had to reset their password in the process
Goes together with: https://github.com/alphagov/notifications-admin/pull/3670
Pivotal ticket: https://www.pivotaltracker.com/story/show/174488590
> Put redirect link in reset password email link

- app/dao/notifications_dao.py
- tests/app/dao/notification_dao/test_notification_dao.py
We have had a few instances where letters have caused problems. Particularly for precompiled letters, often the issue comes from the same service.
The hope is that by adding a sort order this will help the print provider narrow down the problem.
There is a small degradation of the performance of the query, but it's not enough to concern me.
> Adding service_id to the sort order for the letters being sent to print.

- app/schemas.py
- tests/app/template/test_rest.py
Broadcast services only have broadcast templates. But on the frontend we show the template type under the name of the template. This is redundant. It would be better to preview the content of the template instead.
At the moment we can’t do this because we optimised the template schema response to not include the content of the templates in https://github.com/alphagov/notifications-api/pull/2880
This commit reverses that optimisation, for broadcast templates only. This should be OK, because broadcast services:
- shouldn’t have hundreds of templates
- have templates that are much shorter than the typical email or letter, because of the character restrictions of the broadcast medium
> Serialise content for broadcast templates

- app/dao/notifications_dao.py
- tests/app/dao/notification_dao/test_notification_dao.py
- tests/app/db.py
This is a temporary measure over the weekend so that DVLA can catch up with all other letters.
We should revert this on Monday 19.10.2020
> Temporarily do not send letters from Insolvency Service to DVLA

- app/celery/letters_pdf_tasks.py
- app/dao/notifications_dao.py
- tests/app/celery/test_letters_pdf_tasks.py
- tests/app/conftest.py
- tests/app/dao/notification_dao/test_notification_dao.py
Reintroduce the sending of Insolvency letters to DVLA and mark ZIP files with insolvency letters so DVLA knows to process those separately.
Review commit by commit.
> Start sending letters from Insolvency Service to DVLA again

- app/__init__.py
- app/celery/broadcast_message_tasks.py
- app/clients/cbc_proxy.py
- app/config.py
- manifest.yml.j2
- tests/app/celery/test_broadcast_message_tasks.py
- tests/app/clients/test_cbc_proxy.py
What
----
When a broadcast is approved, and a new Broadcast Event is despatched with status`ALERT` we want to invoke the CBC Proxy which will generate a CAP XML message and send it to the CBC
Checklist
----
Pair
----
@klssmith @CrystalPea
> Non-production environments invoke CBC Proxy during broadcast event creation

- app/celery/letters_pdf_tasks.py
- tests/app/celery/test_letters_pdf_tasks.py
This is at request of DVLA. They would prefer to have zip files with the
same number of arguments in the name. After being offered a few
different options, such as including an org and service id for all zips,
they chose to just remove the 'INSOLVENCY' tag.
For more context see PR that added the tag
https://github.com/alphagov/notifications-api/pull/3006
> Remove 'INSOLVENCY' from zip files for insolvency letters

- app/celery/letters_pdf_tasks.py
- app/dao/notifications_dao.py
- tests/app/celery/test_letters_pdf_tasks.py
- tests/app/dao/notification_dao/test_notification_dao.py
we had issues where we had 150k 2nd class notifications, and the collate task never ran properly, presumably because the volume of data being returned was too big.
to try and help with this, we can switch to streaming rather than using `.all` and building up lists of data. This should help, though the initial query may be a problem still.
Testing locally with 65k notifications, in the new branch the collate task takes approx 1min20 - 1min30 to send each zip file off to the ftp queue. meanwhile the master branch code has taken 10 minutes and still hasn't sent the first file yet. 
based on a cursory glance at `pg_stat_activity`, I think that the real time sink may be going to s3 65,000 times to get the metadata for each different file - on master we're doing this for every file before …
> stream notifications when collating zip files

- app/dao/notifications_dao.py
we've seen issues where tasks mysteriously hang and do not process large volumes of letters - in this case >150k letters in created state.
to try and get at least some letters out of the door, limit the query to only return 50k letters per postage type. We may need to run the task multiple times, or letters may get delayed until the next day when they'd be picked up (provided there's enough capacity then). The task should only be re-run AFTER the ftp tasks have all finished, and updated the letters to sending, or we run the risk of sending the same letters twice.
For context, the largest ever letter day we've sent is ~65k in march of this year.
> limit collate task to 50,000 messages

- app/celery/broadcast_message_tasks.py
- app/clients/cbc_proxy.py
- tests/app/celery/test_broadcast_message_tasks.py
- tests/app/clients/test_cbc_proxy.py
What
----
Related to https://github.com/alphagov/notifications-broadcasts-infra/pull/23
Currently when we send an alert, the area is hardcoded to a large area around London
This PR passes through the area names and transmitted areas from the `BroadcastEvent` to the CBC Proxy function, so that when we choose an area, it is reflected in the generated CAP XML
> clients: cbc_proxy actions accepts areas param

- app/celery/broadcast_message_tasks.py
- app/config.py
- tests/app/celery/test_broadcast_message_tasks.py
⚠️ Needs a rebase once https://github.com/alphagov/notifications-api/pull/3011 is merged
What
----
Removes references to the CBC stub
Wires up the update and cancel methods of the `cbc_proxy` client
Why
----
We are testing with live CBCs, we don't need to use a stub and the two codepaths will diverge and make things unnecessarily complicated and non-obvious
> Remove references to stub CBC

- app/celery/letters_pdf_tasks.py
- app/dao/notifications_dao.py
- tests/app/dao/notification_dao/test_notification_dao.py
Two main concepts here - for info on each one, check the commit messages for more info
Rather than using `Notification.query` to return an ORM Notification object, we can just return the specific columns we need. We can join on service to fetch the crown status, there's much less data sent over the wire, less memory used on the app, and it's also useful for...
Sqlalchemy supports not pre-fetching all results, but instead yielding every X (I set this to 10k, ignore the branch name). This is risky to use with more ORM features like referring to relationships (which is part of the motive for the first commit), but means that we don't fetch all data and build up lots of ORM objects in memory - only 10k each time, then we'll go get the files from s3 and start to send them before going back to …
> Optimise dao_get_letters_to_be_printed query

- app/celery/broadcast_message_tasks.py
- tests/app/celery/test_broadcast_message_tasks.py
- tests/app/db.py
What
----
* More explicit areas within tests
* Do not pass "description" to CBC Proxy, as it is not needed
_more context in individual commit messages_
@idavidmcdonald @rjbaker
> CBC Proxy does not need area descriptions

- app/celery/scheduled_tasks.py
- app/clients/cbc_proxy.py
- app/config.py
- tests/app/celery/test_scheduled_tasks.py
- tests/app/clients/test_cbc_proxy.py
The CBC Proxy is essentially a lambda function which we invoke with
various arguments.
A way in which this can fail is that the notifications-api app invoking
the function may not be able, any longer, to invoke the function.
This could be caused by, for example:
* an egress restriction preventing access to eu-west-2.lambda.amazonaws.com
* a network partition preventing access to eu-west-2.lambda.amazonaws.com
* the app's credentials have been rotated or revoked
If we invoke a simple "canary" lambda function for which the app should
have access to invoke, and check it for failures, we will know quickly
if something is likely to be broken.
This is especially important for cell broadcasts compared to email/SMS
because we always have a baseline of traffic for email/SMS, and so any
failure is …
> Add task to send canary to cbc proxy

- app/broadcast_message/rest.py
- app/models.py
- requirements-app.txt
- requirements.txt
This PR uses the `BroadcastMessageTemplate` to format the content of the message at the time of creating the event. This means that any downstream code (eg Celery tasks) can assume the content is already formatted correctly.
Also, these downstream tasks don’t  know which template the broadcast was created from, so if we support personalisation in the future this is the most sensible place to bring together the template and the personalisation.
***
I had to re-create some of the deleted code from utils for stuff like formatting the timestamp to the CAP standard.
***
Brings in:
> Use utils template to format broadcast content

- app/celery/tasks.py
- app/config.py
- app/v2/notifications/post_notifications.py
- scripts/paas_app_wrapper.sh
- tests/app/celery/test_tasks.py
- tests/app/test_config.py
- tests/app/v2/notifications/test_post_notifications.py
When we initially added a new task to persist the notifications for a high volume service we wanted to implement it as quickly as possible, so ignored SMS.
This will allow a high volume service to send SMS, the SMS will be sent to a queue to then persist and send the SMS, similar to emails.
At this point I haven't added a new application to consume the new save-api-sms-tasks. But we can add a separate application or be happy with how the app scales for both email and sms.
How to test:
Add a local service to the HIGH_VOLUME_SERVICE in app.config.Development or your source environment.sh, it's an array. Then post a sms and email from the python client using that service, need to use a live or team key. You should see the save-api-email-task or save-api-sms-task being called from the celery …
> Add a task to save-api-sms for high volume services.

- tests/app/dao/test_uploads_dao.py
There seems to be a UTC time bug around the dao_get_uploads_by_service_id function.
To fix the build tonight I'm putting freezing the time for the test. But will investigate further tomorrow.
> Quick UTC bug fix

- app/celery/scheduled_tasks.py
- app/clients/cbc_proxy.py
- app/config.py
- tests/app/celery/test_scheduled_tasks.py
- tests/app/clients/test_cbc_proxy.py
What
----
- `cbc_proxy_client` sends `message_type` to the CBC Proxy
- `cbc_proxy_client` can send link test messages using the `test` alert type
- Adds a periodic task to trigger link tests
Further detail in commit messages
Who
----
Mob with @CrystalPea @rjbaker
> Link tests

- app/celery/broadcast_message_tasks.py
- app/clients/cbc_proxy.py
- app/models.py
- tests/app/celery/test_broadcast_message_tasks.py
- tests/app/clients/test_cbc_proxy.py
What
----
A `BroadcastEvent` knows when an event was sent and should expire using the fields
* `sent` == `sent_at`
* `expires` == `transmitted_finishes_at`
We pass through these values directly to the CBC Proxy, because `BroadcastEvent` knows how they should be formatted
> client: cbc_proxy passes through sent/expires

- app/notifications/validators.py
- requirements-app.txt
- requirements.txt
- tests/app/notifications/test_validators.py
- tests/app/service/test_send_one_off_notification.py
Up until now, only sms messages could get message-too-long error,
but now we also need to validate the size of email messages, so
the message content needs to be tailored to the notification type.
This utils PR needs to go in first: https://github.com/alphagov/notifications-utils/pull/798/files
Pivotal ticket: https://www.pivotaltracker.com/story/show/175115179
> Tailor message-too-long error message depending on the notification type

- app/notifications/validators.py
- requirements-app.txt
- requirements.txt
- tests/app/notifications/test_validators.py
- tests/app/service/test_send_one_off_notification.py
Reverts alphagov/notifications-api#2992
Reverting since this seems to be including document download files as part of the email length
> Revert "Tailor message-too-long error message depending on the notification type"

- app/config.py
What
----
This is causing the disk of the CBCs to fill up quickly, and their
logrotate seems a bit flakey
Reducing the rate will ensure the disks fill up less often
@yahoopete
> celery: link test less often

- app/cloudfoundry_config.py
- tests/app/test_cloudfoundry_config.py
What
---
Refer to https://www.postgresql.org/docs/11/libpq-connect.html#LIBPQ-CONNECT-SSLMODE
GOV.UK PaaS gives us the database URI, and we use the default mode of postgres auth which prefers a TLS connection instead of a plain TCP connection
We are now specifying the SSL mode in the URI when establishing our connection to the database, so that:
* We will not connect to the database via a plaintext connection
* We will verify the database connection against a list of trusted CAs
The RDS CA from which the database's certificate is issued is added into
the Cloud Foundry app container via
https://github.com/alphagov/paas-cf/blob/925681f19bbf9d442298fbfa93d18804a7e150eb/manifests/cf-manifest/operations.d/350-diego-cell.yml#L17-L22
---
Pair with @idavidmcdonald
> Specify sslmode in Cloud Foundry environment variables

- app/notifications/validators.py
- app/v2/notifications/post_notifications.py
- requirements-app.txt
- requirements.txt
- tests/app/notifications/test_validators.py
- tests/app/service/test_send_one_off_notification.py
We want to add validation for an email that's too long, that way the user knows why the message is failing. At the moment if an email is too long it will get a technical failure, after the retries fail. This way the email post will get a validation error.
This PR adds a boolean to check_char_count, when validate_template is called. This is set to false if the notification is an email/sms from the API. We want to check the length after the document download file has been uploaded and the variable replaced with the link. Otherwise the check can fail.
Once this: https://github.com/alphagov/notifications-utils/pull/804 is reverted, we can update the utils version.
> Change how we validate the length of templates.

- requirements-app.txt
- requirements.txt
This version changes the `.fragment_count` method of the `BaseSMSTemplate` class to take extended GSM characters into account.
[Pivotal story](https://www.pivotaltracker.com/story/show/175457294)
> Bump notifications-utils to 43.5.0

- app/celery/service_callback_tasks.py
- app/celery/tasks.py
We don't retry any callbacks when it receives a 4xx status. We should
probably be aware of this happening and at the moment there is nothing
in our logs to easily identify whether the request failed and is being
retried or if it failed and is not being retried. This will enable us to
search our logs easily and figure out how much it's happening.
It's quite likely that we should in the future allow callbacks to retry
if they get a 429 http response (rate limiting) but we should do this in
a smart way (exponential backoff) and so this is a first step to being
aware of how big a problem it is in case we want to do something about
it.
Note, we already have a test for the behaviour that we don't retry for 4xx so I didn't need to add one …
> Log when we don't retry a callback

- app/config.py
This is done on a temporary basis for billing-related reasons.
> Give sms providers equal shares of traffic

- requirements-app.txt
- requirements.txt
Brings in https://github.com/alphagov/notifications-utils/pull/807
which removes a hack we had in our email template
to deal with this bug:
https://www.pivotaltracker.com/story/show/161183433
This behaviour is no longer happening so this
removes the hack.
See
https://www.pivotaltracker.com/story/show/161183433/comments/219297211
for evidence of the change in behaviour.
> Bump utils to 43.5.1

- app/celery/process_ses_receipts_tasks.py
- app/notifications/notifications_ses_callback.py
- tests/app/celery/test_process_ses_receipts_tasks.py
At the moment we log everytime we get a bounce from SES, however we
don't link it to a particular notification so it's hard to know for what
sub reason a notifcation did not deliver by looking at the logs.
This commit changes this by now looking the bounce reason after we have
found the notification ID and including them together. So if you know
search for a notification ID in Kibana, you will see full logs for why
it failed to deliver.
> Add notification ID to SES bounce reason

- app/config.py
This is done because we will be load testing on staging.
> Turn on SMS and email stubs on staging

- app/celery/broadcast_message_tasks.py
- app/celery/scheduled_tasks.py
- app/clients/cbc_proxy.py
- app/config.py
- tests/app/celery/test_broadcast_message_tasks.py
- tests/app/celery/test_scheduled_tasks.py
- tests/app/clients/test_cbc_proxy.py
previously we made some incorrect assumptions about set-up on staging and prod - they currently don't have any cbc_proxy aws creds at all.
We shoudn't be attempting canaries or link tests when there's no AWS infrastructure to connect to.
We also shouldn't bother writing a row into the database at all for the broadcast_provider_message since we're not even attempting to send, and we shouldn't get confused between messages that failed and messages we never wanted to send at all.
> add CBC_PROXY_ENABLED config flag to control if tasks are triggered

- requirements-app.txt
- requirements.txt
Brings in:
Changes:
- https://github.com/alphagov/notifications-utils/compare/43.5.1...43.5.2
> Bump utils to 43.5.2

- app/delivery/send_to_providers.py
We currently measure the sending time for all. This commit then breaks
it down into
- test keys and non test keys
- high volume services and non high volume services
Breaking it down into test keys and non test keys is important because
we don't care as much about sending test notifications within 10
seconds, only non test keys so we don't want our graphs to reflect poor
performance if it's just test keys affecting this
Breaking it down into high volume and non high volume will allow us to
easily debug issues with slow sending if they are high volume or non
high volume issues
> Break down how long it takes to send a notification

- app/delivery/send_to_providers.py
Changes the high volume and not high volume metrics to both only include
non test notifications. This is because when looking at the grafana
metrics, it was impossible to tell what affect the high volume/non high
volume effect was having vs the test/live notification effect.
This leaves us with no break down of high volume/not high volume sending
times for test notifications but I don't think we really need that.
> Tweak sending time metrics to only include live notifications

- app/delivery/send_to_providers.py
`service.id` is a uuid so will not be matched to anything in
`current_app.config.get('HIGH_VOLUME_SERVICE')` because that is a list
of strings.
This is why we are never falling into the first if statement and having
any metrics for high volume services on our dashboards at the moment.
Note, I had taken the existing line from the `post_notification`
endpoint, but that is using a serialised service which already has the
UUID converted to a string.
> Fix comparison of uuid to string

- app/dao/jobs_dao.py
- tests/app/dao/test_jobs_dao.py
- tests/app/job/test_rest.py
Now that we’re grouping jobs sent from contact lists within their parent, they shouldn’t also be listed on the jobs page at the top level.
***
Depends on:
> Don’t return jobs sent from contact lists

- app/dao/jobs_dao.py
- app/dao/uploads_dao.py
- tests/app/dao/test_jobs_dao.py
- tests/app/dao/test_uploads_dao.py
- tests/app/job/test_rest.py
Now that we’re grouping jobs sent from contact lists within their parent, they shouldn’t also be listed on the jobs page at the top level.
The jobs page uses the uploads API, not the jobs API, so this commit makes sure that filtering is happening in the proper place (unlike a previous attempt which used the jobs API).
> Don’t return jobs sent from contact lists (uploads page edition)

- app/clients/cbc_proxy.py
- tests/app/clients/test_cbc_proxy.py
A minor fix to set the `message_format` parameter sent to the CBC Proxy to be one of `cap` or `ibag`.
> Set cbc proxy message_format to "cap"

- requirements-app.txt
- requirements.txt
Changes: https://github.com/alphagov/notifications-utils/compare/43.5.4...43.5.6
> Bump utils to 43.5.6

- app/notifications/validators.py
- requirements-app.txt
- requirements.txt
- tests/app/notifications/test_validators.py
This is because GOV.UK has hit the email size limit with their
weekly digest email.
> Increase email size limit to 2MBby pulling in new utils

- app/celery/broadcast_message_tasks.py
- app/clients/cbc_proxy.py
- tests/app/celery/test_broadcast_message_tasks.py
- tests/app/clients/test_cbc_proxy.py
This is so we could send cancel messages to the lambda.
> Add cancel routes to cbc proxy clients

- requirements-app.txt
- requirements.txt
- tests/app/notifications/test_validators.py
Fixes bugs with HTML escaping and calculating size of emails.
Changes: https://github.com/alphagov/notifications-utils/compare/43.5.7...43.5.9
> Bump utils to 43.5.9

- app/dao/notifications_dao.py
- tests/app/dao/notification_dao/test_notification_dao_delete_notifications.py
- tests/app/db.py
https://www.pivotaltracker.com/story/show/176141920
Definitely review commit by commit
Definitely up for conversation about which is the lesser of two evils here in terms of losing letters and sticking strictly to our data retention policy. I wrote the pivotal ticket so that's only my opinion, would like to hear opposing.
Note, as per the ticket, this will stop us deleting letters that have not moved into a final state. We already have alerts for each of the non final statuses
`raise_alert_if_letter_notifications_still_sending` to alert us about notifications still in sending when they shouldn't be
`check_precompiled_letter_state` to alert us about notifications still in `pending-virus-scan` when they shouldn't' be
`check_templated_letter_state` to alert us about notifications still in …
> Do not let us delete letters that have not reached a final state

- app/__init__.py
- app/celery/service_callback_tasks.py
- app/celery/tasks.py
- app/clients/cbc_proxy.py
- app/commands.py
- app/models.py
- app/schemas.py
- app/service/rest.py
- app/template_statistics/rest.py
- app/utils.py
- app/v2/notifications/post_notifications.py
- tests/app/celery/test_service_callback_tasks.py
- tests/app/celery/test_tasks.py
- tests/app/clients/test_cbc_proxy.py
- tests/app/template_statistics/test_rest.py
- tests/app/v2/notifications/test_get_notifications.py
- tests/app/v2/template/test_get_template.py
Datetime object is not json-serializable, we have to convert it to string for the created_at field of previous broadcast provider messages.
Also move DATETIME_FORMAT from app to app.utils to avoid cyclical import issues
Best to look commit by commit ☺️
> Fix cancel broadcast by converting reference date to string

- app/celery/research_mode_tasks.py
- tests/app/celery/test_research_mode_tasks.py
We have been getting log lines of the following:
`API POST request on
https://api.notifications.service.gov.uk/notifications/sms/mmg failed
with None`
It's not clear what error caused the request to fail because the value
of `api_error.response` is always `None`.
There appears to be something wrong with this logging.
`raise_for_status` will raise an `HTTPError`, so then there should be no
reason to then pass that error into another `HTTPError` (which is
causing the response to be lost).
We can instead simply catch the `HTTPError` and log it's status
code.
This might not be perfect, but it's definitely an improvement and should
give us some more context about why these requests occasionally fail.
> Fix logging line to include response context

- app/celery/celery.py
If the request_id exists in the Flask global context, add it to the kwargs for the task.
The request_id is set is the task is created from a http request, if that task then calls through to another task this will set the request_id from the global context. We should then be able to follow the creation of a notification all the way from the original http request to the sending task.
> Pass request_id onto the task if called from a task

- .flake8
- app/dao/users_dao.py
- app/schema_validation/__init__.py
- app/service/rest.py
- app/v2/errors.py
- gunicorn_config.py
- requirements_for_test.txt
- setup.cfg
- tests/app/authentication/test_authentication.py
- tests/app/aws/test_s3.py
- tests/app/celery/test_reporting_tasks.py
- tests/app/celery/test_tasks.py
- tests/app/dao/notification_dao/test_notification_dao.py
- tests/app/dao/test_invited_user_dao.py
- tests/app/dao/test_service_email_reply_to_dao.py
- tests/app/dao/test_services_dao.py
- tests/app/dao/test_uploads_dao.py
- tests/app/dao/test_users_dao.py
- tests/app/db.py
- tests/app/job/test_rest.py
- tests/app/letter_branding/test_letter_branding_rest.py
- tests/app/notifications/test_process_notification.py
- tests/app/notifications/test_receive_notification.py
- tests/app/notifications/test_validators.py
- tests/app/service/test_rest.py
- tests/app/upload/test_rest.py
- tests/app/user/test_rest_verify.py
- tests/app/v2/notifications/test_post_letter_notifications.py
- tests/app/v2/notifications/test_post_notifications.py
- tests/app/v2/templates/test_get_templates.py
Flake8 Bugbear checks for some extra things that aren’t code style errors, but are likely to introduce bugs or unexpected behaviour. A good example is having mutable default function arguments, which get shared between every call to the function and therefore mutating a value in one place can unexpectedly cause it to change in another.
This commit enables all the extra warnings provided by Flake8 Bugbear,
except for:
- the line length one (because we already lint for that separately)
- B903 Data class should either be immutable or use `__slots__` because this seems to false-positive on some of our custom exceptions
- B902 Invalid first argument 'cls' used for instance method because some SQLAlchemy decorators (eg `declared_attr`) make things that aren’t formally class methods take a class …
> Do extra code style checks with flake8-bugbear

- tests/app/dao/notification_dao/test_notification_dao_delete_notifications.py
Was failing when ran after 5:30pm as this would cause the letters to be
in a different subfolder (for one day later). Solved by freezetiming it
Example build that failed: https://cd.gds-reliability.engineering/builds/1876957
> Fix test that fails after 5:30pm

- app/clients/cbc_proxy.py
- tests/app/clients/test_cbc_proxy.py
If we’re sending non-GSM characters, we need to mark the language in the XML as Welsh (`cy-GB` in CAP, `Welsh` in IBAG).
Currently, the CBC proxy checks the content we’re sending, and then uses an approximation based on ASCII to determine whether we’re sending any non-GSM characters, and if so, sets the language appropriately.
Instead, we should can functionality from the notifications-utils repo to determine the language. If any non-GSM characters are used, then the we can set the language to Welsh.
We’ll need to update the proxy to look at this new language flag.
***
https://www.pivotaltracker.com/story/show/176095502
> Pass language through to lambda

- scripts/paas_app_wrapper.sh
- scripts/run_app_paas.sh
- scripts/run_multi_worker_app_paas.sh
The increased traffic highlighted two issues with our logs:
The first issue was that sender workers, because of the `celery multi`, were keeping duplicate logs: The ones generated from our application and the ones generated from celery itself.
The second issue was around handling the scenario were the instances would run out of disk space. Given the constraints of our runtime environment the simplest solution is to recycle the instances, when their disk usage is over a certain threshold.
For now, I set the threshold to 75%, same as the alert threshold.
> Fix app logging

- manifest.yml.j2
On monday, we had a build of emails in the email queue that weren't
getting picked up by the sender worker and causing delays.
After further investigation with Andy from the PaaS, we believe the
following happened.
We received a bunch of traffic at 8:30ish which consisted of some
very large emails in terms of their length and complexity. The amount
of memory used by the app instances got very high and a few apps
crashed due to OOM (recorded by 5 cf app event crashes). When new
app instances tried to spin up, they weren't able to as they
potentially also ran out of memory immediately (note, we don't have
app crashes for these recorded in the PaaS, the hypothesis is that the
containers failed on startup and the PaaS does not record these).
This left us in the position of having fewer app …
> Add more memory for the sender and letter workers

- app/schemas.py
- tests/app/template/test_rest_history.py
We already serialise it in the templates response. We should make sure the field is also present in the history response, if we want to use cached template versions when processing notifications.
> Serialise process_type for template history

- app/clients/document_download.py
- tests/app/clients/test_document_download.py
previously we'd see an error message in the logs: `AttributeError: 'NoneType' object has no attribute 'status_code'` because we were assuming the requests exception would always have a response - it won't have a response if it wasn't able to create a connection at all.
this'll still raise an `Exception` downstream so will still get caught by existing handlers exactly the same, but it'll be easier to understand when reading kibana
> handle doc dl connection errors correctly

- app/delivery/send_to_providers.py
- tests/app/delivery/test_send_to_providers.py
For every email or text message we send we have to work out which provider to send it with. Every time we do this we go and load the list of providers from the database.
For emails, the result will always be the same.
For text messages the result is randomly chosen to balance the load between the providers.
For international text messages the result is always the same (we only have one international text message provider).
This pull request adds an in-memory cache with a 2 second time-to-live so that we’re not fetching the providers from the database every time, which should speed things up a bit.
This does mean that, for text messages, the random choice will ‘stick’ for two seconds on each instance, before being re-chosen. I think this is OK because it will even out to the same …
> Cache provider lookups for 10 seconds

- app/broadcast_message/rest.py
- app/models.py
- migrations/versions/0335_broadcast_msg_content.py
- tests/app/broadcast_message/test_rest.py
- tests/app/celery/test_broadcast_message_tasks.py
- tests/app/db.py
we want to be able to create broadcast messages without templates. To start with, these will come from the API, but in future we may want to let people create via the admin interface without creating a template too.
populate a non-nullable content field with the values supplied via the template (or supplied directly if via api).
> add content to broadcast_message and make template fields nullable

- app/broadcast_message/rest.py
- migrations/versions/0335_broadcast_msg_content.py
- tests/app/broadcast_message/test_rest.py
* allow null content in migration because existing rows won't have any content populated yet.
* allow broadcasts to have a template and no content. this ensures code remains backwards compatible during the deploy. this commit should be reverted once all broadcast_message.content fields have been back-filled.
> Fix broadcast migration

- app/dao/fact_billing_dao.py
- app/organisation/rest.py
- tests/app/organisation/test_rest.py
Ensure the archived services are at the bottom of the list. The organisation trial mode page already sorts the archived services to the bottom.
> Change the sort order for the organisation usage page

- app/broadcast_message/rest.py
- migrations/versions/0336_broadcast_msg_content_2.py
- tests/app/broadcast_message/test_rest.py
new broadcast messages will have content filled whether they have a template or not, but old ones won't so populate.
Stole the session constructor from 0044_jos_to_notification_hist.py
> add content to old broadcast messages with no content

- app/celery/nightly_tasks.py
- tests/app/celery/test_nightly_tasks.py
In https://github.com/alphagov/notifications-api/pull/2627/commits/8285ef5f89f45287d0bb9e23fd184b0565cb5784
we turned off alerting on 2nd class letters still being in sending on
certain days of the week because we were only sending letters out on
Mon, Wed, Fri.
Now we have swapped back to sending out 2nd class letters on all
workdays so this change can be reverted. Note, I haven't reverted the
commit exactly but more so the behaviour, whilst leaving in some tests
to explicitly test 2nd class letters for the alert in case we change
this again.
> Alert on 2nd class letters still in sending everyday

- app/clients/cbc_proxy.py
- tests/app/clients/test_cbc_proxy.py
Introduce failover behaviour such that if any error is raised by the first lambda (that includes both invoke errors and function errors connected to trying to talk to the CBC), then our API will then retry by invoking the second lambda.
Logs error types returned by https://github.com/alphagov/notifications-broadcasts-infra/pull/79
Note, the second lambda doesn't exist yet. It also isn't defined yet whether the second lambda will be pointed at the second CBC or if it will still point at the first CBC (or if it needs to be able to decide on the fly).
Please review this commit by commit.
The annoyance we have is that AWS docs are a bit unclear with what values we get back from an exception in the lambda code. We've made assumptions about the interface in our tests but we will need to do some …
> Failover to second lambda on error

- app/clients/cbc_proxy.py
- app/config.py
- tests/app/clients/test_cbc_proxy.py
Commit one creates the CBC proxy client for Three
Commit two turns it on.
@rjbaker could you confirm whether we are good to release this with it turned on or if we need to hold off on that until later. Note, I'm expecting it will be fine to release it because if Three is not ready then our calls to the lambda will fail and we will log a failure but nothing much else will happen
Decided not to abstract the EE and Three proxies into a `CBCProxyOne2Many` subclass just yet. Will probably be a sensible move in the future but going to hold off until we add O2 or we get Three working as that may provide different information about any differences between the proxies
Note, our tests are made a bit nasty by the fact that we have the `CBCProxyEE` class uses a proxy that is not called `ee-proxy-1` …
> Three proxy

- app/models.py
- app/utils.py
- migrations/versions/0336_broadcast_msg_content_2.py
- migrations/versions/0337_broadcast_msg_api.py
When we have a public API there will be no human creating the broadcast message. Instead it will be created by an API integration, authenticated by a key (just like for emails or texts).
This updates the database to:
- add a new foreign key from BroadcastMessages to API keys
- make `created_by` nullable when `api_key` is non-null, and vice versa
- add a reference field which the frontend can use instead of template name, for broadcasts without templates
***
This commit also fixes a previous migration to remove use of a model class.
We shouldn’t import models into migrations because if the model changes later down the line then the migration can’t be re-run at a later date (for example to rebuild a database from scratch).
> Allow broadcast messages to be created with API key

- app/broadcast_message/rest.py
- app/celery/broadcast_message_tasks.py
- app/celery/scheduled_tasks.py
- app/config.py
- manifest.yml.j2
- scripts/paas_app_wrapper.sh
- tests/app/broadcast_message/test_rest.py
- tests/app/celery/test_broadcast_message_tasks.py
- tests/app/celery/test_scheduled_tasks.py
- tests/app/test_config.py
https://www.pivotaltracker.com/story/show/176459474
Will require a manual `cf create-app notify-delivery-worker-broadcasts` in each CF space before this can be deployed. 
Will then need to manually scale the app up to 2 instances for high availability. Either that or we set up autoscaler config such that it's min and max number of apps is 2 instances (not particularly a pattern we do yet but maybe one to introduce). Introducing this pattern of adding config to the autoscaler will also give us the benefit of tracking the number of instances in the autoscaler grafana dashboard and how many tasks are being added to queues/processed by the broadcast worker etc. Would be interested to get your thoughts on this please.
> Broadcast tasks onto worker

- app/celery/tasks.py
- app/serialised_models.py
- tests/app/celery/test_tasks.py
- tests/app/v2/notifications/test_post_notifications.py
When sending jobs from concurrent CSV files we seem to be limited by how fast we can save items to the database. We’ve made saving to the database faster in other places by taking advantage of the service and template cache to open the connection later. 
Depends on:
> Use cache to improve performance of CSV processing

- app/broadcast_message/broadcast_message_schema.py
- app/broadcast_message/rest.py
- tests/app/broadcast_message/test_rest.py
This pull request updates the JSON schemas and REST endpoint to allow creation of a broadcast with either:
- a `template_id` or
- `content` and a `reference` 
`reference` is so we have something to show in the admin app in lieu of template name when a template isn’t used.
The JSONSchema errors are a bit gnarly, but I think this is OK because this is the internal API.
> Let the admin app create broadcasts without templates

- app/broadcast_message/rest.py
- tests/app/broadcast_message/test_rest.py
This has been added in for speed of development but now we are getting
close to integrating with production systems, we will be turning off
these helpful hacks to reduce the risk of someone sending a real
broadcast to citizens.
Note, platforms are still able to approve broadcasts when their service
is in training mode.
> Remove ability for platform admins to approve own broadcast

- app/clients/cbc_proxy.py
- app/config.py
- tests/app/clients/test_cbc_proxy.py
o2 use One-2-many CBC so we can use the O2M/CAP client.
Once differences between CBCs have been worked out we can consolidate O2M clients to reduce duplication.
> Add proxy client for o2 cell broadcasting

- app/clients/cbc_proxy.py
- tests/app/clients/test_cbc_proxy.py
We want to rename the `bt-ee-1-proxy` lambda function to `ee-1-proxy`.
This change will need to be deployed at the same time that we change
the name of the lambda function in the Terraform.
https://www.pivotaltracker.com/story/show/176551400
> Rename bt-ee-proxy to ee-proxy

- migrations/versions/0341_new_letter_rates.py
All rates are changing, so we add an end date for the current rates and insert new rates for every post_class, sheet count and crown status.
To review - run the migration and check the rates against the new rates in the story https://www.pivotaltracker.com/n/projects/1443052/stories/176222554
> Add February 2021 letter rates

- app/broadcast_message/rest.py
So that MNOs can use training mode accounts to test end-to-end broadcast sending. This will enable them to approve their own broadcasts.
> Don't stub broadcasts on preview

- requirements-app.txt
- requirements.txt
- tests/app/notifications/test_process_notification.py
This brings in the change to stop TV numbers from being treated as international numbers.
> Bump utils to 43.8.1

- app/clients/cbc_proxy.py
- tests/app/clients/test_cbc_proxy.py
https://www.pivotaltracker.com/story/show/176459886
This used to be hardcoded in the CBC proxy but now we will hardcode it
in the cbc_proxy_client.
In a future PR we can start choosing which channel a broadcast will go
to based on the channel configured for that broadcast service.
See https://github.com/alphagov/notifications-broadcasts-infra/pull/102 for related PR that allows the choice of broadcast channel.
This PR will be merged first before the broadcasts-infra PR as that introduces the requirement for the `channel` key. Nothing should break by sending an extra JSON key at the moment that the CBC proxy doesn't know about.
> Set the default broadcast channel to test

- app/celery/scheduled_tasks.py
- tests/app/celery/test_scheduled_tasks.py
We already trigger a zendesk ticket for these two cases, meaning that
whenever we get this situation, we get 3 emails. One for the zendesk
ticket, one from logit raising the fact an exception was raised and one
from cloudwatch raising the fact an exception was raised.
We don't need all these emails, a zendesk ticket is sufficient.
Downgrading to a warning means this event will still be findable in our
logs however.
> Downgrade exceptions to warnings to reduce emails

- app/broadcast_message/rest.py
- app/celery/broadcast_message_tasks.py
- app/clients/cbc_proxy.py
- app/dao/broadcast_message_dao.py
- app/models.py
- tests/app/celery/test_broadcast_message_tasks.py
- tests/app/clients/test_cbc_proxy.py
- tests/app/db.py
Retry tasks if they fail to send a broadcast event. Note that each task tries the regular proxy and the failover proxy for that provider. This runs a bit differently than our other retries:
Retry with exponential backoff. Our other tasks retry with a fixed delay of 5 minutes between tries. If we can't send a broadcast, we want to try immediately. So instead, implement an exponential backoff (1, 2, 4, 8, ... seconds delay). We can't delay for longer than 310 seconds due to visibility timeout settings in SQS, so cap the delay at that amount.
Normally we give up retrying after a set amount of retries (often 4 hours). As broadcast content is much more important than normal notifications, we don't ever want to give up on sending them to phones...
...UNLESS WE DO!
Sometimes we do want to give …
> retry sending broadcasts

- app/broadcast_message/rest.py
- tests/app/broadcast_message/test_rest.py
otherwise we run into issues where we dont issue the cancel as we say "oh look the expiry time just passed, so we shouldnt send this message as it's already been removed from the cbc"
> dont update finishes_at when cancelling broadcast

- app/celery/broadcast_message_tasks.py
- manifest.yml.j2
- tests/app/celery/test_broadcast_message_tasks.py
* Celery grabs up to 10 tasks from an SQS queue by default
* Each broadcast task takes a couple of seconds to execute, or double that if it has to go to the failover proxy
* Broadcast tasks delay retry exponentially, up to 300 seconds.
* Tasks are acknowledged when celery starts executing them.
* If a task is not acknowledged before its visibility timeout of 310 seconds, sqs assumes the celery app has died, and puts it back on the queue.
A task stuck in a retry loop was reaching its visbility timeout, and as such SQS was duplicating it. We're unsure of the exact cause of reaching its visibility timeout, but there were two contributing factors: The celery prefetch and the delay of 300 seconds. Essentially, celery grabs the task, keeps an eye on it locally while waiting for the delay ETA to …
> broadcast event retry loop fix

- app/v2/broadcast/post_broadcast.py
- tests/app/v2/broadcast/test_post_broadcast.py
`lxml` wants its input in bytes:
> XML is explicitly defined as a stream of bytes. It's not Unicode text. […] rule number one: do not decode your XML data yourself.
– https://lxml.de/FAQ.html#why-can-t-lxml-parse-my-xml-from-unicode-strings
It will accept strings unless, unless the document contains a declaration<sup>1</sup> with an `encoding` attribute. Then it will refuse to parse the document and raises a `ValueError`<sup>2</sup>.
We can fix this – thereby supporting documents which have a declaration – by passing `lxml` the bytes from the request, rather than the decoded text.
***
1. > XML documents may begin with an XML declaration that describes some information about themselves. An example is `<?xml version="1.0" encoding="UTF-8"?>`.
– …
> Handle XML files that have a declaration

- app/broadcast_message/rest.py
- app/celery/broadcast_message_tasks.py
- app/clients/cbc_proxy.py
- app/dao/broadcast_message_dao.py
- app/models.py
- manifest.yml.j2
- tests/app/celery/test_broadcast_message_tasks.py
- tests/app/clients/test_cbc_proxy.py
- tests/app/db.py
we're still having issues with duplicate tasks ending up in a retry loop death spiral, despite the attempted fixes we put in https://github.com/alphagov/notifications-api/pull/3123. 
revert this and have another stab it at later when we figure out a bit more about why it might fail
> Revert cell broadcast retry logic

- requirements-app.txt
- requirements.txt
One of our dependencies has a dependency on cryptography, which has
recently released version 3.4.
This version introduced a circular import error
(pyca/cryptography#5756) which was fixed in
3.4.1.
However, 3.4.1 has a different error where it fails because it cannot
find a rust compiler.
The suggested
solutions are:
Install a newer version of pip which will install a pre-compiled
cryptography wheel OR
Have rust installed and available on our PATH so that it can be used
to build the package.
Since we can't change the buildpack's pip version and we cannot install
rust ourselves, the only we're left with is to avoid upgrading to 3.4 -
at least until PaaS updates their python buildpacks.
> Pin cryptography to a version < 3.4

- app/v2/broadcast/post_broadcast.py
- tests/app/v2/broadcast/test_post_broadcast.py
This PR makes sure `stubbed` is set when creating broadcast message via API.
> Set broadcast message to stubbed when posting broadcast via API

- app/notifications/validators.py
- requirements-app.txt
- requirements.txt
- tests/app/v2/notifications/test_post_letter_notifications.py
Postal address validation now includes `< >` in the invalid characters allowed at the start of an address line.
> Update notifications-utils version.

- app/celery/service_callback_tasks.py
- app/config.py
- scripts/paas_app_wrapper.sh
- tests/app/celery/test_service_callback_tasks.py
- tests/app/test_config.py
At the moment, if a service callback fails it will get put on the retry queue. This causes a potential problem though:
If a service's callback server goes down, we may generate a lot of retries and this may then put a lot of items on the retry queue. The retry queue is also responsible for other important parts of Notify such as retrying message delivery and we don't want a service's callback server going down to have an impact on the rest of Notify.
Putting the retries on a different queue means that tasks get processed faster than if they were put back on the same 'service-callbacks' queue.
https://www.pivotaltracker.com/story/show/176596898
> Put service callback retries on a different queue

- app/models.py
- migrations/versions/0344_move_broadcast_provider.py
- tests/app/celery/test_broadcast_message_tasks.py
- tests/app/service/test_rest.py
Move provider restriction into broadcast settings
This means we will have a much easier way of knowing what the settings
are for a broadcast service.
Note, we can just move data directly into the newer table as there is
nothing on the API or admin app that is putting data in the
`service_broadcast_provider_restriction` table, this was being done
manually for the few services that needed it.
> Move provider restriction into broadcast service settings table

- app/clients/cbc_proxy.py
By creating a new `CBCProxyOne2ManyClient` class for the three One2Many
clients to inherit from. These three clients are the same apart from the
`lambda_name` and the `failover_lambda_name`.
> Refactor the CBC proxy classes

- app/broadcast_message/translators.py
- app/v2/broadcast/broadcast_schemas.py
- tests/app/v2/broadcast/sample_cap_xml_documents.py
- tests/app/v2/broadcast/test_post_broadcast.py
We don’t support these methods at the moment. Instead we were just ignoring the `msgType` field, so issuing one of these commands would cause a new alert to be broadcast 🙃
We might want to support `Cancel` in the future, but for now let’s reject anything that isn’t `Alert` (CAP terminology for the initial broadcast).
> Don’t accept cancel or update via broadcast API

- app/config.py
- app/delivery/send_to_providers.py
- app/serialised_models.py
- tests/app/delivery/test_send_to_providers.py
This PR is to optimise the methods used to send notifications to providers by remove calls to the database. 
It probably easiest to go through it commit by commit.
- Remove validate_and_format for email and phone numbers, using normalised_to instead because that function has already happened when persisting the notificaiton.
- Remove 2 extra select queries after the update and commit. Once a transaction is committed SQLAlchemy will query for the db model if referenced after a commit.
- Use the cached template object.
By adding SerialisedTemplate we can avoid a database call for the template. This is useful when sending many many emails/sms for the same template/version.
- User cache for service in send_to_provider methods. 
This will remove a call to the db if the service exists in the …
> Improve sender task

- app/delivery/send_to_providers.py
- app/serialised_models.py
- tests/app/delivery/test_send_to_providers.py
Reverts alphagov/notifications-api#3134
The ServiceSerialised object that was introduced is not populating the logo for email branding
> Revert "Improve sender task"

- app/config.py
nb: will need cbc aws key to be set in credentials before deploy. will need iam user set up to get those.
> enable cell broadcast on prod for vodafone only

- app/v2/broadcast/broadcast_schemas.py
- app/v2/broadcast/post_broadcast.py
- requirements-app.txt
- requirements.txt
- tests/app/v2/broadcast/sample_cap_xml_documents.py
- tests/app/v2/broadcast/test_post_broadcast.py
The maximum content count of a broadcast varies depending on its encoding, so we can’t simply validate it against a schema. This commit moves to using the validation from `notifications-utils`, and raising a custom error response.
***
Depends on:
> Validate content length on broadcast API

- app/celery/letters_pdf_tasks.py
https://www.pivotaltracker.com/story/show/176804965
This was renamed in [1], and enough time has elapsed that instances
of the task should all have finished processing.
[1]: https://github.com/alphagov/notifications-api/commit/5d6f2da15590cd82f9804963215b56620c809a7d
> Remove redundant (renamed) letters task

- app/__init__.py
- app/celery/broadcast_message_tasks.py
- app/clients/cbc_proxy.py
- tests/app/celery/test_broadcast_message_tasks.py
- tests/app/clients/test_cbc_proxy.py
boto returns a `StreamingBody`[1] response rather than a json struct. We're currently just logging things like "Error calling lambda o2-1-proxy with function error <botocore.response.StreamingBody object at 0x7f74cd6e02e8>" which is obviously less than ideal. Also make the tests properly reflect this - annoyingly it appears like we can't use moto to reliably test this interface as the moto `mock_lambda` decorator needs you to be running inside a docker container??
previously we would retry if the task was queued up for retry but the status is in "received-ack" or "received-err". We don't expect that a task will be retried after getting this status, but if there are duplicate tasks that could happen. Lets plan for the worst by saying "only process a retry if the task is currently in …
> Retry bug fix

- app/cronitor.py
confusingly, some errs are not subclasses of Exception (things like sys.exit()). `status` not being set when a BaseException (not an Exception) is thrown was confusing things a bit.
Lets make sure the status is always set so cronitor knows what to ping.
> make sure status is always set by finally block

- app/delivery/send_to_providers.py
- app/serialised_models.py
- tests/app/delivery/test_send_to_providers.py
- Add caching by using the SeriralisedTemplate and SerialisedService objects
- Removed extra call to the database to fetch the notification after the commit by saving the created_at and key_type to a local variable. After the update to the notification to mark it as sending the db.session is committed. Any reference to the the Notification data model after that will require a query to fetch the object again because it is considered "dirty" or out of date.
- Added name, sms_prefix and email branding to SerialisedService.
- Refactor the get_html_options to work with the SerialisedService object.
- Removed the need to validate and format the to field by using `normalised_to`, since when persisting the notification the `normalised_to` field has already had this done.
- Removed the validate …
> Add caching and remove extra call to database

- app/celery/letters_pdf_tasks.py
- app/config.py
- app/dao/notifications_dao.py
- migrations/versions/0347_add_dvla_volumes_template.py
- tests/app/celery/test_letters_pdf_tasks.py
- tests/app/conftest.py
- tests/app/dao/notification_dao/test_notification_dao.py
Send daily email with volumes of letters and sheets to DVLA around 6pm so they know how many letters to expect for printing.
To do this we need to:
- create an email template by migration - done here
- add DVLA email to our credentials - done: https://github.com/alphagov/notifications-credentials/pull/199
- gather volumes of letters and sheets - done here
- create a notification and put it on the queue - done here
> Send daily email with volumes of letters and sheets to DVLA

- app/celery/letters_pdf_tasks.py
- app/config.py
- manifest.yml.j2
- tests/app/celery/test_letters_pdf_tasks.py
Personalisation was missing date attribute. The email still got sent last night, just it didn't have a value for date placeholder.
Also add DVLA_EMAIL_ADDRESS to manifest file, so it gets picked up from Credentials.
> Add date to personalisation for DVLA email

- app/user/rest.py
- requirements-app.txt
- requirements.txt
- tests/app/user/test_rest.py
Check international number for alpha: NO if true then use number to send SMS.
This is not a catch all for international SMS, the rules are quite
complex and still not completely understood. We are talking with our
provider who maybe able to sort this out for us. But in the meantime,
this should solve for the case that we understand.
> Check international rules to decide on a sender

- app/config.py
Removes the configuration override for Live, so the base configuration is used, enabling cell broadcasting for all MNOs in the production environment.
> Enable EE Cell Broadcasts in production environment

- app/user/rest.py
- tests/app/user/test_rest.py
the existing endpoint is a GET, and so leaves email addresses in log files.
we've got an existing POST find_users_by_partial_email, but not one that matches on a whole email address.
> add POST get user by email endpoint

- pytest.ini
This avoids being verbose by default, which is consistent with how
we configure pytest for the admin app [1].
[1]: https://github.com/alphagov/notifications-admin/blob/master/pytest.ini#L16
> Quieten output for pytest

- app/clients/sms/firetext.py
- app/dao/notifications_dao.py
- tests/app/clients/test_firetext.py
- tests/app/dao/notification_dao/test_notification_dao.py
- tests/app/notifications/test_process_client_response.py
We only need to check what the status is for firetext SMS responses.
This PR is to clean up that code a little bit.
I had a thought that this code doesn't belong in notification_dao but perhaps here app.notifications.notifications_sms_callback.process_firetext_response or app.celery.process_sms_client_response_tasks.process_sms_client_response. That's a larger refactor, but is it worth it?
> Refactor method for deciding the failure type

- app/dao/broadcast_service_dao.py
- tests/app/service/test_rest.py
We are using the `set_broadcast_service_type` route to make changes to
service objects. However, we had forgotten to add the `version_class`
decorator to it which will mean the changing of a service going from
training to live mode will also be recorded in the services_history
table for free. Whilst not essential, this easy change makes things more
consistent for how we update other services.
Have tested locally by making a service a broadcast service and it works
> Add service versioning to broadcast account type change

- app/celery/letters_pdf_tasks.py
https://www.pivotaltracker.com/story/show/176823265
All other tasks in app/celery/*_tasks.py have timers on them. Some
of these timers will be useful to check before/after performance as
a way to reassure ourselves about the impact of [1].
[1]: https://github.com/alphagov/notifications-api/pull/3172
> Add missing statsd timers to celery tasks

- Makefile
This is consistent with our other apps [1]. Although it won't get
picked up by CI just yet [2], we can still benefit from it locally.
[1]: https://github.com/alphagov/document-download-api/blob/master/Makefile#L25
[2]: https://github.com/alphagov/notifications-manuals/issues/9
> Run 'test-requirements' as part of 'make test'

- app/aws/s3.py
- app/celery/letters_pdf_tasks.py
- app/dao/notifications_dao.py
- app/letters/utils.py
- app/service/send_notification.py
- tests/app/aws/test_s3.py
- tests/app/celery/test_letters_pdf_tasks.py
- tests/app/dao/notification_dao/test_notification_dao_delete_notifications.py
- tests/app/letters/test_letter_utils.py
https://www.pivotaltracker.com/story/show/176823265
A couple of extra notes:
- This duplicates an existing precedent for getting files in S3 by prefix [1].
Unfortunately it would be quite hard to DRY up the new code, so I'm going to
leave it as-is unless someone feels strongly.
- While this makes it a moot point whether we remove the crown / non-crown part
of the filename, I still intent to pursue this in follow-up work, just so that we
have one less thing to remember the meaning of.
- This makes additional use of S3, so warrants a bit of performance testing just
to make sure there's no unexpected impact from the change. I'll do that before
merging the PR.
[1]: https://github.com/alphagov/notifications-api/blob/6db9a7a2f2b7d9ebb24cae7f8a976f …
> Lookup PDFs by prefix in S3 (not whole filename)

- app/dao/fact_billing_dao.py
- app/platform_stats/rest.py
- tests/app/dao/test_ft_billing_dao.py
- tests/app/db.py
- tests/app/platform_stats/test_rest.py
So that when we build the billing report, we get the new details:
- purchase order number
- billing contact names
- billing contact email addresses
- billing reference
Also only return services with bills to pay.
Pivotal ticket: https://www.pivotaltracker.com/story/show/176521236
From the ticket:
> In order to determine where to fetch these values from, first check if there is a ‘purchase order number’ present for the service. If there is then set these fields using the values stored against the service.
> If there is no purchase order number on the service, then check if there is a purchase order number on the parent organisation. If there is then set these fields using the values stored against the organisation.
> If neither is present leave those fields empty in the report.
How to …
> Update usage endpoint with billing details for orgs and services

- requirements-app.txt
- requirements.txt
This bumps lxml to version 4.6.3 because version 4.6.2 had a vulnerability (https://lxml.de/4.6/changes-4.6.3.html).
> Bump lxml for security vulnerability

- app/celery/service_callback_tasks.py
- app/commands.py
- tests/app/celery/test_service_callback_tasks.py
This adds the `template_id` and `template_version` fields to the data
sent to services from the `send_delivery_status_to_service` task.
We need to account for the task not being passed these fields at first
since there might be tasks retrying which don't have that data. Once all
tasks have been called with the new fields we can then update the code
to assume they are always there.
Since we only send delivery status callbacks for SMS and emails, I've
removed the tests where we call that task with letters.
[Pivotal story](https://www.pivotaltracker.com/story/show/177183754)
> Send template id and version with delivery status callback

- app/celery/letters_pdf_tasks.py
- app/letters/utils.py
- app/service/send_notification.py
- tests/app/celery/test_letters_pdf_tasks.py
- tests/app/dao/notification_dao/test_notification_dao_delete_notifications.py
- tests/app/letters/test_letter_utils.py
- tests/app/service/test_send_pdf_letter_notification.py
https://www.pivotaltracker.com/story/show/176823265
This is not required by DVLA and since [1] we no longer care about
the end of letter filenames when collating them, so removing it is
safe to do. Note that the name of the ZIP files of collated letters
is based on a hash of the filenames, which needed updating in tests.
Before merging this we need to do a test run in Staging, so DVLA can
check that a mixture of the old / new filenames won't cause issues.
[1]: https://github.com/alphagov/notifications-api/pull/3172
> Remove non/crown indicator in letter filenames

- app/celery/scheduled_tasks.py
- app/clients/cbc_proxy.py
- app/config.py
- tests/app/celery/test_scheduled_tasks.py
- tests/app/clients/test_cbc_proxy.py
See https://github.com/alphagov/notifications-broadcasts-infra/pull/197
for why we no longer need this and we get to delete some code!
> Remove the emergency alerts canary

- app/celery/service_callback_tasks.py
Now that https://github.com/alphagov/notifications-api/pull/3184 has been deployed for a while, the `send_delivery_status_to_service` task will always have `template_id` and `template_version` being passed in. This means we don't need to check if those fields are there.
> Simplify send_delivery_status_to_service code

- requirements-app.txt
- requirements.txt
It was requested by our user and it is an allowed domain format with Amazon SES, so we started allowing it in our validation.
Utils PR: https://github.com/alphagov/notifications-utils/pull/855 (merged)
> Bump utils to allow double hyphens in email address domain

- app/commands.py
- app/dao/annual_billing_dao.py
- tests/app/dao/test_annual_billing_dao.py
- tests/app/db.py
The free SMS allowances are changing for the financial year starting April 1 2021.
In this PR there is a command to set annual_billing for all active
services with the the new defaults. The new command will work for previous year as well. 
The reason for the missing_services_only parameter for the command is so that we can set the defaults for any services that do not have annual billing for 2020. Which will be needed before April 1.
The new method `set_default_free_allowance_for_service` will also be
called in a PR to follow that will set a services free allowance to the
default if the organisation for the service is changed.
> Populate annual billing for 2021

- app/broadcast_message/rest.py
https://www.pivotaltracker.com/story/show/177498565
We previously allowed MNOs to approve a broadcast themselves in training
mode and have it go out to their integration environment as per
https://github.com/alphagov/notifications-api/pull/3114
However, we want to remove this use case as it means we have to support
configuration for training mode services to do things like pick a
channel and send out alerts which we definteily don't want to do in
production.
By making this change, we reduce the chance of a single bug meaning an
alert will go out in prod that shouldn't.
Note, will also make it harder for development environment testing but I
think it is still worth it as https://www.pivotaltracker.com/story/show/177584959
will make it much harder in our code to allow some environments to …
> Don't send real broadcasts for preview training mode

- app/celery/broadcast_message_tasks.py
- tests/app/celery/test_broadcast_message_tasks.py
config['NOTIFY_ENVIRONMENT'] is hardcoded to `'live'` in the Live config class. The values as seen on the environment which we send real messages from:
```
>>> json.loads(os.environ['VCAP_APPLICATION'])['space_name']  # what cloudfoundry sets
'production'
>>> os.environ['NOTIFY_ENVIRONMENT']  # we set this from cloudfoundry
'production'
>>> current_app.config['NOTIFY_ENVIRONMENT']  # hardcoded in the Live config
'live'
>>> current_app.config['NOTIFICATION_QUEUE_PREFIX']  # pulled from env var of same name
'live'
>>> current_app.config['ENV']  # this is an unrelated flask variable
'production'
```
we don't need to be re-notified when someone clicks cancel
> fix environment var checking

- app/__init__.py
- app/celery/celery.py
- requirements_for_test.txt
- tests/app/celery/test_celery.py
https://www.pivotaltracker.com/story/show/176261229
This adds code to send a new set of StatsD metrics about Celery tasks,
which will replace the existing stats when we have enough data.
The new metrics require less code to implement, are more consistent with
our logging approach, and contain more useful dimensions for filtering.
If the approach here is successful, we can duplicate it in the Antivirus
and Template Preview apps, which have a similar superclass for Celery tasks.
Note: this will temporarily result in us sending roughly double the number
of datapoints to StatsD. This shouldn't cause a problem, as the data is sent
over UDP. I will do a quick test on Preview to check for any warning signs.
> Migrate towards new metrics for Celery tasks

- app/celery/broadcast_message_tasks.py
- app/config.py
- manifest.yml.j2
- tests/app/celery/test_broadcast_message_tasks.py
Review commit by commit but the main problem this is solving is reducing the number of our API apps that have IAM creds for sending emergency alerts (only the broadcast worker needs them)
> Broadcast envars

- manifest.yml.j2
This app will replace the `notify-api-sms-callbacks` app as it is an app
that handles receipts, not callbacks.
After this and the corresponding concourse PR is merged and deployed (at which
point we will have two apps sharing the traffic) we can then put in PRs
to remove the `notify-api-sms-callbacks` app.
There is a chance it could all be done as a single PR (or at least one
for the API and one for the concourse pipelines) but I'm playing it safe
and doing it as a very clear two step process just in case.
See https://github.com/alphagov/notifications-api/pull/2979 for context
> Add sms receipts app manifest config

- app/celery/celery.py
- tests/app/celery/test_celery.py
Celery's apply_async function accepts 'kwargs' as (get ready to be
confused) either a positional argument, or a keyword argument:
Positional: apply_async(['args'], {'kw': 'args'})
Keyword: apply_async(args=['args'], kwargs={'kw': 'args'})
We rely on the positional form in at least one place [1]. This fixes
the overload of apply_async to cope with both forms, and continue to
pass through any other (confusion time again) positional or keyword
args (like queue='queue') to the original function.
[1]: https://github.com/alphagov/notifications-api/blob/fde927e00ed9f117f33ae4eedf4c3a05e4db207b/app/job/rest.py#L186
> Fix apply_async not working with positional kwargs

- app/broadcast_message/rest.py
- tests/app/broadcast_message/test_rest.py
**Don't create broadcast event unless necessary**
If we're not going to send a broadcast, we don't need to create the
BroadcastEvent in the database. The BroadcastMessage contains all the
data we need - the BroadcastEvent is not used.
Not creating the event when we won't send the broadcast (e.g. when the
broadcast message was created when the service was in trial mode) adds
an extra layer of security.
**Check if a service is live before sending a broadcast**
We only want to send a broadcast if the broadcast message is not stubbed
and the service is live at the point at which the broadcast event should
be created. This is to prevent the situation where a broadcast service is
switched to live / trial mode in between the message being created and
approved (we log an error if this happens).
A …
> Check if service is in live mode before sending a broadcast

- manifest.yml.j2
We no longer need this as it has been replaced by the api-sms-receipts
app which is the new app with the correct name but no functionality
change.
> Remove api-sms-callbacks app

- app/celery/scheduled_tasks.py
- tests/app/celery/test_scheduled_tasks.py
Update the Zendesk ticket content for `check_if_letters_still_in_created`
The message to Zendesk includes a list of notification ids, this isn't really necessary and is included in the run book. Creation of the
Zendesk ticket can fail if the message is too long, removing the list of ids can prevent that from happening.
> Update the Zendesk ticket content for `check_if_letters_still_in_created`

- app/billing/rest.py
- app/dao/annual_billing_dao.py
- tests/app/billing/test_billing.py
Simplify the get_free_sms_fragment limit for the case when the row is missing, by setting the free allowance to the default.
> Set free allow to default if row is missing when calling GET

- app/broadcast_message/rest.py
- tests/app/broadcast_message/test_rest.py
Also update error message for when someone does not have permissions.
The message referenced approving broadcasts specifically, whereas people would also see it if they try to cancel or reject broadcast without permission.
Why we allow platform admins to cancel broadcasts:
we do this so they can react quickly if a broadcast was approved by accident.
Pivotal ticket: https://www.pivotaltracker.com/story/show/177482418
Admin PR: https://github.com/alphagov/notifications-admin/pull/3854
> Allow platform admins to cancel broadcasts.

- app/celery/broadcast_message_tasks.py
This tries to make it clear what the different IDs in the log messages are and adds a bit more detail.
[Pivotal story](https://www.pivotaltracker.com/story/show/177493786)
> Add detail to broadcast logging messages

- app/broadcast_message/broadcast_message_schema.py
- app/broadcast_message/rest.py
- app/template/rest.py
- tests/app/broadcast_message/test_rest.py
- tests/app/template/test_rest.py
This changes the content length validation of the internal API to match the validation of the public broadcast API<sup>1</sup>.
This removes the length check from JSONSchema, which isn’t sophisticated enough to deal with things like normalising newlines or handling different encodings.
The admin app should catch these errors before they’re raised here, but it’s best to be belt and braces.
It also adds a check for creating templates, similar to the existing one we have for SMS.
***
1. https://github.com/alphagov/notifications-api/blob/7ab0403ae7ab9c9a17b3fb6595c8c8d2f8b32cbb/app/v2/broadcast/post_broadcast.py#L53-L63
> Normalise broadcast content before validating length

- app/celery/celery.py
- tests/app/celery/test_celery.py
https://www.pivotaltracker.com/story/show/176261229
This applies the same change we made in other apps [1][2]. Adding
the override here is special, though, because it means the others
will now get triggered, since this app is the start of the chain
of tasks for a request. We will also retain existing request_id
tracing for tasks within this app, since "apply_async" calls the
"send_task" method internally, which is the one we're overriding.
These show the logs we get for sending a precompiled letter, filtered by request ID. The difference is that more of the logs now have the request ID field populated, and so show up with the filter applied.
| Before | After |
| ------ | ------ |
| ![screencapture-kibana-logit-io-s-4c3b5032-5afa-42e5-8211-bcba010be352-app-kibana-2021-04-27-11_29_28](https: …
> Move request_id injection into send_task override

- app/dao/annual_billing_dao.py
- app/models.py
- migrations/versions/0351_unique_key_annual_billing.py
This is an extra precaution for the table to ensure data integrity. Since we only update/insert the data using the annual_billing_dao methods the integrity is in tact. I've check the data on preview, staging and prod there are no violations of this unique key.
> Add unique key on annual_billing for service_id + financial_year_start.

- Makefile
if you run `make help` or just `make` then you get a nice list of the
tasks that you can run (or at least, the ones with help text added to
them.
We were missing these for some of the key commands that a developer
would want to know about.
By adding help text to them, they will now show up in `make` or `make
help` and saves a developer needing to go either look in the README or
go look in the Makefile to figure out what commands are available.
Note, there is no particular convention around which commands have help
comments. I don't think we need to figure out this but at the least, the
ones which developers may want to run locally I think should show up.
> Add make help commands for commonly used tasks

- app/config.py
If this alert goes off in the morning, it usually means we need to do
something, ideally quite quickly as it indicates a potential problem
with the sending of letters over to DVLA the night before.
Given this goes off at 9am at the moment, but actually some people start
work earlier, if we alert at 7am it means it will likely be looked at
earlier in the day and we can potentially fix any problems with letters
sooner than later.
> Make check-if-letters-still-in-created run at 7am

- app/broadcast_message/rest.py
- app/celery/broadcast_message_tasks.py
- app/clients/cbc_proxy.py
- tests/app/broadcast_message/test_rest.py
- tests/app/celery/test_broadcast_message_tasks.py
https://www.pivotaltracker.com/story/show/177758598
Note that this should be unnecessary, since:
- The API routes for broadcasts already have this protection [1][2].
- The Admin app prevents any action against a suspended service [3].
However, just like for jobs, we feel it's important to have a secondary layer
of checks for such a high impact action.
[1]: https://github.com/alphagov/notifications-api/blob/3d71815956eb930a1683d47e60d8c4a53974fd32/app/__init__.py#L312
[2]: https://github.com/alphagov/notifications-api/blob/3d71815956eb930a1683d47e60d8c4a53974fd32/app/authentication/auth.py#L112
[3]: https://github.com/alphagov/notifications-admin/pull/3854/commits/63c597d540be7457ac5a489a3dcc99539e5c2ce6#diff-09dc9a05865349d00b85e381975b49e62 …
> Enforce service suspension for broadcasts

- migrations/README.md
This clarifies how we generate migration filenames, and points to
the official docs and help commands, instead of repeating them.
> Rewrite migration README

- app/dao/services_dao.py
https://www.pivotaltracker.com/story/show/177908219
Second attempt [1]. This increases the threshold so:
- It's a more substantial amount of money lost (£16).
- It's 10% of the minimum free allowance for a service.
- It's greater than the threshold we have for TV numbers (500).
Having a higher threshold for this alert will help prevent wasted
effort investigating more negligible failures, and reduces the
ambiguity of whether we should take action: we should.
[1]: https://github.com/alphagov/notifications-api/pull/3221
> Increase warning threshold for SMS failures

- app/celery/letters_pdf_tasks.py
- app/dao/notifications_dao.py
- tests/app/celery/test_letters_pdf_tasks.py
DVLA would like to be able to identify letters sent by the Insolvency Service, so we are changing the zipfile name. They need all zipfile names to have the same structure, so we can't just add a marker to files sent by that service - we have to change all filenames.
The new format is like this: `{NOTIFY}.{DATE}.{SEQUENCE_ID}.{UNIQUE_ID}.{SERVICE_ID}.{ORG_NAME}.{EXTENSION}`
[Pivotal story](https://www.pivotaltracker.com/story/show/177644984)
_**Note**_
This change means that we now call `letter.service.organisation_id` (where `letter` is a `Notification`) for each letter, so we are now loading the service relationship. However, the alternative would be to make [this query](https://github.com/alphagov/notifications-api/blob/0161adca063ee58d2ee38b394a646e6afb8ebade/app/dao/notifications_dao.p …
> Change letter zip file names for Insolvency Service letters

- app/dao/broadcast_service_dao.py
- app/models.py
- app/service/service_broadcast_settings_schema.py
- migrations/versions/0352_broadcast_provider_types.py
- tests/app/celery/test_broadcast_message_tasks.py
- tests/app/service/test_rest.py
- tests/conftest.py
This adds a type table for broadcast providers, which is the pattern we
follow with our models (e.g. we have a `broadcast_channel_types` table).
As well as the four providers, the migration populates it with `all`
which is the value that will replace `null` in a later change.
It should be safe to add the foreign key constraint to the
`service_broadcast_settings` in the same migration since the column is
still nullable and we don't have data in that column that is not in the
types table.
Step one of [Pivotal story](https://www.pivotaltracker.com/story/show/177759863)
> Add a type table for broadcast providers

- app/models.py
- app/service/service_broadcast_settings_schema.py
- migrations/versions/0353_broadcast_provider_not_null.py
- tests/app/celery/test_broadcast_message_tasks.py
- tests/app/service/test_rest.py
**Make service_broadcast_settings.provider non-nullable**
We set all existing null values to "all", then make the column
non-nullable. Admin is already passing through the value of "all".
**Remove references to broadcast provider_restriction being `None`**
Part three of [Pivotal story](https://www.pivotaltracker.com/story/show/177759863)
Must be merged after
> Make service_broadcast_settings.provider non-nullable

- app/service/service_broadcast_settings_schema.py
- migrations/versions/0354_government_channel.py
- tests/app/celery/test_broadcast_message_tasks.py
- tests/app/service/test_rest.py
This adds "government" to the broadcast_channel_types table. It also adds it to the service_broadcast_settings_schema so that notifications-admin can pass through a value of "government". We don't have any logic around the value of service.broadcast_channel, so no updates are needed to the tasks etc.
[Pivotal story](https://www.pivotaltracker.com/story/show/178110633)
> Add "government" as a broadcast channel type

- manifest.yml.j2
This will allow shipping app and router logs to splunk[1]
This is only bound on the API because we're only interested in
paas router logs for the time being
1: https://github.com/alphagov/paas-csls-splunk-broker/blob/main/docs/user-guide.md
Same as alphagov/notifications-admin#3888
> Add splunk service

- app/user/rest.py
- app/user/users_schema.py
- tests/app/user/test_rest.py
with sms and email auth the api handles verifying logins in the `/<user_id>/verify/code` endpoint, when it checks the code is valid etc. The admin app has already done this for webauthn logins, but we still need an API endpoint so that we can set up the user's db entry to have a new logged in timestamp, a new session id (this is important for logging out other browser sessions), etc.
Also, we need to be able to make sure that the user's max login count isn't exceeded. If it's exceeded, we shouldn't let them log in even with a valid webauthn check.
This endpoint is a POST where the admin passes in a json dict with key "succesful" being True or False. True sets up the db stuff as mentioned. False just increments the failed login count.
> add endpoint for verifying webauthn login

- app/__init__.py
- app/notifications/validators.py
- app/v2/notifications/get_notifications.py
- requirements-app.txt
- requirements.txt
- requirements_for_test.txt
- tests/app/celery/test_scheduled_tasks.py
- tests/app/dao/test_fact_notification_status_dao.py
- tests/app/user/test_rest.py
- tests/app/v2/notifications/test_post_letter_notifications.py
- tests/app/v2/test_errors.py
Reverts alphagov/notifications-api#3250
Some sort of potential memory leak
@servingUpAces has said in slack
> If you need to revert  https://github.com/alphagov/notifications-api/pull/3250/files, that is okay. It will only mean that the new validation for letters will not happen for templated letters posted to the API. It will not affect precompiled letters or letters uploaded via UI or CSV files.
Next steps are not as clear but potentially we could wait a week or two and try again with newer versions and hope that someone found the bug and fixed it
> Revert "Bump utils version for new invalid address character"

- app/dao/services_dao.py
- tests/app/dao/test_services_dao.py
We have an index on Notifications(service_id, created_at), by updating the query to use between created_at rather than date(created_at) this query will use the index. See the commit message for details about the query plan. 
This query is still rather slow but is improved by this update.
https://www.pivotaltracker.com/story/show/178263480
We can try to revert https://github.com/alphagov/notifications-admin/pull/3895 once this is deployed.
> Update the dao_fetch_todays_stats_for_service query.

- app/celery/broadcast_message_tasks.py
- app/celery/scheduled_tasks.py
- tests/app/celery/test_scheduled_tasks.py
Many of the team members do not look at emails from zendesk, adding a current_app.logger.error message for things we care about to give developers a better chance of seeing them.
I have purposely not added an erro log for `check_for_services_with_high_failure_rates_or_sending_to_tv_numbers` because it's not something we need to look at immediately.
> Add a error log for alert tasks.

- app/dao/fact_notification_status_dao.py
- tests/app/dao/test_fact_notification_status_dao.py
This change is a temporary fix to allow users for high volume services to use the admin app.
The trouble is the aggregate query to return the big blue numbers on the dashboard and /notifications/{notification_type} page is taking too long to return.
I have some ideas on how to improve the query, but should take some time to do some more research and test. In the meantime, let's just ignore "todays" total numbers for the high volume services. There are only two services that this will affect.
> Do not include today's totals

- app/dao/fact_notification_status_dao.py
- tests/app/dao/test_fact_notification_status_dao.py
The expected behavior was that the /notifications page would load for high volume services - that does not seem to be the case for reasons beyond my understanding at this point. 
Reverting this until I can figure it out.
> Revert "Do not include today's totals"

- app/user/rest.py
- tests/app/user/test_rest.py
it doesn't really do any verification - that's the webauthn code in the browser and the admin app that does that. Instead, this completes the login flow, by marking the user as logged in in the database. Added a docstring that explains this process a bit more, and also added a new route: `/<id>/complete/webauthn`. We'll move the admin code over to use this new url in time.
> rename verify webauth endpoint to complete

- app/authentication/auth.py
- tests/app/authentication/test_authentication.py
previously 'invalid-strings' would be handled, but integers would just return 500.
> make sure all non-uuid service ids 403 in api keys

- app/dao/fact_billing_dao.py
- app/platform_stats/rest.py
- tests/app/dao/test_ft_billing_dao.py
- tests/app/platform_stats/test_rest.py
This adds total_letters to the data that is returned by the `/platform-stats/data-for-billing-report` endpoint so that we can add total letters as a column in the CSV file that can be downloaded.
[Pivotal story](https://www.pivotaltracker.com/story/show/177558710)
> Add new total_letters field to the billing report data

- Makefile
Related to: https://github.com/alphagov/notifications-aws/pull/905
Previously this would fail because the Docker image we use for CI
builds doesn't have an 'environment.sh' file; it uses preset env
vars instead. This makes the command to load the file optional,
for which the error should be self evident if it's missing locally.
> Fix 'flask db upgrade' not working on CI

- app/celery/tasks.py
We had a situation where the delivery-worker app instance was terminated before the job was marked as `in-progress`, presumably because the query to check the daily limits was taking too long to complete.
If the job was in progress the `check_job_status` task would have restarted the job.
Updating the status to in-progress sooner will help.
> Update the job_status to in-progress sooner.

- app/dao/services_dao.py
- tests/app/dao/test_services_dao.py
The query to check daily totals had a group by on notification_type and notification_status, this not only slows the query down but is wrong. The query only looked at the first result, but this query would return as many rows as different notification types and status, meaning the results do not include the correct number. The query is used by process_job task when a CSV is uploaded or send on-off notification or upload a pdf.
This improves the query.
> Improve the query to get today's totals for a service.

- app/models.py
- tests/app/test_model.py
It's possible a letter can pass our validation but our print provider can not print the letter. The letter will be marked as permanent failure in this case. Typically happens with precompiled letters.
> Add permanent-failure for letters.

- Makefile
This was added by mistake - the Concourse pipeline never did this
previously, and errors if we try (the necessary environment vars
aren't present, even if we wanted to).
> Don't try to upgrade DB on CI

- app/models.py
- Update the Notification and NotificationHistory model to reflect the database.
- Updates to datatypes, removal of indexes and addition of indexes.
After running the `flask db migrate` command there are many deltas because we did some work to update the notification and notification_history tables, however, the SQLAlchemy models were not updated to reflect those changes. This PR cleans up all those deltas.
However, there are still some differences that can be done but we can look at that in another PR.
- Run `flask db upgrade --rev-id before` 
- move before.py out of migrations 
- Checkout this branch
- Run `flask db upgrade --rev-id after`
You should see a significant difference in the two scripts
> Tidy up models

- app/delivery/send_to_providers.py
- app/serialised_models.py
- app/v2/notifications/post_notifications.py
Just looks a bit tidier and less repetitive.
I’ve only done this for the serialised service because:
- we’re only checking this in places where we’re already using the serialised service
- if we want to check this elsewhere there’s a good chance that new code should be using the serialised service, since it’ll itself be doing some kind of performance optimisation
> Refactor high volume into serialised service model

- app/service/rest.py
- tests/app/service/test_rest.py
This wasn't working - the error given when trying to access it was `TypeError: Object of type 'Row' is not JSON serializable` when we tried to serialize a SQLAlchemy Row.
I haven't looked too far into what has changed to stop this from working, but have just changed the endpoint to return a nested list instead.
> Fix the endpoint for the monthly status report

- app/celery/tasks.py
- app/dao/services_dao.py
- app/notifications/process_notifications.py
- app/notifications/validators.py
- tests/app/celery/test_tasks.py
- tests/app/dao/test_services_dao.py
- tests/app/notifications/test_process_notification.py
- tests/app/notifications/test_validators.py
Last year we had an issue with the daily limit cache and the query that was populating it. As a result we have not been checking the daily limit properly. This PR should correct all that.
The daily limit cache is not being incremented in app.notifications.process_notifications.persist_notification, this method is and should always be the only method used to create a notification.
We increment the daily limit cache is redis is enabled (and it is always enabled for production) and the key type for the notification is team or normal.
We check if the daily limit is exceed in many places:
- app.celery.tasks.process_job
-  app.v2.notifications.post_notifications.post_notification
- app.v2.notifications.post_notifications.post_precompiled_letter_notification
- …
> Correct the daily limits cache.

- app/notifications/validators.py
- tests/app/notifications/test_validators.py
I forgot to return service_stats if the cache exists. And fixed the tests to check service_stats value.
> Fix bug in check_service_over_daily_limit

- app/models.py
- tests/app/conftest.py
- tests/app/service/test_sender.py
- tests/app/test_model.py
- tests/app/user/test_rest.py
https://www.pivotaltracker.com/story/show/178609960
Currently we have some data-driven roles to say who can use this feature.
Adding a flag in the API means we can avoid API calls in the Admin app to
determine the same.
Allowing members of the GOV.UK Notify service to use the feature is a
workaround, so we can avoid making someone a Platform Admin before they've
protected their account with it.
> Add flag to say if user is eligible for WebAuthn

- app/models.py
- migrations/versions/0359_more_permissions.py
We want to have new permissions which will be used specifically for broadcasts:
- `create_broadcasts`
- `approve_broadcasts`
- `reject_broadcasts`
- `cancel_broadcasts`
Cancel and reject will always go together, but having separate database permissions makes things easier to change in the future.
The permission column of the permissions table is an enum. We can add values in the alembic upgrade script, but removing individual values from an enum is not supported by Postgres. To remove values, we have to recreate the enum with the old values.
[Pivotal story](https://www.pivotaltracker.com/story/show/178482657)
> Add new broadcast related permissions

- app/dao/broadcast_service_dao.py
- app/service/rest.py
- tests/app/service/test_rest.py
The "normal" service permissions and broadcast service permissions are
going to be different with no overlap. This means that if you were
viewing the team members page, there might be permissions in the
database that are not visible on the frontend if a service has changed
type. For example, someone could have the 'manage_api_keys' permission,
which would not show up on the team members page of a broadcast service.
To avoid people having permissions which aren't visible in admin, we now
remove all permissions from users when their service is converted to a
broadcast service.
Permisions for invited users are also removed.
It's not possible to convert a broadcast service to a normal service, so
we don't need to cover for this scenario.
> Remove user permissions if service becomes a broadcast service

- app/__init__.py
- app/authentication/auth.py
- requirements-app.txt
- requirements.txt
- requirements_for_test.txt
- tests/app/celery/test_scheduled_tasks.py
- tests/app/dao/test_fact_notification_status_dao.py
- tests/app/user/test_rest.py
- tests/app/v2/broadcast/test_post_broadcast.py
See https://github.com/alphagov/notifications-utils/pull/878 for details.
Changes we had to make for our app and tests to work correctly after the dependency updates:
1. Update emergency alerts polygons test because we changed how exact we are with locations of the points on the map.
2. Use Flask's g object to set additional request attributes
So far we have been storing them in _request_ctx_stack which is an innard for Flask's request context.
Because of major update to Werkzeug dependency, which Flask relies on, the way we were using it stopped working, so we had a new way to set those values.
The way we set those values now, by using g object, seems to also be favoured in Flask documentation:
https://flask.palletsprojects.com/en/1.1.x/reqcontext/#how-the-context-works
> Bump utils to bring in fix for optional placeholder bug

- app/celery/service_callback_tasks.py
- tests/app/celery/test_service_callback_tasks.py
if we're served a 429, put the item on the retry queue and retry the same as if the service returned a 5xx. 429 is commonly returned for rate limit exceeding, and retrying on a delay is a typical response to that.
> retry service callbacks on 429

- requirements-app.txt
- requirements.txt
We observe high memory usage since we bumped it (along with other
things) and because it only appears on the API and not on the workers
the hypothesis is that Werkzeug is responsible for it.
> Revert werkzeug to the last non-2.0.0 version

- migrations/versions/0361_new_user_bcast_permissions.py
The broadcast user permissions are changing, so to avoid confusion and permissions which exist in the database but don't display on the frontend we are going to remove all existing permissions for users of broadcast services. This also updates the permissions of invited users who are still pending.
The exception to this is the `view_activity` permission, which we [always add for broadcast users](https://github.com/alphagov/notifications-admin/blob/aad017a184d314d9d192f4b9d6485915f83217c1/app/main/forms.py#L1043) even if they have no other permissions.
[Pivotal story](https://www.pivotaltracker.com/story/show/178482657)
> Remove original permissions from broadcast users

- app/dao/broadcast_service_dao.py
- tests/app/service/test_rest.py
We made a change to remove all permissions from users and invited users when the broadcast service settings form is submitted (#3284). However, when the form is submitted, notifications-admin always [adds the `view_activity`
permission](https://github.com/alphagov/notifications-admin/blob/256c840b46d4095edbd0af105e5c1a340242575d/app/main/forms.py#L1042) even if no permission boxes are ticked, so we don't want to remove that one permission.
> Always keep view activity permissions for broadcast users

- app/celery/broadcast_message_tasks.py
- app/clients/cbc_proxy.py
- tests/app/celery/test_broadcast_message_tasks.py
- tests/app/clients/test_cbc_proxy.py
https://www.pivotaltracker.com/story/show/178738544
Previously there was a risk that we'd only find out that the failover lambda
was broken at the point when we needed it. This rewrites the link test task
and its supporting code to make it easy to test each lambda independently.
Paired with @rjbaker
> Trigger separate link test for failover lambda

- app/celery/scheduled_tasks.py
- app/config.py
- tests/app/celery/test_scheduled_tasks.py
https://www.pivotaltracker.com/story/show/178926353
Since the expiry is sent as part of the message payload, we don't
need to invoke the CBC proxies (and indeed there's no way to do so
for an expired alert). In future we plan to extend this task so it
triggers the regeneration of content on gov.uk/alerts.
It's worth noting that 'finishes_at' can theoretically be None, in
which case it's unclear when the alert should expire. While alerts
from the Admin app should always have an expiry [1], we have many
in the DB that don't, so it's worth checking for this scenario.
[1]: https://github.com/alphagov/notifications-admin/blob/078ac10c8df855a84c157190d43daa9a8897832b/app/models/broadcast_message.py#L255
> Auto expire old broadcast messages

- manifest.yml.j2
This is to see if the worker requires slightly more memory than it has access to or to determine if there is a memory  leak somewhere in the code that needs to be further investigated.
This comes at the heels of yesterday's issue that we could not process the CSVs the users uploaded, where the memory graph for this worker showed that it was using almost all of its available memory, so a redeploy fixed the problem.
> Set jobs worker memory to 2GB

- app/dao/broadcast_service_dao.py
- tests/app/service/test_rest.py
On a regular Notify service anyone with permission can create an API key. If this service then is given permission to send emergency alerts it will have an API key which can create emergency alerts. This feels dangerous.
Secondly, if a service which legitimately has an API key for sending alerts in training mode is changed to live mode you now have an API key which people will think isn’t going to create a real alert but actually will. This feels really dangerous.
Neither of these scenarios are things we should be doing, but having them possible still makes me feel uncomfortable.
This commit revokes all API keys for a service when its broadcast settings change, same way we remove all permissions for its users.
> Revoke API keys when changing broadcast settings

- app/service/rest.py
- requirements-app.txt
- requirements.txt
- tests/app/service/test_rest.py
Show separate error for when user tries to cancel letter that is already cancelled. 
This is to show a better error messages to our users, and also so we have more detailed log messages for related errors.
Relies on: https://github.com/alphagov/notifications-utils/pull/886
Needed for: https://github.com/alphagov/notifications-admin/pull/3984
> Show separate error for when user tries to cancel letter

- app/__init__.py
- app/authentication/auth.py
- app/config.py
- app/v2/govuk_alerts/__init__.py
- app/v2/govuk_alerts/get_broadcasts.py
- tests/__init__.py
- tests/app/authentication/test_authentication.py
https://www.pivotaltracker.com/story/show/179039225
Previously we just had a single array of "API SECRETS" that any app could use to
get access to any internal API. This replaces that approach with something that's
much more similar to service API keys: each app is like a "service", with its own
array of allowed "Internal API keys".
Making this change was hard because:
- Half the tests were written using one pattern (calling functions directly) and
half were written using another pattern (calling an arbitrary endpoint).
- The "requires_auth" function does similar but different checks, which meant a lot
of the tests were duplicated, but others were missing - it was hard to tell.
A lot of the commits are about DRYing up and simplifying the tests (and adding ones
that were missing), so that …
> Split up authentication for internal API endpoint

- app/delivery/send_to_providers.py
- tests/app/delivery/test_send_to_providers.py
As of https://github.com/python/cpython/commit/041d8b48a2e59fa642b2c5124d78086baf74e339 it’s not valid to call `random.choices` without giving at least one of the options a positive weighting.
This makes sense, because giving a zero weighting is effectively saying ‘theres’s only one choice, but don’t choose it’.
In our codebase this is applicable where there’s only one international provider, which we want to use even when it’s been de-prioritised for domestic SMS.
This doesn’t cause a problem now, but will if we upgrade to Python versions greater than 3.9.0.
> Don’t call random.choices with zero weighting
