app/__init__.py
config.py
requirements.txt

Adds logging from notifications-utils
- log level, location and app name set from config
NOTIFY_LOG_LEVEL = 'DEBUG'
NOTIFY_APP_NAME = 'api'
NOTIFY_LOG_PATH = '/var/log/notify/application.log'
- Application logs to console when running in DEBUG mode
- Application logs to file when not in DEBUG mode, logs in text and in json.
- Need to create folder locally in the required location for app to work.

Added logging from notifications-utils.

---

app/__init__.py
app/dao/jobs_dao.py
app/job/rest.py
tests/app/dao/test_jobs_dao.py
tests/app/job/test_job_rest.py

The service id path parameter is captured in the url prefix for the
job blueprint.

Fix for job urls that should have been within context of a service.

---

app/dao/api_key_dao.py
app/service/rest.py
tests/app/dao/test_api_key_dao.py
tests/app/service/test_api_key_endpoints.py

Previously we assumed there was only one api key that was valid.

Update api-key/revoke endpoint to expire the key for the service.

---

app/authentication/auth.py
app/notifications/rest.py
app/schemas.py
config.py
tests/app/notifications/test_rest.py

Once removal of code that uses existing alpha is done, then
duplicated code from /notifications/sms and the new endpoint
can be merged.
Job id is now available in notification but is not used yet.

New endpoint for delivery app to use.

---

app/schemas.py

When the delivery app creates the sms on behalf of the service,
the validation was failing.

Fix validation of template for service.

---

README.md

that suggested in delivery app.
Called out the reason for unique prefixes or queue names.

Updated sample values for secret keys in environment.sh to match

---

app/__init__.py
app/celery/tasks.py
app/clients/sms/firetext.py
config.py
environment_test.sh
tests/app/celery/test_tasks.py

Pulls in a very (too) simple client to send SMS via Firetext
Firetext is a G-Cloud SMS supplier. This will deliver SMS's that are created using the client API - so not the validation code ones.
Requires new properties:
- FIRETEXT_NUMBER - From number for the text
- FIRETEXT_API_KEY - API key for firetext
This replaces twilio for those calls.
Will need a more detailed set of clients for full on beta delivery. This is to get us off twilio to see if delivery is better. The start not the end of SMS integrations.

Fire text client

---

app/errors.py
app/job/rest.py
app/notifications/rest.py
app/service/rest.py
app/template/rest.py
app/user/rest.py
tests/app/service/test_rest.py

Replace some 400s with more appropriate 500s.
Calls to dao functions or any others that cause unexpected exceptions get caught and
logged by errors.py 500 error handler.

Wire up error handlers.

---

app/errors.py
app/schemas.py
app/user/rest.py
tests/app/user/test_rest.py
tests/app/user/test_rest_verify.py

- Created new endpoint user/<user_id>/sms-code to send the sms verification code to the user.
- Create new endpoirtn user/<user_id>/email-code to send the email verifcation code to the user.
- Marked the old methods, schema, tests with a TODO to be deleted when the admin app is no longer sending messages to /user/<user_id>/code
- Added error handlers for DataError and NoResultFound. Data error catches invalid input errors.
- Added error handler for SqlAlchemyError which catches any other database errors.
- Removed the need for the try catches around the db calls in the user endpoints with the addition of the db error handlers.
- We may want to wrap db exceptions in the dao, if we want the No results found message to be more specific and say no result found for user.

Refactor user/<user_id>/code into two endpoints.

---

config.py
scripts/run_celery.sh

- now in config not the script
Note - uses default exchange / routing keys, TBD if this is OK for production.

Moved the deinition of which queues the worker will consume from

---

app/celery/tasks.py
tests/app/celery/test_tasks.py

When building the template it was looking for a placeholder called ((phone number)). This caused it to fail because the template it had did not match the personalisation it was being given.
`Template` has an optional parameter for specifying personalisation values that should be ignored. The recipient of a message is an example of such a value.
This commit passes that extra parameter, which fixes that bug.

Fix bug where sending messages failed

---

app/celery/tasks.py
app/models.py
tests/app/celery/test_tasks.py
tests/app/conftest.py

This is checked on 3rd party API calls, but jobs (CSV files) were able expected to only allow valid files.
Change in tack means we want to have restricted notification failures reported in the UI.

Ensure restricted service are respected by tasks:

---

app/template/rest.py
requirements.txt
tests/app/template/test_rest.py

Templates are created in the admin app and persisted in the API.
They are consumed:
- in the admin app, by requesting them from the API
- in the API, by loading them from the database
There are two potential places where unescaped HTML could be sent to a user:
- when the admin app is previewing a template (it has to render the template as markup in order to show the placeholders)
- in the body of an email
For all consumers to have confidence that the templates are safe, it makes sense to sanitise them at the point of creation (and modification). This also avoids any performance issues that could come from doing it at the point of requesting a template.
In the future they could be created by a direct API call, bypassing the admin app, another reason for this to happen in the API.
The …

Strip HTML from template content

---

app/celery/tasks.py
app/schemas.py
requirements.txt
tests/app/conftest.py
tests/app/notifications/test_rest.py

***
See alphagov/notifications-utils#9 for details of the changes.
This was added to utils in alphagov/notifications-utils@5914da7
This means that:
- we are doing the exact same validation in the API and admin app
- we are actually validating phone numbers for the correct format (hence all the changes to the tests)
This uses the `format_phone_number` method from utils to output phone numbers in a consistent format. It is added to the schemas, so will be applied before the API tries to do anything with a provided phone number.
So now the API will accept any of the following:
- 07123456789
- 07123 456789
- 07123-456-789
- 00447123456789
- 00 44 7123456789
- +447123456789
- +44 7123 456 789
- +44 (0)7123 456 789
…but the API will always hand off phone numbers to 3rd party APIs in the format …

Use utils to validate and iterate over recipients

---

.gitignore
app/celery/tasks.py
app/dao/invited_user_dao.py
app/dao/notifications_dao.py
app/dao/users_dao.py
app/notifications/rest.py
config.py
scripts/run_celery_beat.sh
tests/app/celery/test_tasks.py
tests/app/conftest.py
tests/app/dao/test_invited_user_dao.py
tests/app/dao/test_notification_dao.py
tests/app/dao/test_users_dao.py
tests/app/notifications/test_rest.py

Scheduled tasks to clean up the database  …
- tasks run hourly
- uses celery beat to schedule the tasks
4 new tasks
- delete verify codes (after 1 day)
- delete invitations (after 1 day)
- delete successful notifications  (after 1 day)
- delete failed notifications (after 7 days)
Delete methods in the DAO classes - 1 per type of delete
Schedule:
is a little bit staggered: see the config for the frequency of the jobs.
To run this there is a new script (run_celery_beat.sh) which starts the scedular. This puts tasks on the "peridoic" queue with the frequency as defined in the config.

Delete expired things

---

app/celery/tasks.py
tests/app/celery/test_tasks.py

This pull request fixes a bug introduced here: https://github.com/alphagov/notifications-api/commit/832375744185f35cdb7d739a49ccbaefa44ce6e6
***
If a service is in restricted mode then a user can’t send messages to anyone other than themselves and members of their team. To do this the API has to compare the numbers they are sending to with those of their team members.
It will (falsely) say the numbers do not match if they are in a different format, eg 07700 900849 vs +447700900849
This commit uses the code we use elsewhere for formatting phone numbers to make sure that both numbers are in a consistent format before doing a comparison.
I have a strong preference for doing it this way, rather than formatting numbers before we store them:
1. https://en.wikipedia.org/wiki/Robustness_principle …

Be agnostic about format when comparing phone numbers

---

app/__init__.py
app/celery/tasks.py
app/clients/email/aws_ses.py
app/clients/sms/firetext.py
app/dao/notifications_dao.py
app/models.py
app/notifications/rest.py
migrations/versions/0039_more_notification_states.py
migrations/versions/0040_add_reference.py
test_ses_responses/ses_response.json
tests/app/__init__.py
tests/app/celery/test_tasks.py
tests/app/conftest.py
tests/app/dao/test_notification_dao.py
tests/app/notifications/test_rest.py

I'm not in today so this could wait till Monday for demos, raising pull request for code review only, and to park this work.
Commented the files a bit in this pull request to help reviews.
This pull request wires in the callbacks from Firetext and AWS SES. In both cases when a message has been processed by those platforms they call back to a URL on Notify to update the status:
Firetext:
- Update to SMS task to send notification id as a "reference". This is passed back in the callback to allow status updates
- Validation codes use the 'send-sms-code' as the reference to allow us to know whether to attempt a notification update
- Firetext client has an object to map firetext status codes to notifcation states.
- New endpoint in the notification rest controller - POST …

Client callbacks

---

scripts/aws_start_app.sh
scripts/aws_stop_app.sh

Primarily to handle the two celery processes
- On the environments we have start/stop scripts for the 3 API types
- Normal API
- Celery Workers
- Celery Beat
We now have a different upstart script for each, and there may be more than one on a box, so check for the upstart scripts and if present use them.

Updated aws start/stop scripts to handle multiple start/stop scripts

---

app/__init__.py
run_celery.py

- allows logger to log as correct application
This allows the delivery api to set app name as 'delivery' to allow easier log filtering

Pass application name in from start scripts

---

app/celery/tasks.py
app/user/rest.py
config.py
tests/app/conftest.py
tests/app/user/test_rest_verify.py

On initial registration user is sent a link to click on to verify email address.
Left original email code endpoint in as it is still used for things like email change.
The work in this pr is needed for https://github.com/alphagov/notifications-admin/pull/293

Added task for sending email verification links

---

app/celery/tasks.py
app/clients/email/aws_ses.py
requirements.txt
tests/app/celery/test_tasks.py

Make the SES client optionally pass through HTML and text body, as per:
http://docs.aws.amazon.com/ses/latest/APIReference/API_Body.html
Gets the message as HTML from:
https://github.com/alphagov/notifications-utils/pull/12

Add HTML email

---

app/notifications/rest.py
tests/app/notifications/test_rest.py

Post endpoint to create notification and get endpoint to retrieve notification by id return 
data in shape more consistent with other api endpoints.

Align notifications api with docs and other endpoints

---

app/celery/tasks.py
tests/app/celery/test_tasks.py

The Celery `send_sms` and `send_email` tasks _could_ assume that all the recipients it gets are safe, because they have been checked either:
- when the admin app processes the CSV
- in the `/notifications/sms|email` endpoint
**However**, it’s probably safer to make the check again when the Celery task runs and passes the message off to the third party.
This also means that changing a service _back_ to restricted would have an effect on messages that were queued, as well as all subsequent messages.
This commit:
- restores the test that was removed here: https://github.com/alphagov/notifications-api/commit/e56aee5d1d77142b78434f3faeddfd2cb1a6e9bf#diff-e5627619e387fccc04783c32a23e6859L346
- adds a similar test for sending email while a service is in restricted mode
- adds checks back into …

Catch sending to restricted recipients in Celery

---

app/dao/notifications_dao.py
tests/app/dao/test_notification_dao.py
tests/app/template_statistics/test_rest.py

It should always be last n days, whether or not there is data.

Fix for date range required for template stats

---

requirements.txt

Implements and depends on:
Depends on this admin app deploy:

Use version of crown logo hosted by admin app

---

app/authentication/auth.py
requirements.txt
tests/app/authentication/test_authentication.py

This pull request removes the need for the req and pay in the claims JWT.
Use the new version of the notifications-python-client. This version no longer adds the req and pay to the claims of the jwt.
The change is backward compatible so an older client that sends a JWT with the extra claims will pass authentication.
Once all the clients have been updated to not include the extra claims some updates to exclude them from the method signatures will happen as well.
https://www.pivotaltracker.com/story/show/116971293

Simplify jwt

---

app/celery/tasks.py
requirements.txt

Implements (and depends on) https://github.com/alphagov/notifications-utils/pull/24
Works for:
- emails we send to users, eg invite, forgot password
- email templates that users have created
***
***

Stop GOV.UK becoming a link in email clients

---

app/dao/notifications_dao.py
app/notifications_statistics/rest.py
tests/app/dao/test_notification_dao.py

On the dashboard we want to show counts of notifications sent in the last 7 days, plus today. So the API endpoint needs to accept an argument to limit how many days worth of statistics it will return.
This is a bit fiddly at the DAO level because the date is just stored as a string.
https://www.pivotaltracker.com/story/show/117920839

Allow filtering of notification stats by days

---

app/notifications_statistics/rest.py
tests/app/notifications/test_rest.py

The response import was missing, which broke things.
There was no test to catch this.
This commit adds a rudimentary test to make sure that the endpoint doesn’t 500, at the very least.

Fix missing import on notification stats endpoint

---

app/schemas.py
app/service/rest.py
tests/app/service/test_rest.py

This is a temporary endpoint to get history of service and api key updates. 
This will be surfaced on a simple log page on admin app until product team work out who/how/when etc. of viewing history data.

Temp history of endpoint

---

app/dao/api_key_dao.py
app/dao/dao_utils.py
app/dao/services_dao.py
tests/app/dao/test_api_key_dao.py

When using the versioned decorator I noticed that when adding or revoking an api key the service it associated with was of course added to db.session.dirty.
That resulted in an updated version of service being added to the service history table that showed no visible difference from that record immediately preceding it as the change was to another table,
namely the api_key table. 
A new api key or revoked api key was correctly added to api_key and api_key_history tables. However I think an 'unchanged' service history record may be a bit confusing as you'd need to correlate with api_keys to work out what the change was.
I think it's best to just record the new/revoked api_key and not create another version of the service.
This pr wraps the existing versioned decorator with one that take a …

Only record history for specified class

---

app/dao/notifications_dao.py
app/models.py
config.py
tests/app/dao/test_notification_dao.py

This means we will retain notifications for a full week and not
delete records that are 7 x 24 hours older than the time of the run of
the deletion task.
Also the task only needs to run once a day now, so I have changed
the celery config for the deletion tasks.

Use short dates when selection notifications for deletion.

---

app/celery/tasks.py
app/user/rest.py
tests/app/celery/test_tasks.py
tests/app/conftest.py
tests/app/user/test_rest_verify.py

We don’t send email codes any more.
No corresponding API client method here: https://github.com/alphagov/notifications-admin/blob/master/app/notify_client/user_api_client.py
So it’s definitely not being used.

Remove send email code task

---

app/celery/tasks.py
app/notifications/rest.py
tests/app/celery/test_tasks.py
tests/app/notifications/test_rest.py

It’s nicer to have emails with a sender name, as well as the raw email address.
Amazon SES can acheive this by using the format
```
"Sender name" <sender.name@domain.com>
```
— http://docs.aws.amazon.com/ses/latest/DeveloperGuide/email-format.html
We also have to remove all non-ASCII characters from the sender name, because SMTP only supports 7-bit ASCII:
> A field name MUST be composed of printable US-ASCII characters (i.e., characters that have values between 33 and 126, inclusive), except colon.
— http://www.ietf.org/rfc/rfc5322.txt
We use the service name as the sender name when:
- sending emails from the API
- sending emails from a CSV file
We use GOV.UK Notify as the sender name when:
- sending invitation emails
- sending password reset emails

Send emails with a friendly from name

---

app/errors.py
tests/app/service/test_rest.py

There is a uniqueness constraint on service `name` and `email_from`.
When you try to insert a row which has _both_ constraints, there is no guarantee which one the operation will fail on.
This means that, when handling the exception, service `name` is not reliably available, because sometimes the operation fails on the `email_from` constraint instead.
This caused the tests to fail non-deterministically because they were looking for the service `name` in the error message. As a fix, this commit does two things:
1. Return either the service `name` or `email_from` in the error message, depending which is available.
2. Modify the test to pass on _either_ of the two possible error messages.
This is not ideal, but I can’t think of a way to maintain the original behaviour, and have reliably …

Fix test for duplicate service name

---

app/dao/notifications_dao.py
app/notifications_statistics/rest.py
tests/app/dao/test_notification_dao.py
tests/app/template_statistics/test_rest.py

We were using two different queries to filter template stats to the past 7 days, plus today.
Since we’re storing both as short dates, we can now use the same query for both.
0      | 1       | 2         | 3        | 4      | 5        | 6      | 7
-------|---------|-----------|----------|--------|----------|--------|-------
Monday | Tuesday | Wednesday | Thursday | Friday | Saturday | Sunday | Monday
So if we are on Monday, the stats should include today, plus everything back to last Monday.
Previously the template stats query was only going back to the Tuesday.
This should mean the numbers on the dashboard always line up.

Align date range for template + notification stats

---

app/dao/notifications_dao.py
app/notifications/rest.py
app/schemas.py
config.py
tests/app/dao/test_notification_dao.py

This pr is needed for https://github.com/alphagov/notifications-admin/pull/519
Also added config for deletion task so that it will run at midnight, 1am and 2am to cover utc and utc+1 servers, also clock skew and possibility of servers time zones not being changed in sync. In longer term it might be worth running this job more frequently with a limit on delete in case of lots of records to delete.

Added limit_days filter to get notifications dao.

---

app/authentication/auth.py
app/celery/tasks.py
tests/app/authentication/test_authentication.py

If the service does not have any api keys, there would be an error but it was not formed well.

This pull request fixes a bug in authentication.

---

app/celery/tasks.py
requirements.txt
test_csv_files/email.csv
test_csv_files/multiple_email.csv
test_csv_files/multiple_sms.csv
test_csv_files/sms.csv

Implements and depends on: https://github.com/alphagov/notifications-utils/pull/27
Should be merged and deployed before the same change in the admin app.
Object passed to Celery tasks must be JSON serialisable, hence the `dict` comprehension to convert from a `Columns` object.

Process CSV files with column headers of any case

---

app/dao/templates_dao.py
app/schemas.py
app/template/rest.py
tests/app/dao/test_templates_dao.py
tests/app/template/test_rest.py
tests/app/template/test_rest_history.py

The private api will support retrieving a template history endpoint and for the existing GET template endpoints will now return a list of versions for each template.

Template history endpoint added. All tests passing.

---

app/__init__.py
requirements.txt

Records the start time as a monotic on the global, to be read and used as part of request logging

Log start of request so requests can be timed

---

app/clients/email/aws_ses.py
app/dao/notifications_dao.py
app/notifications/rest.py
tests/app/clients/test_aws_ses.py
tests/app/dao/test_notification_dao.py
tests/app/notifications/test_rest.py

Update ses callback to interpret hard and soft bounces.  
If the notification has a status == sending then update the status otherwise do not update the status.
In other words do not change the status more than once.

Email failures

---

appspec.yml
scripts/common_functions.sh
scripts/deregister_from_elb.sh
scripts/register_with_elb.sh

Adding nodowntime scripts as used in the admin app
Adapted to look up instance name from instance Tags
Allows app to choose correct ELB to de/register with
Delivery apps exit with code 0 earlier in the process

Adding nodowntime scripts

---

app/dao/notifications_dao.py
app/notifications/rest.py
app/schemas.py
tests/app/notifications/rest/test_notification_statistics.py

put the tests inside a new `rest` subfolder as I didn't really want to add them into the 1.8k LOC `test_rest.py`.

notification_statistics endpoint

---

app/dao/notifications_dao.py
app/notifications/process_client_response.py
tests/app/dao/test_notification_dao.py
tests/app/notifications/test_rest.py

If the sms client provider sends more than one delivery receipt only take the update for the the first one.
Only update the notification.status if status = sending.
https://www.pivotaltracker.com/story/show/119377985

Only update status when status is sending.

---

migrations/versions/0021_add_delivered_failed_counts.py

This script has been applied to all environments except live, this can be pushed through to live without issue because of how alembic works.

Remove the status from the group by clause of the update statement.

---

app/dao/notifications_dao.py
app/notifications/process_client_response.py
app/notifications/rest.py
tests/app/dao/test_notification_dao.py

First pass at trying to address deadlocks
- ensure updates are the same order on the seperate transactions. 
- previously job was first on create and last on update, causing transactions to block
- unable to fully test locally so pull request for testing on preview.

Reorder updates to the notification / stats tables to match create.

---

app/dao/services_dao.py
config.py
migrations/versions/0025_notify_service_data.py

Add a service that will be used to send Notify's messages.
Including sms code, email verification, invitation emails, and password reset emails
Added the service id and template ids to config.
Small change to dao_create_service to use id if set.
First PR for https://www.pivotaltracker.com/story/show/120282429

Add a service for Notify to use to send messages

---

app/dao/templates_dao.py
tests/app/dao/test_templates_dao.py
tests/app/template/test_rest.py

When you add a new template, it’s probably the one that you want to do subsequent stuff with. But it’s also helpful to see the template in context (with its siblings) to understand that there are multiple
templates. So we don’t want to do what we do in https://github.com/alphagov/notifications-admin/pull/648
for adding a new template.
But we _can_ make your brand-new template appear first by always ordering by when the template was created.
This also removes the confusion caused by having `updated_at` affecting order, and causing the templates to move around all the time.

Order templates by newest created first

---

requirements.txt

This commit doesn’t introduce any new functionality, just keeps things from getting too far behind.
This is a breaking change in utils, see:
https://github.com/alphagov/notifications-utils/commit/4683922d30704e932e7a49d5c3ab058814ee5356
None of these methods are used by the API, so no API code needs to change, cf:
https://github.com/alphagov/notifications-api/search?utf8=%E2%9C%93&q=rows_with_errors&type=Code
https://github.com/alphagov/notifications-api/search?utf8=%E2%9C%93&q=has_errors&type=Code
https://github.com/alphagov/notifications-api/search?utf8=%E2%9C%93&q=annotated_rows&type=Code
https://github.com/alphagov/notifications-api/search?utf8=%E2%9C%93&q=annotated_rows_with_errors&type=Code

Bump utils to latest version

---

app/dao/notifications_dao.py
app/template_statistics/rest.py
tests/app/template_statistics/test_rest.py

`/service/<service_id>/template-statistics/<template_id>`
still requires service-id just to try and keep api tree cleaner

add template_statistics endpoint for specific template

---

app/dao/permissions_dao.py
app/service/rest.py
app/user/rest.py
tests/app/dao/test_services_dao.py

This is marked as WIP for the bug as I still need to do a migration script for existing broken accounts.
When adding a user new with permissions to a service, the permissions
dao was deleting all permissions for that user (regardless of service
id) as the last filter on the permissions dao get_query method won.
I've added a replace flag to the set_user_service_permission method
so that it can handle adding new users + permissions and editing
of existing users' permissions.
Also by pass the get_query method until it can be refactored to work
correctly.
For now execute the filter query directly on the model.

[WIP] Permissions being removed

---

app/dao/notifications_dao.py
tests/app/template_statistics/test_rest.py

they were previously returning unordered, which broke the build (once and arbitrarily)
i tried to use freezegun to make the updated_at times predictable but didn't have any luck with that, but separate commits should be enough

fix template api tests being inconsistent by adding ordering

---

app/celery/research_mode_tasks.py
tests/app/celery/test_research_mode_tasks.py

requests converts dicts into query parameters anyway if you don't specify so dont try and encode the data ourselves, also hardened up tests

fix firetext research mode requests

---

app/celery/tasks.py
tests/app/celery/test_tasks.py

We use a notify service to send the sms code via using a template.
https://www.pivotaltracker.com/story/show/120282429

Remove task send_sms_code.

---

app/errors.py
app/template_statistics/rest.py

Rest methods that explicitly return errors by pass the error handlers as they do not raise exceptions.
Introduced a simple exception that contains error messages and status
code that can be used rather than return json + status code from rest
methods directly.
The handler in errors for this exception can then log the error before
returning json.

Better error logging

---

tests/app/dao/test_notification_dao.py
tests/app/notifications/test_rest.py

It’s going to be useful to see all the notifications for a job that are failed/delivered/etc.
The API seems to support this behaviour already, but it doesn’t seem to be tested.
This commit adds some tests for the DAO and REST layers.

Test for filtering a job by notification status

---

app/celery/tasks.py

Next deploy will remove the extra task.

Rename the task so that it is the name we want to use.

---

app/accept_invite/rest.py
app/errors.py
app/events/rest.py
app/invite/rest.py
app/job/rest.py
app/notifications/rest.py
app/notifications_statistics/rest.py
app/permission/rest.py
app/provider_details/rest.py
app/schemas.py
app/service/rest.py
app/template/rest.py
app/template_statistics/rest.py
app/user/rest.py
tests/app/dao/test_templates_dao.py
tests/app/user/test_rest.py

Change endpoint responses where there are marshalling, unmarshalling or param 
errors to raise invalid request or marshmallow validation exceptions. 
That will cause those responses to be handled in by errors.py, which will log the errors.
Set most of schemas to strict mode so that marshmallow will raise exception rather than checking for errors in return tuple from load.
Added handler to errors.py for marshmallow validation errors.

Make errors return via error handlers in errors.py

---

app/notifications/rest.py
tests/app/notifications/rest/test_send_notification.py

example return value:
```
{'data': {'body': "dear leo\n\nit's currently sunny.\n\nbye!",
'notification': {'id': '71e377b6-a1fb-495b-ba51-6af4bd7bf7cb'},
'subject': 'my subject',
'template_version': 1}}
```
subject only sends for emails

add template body, version, and subject to send_notification api

---

app/invite/rest.py
app/user/rest.py
tests/app/conftest.py
tests/app/invite/test_invite_rest.py
tests/app/user/test_rest.py
tests/app/user/test_rest_verify.py

This PR uses the GOV.UK Notify service to send the email for password reset and invitation emails.
The templates are managed by the template and the endpoints send the send_email task the personalisation for the templates.

Use notify to send forgot password and invitation emails

---

app/template/rest.py
tests/app/template/test_rest.py

There’s a need for users of the API to be able to take advantage of Notify’s template rendering.
For example, there’s a service that’s building a case management system. Their users are sending emails on a case-by-case basis. Before they send an email, it’s reassuring to double check that the right data is being inserted, that the right template is being used, etc.
This commit:
- adds a separate endpoint for previewing a template, with personalisation taken from the get parameters of the request
- beefs up the tests around getting a template
Not part of this pull request:
- making this endpoint publicly accessible

Add a ‘preview template’ endpoint

---

app/authentication/auth.py
tests/app/authentication/test_authentication.py

We are trying to get all the error messages to return in the following format:
{result: error,
message: ['what caused error': 'reason for error']
}

Update auth module to return consistently formed error messages.

---

app/dao/api_key_dao.py
app/service/rest.py
tests/app/authentication/test_authentication.py
tests/app/dao/test_api_key_dao.py
tests/app/service/test_api_key_endpoints.py

The only update we should be doing to an api key is to expire/revoke the api key.
Removed the update_dict from the the save method.
Added an expire_api_key method that only updates the api key with an expiry date.

Refactor the api_key_dao.

---

tests/app/dao/test_notification_dao.py
tests/conftest.py

We were dropping all tables at the end of the test run, however the alembic_version table is not part of the metadata so was being persisted. Alembic then doesn't upgrade the database next test run, since the version appears up to date, so we were, in the notify_db_session fixture, recreating from MetaData (sqlalchemy models). This involves quite a costly comparison of the postgres system tables and the tables in models.py, which was adding half a second to each test that uses the notify_db_session fixture (virtually all of them).

Remove db.drop_all from notify_db session fixture to speed up tests

---

app/notifications/rest.py
app/schemas.py
tests/app/notifications/rest/test_send_notification.py
tests/app/notifications/test_rest.py

In the two new tickets to add the final compiled message body to the `POST /notifications/_ _ _ _`  and  `GET /notifications[/ _ _ _ _]` responses, we neglected to convert email subjects with placeholders in them
Tests and code for that.

Replaced subjects

---

app/celery/provider_tasks.py
app/celery/tasks.py
app/dao/notifications_dao.py
app/models.py
tests/app/celery/test_provider_tasks.py
tests/app/celery/test_tasks.py
tests/app/dao/test_notification_dao.py
tests/app/notifications/test_rest.py

- The send_sms task will created the notification with a status = created.  
- The encrypted_notification for the send_sms_to_provider task has been made optional.
- The encrypted_notificaiton is still passed through to the send_sms_to_provider task so that the code is backward compatible during deployments.

Notification created status for send_sms

---

app/schemas.py
tests/app/service/test_api_key_endpoints.py

depends on https://github.com/alphagov/notifications-admin/pull/730
remove the default key_type - given that we only have one route for creating API keys, which will imminently let the user choose key_type, it makes no sense to provide this default, it's just extra unwelcome logic that we have to remember/support

remove default key_type

---

app/celery/provider_tasks.py
app/celery/tasks.py
app/models.py
app/notifications/rest.py
app/template/rest.py
app/user/rest.py

A small refactor to use the SMS_TYPE and EMAIL_TYPE in code rather than 'sms' or 'email'

Use type from model

---

app/__init__.py
app/authentication/auth.py
app/authentication/utils.py
app/dao/api_key_dao.py
app/errors.py
app/job/rest.py
app/models.py
app/notifications/rest.py
app/service/rest.py
app/utils.py
tests/app/authentication/test_authentication.py
tests/app/authentication/test_utils.py
tests/app/dao/test_api_key_dao.py
tests/app/job/test_rest.py
tests/app/notifications/test_rest.py
tests/app/service/test_rest.py

used in notifications/rest.py to get the current API's service id, it previously contained a dict of `{'client': service_id, 'secrets': [ all api_key secrets of that service ]}`. now contains full db object.
the api_key needs to be stored after the requires_auth decorator, for distinguishing between api_key types.
To aid me I attempted a cleanup of auth.py
it's not required - nginx performs all of its functionality
the functions that used it moved from notifications to job/rest.py and service/rest.py with no changes
so that it can be accessed cleanly from a new `unsigned_secret` property on the `ApiKey` model.
ensure consistency and accuracy of error messages - sometimes previously would report wrong error message if there were multiple invalid keys in the database
* **new**: if the token …

Api user cleanup

---

requirements.txt

Add breathing room around GOV.UK logo in emails

---

app/__init__.py
app/celery/provider_tasks.py
app/celery/tasks.py
tests/app/celery/test_provider_tasks.py
tests/app/celery/test_tasks.py

Split send_email task into one task to create the notification and one to send it to the provider.
If there is an exception the task will go to the retry queue.
https://www.pivotaltracker.com/story/show/123845161

Split send email task

---

app/celery/provider_tasks.py
app/celery/tasks.py
app/clients/email/aws_ses.py
tests/app/celery/test_provider_tasks.py
tests/app/celery/test_tasks.py

dont send reply_to_addresses around from process_job and send_email - take it from the service in send_email_to_provider. also clean up the kwarg in aws_ses.send_email to more accurately reflect what we might pass in
this is the first of two PRs - next PR will remove kwargs from celery tasks

dont pass reply-to-addresses about

---

.travis.yml

* our travis builds spend several minutes building python dependencies.
* pip rebuilds dependencies, even if the version hasn't changed.
* many of our dependencies are c-compiled, and take a long time to build.
* [pip-accel](https://github.com/paylogic/pip-accel) is a library that locally caches built python libraries
* we can use travis' built-in caching system to cache that pip-accel directory, and hopefully as a result can reduce build times (after the initial build)
from ~100s down to ~25 seconds on this branch

add pip-accel to travis to speed up builds

---

app/notifications/rest.py
tests/app/notifications/rest/test_send_notification.py

Daily message limits are imposed for csv jobs, but not api calls. This pr brings these into line by respecting limits in api calls. It may be decided later that no limit is the way to go, and if so, this can be reverted and a check for service being restricted can be added to tasks.py -> process_job.
Another pr will be coming on admin side to increase the daily limit that is set when service is un restricted.
Fix for https://www.pivotaltracker.com/story/show/126230157

Daily message limit imposed for service api calls.

---

requirements.txt

Implements and depends on:
Should be deployed ahead of the admin side of these features, which
is in: https://github.com/alphagov/notifications-admin/pull/781

Add conditional placeholders and formatting of email messages

---

requirements.txt

Bleach 1.4.2 installs html5lib version 0.999 or greater.
This was fine, until version 0.999999999 (nine nines) was released, which doesn’t work.
Bleach 1.4.3 pins html5lib to 0.9999999 (seven nines), which stops the bad version getting installed.

Upgrade bleach to fix dodgy html5lib version

---

app/dao/services_dao.py
app/schemas.py

Speed up GET services:
Joined loads are almost always better than lazily loading - we know we need users, so load them when we grab the service, rather than when we dump the schema.
No loads are better than both, so exclude stats tables.

Speed up GET services endpoints

---

app/notifications/rest.py
tests/app/notifications/rest/test_send_notification.py

We limit SMS to be a maximum of 495 characters at the point of an API call being made.
We were also applying this limit to emails, which is wrong.

Only put a character limit on SMS notifications

---

app/celery/provider_tasks.py
tests/app/celery/test_provider_tasks.py

Statsd timings were being passed a timedelta instead for float for milliseconds.
Bugfix for https://www.pivotaltracker.com/story/show/126852733

Statds value error

---

app/template/rest.py
requirements.txt

Markdown parsing (will be active but isn’t documented):
Email sub branding (not used yet):

Update utils for Markdown parsing + subbranding

---

app/dao/services_dao.py
app/schemas.py
app/service/rest.py
tests/app/conftest.py
tests/app/dao/test_services_dao.py
tests/app/service/test_rest.py
tests/conftest.py

new detailed service api endpoint that returns the service information, plus an additional statistics dictionary for use on the frontend.
~~depends on #538~~ 
blocks:
https://github.com/alphagov/notifications-admin/issues/802
https://github.com/alphagov/notifications-admin/issues/803

detailed service api endpoint

---

environment_test.sh

If TEST_DATABASE is set then the postgres connection is set to that.
Jenkins sets it to the RDS instance that is in that AWS Account

Override postgresc connection for jenkins

---

tests/app/notifications/test_rest.py
tests/app/provider_details/test_rest.py

Just a couple of tests that were returning inconsistent data, and sometimes screwing up my test runs.
* tests on API endpoints that we do not explicitly sort should either sort the results or use a data set where we do not rely on json list order being consistent
* tests that touch the provider_details should reset values after running, since the provider_details table is not torn down and re-created between tests (unlike most tables)

make tests run consistently

---

app/job/rest.py
app/notifications/rest.py
app/schemas.py
app/service/rest.py
app/spec/rest.py
tests/app/job/test_rest.py
tests/app/notifications/test_rest.py

problem is due to a bug (still outstanding see pivotal #127079637) in our marshmallow notification schema when it tries to recreate the message content from personalisation if the template has been edited.
Fixed by using different schema that skips that in all places except for the public /notification endpoint.
Added an expected-fail test to test that

fix notification 500

---

app/dao/services_dao.py
app/service/rest.py
migrations/versions/0043_notification_indexes.py
tests/app/conftest.py
tests/app/dao/test_services_dao.py
tests/app/service/test_rest.py

This endpoint is needed by the send page, which checks to see how many messages you've sent today compared to your daily limit
blocks https://github.com/alphagov/notifications-admin/pull/809
~~blocked by #557~~

Get service with stats for today

---

app/dao/services_dao.py
app/service/rest.py
app/service/statistics.py
tests/app/conftest.py
tests/app/dao/test_services_dao.py
tests/app/service/test_rest.py
tests/app/service/test_statistics.py

New function to replace `GET /service/<id>/notifications-statistics/seven_day_aggregate` - summarises status counts on a per-week basis from the `notifications_history` table - I'm not 100% sure how the old one actually worked but this one works fine - i moved as much date manipulation and aggregation back into python to try and make it more legible but let me know if it's off
apologies for lots of +- changes but they're mostly new test cases and moving a couple of fns to a different file
~~blocked by #559~~

New weekly aggregate function

---

tests/app/dao/test_services_dao.py
tests/app/service/test_rest.py

also fixed a gotcha where an object was created in a fixture, so the freezetime decorator didn't apply

use freeze_time whenever we mess with dates

---

app/notifications/rest.py
tests/app/notifications/rest/test_send_notification.py

Scenario we saw in research:
- trying to send a message to someone outside your team
- service is in trial mode
Result:
- error message was terrible, no-one understood it
Solution:
- better error message
Although using a team key is functionally the same as your service being restricted, conflating the two errors is not helpful. What we typically saw in research was that someone was using a team key, got the error, used a live key and got the _same_ error.
This commit adds a new error message that specifically mentions the type of API key that you’re using.

Give better error messages when using the API to send to recipients not in your team

---

app/celery/provider_tasks.py
app/celery/tasks.py

**Extend the retry time on the create notification DB tasks**
- Was previoulsy 5 attempts 5 seconds apart
- No 5 times 5 minutes apart.
- Gives 25 mins of retries before an error
**In event of a task retry ensure the log message is identifier as such**
- "RETRY" prefixes the messages
In event of the retry attempts completing without successfully completing the task identify message as such
- "RETRY FAILED" prefixes the messages
Applies to the send_sms|send_email and send_sms_to_provider|send_email_to_provider tasks
These are there to try and ensure we can alert on these events so that we know if we have started retrying messages
Retry messages also contain notification ids to aid debugging.

Improve logging and extend time periods associated with retrying

---

aws_run_celery.py

- means that logs are branded as application:api not delivery.

Missing the name on the aws start celery command

---

app/dao/dao_utils.py
app/dao/notifications_dao.py
app/dao/services_dao.py
app/dao/templates_dao.py
app/history_meta.py
app/models.py
app/notifications/rest.py
app/schemas.py
app/service/rest.py
tests/app/celery/test_provider_tasks.py
tests/app/dao/test_notification_dao.py
tests/app/dao/test_services_dao.py
tests/app/dao/test_templates_dao.py
tests/app/notifications/test_rest.py

kinda two separate parts to this:
version table is a total pain and doesn't actually give us that much for free - but does block us from constructing sqlalchemy relationships or joining to it in an ORM manner, so remove it. Turns out this is very simple - had to do some small work to the version decorator (used on ORM create/update methods) to support this but that's all)
It's not complete in this ticket, but this is the smallest section of work that fixes the 500 errors.
We shouldn't be referring to templates in the notification table - notifications are tied to a template's version at the moment in time that they're created, and if the template changes we shouldn't change that reference.
So for now solve this in a stop-gap method - add a new relationship called `template_history` and …

fix GET /notifications 500 error

---

app/dao/notifications_dao.py
app/template_statistics/rest.py
tests/app/dao/test_notification_dao.py
tests/app/template_statistics/test_rest.py

DO NOT MERGE IS A BREAKING CHANGE ON ADMIN
New query to enable the template stats to be driven from notifications history.
New query in DAO and rest endpoint rewired.
Note. Does not use marshmallow, so response is serialized by hand in the rest endpoint. Response format has changed.
Previous:
{
'template': {
'name': 'Brine Shrimp',
'template_type': 'sms',
'id': 1
},
'id': '6005e192-4738-4962-beec-ebd982d0b03f',
'day': '2016-04-06',
'usage_count': 6,
'service': '1491b86f-c950-48f5-bed1-2a55df027ecb'
},
Current:
{
'template_type': 'sms',
'template_name': 'one',
'template_id': 'id-1',
'count': 100,
'day': '2016-01-01'
},
I removed the notion of nested objects and simplified the structure. There were 3 IDs previously in the JSON. Now only template ID.
This breaks the admin and the admin pull …

Template queryies

---

app/dao/notifications_dao.py
app/template_statistics/rest.py
tests/app/dao/test_notification_dao.py
tests/app/template_statistics/test_rest.py

Requires https://github.com/alphagov/notifications-api/pull/610
Is a breaking ADMIN change.
Changes last template usage query to be based on history table and gets last row for that template to allow us to work out what the last use for that template was.

Template useage per

---

app/dao/jobs_dao.py
app/job/rest.py
app/schemas.py
tests/app/dao/test_jobs_dao.py
tests/app/job/test_rest.py

BREAKING CHANGE FOR THE ADMIN APP
- Refactors the JOBS api to use the notifications history table to build up the statuses for the notifications.
- Groups by status
- returns a new block on the API response
{
'statistics' [{
'status': 'created, 'count': 1,
...
}]
}

Returns the outcome statistics for the job on the API call.

---

app/__init__.py
app/dao/services_dao.py
app/service/rest.py
app/service/statistics.py
requirements_for_test.txt
tests/app/notifications/test_rest.py
tests/app/service/test_rest.py
tests/app/service/test_statistics.py

(also removed a whole bunch of unused code for getting some stats we already removed previously)
The new function's `dao_fetch_todays_stats_for_all_services`, and it's called by hitting `GET /services?detailed=True`, which returns a list of dicts that looks something like:
```
{
'id': '1234...',
'name': 'My Service',
'created_by': '...',
...
'statistics': {
'sms': {'created': 0, 'delivered': 0, 'failed': 0},
'email': {'created': 1, 'delivered': 1, 'failed': 0}
}
}
```
I reused code from existing dashboard queries to get the stats into that format.
blocks https://github.com/alphagov/notifications-admin/issues/907

Platform admin notification query

---

app/celery/provider_tasks.py
requirements.txt
tests/app/celery/test_provider_tasks.py

Don’t prefix text messages if sender name is set

---

app/celery/tasks.py
tests/app/celery/test_tasks.py

Use the same queues for CSV notifications as for API ones. Looking to push notifications at their own workers, leaving workers for normal "admin" style stuff behind.

Pushed the notifications from the CSV in the DB queue

---

app/notifications/rest.py
tests/app/notifications/rest/test_send_notification.py

https://www.pivotaltracker.com/story/show/128136359
When you use a test API key it should behave like a live service, except for actually sending the messages. There should be no limits even if the service is in trial mode.
This pull request removes these restrictions when you use a test key:
- sending messages to people outside your team when you’re in trial mode.
- sending messages when you’ve sent up to your daily limit.

Remove restrictions when using simulate API key

---

tests/app/notifications/rest/test_send_notification.py

Sending emails was moved to a different queue in https://github.com/alphagov/notifications-api/pull/647
At the time that https://github.com/alphagov/notifications-api/pull/645 was written, the previous queues were still being used. So when #645 got merged it was testing for the old queues, which broke the tests.

Fix test to expect correct db queue

---

config.py
scripts/aws_start_app.sh
scripts/aws_stop_app.sh

Rejigged the queue config.
- the two new queues that handle delivery of notifications (db-[type] / send-[type]) Now no longer are processed by the default workers
- These workers now to the admin type queues for notify (CSV/Validation codes) etc.
- Two new workers are deployed to the AWS environments, one focused on db- tasks and one for send tasks
- These will pick up those queues explicitly.

Queues for production

---

app/job/rest.py
tests/app/job/test_rest.py

FAO @quis 
Should fix issue we saw on preview.
Adds statistics block onto the job when a create-job is called

Return empty stats list for job creation

---

.gitignore
scripts/run_tests.sh

so we can get test stats (including time taken, which i'm most interested in) on jenkins. creates test_results.xml in your project root.

add junit xml reporting to pytest

---

app/dao/jobs_dao.py
app/job/rest.py
app/models.py
migrations/versions/0051_cancelled_job_status.py
tests/app/conftest.py
tests/app/dao/test_jobs_dao.py
tests/app/job/test_rest.py

If you schedule a job you might change your mind or circumstances might change. So you need to be able to cancel it. This commit adds a `DELETE` endpoint for individual jobs which sets their status to `cancelled`.
I don’t really know what I’m doing here so someone should probably take a close look at it.

Add an endpoint to cancel a job

---

migrations/versions/0053_cancelled_job_status.py

The cancelled job migration originally went in as version `0051`.
But `0051_set_job_status` went in first in e3fa8bffd7dd436a9d3da68058528d3ad1cd2c09
This meant that Alembic couldn’t work out what order to run the migrations in, and blew up.
This commit puts the scheduled job migration after all others.

Fix mis-matched database migrations

---

requirements.txt

Just so that nobody else has to do it.
Implements:
Which is a breaking change, but the breaking bits don’t seem to affect this app.

Update Python client

---

app/accept_invite/rest.py
tests/app/accept_invite/test_accept_invite_rest.py

- If the token for invitation was expired, the method would throw a 500 while creating the erorr message.
- Added unit tests.

Fix a bug in the accept invitation that was throwing a 500.

---

app/celery/scheduled_tasks.py
app/dao/notifications_dao.py
tests/app/dao/test_notification_dao.py

We found that if the notifications were in created or pending they are not purged from notifications.
- New bulk update method to set all notificaitons with:
-  a status = created|sending|pending to temporary-failure
- and is older then today minus SENDING_NOTIFICATIONS_TIMEOUT_PERIOD (in seconds)
- the scheduled task to timeout notifications use the new bulk update query.
- the task will be more efficient

Update the timeout_notifications scheduled tasks.

---

app/notifications/rest.py
config.py
tests/app/notifications/rest/test_send_notification.py

This provides capability to stop emails/sms messages being sent to a specific set of simulated addresses. This provides a means to test these addresses on live without billing. Once a call is made to send an email or sms with the API a simulated response (message body, template id etc.) is returned.

Add capability for simulated numbers and email addresses

---

app/authentication/auth.py
tests/app/authentication/test_authentication.py

If you sign a token with a service ID that doesn’t exist (say, for example, that you get service ID and API key mixed up) then you get an error saying that “no API keys exist for the service”. This is wrong because the service doesn’t even exist.
This commit adds:
- code to check if the service does exist
- a specific error message for this case
The check does mean an extra database call to look up the service. However this only happens _after_ looping through all the API keys. So it shouldn’t have a performance implication for anyone using a valid API key.

Improve error messages if you make an API call with a bad token

---

app/dao/notifications_dao.py
app/notifications/rest.py
app/schemas.py
app/service/rest.py
tests/app/conftest.py
tests/app/dao/test_notification_dao.py
tests/app/notifications/test_rest.py
tests/app/service/test_rest.py
tests/app/test_schemas.py

Ensure that we do not return JOB created notifications in the API calls.
Unless:
It is a LIVE key and the include_jobs param is set to TRUE
Other key types CANNOT retrieve JOB created notifications from the API.
Note:
API calls made by the Admin app ALWAYS return ALL notifications (JOB|API) - this may need to change to create flexibility the in the dashboards, but this is like for like functionality for now.

No jobs on api get

---

app/dao/notifications_dao.py
app/dao/services_dao.py
app/notifications/rest.py
app/schemas.py
app/service/rest.py
tests/app/conftest.py
tests/app/dao/test_notification_dao.py
tests/app/dao/test_services_dao.py
tests/app/notifications/test_rest.py
tests/app/service/test_rest.py
tests/app/test_schemas.py

Depends on
https://github.com/alphagov/notifications-api/pull/677
Ensure we don't return TEST key data on the various calls to the dashboard.
Note this probably requires us to look again at the DAO classes and think of a better interface as logic is getting spread about too much.

Remove test keys from admin app

---

tests/app/notifications/rest/test_callbacks.py
tests/app/public_contracts/schemas/GET_notifications_return.json

The current schema disallows the links' object within the returned response to have any properties despite being contained in the response (as expected). This removes the aforementioned constraint and implements a check to ensure the link's object contains the expected properties.

Update schema to validate contents of GET notifications

---

Makefile
appspec-db-migration.yml
deploy-exclude.lst
scripts/aws_change_ownership.sh
scripts/aws_install_dependencies.sh
scripts/aws_run_db_migrations.sh
scripts/aws_start_app.sh
scripts/aws_stop_app.sh

In every environment there will be a t2.nano instance with a separate CodeDeploy configuration to run just the database migrations. This way we only run the migrations once. After the migrations are ready, we run the functional tests first, then deploying the app everywhere and finally and other round of functional tests.
Changes:
* separate appspec-db-migration.yml file to run only the database migrations
* separate zip file is built for the db migrations (only the appspec.yml is different)
* cleaning up the aws scripts

Deploy db migrations

---

app/service/rest.py
tests/app/service/test_rest.py

This commit adds the `include_jobs` filter to the `GET /services/…/notifications` endpoint. It defaults to `True` (i.e. show all notifications) but makes it possible to only return notifications
created by _any_ API key.
This is so that we can show a log of all notifications sent through the API in the admin app.
It does not expose this parameter to the public `GET /notifications` endpoint because this would violate our rules about keys only being able to get notifications created with keys of the same type.

Optionally get only notifications created by API

---

app/dao/jobs_dao.py
app/job/rest.py
app/utils.py
tests/app/conftest.py
tests/app/dao/test_jobs_dao.py
tests/app/job/test_rest.py
tests/conftest.py

it'll now only return 50 results by default, and is paginated with all the neat jazz that comes with

Paginate `GET /service/{}/job` query

---

app/dao/notifications_dao.py
app/schemas.py
app/service/rest.py
tests/app/dao/test_notification_dao.py
tests/app/service/test_rest.py

_Reviewers: There are quite a lot of whitespace changes in this PR. The meat of the changes are in f9f3bb8 and d7bb83f._
***
Developers need visibility of what their integration is doing within the app. This includes notifications sent with a test key.
This PR adds an optional, defaults-to-false parameter to include notifications sent from a test API key when getting notifications.
This is only for the method that the admin app uses; it doesn’t affect the public get notifications endpoint.

Optionally get notifications created with a test key

---

app/schemas.py
tests/app/conftest.py
tests/app/test_schemas.py

We want to show developers a log of notifications they’ve sent using the API in the admin app. In order to identify a notification it’s probably helpful to know:
- who the notification was sent to (which we expose)
- when the notification was created (which we expose)
- which key was used to create the notification (which we expose, but only as the `id` of the key)
Developers don’t see the `id` of the API key in the app anywhere, so this isn’t useful information. Much more useful is the `type` and `name` of the key. So this commit changes the schema to also return these.
This commit does some slightly hacky stuff with conftest because it breaks a lot of other tests if the sample notification has a real API key or an API key with a non-unique name.

Add details of API key to notifications

---

app/notifications/rest.py
tests/app/notifications/rest/test_send_notification.py

Fixing a bug that allows a sms notification to be sent with an email template and vice versa.
This has been resolved for the post notifications endpoint

Fix template type bug

---

app/dao/jobs_dao.py
app/job/rest.py
app/models.py
tests/app/job/test_rest.py

> can now pass in a query string `?statuses=x,y,z` to filter jobs based on `Job.job_status`. Not passing in a status or passing in an empty string is equivalent to selecting every filter type at once.
This is required cos now that jobs are paginated, the front end has to make two separate calls to get jobs - one for scheduled, and one for everything else

add statuses filter to GET /service/{}/job

---

app/celery/tasks.py
app/notifications/rest.py
tests/app/celery/test_provider_tasks.py
tests/app/celery/test_tasks.py
tests/app/notifications/rest/test_send_notification.py
tests/app/public_contracts/test_POST_notification.py

When notifications are being created, currently they go onto the normal db-sms/db-email and send-sms/send-email queues.
This is true for both research-mode and non-research mode services and for ALL key types.
This has the side effect of affecting delivery performance of the application as these 'test' messages endup being processed by workers that are also processing the genuine notifications.
This PR does 3 things:
- CSV file processing now creates the send-email/send-sms tasks in the research mode queue if the service is in research mode.
- send-email/send-sms tasks now create the deliver-sms/deliver-email tasks in the research-mode queue for research mode services
- API calls that are for research-mode services OR use test keys create the deliver-sms/deliver-email tasks in the …

Research mode queue should be used for research-mode services

---

app/celery/tasks.py
app/notifications/rest.py
tests/app/celery/test_tasks.py
tests/app/notifications/rest/test_send_notification.py

- passing a single param to a celery task must be done as a list not a tuple.

Fixed build

---

app/dao/notifications_dao.py
app/service/rest.py
tests/app/dao/test_notification_dao.py
tests/app/service/test_rest.py

In order to invoice people we need to know how many text message fragments they’ve sent per month.
This should be per (government) financial year, ie April 1<sup>st</sup> to April 1<sup>st</sup> because we’ll only ever show a page for one year (because the 250,000 allowance is topped up at the start of every financial year).
**Exposed at**
`/services/ef7a665d-11a4-425a-a180-a67ca00b69d7/billable-units?year=2016`
**Returns**
```python
{
'April': 3,
'July': 1,
'August': 1,
'January': 1
}
```

Add DAO and endpoint for getting billable units/financial year

---

app/celery/tasks.py
tests/app/celery/test_tasks.py

- It seems that when we changed the name of the job.status column that we didn't update the code to use job.job_status.
- Therefore none of the jobs since then have had the job status updated.
- Now that this is fix we can show the job status when there is an error like "sending exceeds limits"
- This could happen if a job is scheduled to run at the top of the hour, so at the time of the job creation the limit was not exceed, but at the time of processing the job the limit is exceed.

Fix for the job status

---

app/celery/scheduled_tasks.py
app/celery/tasks.py
app/dao/jobs_dao.py
lambda_function/README.md
tests/app/celery/test_tasks.py
tests/app/dao/test_jobs_dao.py

we weren't locking the job table, so if the task runs twice (it in fact runs three times) there is a chance it will pick up the same job to process multiple times. The odds increase as more jobs are scheduled, so this got through to live before we noticed. Bad us.
This PR:
* makes the run_scheduled_jobs lock the job table (only against updates, deletes, and other run_scheduled_jobs tasks) using `FOR UPDATE`
* makes the process_job task check if the job is pending. Note: this is _in no way_ failsafe (as it's not tied using a lock to the update that sets `job_status = 'in progress'` , however it is another line of defence.

fix run_scheduled_jobs concurrency bug

---

app/service/utils.py
tests/app/notifications/rest/test_send_notification.py

There is an overlap between team key/trial mode/whitelist. But it’s not a complete overlap. So it’s hard to understand all the different permutations of which key lets you send to which people when.
This commit tries to reduce the differences between these concepts. So for a user of the API
**In trial mode**
- You can send to anyone in your team or whitelist, using the team key
- You can simulate sending to anyone, using the simulate key
**When you’re live**
- You can send to anyone in your team or whitelist, using the team key
- You can simulate sending to anyone, using the simulate key
- You can send to anyone with the live key
So doing a `diff` on that list, the only change when you go live mode is:
`+ You can send to anyone with the live key`
***
**(How trial mode used to work)**
- …

Let team key send to whitelist

---

app/dao/jobs_dao.py
tests/app/conftest.py
tests/app/dao/test_jobs_dao.py

Say you have a dashboard with some jobs you sent. Normally looks like:
job | sent
--- | ---
file.csv | _5pm_
file.csv | 3pm
file.csv | 1pm
file.csv | 11am
However if your 5pm job was scheduled at lunchtime, then it will look like this:
job | sent
--- | ---
file.csv | 3pm
file.csv | 1pm
file.csv | _5pm_
file.csv | 11am
This is because the jobs are sorted by when they were created, not when they were sent. It looks wrong.
**For jobs that have already been sent**
This commit changes the sort order to be based on `processed_at` instead.
**For upcoming jobs**
If a job doesn’t have a `processed_at` time then it’s scheduled, but hasn’t started yet. Only in this case should we still be sorting by`created_at`.

Sort jobs by processed time first

---

app/notifications/rest.py
tests/app/notifications/test_rest.py

Currently getting a single notification by ID is restricted to notifications created with the same key type.
This makes things awkward for the functional tests now we’ve removed the ability to create live keys in trial mode. So this commit removes the restriction, so that any key can get any notification, no matter how it was created.
And you’re never going to guess a UUID, so the chances of this giving you privileged access to someone’s personal information is none.
This does not change the get all notifications endpoint, which absolutely should be restricted by key type.

Loosen key restriction on get notification

---

migrations/versions/0057_change_email_template.py

Creation of a new template for the GOV.UK Notify service to send to users to confirm the change of their email address.

Confirm new email address template.

---

app/dao/jobs_dao.py
config.py
tests/app/conftest.py
tests/app/dao/test_jobs_dao.py

We previously filtered test messages on the front-end - unfortunately this doesn't play well with pagination since if you have a page that only contains jobs - eg:
so put this on the API side so its filtered before paginating.

Test message filtering

---

requirements.txt

includes improved email validation regex
had to wait a day after admin to ensure any earlier invalid emails that were still in the queue flush through the system fine

bump notification-utils to 9.0.5

---

app/schemas.py
tests/app/job/test_rest.py

If you want to send a job on Monday morning, you should be able to schedule it on Friday. You shouldn’t need to work on the weekend.
96 hours is a full 4 days, so you can schedule a job at any time on Friday for any time on Monday.
We’ve checked with the information assurance people, and they’re OK with us holding the data for this extra amount of time.

Let jobs be scheduled up to 96 hours in the future

---

app/celery/scheduled_tasks.py
app/errors.py
app/notifications/rest.py

1. Fix `logger.exception` syntax. log functions (`info`, `error`, etc) take in a msg parameter, the message to display, and any further parameters are assumed to be `%s` style format arguments - if they don't match, then the logger handles this error, however this was not being picked up by our custom handlers for JSON output (for kibana). I've made sure that everywhere where we call `logger.exception` we don't pass in `e` (`logger.exception` simply logs a regular error message, and then includes stack trace from the sys exc_info vars).
2. Clean up errors.py a little bit. Made sure there's a generic Exception handling thing so that if we throw any arbitrary exception it gets handled by our custom loggers and returns proper json, and removed some unused code paths and code duplication

Error handling

---

Makefile
scripts/aws_install_dependencies.sh

Currently AS deployment takes reasonably long due to installing dependencies from requirements.txt each time. This has been optimised so that the artifact used for deployment includes a wheelhouse (wheels for all dependencies) from which the packages can be installed instead of having to resolve PyPi for each dependency.

Use python wheels to speed up AS deployment

---

app/authentication/auth.py
tests/app/authentication/test_authentication.py

From a support ticket:
> the "Bearer" prefix on the auth header is case sensitive. Can this be made case-insensitive?
Sure can 🙃
https://www.pivotaltracker.com/story/show/133183605

Make bearer prefix on auth header case insensitive

---

app/authentication/auth.py
requirements.txt
tests/app/authentication/test_authentication.py

this is to prevent 500 errors because <2.0.0 raised AssertionError if supplied JWT tokens were incorrectly formatted
tests added

update python client to 2.0.0

---

app/celery/tasks.py
requirements.txt
tests/app/conftest.py
tests/app/invite/test_invite_rest.py
tests/app/notifications/rest/test_send_notification.py
tests/app/user/test_rest.py

From a support ticket:
> it's possible to add a personalisation token with trailing whitespace (eg. "key " rather than "key"). Can this be trimmed in the UI to guard against this? (one of our devs copied and pasted it from a document and inadvertently included the space)
> 
> Nothing major but caused a few hours of investigations!
Rather than trim the placeholder in the template, we should treat personalisation in API calls the same way we do with CSV files, ie we ignore case and spacing in the name of the placeholder. So
`(( First Name))` is equivalent to `((first_name))`, and both would be populated with a dictionary like `{'firstName': 'Chris'}`.
Depends on:

Ignore case and whitespace in personalisation keys

---

migrations/versions/0059_add_letter_template_type.py

A letter type was added to the `enum` in the `Template` model at the same it was added to the `Notification` model. But the migration was only done for the `notifications` table, not the `templates` table.
See: https://github.com/alphagov/notifications-api/commit/25db1bce#diff-516aab258e161fc65e7564dabd2c625aR19
This commit does the migration to add `letter` as a possible value for the `template_type` column, which is a bit fiddly because `enum`s.
Before:
```
notification_api=# select enum_range(null::template_type);
enum_range
-------------
{sms,email}
(1 row)
```
After upgrade:
```
notification_api=# select enum_range(null::template_type);
enum_range
--------------------
{sms,email,letter}
(1 row)
```
After downgrade
```
notification_api=# select enum_range(null::template_type); …
```

Add letter to possible template types in DB

---

migrations/versions/0060_add_letter_template_type.py

Two different versions of `0059` were merged.
`0059_set_services_to_active` was merged first, so this renames my migration to `0060`, so it goes in afterwards.

Fix conflicting migration versions

---

app/schemas.py
tests/app/conftest.py
tests/app/dao/test_templates_dao.py
tests/app/template/test_rest.py

Depends on:
So that you can create and get letter templates.
Fairly straightforward with few changes, apart from loads of whitespace-only changes in 1cda00b
Best to look at the commits in isolation because of that last one.

Add ‘letter’ as a possible template type

---

app/dao/services_dao.py
tests/app/service/test_deactivate.py

don't re-delete already archived/revoked templates/api-keys
it was making extra versions and changing expiry dates which is bad

archive service - don't re-delete templates etc

---

app/celery/tasks.py
app/models.py
app/notifications/process_notifications.py
tests/app/celery/test_tasks.py
tests/app/notifications/test_process_notification.py
tests/app/test_model.py

- Refactor send_sms and send_email to use common code to persist the notificaiton.
- Use the same method to persist a notification.
- Refactored the send_sms task to use this method.
- Fix the send_sms and send_email code to send the notification id that has been persisted.
- Fix logging in send_sms and send_email

Refactor for code reuse

---

app/notifications/process_notifications.py
app/v2/notifications/notification_schemas.py
app/v2/notifications/post_notifications.py
tests/app/v2/notifications/test_post_notifications.py

For the post_sms_response and post_email_response the reference property is always present but the value can be null.
Added a test for an empty reference.
Remove datetime format on the created_at attribute of a notification, it is not needed.

Small fixes for the V2 post notification endpoints

---

app/models.py
tests/app/test_model.py
tests/app/v2/notifications/test_get_notifications.py

When trying to call getNotificationById a 500 occurred. 
Essentially it complained at the point we we're trying jsonify the notification response (without having str'd the cost). This seems to fix the issue after testing on the NET client.

Stringify the cost before passing to jsonify as it complains otherwise

---

app/dao/notifications_dao.py
app/models.py
app/notifications/rest.py
app/schemas.py
app/v2/notifications/get_notifications.py
app/v2/notifications/notification_schemas.py
tests/app/conftest.py
tests/app/dao/test_notification_dao.py
tests/app/public_contracts/test_GET_notification.py
tests/app/test_model.py
tests/app/v2/notifications/test_get_notifications.py

This pull request: 
- adds the 'v2' route to get all notifications
- allows filtering by `status`, `template_type`, or `older_than`
- adds logic to filter by `failed`, even though that's not a real status 
- removes `.cost()` key from the returned json for a notification 
- adds a 'v2' schema for getting a list of notifications
Keeps all the marshmallow validation stuff working because it still all hangs together.  Don't fix what ain't broke or whatever.  Worth noting that there's a nasty marshmallow error returned when trying to put in the wrong status or something -- not sure if it's there in production but maybe we eventually want to handle these errors differently.  
[--> on Pivotal](https://www.pivotaltracker.com/story/show/131977833)

[#131977833] Create get all notifications endpoint for V2 API

---

app/v2/notifications/post_notifications.py
tests/app/notifications/test_validators.py
tests/app/v2/notifications/test_post_notifications.py

The body of the content in the response to a POST v2/notifications was not replacing the placeholders.
This PR fixes that and adds a test for it.
I am confused as to why I had to change the test_validators test that is checking if the mock is called.
Why did this code pass on preview?

Fix version 2 of post notification, return placeholders

---

app/dao/notifications_dao.py
app/schema_validation/__init__.py
app/v2/notifications/get_notifications.py
app/v2/notifications/notification_schemas.py
tests/app/v2/notifications/test_get_notifications.py
tests/app/v2/notifications/test_notification_schemas.py

The `get_notifications` route is now using a json schema to validate query parameters rather than the marshmallow thing.
Also changed how error messages are returned from `jsonschema` because the previous way was cutting off our failing `enum` routes.
New tests for: 
- invalid statuses
- invalid template_types
- invalid `older_than` ids
- invalid ids in the route to get a single notification

Remove marshmallow schema validation + format error messages

---

app/celery/tasks.py
app/notifications/process_notifications.py
tests/app/celery/test_tasks.py
tests/app/notifications/test_process_notification.py
tests/app/notifications/test_validators.py

Sometimes a message is picked up twice of the SQS queue, we need to safe guard ourselves for that.
In this PR the id for the notification is passed in and used to created the notification, which causes a integrity error.
Normally when we get a SQLAlchemy error here we send the message to the retry queue, but if the notification already exists
we just ignore it.

Protect send_sms send_email task from being executed twice

---

app/__init__.py
tests/app/test_user_agent_processing.py

We want to log the usage of the various API clients we have so that we understand when they can be cycled.
To this end we are going to count usage in statsd.
All notify clients have a suer agent, of the format: NOTIFY-API-{LANGUAGE}-CLIENT/version.number
For example, NOTIFY-API-PYTHON-CLIENT/3.0.0
We convert that into a statsd/graphite friendly string of the format: notify-api-python-client.3-0-0
So we can subdivide on client and client version on our dashboards.
Present but unknown User agents are records as "non-notify-user-agent"
Missing are presented as "unknown"

Statsd counter for user agents.

---

app/authentication/auth.py
app/notifications/rest.py

this is used later in logging of requests
- if a client call the service id is stored
- if an admin app call the string "admin-app" is recorded.
depends on

Records the service ID if present in the request

---

app/__init__.py
requirements.txt
tests/app/celery/test_tasks.py

depends on
Enables request id logging on the API.
- request ids if not present are generated by the utils code and attached to all log events in a request
- request ids present on an API call are respected and attached to all log events in a request

Request id logging

---

app/dao/services_dao.py
app/service/rest.py
tests/app/dao/test_services_dao.py
tests/app/service/test_rest.py

We want to be able to toggle the numbers on the platform admin page between
including and excluding notifications sent using test keys, so that we can see
both real use of the platform and all load on it.
This parameter defaults to `True`, which is the existing behaviour.
Also add tests for the existing query for fetching today's stats for all services.

Add include_from_test_key parameter to /service

---

app/notifications/process_notifications.py
app/user/rest.py
tests/app/notifications/test_process_notification.py
tests/app/user/test_rest_verify.py

At the moment Notify's 2FA codes and internal emails go first to a `notify` queue, but then are put on the shared `send-sms/email` queues along with all other notifications, and they can take some time to arrive if big jobs are being processed.
This change means that these codes won't be delayed by large jobs going through the `send-sms/email` queues. `send_user_sms_code` now works much more like the endpoints for sending notifications, by persisting the notification and only using the `deliver_sms` task (instead of using `send_sms` as well).
The workers consuming the `notify` queue should be able to handle the deliver task as well, so no change should be needed to the celery workers to support this.
I think there's also a change in behaviour here: previously, if the Notify service was in …

Send Notify's 2FA codes via only one queue

---

app/dao/notifications_dao.py
app/v2/notifications/get_notifications.py
app/v2/notifications/notification_schemas.py
tests/app/conftest.py
tests/app/dao/test_notification_dao.py
tests/app/v2/notifications/test_get_notifications.py

This will allow an end user to get a notification by reference. Instead of creating a new endpoint, the get all notifications was modified to allow passing in the client reference as a query param e.g. `/v2/notifications?client_reference=someref.` 
The reference is unique so we will only ever return one (if it exists) and the response will be in the same format as when retrieving a single notification.

V2 get notification by reference

---

app/v2/notifications/notification_schemas.py
app/v2/notifications/post_notifications.py
tests/app/v2/notifications/test_post_notifications.py

If the service.sms_sender is not set the FROM_NUMBER from the config is returned, which is the default for the notification.

Fix the from number in the post_sms_response.

---

app/dao/notifications_dao.py
app/v2/notifications/get_notifications.py
app/v2/notifications/notification_schemas.py
tests/app/dao/test_notification_dao.py
tests/app/v2/notifications/test_get_notifications.py

This fixes an error in #762 where a reference was assumed to be unique and therefore a single 'get-notification' type response was returned.
A client may wish to retrieve a single notification by reference or _batch notifications_ (having the same reference). This pull request adds functionality in get_notifications to check for a `reference` param and if provided, it is used as a filter to retrieve the matching notifications.
The tests have also been updated to reflect the case where multiple notifications can have the same reference.

Fix: Retrieve notifications by reference

---

app/delivery/send_to_providers.py
app/notifications/process_notifications.py
app/notifications/rest.py
app/schemas.py
app/template/rest.py
app/utils.py
app/v2/notifications/post_notifications.py
requirements.txt
tests/app/dao/test_notification_dao.py
tests/app/delivery/test_send_to_providers.py
tests/app/notifications/rest/test_send_notification.py
tests/app/notifications/test_process_notification.py
tests/app/notifications/test_rest.py
tests/app/v2/notifications/test_post_notifications.py

Includes:
The test for `get_sms_fragment_count` has been removed because this method is already tested in utils here: https://github.com/alphagov/notifications-utils/blob/ac20f7e99ece4935fccf39ed9d5c0fb40e45bfbc/tests/test_base_template.py#L140-L159
Also includes this bug fix:

Update utils to 12.1.1

---

app/dao/notifications_dao.py
tests/app/celery/test_scheduled_tasks.py
tests/app/dao/test_notification_dao.py

Update the timeout notifications to use technical-failure rather than temporary failure

Update the timeout notifications to use technical-failure 

---

app/schema_validation/__init__.py
app/v2/notifications/notification_schemas.py
tests/app/delivery/test_send_to_providers.py
tests/app/v2/notifications/test_get_notifications.py
tests/app/v2/notifications/test_notification_schemas.py

In our v2 notification responses the URI's are returned with an invalid format. An example is `"http://api.url:6011//v2/templates/be35a391-e912-42e9-82e6-3f4953f6cbb0"` where `//` appears twice. 
This pull request rectifies the responses to ensure the URIs are returned in the correct format. Additionally the JSON schemas have been updated to reflect this and tests have been added. 
These tests exposed issues in our error handling, particularly where we build an array of schema validation errors. This function has also been modified to be more bulletproof to ensure we can build this array properly and not break whilst doing so.
Existing tests have also been refactored to check that we now receive the field name as well as the value that failed validation.

Fix uri validation in v2 responses

---

app/user/rest.py
tests/app/user/test_rest.py

Update the send_user_confirm_new_email to persist the notification then put on the "notify" queue for delivery.
The reason for doing this is to ensure the tasks performed for the Notify users are not queued behind a large job, a way to
ensure priority for messages.
2nd task for story: https://www.pivotaltracker.com/story/show/135839709

Refactor endpoint to confirm new email 

---

app/user/rest.py
tests/app/user/test_rest_verify.py

Refactor send_user_email_verification to persist the notification then put on the "notify" queue for delivery.
The reason for doing this is to ensure the tasks performed for the Notify users are not queued behind a large job, a way to
ensure priority for messages.
3rd task for story: https://www.pivotaltracker.com/story/show/135839709

Refactor the endpoint to send user email verification when registering

---

app/celery/provider_tasks.py
app/dao/notifications_dao.py
app/dao/provider_details_dao.py
app/models.py
app/provider_details/rest.py
config.py
migrations/versions/0062_provider_details_history.py
tests/app/clients/test_firetext.py
tests/app/conftest.py
tests/app/dao/test_provider_details_dao.py
tests/app/provider_details/test_rest.py
tests/conftest.py

uses a history table, like `template_history` or `service_history`
doesn't use the `Versioned` thing because we're only ever updating this from one place (`dao_update_provider_details`) and it's super straightforward what we're actually doing, compared to that history_meta which is some mad shit.
I did take the liberty of making some reasonably chunky QOL changes to the provider_details tests - I added a new fixture that preserves the existing state of your provider_details/history table so that we don't need to worry about it being irreversibly torn down by a test failing, and was able to refactor some tests as a result of that
in test_rest.py, most of the diff is me unindenting, but I did make some other changes too - lots of the old tests did things like "update, set priority to 5, …

audit changes to provider_details table

---

app/invite/rest.py
app/user/rest.py
tests/app/invite/test_invite_rest.py
tests/app/user/test_rest.py
tests/app/user/test_rest_verify.py

Refactor endpoints used to send messages by the Notify service to persist and send message to the notify queue.
These messages are for inviting someone to a service, reset password, and already registered email.
The reason for doing this is to ensure the tasks performed for the Notify users are not queued behind a large job, a way to ensure priority for messages.
story: https://www.pivotaltracker.com/story/show/135839709

Refactor notify user endpoints

---

app/celery/tasks.py
tests/app/celery/test_tasks.py
tests/app/conftest.py

it now switches utils.template.Template type, since the base Template type now no longer has a subject attribute.
updated test case to use `sample_email_template_with_placeholders` instead of `sample_email_template`

fix placeholders not appearing in email subject

---

app/delivery/send_to_providers.py
config.py
requirements.txt
tests/app/delivery/test_send_to_providers.py

branding in emails was previously hosted from admin app - this changes the url to be static.{domain}/images instead of {domain}/static/images, which redirects to cloudfront.
some manipulation of the URL was required to make sure it still serves locally rather than returning "static.localhost:6012" for example.
(if ADMIN_BASE_URL is localhost it just returns the old /static/ path)
also was able to remove DB interaction from a test. woo!

use cloudfront instead of flask to serve static images

---

app/delivery/send_to_providers.py
tests/app/delivery/test_send_to_providers.py

cloudfront caching isn't set up on those environments yet, so continue
to use flask for now - in the future we'll want to revert this once
those environments are up and running properly

don't use cloudfront on preview or staging

---

app/dao/services_dao.py
app/service/rest.py
tests/app/dao/test_services_dao.py
tests/app/service/test_rest.py

When the start_date and end_date query argruments exists in the request,
the query will return the results from the NotificationHistory table for the given date range.
We will need to check the performance of this query, but this will only be used by the platform admin page.

Added a date range filter for the get all services end point.

---

app/v2/notifications/notification_schemas.py
app/v2/notifications/post_notifications.py
tests/app/v2/notifications/test_notification_schemas.py
tests/app/v2/notifications/test_post_notifications.py

Small PR to remove the oneOf validation in the v2 get_notification_response schema. It doesn't work properly with the required element of the schema.

Removed the oneOf validation in the get_notification_response schema.

---

app/schema_validation/__init__.py
app/schemas.py
requirements.txt
tests/app/clients/test_aws_ses.py
tests/app/invite/test_invite_rest.py
tests/app/notifications/rest/test_send_notification.py
tests/app/user/test_rest.py
tests/app/v2/notifications/test_notification_schemas.py

brings in a fix to InvalidEmail/Phone/AddressExceptions not being instantiated correctly. `exception.message` is not a python standard, so we shouldn't be relying on it to transmit exception reasons - rather we should be using `str(exception)` instead. This involved a handful of small changes to the schema validation

bump utils to 13.0.1

---

tests/app/celery/test_tasks.py
tests/app/conftest.py
tests/app/dao/test_jobs_dao.py
tests/app/dao/test_users_dao.py
tests/app/db.py
tests/app/notifications/rest/test_send_notification.py
tests/app/service/test_api_key_endpoints.py
tests/app/service/test_rest.py

This is a proof of concept for a significant cleanup of the db test fixtures - by separating the two use cases of `sample_*` db objects:
* invoking as a fixture parameter so pytest automatically creates objects
* calling manually to create a custom object, perhaps with some specific non-default property. Often used if we want more than one of that object in the database.
So to help this, I've refactored `sample_user` fixture into the fixture and the db call as two separate functions. `sample_user` was chosen as it has no downstream dependencies on other fixtures - this refactor has to be done from leaf nodes else we'll get into cyclical import hell. The fixture just wraps the db call. Those who want to use the fixture still can, with zero changes. 
Those who want to create a custom user …

Conftest cleanups

---

app/models.py
migrations/versions/0063_templates_process_type.py
tests/app/notifications/test_process_notification.py
tests/conftest.py

This is the first deploy in series of deploys to give certain templates priority in processing.
If the template is marked as priority the notification will be sent using the `notify` queue.
The `notify` queue is a low volume queue, messages here will not be queue behind a large job and should be delivered with in a more consistent time frame.
- Added templates.process_type and templates_history.process_type column.
- Added a template_process_type table to handle the enum for templates.process_type, initial values are normal and priority
https://www.pivotaltracker.com/story/show/135429147

Add templates process type

---

app/authentication/auth.py
tests/app/authentication/test_authentication.py

We’ve seen quite a few developers encounter the `Invalid token: expired` error message when they’re getting started using the Notify API. When this happens they either raise a support ticket or ask for help on Slack.
In every case this has been because the clock on their machine/environment/container isn’t accurate. The error message doesn’t help them figure this out.
This commit adds extra detail to the error message so they can fix the problem without having to come to us for help.

Give a more helpful error when token has expired

---

app/template/rest.py
requirements.txt
tests/app/conftest.py
tests/app/delivery/test_send_to_providers.py
tests/app/template/test_rest.py

Depends on:
***
Right now we strip HTML from templates at the point of saving them. This also converts stuff like ampersands to their entity form (eg &amp;) and this is what we save in the database.
This is a bad idea when you’re sending a text message or a letter, in which an HTML entity makes no sense. But we still need to encode HTML in the body of HTML emails.
The right place to do this is when rendering the templates. The code to do this is now in utils. So this commit:
- pull in this new utils code
- removes the old
- adds some integration tests to make sure that everything is working as expected (more thorough unit tests are happening in utils)

Don’t strip HTML when saving templates

---

app/celery/research_mode_tasks.py
tests/app/celery/test_research_mode_tasks.py

The notification.to field is being formatted to be +447...
This meant that the research mode task would never work.
Also the way we mark data as "temporary-failure" with firetext is with first a pending status callback then a declined callback.
This PR changes the research mode task to account for that situation.

fix simulate research mode logic

---

app/config.py
app/notifications/rest.py
app/v2/notifications/get_notifications.py
tests/app/notifications/test_rest.py

Current the get all notifications API calls only return 50, this increases it to 250.

Increase page size for API calls to 250

---

app/celery/provider_tasks.py
app/dao/provider_details_dao.py
app/delivery/send_to_providers.py
app/provider_details/switch_providers.py
tests/app/celery/test_provider_tasks.py
tests/app/conftest.py
tests/app/dao/test_provider_details_dao.py

This will auto-switch to a new provider when the existing provider returns an error in `deliver_sms`.
When we send an sms notification for delivery to the provider, they could raise an exception (due to some error). In this case we want to switch to another provider. This will account for edge cases where the provider we want to switch to is already set as primary or they are inactive.

Auto-switch providers on error

---

app/dao/provider_statistics_dao.py
app/service/rest.py
tests/app/dao/test_provider_statistics_dao.py
tests/app/service/test_rest.py

We already filter the usage-by-month query by financial year. When we show the total usage for a service, we should be able to filter this by financial year.
Then, when the two lots of data are put side by side, it all adds up.

Allow filtering of billing info by financial year

---

app/celery/research_mode_tasks.py
app/delivery/send_to_providers.py
tests/app/delivery/test_send_to_providers.py

Previously research mode created a task to fake the callback from the providers. This meant there is an extra task for each notification than would be generated in a live situation.
This PR changes that, so that a research mode/test key notification calls the callback API rather than make a task to do that .
This ensures that the flow for research mode more closely mimics that of live, and removes a task from the process so we can more accurately test throughput,

Change to research mode.

---

app/notifications/process_client_response.py
app/notifications/rest.py
tests/app/notifications/rest/test_callbacks.py

This PR changes the response to POST /notifications/sms/<mmg | firetext> from a 400 response to a 200 response.
If we get a callback for a notification more than once or for a notification we log that but we return a 200 success response to the provider.
We have found that there is a situation where the send to provider throws a timeout exception but the provider did get the message, but we still send it to them again.
In which case they send the message twice, and callback for the message twice.
Another case where we may get duplicate callbacks is that the network gave the provider two callbacks meaning they pass those two callbacks onto us.
So it is really difficult to know if we sent to the provider twice or just got two callbacks.
The test_callback has many changes because I took the …

Return success of the callback is a duplicate or for an id that does not exist

---

app/__init__.py
app/celery/scheduled_tasks.py
app/clients/performance_platform/performance_platform_client.py
app/config.py
app/dao/notifications_dao.py
app/service/rest.py
app/utils.py
tests/app/celery/test_scheduled_tasks.py
tests/app/clients/test_performance_platform.py
tests/app/conftest.py
tests/app/dao/test_notification_dao.py
tests/app/test_utils.py

This adds a daily task that will update the performance platform with the latest email and sms notification counts 
The task is scheduled to run each day at 00:30AM. It will calculate the number of sent (failed, delivered) notifications from the previous day. 
E.g. When the task runs on Thur, Mar, 2017 at 00:30AM, it will retrieve counts for the day before until midnight (Wed, Mar, 2017 00:00AM to Thu, Mar, 2017 00:00AM). These will then be sent to the performance platform.

Add client and job to update the performance platform daily

---

app/celery/tasks.py
app/config.py
manifest-delivery-worker-database.yml
tests/app/celery/test_tasks.py
tests/app/conftest.py
tests/app/db.py

I pulled out the per-row handling from process_job into a separate function for readability/testability. I also pulled the exception handling stuff from send_sms and send_email out because it's literally identical.
I tried not to do too much, but moved a couple of tests around so they're in logical sections within the file, and changed a couple of mock points. I also created some new functions in `tests/db.py` to create templates and notifications - these don't require `notify_db`/`notify_db_session` so can be used anywhere cleanly - though you'll need to take care to ensure your test cleans up after itself.
Added new task `persist_letter` - I know it's not named at all related to the `send_sms` and `send_email` tasks it mimics, but those tasks aren't really fair - those tasks persist to …

Persist letters

---

app/__init__.py
app/celery/scheduled_tasks.py
app/clients/performance_platform/performance_platform_client.py
tests/app/celery/test_scheduled_tasks.py
tests/app/clients/test_performance_platform.py

This fixes the performance platform job that was not being executed.
**Changes:**
- Only execute the task if the client is set as active
- Ensure request JSON is formatted correctly
- Add more logs

Fix perf platform stats job

---

app/dao/notifications_dao.py
app/dao/services_dao.py
app/service/rest.py
app/utils.py
tests/app/dao/test_services_dao.py
tests/app/service/test_rest.py

This endpoint will eventually replace the weekly breakdown one. By month for a given financial year is better, because it gives us consistency with the breakdown of financial usage (and eventually consistency with the template usage).
The code to do this is a bit convoluted, in order to fill out the counts for months and statuses where we don’t have notifications.
This will make the admin side of this easier, because we can rely on there always being numbers available. The admin side will deal with summing the statuses (eg `temporary-failure` > `failed`) because this is presentational.
This commit also modifies the usage count to use `.between()` for consistency.

Add endpoint for breakdown of activity by month

---

README.md
app/models.py
requirements_for_test.txt
scripts/run_tests.sh
setup.cfg

PEP8 was renamed to pycodestyle; this issue explains why: https://github.com/PyCQA/pycodestyle/issues/466
This commit changes our tests to use pycodestyle instead of pep8.
It also means:
- making a couple of whitespace changes to appease the linter
- disabling warnings for bare `Except`s (ie `Except` instead of `Except ValueError`) – this seems like a sensible thing to lint for but I’m not going to make meaningful code changes in this commit

Use pycodestyle instead of PEP8

---

app/dao/users_dao.py
app/schemas.py
app/user/rest.py
tests/app/dao/test_users_dao.py
tests/app/user/test_rest.py

Currently we change the entire `User` object when we want to update the password. 
This refactors so we can update a user's password with a separate endpoint and without passing through the `User` object.

Add separate endpoint to update a user's password

---

app/dao/services_dao.py
tests/app/dao/test_services_dao.py

_All meaningful changes in 0dfa4a9_
The counts for emails and letters sent by month should be 0 in the tests, because we’re not creating any fake email or letter notifications. But they were coming out the same as whatever the count for sms was.
The status dictionary was being assigned once, and then subsequent uses of it were by reference. This meant that each template type was pointing at the same dictionary, and updating one meant updating all.
This commit adds a dictionary comprehension, which gets evaluated once for each template type, so each template type has its own `dict` of statuses.
Before
--
```
Email     SMS       Letter
|        |           |
{'sending':, 'failed', …}
```
After
--
```
Email                SMS                   Letter
|                  | …
```

Fix miscount with monthly totals

---

app/dao/provider_details_dao.py
tests/app/dao/test_provider_details_dao.py

This is a small fix that ensures the provider history table is updated when switching providers.
Originally the priorities were being updated only.

Fix: Update history when auto switching provider

---

requirements.txt
scripts/run_celery.sh
scripts/stop_celery.py

Stopping celery via upstart issues a TERM signal to the whole process group, which immediately kills the worker threads. This can lead to inconsistentcy in the state of a notification as an API call, for example, can take several seconds consequently the likelihood of the call being lost due to a restart is relatively high.
We need to ensure that we stop cleanly to ensure code deploys and autoscale events do not cause issues.
this script is called as part of a pre-stop hook in upstart, which passes a pid file location to the script. The script will then issues the TERM signal to only the master celery process. which will cleanly shut down the workers and exit.
the script will loop based on the existence of a /proc/{pid} for the celery master process. Once the file is gone the script will …

Add a stop celery script into the scripts folder.

---

requirements.txt

Brings in:
Changes:
https://github.com/alphagov/notifications-utils/compare/13.2.0...enable-markdown-links

Bump utils to turn on Markdown links

---

app/__init__.py
app/config.py
app/dao/templates_dao.py
app/notifications/process_notifications.py
app/template_statistics/rest.py
app/utils.py
tests/app/dao/test_templates_dao.py
tests/app/notifications/rest/test_send_notification.py
tests/app/notifications/test_process_notification.py
tests/app/template_statistics/test_rest.py

This PR implements a cache for the template usage statistics, shown on the dashboard. 
The cache expires every 10 minutes.
The cache is incremented on insert.

Add template usage cache

---

appspec.yml
scripts/aws_clear_instance.sh

This will remove the app and installed python3 packages on the instance before run the deployment scripts.
Currently we recycle our instances when we auto-scale. This means that our application files and python packages are installed atop of the existing files during deployment. This will not however take care of removing files that we deleted in the app or packages we removed. 
This taps into the AWS `BeforeInstall` hook which will run specified commands before the app files are copied. At this stage it makes sense to remove all our existing application files `/home/notify-app/notifications-api` and also remove all installed python3 packages. 
Once these actions are complete, we will run the standard deployment steps to copy over the new application files and install requirements …

Remove app and py3 packages on codedeploy-ment

---

app/notifications/process_notifications.py
tests/app/notifications/test_process_notification.py

Fix bug where the increment calls set count to 1 if the cache does not exist.

Redis cache bug fix when incrementing the cache

---

app/config.py
app/dao/users_dao.py
app/user/rest.py
tests/app/dao/test_users_dao.py
tests/app/user/test_rest_verify.py

When the verify code is wrong or expired increment the failed to login count for the user.
When the verify code is successfully used reset the failed login count to 0.
Added a limit to the number of active verify codes.
I removed the tests for the email verify code, we do not use them anymore. 
Merge https://github.com/alphagov/notifications-admin/pull/1134 after this one.
https://www.pivotaltracker.com/story/show/139184309

Set the expiry time on a verify code (2fa) to 10 minutes.

---

app/dao/users_dao.py
app/user/rest.py
tests/app/user/test_rest.py
tests/app/user/test_rest_verify.py

in verify_user_password, if succesful we reset the failed_login_count.
now we use failed_login_count for 2FA attempts, we need to make sure we
reset it in other places too, so that people don't get blocked,
especially in the reset-password user journey.
* verify_user_code - if it's succesful, reset the failed_login_count
* update_password - reset failed_login_count because either
* you're logged in and so it's 0 anyway
* you're resetting your password via pword reset link, and the old
count isn't relevant anymore
update_user now resets failed_login_count if password is changed  …
until work is done to stop using PUT /user/{id} on the admin app, this
function also needs to reset failed logins, cos it's used during the
forgotten password flow
best viewed in the separate commits 	ac9739f and …

ensure we reset failed_login_count when appropriate

---

app/dao/services_dao.py
app/service/rest.py
app/service/statistics.py
tests/app/dao/test_services_dao.py
tests/app/service/test_rest.py
tests/app/service/test_statistics.py

The weekly stats endpoint wont be used once https://github.com/alphagov/notifications-admin/pull/1109 has been merged.
It has been replaced with a new monthly endpoint in https://github.com/alphagov/notifications-api/pull/807

Remove weekly stats endpoints

---

requirements.txt

Brings in:
Changes: https://github.com/alphagov/notifications-utils/compare/13.5.0...remove-markdown-links

Bump utils to turn off Markdown links

---

Makefile

This removes the old `target` directory (containing api files) before recreating it and also ensures any dotfiles are included in the zip files.

Remove target dir before build and include any dotfiles in the zips

---

requirements.txt
tests/app/db.py
tests/app/delivery/test_send_to_providers.py

also refactor test_send_to_providers to use the shiny new db.py create_*db obj* functions and clean up some of the fixture usage

bump utils to 13.6.0 - downgrade non-gsm chars on sms send

---

Makefile

This removes the old wheelhouse directory (including old wheels) before we build from the potentially _updated_ `requirements.txt`.

Delete old wheels on build

---

Makefile
app/config.py

The API_HOST_NAME exists in credstash for all existing environments.

Remove explicit api_host_name vars from the envs

---

scripts/aws_install_dependencies.sh

This installs all wheels from the `wheelhouse` directory instead of resolving each requirement in `requirements.txt`.
Currently if any VCS link exists in `requirements.txt`, pip will attempt to resolve the package by going online. This introduces issues during our deployment process, particularly when Github is down - as we have two VCS dependencies (`boto` and `notifications-utils`). 
In #825, changes were introduced to delete the old app directory (include the leftover wheels) during deployment on recycled instances. This instills confidence that the latest wheelhouse directory will not contain any duplicate wheels (from a previous deployment) but instead have the latest up-to date wheels generated during our build process. This will install all of the wheels in the wheelhouse directory …

Ensure all wheels are installed offline from the wheelhouse directory

---

setup.cfg

see https://github.com/alphagov/notifications-utils/pull/121 for what might happen if your tests xpass

make xpass fail the test run

---

app/user/rest.py
tests/app/user/test_rest.py
tests/app/user/test_rest_verify.py

This PR will help to fix the user login flow when the user account becomes locked. However the story is not done until the admin PR is merged as well. 
It is ok to deploy this before the admin app, it will not make the user login flow any worse but it will not be correct until the admin app is deployed as well. Follow up with merging  https://github.com/alphagov/notifications-admin/pull/1162

Fix failed login count

---

app/dao/notifications_dao.py
app/dao/services_dao.py

Removed unused code in services_dao, which led to looking some of the queries.
By removing the join to services for the fetch_stats_by_date_range_for_all_services and dao_fetch_todays_stats_for_all_services queries we get a 30% and 25% performance improvement.

Query enhancement

---

app/dao/services_dao.py
app/dao/templates_dao.py
app/service/rest.py
app/service/statistics.py
tests/app/celery/test_scheduled_tasks.py
tests/app/conftest.py
tests/app/dao/test_services_dao.py
tests/app/db.py
tests/app/service/test_rest.py

This adds an endpoint to retrieve stats for a service grouped by template per month.
Call the endpoint with a given service id and financial year. It will return a dictionary containing counts of notifications by status for each template per month.
E.g. Calling for 2016 would return in the format of:
```
{
'2017-03': { 
"first_template_id":  {
"name": "sample template one",
"counts": { "sending": 0, "created": 0, .....}
},
"second_template_id": {
"name": "sample template two",
"counts": { "sending": 0, "created": 5, .....}
},
...
}, 
'2017-02': {}, 
'2017-01': {},
...
}
```

Add endpoint for service monthly usage stats by template

---

app/notifications/process_notifications.py
app/notifications/rest.py
app/template/rest.py
tests/app/notifications/rest/test_send_notification.py
tests/app/notifications/test_process_notification.py
tests/app/template/test_rest.py

> If a user makes an API request with additional personalisation fields,
> we should simply discard any fields that the template doesn't have.
>
> This gives a couple of related advantages:
>
> - modifying template parameters no longer requires downtime for
>   clients - as they can pass in extra new parameters before a template
>   change, or continue passing in old unused parameters after removing
>   them from a template
>
> - services can pass in large user objects, for example, and then play
>   around with templates adding and removing fields at will
>
> we should make sure we still return an error if a user doesn't pass in
> a required parameter.
– https://www.pivotaltracker.com/story/show/140774195

Quietly ignore extra personalisation

---

app/job/rest.py

Let's get some more info of the pagination object and the args pass into the next query

Add temporary logging for job notifications' retrieval

---

app/__init__.py
app/models.py
app/v2/template/__init__.py
app/v2/template/get_template.py
app/v2/template/template_schemas.py
tests/app/v2/template/test_get_template.py
tests/app/v2/template/test_template_schemas.py

Added v2/template/{id} endpoint with JSON schema and supporting tests.
Details outlined in this document under `Templates / Get Template by ID` section - [Notify V2 API](https://docs.google.com/document/d/1EuCipShwpZKVPQp3N0j7yRKazS34v5Bj5E9epl89iqY/edit#)
execute `py.test tests/app/v2/template/`
[Pivotal Tracker story] (https://www.pivotaltracker.com/n/projects/1443052/stories/141482957)

Added v2 template get ID endpoint, schema & tests

---

app/celery/tasks.py
app/config.py
app/dao/jobs_dao.py
tests/app/celery/test_tasks.py
tests/app/dao/test_jobs_dao.py
tests/app/db.py

A new task has been created to build a dvla file from the notifications for a given job for letters.
- If all notifications for the job have been persisted to the database we then create a file to save to S3.
Each notification is transformed to a pipe delimited line that matches the DVLA file format, https://github.com/alphagov/notify-ftp-documentation/tree/master/dvla_documentation.
The notifications-ftp app will then aggregate all the files for the day to then send to DVLA to be posted. 
- Else if all the notifications are not persisted to the database the task goes to the retry queue and is retried in 5 minutes for 15 tries. It is likely a job will complete in about 15 minutes so it is unlikely the task will retry more than a few times. 
TODO: move the s3upload method to the …

Create dvla file for a letter job

---

app/celery/tasks.py
app/notifications/process_notifications.py
app/notifications/rest.py
app/v2/notifications/post_notifications.py
tests/app/celery/test_tasks.py
tests/app/notifications/rest/test_send_notification.py
tests/app/notifications/test_process_notification.py
tests/app/public_contracts/test_POST_notification.py
tests/app/v2/notifications/test_post_notifications.py

This is being done for the PaaS migration to allow us to keep traffic coming in whilst we migrate the database.
uses the same tasks as the CSV uploaded notifications. Simple changes to not persist the notification, and call into a different task.

Reinstating the 2 task model for API submitted notifications.

---

app/celery/tasks.py
app/notifications/rest.py
app/v2/notifications/post_notifications.py
tests/app/celery/test_tasks.py
tests/app/notifications/rest/test_send_notification.py
tests/app/service/test_rest.py
tests/app/v2/notifications/test_post_notifications.py

when we made the change to async persist notifications, we forgot to pass through api_key_id and key_type. in send_sms/email, for legacy reasons, they default to None/KEY_TYPE_NORMAL, so regardless of what your api key was set up as, we would send real messages!
TODO: Once the PaaS transition is complete and the task changes are reverted, remove the api_key_id and key_type params from the send_* tasks entirely, as those are only called from the csv job flow, and don't need them

ensure we're passing through api keys and key types from notifications

---

app/dao/services_dao.py
app/service/rest.py
tests/app/service/test_rest.py

Problem after setting time to BST in get_detailed_services detected by test test_get_detailed_services_for_date_range which was failing. 
After setting the time to a datetime object the query on the DB would search for a precise datetime range rather than a date range.
Fixed in the service DAO by setting the end_date to the end of the day by adding 23 hours, 59 minutes and 59 seconds and filtering on the query based on datetime and not date.
execute py.test tests/app/service/test_rest.py::test_get_detailed_services_for_date_range
test has been updated with a range of datetimes for various states

Fix daterange in service DAO to work with BST

---

app/celery/tasks.py
app/notifications/process_notifications.py
app/notifications/rest.py
app/v2/notifications/post_notifications.py
tests/app/celery/test_tasks.py
tests/app/notifications/rest/test_send_notification.py
tests/app/notifications/test_process_notification.py
tests/app/public_contracts/test_POST_notification.py
tests/app/v2/notifications/test_post_notifications.py

[DO NOT MERGE - going to do some testing. Review welcome though]
This removes 2 pull requests
1) the code that places an API notification in the DB task queue prior to persistance. This was needed for a no-downtime deploy of the new hosting platform.
2) the api key bug fix that patched an error in (1) that caused an issue in sending test messages.

Revert db tasks from api

---

app/notifications/process_notifications.py
tests/app/notifications/test_process_notification.py

The redis cache for daily limits and template usage was being updated for notifications with a test api key.
This PR corrects that.

Stop notifications with test api key incrementing the cache

---

app/cloudfoundry_config.py
app/config.py
tests/app/test_cloudfoundry_config.py

Problems after change to BST as date passed to performance platform were 1 day out
Performance platform stats should be correct for future data pushes
https://www.gov.uk/performance/govuk-notify

Update daily performance job 4am

---

app/config.py
manifest-delivery-production.yml

Bumps the available memory on worker instances on PaaS prod.
Also breaks up the schedule on longer running jobs.

Bump memory on prod

---

app/clients/performance_platform/performance_platform_client.py
app/utils.py
tests/app/clients/test_performance_platform.py
tests/app/test_utils.py

Problem after BST time change, this fix will ensure that the performance platform will get the correct stats as the performance platform doesn't change UTC to BST.
Tests have been added to handle conversion from UTC to BST for performance platform POSTs
py.test -k test_get_utc_in_bst_returns_expected_date /tests

Add fix for bst

---

requirements.txt
tests/app/notifications/rest/test_send_notification.py

Brings in:
Also adds a test to make sure that passing a dictionary as a value in the `personalisation` argument works.
> Here are some animals:
>
> ((animal))
```python
send_email(…, personalisation={
'animal', ['cat', 'rat', 'gnat']
})
```
> Here are some animals:
>
> * cat
> * rat
> * gnat

Bump utils to allow lists as placeholder values

---

app/config.py
app/notifications/rest.py
app/v2/notifications/post_notifications.py
manifest-delivery-base.yml
manifest-delivery-production.yml
tests/app/notifications/rest/test_send_notification.py
tests/app/v2/notifications/test_post_notifications.py

[DO NOT MERGE - Depends on an update to the jenkins build pipeline to ship the new workers that are defined here in the delivery manifests]
Couple of changes to the workers:
1) Celery beat reduced in memory and instance count. (128M and single instance)
2) New workers added for the periodic and priority queues
3) Priority templates now written to the priority queues
4) Priority and periodic queues now no longer read by default. Have specific workers.

Update scheduled jobs

---

app/celery/tasks.py
tests/app/celery/test_tasks.py
tests/app/conftest.py

Whatever a user has entered for their service’s contact block should appear in the right place in the file we give to DVLA.
The work to output in the right fields in the DVLA file has already been done. We just weren’t passing it through. This commit passes it through.
***
This is a very simple change (see e47a008) but there’s a bit more refactoring and adding tests behind it that make this pull request larger.
Specifically on the changed way of generating random numbers, I wanted to make sure that they were still evenly distributed. To check this I generated a list of 1000 using both the old and new methods, then sorted and graphed them. Distribution looks pretty even to me:

Pass through contact block from service to outputted letter

---

app/celery/research_mode_tasks.py
app/clients/sms/firetext.py
app/clients/sms/mmg.py
app/notifications/notifications_sms_callback.py
tests/app/clients/test_firetext.py
tests/app/clients/test_mmg.py

Added a 60 second timeout to the MMG and fire text clients.
- This is a CONNECT and a READ timeout.
- Gets wrapped in the standard client exception, with a status code of 504, message Gateway timeout.
- Is quiet noisy in logs to allow us to see it
- Ensures we flick across the provider.
To test change the timeout to 0 and it will timeout.

Throw exception on long running client call

---

app/celery/scheduled_tasks.py
app/dao/jobs_dao.py
tests/app/celery/test_scheduled_tasks.py
tests/app/dao/test_jobs_dao.py

- previously this was unbounded, so it got all jobs older then 7 days. In excess of 75,000 🔥
- this meant that the job took (a) a long time and (b) a lot memory and (c) doing the same thing every day
These changes mean that the job has a 2 day eligible window for jobs, minimising the number of eligible jobs in a run, whilst still retaining some leeway in event if it failing one night.
In principle the job runs early morning on a given day. The previous 7 days are left alone, and then the previous 2 days worth of files are deleted:
so:
runs on
31st
30,29,28,27,26,25,24 are ignored
23,22  have files deleted
21 and earlier are ignored.

Updates to the delete CSV file job to reduce the number jobs included in any run.

---

app/dao/services_dao.py
tests/app/dao/test_services_dao.py

Updated the fetch_stats_by_date_range to return test notifications if the start and end date are with in the last 7 days.
- If the date range is with the last 7 days we query Notifications.
- If the date range is outside of the last 7 days we query NotificationHistory.
NotificationHistory does not persist notifications created with a test api key, since January 10, 2017.

Platform admin query

---

requirements.txt
tests/app/celery/test_tasks.py

Problem: we were sending the first line of the address in the `TO_NAME_2` field. This meant that they couldn’t do any PAF lookups with it, because it wasn’t where they were expecting.
The first line of the address is the second line of what our users give us. We need to give this to DVLA as the _third_ line of the address output, which they call `TO_ADDRESS_LINE_1`.
Also fixes a problem with line breaks between items in bulleted lists.
Depends on:

Build DVLA file with blank `TO_NAME_2` field

---

app/dao/notifications_dao.py

we do get the template for the notification, but in this case maybe it's better to lazily load it :)
although random thought - i'm not sure why we're returning the template at all - surely all this needs to return is the notification created_at

remove slow join from template-last-use query

---

requirements.txt

Update notifications-utils to version 15.1.1 in the hopes that the new logging level for s3tranfer will stop the boto logging of the letters body.
But I can only test this on preview.

Reduce boto logging level.

---

app/__init__.py
app/celery/tasks.py
app/dao/jobs_dao.py
app/notifications/process_notifications.py
app/v2/notifications/post_notifications.py
requirements.txt
tests/app/celery/test_tasks.py
tests/app/notifications/test_process_notification.py

- uses the reference field on the notifications table to store a 16char random string used to cross reference DVLA letters back to the notification
- used as letter barcode does not have space for a UUID notification id
Renamed the numeric_id to notification_reference in utils and changed validation rules to match this
Note also the persist_notification method set "reference" to be "client_reference" which is confusing and they are different things, so fixed this too.

Added the random string reference to the letter

---

app/v2/templates/get_templates.py
tests/app/v2/templates/test_get_templates.py

Route doesn't need a trailing slash for v2 get templates, so have removed it and updated the tests.

Removed slash from v2 get all templates route

---

app/dao/notifications_dao.py
tests/app/celery/test_scheduled_tasks.py
tests/app/dao/test_notification_dao.py
tests/app/db.py

letters shouldn't be timed out after 72 hours - it can take longer than that just to post them yet alone get delivery receipts. keep them in created/sending forever.
letters should, however, still be deleted after a week
also i refactored the timeout function cos it was gross

exclude letters from scheduled cleanup tasks

---

app/models.py
migrations/versions/0073_add_international_sms_flag.py

Add new column in db for international sms feature flag
Check that `can_send_international_sms` column is added to the `services` and `services_history` after migration

Add international sms feature flag in db

---

app/dao/provider_details_dao.py
tests/app/dao/test_provider_details_dao.py

This fixes the issue where `get_current_provider` returns an inactive provider. This would happen in the case where we have an inactive provider with the lowest priority (compared to others of the same notification type).

Fix: Ensure get_current_provider returns an active provider

---

app/dao/rates_dao.py
app/models.py
migrations/versions/0074_update_sms_rate.py
migrations/versions/0075_create_rates_table.py
tests/app/dao/test_rates_dao.py
tests/conftest.py

Added a new rates table.
We only need one rate per channel. This reflects that. The provider_rates has been left for now, it is still not being used.
New dao has been added to select the right rate for the given notification_type and date of notification.

Update sms rate

---

app/models.py
migrations/versions/0074_add_intl_flag_to_provider.py
migrations/versions/0076_add_intl_flag_to_provider.py
tests/app/provider_details/test_rest.py

This adds a `supports_international` flag on the providers and sets MMG as `True` for this.
The story was redefined: we don't need to have another provider, but do need some way of differentiating between `domestic` and `international`.
**Also: I'll update the migration to be up-to with master in a separate commit.**

Add international support flag for providers (migration)

---

app/models.py
migrations/versions/0076_add_intl_notification.py
migrations/versions/0077_add_intl_notification.py
tests/app/notifications/test_process_notification.py

This adds three new fields the `Notification` model that will be used to differentiate between domestic and international notifications.
All fields are nullable for now but a default has been set so that any new notification created with have `international` set to `False`.
**Note: Will rebase of master once #918 is in.**

Add intl notification fields

---

app/notifications/process_notifications.py
app/notifications/rest.py
app/notifications/validators.py
app/schema_validation/__init__.py
app/schemas.py
app/v2/notifications/post_notifications.py
requirements.txt
tests/app/conftest.py
tests/app/delivery/test_send_to_providers.py
tests/app/notifications/rest/test_send_notification.py
tests/app/notifications/test_process_notification.py
tests/app/notifications/test_validators.py
tests/app/v2/notifications/test_post_notifications.py

- uses new utils methods to validate phone numbers
- defaults to International=True on validation. This ensures the validator works on all numbers
- Then check if the user can send this message to the number internationally if needed.

Validate International phone numbers

---

app/models.py
app/notifications/process_notifications.py
tests/app/notifications/test_process_notification.py
tests/app/user/test_rest_verify.py

This will persist the notification with the international fields to the database. This calls additional validation/formatting in the persist_notification method, given that it will be passed the original recipient entry.
Also, we currently do no validation on send user sms code. For now we rely on the admin validation that only allows UK phone numbers. We'll need to think about supporting verification codes for international numbers in a separate story.

Persist international notification fields

---

app/dao/provider_details_dao.py
app/delivery/send_to_providers.py
tests/app/dao/test_provider_details_dao.py
tests/app/db.py
tests/app/delivery/test_send_to_providers.py

when sending international notifications, try and use the international providers.
uses the flag on the notification to pass an additional param to the get providers DAO calls.
This allows us to bring back:
- All providers by default
- Int ones if requested

Feat use intl provider send sms

---

tests/app/delivery/test_send_to_providers.py

These methods don’t exist any more.
Not doing this reformatting in the tests probably makes the tests more
robust too 😬

Remove references to old utils code

---

app/celery/provider_tasks.py
app/dao/notifications_dao.py
app/delivery/send_to_providers.py
tests/app/dao/test_notification_dao.py
tests/app/delivery/test_send_to_providers.py

This adds the last piece of the puzzle to _actually_ send international notifications to the providers. 
Additionally this also ensures we do not update international notifications with a status.
This depends on:

Send to provider for international

---

app/models.py
tests/app/test_model.py

"sent" is fine as an internal marker but not very obvious to the end
user that it specifically refers to international messages. We now
say "Sent internationally" in the CSV

add type conversion to report downloads

---

app/service/statistics.py
tests/app/dao/test_jobs_dao.py
tests/app/service/test_statistics.py

this is for when we fetch the large blue numbers for viewing
notifications for an entire service

treat sent as delivered in detailed service api

---

app/dao/notification_usage_dao.py
tests/app/dao/test_notification_usage_dao.py

get_yearly_billing_data function was making queries based on the valid_from rate date for the last rate object passed to the query, I've now updated this to use the start_date of the financial year rather than the rate valid_from date and have created a test to check that it is working as expected.
This only affects future usage dates, current year dates are correct.

Update billing data to handle future dates

---

app/dao/notification_usage_dao.py
migrations/versions/0080_fix_rate_start_date.py
tests/app/dao/test_notification_usage_dao.py

Update the valid_from date for the rate that is intended to start at the beginning of the financial year.
It was the start of the financial year in BST, needed to convert it to UTC.
Small change to the logic to find the rates.

Update the valid_from date for the rate

---

app/dao/services_dao.py
app/errors.py
app/models.py
migrations/versions/0081_noti_status_as_enum.py
tests/app/dao/test_notification_dao.py
tests/app/service/test_rest.py
tests/conftest.py

Adds a new column, `notification_status`, to the notification object. I know the name's a bit confusing, but I didn't want it to have some meta name that referenced the fact it's from a table.
This PR sets up the status table, and the new column as a nullable, foreign keyed table.
I've renamed the cols on the model to `_status_enum` and `_status_fkey` - they should not be interacted with directly. `Notification.status` now refers to a property that *reads from enum* and *updates both* - this way we immediately start populating new data without breaking old data. Then we can look at how to transfer old data across

notification status as table

---

migrations/versions/0082_set_international.py
migrations/versions/0083_set_international_not_null.py
migrations/versions/set_notifications_international.py

Update the script to set the international flag False where the value is null in the  notifications and notification_history, these updates are done in separate loops.
It takes about 1.5 minutes to update 27,000 notifications and 27,000 notification_history. 
The update is a row level lock so will only affect updates to the same row.
This is unlikely as the data being updated should be older than 3 days.
The second scripts updates the table to set international as not null, to make the model.

Update notification international

---

app/schema_validation/__init__.py
tests/app/v2/notifications/test_notification_schemas.py

jsonschema states:
> A format attribute can generally only validate a given set of instance types. If the type of the instance to validate is not in this set, validation for this format attribute and instance SHOULD succeed.
We were not checking for the type of the input, and our validators were behaving in unexpected manners (throwing TypeErrors etc etc). Despite us declaring that the phone_number field is of type `str`, we still need to make sure the validator passes gracefully, so that the inbuilt type check can be the bit that catches if someone passes in a non-str value. We've seen this with people passing in integers instead of strs for phone numbers. This'll make them receive a nice 400 error (e.g. "phone_number 12345 is not of type string"), rather than us having a 500 internal …

fix v2 schema phone/email validation when non-str passed in

---

app/aws/s3.py
app/celery/tasks.py
app/dao/notifications_dao.py
app/notifications/notifications_letter_callback.py
app/notifications/notifications_ses_callback.py
app/notifications/utils.py
tests/app/celery/test_tasks.py
tests/app/notifications/rest/test_callbacks.py

This processes the SNS request that is triggered when DVLA return a response file (S3). This will call a task to process the file if the file is in the correct format as we expect.
DVLA will return a response file containing the list of notification references along with their status (Success/Failed). We've setup SNS to trigger a notification which will be sent to our endpoint. 
This pulls the file from S3 and then prepares it for processing. Currently this doesn't actually do anything with each notification to update. We can only do this once we've setup our migration to move away from status enums.
We will receive two possible events from SNS, `Notification` for an S3 update or `SubscriptionConfirmation`. Both will have the `Type`, `MessageId` and `Message` hence their inclusion in the …

Process SNS request triggered by a DVLA S3 update

---

app/aws/s3.py
app/celery/tasks.py
app/notifications/notifications_letter_callback.py
app/notifications/notifications_ses_callback.py
app/notifications/utils.py
tests/app/aws/test_s3.py
tests/app/celery/test_tasks.py
tests/app/notifications/rest/test_callbacks.py

This follows from https://github.com/alphagov/notifications-api/pull/939 which processes the SNS request that is triggered when DVLA return a response file (S3). This will call a task to process the file if the file is in the correct format as we expect.
This originally failed on Preview as the refactoring in `s3.py` caused issues. This has been reverted to its original content. Additionally `get_s3_file` was added (with a test) as a helper method that is used as part of the celery task.

Add callback to process DVLA response file

---

app/notifications/notifications_letter_callback.py
tests/app/notifications/rest/test_callbacks.py

This fixes an issue where the JSON is not being parsed properly in the DVLA callback. 
An SNS callback with a JSON body has the header set to `text/plain` (http://docs.aws.amazon.com/sns/latest/dg/SendMessageToHttp.html). Flask's `request.get_json()` returns None if header is not set to `application/json`. This can be overridden by passing in the `force` parameter with a `True` value.
We haven't faced this behaviour with our SES callbacks as in there we call `json.loads(request.body)` which doesn't look at the header. This solution is less `flasky`, however.

Force parse JSON received from SNS

---

requirements.txt

Brings in:
***
Also brings in https://github.com/alphagov/notifications-utils/compare/16.1.3...17.0.2. Breaking change is in https://github.com/alphagov/notifications-utils/commit/06beb23c952c75374d8739cba2ffc3054bed33ef – shouldn’t affect the API.

Output contact blocks with placeholders replaced

---

app/dao/service_permissions_dao.py
app/dao/services_dao.py
app/models.py
tests/app/dao/test_service_permissions_dao.py
tests/app/dao/test_services_dao.py
tests/app/db.py

When creating a service default service_permissions (email and sms) will be added to the service_permissions table. 
The data model was also updated to include the service_permissions and tests had to be refactored in order to get them to pass.

Ken default permissions when creating service

---

app/service/rest.py
tests/app/service/test_rest.py

250,000 is easier to read than 250000.

Comma-format number when emailing live services

---

app/celery/tasks.py
app/notifications/notifications_letter_callback.py
tests/app/celery/test_tasks.py
tests/app/notifications/rest/test_callbacks.py

This fixes the issue where the JSON received from SNS in the DVLA callback was not being parsed correctly.
In short, `request.get_json(force=True)` wasn't enough to parse a nested JSON obj. The test data was incorrect so this wasn't caught by the test initially. The test stub has been fixed and now we additionally use `json.loads(req_json['Message')` to parse the nested JSON properly.

Fix issue with parsing JSON in SNS callback

---

app/models.py
migrations/versions/0085_update_incoming_to_inbound.py
tests/app/dao/test_service_permissions_dao.py
tests/app/dao/test_services_dao.py

Previously approved by Imdad, the only change in this PR https://github.com/alphagov/notifications-api/pull/969 is not to drop the updated_at column in service_permissions table

Ken refactor service permissions data model inc updated at

---

app/models.py
migrations/versions/0085_govuk_sms_sender.py
migrations/versions/0086_govuk_sms_sender.py
tests/app/delivery/test_send_to_providers.py
tests/app/service/test_rest.py

This upgrades the database to enforce a non-null constraint on the database. This requires us to make sure we don't put nulls in the DB, which the following two PRs will do:
Then, this can be run to update all existing nulls to 'GOVUK'.

Non null sender

---

app/celery/scheduled_tasks.py
app/config.py
app/dao/notifications_dao.py
tests/app/celery/test_scheduled_tasks.py
tests/app/dao/test_notification_dao.py

- PREVIOUS
based on status. so as we add new status we have some orphaned rows, as these delete queries would miss them
- NOW
based on type. In effect they do the same thing, deleting emails, sms or letters older than a week old irrespective of status. Can see is iterating on this to have more granularity say for letters, so split up. Also means that the delete action isn't so big, as we half the affected rows, by doing it by type.

Change delete jobs to delete by type

---

app/models.py
migrations/versions/0086_add_norm_to_notification.py

This adds `normalised_to` field to the `Notification` which will store the number that we normalise to when sending notifications.

Add normalised_to field to notification

---

app/models.py
app/service/rest.py
tests/app/service/test_rest.py

Marshmallow validates and deserialises - BUT, when it deserialises, it explicitly sets 
`sms_sender=None`, even when you haven't passed sms_sender in. This is problematic, because we wanted to take advantage of sqlalchemy's default value to set sms_sender to `GOVUK` when the actual DB commit happens.
Instead, still use marshmallow for validating, but manually carry out the json deserialisation in the model class.
This fixes a bug that only manifested when the database was upgraded, but the code hadn't updated. :tada:

separate service deserialization from validation

---

app/dao/notifications_dao.py
tests/app/dao/test_notification_dao.py

some countries don't return delivery receipts
me countries return delivery receipts when they reach the carrier
these countries, we should keep the notifications in sent (i.e. sent internationally) for. However, for countries that have normal delivery receipts, we should update them as we do for UK numbers
The ticket - https://www.pivotaltracker.com/story/show/144681997 - also states that when notifications are sent to countries that handle delivery receipts, we should record them as "sending" rather than "sent internationally", to distinguish them - however, haven't implemented that in this PR as wasn't sure if they're shown as different to UK numbers on the frontend.

update delivery receipts for countries that return them

---

scripts/delete_sqs_queues.py

This adds a simple script to retrieve and delete queues on SQS.
This retrieves a list of queues using `boto` and then deletes them one-by-one. This was run on tools for a cleanup. **This won't be run and is only being added so we can get this in and then iterate it for other envs.**

Add script to delete SQS queues

---

app/celery/tasks.py
app/notifications/process_notifications.py
tests/app/notifications/test_process_notification.py

This persists the normalised recipient to the `Notification` for sms and email.
This paves way for searching for notifications (needed for two-way) as we can query against this. 
This was branched off #979 so will be rebased off `master` once that's merged in.

Persist normalised recipient to `Notification`

---

app/dao/notifications_dao.py
app/service/rest.py
tests/app/conftest.py
tests/app/dao/test_notification_dao.py
tests/app/db.py
tests/app/notifications/test_process_notification.py
tests/app/service/test_rest.py

This adds ability to search notifications against their normalised address.
The `dao_get_notifications_by_to_field` normalises the search query and then searches Notifications against `normalised_to`. Additionally a `status` filter has been added that allows filtering by one or more statuses.
This was branched off #981 and needs to be rebased off master.

Search notifications against normalised address

---

app/dao/services_dao.py
app/models.py
app/schemas.py
app/service/rest.py
tests/app/conftest.py
tests/app/dao/test_services_dao.py
tests/app/service/test_rest.py

Enables the API to handle both deprecated service permission `can-send` columns in the `services` table and new permissions in `service_permissions` table.
The new json expected by the API in order to update service permissions will be in the form of - 
```
{
"permissions": ["email", "sms"]
}
```
The existing flags `can_send_letters` and `can_send_international_sms` will still be supported and will update the service_permissions within this PR.
To add a new permission simply be append a valid permission to the list.
To remove permissions remove it from the list.
This will also update the deprecated flags.
Supported permissions -  `["email", "sms", "letter", "international_sms", "inbound_sms"]`
Duplicate permissions will raise errors.

Ken update api service permissions handling

---

app/celery/provider_tasks.py
app/celery/scheduled_tasks.py
app/celery/statistics_tasks.py
app/celery/tasks.py
app/config.py
app/delivery/rest.py
app/invite/rest.py
app/job/rest.py
app/letters/send_letter_jobs.py
app/notifications/notifications_letter_callback.py
app/notifications/process_notifications.py
app/notifications/rest.py
app/service/sender.py
app/user/rest.py
app/v2/notifications/post_notifications.py
manifest-delivery-base.yml
tests/app/celery/test_provider_tasks.py
tests/app/celery/test_scheduled_tasks.py
tests/app/celery/test_statistics_tasks.py
tests/app/celery/test_tasks.py
tests/app/delivery/test_rest.py
tests/app/invite/test_invite_rest.py
tests/app/job/test_rest.py
tests/app/letters/test_send_letter_jobs.py
tests/app/notifications/rest/test_callbacks.py
tests/app/notifications/rest/test_send_notification.py
tests/app/notifications/test_process_notification.py
tests/app/user/test_rest.py
tests/app/user/test_rest_verify.py
tests/app/v2/notifications/test_post_notifications.py

Change retries policy. 
Before we had a long back off, now we have more, but shorter back offs.
- PREVIOUS
When we had an error talking to a provider we retried quickly and if we still got errors we backed off more and more. Maximum attempts was 5, max delay 4hours. This was to allow us time to ship a build if that was required.
- NOW
Backing off 48 times of 5 minutes each. This gives us the same total back off, but many more tries in that period.
- WHY
Having the long back off meant messages could be delayed 4 hours. This was happening more and more, as PaaS deploys can place things into the "inflight" state in SQS. The inflight state MUST have an expiry time LONGER than the maximum retry back off. This meant that messages would be delayed 4 hours, even when there was no app error.
By …

Redo queue visibitlity timeout

---

app/dao/notifications_dao.py
tests/app/dao/test_notification_dao.py

In the future we might want to validate email addresses before attempting to search by them. But for a first pass we can just return no results when a user types in something that isn’t an email address or phone number.
It definitely better than returning a 500.

Don’t 500 when searching with bad email address

---

manifest-api-preview.yml
manifest-delivery-base.yml
manifest-delivery-preview.yml
manifest-delivery-production.yml
manifest-delivery-staging.yml

Staging and prod now default to 768M of RAM, down from a 1G saves 512M per instance type
Preview down to 256M per app

Reduced memory footprint of the API apps.

---

app/dao/services_dao.py

sqlalchemy default doesn't appear to work correctly when there is a difference between the DB schema and the code (ie: during a migration) in this case, lets just set sms_sender ourselves.
we can't write unit tests for this because this only happens when the db is in an inconsistent state :weary:
(i've actually tested this).
Once this is deployed, I'll re-re-re-re-revert the db migration

manually set sms_sender when creating service

---

app/config.py
manifest-delivery-base.yml

Now we have new queues with new timeouts, this removes references to the old ones from the code base. It does not delete the queues, we can use @imdadahad script for that later.
CANNOT be shipped until at least 4 hours after https://github.com/alphagov/notifications-api/pull/987 on the offchance something ends up in 'inflight'
I'd ship it tomorrow (wednesday) at earliest

Removed references to old queus

---

app/notifications/receive_notifications.py
tests/app/notifications/test_receive_notification.py

First PR on firetext inbound SMS.
Simply dumps the form data out.
This verifies:
- Content type is url-form-endcoded
- Form body is as expected.
Future PRs will save this to the database.

Firetext inbound sms

---

Makefile

This script is run on Jenkins but with `python2`, it needs to run with `python3` otherwise a nasty SSL error occurs.

Use python3 when running migration-check script

---

app/models.py
app/notifications/validators.py
app/v2/notifications/notification_schemas.py
app/v2/notifications/post_notifications.py
migrations/versions/0088_add_schedule_serv_perm.py
tests/app/v2/notifications/test_post_notifications.py

Check service.permissions for the existence of schedule_notifications if the notifications is being created with a scheduled_for param.
We still need a way to add the permission from the front end.

Invite the service to schedule notifications from the API

---

app/config.py
app/dao/jobs_dao.py
tests/app/dao/test_jobs_dao.py

Same as how we ignore ‘send yourself a test’ messages (see: d8467bfc3cdca0f7dcd019f93ca20d981ef28760). The dashboard gets clogged up with one off messages otherwise, which affects:
- performance
- users ability to find their jobs

Ignore one-off messages in job list on dashboard

---

app/notifications/receive_notifications.py
tests/app/notifications/test_receive_notification.py

the DateRecieved field from MMG comes in with +s instead of spaces,
and uriencoded (the same as how they format their messages)
Make sure we decode this, and then convert to a UTC timestamp

parse datetimes from mmg inbound sms

---

app/__init__.py
app/dao/inbound_sms_dao.py
app/inbound_sms/rest.py
app/models.py
app/notifications/receive_notifications.py
tests/app/conftest.py
tests/app/dao/test_inbound_sms_dao.py
tests/app/db.py
tests/app/inbound_sms/test_rest.py
tests/app/notifications/test_receive_notification.py

This adds an inbound sms api, with two endpoints - one to get all inbound sms, and one to get a summary (for use on the dashboard)
the inbound sms endpoint is limitable and searchable
also, I added an `admin_request` fixture which takes care of some `client` boilerplate - namely gets rid of the need to sort out headers, and json loading/dumping.

Inbound sms api

---

app/celery/scheduled_tasks.py
app/config.py
app/dao/inbound_sms_dao.py
app/dao/notifications_dao.py
tests/app/celery/test_scheduled_tasks.py
tests/app/dao/test_inbound_sms_dao.py
tests/app/db.py

This adds a scheduled task that deletes inbound sms older than 7 days. This runs at 1AM every day, similar to other delete jobs which run 20 mins apart.

Delete inbound messages older than seven days

---

migrations/versions/0092_data_gov_uk.py

We need to send an email with data.gov.uk branding.
The image for the logo doesn’t exist yet, but doing this migration so we’re ready when it the logo does exist.

Add data.gov.uk to the list of organisations

---

app/celery/scheduled_tasks.py
app/config.py
app/dao/jobs_dao.py
tests/app/celery/test_scheduled_tasks.py
tests/app/conftest.py
tests/app/dao/test_jobs_dao.py

This adds a celery task `remove_letter_jobs` to delete letter jobs separately from deleting email&sms jobs (now renamed to `remove_sms_email_jobs`).
We now have two celery tasks:
1. `remove_sms_email_jobs` - run at 4am
2. `remove_letter_jobs` - run at 4:20am
Currently we call `remove_csv_files` to delete all jobs (letter, sms, email). Letter jobs should be treated differently to other jobs as they take longer to process. For this reason we want to manage their deletion separately. 
This adds a filter on `remove_csv_files` so we can specify the types of notifications we want to delete. This is used by two celery tasks described above to delete the relevant jobs.
- General refactor of tests to make them more readable
- Use `datetime` and `timedelta` for querying instead of `cast(datetime, …

Remove letter jobs separately

---

app/dao/inbound_sms_dao.py
app/inbound_sms/rest.py
tests/app/dao/test_inbound_sms_dao.py
tests/app/inbound_sms/test_rest.py

This adds a new endpoint to get an inbound message by id (to be used by admin).
1. URL: `/service/<id>/inbound-sms/<id>`
2. Added basic validation for now (similar to how we do in v2), will need to add a JSON schema at some point but may possible be an overkill to just validate a single `uuid`...

Add endpoint to get inbound sms by id

---

app/service/rest.py
tests/app/service/test_rest.py

We need this for the two way stuff in the admin app.
We already have this as a public endpoint, but the admin app can’t use it, because the admin app auths with its own key, not that of the service it’s acting on behalf of.
This endpoint makes sure that a request originating from one service can’t be used to see notifications belonging to another service.

Add private endpoint to get notification by ID

---

app/dao/statistics_dao.py
app/models.py
migrations/versions/0094_job_stats_update.py
tests/app/dao/test_statistics_dao.py

Add three new columns to job_statistics for sent, delivered and failed.
A job only ever has one notification type.
This is the first deploy, where the columns are added and populated.
Next a data migration will happen to populate these new columns for the older jobs that do not have the values set.
Then we stop populating the old columns and remove them.
This refactoring of the table structure will make the queries to the table much easier to handle.

Change the job_statistics table structure

---

requirements.txt

When this deploys it MUST do workers THEN api. We'll need to figure that out.
as per:
http://docs.celeryproject.org/en/latest/whatsnew-4.0.html#step-1-upgrade-to-celery-3-1-25
Part of https://www.pivotaltracker.com/story/show/146435939

Bumped version of celery

---

app/aws/s3.py
app/celery/scheduled_tasks.py
app/config.py
app/v2/notifications/get_notifications.py
tests/app/aws/test_s3.py
tests/app/celery/test_scheduled_tasks.py

This adds a scheduled task (runs at 4:40am) to remove transformed DVLA files older than seven days. We only remove two day's worth like we do in the other removal jobs.
We send transformed files to DVLA (that we build) for letter delivery. This removes those files older than seven days but only two day's worth as we do this for the other job files.
Note: Happy for suggestions on how I can make `test_remove_dvla_transformed_files_removes_expected_files` shorter as I opted for readability.

Remove transformed DVLA files older than 7 days

---

app/dao/notifications_dao.py
app/notifications/rest.py
app/service/rest.py
tests/app/dao/test_notification_dao.py
tests/app/service/test_rest.py

This changes `search_for_notification_by_to_field` to return the content of each `Notification`. 
Instead of creating a new endpoint for retrieving notification content for outbound messages, this uses the existing endpoint which is used in `get_notifications_for_service`. This returns the notifications in descending order of `created_at`.

Return notification content for outbound messages

---

app/dao/jobs_dao.py
app/job/rest.py
tests/app/dao/test_jobs_dao.py
tests/app/job/test_rest.py

New endpoints created that use a query that use the job_statistics table rather than the notifications table to aggregate totals. We should see a performance improvement on the dashboard, once integrated into the admin app.

Job stats for dashboard

---

app/aws/s3.py
app/celery/scheduled_tasks.py
app/config.py
tests/app/aws/test_s3.py
tests/app/celery/test_scheduled_tasks.py
tests/app/conftest.py

This adds a task (run daily at 5:10AM) to remove DVLA response files older than 7 days.
This works by using `boto` to get all s3 objects in the bucket and then, for each object, checking `Object["LastModified"]` to see if it is older than seven days (similar to how we do with other jobs). If so we remove the file.
- `boto` annoyingly returns the root directory an `Object`, e.g. if you wanted all files in `somedir/`, it'll return all the files within as objects but additionally an object for `somedir/`. This has to be removed manually.
- the `Object["LastModified"]` is 'offset-aware' and so needs additionally processing to make sure date range filters work as expected.

Remove DVLA response files older than 7 days

---

migrations/versions/0099_tfl_dar.py

Inbound provider and Dial-a-Ride migrations happened at the same time and got the same revision numbers.
This commit puts DAR after inbound provider.

Unpick migration conflict

---

app/config.py
app/errors.py
app/models.py
app/notifications/__init__.py
app/notifications/process_notifications.py
app/notifications/validators.py
app/schemas.py
app/service/rest.py
app/service/send_notification.py
app/v2/errors.py
app/v2/notifications/post_notifications.py
migrations/versions/0100_notification_created_by.py
tests/app/conftest.py
tests/app/inbound_sms/test_rest.py
tests/app/notifications/rest/test_send_notification.py
tests/app/notifications/test_process_notification.py
tests/app/service/test_rest.py
tests/app/service/test_send_one_off_notification.py

new admin endpoint takes `template_id`, `personalisation`, `to` and `created_by` vals, and, after similar validation to an API call, creates a notification and queues up its sending.
We now track `created_by` on the notification object - although only one-off notifications will have a value for this, since it's not applicable for API, and for jobs it's already stored on `job.created_by`.

Send one off messages from new admin endpoint

---

requirements.txt

Depends on:
Brings in these changes: https://github.com/alphagov/notifications-utils/compare/17.1.3...17.4.0

Update utils to make DAR logo bigger

---

app/dao/services_dao.py
app/dao/templates_dao.py
app/models.py
app/schemas.py
app/template/rest.py
migrations/versions/0102_template_redacted.py
tests/app/dao/test_templates_dao.py
tests/app/service/test_rest.py
tests/app/template/test_rest.py

If you make an update_template post containing `{"redact_personalisation": true, "updated_by_id": "..."}`, then we store a `redact_personalisation` marker in a new database table - TemplateRedacted.
This table just contains that boolean, and who and when updated it.

Templates can now be [REDACTED] 

---

app/template/rest.py
migrations/versions/0103_add_historical_redact.py
tests/app/template/test_rest.py

every current template gets a row in the template_redacted table - this inserts one for any template that doesn't already have a row, with redact set to false, the user set to NOTIFY_USER since it was just a script, and the updated_at set to the time the script is run

add historical redaction data

---

migrations/versions/0104_more_letter_orgs.py
tests/app/dvla_organisation/test_rest.py

> The logos are now ready to go on DVLA side- so far we've got:
> 001 = HM Government
> 002 = OPG
> 003 = DWP
> 004 = GEO

Add more organisations for letter branding

---

app/service/rest.py
tests/app/service/test_rest.py

This fixes an issue where the search notification 500's on the dashboard.
The admin expects each serialised `Notification` to have  `personalisation` field which is not dumped by the `notification_with_personalisation_schema`. The `notification_with_template_schema` provides this and we use this anyway in the same endpoint `get_all_notifications_for_service::302`. So let's use it here too...

Fix issue with search notification 500'ing

---

app/dao/services_dao.py
app/delivery/send_to_providers.py
app/models.py
app/notifications/rest.py
app/notifications/validators.py
app/schemas.py
app/service/rest.py
app/template/rest.py
app/utils.py
app/v2/notifications/post_notifications.py
tests/app/conftest.py
tests/app/dao/test_services_dao.py
tests/app/notifications/rest/test_send_notification.py
tests/app/notifications/test_validators.py
tests/app/service/test_rest.py
tests/app/template/test_rest.py
tests/app/v2/notifications/test_post_notifications.py

Refactored the code to remove references to permission flags in service and use service permissions instead.
Also updated code to ensure that email / sms permission settings are honoured for sending, and creating / updating templates.
If the notification is already scheduled or in a queue then honour sending it.

Use new service permissions and allow disabling of email/sms

---

app/models.py
tests/app/test_model.py

There are a variety of ways a notification can be created - via the API, via CSV, via one-off messages, via the same but sent as a test - the point is, there are lots of entry points, and lots of inconsistency about how personalisation may be sent in. If there are no personalisation options in the template, we may get either `None` or `{}` - if the value is None, to avoid an error in our encryption lib, we just store None in the database.
THIS ENDS NOW!
We've had some problems on the front-end that is caused by notifications having the `None` value. This commit changes the personalisation property getter and setter to store/return `{}` rather than None.

notification.personalisation now always returns an empty dict

---

app/models.py
tests/app/dao/test_jobs_dao.py
tests/app/dao/test_notification_dao.py

This stops updating the old `Notification. _status_enum` and `NotificationHistory. _status_enum` columns and instead will now only update the newer `_status_fkey` column.
- Return new column when calling `.status`
- Remove unncessary tests that were checking `._status_enum` was being populated
- Updates some tests which can cause failure if unordered

1/4 Stop updating old Notification status column

---

app/dao/notifications_dao.py
tests/app/celery/test_scheduled_tasks.py

This fixes an issue where the status fields for `Notification` and `NotificationHistory` are not being synced correctly.
The scheduled job `timeout_notifications` times out notifications after three days. This results in the statuses in both `[Notification, NotificationHistory]` to be updated based on some rules.
However, this does not correctly update **both** status fields (_status_enum, _status_fkey) correctly to keep them in sync. 
Once this is in place, another DB command will need to be run that clean up the mess.

Fix syncing issue with Notification statuses

---

app/notifications/receive_notifications.py
tests/app/conftest.py
tests/app/notifications/test_receive_notification.py

This update prevents services that do not have inbound SMS and SMS permissions from storing the inbound sms message.

Prevent inbound SMS store if no inbound SMS permissions

---

migrations/versions/0105_opg_letter_org.py

Logo was added here: https://github.com/alphagov/notifications-template-preview/pull/19
> OPG logo has already been submitted to DVLA and designated 002

Add OPG to letter organisations

---

app/models.py
migrations/versions/0106_null_noti_status.py

Before we can remove `_status_enum` we need to make this column nullable. This will ensure that when we create notifications after removing this, the `status` field in the `Notification` and `NotificationHistory` tables can be set to `null` allowing us to still create notifications despite not populating this field.
I tested this locally with 9m notifications and it ran in a second so no potential issues on that front.
2/3 - Stop updating old Notification status column
3/3 - Delete the old column

1/3 Make Notification._status_enum and NotificationHistory._status_enum nullable

---

app/dao/jobs_dao.py
app/dao/notifications_dao.py
app/dao/services_dao.py
app/dao/statistics_dao.py
app/models.py
app/schemas.py
tests/app/celery/test_scheduled_tasks.py
tests/app/dao/test_jobs_dao.py
tests/app/dao/test_notification_dao.py
tests/app/job/test_rest.py
tests/app/test_schemas.py

This stops updating the old `Notification. _status_enum` and `NotificationHistory. _status_enum` columns and instead will now only update the newer `_status_fkey` column.
- Return new column when calling `.status`
- Remove unncessary tests that were checking `._status_enum` was being populated
- Updates some tests which can cause failure if unordered

2/3 Stop updating old Notification status column

---

app/cloudfoundry_config.py
app/config.py
tests/app/test_cloudfoundry_config.py
tests/conftest.py

in tests, we were replacing os.environ with a basic dict so that
we didn't overwrite the contents of the real environment during tests.
However, os.environ doesn't accept non-str values, so this commit
changes the fixture so that it asserts all values set are strings.
We needed to change how we store ip whitelist stuff in the env because
of this.

don't store non-strings to os.environ

---

app/celery/celery.py

We don't use boto2 on the api anymore, not since celery 4.0.2
Note - if you run locally with boto2 still installed you'll see errors that complain about things like:
boto.exception.SQSError: SQSError: 403 Forbidden
<?xml version="1.0"?><ErrorResponse xmlns="http://queue.amazonaws.com/doc/2012-11-05/"><Error><Type>Sender</Type><Code>SignatureDoesNotMatch</Code><Message>Credential should be scoped to a valid region, not 'queue'. </Message><Detail/></Error><RequestId>52207ca4-9131-58cb-89ae-2d45f06623a3</RequestId></ErrorResponse>
If so, make sure boto2 is completely uninstalled.

remove `sqs` from region - this is only needed in boto2

---

requirements.txt

This pulls in the most recent version of celery/kombu/master - it
prevents situations where the celery MainProcess would consume 100%
CPU while not distributing any tasks to the workers.
Note: If, locally, you already have kombu==4.0.2, you'll have to run
pip install --upgrade https://github.com/celery/kombu/zipball/b2f21289
to get the new version.

update kombu version to prevent 100% CPU usage

---

migrations/versions/0109_rem_old_noti_status.py

This drops the old `Notification.status` and `NotificationHistory.status` columns from the DB. It is no longer referenced in the models and as a result this is just a migration.

3/3 Drop old notification status column

---

app/notifications/process_notifications.py
tests/app/v2/notifications/test_post_notifications.py

When a post is made for a simulated number the id is empty in the notificaiton object that we return.
This fixes that.

Fix for simulated notifications.

---

app/celery/tasks.py
app/config.py
app/delivery/rest.py
app/notifications/process_notifications.py
manifest-delivery-base.yml

we're reading from those two queues as well as the existing send queue, however for now we don't send anything to them
we don't want to start sending immediately notifications to the new queues or they won't be picked up while the deploy's underway

[1/3] add separate send-sms and send-email queues

---

app/notifications/notifications_sms_callback.py

Added logging to show the entire form posted to us by the SMS client … ……providers.
This can be useful information when debugging what happened to a notificaiton.
Recently there was a discrepancy between the failure type used by each provider for a particular number, this logging would have helped.

Add logging to SMS delivery receipts

---

.gitignore
Makefile
scripts/aws_install_dependencies.sh

This removes storing wheels for offline installation as we used for AWS.
Will need to manually remove the `wheelhouse` folders on the Jenkins before merging this.

Remove wheels-ing on deployment

---

app/config.py
app/delivery/send_to_providers.py
tests/app/delivery/test_send_to_providers.py

In order to manage organisation logos from Admin, the API has to be updated to deliver images from a CDN which is pointing at the S3 logos bucket. 
In preparation any existing logos in use have been uploaded to the s3 bucket so that any emails sent out via the api will pick them up from the logo CDN and not the static location on the web app folder. 
This should ensure no breaks during the update of the API as the existing logos will still be available in the static web app folder.
Step 3/5 from https://www.pivotaltracker.com/story/show/148289053
Send an email to yourself from a template that is using a logo
- check that the logo image can be seen
- right click on the logo to check that the image src is the logo CDN

Update email logo to use logo CDN

---

app/dao/monthly_billing_dao.py
tests/app/dao/test_monthly_billing.py

This fixes the issue where the monthly billing data was not being updated in some cases when running the db command.
`create_or_update_monthly_billing_sms` did not query the `MonthlyBilling` table with the `service_id`. This meant that we would not create a new `MonthlyBilling` entry if one existed already with the same `start date` or `notification_type`.
Add the `service_id` in the filter.

Fix issue where monthly billing data was not being updated

---

requirements.txt

Changes: https://github.com/alphagov/notifications-utils/compare/17.5.7...17.7.0

Bump utils to 17.7.0

---

app/commands.py
app/config.py
app/dao/notification_usage_dao.py
tests/app/dao/test_notification_usage_dao.py

This starts populating the monthly billing data daily (5:10AM) and also adjusts the backfill command to make it less granular.
Currently the backfill command takes in the `month` and `year` which is pretty granular. Let's populate it by year. as we'll need to do this for multiple services.
Additionally let's start populating the `MonthlyBilling` table daily with the latest stats on a schedule. As part for this query it does a check to see all services that need to be populated. I checked and found that it took <3 secs to do that which is okay.
Relies on this fix to be in:

Populate monthly billing on a schedule and make backfill less granular

---

app/dao/notifications_dao.py
app/template_statistics/rest.py
tests/app/template_statistics/test_rest.py

This removes querying from the `NotificationHistory` to check last usage of a given template.
Querying from the `NotificationHistory` table has caused timeouts in multiple places. Let's remove that from here as it's good enough to know (on the admin) that a given template hasn't been used for more than seven days, as opposed to the actual time after seven days.

Update the last template usage query to check Notification table

---

app/cloudfoundry_config.py
app/config.py
requirements.txt
scripts/run_app_paas.sh
tests/app/test_cloudfoundry_config.py
tests/app/test_config.py

previously in run_app_paas.sh, we captured stdout from the app and piped that into the log file. However, this came up with a bunch of problems, mainly:
* exceptions with stack traces often weren't formatted properly, and kibana could not parse them
* celery logs were duplicated - we'd collect both the json logs and the human readable stdout logs.
instead, with the updated utils library, we can use that to log json straight to the appropriate directory directly.

don't capture logs directly from stdout

---

app/service/rest.py
tests/app/service/test_rest.py

Created a new service endpoint that checks if the service name or email_from is unique.
Why is this needed?
When a user updates a service name they enter the new name in a form, are then asked to confirm the change by entering their password. Then the API call to update_service is called. If we let the update service API call fail with the integrity constraint it will be awkward for the user.

Check service name is unique

---

migrations/versions/0114_drop_monthly_billing_cols.py

We're no longer using these columns in favour as we now use the `start_date` and `end_date`.

Drop unused month and year columns from MonthlyBilling

---

app/config.py

We are not processing the data in these files yet so we need to stop deleting them until the data is recorded.

Stop purging the DVLA response files from S3

---

app/dao/inbound_numbers_dao.py
app/models.py
migrations/versions/0113_add_inbound_numbers.py
migrations/versions/0114_add_inbound_numbers.py
migrations/versions/0115_add_inbound_numbers.py
tests/app/conftest.py
tests/app/dao/test_inbound_numbers_dao.py
tests/app/dao/test_services_dao.py
tests/app/db.py
tests/app/test_model.py

Rather than manage inbound numbers via a google doc, this is the first step `1/6` to manage `inbound_numbers` via a database table - https://www.pivotaltracker.com/story/show/146774373
- `inbound_number` data model added
- `inbound_numbers_dao` added
- migration script to create the `inbound_numbers` table added
- update service DAO test so can access inbound_number
execute `run_tests.sh` to run unit tests that use `inbound_numbers_dao`, 
and check that a new `inbound_numbers` table is correctly created in your local database.

Add inbound number model and DAO

---

migrations/versions/0116_another_letter_org.py

More migrations got merged in between me making 0114 and merging the PR that contained 0114.
If we named the files as just 0114.py then this would get flagged as a merge conflict…

Fix order of DB migrations

---

app/celery/scheduled_tasks.py
app/clients/performance_platform/performance_platform_client.py
app/commands.py
app/dao/date_util.py
app/dao/monthly_billing_dao.py
app/dao/notification_usage_dao.py
app/models.py
app/service/rest.py
app/utils.py
migrations/versions/0112_add_start_end_dates.py
tests/app/celery/test_scheduled_tasks.py
tests/app/dao/test_date_utils.py
tests/app/dao/test_monthly_billing.py
tests/app/dao/test_notification_usage_dao.py
tests/app/db.py
tests/app/service/test_rest.py
tests/app/test_utils.py

This adds functionality to populate billing data into the new `MonthlyBilling` table for `email` and `sms` and helpers to retrieve that data.
**This is best reviewed commit by commit**
1. Currently we have only populated billing data for `sms`. This adds the changes to populate for `email` too. Both the command to manually populate by `year` as well as the nightly task have been updated. Additionally, it's a bit more robust in checking date conversion and updating the right month for billing (review 85ac0d3ea74fbc636b4cb0e8e9335530628624b1)
2. Helpers have been added to retrieve the a given month's billing data as the whole financial year  from the new table. This also includes the current day delta totals (review 13904c54f661b16d969e05f4177ba28630ccc325) which we will use on the admin to …

Populate and retrieve billing data from the new MonthlyBilling table

---

app/__init__.py
app/billing/rest.py
app/service/rest.py
tests/app/billing/test_billing.py

This adds two new endpoints to retrieve billing data from the new table.
A new `billing_blueprint` has been added to keep this nice and separate.
For the monthly breakdown endpoint, it returns the same response as we did before. 
For the yearly endpoint, the response is slightly different. This is because admin only makes use of `rate`, `notification_type` and `billing_units`, hence why only these are returned.
Additionally it's worth noting that currently we are making a strong assumption that we will only have a single rate per year (not a new thing in this pr). As discussed, we will have to refactor etc. as and when that day comes. For now it returns the rate corresponding to that year.

Add endpoints to retrieve billing data

---

app/models.py
app/v2/template/template_schemas.py
tests/app/v2/template/test_get_template.py
tests/app/v2/template/test_template_schemas.py
tests/app/v2/templates/test_templates_schemas.py

The use for the public template API is for building caseworking systems or similar, where you might need a list of templates to pick from (ie instead of using the Notify web interface to pick from and send a message).
Right now our API isn’t returning the template name as part of the response. The name is a useful, human-friendly way of identifying a template.
This commit changes the response to include the name.
Some clients will need updating before this can be useful.

Return template name in public API

---

app/billing/rest.py
app/dao/date_util.py
tests/app/billing/test_billing.py
tests/app/dao/test_monthly_billing.py

This retrieves the monthly billing data from the `MonthlyBilling` table, instead of `NotificationHistory`.
1. For every month in the desired financial year, we query the retrieve the monthly billing data. If it is empty, we return an empty `[]`. If the `monthly_totals` is empty, we return a blank result set otherwise we return the transformed data.
2. The `get_months_for_financial_year` and `get_months_for_year` helpers were taken from the admin. As their thoroughly tested over there, they've just been included here with no tests. A separate story will be added into to move this into utils.
3. Remove redundant `_create_monthly_billing_entry` in tests as we have `create_monthly_billing_entry` in `tests/app/db.py`.

Get monthly usage breakdown from the correct table

---

app/billing/rest.py
tests/app/billing/test_billing.py

Currently API only returns for a single monthly total entry. 
This aggregates for multiple entries (in that case) and also calculates based on the `rate_multiplier` correctly.

Fix: Aggregate monthly totals from billing data

---

app/commands.py

Update script to link an `inbound_numbers.number` to a `services.sms_sender`.
This script should only be run after Admin has been deployed - https://github.com/alphagov/notifications-admin/pull/1429
Part 7 / 8 of https://www.pivotaltracker.com/story/show/146774373
Execute the command 
`python application.py custom_db_script -n link_inbound_numbers_to_service`
After running the command, check that the service ids are populated correctly in the `inbound_numbers` table by checking that the `services.sms_sender` matches the `inbound_numbers.number`

Update inbound_numbers to services that have sms_sender in inbound_numbers

---

app/dao/notifications_dao.py
tests/app/dao/test_notification_dao.py

The activity page doesn’t show notifications sent with a test key.
However it _does_ when you search by recipient. This is confusing and inconsistent.

Exclude test keys when searching by recipient

---

app/authentication/auth.py

if you log a dictionary, python-json-logger will pass that through to the json output. In the ip restriction wrapper, lets log the ip_address and whether it was found in the whitelist, to a nested `log_contents` dict.
when logging json, it looks like this:
`{"name": "app", "levelname": "INFO", "message": "Logging configured", "pathname": "/Users/leohemsted/.virtualenvs/api/lib/python3.5/site-packages/notifications_utils/logging.py", "lineno": 98, "log_contents": {"thing": 1, "foo": "bar"}, "requestId": "no-request-id", "time": "2017-07-31T18:09:39", "application": "api", "logType": "application"}`
when logging via stdout locally, it looks like this:
`2017-07-31T18:11:31 api app INFO no-request-id "{'log_contents': {'foo': 'bar', 'thing': 1}, 'message': 'Logging configured'}" [in …

log ip address as separate field to allow analysis of messages

---

app/template_statistics/rest.py
tests/app/template_statistics/test_rest.py

The logs kept reporting a data error from the redis client. This would happen any time we set the cache with empty cache values.
Added a check for values before setting the cache

Stop redis cache from throwing an error

---

requirements.txt

pyup is trying to upgrade flask-bcrypt, which causes errors in all subsequent PR builds for #reasons. Lets make pyup ignore flask-bcrypt until we figure out why the upgrade doesn't work

make pyup ignore flask-bcrypt

---

app/notifications/rest.py
tests/app/notifications/rest/test_send_notification.py

If the notification was invalid it would raise an exception with an error message. Now if someone tries to send a letter with the old API they will get a message to try the latest version of the client.

Added a proper error response if the notification type is not supported.

---

app/dao/services_dao.py
app/notifications/receive_notifications.py
tests/app/dao/test_services_dao.py
tests/app/db.py
tests/app/notifications/test_receive_notification.py

Final step of the story to use `inbound_numbers` table - https://www.pivotaltracker.com/story/show/146774373
- Refactor out `sms_sender` so that it is not returned when getting a service from an inbound number
- removed unnecessary tests
Tests should still run and admin functionality to turn on and off inbound sms should still work.

Refactor inbound numbers

---

app/celery/scheduled_tasks.py
app/clients/performance_platform/performance_platform_client.py
app/cloudfoundry_config.py
app/config.py
app/performance_platform/total_sent_notifications.py
manifest-api-base.yml
manifest-delivery-base.yml
tests/app/celery/test_scheduled_tasks.py
tests/app/clients/test_performance_platform.py
tests/app/performance_platform/test_total_sent_notifications.py
tests/app/test_cloudfoundry_config.py

With a second performance stats endpoint coming, we needed a refactor - we were previously only dealing with one endpoint and one bearer token, but now we have many, so they should be in a cloudfoundry config.
Also, a lot of refactoring happened, moving stuff out of performance_platform_client that wasn't specifically generic performance platform client stuff, so that's gone in its own file in `app/performance_platform/`
this needs to be deployed at around the same time as: 
it needs to happen after AWS, but before any other api deploys happen

Perf stats refactor

---

requirements_for_test.txt
scripts/run_tests.sh
tests/conftest.py

previously we didn't do this because the tests all used the same DB (test_notifications_api), however @minglis shared a snippet that simply creates one test db per thread. If you run without using `run_tests` (or `py.test -n #`) then it'll create a db `test_notifications_api_master`

run tests in multiple threads at once

---

app/models.py
app/schemas.py
migrations/versions/0117_international_sms_notify.py
tests/app/dao/test_users_dao.py
tests/app/service/test_service_whitelist.py

Right now Notify restricts you to registering with a UK mobile number. This is because when we built the user registration stuff we couldn’t send to international mobiles.
However we can send to international mobile numbers, and it’s totally reasonable to expect employees of the UK government to be working abroad, and have a foreign mobile phone – we’ve heard from one such user.
In order for users of Notify to register with an international phone number, the Notify service needs to have the `international_sms` permission set. Which this commit does, as a data migration.
---
Since we’re letting users register with international phone numbers on the frontend, we shouldn’t block users from doing this on the API side.  Same thing for the whitelist, where we’re also allowing international …

Allow Notify service to send international sms

---

app/dao/monthly_billing_dao.py
app/dao/notification_usage_dao.py
app/service/rest.py
tests/app/dao/test_monthly_billing.py
tests/app/dao/test_notification_usage_dao.py
tests/app/service/test_rest.py

The removes billing code that was previously used by admin for the usage page. 
The yearly and monthly functions that queried the `NotificationHistory` table are no longer used. Instead we now query and do aggregation with results from `MonthlyBilling`.

Remove unused billing usage code

---

app/models.py
migrations/script.py.mako
migrations/versions/0119_add_email_reply_to.py

This adds a migration that creates the `service_email_reply_to` table that will facilitate having multiple from-email addresses for a service.
`email_address` cannot be `null` which means for services that have no `reply_to_email_address` will not have an entry in the table. 
The alembic template used to generate migration scripts was also changed which resolves some PEP errors.

[1/5] Create new ServiceEmailReplyTo table

---

app/dao/service_email_reply_to_dao.py
app/service/rest.py
tests/app/dao/test_service_email_reply_to_dao.py
tests/app/db.py
tests/app/service/test_rest.py

**Branched off #1233 and will rebase off master once #1233 is merged.**  
This will upsert (update or insert) the `service_email_reply_to` table when the `reply_to_email_address` for a service is changed.
**UPDATE: Rebased successfully.**

[2/5] Upsert into ServiceReplyToEmail table when updating a service

---

app/v2/notifications/notification_schemas.py
app/v2/notifications/post_notifications.py
requirements_for_test.txt
tests/app/v2/notifications/test_notification_schemas.py
tests/app/v2/notifications/test_post_letter_notifications.py
tests/app/v2/notifications/test_post_notifications.py

My local build was not always getting the optional requirement for the jsonschema uri format checker (rfc3987).
The requirement has been added to the requirements_for_test file.
I changed the tests to validate the response schema from the post_notifications tests, this way we can tell if we are breaking the contract.
This showed that the email_from was not returning the entire email address but just the username, that has been corrected here.
Removed the response schema validation tests since they are not being testing in the post notification tests.

Small refactor to how notification_schemas are tested.

---

app/encryption.py
requirements.txt

this uses bcrypt directly rather than using the wrapper python-bcrypt.
WARNING! You'll need to update your local install by running:
```
pip uninstall python-bcrypt
pip install flask-bcrypt==0.7.1
```

upgrade flask-bcrypt to 0.7.1

---

app/models.py
app/schemas.py
tests/app/service/test_rest.py

- Updated reply to email test so that the request to create or update
email is not mocked.
- Excluded reply_to_email_addresses from the Service schema

Update reply to email test

---

app/schema_validation/definitions.py
tests/app/v2/notifications/test_post_letter_notifications.py

Fixes the problem mentioned here https://www.pivotaltracker.com/story/show/150843938 
Currently for letter API calls it throws a `400` on missing required fields but accepts blank ones, which should really also throw a `400` with an appropriate message.
- Updated the JSON schema to check that strings are not empty.
- Refactored letter tests so that they are not broken

Raise validation errors for empty letter fields

---

app/commands.py
application.py

Branched off #1237 and will be rebased once that's merged in.
This adds a command that will migrate all the existing data to the new `service_email_reply_to` table.
As it stands, any service that updates their `reply_to_email_address` will have an 'upserted` entry in 
`service_email_reply_to`. However services that do not, still need an entry in this new table if their `reply_to_email_address` has been set. 
This adds a command that will do that. There are two key rules:
1. If the `reply_to_email_address` is `NULL` for a service, we do not want to create an entry
2. If an entry already exists for a service in `service_email_reply_to`, don't populate the new table as  it's already there
**UPDATE: Rebased off master**

[3/5] Migrate existing data to new service_email_reply_to table

---

app/dao/service_sms_sender_dao.py
app/dao/services_dao.py
app/inbound_number/rest.py
app/schemas.py
app/service/rest.py
tests/app/dao/test_service_sms_sender_dao.py
tests/app/inbound_number/test_rest.py
tests/app/service/test_rest.py

In order to allow multiple SMS senders for a service we want to store those numbers in a new table, SERVICE_SMS_SENDERS. Which was created in a previous PR. 
In this PR we are inserting or updating the SMS sender to the new table anytime the Service.sms_sender is updated or inserted and any time the InboundSms is updated or added for a service. This will ensure the data is up to date in both places.

Insert or update service sms senders

---

app/dao/service_email_reply_to_dao.py
app/models.py
app/service/rest.py
tests/app/dao/test_service_email_reply_to_dao.py
tests/app/db.py
tests/app/service/test_rest.py

- Changed the dao_get_reply_to_by_service_id method to return a list of
results.
- Added a GET /service/<service_id>/email-reply-to endpoint

Add multiple reply to email endpoints

---

app/celery/scheduled_tasks.py
app/config.py
app/letters/rest.py
app/v2/notifications/post_notifications.py
tests/app/celery/test_scheduled_tasks.py
tests/app/letters/test_send_letter_jobs.py

the tasks (on the ftp app) do the same thing, but to improve clarity i've renamed it to jobs, because we'll be adding a notifications one soon

use new send-jobs-to-dvla task instead of send-files-to-dvla

---

app/models.py
tests/app/conftest.py
tests/app/v2/notifications/test_get_notifications.py

> For get all or get one letter the response needs to be updated so that it looks similar to admin app.
>
> status: created|sending --> received letter
> new column: `estimated delivery date`: derived from created at date. (see how the admin app is doing it)
>
– https://www.pivotaltracker.com/story/show/150512525
This commit implements the date (not status) part of this story.
***
Depends on:

Return delivery estimate for letter notifications

---

requirements.txt

six is used for Python 2/3 compatibility. We never run under Python 2.
Closes #1260

Remove six dependency

---

app/delivery/send_to_providers.py
app/models.py
app/schemas.py
tests/app/delivery/test_send_to_providers.py
tests/app/service/test_rest.py
tests/app/test_model.py

Stop using Service.reply_to_email_address, instead use the default reply to email address from the Service_reply_to_email table.

Use reply to email address from new table

---

scripts/run_tests.sh
tests/app/celery/test_tasks.py
tests/app/conftest.py
tests/app/job/test_rest.py

previously they were using sample_service fixture under the hood, but with full permissions added - this works fine, **unless** there's already a service with the name "sample service" in the database. This can happen for two reasons:
* A previous test didn't tear down correctly
* This test already invoked the sample_service fixture somehow
If this happens, we just return the existing service, without modifying its values - values that we might change in tests, such as research mode or letters permissions.
In the future, we'll have to be vigilant! and aware! and careful! to not use sample_service if we're doing tests involving letters, since they create a service with a different name now

update letter tests to use correct service

---

app/models.py
app/organisation/organisation_schema.py
migrations/versions/0121_nullable_logos.py
tests/app/dao/test_organisations_dao.py
tests/app/organisation/test_rest.py

Now we have the org banner branding, not all organisations need a logo. So it shouldn’t be an error to not provide one.

Make organisation logo nullable

---

app/delivery/send_to_providers.py
tests/app/delivery/test_send_to_providers.py

Code was not expecting logo to be `None`, thereby causing the task to throw an exception, and retry until eventually putting the email in technical error (for services with org branding but no logo).

Fix sending emails with no logo

---

app/dao/inbound_numbers_dao.py
app/inbound_number/rest.py
app/models.py
tests/app/dao/test_inbound_numbers_dao.py
tests/app/inbound_number/test_rest.py

- Add new endpoint to get available inbound number.
- Add new endpoint to allocate a specific number to a given service.
This will allow the platform admin user to choose a number when setting the inbound_sms permission for a service.

Select an inbound number for a service

---

app/authentication/auth.py
app/config.py
tests/app/authentication/test_authentication.py
tests/app/notifications/rest/test_callbacks.py
tests/app/notifications/test_receive_notification.py

**Why**
Secure inbound sms by IP whitelisting the sms providers' address 
**What's new**
Previously we have monitored the inbound sms traffic. In this update we enable blocking using the whitelist.  Also update the tests to include this additional header that we check. 
**Pivotal story**
146688097

Enable Inbound sms IP blocking

---

app/aws/s3.py
app/celery/scheduled_tasks.py
app/celery/tasks.py
app/config.py
app/dao/notifications_dao.py
app/notifications/process_letter_notifications.py
app/notifications/process_notifications.py
app/v2/notifications/post_notifications.py
tests/app/aws/test_s3.py
tests/app/celery/test_ftp_update_tasks.py
tests/app/celery/test_scheduled_tasks.py
tests/app/celery/test_tasks.py
tests/app/dao/notification_dao/test_letter_api_notification_dao.py
tests/app/dao/notification_dao/test_notification_dao.py
tests/app/db.py
tests/app/notifications/test_process_letter_notifications.py
tests/app/v2/notifications/test_post_letter_notifications.py

Sorry it's a bit of a beast!
* No longer create a job
* If test/research mode, create the notification with status `sending`, and then trigger `update-notifications-to-sent-to-dvla`
* Runs at 5:40 (`run-letter-jobs runs` is at 5:30)
* gets all notifications that:
- are letters
- that were sent via the api
- using a normal (live) api key
- that are in status `created`
* sets those notifications to status `pending` to prevent sending twice if the task is triggered twice
* converts these notifications to dvla pipe file format, and concatenates them into one big file
* upload that to a new s3 bucket, `{}-dvla-letter-api-files` (https://github.com/alphagov/notifications-aws/pull/235), with the filename `{ISO_TIMESTAMP}-dvla-notifications.txt`
* tells the FTP app to send the notifications to …

Letter api not by job

---

app/dao/service_letter_contact_dao.py
app/service/rest.py
tests/app/dao/test_service_letter_contact_dao.py
tests/app/service/test_rest.py

This upserts into the `ServiceLetterContact` table when updating a service as well as preserving the existing update to `Service.letter_contact_block`
1. This adds an 'upsert' dao method to insert or update in the new table when a service updates their letter contact block
2. This takes some of the code used in #1258 to manage defaults effectively. In short, when adding a `ServiceLetterContact` we want to ensure that there is only ever one entry that is the current default (`.is_default = True`).
3. When updating a service via the endpoint, this will call the DAO method from 1.
Pivotal Story: https://www.pivotaltracker.com/story/show/151287398

[2/4] Upsert into ServiceLetterContact table when updating a service

---

app/models.py
tests/app/conftest.py
tests/app/v2/template/test_get_template.py

> Currently when retrieving a template via one of the clients, we do not return the personalisation fields that are required for that template.
>
> This is useful for services who want to perform template validation on their own systems. A service user has also requested this.
– https://www.pivotaltracker.com/story/show/150674476
This commit adds an extra attribute to the JSON response containing an array of the placeholder names. This key is called "personalisation", to match the argument that developers use to pass in the values of placeholders.

Return placeholders when getting a template

---

app/commands.py
application.py

This adds a command to populate the new `service_letter_contacts` from existing data pulled from `Service.letter_contact_block` for each service.
Conditions:
1. Only create a record if `Service.letter_contact_block` actually has something
2. service_letter_contacts hasn't already been populated for the service

[3/4] - Populate service_letter_contacts from existing data

---

app/dao/services_dao.py
app/service/rest.py
tests/app/service/test_rest.py

**Why**
This is to reverse part of the pull request in #1506. Passing trial_mode_service parameter requires joining the service schema, which creates extra delay in loading the data.
#1506
**Change**
Do not pass trial_mode_service to api.
**Pivotal Story**
Platform Admin performance issue
#151371820

admin to api not passing trial_mode_service 

---

runtime.txt

Updated from Python 3.5.2 to Python 3.5.4
See https://github.com/cloudfoundry/python-buildpack/commit/40995d807b5cab59a840ed2278a904af13aab3c7

Update runtime Python version to 3.5.4

---

app/celery/tasks.py
app/models.py
app/schemas.py
app/service/rest.py
tests/app/celery/test_tasks.py
tests/app/conftest.py
tests/app/test_model.py

_Note: This was branched off from https://github.com/alphagov/notifications-api/pull/1277 and will be rebased off master once that's merged._
This uses the new table to retrieve the default letter contact for a service and updates the schema to return the default letter contact from the new table or `None`.

[4/4] Use letter contact from the new table

---

requirements.txt

Version 1.11.1 seems to be
[broken](https://bitbucket.org/cffi/cffi/issues?status=new&status=open)
It's pulled in because of [Flask-bcrypt](https://github.com/alphagov/notifications-api/blob/master/requirements.txt#L4)
which [depends on bcrypt](https://github.com/maxcountryman/flask-bcrypt/blob/master/setup.py#L33) which
[asks for a version of cffi >= 1.1](https://github.com/pyca/bcrypt/blob/master/setup.py#L12)

Pin to a specific version of cffi

---

app/inbound_number/rest.py
app/models.py
app/schemas.py
tests/app/celery/test_ftp_update_tasks.py
tests/app/db.py
tests/app/delivery/test_send_to_providers.py
tests/app/inbound_number/test_rest.py
tests/app/test_model.py

Created a get_default_sms_sender method, which returns the default sms_sender from the service_sms_sender table rather than service.sms_sender.
One step closer to removing services.sms_sender.
**Pivotal Story:**
https://www.pivotaltracker.com/story/show/150880948

Return service_sms_sender

---

app/dao/notifications_dao.py
app/notifications/process_notifications.py
app/notifications/validators.py
app/v2/notifications/post_notifications.py
tests/app/dao/notification_dao/test_notification_dao.py
tests/app/notifications/test_process_notification.py
tests/app/notifications/test_validators.py
tests/app/v2/notifications/test_post_notifications.py

- Added a DAO to add the mapping between notification and reply to email to the database so that they can be linked
- Added a validator to check that the email_reply_to.id which was sent in the form exists in the database and returns  error 400 if it does not so we only add id which have been added
- Persisted the mapping if the email_reply_to.id is valid
- dded tests to test the functionality

Task 3 - Allow API calls to specify the reply address option

---

app/delivery/send_to_providers.py
tests/app/db.py
tests/app/delivery/test_send_to_providers.py

- Updated send_to_providers.py to allow the email to pick up the mapped reply to address, if there is no reply to address mapped it uses the default for the service
- Added tests to test the functionality

Task 4 - Allow API calls to specify the reply address option

---

app/notifications/validators.py
app/service/send_notification.py
tests/app/service/test_send_one_off_notification.py

Insert a row for the mapping of notification to email_reply_to for one off notifications.

Add email_reply_to_id for one off notifications

---

app/celery/scheduled_tasks.py
app/dao/notifications_dao.py
tests/app/celery/test_scheduled_tasks.py
tests/app/dao/notification_dao/test_notification_dao.py

When we purge the notifications table we also need to purge any rows in the link table `notifications_email_reply_to` table as we will not be able to remove the notifications with the foreign key constraint.
Reference 
Step 5 - https://www.pivotaltracker.com/story/show/150440099

Purge notifications to email reply to rows older than 7 days

---

app/commands.py
app/models.py
app/schemas.py
app/service/rest.py
application.py
migrations/versions/0124_add_free_sms_fragment_limit.py
tests/app/conftest.py
tests/app/service/test_rest.py

Prepare the back-end so that we can store different free_sms_fragment_limit values for different organisation types for billing purposes. 
- Add new database column
- Changed schema
- Made sure the existing read and write end points work before the change in the front end
Related Stories
https://www.pivotaltracker.com/story/show/151837054
https://www.pivotaltracker.com/story/show/151176604

[#151837054] Add new column free_sms_fragment_limit in the Services table

---

app/__init__.py
app/delivery/send_to_providers.py

Research mode tasks send a request from the delivery-worker-research boxes to the api, which was failing due to 403s. Also fixed it to tech fail rather than timeout if that request fails.
TODO: solve questions
* do we need to restrict IP addresses here?
- if so, how do we ensure that research mode gets round this.
- if not, do we also want to restrict IP addresses for SES? Given that we don't currently, is this something we're concerned about?

Remove ip whitelist from callbacks

---

manifest-api-preview.yml
manifest-api-production.yml
manifest-api-staging.yml

This was introduced during the migration and is no longer needed nor
should it be used.

Drop api-paas.* route

---

app/commands.py
app/models.py
app/schemas.py
app/service/rest.py
application.py
migrations/versions/0124_add_free_sms_fragment_limit.py
tests/app/conftest.py
tests/app/service/test_rest.py

Reverts alphagov/notifications-api#1314, which reverts #1305. 
This is due to a temporary failure on PaaS on unbinding apps. 
The description on the PR is in #1305.

Revert "Revert "[#151837054] Add new column free_sms_fragment_limit in the Services table""

---

app/delivery/send_to_providers.py
requirements.txt
tests/app/db.py
tests/app/delivery/test_send_to_providers.py

we allow some invalid to addresses - for example, phone numbers with spaces or brackets - in the database. This is so that users can match up their data in a format that they expect (since they passed it in). When we send SMS, we strip this formatting just before sending - but we weren't with email. This commit changes that and adds some tests.
It also adds formatting for reply_to addresses. We should never expect invalid reply_to email addresses in our data, but just in case, lets validate them here.
Also, bump requirements.txt to capture some more email validation

ensure emails are formatted before sending

---

app/celery/scheduled_tasks.py
app/celery/tasks.py
app/config.py
app/dao/notifications_dao.py
test_csv_files/multiple_letter.csv
tests/app/celery/test_scheduled_tasks.py
tests/app/celery/test_tasks.py
tests/app/dao/notification_dao/test_notification_dao.py

- Added a new task to process incomplete jobs
- Added tests to test the new task
- Updated the check for incomplete jobs method to start the new task if incomplete jobs are found.
This will effectively resume tasks which for some reason were interrupted
whilst they were being processed e.g. if the application unintentionally restarted. In some cases only some of the csv is processed, this will find the place in the csv and continue processing the job from that point and mark the job as complete.

 Process Incomplete Jobs

---

app/models.py
app/schemas.py
migrations/versions/0125_add_organisation_type.py
tests/app/service/test_rest.py

> So that we can default services to their appropriate text allowance, we need to find out what sector they're in. So let's start collecting that from teams as they create new services.
In order to work out what a team’s allowance should be, we need to know what part of government they’re from. We’re going to do this logic in the admin app and then `POST` the allowance to the API.
So all we need to do with the information that the users give us is store it against the service, so we have a record. Doesn’t need any logic doing as a result of it, doesn’t need foreign keying to the organisations table, etc.
---
https://www.pivotaltracker.com/story/show/151207049

Store organisation type against each service

---

app/celery/tasks.py
tests/app/celery/test_tasks.py

Created three new celery tasks:
* `save_sms`          (will replace `send_sms`)
* `save_email`        (will replace `send_email`)
* `save_letter`       (will replace `persist_letter`)
The difference between the new tasks and the tasks they are replacing is
that we no longer pass in the datetime as a parameter.
The code has been changed to use the new tasks, and the tests now run
against the new tasks too. The old tasks will need be removed in a separate
commit.

Add celery tasks- save_sms, save_email, save_letter

---

manifest-api-preview.yml
manifest-api-staging.yml
manifest-delivery-preview.yml
manifest-delivery-staging.yml

This should and will be moved back to the approriate manifest-base-*.yml
files when it is configured for production usage.
Related: alphagov/notifications-admin#1556

Add syslog drain service to preview and staging

---

app/dao/services_dao.py
tests/app/conftest.py
tests/app/dao/test_services_dao.py
tests/app/notifications/test_validators.py
tests/app/service/test_rest.py
tests/app/v2/notifications/test_post_notifications.py

International SMS is a mature, documented feature now. There’s no reason it shouldn’t be available to everyone. If it’s turned off by default then we’re relying on people finding it in the settings page to know that it exists (which we found in research the other week that users, who would have benefitted from having international SMS, were failing to do).
This also fixes the problem whereby users signing up for Notify with an international phone number (eg those working abroad for the Foreign and Commonwealth Office) couldn’t get through the tour because they weren’t able to send themselves the example text message (see https://www.pivotaltracker.com/story/show/150705515).

Make international text messaging on by default for new services

---

app/dao/services_dao.py
app/service/rest.py
tests/app/service/test_rest.py

The /platform-admin takes a long time, probably because the marshmallow schema used joins to the service table to return all the service data and is inefficient.
The query itself has not been improved much at all but by not using a marshmallow schema I hope to get the performance gain I am looking for.

Improve platform admin

---

app/notifications/process_notifications.py

In other places the text we use for this error message is "Missing personalisation: name, date, thing". See:
- https://github.com/alphagov/notifications-api/blob/72b108b694c76a4559be04cb51c468be8db46c57/app/template/rest.py#L125
- https://github.com/alphagov/notifications-api/blob/717c0510a3986123497d0e49dd52ae3f87d953d3/app/notifications/rest.py#L206
- https://github.com/alphagov/notifications-api/blob/05a179c6efb051de1ea70bd560d7cb6966c44ff6/app/v2/template/post_template.py#L38
For some reason this part of the codebase says "Template missing personalisation: …". This is inconsistent, and also confusing because it’s the API call that’s missing the personalisation, not the template itself. 
This commit changes the error message to be consistent with the majority of the codebase, which …

Make missing personalisation error consistent

---

app/dao/service_sms_sender_dao.py
app/service/rest.py
tests/app/dao/test_service_sms_sender_dao.py
tests/app/service/test_rest.py

This PR is to retain current behaviour when we allocate an inbound number for a service.
When a service is allocated an inbound number and they only have one SMS sender, then update that SMS sender to the inbound number.
That way they will not have more than one SMS sender and will not have to choose to use either one.

Do not create a new SMS sender when allocating an inbound number

---

app/celery/tasks.py
app/models.py
app/v2/notifications/notification_schemas.py
tests/app/celery/test_ftp_update_tasks.py
tests/app/test_model.py
tests/app/v2/notifications/test_get_notifications.py
tests/app/v2/notifications/test_notification_schemas.py

Currently letter responses are not being handled so we have no idea if a letter has been sent, this PR will update letter notifications to a `delivered` or `failed` status based on the DVLA response file.
- status returned in the response file should be either `Sent` or `Failed`
- rather than use an existing `delivered` status in the json response this will be mapped to `received` for requests. Internally we will still use `delivered` status.
https://www.pivotaltracker.com/story/show/151649162

Handle DVLA response file

---

app/dao/services_dao.py
app/service/rest.py
tests/app/dao/test_services_dao.py
tests/app/service/test_rest.py

Refactored the get_detailed_services to stop using marshmallow. 
Also removed an extra query to services.
The query has been refactored to use an outer join to services on the notifications or notification_history table.
The expectation is that this change will improve the performance of the trial/live-services pages for platform admins.

Improve get services

---

app/celery/tasks.py
app/dao/notifications_dao.py
tests/app/celery/test_ftp_update_tasks.py
tests/app/dao/notification_dao/test_notification_dao.py

Update the billable units with the page count from the response file for letter notifications.

Update page count when processing response file for letters

---

app/celery/tasks.py
tests/app/celery/test_tasks.py

Instead of retrying if there are genuine errors, only retry if there are errors which are unexpected as otherwise the retries will happen and fail for the same reason e.g. that the message has changed format and will require a code update.
- Updated process_ses_results to only retry if there in an unknown exception
- Update test and assert that there is a retry there is a unknown exception

Retry in only certain scenarios

---

manifest-delivery-base.yml

This needs to go in after alphagov/notifications-aws#246
It creates a new app to handle delivery receipts which will monitor its own queue and will scale autonomously without affecting existing apps.

Add worker-receipts app

---

app/models.py
app/schemas.py
migrations/versions/0131_user_auth_types.py
tests/app/invite/test_invite_rest.py
tests/app/user/test_rest.py
tests/conftest.py

the new `auth_type` table contains `sms_auth` and `email_auth`, however, any users or invited users created with old code will default to `sms_auth` until the code is updated. (this is done using a server_default so that it ensures backwards compat.)

Add auth_type column to user and invited user

---

app/celery/tasks.py
app/commands.py
application.py
requirements.txt

- Update utils with a fix for address formats for letters. 
- Added a command to re-run the build_dvla_file for a given job id.  
There was an instance where the file failed to create because the address in the personalisation had punctuation which caused the address lines to merge into one.
Utils has been updated to fix that problem, this task will allow us to re-run the task so that the notifications can be sent.

Update utils with a bug fix for addresses in LetterDVLA template

---

app/dao/notifications_dao.py
app/dao/services_dao.py
app/delivery/send_to_providers.py
app/notifications/process_notifications.py
app/notifications/validators.py
app/service/send_notification.py
app/v2/notifications/notification_schemas.py
app/v2/notifications/post_notifications.py
tests/app/dao/notification_dao/test_notification_dao.py
tests/app/db.py
tests/app/delivery/test_send_to_providers.py
tests/app/notifications/test_process_notification.py
tests/app/notifications/test_validators.py
tests/app/service/test_send_one_off_notification.py
tests/app/test_model.py
tests/app/v2/notifications/test_post_notifications.py

We have recently add the functionality to add multiple SMS senders for a service. This PR allows a service to send the SMS sender in the POST notification request, that SMS sender is then used as the sender id. At the moment only the default sender is used for a notification.
- Added an optional parameter in the form for POST /v2/notifications/sms and /service/<service_id>/send-notification to pass in the SMS sender id.
- Get the sms sender from the notification_sms_sender mapping table if that does not exist get the default sms sender to pass on to the sms provider.
- Added the notification_to_sms_sender mapping table to the purge notifications query
As part of https://www.pivotaltracker.com/story/show/152106587

SMS sender id for post notifications

---

app/celery/tasks.py

also, downgrade client returning bad status codes from `exception` to error - it's not a problem with our system so we don't want it to trip any cloudwatch alerts or anything.

always log when we send out inbound sms

---

app/delivery/send_to_providers.py
app/models.py
app/schemas.py
migrations/versions/0132_add_sms_prefix_setting.py
tests/app/db.py
tests/app/delivery/test_send_to_providers.py
tests/app/service/test_rest.py

If the service is sending messages from GOVUK, then its messages should be prefixed with the service name. Right now this logic is:
- worked out separately in the admin app and API
- isn’t aware of multiple senders
This commit moves the logic to one place (the service model). It does this in a slightly naive way, in that it only looks at the default sender, not the actual sender of the message.
In the future this will go away because we’ll move it to being a setting that’s controlled independently of the service name. But this is the first step towards that.
`service.sms_sender` has been deprecated; we should be looking at which of the service’s SMS senders is default to work out if the message has been sent from GOVUK or not (and if it has, then prefix the message with the service name). …

Work out SMS message prefixing in a way that is aware of multiple SMS senders

---

app/models.py
tests/app/dao/test_services_dao.py
tests/app/delivery/test_send_to_providers.py
tests/app/service/test_rest.py

We want new services, when they do the tour, to see how the service name they just made shows up in the messages. This is how it (should) work at the moment (although got broken because of the multiple senders stuff).
Need to do this before we do the migration now otherwise a new service could sneak in with this setting still set to `null`.
---
Depends on:

Default new services to prefixing text messages

---

migrations/versions/0133_set_services_sms_prefix.py

We want services to have control over this setting, rather than deriving it from the value of their sender. This commit does that derivation one last time, and stores it in the column, where it can be changed as and when needed.
Depends on:

Migrate prefix SMS setting to be true or false

---

app/notifications/receive_notifications.py
tests/app/notifications/test_receive_notification.py

One of our providers gives us messages with special characters escaped, ie a newline comes through as `\n`, not a literal newline. We shouldn’t be showing these backslashes to any of our users. We also have examples of real inbound messages containing `👍` and `’`, so we should continue to display these properly.
It’s a bit tricky, because the strings we get from this provider are a mixture of escape sequences (eg `\n`) and unicode characters (eg `😨`). So we have to first convert the unicode character `😨` into an escape sequence, `\U0001f628` in this example. We do this by encoding with the `raw_unicode_escape` codec:
> Latin-1 encoding with \uXXXX and \UXXXXXXXX for other code points. Existing backslashes are not escaped in any way.
– …

Fix escaping in inbound text messages from MMG

---

app/billing/billing_schemas.py

A small pull request that remove the schema check of financial_year_start as this parameter is allowed to be None

remove check to financial_year_start in schema as it can be None

---

app/__init__.py
app/dao/inbound_sms_dao.py
app/models.py
app/v2/inbound_sms/__init__.py
app/v2/inbound_sms/get_inbound_sms.py
app/v2/inbound_sms/inbound_sms_schemas.py
tests/app/conftest.py
tests/app/dao/test_inbound_sms_dao.py
tests/app/db.py
tests/app/inbound_sms/test_rest.py
tests/app/v2/inbound_sms/test_get_inbound_sms.py
tests/app/v2/inbound_sms/test_inbound_sms_schemas.py

Add endpoints for API to get `inbound_sms` information
- dates for the `inbound_sms` `created_at` and `provider_date` had to be refactored in order to pass the schema response check
- paging added for response json, `next` element will show the url value to use to fetch the next page of results, limit is set to `API_PAGE_SIZE` which is currently default to 250 in `config.py`
https://www.pivotaltracker.com/story/show/147024273

Get inbound SMS API

---

app/celery/scheduled_tasks.py
tests/app/celery/test_scheduled_tasks.py

There are some Null template_ids in the production database which was
causing a failure as the stats_template_usage_by_month has a constraint
that it should not be null. This update only adds populated template_ids
- Updated Celery task
- Add a new test to test for null template_ids and not try to add them to the stats

Handling Null template_id for monthly stats

---

app/errors.py
app/models.py
app/schemas.py
app/user/rest.py
migrations/versions/0136_user_mobile_nullable.py
tests/app/user/test_rest.py

You can set both at the same time if you want.
If not, it currently gives a message "Mobile number must be set if auth_type is set to sms_auth". idk if we want to tweak that to make it a front-end display ready error message.
Also removed `PUT /user/<id>` as it's unused on the front-end

User mobile optional

---

scripts/check_if_new_migration.py

was causing jenkins to always run DB migrations

remove trailing underscore, which is sometimes created by alembic

---

app/celery/scheduled_tasks.py
app/config.py
app/dao/services_dao.py
app/dao/stats_template_usage_by_month_dao.py
app/models.py
app/service/rest.py
tests/app/dao/test_services_dao.py
tests/app/dao/test_stats_template_usage_by_month_dao.py
tests/app/service/test_rest.py

Added a new endpoint which combines the usage of the stats table and the data from the notifications tables, instead of using all the data from the notification_history table. This should speed up the query times and improve the page performance.
- Updated to make the stats create and update function transactional as it actually wasn't committing the data to the table
- Added the get from the stats table
- Add a a method to combine the two results
- Added the endpoint

Added new endpoint to get the new template stats

---

migrations/versions/0139_migrate_sms_allowance_data.py

This PR is the same as #1389 but the migration version has been changed from 0138 to 0139. 
https://github.com/alphagov/notifications-api/pull/1389

Free sms allowance change db migration version

---

app/config.py
app/dao/services_dao.py
app/dao/stats_template_usage_by_month_dao.py
app/service/rest.py
tests/app/dao/test_services_dao.py
tests/app/dao/test_stats_template_usage_by_month_dao.py
tests/app/service/test_rest.py

The check for aggregation was too broad and hence was adding together totals based on template_id and not the unique combination of template id, month and year. The template type is needed for the UI .
- Added test to test for the failure
- Added check and a test to for template_id, month and year matches
- Celery process name did not match the task
- Added type to the rest call

 Added a template_type to the rest call and Aggregation Bug Fix

---

app/v2/notifications/get_notifications.py
app/v2/notifications/notification_schemas.py
tests/app/v2/notifications/test_get_notifications.py
tests/app/v2/notifications/test_notification_schemas.py

In order to get the functional tests to work with the v2 endpoint we need to allow it to handle the `include_jobs` argument to return all notifications including ones created by jobs.
https://www.pivotaltracker.com/story/show/152925357

Allow include jobs request param on v2 get all notifications

---

app/celery/callback_tasks.py
app/celery/research_mode_tasks.py
app/celery/tasks.py
app/delivery/send_to_providers.py
app/notifications/notifications_ses_callback.py
tests/app/celery/test_callback_tasks.py
tests/app/celery/test_provider_tasks.py
tests/app/celery/test_research_mode_tasks.py
tests/app/celery/test_tasks.py
tests/app/delivery/test_send_to_providers.py
tests/app/notifications/rest/test_callbacks.py
tests/app/notifications/test_notifications_ses_callback.py

They were trying to hit the old URL, which we removed. Now they trigger the task - the task had to be moved to `callback_tasks.py` to prevent circular imports.
Also, since the task expects a dict rather than a jsonified str payload, i had to refactor the tests and such - one part of this was making the example payloads in `research_mode_tasks.py` actual callbacks that me and @sakisv captured from real SNS notifications generated by ses simulator email addresses. 
Also, I scrubbed emails from the bounce dict logs.

Fix research mode email callbacks

---

migrations/versions/0140_sms_prefix_non_nullable.py
tests/app/conftest.py
tests/app/db.py
tests/app/service/test_rest.py

We have now:
- defaulted new services to start with this column set to `true`
- migrated all preexisting services to have either `true` or `false` set for this column
There is no way for a service to switch back from `true`/`false` to `null`.
This means that we can safely enforce a non-nullable constraint on this column now.
Depends on:

Make SMS prefix setting non-nullable

---

app/dao/services_dao.py
app/dao/stats_template_usage_by_month_dao.py
tests/app/dao/test_services_dao.py
tests/app/dao/test_stats_template_usage_by_month_dao.py

Return financial year not calendar year as the report on the admin UI is FY only and ensure double precision values are not returned from queries as the admin UI convert the number of the month to a word and this requires an int, however the 'extract' database function was returning a double precision float.
- Updated stats_template_usage_by_month_dao.py to return the results for financial year not calendar, as the report os for FY only and hence only the FY data is required
- Updated services_dao.py to ensure double precision values are converted to an int as the 'exact' function returns double precision from the database query, as the admin code requires the value for month to be an int
- Added tests for the above

Template usage stats updates for FY usage and bug fix

---

migrations/versions/0142_validate_constraints.py

Removes "NOT VALID" mark from the notifications -> template_history
foreign key constraint by validating existing records.
From postgres docs:
> This form validates a foreign key or check constraint that was
> previously created as NOT VALID, by scanning the table to ensure there
> are no rows for which the constraint is not satisfied. Nothing happens
> if the constraint is already marked valid.
> Validation can be a long process on larger tables. The value of
> separating validation from initial creation is that you can defer
> validation to less busy times, or can be used to give additional time
> to correct pre-existing errors while preventing new errors. Note also
> that validation on its own does not prevent normal write commands
> against the table while it runs.
> Validation …

Validate notifcations.template_history foreign key constraints

---

app/dao/services_dao.py
tests/app/dao/test_services_dao.py

The dao_fetch_monthly_historical_usage_by_template_for_service code wasn't being tested properly due to an bug on the test which created a notification with the same template and hence was not testing that a specific service would have a different template id.
- Fixed the bug in the test
- Update services_dao so that the service id check is made

Fixed bug in test which was passing but not testing the services_dao properly

---

app/cloudfoundry_config.py
app/config.py
app/notifications/receive_notifications.py
tests/app/notifications/test_receive_notification.py
tests/app/test_cloudfoundry_config.py

Checks authentication header value on inbound SMS requests from
Firetext against a list of allowed API keys set in the application
config.
At the moment, we're only logging the attempts without aborting the
requests. Once this is rolled out to production and we've checked
the logs we'll switch on the aborts and add the tests for 401 and 403
responses.
Pivotal: https://www.pivotaltracker.com/story/show/152964252

Add FIRETEXT_INBOUND_SMS_AUTH config variable and auth check

---

app/dao/services_dao.py
tests/app/dao/test_services_dao.py
tests/app/service/test_rest.py

- Added a check to ensure that the current date falls in between the financial year for the year supplied by the method, so that the todays stats will only be appended in that situation.
- The integration tests did test for zero return. Added a method to test for a year which has no data and also tweaked the existing tests to ensure they are testing the year more fully.
Pivotal: https://www.pivotaltracker.com/story/show/151679396

 Template usage always aggregating today's stats 

---

app/history_meta.py
app/models.py
app/schemas.py
app/template/rest.py
migrations/versions/0144_template_service_letter.py
tests/app/dao/test_templates_dao.py
tests/app/template/test_rest.py
tests/app/template/test_rest_history.py

Paired with @klssmith.
When createing a history instance of the updated object `create_history` sets attributes using `setattr`. Since SQLAlchemy model instances are Python objects they don't prevent new attributes being created by setattr, which means that if history models are missing some of the columns the attributes will still be assigned, but their values will not be persisted by SQLAlchemy since database columns for them do not exist.
To avoid this, we check that the attribute is defined on the `history_cls` and raise an error if it isn't.
This allows us to avoid duplication between Template and TemplateHistory classes and makes it easier to ensure that all columns are copied to the TemplateHistory objects.
Adds a relationship between Template models and service letter contact …

Allow letter templates to select the default contact block

---

app/models.py

reply_to requires template_type to be already set, but the order
of attribute assignment is not defined when a model object is created
from a dictionary. This changes the test to use an OrderedDict instead.
The problem might still exist when the template is created through the
API, so this is a temporary fix to unblock the release.

Fix an intermittent test failure when creating a template with reply_to

---

migrations/versions/0144_add_notification_reply_to.py
migrations/versions/0145_add_notification_reply_to.py

This is text value of the sender_id, depending on the channel this will be a SMS sender, email reply to address or a letter contact block.
This is the first PR in a series to refactor how we send the "reply_to" the provider, eventually we can eliminate the notification_to_sms_sender and notification_to_email_to tables.

Add a column to Notifications to store the reply_to_text.

---

app/dao/templates_dao.py
tests/app/dao/test_templates_dao.py
tests/app/db.py
tests/app/template/test_rest.py
tests/app/v2/templates/test_get_templates.py

Before | After 
--- | ---
Currently templates are ordered by the newest created first. This made sense when, after creating a new template, you were landed on the page that listed all the templates. In other words, you needed to see confirmation of the thing that you’ve just done.
Since https://github.com/alphagov/notifications-admin/pull/1195 (March 2017) you get landed on the page for just that template. So you always see the template you’ve just created, no matter how the list of templates is ordered. So we are free to change the order of the templates.
Ordering by time created is not great, because it gives users no control over which templates appear first. For example, our research reported this from one team:
> One frustration they have is that when you add a new template it …

List templates in alphabetical order

---

scripts/fix_migrations.py

When generating a new migration we give it a number that increments the latest existing migration on master. This means that when there are multiple PRs open containing a migration and one of them gets merged the others need to be updated to move their migration files to apply on top of the recently merged one.
This requires renaming the file and changing migration references for both the migration revision and down_revision.
If a PR introduced more than 1 migration they all need to be updated one after another since each one needs to be renamed.
This adds a script to simplify this process. `./scripts/fix_migrations.py` will check for any branch points If it finds exactly one (which should be the common case), it asks which migration should be moved and renames / updates references to …

Add a script to fix migration ordering conflicts

---

Makefile

Rationale:
Sometimes, when deploying, we've seen errors while stopping the old
apps: "(psycopg2.ProgrammingError) permission denied for relation notifications".
When you call cf stop, it may not be entirely synchronous. Under the
hood, cloudfoundry has to do a whole bunch of things when you stop an
app - it has its own internal db of what app states are, and also has
to remove it from any load balancers etc, and also it has to actually
stop the app. We're not sure if the `cf stop` command guarantees that
your process has already terminated by the time that the command
returns.
In our Makefile, we call `cf stop`, followed by `cf delete`. One
posisble theory is that the process is still running when `cf stop`
exits, and then `cf delete` unbinds that service from the database,
removing all …

remove cf stop to try and improve deploy robustness

---

app/notifications/receive_notifications.py
tests/app/notifications/test_receive_notification.py

Switches on authentication checks for Firetext inbound SMS callbacks.
This should only be released once Firetext callback URLs have been
updated with authentication details.

Abort unauthenticated requests for Firetext inbound SMS

---

Makefile

sleep for 10 seconds to try and make sure that all worker threads (either web api or celery) have finished before we delete when we delete the DB is unbound from the app, which can cause "permission denied for relation" psycopg2 errors.

Add sleep after stopping the old app instances on deploy

---

app/celery/callback_tasks.py
app/celery/tasks.py
tests/app/celery/test_tasks.py

This causes an issue when it hits the max retry limit, and tries to throw your exception to let you deal with it - at this point it was moaning because we pass in a string
if it's not defined, and we're inside an exception block celery grabs the exc itself.

celery.task.retry exc param should be a throwable.

---

app/commands.py
requirements.txt
tests/app/test_commands.py

Some small tweaks I did while waiting for jenkins - click has type validation and coercion built in so we can remove some of the checking and stuff we wrote ourselves.
```
[leohemsted:~/dev/api]$ flask command create_provider_rates --help
Usage: flask command create_provider_rates [OPTIONS]
Backfill rates for a given provider
Options:
-p, --provider_name [mmg|firetext|ses]
[required]
-c, --cost FLOAT                Cost (pence) per message including decimals
[required]
-d, --valid_from DATE           [required]
--help                          Show this message and exit.
[leohemsted:~/dev/api]$ flask command create_provider_rates -p ses -c 1.234 -d invalid
Usage: flask command create_provider_rates [OPTIONS]
Error: Invalid value for "-d" / "--valid_from": Could not parse datetime string …
```

Click tweaks

---

manifest-api-staging.yml

Increased Gunicorn threads to 10 on staging to test if there is a
performance increase when testing request per second. Increased to 10.
Gunicorn recommend 2 x cores + 1 however on PaaS the number of cores
is not consistent.

Increased Gunicorn threads

---

manifest-api-staging.yml

Increasing the Gunicorn workers to 10 actually made the API decrease
in performance from ~200 requests/sec with with 20 API instances to
150 requests per/sec. The base value is 5 so this is to test how the API
performs with a slight increase.

Decreased Gunicorn threads

---

app/models.py
migrations/versions/0147_drop_mapping_tables.py

We no longer need them because we record the text value of the sender on the notification.

Drop the Notification to sender mapping tables.

---

requirements.txt

Previously, making nice quotes for 250 8400-character notifications took `34.42` seconds, resulting in a 502. 😢 
Now it takes `2.99` seconds 🎉 🔥 🔥 🔥 💨 
note: this requires adding smartypants as a line in requirements.txt, due to it coming from a git repo. Once the new version of smartypants is in pypi, this line will no longer be required.

update utils to 23.2.0

---

app/history_meta.py
tests/app/template/test_rest.py

`create_history` used to initialise an empty model instance and assign attributes to it one by one. Assigned attributes are collected by iterating over internal state of the modified record and stored in a dictionary, so the order in which they are set on the history instance is undefined.
This works fine for most model instances, but recent changes to the Template models require `template_type` to be set before `reply_to`, otherwise Template doesn't know which column to use to persist the `reply_to` value.
This means that we need to order the attributes when they're being assigned. We achieved this by defining a constructor for Template objects that assigns `template_type` first.
In order to make it work with `create_history` we replace individual `setattr` calls with a single call to …

Use model constructors when creating history instances

---

scripts/run_app_paas.sh

The logs agent would complain for the missing gunicorn error log file.

Touch log files in the initialization

---

app/config.py
manifest-api-staging.yml

- Reverted the Gunicorn worker number to 5 (this should be investigated further on a well baselined system to compare)
- Enabled REDIS
- Increased the rate limit to 400 req/sec as using early testing yesterday 450+ was being achieved so brings it more inline with what can be acheived

Revert changes to staging for performance tests and increased rate limit

---

app/billing/rest.py
app/commands.py
app/dao/annual_billing_dao.py
app/dao/services_dao.py
app/models.py
app/schemas.py
app/service/rest.py
tests/app/billing/test_billing.py
tests/app/conftest.py
tests/app/dao/test_annual_billing_dao.py
tests/app/dao/test_services_dao.py
tests/app/db.py
tests/app/service/test_rest.py

👋 
You still pass them in when you create a service - because the list of how many each type of org (local, nhs, central) get is stored on admin. But we don't update.
This needs to be merged before https://github.com/alphagov/notifications-api/pull/1458

Bye bye free fragments

---

app/celery/tasks.py
tests/app/celery/test_tasks.py

Currently incomplete letter jobs will never be called as the argument passed to `job_complete` is `template` rather than the expected `template.template_type`

Fixed processing of incomplete letter jobs

---

requirements.txt

The latest version of html5lib breaks bleach which is used in notification utils. 
In order to fix this we have pinned html5lib to the last working version - 1.0b10

Update requirements to fix html5lib issue

---

app/celery/scheduled_tasks.py
app/dao/notifications_dao.py
tests/app/dao/notification_dao/test_notification_dao.py

As part of the pivotal story of https://www.pivotaltracker.com/story/show/153087419
We should also send delivery status from calling scheduled timeout tasks as it is one of the final status update place.

modified dao_timeout_notifications

---

app/aws/s3.py
app/celery/letters_pdf_tasks.py
app/celery/tasks.py
app/config.py
app/dao/notifications_dao.py
app/models.py
app/v2/notifications/post_notifications.py
tests/app/celery/test_letters_pdf_tasks.py
tests/app/celery/test_tasks.py
tests/app/conftest.py
tests/app/dao/notification_dao/test_letter_api_notification_dao.py
tests/app/test_config.py
tests/app/v2/notifications/test_post_letter_notifications.py

- Added a task to create a cmyk pdf and store this in the letters-pdf bucket on s3.
- Only allow this for services that have `letters_as_pdf` set
- Ensure that for these services the `build_dvla_file` is not called so that DVLA only get pdfs or csv files to process.
- Ensure that letter notifications API calls the create letters pdf task when in `letters_as_pdf` service
- Make sure that only notifications not in `letters_as_pdf` services are processed for api calls that are building dvla files.
- From admin settings, switch a service to send letters as pdf
- then from a letter template upload a csv file
- you should be able to see the newly created CMYK files on the s3 bucket for that environment
- or from celery logs you should be able to see something like this -
`PDF Letter [noti id] …

Add letters pdf task & api

---

app/cloudfoundry_config.py
app/config.py
manifest-delivery-base.yml
manifest-delivery-preview.yml
manifest-delivery-staging.yml
tests/app/test_cloudfoundry_config.py

In order for the different environments on paas to pick up the template preview host url and key we need to put it in a cf config file.

Add template preview host url and key to cf config

---

app/config.py
manifest-delivery-base.yml

create-letter-jobs celery was not being called on the celery delivery-worker app because it wasn't configured to look on that queue, this PR should correct that bug.

Add create-letters-pdf-tasks to notify-delivery-worker

---

Makefile
scripts/run_app_paas.sh

we saw an issue where the app started, then immediately crashed due to a setup error. However, jenkins had already returned positively, and the deploy continued.
cf-deploy should fail if the app doesn't start up.
We do this by looking through the cloudfoundry events, and aborting if there are any `app.crash` events for the new GUID.

if apps crash on startup, then fail deploy process

---

app/config.py

Create letters PDF needs to be name matching the `manifest-base-delivery.yml` otherwise the delivery worker will not pick up the queue to process the task

Create letters pdf queue was renamed with tasks, but was lost in another merge

---

app/celery/letters_pdf_tasks.py
tests/app/celery/test_letters_pdf_tasks.py

As we have access to the page count from the template preview service print.pdf endpoint, we should be able to update the billable units using this information after uploading the file to the s3 bucket. 
A billable letter unit is counted per sheet which consists of 2 pages, so to calculate it I use this calculation - 
`billable_units = celiing( page count / 2 )`
| page count | billable_units |
|------------|----------------|
| 1          | 1              |
| 2          | 1              |
| 3          | 2              |
| 4          | 2              |
Step 5/5 - https://www.pivotaltracker.com/story/show/151511579

Update billable units for letters pdf task

---

app/cloudfoundry_config.py
app/config.py
app/notifications/receive_notifications.py
tests/app/notifications/test_receive_notification.py
tests/app/test_cloudfoundry_config.py

Checks authentication header value on inbound SMS requests from
MMG  against a list of allowed API keys set in the application
config.
At the moment, we're only logging the attempts without aborting the
requests. Once this is rolled out to production and we've checked
the logs we'll switch on the aborts and add the tests for 401 and 403
responses.
This work has already been done for Firetext in a previous PR:
https://github.com/alphagov/notifications-api/pull/1409
Paired with @venusbb 
To be merged after deploying new env variables

Add MMG_INBOUND_SMS_AUTH config variable and auth check

---

app/invite/rest.py
tests/app/invite/test_invite_rest.py

If someone receives an invitation email for Notify, the reply-to address
of the email was the GOV.UK Notify email address. This has been changed
to be the email address of the user who sent the invite.
Pivotal story: https://www.pivotaltracker.com/story/show/153094646
Paired with @allait

Change reply to address for invitation emails to be invitation sender

---

tests/test_manifest_delivery_base.py

Make sure that the defined queue names in `config.py / QueueNames` are also added in the `manifest-delivery-base.yml` file so that the queues are listened on by workers and that there are no spaces that would cause problems in PaaS.

Add test for manifest-delivery-base.yml

---

app/celery/tasks.py
app/models.py
app/notifications/validators.py
app/service/send_notification.py
app/template/rest.py
app/v2/notifications/post_notifications.py
tests/app/celery/test_tasks.py
tests/app/db.py
tests/app/notifications/test_validators.py
tests/app/service/test_send_one_off_notification.py
tests/app/template/test_rest.py
tests/app/v2/notifications/test_post_notifications.py

Validators check that service_letter_contact_id belongs to the same service as the notification/template.
Generic reply_to validator calls the correct function for the given type (for either notification or template). It can be used by the template API endpoints to verify that given reply_to ID has the same service_id as the template itself.
The original approach was to create a DB foreign key constraint, but this caused issues with the `version_class` decorator saving related Service objects without creating a history record.
Checks that email/sms/letter reply to object has the same service_id as the template it's being attached to, to make sure it's not possible to retrieve data about return addresses for other services.
Returns either template's reply_to text if set or the related …

Notification reply to text from template

---

app/notifications/receive_notifications.py
tests/app/notifications/test_receive_notification.py

MMG has sent us a set of auth tokens. It has been tested and we can now turn the blocking on. 
This is part of the last task in 
Pivotal: https://www.pivotaltracker.com/story/show/152964252

Enable MMG inbound sms blocking based on bearer tokens

---

app/__init__.py
app/authentication/auth.py
tests/app/authentication/test_authentication.py
tests/app/notifications/test_receive_notification.py

We are using basic auth instead of inbound whitelist. So retiring this old code
pivotal: https://www.pivotaltracker.com/story/show/152964252

remove ip whitelist inbound sms codes

---

app/authentication/auth.py
app/v2/errors.py
tests/__init__.py
tests/app/authentication/test_authentication.py

(will help with tracking down client problems)
We currently don't log anything - but it'll be useful to see if services are getting lots of invalid system clock, or key expired, etc etc.

log auth errors from the v2 api

---

app/config.py

Use production in bucket name rather than live to keep it consistent with latest buckets

Change live-letters-pdf to production-letters-pdf

---

app/celery/letters_pdf_tasks.py
app/config.py
tests/app/celery/test_letters_pdf_tasks.py

add collate-letter-pdfs task (name pending). This retrieves a list of
letter pdf files (just the metadata, not the actual data) from s3, and
loops through them, calling the ftp task zip-and-send-letter-pdfs. It
groups them up by adding them to lists while counting the total
filesize, if it gets over a certain filesize (currently set to 500mb)
it breaks at that chunk, sends off that list of files to the ftp app,
and then starts building up a new list.
DVLA have a hard 2gb limit on how big the zip files we can send is -
however we're going to be limited by the amount of memory on the ftp
app well before we get around to handling 2gb of pdf data - so the
limit is 500mb for now. We'll adjust it after we see how ftp performs.

add collate-letter-pdfs task

---

requirements.txt

Enable Markdown links in emails

---

app/models.py
app/service/send_notification.py
app/v2/notifications/post_notifications.py
tests/app/celery/test_tasks.py
tests/app/service/test_send_one_off_notification.py
tests/app/v2/notifications/test_post_notifications.py

Pivotal story: https://www.pivotaltracker.com/story/show/153140515
Branched off #1500
Replaces 0 with 44 in UK SMS sender number to make it possible to respond to the SMS from an international number.
We've tested this and both iOS and Android join the new `+44...` incoming messages with existing `0...` conversation threads, so we're applying this change to all outgoing messages that use a UK phone number as sms_sender.
Paired with @klssmith

Set SMS sender to international format

---

app/celery/tasks.py
tests/app/celery/test_ftp_update_tasks.py

This has been removed because the services only see one status.
Pivotal story: https://www.pivotaltracker.com/story/show/153674962
Paired with @allait

Remove the delivery receipt callback for letters

---

migrations/versions/0156_set_temp_letter_contact.py

Migration script to update the templates and templates_history (latest version only) with the service default letter contact block.

Migration script for setting a default on the template. 

---

migrations/versions/0157_add_rate_limit_to_service.py

The API rate limit will be removed from the config and added to each Service.
This will allow the rate_limit to be changed for individual services (in rare cases).
Pivotal story: https://www.pivotaltracker.com/story/show/153992529

Add rate_limit column to service model

---

app/dao/templates_dao.py
app/template/rest.py
tests/app/celery/test_tasks.py
tests/app/dao/test_templates_dao.py
tests/app/template/test_rest.py

It seems selecting the service_letter_contact in the validation method was causing SQLAlchemy to persist the object. When the dao was called to save the object nothing was different so we didn't persist the history object.
It may be time to take another look at how we version. :(

Fix the template history when updating the reply_to for a template.

---

app/config.py
app/models.py
app/notifications/validators.py
tests/app/notifications/test_validators.py
tests/app/service/test_rest.py

PR #1550 added the rate_limit column to the Service table.
This PR removes the rate limits from the config and uses rate_limit from
the Service model instead. Rate limits are still separated into 'team',
'normal' and 'test', but these values are the same for a service.
Pivotal story https://www.pivotaltracker.com/story/show/153992529
Paired with @leohemsted

Get rate limit from service.rate_limit column (not config)

---

migrations/versions/0158_remove_rate_limit_default.py

The default for the rate_limit column in the services and
services_history model is now set in the model, so we can remove the
default from the database.
Pivotal story: https://www.pivotaltracker.com/story/show/153992529
Paired with @leohemsted

Drop rate limit database default

---

app/notifications/validators.py
tests/app/notifications/test_validators.py

Previously, if the SMS recipient was None there would be a 500 error
with no message displayed to the user. We now check if the recipient is
None and raise a BadRequestError if this is the case.

Add validation to check that sms recipient is not None

---

app/aws/s3.py
app/celery/scheduled_tasks.py
tests/app/aws/test_s3.py
tests/app/celery/test_scheduled_tasks.py

A small task to fix a typo error in schedule_task to compare zip files
Modified unit test to be more robust
Related to this PR
https://github.com/alphagov/notifications-api/pull/1567

Fix a typo error on task argument

---

app/__init__.py
app/celery/scheduled_tasks.py
app/config.py
manifest-api-base.yml
manifest-delivery-base.yml
requirements.txt
tests/app/celery/test_scheduled_tasks.py

Deskpro client is used to create tickets from celery alerting tasks (eg alerts for missing ack or response files from DVLA).
We should receive a response file from DVLA by 4pm the next working day (next Monday for letters created on Friday, Saturday or Sunday).
Response file triggers a task to update the letters status from 'sending' to either 'failed' or 'delivered', at which point there should be no letter notifications in the 'sending' state for that day.
To catch any errors in the process (eg a missing response file from DVLA) we add a scheduled task that checks letter notifications for previous day (or Friday when run on Monday) and raises a Deskpro ticket if it finds any in a 'sending' state. The task runs at 4:30pm, which should give the response file processing task enough time to …

Add a celery scheduled task to alert if letters are still sending

---

app/celery/scheduled_tasks.py
tests/app/celery/test_scheduled_tasks.py

Since preview and staging environments don't have a full DVLA integration they're likely to contain letter notifications in a 'sending' state. To avoid spamming Deskpro we skip the check unless we're in a production or test environment.

Disable Deskpro letters still sending alert in preview and staging

---

migrations/versions/0159_add_historical_redact.py

Will specifically affect the email auth template, which was seeded without a matching row in the `template_redacted` table.
Effectively re-runs c24edcf38825c694fdc14e5a8e3888f136650506
> add historical redaction data
>
> every current template gets a row in the template_redacted table - this inserts one for any template that doesn't already have a row, with redact set to false, the user set to NOTIFY_USER since it was just a script, and the updated_at set to the time the script is run

Backfill redaction for pre-seeded templates

---

app/aws/s3.py
app/celery/scheduled_tasks.py
tests/app/celery/test_scheduled_tasks.py

This work is a continuation from 
https://github.com/alphagov/notifications-api/pull/1567  and
https://github.com/alphagov/notifications-api/pull/1578
https://github.com/alphagov/notifications-ftp/pull/42
We are going to stop uploading the daily zip files created for sending to DVLA to S3. It means that we need to persists the zip information somewhere else. 
FTP is going to create a sub-folder inside today's subfolder called zips_sent. In this folder, it is a list of .ZIP.TXT that contains the name of the zip files and meta data of the pdf sent with that zip file. 
This PR changes the processing of DVLA acknowledgement file against this new sub directory. 
- Compare the DVLA acknoledgement file against all the zip files in this sub-directory
- If there is missing zip files in the …

Process letter acknowledge file with new S3 zip file meta file structure

---

app/errors.py
app/v2/errors.py

There were some exceptions in production today where a one off message was sending a message with an invalid email address.
The admin app validation did not catch this problem. But the API did.
This PR is a small fix to catch the erorr thrown by the notifications-utils/recipient validation methods and return a 400 status rather than a 500.
This only solves the issue of the user seeing "We are experiencing technical difficulties" rather than "invalid email address"
The bug can be replicated if you enter use quotes when entering the email address.
More work needs to be done so that the admin app does the same validation as the api so the user sees a nice form validtion error rather than a 400 after clicking send.
See: https://www.pivotaltracker.com/story/show/154472625

Raise 400 for a validation error

---

app/celery/scheduled_tasks.py
tests/app/celery/test_scheduled_tasks.py

Aws s3 use this format (datetime.now(tz=pytz.utc)) when returning datetime. 
example return: datetime.datetime(2018, 1, 16, 17, 8, 17, tzinfo=tzutc())
Otherwise, we would get "can't compare offset-naive and offset-aware datetimes error".

Fix a date time format problem - need to use AWS S3 format

---

app/notifications/validators.py
app/service/send_notification.py
app/service/utils.py
tests/app/notifications/test_validators.py
tests/app/service/test_send_one_off_notification.py

The whitelist was built to help developers and designers making prototypes to do realistic usability testing of them, without having to go through the whole go live process.
These users are sending messages using the API. The whitelist wasn’t made available to users uploading spreadsheets. The users sending one off messages are similar to those uploading spreadsheets, not those using the API. Therefore they shouldn’t be able to use the whitelist to
expand the range of recipients they can send to.
Passing the argument through three methods doesn’t feel that great, but can’t think of a better way without major refactoring…
---
https://www.pivotaltracker.com/story/show/153787321

Don’t respect the whitelist for one off sending

---

app/celery/scheduled_tasks.py
tests/app/celery/test_scheduled_tasks.py

When processing ack files for letters every day, we only send alerts in production environment, not in staging and preview. 
Also Deskpro alerts include bucket names for debugging purpose.

Processing ack files only send alerts in production environment.

---

app/celery/tasks.py
app/dao/notifications_dao.py
app/notifications/notifications_letter_callback.py
tests/app/celery/test_ftp_update_tasks.py
tests/app/dao/notification_dao/test_notification_dao.py
tests/app/notifications/rest/test_callbacks.py

Response files from the DVLA in the new format will have a `.RSP.TXT` extension. In this PR we have:
- Updated the notification letter callback to ensure that files in the new format are processed.
- Changed the notification status of failed letters from `NOTIFICATION_TECHNICAL_FAILURE` to `NOTIFICATION_TEMPORARY_FAILURE`.
- We compare the page_count in the response file with the billable_units of the letter. If these don't match, we log an error.
[Pivotal story](https://www.pivotaltracker.com/story/show/151511723)
Paired with @kentsanggds

Process the new post printing response file from DVLA

---

manifest-delivery-base.yml

Tasks that are put on the notify-internal-tasks queue are notifications
sent by the notify service, including 2FA and email auth messages.
These should never be delayed by other messages in the queue.
Created a separate delivery app to consume the notify-internal-tasks
queue and only that queue.

Create a separate delivery app to consume the notify-internal-tasks

---

app/notifications/process_notifications.py
app/notifications/validators.py
app/v2/notifications/create_response.py
app/v2/notifications/post_notifications.py

Removed the performance testing statsd calls as they are no longer needed for monitoring the performance of the v2 endpoints. They were put in as a temporary measure whilst sustained performance testing was taking place.

Removed the performance testing statsd calls

---

app/config.py

Changed the time of the daily-stats-template-usage-by-month task to run at 00:05 as the query gets data for the day before 0:00, so to minimise the report being out of date run the query at 0:05.

Changed the time of the daily-stats-template-usage-by-month task to run at 00:05

---

app/aws/s3.py
app/celery/letters_pdf_tasks.py
app/celery/research_mode_tasks.py
app/celery/scheduled_tasks.py
app/celery/tasks.py
app/models.py
app/v2/notifications/post_notifications.py
tests/app/aws/test_s3.py
tests/app/celery/test_letters_pdf_tasks.py
tests/app/celery/test_research_mode_tasks.py
tests/app/celery/test_scheduled_tasks.py
tests/app/celery/test_tasks.py
tests/app/test_model.py
tests/app/v2/notifications/test_post_letter_notifications.py

In order to run letter functional tests we need to improve the way that API handles letters in research mode. I've also had to fix some bugs that I picked up during the functional tests.
- Fixed the way that the personalisation for letters is serialized so that it can serialize regardless of how it is stored
- Refactored the code so that the business logic resides in the letter task handling rather than s3 handling
- fixed ACK file handling as it was reporting random errors due to random order of sets
- added a create fake letter response file task in research mode tasks which will also trigger the dvla callback in development environment
- updated handling of letter jobs for letter pdfs to call the create response file task in preview and development environments
- updated handling of …

Refactor letter research processing for letter pdfs

---

app/v2/notifications/post_notifications.py
tests/app/v2/notifications/test_post_letter_notifications.py

task not really necessary as the status is already set to 'sending' before the task is called if it is not sending i.e. in research mode or using a test key

Remove sent to dvla task

---

app/dao/services_dao.py
tests/app/dao/test_services_dao.py
tests/app/service/test_rest.py

Letters is a mature enough feature now – and one that we’ve been talking about offering for long enough – that we shouldn’t make people dig around in the settings.
I think we’d want to wait a bit longer/indefinitely before deciding to turn it on for existing services across the platform.
---
This takes letters from 4 to 5:

Turn letters on by default for new services

---

app/dao/notifications_dao.py
tests/app/dao/notification_dao/test_notification_dao.py

if the international_billing_rates.yml has `dlr: null`, that means we don't know what delivery receipts they provide - they might not provide any. So if we do get an update, we don't know for sure that the message was actually delivered - lets not update it.

fix 500 when receiving delivery receipt from some international nums

---

app/celery/scheduled_tasks.py

The NOTIFY_ENVIRONMENT variable is set to `production` from the run_paas_app script, but that is overwritten with `live` in the create_app function when starting an application.
Although this is confusing and it would be good to resolve that. It is a larger piece of work. For now I have included booth strings in the if condition, that way when we do migrate the code we will not have an issue with these two methods.

Fix bug with sending deskpro tickets in production.

---

app/celery/research_mode_tasks.py
tests/app/celery/test_research_mode_tasks.py

When triggering a fake DVLA response file as part of the research service test when creating letter notifications, the notifications billable_unit is left at 0, so the fake dvla response should also be 0. Otherwise there will be confusing logs reporting mismatched page count and billable units which are just research ones. 
This is fairly low priority and impact as only happens on local dev and preview.

Update the dvla response data to 0 page count

---

app/__init__.py
app/celery/celery.py
requirements.txt

Updated utils to the latest version. This version of utils has less logging at info level and as such no longer prints out the celery task timing, which are useful to find out if a tasks has been called but also the timing for the task. Added an extra timing message for celery tasks so that it can be determined if the these are less frequent than the API calls and provide more useful information.

Updated utils to the latest version and add celery logging

---

app/models.py
app/schemas.py
app/service/rest.py
migrations/versions/0161_email_branding.py
tests/app/service/test_rest.py

Use a mapping table for email branding.
with `uselist=False` on the relationship we can force this to be one-to-many. Also, I've made the service_id the sole primary key of the mapping table - so we definitely won't end up with two rows for one service

Email branding mapping table

---

app/email_branding/rest.py
tests/app/email_branding/test_rest.py

the new endpoint `/email-branding/<id>` returns data `{'email_branding': {...}}`
the old endpoint `/organisation/<id>` should still return data `{'organisation': {...}}`

ensure old route still returns json in same shape

---

app/dao/services_dao.py
tests/app/dao/test_services_dao.py

they were not included in nightly task since that runs off NotificationHistory, which doesn't include test keys. However, when you load the page we top up the nightly stats with today's data from the Notifications table, which *does* include test data.

exclude test keys from template usage page

---

app/celery/tasks.py
app/delivery/send_to_providers.py
app/notifications/notifications_letter_callback.py
app/notifications/notifications_sms_callback.py
app/notifications/process_client_response.py
app/notifications/process_notifications.py
app/notifications/receive_notifications.py
app/notifications/rest.py
app/notifications/utils.py
app/v2/notifications/post_notifications.py

As Notify matures we probably need less logging, especially to report happy path events.
This PR is a proposal to reduce the average messages we see for a single notification from about 7 messages to 2.
Messaging would change to something like this:
February 2nd 2018, 15:39:05.885	Full delivery response from Firetext for notification: 8eda51d5-cd82-4569-bfc9-d5570cdf2126
{'status': ['0'], 'reference': ['8eda51d5-cd82-4569-bfc9-d5570cdf2126'], 'time': ['2018-02-02 15:39:01'], 'code': ['000']}
February 2nd 2018, 15:39:05.885	Firetext callback return status of 0 for reference: 8eda51d5-cd82-4569-bfc9-d5570cdf2126
February 2nd 2018, 15:38:57.727	SMS 8eda51d5-cd82-4569-bfc9-d5570cdf2126 sent to provider firetext at 2018-02-02 15:38:56.716814
February 2nd 2018, 15:38:56.727	Starting sending SMS …

Reducing the logging for the life cycle of a notification

---

manifest-delivery-base.yml

When there are high volumes of emails being processed the SES callback task will trigger the service-callback task.
This PR creates a new worker to deal with the service-callback so that one event doesn't block the other.

New worker for service-callbacks

---

app/celery/celery.py
app/config.py

Fixed typo in call, should be self.name not Task.name.
Task.name always returned None.

Fixed typo in log call so that the name of the task is returned

---

app/user/rest.py
app/user/users_schema.py
app/utils.py
tests/app/user/test_rest_verify.py

Similar to https://github.com/alphagov/notifications-api/pull/1515
This lets the admin app pass in a domain to use for email auth links, so that when it’s running on a different URL users who try to sign in will get an email auth link for the domain they sign in on, not the default admin domain for the environment in which the API is running.

Allow admin to specify domain for email auth links

---

.gitignore
app/celery/letters_pdf_tasks.py
app/variables.py
requirements.txt
tests/app/celery/test_letters_pdf_tasks.py

so we can delete them automatically with s3's lifecycle policy

upload letter pdfs with retention tag

---

requirements.txt

fix bug where we s3upload crashed if you didn't supply tags

---

tests/app/celery/test_letters_pdf_tasks.py

as it failed on prodction and I managed to get it to fail locally
in running 'for i in {1..20}; do pytest -k test_create_letters_pdf_calls_s3upload; done' I managed it to fail on my local machine however running it a second and third time it did not.
{'file_location': '2018-02-12/NOTIFY.FOO.D.2.C.N.20180212164427.PDF'}
!= {'file_location': '2018-02-12/NOTIFY.FOO.D.2.C.N.20180212164428.PDF'}
A freeze time till ensure that the filename which is based on the time will not fail.

Added a freezetime to the test test_create_letters_pdf_calls_s3upload

---

app/service/rest.py
tests/app/service/test_rest.py

Changed the `/service/unique` endpoint to optionally accept the
`service_id` parameter. It now doesn't matter if a user tries to change
the capitalization or add punctuation to their own service name. But
there should still be an error if a user tries to change the punctuation
or capitalization of another service.
`service_id` needs to be allowed to be `None` until notifications-admin is
updated to always pass it in.
[Pivotal story](https://www.pivotaltracker.com/story/show/155127026)

Allow services to add punctuation to or change the case of their name

---

app/celery/tasks.py
app/config.py
app/v2/notifications/post_notifications.py
tests/app/celery/test_tasks.py
tests/app/v2/notifications/test_post_letter_notifications.py
tests/app/v2/notifications/test_post_notifications.py

We are ready to send all letters to our provider as a PDF and not a text file that they then use to create a PDF. 
In this PR, anytime we are sending a letter it will create a PDF to use to send to the provider at the scheduled time of day.

Switch to using the pdf letter flow.

---

scripts/run_tests.sh

If a PR is going to fail because tests aren’t passing then you:
- should know about it as quick as possible
- shouldn’t waste precious Jenkins CPU running subsequent tests
This commit adds the `-maxfail=10` flag to pytest, which stops the test run once an unacceptable number of tests have failed.

Stop pytest on 10th failing test

---

app/dao/stats_template_usage_by_month_dao.py
app/schema_validation/__init__.py
app/schema_validation/definitions.py
tests/app/v2/notifications/test_notification_schemas.py

The regex to validate uuids was not rejecting uuids with a space at the end.
Switched to using a isinstance check on the string.
Added an order by clause to dao_get_template_usage_stats_by_service, it was causing an itermitten failure in the tests.

Fix UUID validate in the JSON schema

---

app/service/rest.py
tests/app/service/test_rest.py

notifications-admin has now been changed to always pass the `service_id`
to the 'service/unique' endpoint. This means we don't need to cover the
case of there being no `service_id` and the tests can also be updated.

Remove unnecessary code to do with testing service name uniqueness

---

app/models.py
migrations/versions/0167_add_precomp_letter_svc_perm.py

migration script to add precompiled_letter in service_permission_types table and also added to service permission types list in models.py
https://www.pivotaltracker.com/story/show/155323023

Add precompiled_letter service permission

---

README.md
app/config.py
pytest.ini

previously, if you had no db set it would work, but if you had the live db set in the env as SQLALCHEMY_DATABASE_URI then it'd try and use that, and error out.
no-one runs on weird setups so we can just manually set it if it's not docker.

make sure tests always run in test db

---

app/celery/celery.py
app/celery/tasks.py
app/exceptions.py
tests/app/celery/test_ftp_update_tasks.py

The Notify team needs to investigate when a notification is marked as failed.
We will process the whole file and mark the notifications with the appropriate status, if any are failed an exception is raised.
The exception will trigger a cloud watch error for the team to investigate.

Added a new exception type for DVLAException

---

app/celery/letters_pdf_tasks.py
app/dao/templates_dao.py
app/letters/utils.py
app/models.py
app/v2/notifications/notification_schemas.py
app/v2/notifications/post_notifications.py
migrations/versions/0168_hidden_templates.py
tests/app/celery/test_letters_pdf_tasks.py
tests/app/conftest.py
tests/app/dao/test_templates_dao.py
tests/app/db.py
tests/app/v2/notifications/test_post_notifications.py

Allows hiding templates from the templates list in the admin app and related API responses.
This is used for 'internal' templates that we create for notifications that wouldn't have a template otherwise (eg pre-compiled PDF letters)
Creates the column as nullable, sets the value to false for all existing templates and template versions and then applies a not-nullable constraint.
All future Templates are created with `False` as the default set in SQLAlchemy.
Adds a separate view function that is registered under the same route as existing letter POST notification.
Pre-compiled letter endpoint uploads PDF contents to S3 directly instead of creating a letter task to generate PDF using template preview.
This moves some of the utility functions used by existing letter celery tasks to …

Post pre-compiled letter PDF notification endpoint

---

migrations/versions/0168_hidden_templates.py
migrations/versions/0169_hidden_templates_nullable.py

Since the application code gets released after the migration setting
a new Template field as non-nullable prevents new templates from being
created by the existing application instances.
This splits the migration to set fields as nullable first and then
update existing records once the application code has been released.
0168 is modified not to run UPDATE query or set non-nullable flag in
staging and production. 0169 is added to rollback preview.

Set Template.hidden as nullable before the new app code gets released

---

app/dao/templates_dao.py
tests/app/conftest.py
tests/app/dao/test_templates_dao.py

Filtering out hidden templates requires all existing templates to
have `hidden` flag set, which can only be done by a migration after
the code that sets the flag to `False` by default for new templates
has been released.
This removes the filtering logic until the migration has been released.

Revert "Don't return hidden templates in API service template responses"

---

app/dao/templates_dao.py
migrations/versions/0170_hidden_non_nullable.py
tests/app/conftest.py
tests/app/dao/test_templates_dao.py

Sets hidden to false for all existing templates and makes column non-nullable.
Brings back filtering hidden templates from the API responses.

Set Templates.hidden column as non-nullable and filter hidden templates

---

app/models.py
tests/app/test_model.py

Postcodes are required for created letters, but not for precompiled, this fix allows postcodes to be None in the model.
As postcodes are still required for created letter they should be caught by validation schemas in the POST handler for created letters

Fix serialization on precompiled letter

---

requirements.txt
requirements_for_test.txt

notably, remove awscli and boto3 - they're both required by utils, and
are generating a lot of PR noise

bump requirements

---

tests/app/celery/test_letters_pdf_tasks.py
tests/app/celery/test_tasks.py

In tests `test_create_letters_pdf_handles_s3_errors` and `test_build_dvla_file_retries_if_s3_err`, was getting KeyError: 'Error' test failures
This is due to the side_effect not generating enough information to be used in the boto ClientError class, this PR adds additional missing information missing from the side_effect.

Fix boto mocks in tests

---

app/service/send_notification.py
tests/app/service/test_send_one_off_notification.py

The vast majority of messages that are being sent one-off are time-sensitive. A typical example is a caseworker on the phone who sends a message at the end of the call. They normally wait until the message has been delivered, so all the time they’re waiting is time when they can’t be helping someone else.
What we don’t want to happen is for the messages they’re sending to get stuck behind a big lump of GOV.UK Subscription emails or passport reminder texts. I think the best way to do this is shift them onto the priority queue.
We’re currently seeing queue sizes of up to 5,000 on the ‘normal’ queues; I don’t think there’s any risk of this change making the priority queue more heavily-laden than this. Especially since the
traffic patterns of users sending one-off messages won’t be spiky.

Send one-off messages as fast as possible

---

migrations/versions/0172_deprioritise_examples.py

Since we send all one off messages as priority [now](https://github.com/alphagov/notifications-api/pull/1722), we don’t need to explicitly mark the ‘Example text message template’ template as
being priority.
This commit retroactively removes the priority flag from these templates, so that they can’t be reused to send other messages as priority. I don’t think this is a real problem now, but worth cleaning this up.
This query will hit approximately 827 templates.
Depends on:

Remove priority flag from example templates

---

app/config.py

We have an issue with the provider. If we need to resend these letters, we need the notification.

Suspend the `delete-letter-notifications` scheduled job.

---

app/celery/tasks.py
app/config.py
app/dao/notifications_dao.py
tests/app/celery/test_ftp_update_tasks.py
tests/app/dao/notification_dao/test_notification_dao.py

Process responses for letters even after the notification has been deleted.
This will continue to update the notification history for letter notifications.
We currently have an issue where the responses to letters from the provider is taking a long time.
This is due to the manual nature of their process.
Updating the status of the letter will still work if the notification has been purged.
Also turned back on the purge letter notification scheduled task.

Process old letter responses

---

app/celery/scheduled_tasks.py
app/commands.py
app/performance_platform/total_sent_notifications.py
tests/app/celery/test_scheduled_tasks.py
tests/app/performance_platform/test_total_sent_notifications.py
tests/app/test_commands.py

We don’t have any way of playing back the totals we send to performance platform.
This commit copies the command used to backfill the processing time and adapts it to backfill the totals instead. Under the hood it uses the same code that we use in the scheduled tasks to update performance platform on a daily basis. I had to modify this code to take a `day` argument because it was hardcoded to only work for ‘yesterday’.

Add command to backfill Performance Platform totals

---

app/celery/tasks.py
app/dao/daily_sorted_letter_dao.py
app/models.py
migrations/versions/0173_create_daily_sorted_letter.py
tests/app/celery/test_ftp_update_tasks.py
tests/app/dao/test_daily_sorted_letter_dao.py
tests/app/db.py

In the response file from the DVLA for letters there is a column that is for `Sorted` or `Unsorted`. We created a new table, `daily_sorted_letter`, which is for storing these values per day. This table gets populated when we process the response file.
[Pivotal story](https://www.pivotaltracker.com/story/show/154395015)

Create and populate DailySortedLetter table

---

docker/Dockerfile

This is to allow us to build cffi

Install libffi-dev and python-dev in docker

---

app/template/rest.py
tests/app/template/test_rest.py

Some template preview endpoints take data and some take json. After a refactor only 'data' was being passed and hence the call where json was passed was producing an error because the content header is automatically being set based on the parameter.
* Added some logic to handle if the post requires data or json
* Added extra logging to display the error with more detail
* Added tests to ensure the correct data type is being passed to the post request

Fixed bug only where only data being passed to TemplatePreview when JSON is required

---

app/organisation/rest.py
tests/app/organisation/test_rest.py

Currently, when changing a service name, a request is made to check if the name is unique before the update request is made. This is so we can give the user good errors before they continue through the flow to verify their password and get hit by a 'name already in use' error anyway.
This PR contains the endpoint to check the organisation name choice is unique, and keep the same standard of error formatting for the user.
**Notes**
- `email_from` has been removed from the organisation expected request params. Unlike a service, it's not necessary for an organisation. In place of email_from, a check will ensure that it is not possible to enter a service name that already exists, albeit in a different case. 
- Also possible for an organisation to bypass the case check if the current identical …

Add endpoint to check for unique organisation names

---

app/celery/service_callback_tasks.py
manifest-delivery-base.yml
tests/app/celery/test_service_callback_tasks.py

We have seen problems with the service callback workers due to the db connection pool being exhausted. When the worker picks up the task, it makes a db query to get the notification, a query to get the callback url, and then closes the session before it makes the 3rd party request.
However, even closing the session before the (potentially lengthy) web request wasn't enough - we've seen significant amounts of `sqlalchemy.exc.TimeoutError`s.
This reverts commit 2dfbd93

Revert service callback eventlets

---

app/celery/service_callback_tasks.py
app/commands.py
tests/app/celery/test_service_callback_tasks.py

When we sent the service the status callback for a notification, we have all the information we need.
Which means we can remove the need to request the data from the database.
In order for the PR to be backwards compatible I have added an optional parameter "encrypted_status_update".
If this is not None then the new code is called.
The next PR will send the encrypted data to this task.
A final PR will remove the code that uses the database to get the notification and service callback api.
A new server command to replay service status updates.

Refactor service callback task

---

app/celery/scheduled_tasks.py
app/celery/tasks.py
tests/app/celery/test_scheduled_tasks.py
tests/app/celery/test_tasks.py

we might stop processing jobs mid-way through if, for example, a deploy or downscale kills the box working on it. We have a scheduled task that identifies any job that we started processing more than half an hour ago that is still processing.
However, we encountered a bug where we triggered the process_incomplete_job multiple times, because the processing_started of the job was still set to half an hour ago. If we reset the processing_started to the current time, then it won't get picked up by future runs of the check_job_status scheduled task.
process_incomplete_jobs loops through jobs processing them in a single task. This means that if the job statuses are all 'error', and then the process_incomplete_jobs task fails, the later jobs in the list that never got picked up won't have their …

Process job fix

---

app/dao/notifications_dao.py
app/service/rest.py
tests/app/dao/notification_dao/test_notification_dao.py
tests/app/service/test_rest.py

Users expect the search to work on partial email addresses ‘similar to Gov.Pay’. We can’t have a situation where Pay are doing something better than us 😜

Match on partial email addresses and phone numbers in search

---

migrations/versions/0175_drop_job_statistics_table.py

All code relating to job statistics was previously deleted in https://github.com/alphagov/notifications-api/pull/1743 and https://github.com/alphagov/notifications-api/pull/1744.
This final stage drops the job_statistics table.
[Pivotal story](https://www.pivotaltracker.com/story/show/155586436)

Migration to drop job_statistics table

---

app/template/rest.py
requirements.txt
tests/app/template/test_rest.py

Updated the notification template endpoint to extract the pdf page before sending it to template preview. This stops the whole pdf file being sent to template preview for each page which is really inefficient on network traffic and memory usage.
* Added logic to the endpoint to extract the specific page requested
* Updated tests to add a mock for the new call to utils
* Added a new test case for exceptions in the PDF extraction process

Updated the notification template endpoint to extract the pdf page

---

manifest-delivery-base.yml

This was overly optimistic that 2G would be enough to handle 4 worker
processes as they are already exhausting the 2G limit.
Depending on performance we may need to tweak the memory instead/too.

Reduce parallel worker processes to 3

---

app/celery/scheduled_tasks.py
tests/app/celery/test_scheduled_tasks.py

When the notification is timedout by the scheduled task if the service is expecting a status update, that update to the service would fail.
A test has been added.

Fix the bug in timeout notifications.

---

app/models.py
migrations/versions/0176_alter_billing_columns.py

Added a model to match the DB migration in PR notifications-api/pull/1750. This is part of the reporting story in pivotal #155511547
In this PR, 
- created the model to match the DB migration script. 
- alter some columns that should be non-nullable.

Add billing models and small alteration to billing tables (Pivotal #155511547)

---

app/celery/research_mode_tasks.py
app/celery/tasks.py
tests/app/celery/test_ftp_update_tasks.py
tests/app/celery/test_research_mode_tasks.py
tests/app/notifications/rest/test_callbacks.py

Two small updates to the `update-letter-notifications-statuses` task -
* We ensure that temporary failures are always handled, regardless of whether 
the response file we receive contains unknown Sorted statuses or not by putting
this code in a `finally` block.
* When getting the billing date from the name of the letter response file we now split
on `-` instead of `.` since the files we receive use `-` in the filename now.
This is an update to [this Pivotal story.](https://www.pivotaltracker.com/story/show/154395015)

Ensure update letter notification statuses task handles temporary failure

---

app/accept_invite/rest.py
tests/app/accept_invite/test_accept_invite_rest.py

Currently, If a malformed invite token hits the API, the server will return with a 500. This PR handles the bad tokens and returns a 400 with an error message, the same as used in malformed email login tokens.

Handle malformed invite tokens

---

app/dao/notifications_dao.py
tests/app/dao/notification_dao/test_notification_dao.py

SQLAlchemy handles escaping anything that could allow a SQL injection attack. But it doesn’t escape the characters used for wildcard searching. This is the reason we’re able to do `.like('%example%')` at all.
But we shouldn’t be letting our users search with wildcard characters, so we need to escape them. Which is what this commit does.
Documentation: https://www.postgresql.org/docs/9.0/static/functions-matching.html#FUNCTIONS-LIKE

Escape special characters in search by recipient

---

app/celery/tasks.py
app/dao/daily_sorted_letter_dao.py
app/models.py
migrations/versions/0178_add_filename.py
tests/app/celery/test_ftp_update_tasks.py
tests/app/dao/test_daily_sorted_letter_dao.py
tests/app/db.py

Handle duplicate calls to update_letter_notifications_statuses
As it turns out the SNS topic is trigger more that once when a file is placed in S3, this is caused by a bug in the s3ftp software used to mount the S3 bucket to the FTP server.
S3ftp performs the create file operation more than once. This is resulting in duplicate counts of DailySortedLetter (the counts of how many letters marked as sorted or unsorted, which affect how much the provider will charge Notify for the letter).
This PR adds a new column to DailySortedLetter called file_name. A new unique constraint on billing_day + file_name is added. Each time we write a row to the table the counts are over written rather than aggregated.
I am aware that this PR is not backwards compatable. However, since the code is typically …

Handle duplicate DVLA files

---

app/config.py
app/letters/utils.py
app/v2/notifications/post_notifications.py
requirements_for_test.txt
tests/app/celery/test_letters_pdf_tasks.py
tests/app/letters/test_letter_utils.py
tests/app/v2/notifications/test_post_letter_notifications.py

To break down this PR, you can have a look at this first - 
https://github.com/alphagov/notifications-api/pull/1772
This PR will access the PDF from the correct bucket for a preview image sent using a test API key
This is a branch off https://github.com/alphagov/notifications-api/tree/ken-upload-test_key-precompiled-to-test_letters-bucket, so should be merged after that branch has merged or can be merged in place of the merging of the parent branch.
https://www.pivotaltracker.com/story/show/155974923

Preview precompiled letters sent using an API test key

---

app/v2/notifications/post_notifications.py
tests/app/v2/notifications/test_post_notifications.py

Updated the precompiled response to only include the notification id and the client reference. It could confuse the client consumer so best to remove it from the response altogether.
* Respond with only the notification_id and client_reference
* Updated the test to check for the response without the template

Update notification response for precompiled

---

app/dao/notifications_dao.py
app/template_statistics/rest.py
tests/app/dao/notification_dao/test_notification_dao.py

We had an exception today caused by a slow running query. This PR will optimise this query to use a more efficient index.
- Add notification_type to the dao_get_last_template_usage to optimize the query.
- Tested and analyzed query on production database with very significant results.
QUERY PLAN
Limit  (cost=0.43..1711.35 rows=1 width=935) (actual time=21186.053..21186.053 rows=0 loops=1)
->  Index Scan Backward using ix_notifications_created_at on notifications  (cost=0.43..4607493.80 rows=2693 width=935) (actual time=21186.052..21186.052 rows=0 loops=1)
Filter: (((key_type)::text <> 'test'::text) AND (template_id = 'xxxxxx'::uuid))
Rows Removed by Filter: 8244071
Planning time: 0.112 ms
Execution time: 21186.082 ms
QUERY PLAN
Limit  (cost=5323.10..5323.10 rows=1 width=935)
->  Sort …

Optimise dao_get_last_template_usage query

---

manifest-delivery-base.yml

The workers are working sequentially so they don't need more than one
connection per thread.
This has been tested with the sender worker and it works fine even
under significant load, so this commit will make it the default for the
other workers as well.

Set db connection pool size to 1 for all workers

---

app/celery/provider_tasks.py
app/celery/scheduled_tasks.py
app/celery/service_callback_tasks.py
app/celery/tasks.py
app/dao/notifications_dao.py
app/delivery/send_to_providers.py
app/exceptions.py
app/notifications/notifications_ses_callback.py
app/notifications/process_client_response.py
tests/app/celery/test_ftp_update_tasks.py
tests/app/celery/test_provider_tasks.py
tests/app/celery/test_scheduled_tasks.py
tests/app/celery/test_service_callback_tasks.py
tests/app/dao/notification_dao/test_notification_dao.py
tests/app/delivery/test_send_to_providers.py
tests/app/notifications/test_notifications_ses_callback.py
tests/app/notifications/test_process_client_response.py

When a notification is timed out in the scheduled task that may happen because the notification has not been sent.
Which means the sent_at date for the notification could be empty causing the service callback to fail.
- Allow code to work if notification.sent_at or updated_at is None
- Update calls to send_delivery_status_to_service to send the data encrypted so that the task does not need to use the db.
- Throw an exception whenever we updated a notification to technical failure. If this is happening we want to know about it.

Send service callback if sent at is none

---

app/dao/services_dao.py
tests/app/service/test_rest.py

Optimise the query used to return the services and todays notification totals.
By changing the created_at filter to use a specific date range I found a significant improvement to the queries performance.
The unit test needed to change because now were are returning todays date as BST the local timezone.
Query plan before
Merge Left Join  (cost=1226133.76..1226143.77 rows=1753 width=70) (actual time=5800.160..5801.657 rows=1849 loops=1)
Merge Cond: (services.id = anon_1.service_id)
->  Sort  (cost=152.99..157.37 rows=1753 width=46) (actual time=2.205..2.631 rows=1762 loops=1)
Sort Key: services.id
Sort Method: quicksort  Memory: 224kB
->  Seq Scan on services  (cost=0.00..58.54 rows=1753 width=46) (actual time=0.011..1.156 rows=1762 loops=1)
Filter: active
Rows Removed by Filter: 101
-> …

Optimise query for platform-admin/live-services and trial-services

---

app/celery/service_callback_tasks.py
tests/app/celery/test_service_callback_tasks.py

The send_delivery_status_to_service task was refactor to take the details of the notification and service api callback such that the task no longer needed to go to the database to provide the status update.
This PR removes the code that is no longer used. This extra step was necessary to keep the tasks backward compatible.

Remove unused code in send_delivery_status_to_service task

---

app/celery/reporting_tasks.py
app/celery/scheduled_tasks.py
app/config.py
tests/app/celery/test_reporting_tasks.py

1. Add 'create-nightly-billing' task at config.py CELERY_IMPORTS to include this. 
2. Also removed retry from the task. 
3. Mark records as 'unknown' rather than randomly assign them to providers if its null.

Add import to reporting_tasks in scheduled tasks

---

app/commands.py

This PR includes a new command 'migrate-data-to-ft-billing', which takes in an argument of start_date and end_date, and migrate data from notification_history to ft_billing table day by day. 
- The command estimates how many rows are migrated for that day. 
- Insert the records by grouping data in notification_history table for the day 
- If the record already exists (defined by primary key: bst_date, template_id, notification_type, rate_multiplier, provider), we update the facts (rate, billable_unit and notifications_count) of that record.  
To test locally, type:
```
flask command migrate-data-to-ft-billing -s '2017-01-01' -e '2018-12-30'
```
This should migrate all the records in your DB locally. 
https://www.pivotaltracker.com/story/show/155511547

Command for migrating data to ft_billing [#155511547]

---

app/notifications/notifications_sms_callback.py
app/notifications/process_client_response.py
tests/app/notifications/test_process_client_response.py

Billing reports need `sent_by` to create the composite primary key and sometimes it is not set.
This PR will -
- set `sent_by` if it hasn't been set in the sms callback
- refactor argument reference to provider_reference to make it clearer
https://www.pivotaltracker.com/story/show/155943544

Set sent_by if not set during sms provider callback

---

app/celery/letters_pdf_tasks.py
app/letters/utils.py
app/v2/notifications/post_notifications.py
tests/app/celery/test_letters_pdf_tasks.py
tests/app/letters/test_letter_utils.py
tests/app/v2/notifications/test_post_letter_notifications.py

Before previewing precompiled PDFs sent with a test key we should run it pass the antivirus scan.
- precompiled PDFs sent by test key uploaded to scan bucket
- set status to `virus-scan-failed` for pdfs failing virus scan rather than `permanent-failure`
- Make call to AV app for precompiled letters sent via a test key, and set notification status to 'pending-virus-scan`
- Successful scans should set the notification to `delivered`
- Failed scans should be set to `virus-scan-failed` and deleted from the scan bucket
https://www.pivotaltracker.com/story/show/155856605

Add antivirus check on precompiled letters sent with test key

---

app/commands.py

After a notificaiton is created we create a task to create the pdf and save it to S3,
if for some reason that task does not run we are left with notifications that are not sent.
This should not happen, but if it does we have a way to continue sending the letter.

New command to create-pdf-letter task for a given notification id.

---

docker/Dockerfile

We use Python 3.5.4 in production.

Update Python version to match PaaS

---

requirements.txt

Brings in:
---
Changes: https://github.com/alphagov/notifications-utils/compare/25.1.0...54px-non-gov-branding

Update utils to fix size of non-gov logos

---

app/models.py
migrations/versions/0182_add_upload_document_perm.py

Service permission allows attaching a file to a notification API request
that gets uploaded to Document Download API.

Add a service permission for uploading documents to Document Download

---

app/celery/letters_pdf_tasks.py
app/letters/utils.py
tests/app/celery/test_letters_pdf_tasks.py
tests/app/letters/test_letter_utils.py

Added a new task to handle any error cases with the anti-virus application. If the Anti-virus app fails due to s3 errors or ClamAV so does not scan (even after retries) the file at all an error needs to be raised and the notification set to technical-failure.
Files should be moved to a 'folder' a separate one for ERROR and FAILURE.
* Added new letter task to process the error
* Added a new method to letter utils.py to move a file into an error or failure folder based on the input
* Added tests to test the task and the utils.py method

Added a new task to handle any error cases with the anti-virus

---

app/celery/provider_tasks.py
tests/app/celery/test_provider_tasks.py

Move the info message before the fetch.
Include the exception in the log message.

Update logging for provider tasks.

---

requirements.txt

Don’t show HTML entities in plain text emails

---

app/celery/reporting_tasks.py
app/commands.py
migrations/versions/0183_alter_primary_key.py
tests/app/celery/test_reporting_tasks.py

Pivotal story:  https://www.pivotaltracker.com/story/show/155511547
* now runs from n-3 to n-1 days (total 3 days) inclusively where n=today 
* now do migration day by day with commit for each day
* The day is defined with BST time rather than UTC time
* use bst time to define a day
* process specified start day to end day exclusive of the end day - to allow the command to run for just 1 day. 
* Additional print informations
* Reinsert data based into dm_datetime using 24:00:00 to defend utc_day_end so that there is  no gap in time for each bst_date
* Define primary key also using service_id column for defining a unique record

Billing database tweak and BST bug fix

---

app/__init__.py
app/authentication/auth.py
tests/app/authentication/test_authentication.py
tests/conftest.py

The main drive behind this is to allow us to enable http healthchecks on
the `/_status` endpoint. The healthcheck requests are happening directly
on the instances without going to the proxy to get the header properly
set.
In any case, endpoints like `/_status` should be generally accessible by
anything without requiring any form of authorization.
Sometimes, when a test using one of the `set_config[_values]` context managers
failed or raised an exception it would cause the context to not be able
to revert its config changes, resulting in a 'spooky action at a
distance' where random tests would start to fail for non-obvious reasons.

Revisit proxy header check

---

app/celery/letters_pdf_tasks.py
app/errors.py
tests/app/celery/test_letters_pdf_tasks.py

Before, the filename needed to be known. Added the notification id to the logging message so that
the notification can be traced through the logging system by knowing the notification id, making it easier to debug. Also changed to raise an exception so that alerts are generated. This way we should get an email to say that there has been an error.

Logging refactor to make debugging Antivirus scans easier

---

app/template/rest.py
tests/app/letters/test_letter_utils.py
tests/app/template/test_rest.py

As API only sends a one page pdf to template preview, this means that template preview has no way of knowing whether the notify tag should be hidden or not. 
So a flag needs to be sent to template preview to tell it whether or not to hide the Notify tag on the first page of a pdf.

Hide notify tag on first page

---

gunicorn_config.py
manifest-api-base.yml

At the same time, decrease the number of workers from 5 to 4.
Effect on max db connections will be the same - although with a higher
"resting" number of connections.
Before:
12 (instances) * 5 (workers) * 20 (10 permanent + 10 overflow) = 1200
After:
12 (instances) * 4 (workers) * 25 (15 permanent + 10 overflow) = 1200

Increase pool size to 15 permanent connections

---

app/v2/notifications/get_notifications.py
app/v2/notifications/notification_schemas.py
tests/app/v2/notifications/test_get_notifications.py

Update the get_notification_by_id to return a sensible message if the id is not a valid UUID.
Previously "Result not found" would be returned when the id is not a valid uuid, which does not make sense.
Now the message says "notification_id is not a valid UUID", this should be a clearer message for the client service.

Fix error message for invalid UUID

---

app/dao/notifications_dao.py
tests/app/dao/notification_dao/test_notification_dao.py

Now that we are in British Summer Time the delete notification scheduled tasks were running at 23:40, but the code expects that the task runs the following day.
Which resulted in the notifications being around for 8 days.
This PR fixes that.

Fix BST date bug

---

app/commands.py
app/config.py
app/notifications/process_notifications.py
app/template_statistics/rest.py
app/utils.py
requirements.txt
tests/app/notifications/test_process_notification.py

We've run into issues with redis expiring keys while we try and write to them - short lived redis TTLs aren't really sustainable for keys where we mutate the state. Template usage is a hash contained in redis where we increment a count keyed by template_id each time a message is sent for that template. But if the key expires, hincrby (redis command for incrementing a value in a hash) will re-create an empty hash.
This is no good, as we need the hash to be populated with the last seven days worth of data, which we then increment further. We can't tell whether the hincrby created the key, so a different approach entirely was needed:
* New redis key: `service-<service_id>-template-usage-<YYYY-MM-DD>`. Note: This YYYY-MM-DD is BTC time so it lines up nicely with ft_billing table
* Incremented …

 add new redis template usage per day key

---

app/letters/utils.py
app/v2/notifications/post_notifications.py
tests/app/letters/test_letter_utils.py
tests/app/v2/notifications/test_post_letter_notifications.py

Refactor process_letter_notification to make the code easier to read.
- Separated the logic of precompiled and template letters.
- Remove the check for research mode, research mode is not relevant to api calls. The test key is used for testing.
Refactor upload_pdf_letter to accept a precompile boolean to save a query to template.

refactor post letters

---

app/celery/scheduled_tasks.py
tests/app/celery/test_scheduled_tasks.py

We now want to wait an extra day before sending the alert that letters
are still sending.
[Pivotal story](https://www.pivotaltracker.com/story/show/155982762)

Add extra day before raising letter still sending alert

---

app/__init__.py
app/clients/document_download.py
app/config.py
app/v2/notifications/post_notifications.py
tests/app/clients/test_document_download.py
tests/app/v2/notifications/test_post_notifications.py

Allows uploading documents to the Document Download API. The client is configured with an API host and auth token. There's no need for a flag to disable the client in the test environments at the moment since the upload is only triggered by a specific payload which would only be sent with an explicit goal of using document download.
Adds support for a new personalisation value type: file upload.
File uploads are represented as a dictionary with a "file" key and a base64-encoded file data as the key's value:
``` personalisation={ 'field1': {'file': '<base64-encoded file contents>'} } ```
Post notification endpoint checks the request personalisation data looking for the file uploads in personalisation data. If any are found and the service has permissions to upload documents the files are …

Post notification with document upload

---

migrations/versions/0185_add_is_active_to_reply_tos.py

Added a new boolean column, `is_active` to the tables for the reply_to addresses:
* `service_email_reply_to`
* `service_sms_senders`
* `service_letter_contacts`
This has a database default of `True` in order to backfill the data, but
this default will be replaced with a model default and then removed later.
[Pivotal story](https://www.pivotaltracker.com/story/show/156476018)

Add is_active column for the 3 reply_to tables

---

app/celery/reporting_tasks.py
app/dao/fact_billing_dao.py
tests/app/celery/test_reporting_tasks.py
tests/app/dao/test_ft_billing_dao.py
tests/app/db.py

Refactor code in reporting_tasks to create re-usable methods. Most of the changes in this PR are for that refactor and the addition of tests for the new methods. 
New query to get billing data for a month, since we are missing todays data there is some code to get the deltas and update/insert data in ft_billing. This new code is only being called in tests. The new endpoint is still coming, but this PR is large enough to get a review and push through as is.

Use ft billing for usage page

---

app/dao/services_dao.py
tests/app/dao/test_services_dao.py

Previously, the dashboard totals on the main page and activity page were gathering counts based off all the notifications in the table. This PR filters the amount of notifications gathered so that the count is only based off the previous 7 days, inclusive of all hours on the 7th day due to only checking on day rather than hour. 
``` dao_fetch_stats_for_service ``` has an extra filter to filter out notifications with a created at older than 7 days from today.
- Test to ensure the notifications are correctly counted, notifcations with createdAts set to:
- Current time
- 7 days ago
- 7 days 2 hours ago (To ensure it checks for the entire day) 
- 8 days ago

Adjust get_service_stats to get counts for a maximum of 7 days ago

---

migrations/versions/0186_rename_is_active_columns.py

Changed the name of the `is_active` columns to `archived` in these
tables:
* `service_email_reply_to`
* `service_sms_senders`
* `service_letter_contacts`
These columns are not being used yet. We describe Templates as
'archived', so this keeps the names consistent.

Change 'is_active' column names to 'archived'

---

app/aws/s3.py
app/job/rest.py
tests/app/job/test_rest.py

All of our uploads now have the metadata about the job set on them in S3. So this commit moves to using that metadata, if it’s there, instead of the data in the body of the post request.
If the metadata isn’t there then it will fall back to looking at the data in the post body.
The aim of this is to stop the admin app having to post this data, which means that it won’t have to keep this data in the session for the while doing the file upload flow.
---
There’s a lot of whitespace changes in the tests; functional changes are in a4857c0 and 84024a9.

Read job metadata from S3 metadata

---

app/dao/service_email_reply_to_dao.py
app/dao/service_letter_contact_dao.py
app/dao/service_sms_sender_dao.py
app/errors.py
app/exceptions.py
app/models.py
app/service/rest.py
app/service/send_notification.py
tests/app/dao/test_service_email_reply_to_dao.py
tests/app/dao/test_service_letter_contact_dao.py
tests/app/dao/test_service_sms_sender_dao.py
tests/app/db.py
tests/app/service/test_rest.py
tests/app/service/test_send_one_off_notification.py
tests/app/v2/notifications/test_post_notifications.py

It should be possible to archive the three types of reply-to addresses:
* `service_email_reply_to`
* `service_sms_sender`
* `service_letter_contact`
It isn't possible to hard delete letter contacts because they are referenced by the Template table, so to keep the ways things work consistent between all notification types, we mark the reply-to addresses as archived instead.
The DAO functions to return one and all reply-to addresses now only return the non-archived ones.
Added a DAO function for each notification type which sets the reply-to address to archived. There are various edge cases that need to be accounted for:
- You shouldn't be able to archive a default reply-to address
- For SMS, you shouldn't be able to archive an inbound number
- In addition to having a default letter contact …

Allow reply-to addresses to be archived

---

app/dao/services_dao.py
tests/app/dao/test_services_dao.py

Because dates are confusing we need to fix this query once more.
The template statistics are returning 7 days inclusive, however the big numbers on the dashboard are for 8 days.
This PR fixes that.

Dates are hard to get right

---

manifest-api-base.yml

Document Download keys have been added to the PaaS environment
credentials so we can use the manifest to set them on the app
instances.

Add document-download-api environment variables to PaaS instances

---

app/template/rest.py
tests/app/template/test_rest.py

Otherwise all letters will show the current date.
Also beefed up the tests around this part of the code a bit.
Template preview will start using this date once this is merged (but it will just ignore it until then): https://github.com/alphagov/notifications-template-preview/pull/120

Pass date of letter to template preview

---

app/billing/billing_schemas.py
app/billing/rest.py
app/commands.py
app/dao/fact_billing_dao.py
app/dao/monthly_billing_dao.py
tests/app/billing/test_billing.py
tests/app/dao/test_ft_billing_dao.py

This PR adds a new endpoint to get yearly usage by month from the ft_billing table. 
If usage is requested for the current year, the deltas added to ft_billing before executing the query to fetch the data. 
There is a command to compare the results of ft_billing to monthly_billing that will give us confidence before switching to the new endpoint on the admin app.

Use ft billing for usage

---

requirements.txt

Reverts alphagov/notifications-api#1854
We've seen several notify-api instances crash since we upgraded gunicorn - wondering if it's related

Revert "Update gunicorn to 19.8.1"

---

app/commands.py
app/models.py
migrations/versions/0188_add_ft_notification_status.py

This PR adds -
- The migration to create the new `ft_notification_status` table
- The model for this table
- A command that will be used to backfill the data
[Pivotal story](https://www.pivotaltracker.com/story/show/156567738)

Add ft_notification_status table and data migration command

---

app/dao/inbound_sms_dao.py
tests/app/dao/test_inbound_sms_dao.py
tests/app/inbound_sms/test_rest.py

Inbound messages were showing if they were older than 7 days, dependant on celery beat to remove them, this PR changes the way that the stats are retrieved, filtering anything older than 7 days within the query.
``` dao_get_inbound_sms_for_service ``` has an extra filter to filter out notifications with a created at older than 7 days from today.
``` dao_count_inbound_sms_for_service ``` has an extra filter to filter out notifications with a created at older than 7 days from today.
``` dao_get_paginated_most_recent_inbound_sms_by_user_number_for_service ``` has an extra filter to filter out notifications with a created at older than 7 days from today.
- Fixed tests that weren't reliant on time to determine counts
- Tested 3 methods to ensure that inbound_sms messages outside of the 7 day …

Only get inbound messages that are a maximum of 7 days old

---

app/billing/billing_schemas.py
app/billing/rest.py
app/celery/reporting_tasks.py
app/commands.py
app/dao/fact_billing_dao.py
app/models.py
migrations/versions/0188_add_ft_notification_status.py
migrations/versions/0189_ft_billing_data_type.py
requirements.txt
requirements_for_test.txt
tests/app/billing/test_billing.py
tests/app/dao/test_ft_billing_dao.py

We found that the reporting task failed twice because of integrity constraints.
This was because the rate_multiplier was being added as 1 and 1.0 which was not resolving to the same.
This updates the table to use Integrer.
Also changed the logging for the task.
Updated the command so that we can rebuild ft_billing for all services.

Update ft_billing table to use integer data types

---

app/dao/fact_billing_dao.py
tests/app/celery/test_reporting_tasks.py
tests/app/dao/test_ft_billing_dao.py

In order to re-run the create_nightly_billing for dates in the past, we added a condition on which table is used.
This will allow us to re-run nightly billing for those 2 days where it failed.
For the majority of time the query will run on Notiifcations.

Conditional table to fetch data for billing.

---

app/celery/reporting_tasks.py
app/commands.py
tests/app/celery/test_reporting_tasks.py

Celery expects the arguments are a string or primitive data type. The create_nightly_billing task needs to convert the string to a datetime before continuing.

Convert the day_start from a string to a datetime.

---

app/billing/billing_schemas.py
app/dao/fact_billing_dao.py
app/dao/monthly_billing_dao.py
tests/app/billing/test_billing.py
tests/app/dao/test_ft_billing_dao.py
tests/app/dao/test_monthly_billing.py

- Only rebuild current month for monthly_billing if today is in the current year.
- Change the usage queries to a union so that billing_units is correct for all notification types. Removing the business logic from the schema.
- Added tests for different fragment counts, rates and sheet counts.

Refactor usage queries and stop rebuilding monthly_billing when not needed. 

---

migrations/versions/0192_drop_provider_statistics.py

The model and all other code relating to provider statistics has already been removed in https://github.com/alphagov/notifications-api/pull/1881

Add migration to drop unused provider_statistics table

---

app/models.py
migrations/versions/0193_add_ft_billing_timestamps.py

Added `created_at` and `updated_at` to the `ft_billing` table - having these
columns makes it easier to track down issues with the data in this table.
`created_at` is nullable initially, but will be changed to non-nullable
once the column is populated and the DAO etc. have been updated.

Add timestamp columns to ft_billing table

---

app/dao/fact_billing_dao.py
tests/app/dao/test_ft_billing_dao.py

To correctly select the rate for letters you need the billable_unit or page count match on the letter_rates.
A new column is added to the query to populate ft_billing which is only populated for letter.

Fix how the letter rates are selected

---

app/commands.py
app/dao/fact_billing_dao.py
app/models.py
migrations/versions/0194_ft_billing_created_at.py
tests/app/celery/test_reporting_tasks.py

`created_at` was added previously and made nullable temporarily. This
commit now populates the column, ensures that it will always have a
value, and makes `created_at` non-nullable.

 Update created_at column of ft_billing to be non-nullable 

---

app/commands.py
app/models.py
migrations/versions/0195_ft_notification_timestamps.py

Added `created_at` and `updated_at` to the `ft_notification_status` table in order
to make it easier to track down any potential issues with the data.
Also updated the command to populate the data to take `created_at` and
`updated_at` into account and to simplify the command. This can all be done in
the same commit since the table is not being used anywhere yet and can
only be populated manually.

Add created_at and updated_at columns to ft_notification_status

---

app/letters/utils.py
tests/app/letters/test_letter_utils.py

This fixes a bug where the folder name was not correctly returning the right date because date used to compare was in UTC but the datetime used for the job start time is in BST.
Units tests have been added for the affected method.

Fix BST bug

---

app/models.py
app/notifications/notifications_ses_callback.py
app/schemas.py
migrations/versions/0196_complaints_table_.py
tests/app/celery/test_process_ses_receipts_tasks.py

New complaints model to persist complaints from SES.
If a someone gets an email from one of our services and then complain about it (mark as spam or otherwise), we get a callback from SES.
The service needs to know about these complaints so they can remove that email from their mailing list.
When processing the SES callback we are now just logging the message from SES, previously we were setting the status to delivered, but this is redundant, a notification should be delivered if there is a complaint. 
In the next PR, the complaint will be persisted when the callback is received.

Handle ses complaints

---

app/models.py
migrations/versions/0196_service_contact_link.py
migrations/versions/0197_service_contact_link.py

This is going to be used for for the document download citizen landing page, a service will add a contact link e.g. https://customerservicecontactnumber.uk/dwp/ which will allow the
user to contact the sending department if there is an error or any issues with the download. This link will be shown along with the Service name.
* Added the contact link to the model
* Added db migration script to add the column to the database

Added Service contact_link column

---

app/dao/complaint_dao.py
app/notifications/notifications_ses_callback.py
tests/app/celery/test_process_ses_receipts_tasks.py
tests/app/dao/test_complaint_dao.py
tests/app/db.py
tests/app/notifications/test_notifications_ses_callback.py

When SES callback is for a complaint save that to the new complaints table.
When handling the complaint we don't want to throw an exception if the message is missing fields. Only log an exception if we are unable to tie a complaint to a notification.

Save complaints from SES 

---

app/notifications/notifications_ses_callback.py

We'd like to see what the bounce message is from SES.
If there is a bounce we update the email to failed.
However, there is more than one reason for the failed message. Adding this logging will give us more details about the failure message.
There was a bug in the code where the log message was always empty because the function to remove the email was returns None but alters the dict. This PR corrects that.

Fix logging for a bounce message

---

app/models.py
migrations/versions/0198_add_caseworking_permission.py

We want to add the option for a user to have a more restricted view of Notify.
This should be opt in/out on a per service basis, because it will be appropriate only for a minority of teams. It shouldn’t be the default because most teams (those without a lot of users or those only using the API) won’t need it.
So this commit adds it as a new service permission, which means we can roll it out:
- in prototype form initially (for doing usability testing)
- then as an opt-in service setting

Add ‘caseworking’ service permission

---

app/commands.py

Due to a bug in 2016, there are some rows without a template id. For that case use a default template id.
This has been tested on the notify-reports-db-migration. And works fine.

Small fix for migration query

---

manifest-api-base.yml
manifest-api-preview.yml
manifest-api-staging.yml
manifest-delivery-base.yml
manifest-delivery-preview.yml
manifest-delivery-staging.yml

To be merged after alphagov/notifications-aws#387 and once #1902 has been tested for a few days.
This puts the `logit-ssl-syslog-drain` service in the base manifest for both api and delivery boxes so it will be enabled for all environments.

Enable syslog drain on all environments

---

app/service/rest.py
tests/app/service/test_rest.py

Format the data for the CSV for the service notifications endpoint.
To enable the download report on the notification activity page, we need the data in the right format.

Format data for csv
