alphagov/notifications-api

app/dao/users_dao.py
app/user/rest.py
tests/app/dao/test_users_dao.py
tests/app/user/test_rest.py

As of https://github.com/alphagov/notifications-admin/pull/4000 the admin app is doing this, so we don’t need to do it here as well.

Don’t update `email_access_validated_at` on password reset

---

app/broadcast_message/broadcast_message_schema.py
app/broadcast_message/rest.py
app/models.py
tests/app/broadcast_message/test_rest.py
tests/app/v2/broadcast/test_post_broadcast.py

Depends on: https://github.com/alphagov/notifications-admin/pull/4006
The Admin app was only using this temporarily and is now using the
"areas" field instead [1], so we can delete this one.
[1]: https://github.com/alphagov/notifications-admin/pull/4006

Remove support for "areas_2" field

---

app/commands.py

Unlike broadcasts created in the Admin app, these are only expected
to have "names" and "simple_polygons" in their areas column [1].
The migration command in the Admin app [2] isn't suitable for these
broadcasts as it would try to aggregate their areas, etc.
I've put a conditional on "areas" being present (in the areas column)
so this command doesn't pick up any new custom broadcasts.
[1]: https://github.com/alphagov/notifications-api/pull/3312/commits/023a06d5fb4c20e6bf5a1c9e65b473cb376b2b6bo
[2]: https://github.com/alphagov/notifications-admin/pull/4011

Add command to migrate custom broadcast areas

---

app/celery/broadcast_message_tasks.py
tests/app/celery/test_broadcast_message_tasks.py

This is happening on the AWS side now as part of
alphagov/notifications-broadcasts-infra#267 - but we still want to keep
the zendesk ticket as it contains useful context _and_ provides
visibility to the team.

Don't raise P1 for broadcasts

---

requirements-app.txt
requirements.txt
tests/app/v2/broadcast/test_post_broadcast.py

This brings in some new polygon simplication code [1] so we need to
tweak any tests that rely on the exact number of polygons after this
operation.
[1]: https://github.com/alphagov/notifications-utils/pull/890

Bump utils to 46.0.0

---

app/models.py
tests/app/service/test_service_contact_list_rest.py

make sure timestamps returned from the api are always consistent.
The only place in models where we're serializing a BST timestamp is on the Notification.serialize_for_csv method now, which at least is a bit different as this is user-facing (it also returns a formatted human-readable notification_status for example).
see also

return contact list created_at in UTC, not BST

---

app/v2/broadcast/broadcast_schemas.py
app/v2/broadcast/post_broadcast.py
tests/app/v2/broadcast/sample_cap_xml_documents.py
tests/app/v2/broadcast/test_post_broadcast.py

Now that these are used for display on gov.uk/alerts we need to
make sure the data is being set properly. We've already found an
example where it wasn't [1]. We validate external broadcasts in
two stages: with the official CAP XML schema [2] and then again
with our own, more specific schema for the converted JSON. Since
this validation is a custom requirement I've made it part of the
JSON schema. Note that jsonschema recommends avoiding metachars
like "\w" since they're not supported by all implementations [3].
I've tested the new validation manually and it works as expected
by disallowing e.g. "  " but still alowing "foo" and "foo bar".
I don't think we need a test for it, as it's declarative code
for an edge case concern.
[1]: …

Add validation to prevent blank area names

---

app/celery/broadcast_message_tasks.py
app/celery/nightly_tasks.py
app/celery/scheduled_tasks.py
requirements-app.txt
requirements.txt
tests/app/celery/test_broadcast_message_tasks.py
tests/app/celery/test_nightly_tasks.py
tests/app/celery/test_scheduled_tasks.py

We introduced a new way of creating Zendesk tickets here https://github.com/alphagov/notifications-utils/pull/899 and tried it out first just on the request to go live tickets (https://github.com/alphagov/notifications-admin/pull/4024).
It worked! So now we want to use the new way of creating tickets everywhere.
[Pivotal story](https://www.pivotaltracker.com/story/show/179005041)

Use the new Zendesk form for all tickets

---

app/dao/users_dao.py
tests/app/dao/test_users_dao.py

People with dyslexia and dyscalculia find it difficult to transpose codes which have consecutive, repeated digits<sup>1</sup>, for example `11122` or `98776`.
This commits enhances the algorithm for generating codes to not repeat the previous digit in a code.
This reduces the key space for our codes from 100,000 (10<sup>5</sup>) possibilities to 65,610 (10 &times; 9<sup>4</sup>) possibilities.
***
1. https://twitter.com/annaecook/status/1442567679710150662
2. Background reading: https://github.com/alphagov/govuk-design-system/pull/1265

Don’t repeat digits in security codes

---

requirements-app.txt
requirements.txt

Brings in fixes for non breaking space support in templates
See https://github.com/alphagov/notifications-utils/pull/908 for context

Bump utils to 48.0.0

---

app/celery/nightly_tasks.py
app/dao/notifications_dao.py

From experimenting in production we found a "!=" caused the engine
to use a sequential scan, whereas explicitly listing all the types
ensured an index scan was used.
We also found that querying for many (over 100K) items leads to
the task stalling - no logs, but no evidence of it running either -
so we also add a limit to the query.
Since the query now only returns a subset of notifications, we need
to ensure the subsequent "update" query operates on the same batch.
Also, as a temporary measure, we have a loop in the task code to
ensure it operates on the total set of notifications to "time out",
which we assume is less than 500K for the time being.

Optimise query to get notifications to "time out"

---

app/celery/letters_pdf_tasks.py
app/commands.py
app/config.py
tests/app/celery/test_letters_pdf_tasks.py

**Add task to re-sanitise and replace a PDF for precompiled letter**
This adds a task which is designed to be used if we want to recreate the PDF for a precompiled letter (either one that has been created using the API or one that has been uploaded through the website).
The task takes the `notification_id` of the letter and passes template preview the details it needs in order to sanitise the original file and then replace the version in the letters-pdf bucket with the freshly sanitised version.
**Add command to run the new task**
We already had the `replay-create-pdf-for-templated-letter` command. This adds a new command, `recreate-pdf-for-precompiled-or-uploaded-letter` which does the same thing but for non-templated letters.
Part of [Pivotal …

Add task to recreate the PDF file for a non-templated letter

---

app/v2/notifications/post_notifications.py
tests/app/v2/notifications/test_post_notifications.py

https://www.pivotaltracker.com/story/show/180017131
Previously we were catching one type of exception if something went
wrong adding a notification to the queue for high volume services.
In reality there are two types of exception so this adds a second
handler to cover both.
For context, this is code we changed experimentally as part of the
upgrade to Celery 5 [1]. At the time we didn't check how the new
exception compared to the old one. It turns out they behaved the
same and we were always vulnerable to the scenario now covered by
the second exception, where the behaviour has changed in Celery 5 -
testing with a large task invocation gives...
Before (Celery 3, large-ish task):
'process_job.apply_async(["a" * 200000])'...
boto.exception.SQSError: SQSError: 400 Bad Request
<?xml …

Improve and clarify large task error handling

---

app/dao/notifications_dao.py

There were two problems with the existing message.
1. There was no space between the new status and the time taken
which made reading and searching harder
2. They key bits of information (before and after status) were
separated by the time taken (which will always be unique) meaning
you couldn't do an easy search for a message that is say in delivered
being attempted to be set to temporary-failure.
Example logs at the moment in Logit which are a bit hard to search through:

Improve log message searchability for duplicate receipts

---

app/celery/scheduled_tasks.py
app/config.py
tests/app/celery/test_scheduled_tasks.py

We have made it so that gov.uk/alerts shows a ‘1 planned test’ banner for the whole of the day when there has been an operator test on that day.
We need to remove the banner when the day is over.
The most straightforward way to do this is to republish the site at the start of every day. The [gov.uk/alerts code will work out if there are or aren’t any planned tests to show that day](https://github.com/alphagov/notifications-govuk-alerts/blob/5a274af6d0c202b7bd5e664967b1e113015b9a31/app/models/alerts.py#L38-L44).

Republish gov.uk/alerts every night to clear down planned tests

---

README.md

This seems to be an issue for several people when we install new
versions of the package. Older versions of the package seem to
be equally affected, so the new need for this is likely related
to us using a newer OS / XCode version.

Link to guidance about installing pycurl

---

scripts/paas_app_wrapper.sh

In version 4.0 of celery, -Ofair became the default
scheduling strategy:
https://docs.celeryproject.org/en/latest/history/whatsnew-4.0.html?highlight=fair#ofair-is-now-the-default-scheduling-strategy
This appears to still be the case:
https://github.com/celery/celery/blob/5d68d781de807b4576cf5f574e5ba0aaf0d17388/celery/concurrency/asynpool.py#L80
Note, it took me a while to be certain of this as the documentation
for the celery CLI suggests a choice of `default` or `fair` which
isn't so useful as both of these are `fair`:
https://docs.celeryproject.org/en/latest/reference/cli.html#cmdoption-celery-worker-O

Remove -Ofair option from celery worker

---

app/celery/letters_pdf_tasks.py
app/celery/reporting_tasks.py
app/cronitor.py
tests/app/test_cronitor.py

https://www.pivotaltracker.com/n/projects/1443052
As stated in the comment, this would have been helpful during an
incident to give further reassurance that a task had at least
started running - at the time the only evidence for this was the
Cronitor dashboard itself, which we don't often look at.
I've removed other, equivalent "starting" logs, but kept those
that provide additional information in the log message.

Log activity on all periodic Celery tasks

---

app/dao/fact_processing_time_dao.py
tests/app/dao/test_fact_processing_time_dao.py

For preview and staging environments, we often send no messages
in a single day. This is currently causing a `DivisionByZero` error
that is rendering the admin page as a 404. This makes it impossible
to look at preview/staging and see if the performance page is
working correctly or not.
```
(psycopg2.errors.DivisionByZero) division by zero
[SQL: SELECT CAST(ft_processing_time.bst_date AS TEXT) AS date, ft_processing_time.messages_total AS ft_processing_time_messages_total, ft_processing_time.messages_within_10_secs AS ft_processing_time_messages_within_10_secs, (ft_processing_time.messages_within_10_secs / CAST(ft_processing_time.messages_total AS FLOAT)) * %(param_1)s AS percentage
FROM ft_processing_time
WHERE ft_processing_time.bst_date >= %(bst_date_1)s AND ft_processing_time.bst_date …
```

Fix division by zero error on performance page

---

app/performance_dashboard/rest.py
tests/app/performance_dashboard/test_rest.py

We are starting to see lots of 100.0%s in the current table
and we think this looks suspiciously too good so think it is
beneficial to change it to be 2dp such that we get a few more
non 100.0% values.
For the admin app to be able to show things to 2dp, we need to
give at least 2dp of accuracy otherwise we are losing 1dp of
granularity.
See https://github.com/alphagov/notifications-admin/pull/4079 for admin app PR.

Report processing stats to 2dp rather than 1dp

---

app/commands.py

When we first started recording the details of the agreements that
were signed by organisations, we stored a copy of the signed agreement
in Google drive. Later, we switched to storing the details in the
database instead.
This adds a command which is designed to be run once and which updates
the database for the organisations which had the details of who accepted
the agreement and when stored in Google drive.
_Note, the organisation cache will need to be cleared after the command is run._
[Pivotal story](https://www.pivotaltracker.com/story/show/180246578)

Add command to populate organisation table with agreement details 

---

app/dao/notifications_dao.py

Adding a filter to `app.dao.notifications_dao.is_delivery_slow_for_providers` query to improve the performance. By added Notifications.notification_type = 'sms' to the query it will improve the performance some analyse shows 500ms improvement, which is a good thing especially when the query is run once a minute.

Improve query performance

---

scripts/paas_app_wrapper.sh

TL;DR
After a chat with some team members we've decided to double the concurrency of the delivery-worker-reporting app to 4 from 2. Looking at the memory usage during the reporting task runs we don't believe this to be a risk. There are some other things to look at, but this could be a quick win in the short term.
Longer read:
Every night we have 2 "reporting" tasks that run.
- create-nightly-billing starts at 00:15
- populates data for ft_billing for the previous days.
- 4 days for email
- 4 days for sms
- 10 days for letters
- create-nightly-notification-status starts at 00:30
- populates data for ft_notification
- 4 days for email
- 4 days for sms
- 10 days for letters
These tasks are picked up by the `notify-delivery-worker-reporting` app, we run 3 instances with a concurrency = 2. …

Increase the concurrency for the delivery-worker-reporting

---

tests/app/test_cronitor.py

https://www.pivotaltracker.com/story/show/180344153
This appears to not be thread safe: it started failing when run in
parallel with other tests in this PR [1]. We don't get much out of
using caplog over patching - it just proves our logging config isn't
swallowing the error logs, which we shouldn't need to test here.
[1]: https://github.com/alphagov/notifications-api/pull/3383

Fix flakey Cronitor test using caplog fixture

---

app/celery/nightly_tasks.py
app/dao/notifications_dao.py

we used to do this until apr 2020. Let's try doing it again. Back then, we had problems with timing. We did two things in spring 2020:
We moved to using an intermediary temp table [1]
We stopped the tasks being parallelised [2]
However, it turned out the real time saving was from changing what services we delete for [3]. The task was actually CPU-bound rather than DB-bound, so that's probably why having the tasks in parallel wasn't helping, since they were all competing for the same CPU. It's worth trying the parallel steps again now that we're no longer CPU bound.
Note: Temporary tables are in their own postgres schema, and are only viewable by the current session (session == connection. Each celery worker process has its own db connection). We don't need to worry about separate workers …

make delete notification tasks parallel by notification type

---

app/celery/nightly_tasks.py
app/config.py

They share a lot with the reporting tasks (creating ft_billing and ft_notification_status), in that they're run nightly, take a long time, and we see error messages if they get run multiple times (due to visibility timeout).
The periodic app has two concurrent processes - previously there was just one delete task, which would use one of those processes, while the other process would pick up anything else on the queue (at that time of night, the regular provider switch checks and scheduled job checks). However, when we switched to running the three delete notification types separately, we saw visibility timeout issues - three tasks would be created, all three would be picked up by one celery instance, the two worker processes would start on two of them, and the third would sit on the box, …

put delete tasks on the reporting worker

---

requirements.in
requirements.txt

Just so other people don’t have to merge these changes.
The breaking changes don’t affect this repo because the API doesn’t:
- check the service guestlist before sending a message
- do any visual preview of emergency alert messages
Full changes: https://github.com/alphagov/notifications-utils/compare/49.0.0...51.0.0
Chagelog:
> **51.0.0**
> - Initial argument to `RecipientCSV` renamed from `whitelist` to `guestlist`, in other words consuming code should call `RecipientCSV(guestlist=['test@example.com'])`
> - `RecipientCSV.whitelist` property renamed to `RecipientCSV.guestlist`
>
> **50.0.0**
> - Make icon in `broadcast_preview_template.jinja2` an inline SVG (requires changes to the CSS of consumer code)
>
> **49.1.0**
> - Add `ttl_in_seconds` argument to `RequestCache.set` to let users …

Bump notifications-utils to 51.0.0

---

app/v2/notifications/get_notifications.py

This is a similar PR to https://github.com/alphagov/notifications-api/pull/2284.
When using flask-sqlalchemy to get a `Pagination` object, by default
it will run two queries
1. Get the page of results that you are asking for
2. If the number of results is equal to the page size, then it will
issue a second query that will count the total number of results
Getting the total number of results is only useful if
- you need to show how many results there are
- you need to know if there is a next page of results (flask-sqlalchemy
uses the total to work out how many pages there are altogether,
which may not be the most efficient way of working out if there
is a next page or not but that is what it currently does).
Looking at the `get_notifications` route, it does
not use …

Set `count_pages` as False to stop running of redundant query

---

app/celery/nightly_tasks.py
app/dao/notifications_dao.py
tests/app/celery/test_nightly_tasks.py
tests/app/dao/notification_dao/test_notification_dao.py

https://www.pivotaltracker.com/story/show/180344153
This makes the temporary hack we put in more permanent:
we can now time out any number of notifications, not just
the arbitrary 500K limit we put in.
Please review commit by commit.

Scale timeout task to work on arbitrary volumes

---

app/celery/nightly_tasks.py
app/dao/notifications_dao.py

https://www.pivotaltracker.com/story/show/180344294
This adds two metrics so we can monitor:
- Slow SMS providers
- Missing receipts (all providers)
The first gives us a more realtime view of the second.
Both help us monitor how our providers are doing.
Please see commits for more details.

Add new metrics for slow / unknown delivery

---

app/dao/notifications_dao.py
tests/app/dao/notification_dao/test_notification_dao_delete_notifications.py

https://www.pivotaltracker.com/story/show/180692253
If the S3 object is missing [1], then that's what we want, so we
don't need such a severe log for it, but we still want to know as
it's not expected. This is separate to more general "ClientError"
exceptions, which could mean anything.
There weren't any tests to cover missing S3 objects, so I've added
one. I don't think we need a test for ClientErrors:
- If there was no handler, the task would fail and we'd learn about
it that way.
- The scope of the calling task is now much smaller, so it matters 
less than it used to [2].
[1]: https://github.com/alphagov/notifications-api/blob/81a79e56ced891ad58901ea61ce707e907de3363/app/letters/utils.py#L52
[2]: https://github.com/alphagov/notifications-api/commit/f965322f25e37f8125463223eb5b2473e246e8 …

Downgrade log for letter deletion exceptions

---

app/dao/services_dao.py

https://www.pivotaltracker.com/story/show/180477467
This is no longer used when creating a service [1]. It was likely
added at a migration point when Admin _did_ specify branding.
[1]: https://github.com/alphagov/notifications-admin/blob/50c3c3e10cd904d2d17035d7665f14b6a181062e/app/main/views/add_service.py#L15-L22

Remove redundant conditional for letter branding

---

app/notifications/receive_notifications.py

We can't control who might be sending messages on inbound numbers
that we own i.e. this log isn't an actionable error. Looks like it
used to represent something that _was_ an error [1], but that's not
the case anymore, so it seems reasonable to downgrade it.
[1]: https://github.com/alphagov/notifications-api/commit/d99ab329eb5937c87c50ac51332beadcd26b53f5#diff-80d123d9abb40f80a221979940657a2751cc7cb33f255aa8f352a8324023e022L125

Downgrade log about orphaned inbound SMS

---

app/dao/fact_billing_dao.py
tests/app/dao/test_ft_billing_dao.py
tests/app/organisation/test_rest.py

The way it was done before, the remainder was incorrect in the billing report and in the org usage query - it was the sms remainder left at the start of the report period, not at the end of that period.
This became apparent when we tried to show sms_remainder on the org usage report, where start date is always the start of the financial year.
We saw that sms sent by services did not reduce their free allowance remainder according to the report. As a result of this, we had to temporarily remove of sms_remainder column from the report, until we fix the bug - it has been fixed now, yay!
I think the bug has snuck in partially because our fixtures for testing this part of the code are quite complex, so it was harder to see that numbers don't add up. I have added comments to the tests to try …

Fix calculating remaining free allowance for SMS

---

manifest.yml.j2

We saw it fail again last night to calculate how many notifications
were sent for one of our services to put in the ft_notification_status
table. It ran in to the sqlalchemy statement timeout again.
To get us through the holiday
period lets make it 2 hours as surely that will be enough and then
we can fix this properly

Bump sqlalchemy statement timeout even higher for reporting worker

---

manifest.yml.j2

Having a pool size of 30 connections means that if we receive a big
number of requests, with the current configuration, the API would end up
holding onto 30 connections per worker * 4 workers per instance * 35
instances = 4200 connections. With a limit of 5000 connections, this
means that we would only have 800 connections to share between the
workers or for overflow usage (btw, even the overflow for the API would
take us above the 5000 limit - 10 overflow connections per worker * 4 *
35 = 1400 connections, total 5600 _only_ for the API).
During our load tests this led to a deadlock situation where nothing
could retrieve connections to deal with a queue build-up.
The reduced pool size allowed for a much more graceful degradation of
the service where, after significant load we would …

Reduce pool size from 30 to 15 connections

---

app/service/rest.py
tests/app/notifications/rest/test_send_notification.py
tests/app/service/test_api_key_endpoints.py
tests/app/service/test_rest.py
tests/app/template_statistics/test_rest.py

We want admin to send a POST request to this route if the data contains
a message recipient (a phone number or email address) so that this does
not show in the logs. This changes the route to accept both GET and POST
requests.
(Plus a couple of small test tidy-ups)
[Pivotal story](https://www.pivotaltracker.com/story/show/180637866)

Allow `get_all_notifications_for_service` to accept POST requests 

---

app/dao/fact_billing_dao.py
tests/app/dao/test_ft_billing_dao.py
tests/app/db.py

If a service has not sent any SMS for the financial year the free allowance was showing up as 0 rather than the number in annual billing. The query has been updated to use an outer join so that the free allow will be returned when there is no ft_billing.
There is a potential performance enhancement to only return the data for the services of the organisation in the `fetch_sms_free_allowance_remainder_until_date` subquery. I will investigate in a subsequent PR.

Fix bug in organisation report for its services and usages.

---

app/dao/fact_notification_status_dao.py
tests/app/dao/test_fact_notification_status_dao.py

Investigation with EXPLAIN and EXPLAIN ANALYZE for the notification history
table shows this is another instance of [1] but for the key type column.
Swapping "!=" for "IN" solves the problem.
Before:
```
GroupAggregate  (cost=48285296.89..48304545.97 rows=699630 width=72) (actual time=382883.029..383541.435 rows=80 loops=1)
Group Key: template_id, service_id, job_id, key_type, notification_status
->  Sort  (cost=48285296.89..48287047.29 rows=700159 width=64) (actual time=382734.683..383303.675 rows=1464049 loops=1)
Sort Key: template_id, job_id, key_type, notification_status
Sort Method: external merge  Disk: 84736kB
->  Index Scan using ix_notification_history_service_id_composite on notification_history  (cost=0.70..48190993.82 …
```

Optimise query to populate notification statuses

---

app/dao/organisation_dao.py
app/organisation/rest.py
tests/app/organisation/test_rest.py

This is similar to the corresponding endpoint for services. However,
it is a little simpler since we don't need to worry about always having
at least one team member for an organisation.
The new dao function added, `dao_remove_user_from_organisation`, is also
simpler than `dao_remove_user_from_service` since we don't have any
organisation permissions to deal with.
[Pivotal story](https://www.pivotaltracker.com/story/show/180573449)

Add endpoint to allow org team members to be removed

---

app/celery/reporting_tasks.py
app/commands.py
app/dao/fact_notification_status_dao.py
tests/app/celery/test_reporting_tasks.py
tests/app/dao/test_fact_notification_status_dao.py

This follows a similar approach as [1]. Recently we've seen lots of errors
from this task, which we think are a consequence of it doing too much work
and tripping Celery's visibility timeout.
While we can optimise the query [2], it's likely the errors will return as
the number of live services grows. Parallelising the aggregation now will
make it more futureproof.
Because the new logs will be broken down by service, I'll also be able to 
confirm if we can safely revert https://github.com/alphagov/notifications-api/pull/3411 - at the moment, it's unclear what 
the max per-service query time is in the DAO loop.
I've broken down the changes into a few commits.
Tested locally to check the tasks are queued up as expected ✅.
Should only be …

Parallelise status aggregation by service and day

---

app/celery/nightly_tasks.py

the new delete-per-service tasks emit lots of boring log lines that look the following:
`delete-notifications-for-service-and-type: service: 64f8dff2-913d-471f-8793-57b9087b6ef3, notification_type: sms, count deleted: 0, duration: 0 seconds`
we try and delete for lots of services. this includes services that don't actually have anything to delete that day. that might be because they had a custom data retention so we always go to check them, or because they only sent test notifications (which we'll delete but not include in the count in the log line). we don't really need to see log lines saying that we didn't delete anything for that service - that's just a long list of boring log messages that will hide the actual interesting stuff - which services we did delete content for.

don't log if we dont delete anything for a service

---

run_celery.py

To support multiple processes and eventlets recording metrics in parallel, prometheus uses files to store metrics. When you write a metric from a multiprocess app, it writes to a file.
Prometheus identifies whether your app is multiprocess by looking for the existence of a `prometheus_multiproc_dir` environment var (in either case). Prometheus reads this variable at a module level (ie: at import time). Assuming it will always used within a web server, the gds_metrics library auto-sets this to `/tmp` on import, to ensure that prometheus will always be set up correctly.
We also have a variety of metrics set up when we create the app. These are generally sensible metrics such as counting the number of database connections in use by measuring sqlalchemy connection events.
We have seen …

disable prometheus writing to files from celery apps

---

app/config.py
manifest.yml.j2

Previously we think this setting was necessary to avoid a memory
leak [1], but it's unclear if this is still an issue:
- We've advanced two major versions of Celery.
- Some of the tasks are now quicker and leaner.
Restarting worker sub-processes after each task is a big problem
for performance, as we move towards parallelising our reporting.
This is something of a test to see if we can manage without this
setting. Note that we need to unset the variable manually:
cf unset-env notify-delivery-worker-reporting CELERYD_MAX_TASKS_PER_CHILD
In the worst case we can always re-run any failed tasks. To check
the worker is still behaving as expected, we can:
- Monitor CPU / memory graphs for it.
- Check `cf events` for unexpected restarts / …

Stop killing reporting processes after each task

---

requirements.in
requirements.txt

we previously pinned cryptography to versions less than 3.4 since after that point, cryptography started using rust as a dependency. This isn't an issue if you install from wheel, but we found that the version of pip bundled with the python buildpack was too old to support this. However, since upgrading from python 3.6 to python 3.9, the pip version has been bumped and we now no longer need to pin cryptography as it installs correctly.
(i tested this by pushing an admin prototype to preview)

unpin cryptography

---

app/celery/letters_pdf_tasks.py
app/dao/notifications_dao.py
app/v2/notifications/post_notifications.py
tests/app/celery/test_letters_pdf_tasks.py
tests/app/dao/notification_dao/test_notification_dao.py
tests/app/letters/test_letter_utils.py
tests/app/v2/notifications/test_post_letter_notifications.py

It is possible that the personalisation for a templated letter can make the letter exceed 10 pages or 5 sheets. We are not validating the letters posted via the API for this validation error. It is only possible to validate the letter once we create the PDF in notifications-template-preview. This means that the letter can only get a validation-failed status after the client has received a 201 from the POST to /v2/notifications.
NOTE: we only validate the preview row of a CSV for this validation error, this change will mean that it is possible for a letter to be marked as validation-failed after a successful file upload.
A new task to update the notification to `validation-failed` has been added to the API. If we find that the letter is too long once we have created the PDF we call the …

Mark letters as validation-failed if the templated letter is too long.

---

app/v2/notifications/post_notifications.py

This caught me out the other day when I was testing. I thought antivirus
was enable, seeing this message didn't help with that assumption. Plus
there is no point in showing the log if we don't actually call the task.

Moved log message inside the if statement where it actually happens.

---

app/platform_stats/rest.py
tests/app/platform_stats/test_rest.py

This field caused some confusion and lots of unnecessary work to our colleague because of unclear name.
The field was named sms_fragments, where in fact the value of the field is: those sms fragments that go above free allowance multiplied by the rate multiplier.
The new name was chosen through consultation with colleagues who use billing report the most.
This change should go out together with: https://github.com/alphagov/notifications-admin/pull/4137

Rename sms_fragments to sms_chargeable_units

---

Makefile
app/config.py
docker/Dockerfile
scripts/run_with_docker.sh

as a team we primarily develop locally. However, we've been experiencing issues with pycurl, a subdependency of celery, that is notoriously difficult to install on mac. On top of the existing issues, we're also seeing it conflict with pyproj in bizarre ways (where the order of imports between pyproj and pycurl result in different configurations of dynamically linked C libraries being loaded.
You are encouraged to attempt to install pycurl locally, following these instructions: https://github.com/alphagov/notifications-manuals/wiki/Getting-Started#pycurl
However, if you aren't having any luck, you can instead now run celery in a docker container.
`make run-celery-with-docker`
This will build a container, install the dependencies, and run celery (with the default of four concurrent …

add script to run celery from within docker

---

app/celery/tasks.py
app/models.py
requirements.in
requirements.txt
tests/app/celery/test_tasks.py

Changes:
53.0.0
---
* `notifications_utils.columns.Columns` has moved to `notifications_utils.insensitive_dict.InsensitiveDict`
* `notifications_utils.columns.Rows` has moved to `notifications_utils.recipients.Rows`
* `notifications_utils.columns.Cell` has moved to `notifications_utils.recipients.Cell`
52.0.0
---
* Deprecate the following unused `redis_client` functions:
- `redis_client.increment_hash_value`
- `redis_client.decrement_hash_value`
- `redis_client.get_all_from_hash`
- `redis_client.set_hash_and_expire`
- `redis_client.expire`
51.3.1
---
* Bump govuk-bank-holidays to cache holidays for next year.

Bump utils to 53.0.0

---

app/broadcast_message/utils.py
app/models.py
app/v2/broadcast/post_broadcast.py
tests/app/broadcast_message/test_utils.py
tests/app/v2/broadcast/test_post_broadcast.py

Needs to go in after https://github.com/alphagov/notifications-api/pull/3453
And needs to go in before:  https://github.com/alphagov/notifications-api/pull/3448

Audit api key id when cancelling broadcast via api - second try

---

migrations/versions/0364_drop_old_column.py

This column has been superseded by a new column named created_by_api_key_id.
Needs to go in after https://github.com/alphagov/notifications-api/pull/3440

Drop api_key_id column from broadcast_message table

---

manifest.yml.j2

This fixes the app crashing - apparently due to a lack of free
memory. Looking over the last month, we can see it's been hovering
at ~90% utilisation. 512M seems like a good compromise to avoid
this happening again vs paying for what we use.
The limit was last changed 5 years ago:
https://github.com/alphagov/notifications-api/pull/882

Bump memory for Celery Beat to 512M

---

app/v2/broadcast/broadcast_schemas.py
tests/app/v2/broadcast/sample_cap_xml_documents.py

References are optional, and we fixed errors when they are not provided in bbc444699a6032ef855959d81aee905775be9862
This commit amends the tests so that they cover the `Alert` message type as well as the `Cancel` (which is already covered).
The XML for an alerts requires a `<description>` field. The XML for a `<cancel>` may have the `<description>` field populated (although we ignore the contents) but it may also be empty.
This commit updates the schema to leave the all the validation to the view layer, which can decide when or when not to validate the content of the `<description>` field.

More tweaks of broadcast message validation

---

app/celery/reporting_tasks.py
app/dao/fact_notification_status_dao.py
tests/app/celery/test_reporting_tasks.py
tests/app/dao/test_fact_notification_status_dao.py

This significantly cuts the number of (insert) queries per service, and
also removes a minor issue of rows in the status table being deleted but
not replaced if the task quits halfway through (for whatever reason).
I think the new version is easier to follow as all the behaviour is in
one place, instead of passing "new_status_rows" around. It was also a bit
of a learning opportunity for me to get used to SQLAlchemy.

Rewrite status aggregation to be a bulk upsert

---

migrations/versions/0365_add_nhs_branding.py

With the changes we will be making to email branding in admin it's useful to know the ID of the NHS email brand. This makes it easier to show a preview of the branding.
This means that the ID will need to be consistent across environments, so this changes the details of the NHS brand in the dev, preview and staging environments to match the production data.
The migration
- Removes NHS branding from existing services
- Removes NHS branding from any orgs which had it as their default
- Deletes the NHS branding row if it exists
- Inserts a new NHS branding row with details which match those in production
This does have the effect of removing NHS branding from people's local and preview services and orgs (NHS branding doesn't exist on staging), but this does not affect real teams. The NHS …

Migration to make NHS email branding ID consistent across environments

---

app/dao/broadcast_message_dao.py
app/v2/broadcast/post_broadcast.py
tests/app/v2/broadcast/sample_cap_xml_documents.py
tests/app/v2/broadcast/test_post_broadcast.py

We’ve found two problems that can come up when trying to cancel an alert:
- the `<references>` field contains reference to the alert which should be cancelled, plus some older, already-cancelled alerts
- the `<references>` field contains references to multiple current or pending alerts, and it’s unclear which one should be cancelled
This pull request adds code to handle the first case and error in the second.

Be more robust in handling ambiguous references to cancel an alert

---

app/v2/broadcast/post_broadcast.py
tests/app/v2/broadcast/test_post_broadcast.py

Before we implemented ‘cancel’ any updates to a broadcast went through the admin app. This meant the admin app could deal with clearing the cache any time a broadcast was updated by a user performing an action.
Now that a broadcast can be updated without the admin app being involved we have another place we need to clear the cache from.
If we don’t do this then the broadcast can look like it’s still going even though it’s successfully been cancelled.

Clear cache when cancelling broadcast via the API

---

Makefile
README.md
app/config.py
scripts/run_with_docker.sh

This makes a few changes to:
- Make local development consistent with our other apps. It's now
faster to start Celery locally since we don't try to build the
image each time - this is usually quick, but unnecessary.
- Add support for connecting to a local Redis instance. Note that
the previous suggestion of "REDIS = True" was incorrect as this
would be turned into the literal string "True".
I've also co-located and extended the recipes in the Makefile to
make them a bit more visible.

Iterate local development with Docker

---

app/config.py

This changes the time of the scheduled task to raise an alert if letters are still sending from 1530 to 1700. DVLA have reported that our "monitoring is executing just before we actually mark them as ‘despatched’ and send you the feedback files." and asked us to make the check a little later.
We don't actually contact DVLA until the morning after the alert anyway, so this won't affect the process of getting in touch with them.
This change will require Cronitor to be updated for the new time.

Make letters still sending check later

---

tests/app/celery/test_reporting_tasks.py

The test was querying `FactNotificationStatus` and ordering the results
by bst_date and notification_type then checking the rows. However, the
bst_date and notification_type for each row is the same, so this test
could fail based on the order that the results came back in. By ordering
on the notification_status instead, we can be sure of the order of the
results.

Fix test which was flakey due to order of items returned from db

---

app/billing/billing_schemas.py
tests/app/billing/test_billing.py
tests/app/db.py
tests/app/v2/notifications/test_get_notifications.py

This updates the `create_or_update_free_sms_fragment_limit_schema` to allow the `free_sms_fragment_limit` to have a minimum of 0, not 1.
[Pivotal story](https://www.pivotaltracker.com/story/show/181282523)

Allow SMS fragment limit to be 0

---

requirements.in
requirements.txt

Gunicorn has a bug where it is incompatible with eventlet>0.30.2
The code to fix this itself was merged into master in gunicorn's repo (https://github.com/benoitc/gunicorn/pull/2581) - however, that master code hasn't been released since it was merged 9 months ago.
There's a [security advisory for eventlet<=0.31.0](https://github.com/eventlet/eventlet/security/advisories/GHSA-9p9m-jm8w-94p2) which doesn't affect us as it only involves websockets, however, it'd be nice to be able to not have that as a lingering issue on our repo.
To fix this, pin github to the merge commit for the PR above. This can revert to a regular pypi requirement for gunicorn once 0.21.1 or higher is released.
The pinned commit adds nothing to gunicorn 20.1.0 other than the eventlet fix and some docs changes.
also …

Bump gunicorn

---

migrations/versions/0366_letter_rates_2022.py

- second class postage will go up by 2 pence, plus VAT
- international postage will go up by 7 pence, plus VAT
- first class postage will go down by 6 pence, plus VAT

Add new letter rates for March 1, 2022.

---

app/dao/services_dao.py

https://govuk.zendesk.com/agent/tickets/4896284
Currently we alert if a service wastes £16 of SMS. It may cost us
around that amount just to deal with the alert, especially if the
service refuses to clean up their data.
This bumps the threshold to something more alarming, which should
make it more reasonable to suspend the service if we can show that
they've already wasted public money. £160 seems like a reasonable
compromise between have wasted vs could waste.
Note: we previously compromised on 1000 [1] down from 63K [2]. I
think we can afford to go a little bit higher.
[1]: https://github.com/alphagov/notifications-api/pull/3234
[2]: https://github.com/alphagov/notifications-api/pull/3221

Tweak SMS alert to make it worth the effort

---

app/letters/rest.py
tests/app/letters/test_returned_letters.py

if we have too many returned letters, we'll exceed SQS's max task size of 256kb. Cap it to 5000 - this is probably a bit conservative but follows the initial values we used when implementing this for the collate-letters-task[^1]. Also follow the pattern of compressing the sqs payload just to reduce it a little more.
[^1]: https://github.com/alphagov/notifications-api/pull/1536

split returned letters tasks into a max count of returned letters

---

app/user/rest.py
tests/app/user/test_rest_verify.py

This follows the pattern for invite emails where the admin app tells the API which domain to use when generating the link.
This will starting working once the admin change is merged:
It won’t break anything if it’s merged before the admin change.

Allow admin app to specify domain for registration email

---

app/celery/service_callback_tasks.py

It is currently 60 seconds but we have had two incidents in the
past week where there is a connection error talking to a service
and the request takes up to 60 seconds before failing. When this
happens, if there are a few of these callbacks then all of them
will completely hog the service callback worker and build up a big
queue of all the other service callbacks.
5 seconds has been chosen as that is still a pretty decent length
time for a simple web request that should just be giving them a
little bit of information for them to store. 5 seconds should be a
sufficient enough reduction that we dramatically reduce this problem
for the moment.
Open to this number
being changed in the future based on how we see it perform.
Note, I could see nothing in the previous git commit for a reason why …

Reduce timeout for service callback attempt to 5 seconds

---

app/celery/scheduled_tasks.py
tests/app/celery/test_scheduled_tasks.py

Since sept 2019 we've had to log on to production around once every twenty days to restart the virus scan task for a letter. Most of the time this is just a case of making sure the file is in the scan bucket, and then triggering the task. If the file isn't in the scan bucket we'd need to do some more manual investigation to find out exactly where the file got stuck, but I can only remember times when it's been in the scan bucket.
So if the file is in the scan bucket, we can just check that with code and kick the task off automatically.

automatically retry letters stuck in pending-virus-scan

---

app/config.py
scripts/run_with_docker.sh

https://www.pivotaltracker.com/story/show/181498273
Currently "test_send_letter_notification_via_api" fails at the final
stage in create-fake-letter-response-file [^1]:
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=6011): Max retries exceeded with url: /notifications/letter/dvla (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff95ffc460>: Failed to establish a new connection: [Errno 111] Connection refused'))
This only applies when running in Docker so the default should still
be "localhost" for the Flask app itself.
[^1]: https://github.com/alphagov/notifications-api/blob/5093064533e558d48add2c373eb5eeaf752e6b8e/app/celery/research_mode_tasks.py#L57

Fix letter functional tests to work in Docker

---

README.md

https://www.pivotaltracker.com/story/show/181498273
Since we moved to Dockerised Celery the pycurl guidance should no
longer be necessary and doesn't work on newer Mac M1 machines.
This also adds new guidance for psycopg2, which will hopefully be
temporary (see issue comment).

Replace pycurl guidance with psycopg2

---

app/dao/notifications_dao.py

This will make it easier to group these logs if a service complains
about the issue.

Log Service ID when we get a duplicate receipt

---

app/commands.py
tests/app/test_commands.py

Update app.commands.populate_annual_billing_with_defaults so that if the service has zero free allowance in the previous year, set this year to
zero as well.
This has been tested locally. 
https://www.pivotaltracker.com/story/show/181513052

Set free allowance to zero if previous year is zero in command to set free allowance for a year

---

app/dao/provider_details_dao.py
tests/app/dao/test_provider_details_dao.py

https://www.pivotaltracker.com/story/show/181574489
Fixes:
>       reduced_provider = providers[identifier]
E       KeyError: 'firetext'

Fix SMS priority adjustment if only 1 provider

---

README.md
app/__init__.py
app/celery/provider_tasks.py
app/clients/email/__init__.py
app/clients/email/aws_ses.py
app/clients/email/aws_ses_stub.py
app/clients/sms/__init__.py
app/clients/sms/firetext.py
app/clients/sms/mmg.py
app/clients/sms/reach.py
app/config.py
app/delivery/send_to_providers.py
migrations/versions/0367_add_reach.py
tests/app/clients/test_firetext.py
tests/app/clients/test_mmg.py
tests/app/clients/test_reach.py
tests/app/clients/test_sms.py
tests/app/dao/test_provider_details_dao.py
tests/app/delivery/test_send_to_providers.py
tests/app/provider_details/test_rest.py

https://www.pivotaltracker.com/story/show/181574489
Separate PR for callback boilerplate: https://github.com/alphagov/notifications-api/pull/3492
Like the callback PR, I've done a few refactorings to avoid
a lot of copy/pasta when creating the new provider for Reach.
See the last commit for instructions about local testing.
Note: this will break the "Change priority" screen in the Admin
app [^1], hence marking the PR with "DNM" for the time being. I
hope to have a PR that fixes that soon.
[^1]: https://www.notifications.service.gov.uk/provider/edit-sms-provider-ratio

Add boilerplate for sending SMS via Reach

---

app/clients/sms/__init__.py
tests/app/dao/test_fact_notification_status_dao.py

This was a mistake in [^1].
[^1]: https://github.com/alphagov/notifications-api/commit/3b082477f05588d638a21ce0874356678fd429df#diff-95316b574f974237b3b7ce453fec09628bd1062087154789ff4d0176ea23c460R52

Fix log for sending SMS to be generic per client

---

app/__init__.py
app/v2/notifications/get_notifications.py
requirements.in
requirements.txt
tests/app/v2/test_errors.py

This bumps Flask to version 2.1.0, which requires some minor changes to the app code and itsdangerous to also be bumped.
This change is similar to https://github.com/alphagov/notifications-api/pull/3250, which got reverted due to a memory leak. However, since that PR there have been later versions of the code released and we have also been running Flask 2 in template preview with no issues.

Bump Flask and itsdangerous

---

app/config.py

It's worth noting this will break the Admin page to edit provider
priorities, which currently works in units of 10. We already have
work planned to fix this [^1] and it's not an immediate problem.
The automatic adjustment algorithm will continue to work properly
as it can cope with increments smaller than 10 [^2].
[^1]: https://www.pivotaltracker.com/story/show/181681739
[^2]: https://github.com/alphagov/notifications-api/blob/b145a299351255c5755ca547629b7936cb7fcf4a/app/dao/provider_details_dao.py#L122

Adjust resting positions for SMS providers

---

app/dao/provider_details_dao.py

This stops the pages being slow to load and defers the need to add
any pagination. Only the most recent data is likely to be relevant.

Limit provider history to 100 results

---

app/broadcast_message/rest.py
app/broadcast_message/utils.py
app/celery/broadcast_message_tasks.py
app/v2/broadcast/post_broadcast.py
tests/app/broadcast_message/test_utils.py
tests/app/celery/test_broadcast_message_tasks.py
tests/app/v2/broadcast/test_post_broadcast.py

https://www.pivotaltracker.com/story/show/181423293
Until we are confident that broadcasts are being sent
out regularly we have this alert to prompt us to check.
This moves the alert earlier in the code path for broadcast
sending, so that we can be more confident that it will
fire irrespective of something going wrong later on e.g.
if the Celery task it was run in got lost in SQS.
We don't think it's necessary to move the alert back any
further, as an error in that part of the code should be
visible to the user approving the alert (hopefully).
I've done a couple of initial commits of small refactoring,
so best to review this one commit by commit.

Alert earlier when a broadcast is approved

---

app/cloudfoundry_config.py
gunicorn_config.py
tests/app/test_cloudfoundry_config.py

https://www.pivotaltracker.com/story/show/181796569
Based on: https://github.com/alphagov/notifications-api/pull/3465
Although we don't expect any impact from change to the monkeypatched
exception, this allows us to deploy the change separately to switching
Redis providers by making the use of PaaS Redis optional.

Prepare to switch to Redis on PaaS

---

app/dao/fact_billing_dao.py
app/platform_stats/rest.py
tests/app/dao/test_ft_billing_dao.py
tests/app/platform_stats/test_rest.py

code generally lifted almost exactly from the daily_volumes_report, but per provider and only for SMS.
see https://github.com/alphagov/notifications-admin/pull/4206

add new daily sms provider volume report

---

manifest.yml.j2

These routes will be used by prometheus to scrape the `/metrics` endpoint.
The shared prometheus scrapes the `/metrics` endpoint using
the public routes.
The `/metrics` endpoint is provided by the [gds_metrics_python][] which
comes with [bearer-token authentication][] where the token is expected
to be equal to the paas app id.
Each app is configured as a separate target in the shared prometheus
with its app id configured as a GET parameter (e.g.
http://notify-api-production.cloudapps.digital/metrics?cf_app_guid=69c87503-6b53-4c35-XXXX-XXXXXXXXXXXX&cf_app_instance=69c87503-6b53-4c35-XXXX-XXXXXXXXXXXX%3A1&cf_app_instance_index=1)
Each scrape request goes through an nginx proxy which retrieves this
argument from the query string and sets it as a header [[source][]]. This way it
passes the …

Add internal routes for api and api-sms-receipts

---

requirements.in
requirements.txt
tests/app/v2/broadcast/sample_cap_xml_documents.py

`charset-normalizer` is now used by default if installed instead of `chardet` (https://pyup.io/changelogs/beautifulsoup4/#4.11.0). We do have `charset-normalizer` installed because it's a subdependency of the requests library, so it is being used.
This caused the `test_content_too_long_returns_400` to fail since it now thought that the encoding of `ŵ` is
`{'encoding': 'Big5', 'language': 'Chinese', 'confidence': 1.0}`.
There are two options for fixing this
1. change the test content so that it doesn't just contain a single letter - the docs state that you shouldn't run character detection on very tiny content
2. add `chardet` as a requirement, so that the code functions exactly the same as before
I've chose the first option, since this avoids adding a dependency and we should never have …

Update beautifulsoup4 to 4.11.1

---

app/config.py
app/organisation/rest.py
tests/app/conftest.py
tests/app/db.py
tests/app/organisation/test_rest.py

Also when updating existing organisation type to an NHS type, update email branding to NHS branding if none set.
This is part of this story: https://www.pivotaltracker.com/story/show/181415981
Next step: write a migration that will update branding for existing NHS type orgs.

When creating a new NHS org, set default email branding to NHS

---

app/cloudfoundry_config.py
manifest.yml.j2
tests/app/test_cloudfoundry_config.py

These env vars can be set directly in the manifest, like we do for
Template Preview [^1].
[^1]: https://github.com/alphagov/notifications-template-preview/blob/c08036189bf40b37516f921967dd21943bb72a63/manifest.yml.j2#L23-L26

Remove redundant CloudFoundry config code

---

app/cloudfoundry_config.py
manifest.yml.j2
tests/app/test_cloudfoundry_config.py

this ensures all apps are bound to redis (for example any new worker types)
to be merged once manual deploy has been rolled out to all apps/envs.

bind to notify-redis automatically

---

migrations/versions/0369_update_sms_rates.py

This change can be merged before the new rates go live because they won't be used until the start date.
[Pivotal story](https://www.pivotaltracker.com/story/show/181936197)

Add new SMS rates for 1 May 2022 onwards

---

app/billing/billing_schemas.py
app/dao/fact_billing_dao.py
tests/app/billing/test_rest.py
tests/app/dao/test_fact_billing_dao.py

https://www.pivotaltracker.com/story/show/181935935
These are no longer used since [^1] and [^2].
[^1]: https://github.com/alphagov/notifications-admin/pull/4225
[^2]: https://github.com/alphagov/notifications-admin/pull/4229

Remove redundant fields from service usage APIs

---

app/dao/notifications_dao.py
tests/app/dao/notification_dao/test_notification_dao.py

https://www.pivotaltracker.com/story/show/182116071
This can happen in the following scenario (primarily for letters):
1. A service has a mixture of "delivered" and "sending" letters,
which the status task aggregates into two rows:
sending | 123
delivered | 456
2. After the 7 day retention has passed, only the "delivered" letters
will be archived [^1].
3. The status task now looks at the history table [^2], which means
it only sees the "delivered" letters.
4. The "sending" letters are eventually "delivered" and archived (before
the 10 day aggregation cutoff).
5. But the status aggregation task doesn't run.
This commit fixes (5).
[^1]: https://github.com/alphagov/notifications-api/pull/3063
[^2]: https://github.com/alphagov/notifications-api/blob/f87ebb094d9c2037ce6a4c4a38bab87daa868be3/app …

Fix out-of-date rows in ft_notification_status

---

app/dao/fact_billing_dao.py
tests/app/dao/test_fact_billing_dao.py
tests/app/db.py
tests/app/platform_stats/test_rest.py

So far we have only changed sms rates at the start of financial year, now we need to do it more often. This PR improves query that shows usage for services belonging to an org (used on organisation dashboard and organisation usage report), so that it handles multiple sms rates within a single financial year.
As an additional perk, it should make organisation dashboard more performant, as we don't need to call `fetch_sms_free_allowance_remainder_until_date()` anymore. This function queries services for all organisations, so it fetches much more data than we need.
Review commit by commit.
Co-authored-by: Leo Hemsted <leo.hemsted@digital.cabinet-office.gov.uk>
Story ticket: https://www.pivotaltracker.com/story/show/181936289

Show correct sms cost in org view if sms rates change within financial year

---

app/dao/fact_billing_dao.py
app/dao/fact_notification_status_dao.py
app/models.py
app/utils.py
migrations/versions/0373_add_notifications_all_time.py
tests/app/celery/test_reporting_tasks.py
tests/app/test_utils.py
tests/conftest.py

https://www.pivotaltracker.com/story/show/178125825
This fixes a bug where (letter) notifications left in sending would
temporarily get excluded from billing and status calculations once the
service retention period had elapsed, and then get included once again when
they finally get marked as delivered.*
Status and billing tasks shouldn't need to have knowledge about which table
their data is in and getting this wrong is the fundamental cause of the bug
here. Adding a view across both tables abstracts this away while keeping
the query complexity the same.
Using a view also has the added benefit that we no longer need to care when
the status / billing tasks run in comparison to the deletion task, since we
will retrieve the same data irrespective (see the commits for a much more 
detailed …

Use notification view for status / billing tasks

---

requirements.in
requirements.txt

This upgrades marshmallow-sqlalchemy, which can be unpinned now that https://github.com/alphagov/notifications-api/pull/3541 has been merged. It also upgrades all the unpinned dependencies in `requirements.txt`.

Upgrade marshmallow-sqlalchemy plus the unpinned dependencies

---

app/template/rest.py
requirements.in
requirements.txt
tests/app/template/test_rest.py

The only impactful change is the major version itself, where I've
fixed the breaking changes due to the upgrade of PyPDF2 [^1] and
checked there are no deprecation warnings when I run the tests.
[^1]: https://github.com/alphagov/notifications-utils/pull/973

Bump utils to version 56.0.0

---

manifest.yml.j2

We have migrated to our own Prometheus metrics stack and no longer require the `gds-prometheus` backing service used to configure the TechOps shared Prometheus metrics system. This is being decommissioned.
We have been running the new metrics stack alongside the existing service for a few weeks and have tested and correlated collected metrics in both systems for correctness.
Changes to the manifest are non-destructive so the service will need to be manually unbound in each environment using the cf cli.
`cf unbind-service APP_NAME SERVICE_INSTANCE`
See: [alphagov/notifications-cf-monitoring](https://github.com/alphagov/notifications-cf-monitoring)

Remove notify-prometheus metrics service binding

---

app/billing/rest.py
app/dao/fact_billing_dao.py
app/dao/services_dao.py
app/organisation/rest.py
app/platform_stats/rest.py
tests/app/dao/test_fact_billing_dao.py

Previously we had a wild variety of overlapping, top-level
and nested function names that made it very hard to navigate
the code used for the ~3 different reports supported here.
This takes each report and renames the associated functions
so they are clearly grouped together, using "_" to indicate
the nested functions that are only used in the file.
Making this change will make it easier to review future PRs.

Rename fact_billing DAO functions consistently

---

tests/app/dao/test_fact_billing_dao.py

This is part of splitting up [^1], where we had to make a lot
of test changes on top of the complex query changes.
I've split the commits into stages:
- The first commits look at the \_for_service\_ tests.
- The next commits look at the _for_organisation tests.
- The last commits look at the _all_services_sms tests.
By the end of this PR we get to the point where we have a set
of consistent tests for the 4 usage functions we care about:
1. fetch_usage_for_service_annual:
- test_fetch_usage_for_service_annual
- test_fetch_usage_for_service_annual_variable_rates
2. fetch_usage_for_service_by_monthly
- test_fetch_usage_for_service_by_month
- test_fetch_usage_for_service_by_month_variable_rates
- …

Rewrite tests for billing report usage functions

---

app/dao/fact_billing_dao.py
app/platform_stats/rest.py
tests/app/dao/test_fact_billing_dao.py

This makes a few initial changes to the very similar
code we have to calculate SMS usage for organisations,
which we then duplicate for the all service report.
By the end of this PR we have three slightly different
versions of the complex windowing query to calculate SMS
usage. It should be possible to consolidate them into one
query, which we will look at in a follow-up PR.

Support variable rates for all service SMS report

---

tests/app/conftest.py
tests/app/dao/test_fact_billing_dao.py

In response to [^1].
This pushes some of the test setup back into each of the
tests for the 4 billing report functions we're working on
at the moment. We can still use some fixtures to make the
setup more focussed e.g. sample_service vs. create_service.
In the remaining commits, I've also converted the "set_up"
functions into fixtures, to match how we write most tests.
[^1]: https://github.com/alphagov/notifications-api/pull/3559#discussion_r902390463

Further refactoring for billing tests

---

Makefile
scripts/create-droplet.sh
scripts/deploy.sh

Adds two scripts:
1. `scripts/deploy.sh` which uses the CF API to reuse droplets and trigger deployments
2. `scripts/create-droplet.sh` which is a helper script to run locally if you need to deploy something to preview
Best reviewed commit-by-commit.

Deploy droplets

---

app/broadcast_message/utils.py
tests/app/broadcast_message/test_utils.py

Broadcast services in training mode create "stubbed" broadcast messages.
Stubbed messages are not sent to MNO networks and do not result in a real broadcast.
We should not create a ticket or raise an incident when these message types are created as this creates unnecessary noise.

Don't create zendesk ticket if broadcast service is in training mode

---

tests/app/conftest.py
tests/app/v2/inbound_sms/test_get_inbound_sms.py
tests/app/v2/inbound_sms/test_inbound_sms_schemas.py
tests/app/v2/notifications/test_get_notifications.py
tests/app/v2/notifications/test_post_letter_notifications.py
tests/app/v2/notifications/test_post_notifications.py
tests/app/v2/template/test_get_template.py
tests/app/v2/template/test_post_template.py
tests/app/v2/templates/test_get_templates.py

in admin tests we have `client_request` fixture for handling boilerplate around testing user-facing requests - logging in the user, json dumping/loading, creating URLs from endpoints and args, etc.
in api tests we have `admin_request` for doing the same for requests coming from the admin.
now in api /v2/ tests, we have `api_client_request`, for requests made by an api client to our public endpoints! The only difference between this and `admin_request` is that it _requires_ a service id (to create a jwt token for), and has an optional _api_key_type arg that can be 'team', 'test' or 'normal' (the default).
if your service has any number of api keys for the given key type, it'll use an arbitrary one of them. If there isn't one, it'll create one of that type.
if your test is simulating a well …

add api_client_request fixture

---

app/dao/organisation_dao.py
app/organisation/organisation_schema.py
app/organisation/rest.py
tests/app/dao/test_organisation_dao.py
tests/app/organisation/test_rest.py

This adds an endpoint to update the email branding pool for an
organisation. The form that the data comes from allows multiple email
brandings to be added at once, so the endpoint takes this into account.
I've added a new dao function which allows bulk adding to the email branding
pool - this saves having to iterate through each new branding and doing
a database update for each one.
As with other POST endpoints, we check the data using a JSON schema,
however the request from admin should always have the data in the
required format, so I would not expect this to raise a validation error
in production. Instead, it acts to document the endpoint and to ensure
any future changes don't break things unexpectedly.
[Pivotal story](https://www.pivotaltracker.com/story/show/182771318)

Add endpoint to update email branding pool

---

app/schemas.py
tests/app/service/test_rest.py

Some users have been trying to create services with unicode service
names. When it comes to sending emails, not all unicode characters can
be 'cleaned' to the simple ASCII charset which is currently required to
build a valid local email fragment.
Rich unicode local email names can theoretically be supported by
converting them to punycode, but we don't want to do this currently as
it will lead to very peculiar-looking emails and we haven't researched
the potential consequences of this.
For a service to currently send emails, they must put in a basic ascii
service name. Let's help the user avoid the error case by enforcing this
strictly in the first place.
We leave it to the future to research and design a long-term solution
that will perhaps allow rich Unicode service names.
Note: the …

Require limited charset for `Service.email_from`

---

app/v2/notifications/post_notifications.py
tests/app/v2/notifications/test_post_notifications.py

Add a short-term log statement to see whether services are sending
`dict` values in the `personalisation` field outside of the file-upload
use-case.

Add temporary logging to check personalisation use

---

app/clients/document_download.py
app/notifications/validators.py
app/v2/notifications/post_notifications.py
tests/app/clients/test_document_download.py
tests/app/db.py
tests/app/v2/notifications/test_post_notifications.py

This PR adds support for a new key to the `personalisation` field of email notifications: `verify_email_before_download`. If present this field must be True/False - and defaults to False if not present.
When added, it causes the call to document-download-api to include a `verification_email` parameter, which will later be used to store the hashed email against the document for verification as part of the user download flow.
TIcket: https://www.pivotaltracker.com/n/projects/1443052/stories/182950357

Verify email before download parameter

---

app/dao/organisation_dao.py
tests/app/dao/test_organisation_dao.py

When we set the default email branding for an organisation, let's also
add it to the email branding pool for that organisation so that services
can switch out of it and back at a later date if they change their minds
without having to contact us.
Ticket: https://www.pivotaltracker.com/n/projects/1443052/stories/182762788

Add new default email branding to pool

---

requirements.txt

Droplet builds using the python buildpack stopped working caused
by an error thrown while building pycurl from source.
All buildpack versions (despite pinning) started to supply setuptools
65.0.2 which causes the breaking change.
Until this is fixed we need to explicitly pin a working setuptools
version (this is not recommended).
Buildpack issue thread: https://github.com/cloudfoundry/python-buildpack/issues/574

Explicitly pin setuptools to work around buildpack build error

---

migrations/versions/0376_email_branding_pools.py

For all organisations that already have a default email branding, add it
to their email branding pool. If it already exists, do nothing.
Ticket: https://www.pivotaltracker.com/n/projects/1443052/stories/182762873

Populate email branding pool with existing default

---

app/v2/notifications/post_notifications.py
tests/app/v2/notifications/test_post_notifications.py

Before merging and releasing
https://github.com/alphagov/notifications-api/pull/3591, let's check to
make sure that any existing personalisation dicts with `file` keys don't
contain any non-file-upload keys. If they do, we can't use the
`additionalProperties=False` check on the JSON schema and we'll have to
allow clients to send other values (which will be ignored).

Check file upload personalisation dicts

---

app/clients/document_download.py
app/notifications/validators.py
app/v2/notifications/post_notifications.py
tests/app/clients/test_document_download.py
tests/app/v2/notifications/test_post_notifications.py

Update the `POST /v2/notification` endpoint to support a
`retention_period` parameter in file upload fields of personalisation.
This just passes the value directly through to the
document-download-api. Validation on the exact value of the
retention_period will happen in document-download-api - although
notify-api does enforce it as a string.
-----
Just reusing the existing service permission toggle ("feature flag") as we expect to release these at the same time, and we will remove the permission from the code shortly afterwards so the potential confusion over the name/value won't persist.
Ticket: https://www.pivotaltracker.com/n/projects/1443052/stories/183092708

Add support for `retention_period` to API

---

app/dao/organisation_dao.py
app/organisation/rest.py
tests/app/dao/test_organisation_dao.py
tests/app/organisation/test_rest.py

Implements a new organisation DELETE endpoint to remove an email
branding from an organisation's pool.
Ticket: https://www.pivotaltracker.com/n/projects/1443052/stories/182880012

Add endpoint to remove email branding from org pool

---

requirements.txt

setuptools was pinned in #3596 to avoid an issue building python
packages from source when using the CloudFoundry Python buildpack.
This has been resolved in the latest buildpack release v1.7.58
https://github.com/cloudfoundry/python-buildpack/releases/tag/v1.7.58
🚨 **Note:** Only deploy after PaaS have confirmed buildpack update

Unpin setuptools

---

app/email_branding/rest.py
tests/app/email_branding/test_rest.py

If we receive a POST request to create an email branding with a name
that already exists, let's return a 400 rather than 500ing on the unique
constraint violation.

Proper error for unique email branding violation

---

app/clients/document_download.py
app/notifications/validators.py
app/v2/notifications/post_notifications.py
tests/app/clients/test_document_download.py
tests/app/v2/notifications/test_post_notifications.py

`Confirm email` is the wording we prefer in documentation and guidance, so let's keep that consistent in the codebase as well.
This will temporarily break the feature until document-download-api is updated, but that should be fine as the feature isn't released yet.

Rename `verify email` to `confirm email`

---

app/celery/scheduled_tasks.py
app/config.py
tests/app/celery/test_scheduled_tasks.py

Events are used to track certain actions users might take (eg logging in), and contain PII. Because of this we shouldn't keep this data forever. We've agreed a 1-year retention period and should regularly purge any data older than this.
Also needs https://github.com/alphagov/notifications-credentials/pull/295

Add scheduled nightly task to purge old events

---

app/v2/notifications/notification_schemas.py
tests/app/v2/notifications/test_post_notifications.py

We've had a number of 500s thrown today because of references that were
~100k long. Obviously that's not particularly sensible or feasible. Past
a certain length Postgres also just says no. So let's return a more reasonable 400 if the client reference exceeds 1000 characters.
[Sample kibana error](https://kibana.logit.io/s/9423a789-282c-4113-908d-0be3b1bc9d1d/app/kibana#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2022-09-30T11:00:26.046Z',mode:absolute,to:'2022-09-30T11:00:44.990Z'))&_a=(columns:!(message),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'logstash-*',key:requestId,negate:!f,type:phrase,value:'2090767d90ab1d8c6d6e39cf9032f606'),query:(match:(requestId:(query:'2090767d90ab1d8c6d6e39cf9032f606',type:phrase))))),index:'logstash …

Limit client_reference to 1,000 characters

---

requirements.in
requirements.txt

Major changes:
> ## 57.0.0
>
> * Breaking changes to `field.Field`:
>
>  - The `html` argument must now be `escape` or `passthrough`. `strip` is no longer valid
>  - The default value of the `html` argument is now `escape` not `strip`
>
> * Removal of `formatters.strip_html`
Full diff: https://github.com/alphagov/notifications-utils/compare/56.0.0...57.0.0

Bump utils to 57.0.0

---

requirements.in
requirements.txt

Fixes an issue when special characters are used in placeholders:
https://github.com/alphagov/notifications-utils/pull/980

Bump utils to 57.0.1

---

app/schema_validation/__init__.py
app/v2/notifications/notification_schemas.py
app/v2/notifications/post_notifications.py
tests/app/v2/notifications/test_post_notifications.py

If a user sends the wrong kind of data/value for the new send-a-file/document download security features, let's provide a user-friendly error message.
I would've ideally liked to do this as part of the generic incoming notification JSON schema, but in order to do that we'd need to use a `oneOf` subschema to allow for multiple data types and different validation depending on the vlaue of personalisation fields. When we do this, we lose the ability to (cleanly) provide explicit error messages about what exactly is wrong with the input, because JSON Schema wraps the root error message in some contextual one about all of the sub-schemas failing to validate.
So we've decided to just do the validation on known-file upload personalisation, which allows us to more cleanly present the error to the …

Add validation for send-a-file upload dicts

---

migrations/versions/0378_remove_doc_download_perm.py

We added a service permission to gate the new document download security features. Now that these have been released, let's remove the permission.

Remove temp doc download service perms

---

app/broadcast_message/translators.py

If not explicitly told what the encoding of the data is, BeautifulSoup
tries a few different ways to guess what it is, using things like
cchardet/charset_normalizer. On one of our "broadcast alert content too
long" tests, this returns iso_8859_16 for the data.
This character encoding is known on most developer machines and so the
text is treated as being this encoding. However, that is actually the
wrong encoding - it's actually a utf-8 string.
This test passes on CI because the instances running the tests don't
recognise the iso_8859_16, and so disregard that encoding and try the
next suggested one - utf-8.
We expect all of our broadcast messages to be sent in utf-8, so let's
tell BeautifulSoup that explicitly.
Ctrl+f for "ENCODING: "
We load the doc into beautifulsoup 3 times: one with …

Force BeautifulSoup to use utf-8 encoding

---

app/dao/users_dao.py
migrations/versions/0379_update_archived_users.py
tests/app/dao/test_users_dao.py

We're now storing a user's original email address in the events table (for 1 year) when we archive a user. However, we still have historical information in the users table (email address and name) which we should redact. We should also insert their original email address into their archive events (where we still have an archive event for them, as we delete events over 1 year old).
In prod there are only 140 archived users so I'm not worried about migration efficiency particularly.
We don't have a framework currently for testing migrations in code. There's a library called `pytest-alembic` that should work but it didn't seem trivial to implement, so for now will settle for manual testing.
This is quite laborious and fiddly so please take care :) It tests four cases: an old archived …

Delete user data and migrate historical archive_user events

---

app/email_branding/email_branding_schema.py
app/models.py
migrations/versions/0380_email_branding_cols_.py
tests/app/email_branding/test_rest.py

Now that we're working to make it possible for users to create their own email branding, let's keep a record of who's created or updated the branding and when in case we ever need to look back and see what's happened.
We also want to emit audit events for changes, but for now we'll do that from the admin app - as that's consistent with our current process. We may look to centralise this back to the API in the future to provide consistency and centralise that responsibility, but not today.

Add created_at/by, updated_at/by columns to EmailBranding

---

app/dao/organisation_dao.py
app/models.py
app/organisation/rest.py
migrations/versions/0381_letter_branding_to_org.py
tests/app/dao/test_organisation_dao.py
tests/app/organisation/test_rest.py

This creates letter branding pools in the database and adds a REST endpoint to get all items in the pool, since this is the first endpoint that will be needed for the next stage of the work.
**Migration for "letter_branding_to_organisation" table**
This adds a migration for a new table, `letter_branding_to_organisation`, which matches the `email_branding_to_organisation` table.
The table has two columns, `organisation_id` and `letter_branding_id`, and the composite primary key on these means that we don't need to create a separate unique constraint because uniqueness is already enforced.
This uses a `db.Table` instead of a `db.Model` (which is what `email_branding_to_organisation` uses) in models.py. We don't need a model class for the join table since we'll only be accessing the …

Create letter branding pools

---

requirements.in
requirements.txt

This pulls in the updated URL escaping that prevents pre-escaped %-encoded URL values ending up rendered as their unescaped characters (eg a URL sent to us as `/blah?redirect=%2Flogin` was ending up in user inboxes as `/blah?redirect=/login` - which can be semantically different to the target server).
Would like to wait 24-48 hours before merging this to give the initial reporter time to acknowledge that this change is going in.

Bump notifications-utils to 57.1.1

---

app/dao/organisation_dao.py
app/organisation/organisation_schema.py
app/organisation/rest.py
app/service/rest.py
tests/app/dao/test_organisation_dao.py
tests/app/organisation/test_rest.py

This adds an endpoint and new dao function to update the letter branding
pool for an organisation. The form that the data comes from allows multiple
letter brandings to be added at once, so the endpoint and dao function take
this into account by allowing the new brandings to be added in bulk.
As with other POST endpoints, we check the data using a JSON schema,
however the request from admin should always have the data in the
required format, so this acts more as documentation than a check that
might fail.

Add endpoint to update letter branding pool

---

app/dao/organisation_dao.py
app/organisation/rest.py
tests/app/dao/test_organisation_dao.py
tests/app/organisation/test_rest.py

This adds a new endpoint to remove a particular letter brand from the letter branding pool for an organisation. As with the email branding equivalent, there is a check that you're not removing the default and that the brand you're trying to remove is in the pool. However, we do also do the same checks in admin, so do not expect these errors to be raised.

Add endpoint and dao function to remove letter branding from pool

---

app/config.py
app/dao/organisation_dao.py
app/organisation/rest.py
migrations/versions/0382_nhs_letter_branding_id.py
tests/app/conftest.py
tests/app/dao/test_organisation_dao.py
tests/app/dao/test_services_dao.py
tests/app/db.py
tests/app/organisation/test_rest.py

**Give NHS letter branding the same ID in each environment**
We gave the NHS email branding the same ID in each environment, which simplifies the code to give it to organisations and to use it on forms.
This does the same for the NHS letter branding ID. The logo exists in all environments. We delete the row in the `letter_branding` table from all environments apart from production, then re-insert it to the other environments with the ID that exists in production.
**Add NHS letter branding to pools and org when creating an NHS org**
When an organisation is created with one of the NHS org types, we now set its letter branding to the NHS brand and add the NHS brand to its branding pool.
We are already setting up NHS branding for services which are NHS services, so this change won't really …

Give NHS letter branding the same ID in each env and give NHS orgs NHS branding when created / updated

---

app/dao/webauthn_credential_dao.py
app/models.py
app/user/rest.py
app/user/users_schema.py
migrations/versions/0382_webauthn_cred_logged_in_at.py
tests/app/user/test_rest.py
tests/app/webauthn/test_rest.py

If the admin passes through a credential id when logging a user in (which it will once https://github.com/alphagov/notifications-admin/pull/4452 is merged), then set `logged_in_at` to be the current timestamp in the database.

Add webauthn_credential.logged_in_at

---

migrations/.current-alembic-head
migrations/env.py

this new file isn't used in our code anywhere, however, if you have a migration in a PR and someone else merges a different migration, this'll mean they also update this same file, thus you'll get a merge conflict and will be forced to rebase and fix the migration

write the current alembic head to file when running bootstrap

---

app/dao/organisation_dao.py
tests/app/dao/test_organisation_dao.py

When we update an organisation to be one of the NHS org types we want to add the NHS branding to the pool. We were already doing this, but had missed one edge case - we weren't adding to the pool in cases where the organisation already had a default branding set.
We now:
* Always add NHS branding to the pool if we're setting the org type to NHS
* Add branding to the pool if it's being set as the default for an org

Always add NHS branding to pools when updating an org

---

migrations/versions/0384_add_nhs_to_letter_pools.py

This migration adds the NHS letter branding to the branding pool for all NHS organisations. There will be another migration later to add the default branding to the pool for all organisations. However this migration deals with the scenario where an NHS organisation does not have NHS branding as its default - we still want to add it to the pool in this case.
**Merge after**

Migration to add NHS letter branding to letter branding pools

---

migrations/.current-alembic-head
migrations/versions/0385_letter_branding_pools.py

This adds the default letter branding for each organisation to the letter branding pool. We have already added the NHS branding for NHS orgs in a previous migration. In future work, we will look at adding brandings for services to the pool too.

Add default letter branding for orgs to branding pools

---

app/email_branding/rest.py
app/models.py
migrations/.current-alembic-head
migrations/versions/0386_email_branding_alt_text.py
tests/app/email_branding/test_rest.py

we set the text to equal the name if it's not passed in from the admin app. at the moment we always pass in, but just an empty string. really, we'd much rather just pass in null and set it to null.
also, add alt-text. it's nullable for now but we'll start setting it on the admin app and passing it through (and eventually we'll migrate old values and make it non-nullable.
question for reviewer: should the logic for deciding the name based on alt text be written in the admin app or here?

Email branding add alt text

---

app/celery/scheduled_tasks.py

https://trello.com/c/qLP6Skv2/65-add-cronitor-task-for-watching-scheduled-jobs
This will ensure it will be run every 15 minutes and if it doesn't then we will get an alert.
How to review
- first review https://github.com/alphagov/notifications-credentials/pull/304
- take a look at the job in Cronitor, click 'edit' and review all of the settings. 
- ensure the name of the cronitor job in this PR matches the key in the credentials repo in https://github.com/alphagov/notifications-credentials/pull/304

Add cronitor for run-scheduled-jobs

---

app/celery/scheduled_tasks.py
app/config.py
requirements.in
requirements.txt
tests/app/celery/test_scheduled_tasks.py

Every (week)day, generate a report and log it into Zendesk listing all of the new email brands created since the last weekday so that they can be manually reviewed for quality. We may want to tweak them or remove them from an organisation's branding pool if it doesn't make sense for the brand to be more widely available.

Generate daily report for new email brands

---

app/delivery/send_to_providers.py
app/email_branding/rest.py
app/models.py
migrations/.current-alembic-head
migrations/versions/0387_migrate_alt_text.py
requirements.in
requirements.txt
tests/app/db.py
tests/app/delivery/test_send_to_providers.py
tests/app/email_branding/test_rest.py
tests/app/service/test_rest.py

Once the above PR goes in, we'll be ready to start using the alt text field.
1. Migrate the old data where `text` is `''` to null, to keep our data consistent.
2. Enforce that exactly one of alt_text and text are set. We only use alt_text if text isn't specified. I don't want us setting alt_text when it won't be used and wondering why it isn't working, for example
3. Catch that constraint being tripped and return a nice error message. (It's unlikely this'll ever be tripped since the frontend will also check for this consistency, but still nice to be clean)
4. Update tests to make sure they're also compliant with the constraint

Email branding - use the alt text field

---

migrations/.current-alembic-head
migrations/versions/0388_populate_letter_branding.py

Previous migrations partially populated the letter branding pools by
- adding NHS branding to the pool for NHS organisations
- adding the default brand for each service to the pool
This migration adds every letter branding being used by a service to the pool for that service's organisation. We'll need to manually check the letter branding pool contents after this to remove any brands we don't think should be there.

Fully populate letter branding pools

---

app/dao/email_branding_dao.py
app/email_branding/email_branding_schema.py
app/email_branding/rest.py
tests/app/dao/test_email_branding_dao.py
tests/app/email_branding/test_rest.py

alt text is not unique, it doesn't need to be. however, names should be unique so people can distinguish email branding options in a list of them.
this endpoint takes in a prospective alt_text, and checks the DB. if there's nothing in the DB with that name, it returns the alt text as provided.
If there is, it tries `{name} (alternate 1)`, and goes up by 1 each time. It compares case-insensitive, though always returns a name with the same case as the input alt_text.
If a branding has 100 alternates already, it gives up. We should probably look into what's happening before that.

add an endpoint to generate a name for a provided alt text

---

app/dao/jobs_dao.py
app/job/rest.py
tests/app/dao/test_jobs_dao.py

The function used to find a job to cancel checks two things:
1) That it's in the SCHEDULED state
2) That it's scheduled for the future.
This means that a job which is scheduled to send, but past the scheduled
time, cannot be cancelled. But there are cases where users may want to
cancel these jobs still. We know that a job hasn't started processing if
the state is SCHEDULED, so it should still be safe to cancel even if the
ideal processing start time has passed. Let's remove the check on
scheduled_for and only require that a job's state is SCHEDULED to
determine if it's cancellable.

Allow any job in scheduled state to be cancelled

---

app/celery/scheduled_tasks.py
app/config.py
tests/app/celery/test_scheduled_tasks.py

We're rolling out some changes soon to allow services to enable inbound
SMS by themselves. At the moment they have to contact support and we'll
manually give them a number, which means we are constantly aware of how
many numbers we have left and can spot when we might need more.
If users can take from the pool themselves, without any oversight, we
need some monitoring in place to alert us automatically that we need to
ask for more numbers.
We don't know how quickly numbers will get used, but expect that a
weekly report should be fine, and that 50 numbers are unlikely to be
used up within the (roughly) week that it takes for new numbers to be
given to us.
Related credentials PR: https://github.com/alphagov/notifications-credentials/pull/306

Weekly report on low free inbound sms numbers

---

Makefile

At the moment we parallelize the tests across 4 cores.
On some machines more cores are available, so using them makes the tests run faster.
pytest-xdist will automatically pick the best number of CPU cores when passed `auto` as the value for the `-n` flag<sup>1</sup>.
This matches what we do in the admin repo:
https://github.com/alphagov/notifications-admin/blob/46b2415fd2a96af4a6503d22f4bad80eaf496f98/Makefile#L67
***
***
1. https://pytest-xdist.readthedocs.io/en/latest/distribution.html
2. Run on a 16 inch Macbook Pro with an Apple M1 Pro chip

Run tests on recommended number of CPU cores

---

app/broadcast_message/utils.py
app/celery/nightly_tasks.py
app/celery/scheduled_tasks.py
app/notify_api_flask_app.py
application.py
run_celery.py
tests/conftest.py

Add the env check to the daily branding review to ensure we don't send it from local/from staging/etc. We already do this check in a bunch of places as seen in the other commits.
--------
I was fed up of us having sketchy config checks everywhere. `current_app` returns the flask app, so create a subclass of `Flask` that has a few helper methods to reduce calls to the config directly for checks like this. Over time we can add more checks elsewhere if we want to.

don't send daily branding review on other envs (and refactor how we access config)

---

app/config.py
app/notify_api_flask_app.py
tests/app/broadcast_message/test_utils.py
tests/app/celery/test_tasks.py
tests/app/v2/notifications/test_post_letter_notifications.py

Confusingly, the OS environment variable `NOTIFY_ENVIRONMENT` is set to equal the paas space, so is `production`, however we then set `current_app.config["NOTIFY_ENVIRONMENT"]` to equal `live`. This has led to lots of confusion, as seen in all the places in code where we're checking if the environment is one of those two values. Not even we are certain which environment we're on!
This PR fixes that by renaming that variable to "production" and ensuring that wherever it is used we refer to `production` instead of `live`.
Note, the variable goes in to our statsd mappings as the `space` value. Then, our prometheus config replaces `live` with `production`.
Note, there's two other notable places that still talk about "live" with regards to the environment:
1. The celery queues. Migrating …

Rename live to prod

---

README.md

FLASK_DEBUG=1 is the proper way to have the debug stack trace screen appear
(this is a very underwhelming code change - the key thing is I also renamed the environment variable in my `environment.sh`)

flask_env is deprecated

---

app/celery/reporting_tasks.py
app/commands.py
app/config.py
app/dao/fact_billing_dao.py
tests/app/dao/test_fact_billing_dao.py
tests/app/organisation/test_rest.py
tests/utils.py

The org dashboard view can be really slow for some orgs with lots of services and notifications. The queries that power this view haven't been optimised much, and so we can make 100s or 1000s of round trips to the DB. Let's refactor some of the supporting logic to make queries in bulk so that we have fewer round trips, and hopefully (much) faster page loads.
With the test case provided below, on my machine we go from ~1250 DB queries to 11, and from 8.6s to 0.3s
This will also speed up the nightly billing fact generation task (create-nightly-billing-for-day). Over the last 7 days in prod it's taken approx 300s each time.
On my machine, with the local test data from below, on `main` it takes 18 seconds and on this branch it takes <1 second. (the log messages don't have any decimal …

Optimise the queries powering the org dashboard page

---

tests/conftest.py

Freezegun has an edge case interaction with `prompt_toolkit` that ends up breaking commands in ipdb (typed text doesn't appear on the prompt, which makes it really hard to use).
There's a PR on freezegun to ignore this module, which would mean we don't need to manually configure it, but for now it's not merged.

Ignore prompt_toolkit module for freezegun

---

app/inbound_number/inbound_number_schema.py
app/inbound_number/rest.py
tests/app/inbound_number/test_rest.py

We already have an endpoint to add an inbound number to a service - `.add_service_sms_sender` is used for both adding new sms senders and adding a particular inbound number to a service. We want to be able to add an inbound number to a service without specifying the exact number to add. This adds a new endpoint which handles adding any inbound number and a particular inbound number to the service.
`.add_service_sms_sender` will be changed later so that it doesn't deal with inbound numbers but only deals with adding sms senders.

Add new endpoint for adding inbound number to a service

---

migrations/.current-alembic-head
migrations/versions/0391_add_go_live_columns.py

This is so we can track:
- which organisations are allowed to approve their own go live requests (this is effectively a feature flag, but we don’t have permissions for organisations like we do for services)
- which services are currently waiting to go live, so we can filter on this attribute
Later we can:
- add default `False` values for these columns
- make them non-nullable 
- have the API return them for use in the admin app

Add columns for managing go live requests

---

app/celery/scheduled_tasks.py
tests/app/celery/test_scheduled_tasks.py
tests/app/db.py

For the daily email branding report, it doesn't make sense to show brands created by platform admins because the report goes to platform admins for review.
Let's exclude those brands.

Only report on brands created by non-admins

---

app/service/rest.py
app/service/service_senders_schema.py
tests/app/service/test_rest.py

We've added a new endpoint for adding an inbound number to a service (either a specific inbound number or a random one). This means that we can simplify the `add_service_sms_sender` endpoint so that it only deals with adding a "normal" sms sender to a service.

Simplify `add_service_sms_sender` endpoint

---

app/models.py
migrations/.current-alembic-head
migrations/versions/0392_go_live_cols_non_nullable.py

Null values don’t make sense for these columns – they should either be `true` or `false`
***
Depends on:

Make go live columns non nullable

---

app/celery/nightly_tasks.py
requirements.in
requirements.txt
tests/app/celery/test_nightly_tasks.py

We've had the letter-checking task run the last few days, which opens a ticket with DVLA suggesting that they've fallen behind processing letters.
This isn't the case, as we've had two bank holidays this week. Let's respect these and properly look beyond them.

Update letter-checking task to ignore bank holidays

---

app/celery/scheduled_tasks.py

It's good practice to provide specific ordering on queries. This also stops flakiness in the `test_zendesk_new_email_branding_report` test.

Select email brandings with ordering

---

app/notifications/validators.py
tests/app/notifications/test_validators.py

There is a theoretical edge case for the new rate limits when posting bulk jobs.
If the first notifications sent by a service on a given day are a bulk job, and that bulk job exceeds the service's limits, we don't fail the job in advance.
This is unlikely to have ever been hit in reality, as bulk jobs are limited to 100k and our new per-channel limits are going to be 250k, but we should fix this anyway to 1) prevent confusion and 2) not cause any future issues if we dropped the limits in the future.
---
(When we roll out the new rate limits we also need to update the frontend to display the per-channel limits rather than the service-total rate limit if a bulk job hits this limit, but will address that in an admin PR separately/at a later date)

Fix edge case for bulk sending

---

app/dao/letter_branding_dao.py
app/email_branding/email_branding_schema.py
app/letter_branding/letter_branding_rest.py
app/letter_branding/letter_branding_schema.py
tests/app/dao/test_letter_branding_dao.py
tests/app/letter_branding/test_letter_branding_rest.py

this is almost identical to the email branding[^1], except we don't have the concept of alt text for letter branding so we can rename the endpoint slightly.
unfortunately with the separate db models for both of them, it wasn't trivial to DRY these up with our current patterns.
[^1]: https://github.com/alphagov/notifications-api/pull/3651

find a unique name for letter branding.

---

run_celery.py

Am interested to know if this helps anyone else with running celery locally?
```
import 'pycurl' # <_frozen_importlib_external.ExtensionFileLoader object at 0x104dd7a60>
...
[2022-12-29 20:14:49,626: INFO/MainProcess] celery@anima.local ready.
[2022-12-29 20:12:36,698: WARNING/MainProcess] # trying /Users/sam/work/gds/notifications-api/venv/lib/python3.9/site-packages/kombu/asynchronous/http/curl.cpython-39-darwin.so
[2022-12-29 20:12:36,698: WARNING/MainProcess] # trying /Users/sam/work/gds/notifications-api/venv/lib/python3.9/site-packages/kombu/asynchronous/http/curl.abi3.so
[2022-12-29 20:12:36,698: WARNING/MainProcess] # trying /Users/sam/work/gds/notifications-api/venv/lib/python3.9/site-packages/kombu/asynchronous/http/curl.so
[2022-12-29 20:12:36,698: WARNING/MainProcess] # trying …
```

Import pycurl early to help run celery locally

---

README.md
application.py
manifest.yml.j2
newrelic.ini
requirements.in
requirements.txt
run_celery.py

We add basic APM instrumentation for NewRelic. This will inject tracing
headers that filter through to any other instrumented apps and send them
to NewRelic so that we can see how requests travel through our services
and how long each span takes. This should help us highlight slower areas
of the codebase which we can then investigate and optimise.
We only send APM information - not logs - here, and we heavily limit the
information sent so that we hopefully aren't gathering much/any PII. We
also only deploy to dev and preview at the moment, so there's no risk of
this code gathering real user data for now. This will allow us to safely
investigate the tool and see whether it's something useful for us.
Required env vars:
`NEW_RELIC_LICENCE_KEY`

Add NewRelic to dev+preview

---

app/celery/scheduled_tasks.py
tests/app/celery/test_scheduled_tasks.py

The flaky test was solved by adding `tick=true` to ensure that the timestamps of the two email brandings are different, and thus ordering is respected.
Then I solved a BST bug we would have discovered in march when it would have picked up the wrong branding in the zendesk report and always been a day out.

Fix zendesk email branding - flaky test and BST bug

---

migrations/.current-alembic-head
migrations/versions/0395_migrate_rate_limits.py

We want to start applying the new per-channel rate limits soon. This migration will set the limits at the levels we want to apply:
For services in trial mode, 50 for each notification channel.
For live services, 250k for emails and SMS, and 20k for letters.
We only overwrite the limits if they're at the current default (insanely high) value, which means that any rate limits we've set manually for specific services won't be affected.
**Note**: need to merge+release https://github.com/alphagov/notifications-admin/pull/4560 first

Migrate per-channel rate limits

---

app/notifications/validators.py
tests/app/notifications/test_validators.py

We've now moved over to per-channel limits, so let's stop checking the daily rate limit for all channels.

Stop checking all-channel rate limits

---

app/celery/scheduled_tasks.py
app/config.py
app/dao/notifications_dao.py
tests/app/celery/test_scheduled_tasks.py
tests/app/dao/notification_dao/test_notification_dao.py

Best reviewed commit by commit
1. [Grafana panel for slow sms delivery](https://grafana-notify.cloudapps.digital/d/icjsQ-MWk2/notify-summary?viewPanel=51&orgId=1) will need relabelling to be 5 minutes rather than 4 minutes
2. New statsd mapping will be need adding to https://github.com/alphagov/notifications-aws/blob/main/paas/statsd/statsd-mapping.yml so the statsd metric can be picked up by prometheus and then added to some panels in Grafana

Change threshold for slow sms delivery and add more delivery metrics

---

app/celery/tasks.py
app/dao/returned_letters_dao.py
tests/app/dao/test_returned_letters_dao.py

previously, if a returned letter was referenced in two separate DVLA reports, we would update the existing row in the database - updating the `reported_at` date and setting the `updated_at` timestamp.
However, this leads to confusing behaviour - the user might have downloaded an old report, then when they check again, that report will have _less_ rows, and the new report will have rows that they may have already handled and actioned a month prior.
Change the code so that if the row already exists, it just skips the insert.

don't update returned letters

---

app/models.py
migrations/.current-alembic-head
migrations/env.py
migrations/versions/0400_non_nullable_ids.py
migrations/versions/0401_prefix_sms_non_null.py
migrations/versions/0402_inbound_sms_history.py

When we make model changes it's nice to be able to use alembic to autogenerate the migration changes.
Unfortunately for a while now it's been generating instructions unrelated to the changes a dev picks up, because things have fallen out of sync over time.
This removes all of the differences except 2 indexes, which are slightly trickier to unpick because we haven't got naming conventions for indexes (see: https://alembic.sqlalchemy.org/en/latest/naming.html).
It also leaves alone the `research_mode` columns that are addressed here: https://github.com/alphagov/notifications-api/pull/3703

Fix some auto-generated migrations

---

templates/tasks/scheduled_tasks/new_email_brandings.html
tests/app/celery/test_scheduled_tasks.py

We've added useful information to the email branding view (not edit) page about whether it's an org default or in use by a service. This feels like more useful overview information to see when reviewing the branding as opposed to immediately seeing the edit branding form.
Probably optional and could be less useful if/when we merge https://github.com/alphagov/notifications-admin/pull/4608

Change email branding report page link

---

app/clients/letter/dvla.py
requirements.in
requirements.txt
tests/app/clients/test_dvla.py

i've already used these locally to great effect to reset the api keys for the tools account
see https://developer-portal.driver-vehicle-licensing.api.gov.uk/apis/authentication-api/authentication-api-description.html for details - the json version there is a bit more complete too

password and api key reset functions

---

app/celery/scheduled_tasks.py
app/config.py
manifest.yml.j2
tests/app/celery/test_scheduled_tasks.py

Adds a task which runs weekly to generate a report for DWP on SMS notifications sent in the last week. The query and zendesk ticket ID are provided through environment variables. We will (🤞) review this way of doing things in Q1 '23 as part of a wider look at reporting.
I've made it so that the entire query for the DWP reject is injected via an environment variable because:
1) It means we can tweak the query without doing a deploy
2) It felt odd to hard-code the query because it contains some service-specific info (the service ID). We could have just injected the service ID via env variables, but that also felt weird and we'd have to make code changes if we altered the query to include some other identifier.
3) Using a dict means we can also provide the report filename as the key

Automate DWP report for zendesk

---

.pre-commit-config.yaml
requirements_for_test.txt

Installing isort from scratch via pre-commit has broken due to a release from Poetry.
https://levelup.gitconnected.com/fix-runtimeerror-poetry-isort-5db7c67b60ff
The solution is to bump to the latest isort version.

Bump isort to 5.12.0 

---

app/clients/letter/dvla.py
tests/app/clients/test_dvla.py

The `send_letter` method now calls the DVLA endpoint to create a print job. All the data needed by the method is passed to it as arguments to avoid the method needing to access the database or S3. International letters are not supported yet.
We raise custom errors based on the DVLA response, but these will be handled in a later story.

Add `send_letter` method to the DVLA client

---

app/celery/provider_tasks.py
app/clients/letter/dvla.py
tests/app/celery/test_provider_tasks.py

The `DVLAClient` has a method to send a letter to the DVLA using their api. This adds a task, `deliver_letter`, to call that method. We need to get information about the letter and the file from S3 to pass as arguments to the client.
Some errors are retried using exponential back-off. If the error type can't be retried or we've reached the maximum number of retries, we put the letter into `technical-failure` status and raise a `NotificationTechnicalFailureException`.
If the API call to the DVLA is successful then we update the letter to `sending`.

Add new `deliver_letter` task

---

app/celery/tasks.py
tests/app/celery/test_ftp_update_tasks.py

The response files we receive from the DVLA have no header row and are in this format:
```
AAAAAAAAAJH3KUL1|Sent|2|Sorted
BBBBBBBBBJ31DT5Q|Sent|1|Sorted
CCCCCCCCCVM6C9GN|Sent|2|Sorted
```
We will soon be receiving the despatch date in the data too, so the data will start taking the following format:
```
AAAAAAAAAJH3KUL1|Sent|2|Sorted|2023-02-23
BBBBBBBBBJ31DT5Q|Sent|1|Sorted|2023-02-23
CCCCCCCCCVM6C9GN|Sent|2|Sorted|2023-02-23
```
This updates our code to not give an error if it receives the extra field. We will start using the extra field later.

Allow DVLA response files to have an extra field

---

app/celery/provider_tasks.py
app/clients/letter/dvla.py
tests/app/celery/test_provider_tasks.py
tests/app/clients/test_dvla.py

In calls to the DVLA API, let's pass our notification reference through
as the businessIdentifier. This maps to the 'reference' we get back from
DVLA in the daily delivery receipt files, so if we send the reference
through the API then we should be able to match delivery receipts up
automatically without having to make any specific changes.

DVLA API letter reference

---

app/clients/letter/dvla.py
tests/app/clients/test_dvla.py

Updates the DVLA API client to accept and appropriately handle international letters.
Note: this meets the DVLA API spec (https://developer-portal.driver-vehicle-licensing.api.gov.uk/apis/printhub-request-api/printhub-request-api.json), but the API doesn't currently accept this request returning an error. Waiting for their clarification...
---
We'll probably be updating the interface for `dvla_client.send_letter` to take a PostalAddress object soon rather than `address_lines: list[str]`. But for now, we keep it as-is, and so rely on the postage to determine whether an address is international or not. If we revisit that decision (when PostalAddress.international is available) we may need to put some further thought into how to reconcile if notification.postage and PostalAddress.postage are …

Support sending international letters via DVLA API

---

app/celery/scheduled_tasks.py
app/clients/letter/dvla.py
app/config.py
tests/app/celery/test_scheduled_tasks.py
tests/app/clients/test_dvla.py

Take a look commit by commit cos there's a lot of nuance here that I'm not sure I've got right
If we get a 401 when creating a jwt token, we should assume the password is out of date. Clear that password from the cache and throw a Retryable exception. Nice and simple.
If we get a 401 when changing our password, we should assume that is because the old password is out of date. The problem is there are two cases here and we can't distinguish between each:
* it expired naturally - we'll need to manually reset it by email. This is a bad state. This should never happen ideally since we reset the password every month (and it normally expires every ninety days)
* it has already been reset by a different process from "old" to "new". Because we clear the cache within the lock, we know that we'll …

Dvla change password/api key scheduled tasks

---

app/config.py
manifest.yml.j2
scripts/paas_app_wrapper.sh
tests/app/test_config.py

This adds a new queue, `send-letter-tasks`, and worker `delivery-worker-sender-letters` that will be used for sending letters to the DVLA via the new API.

Add new queue and worker for sending API letters

---

tests/app/clients/test_dvla.py

This flaky test was patched in another PR but actually we should
probably not use freezegun and actually just check the static value is
what we expect it to be.
Flaked test: https://concourse.notify.tools/teams/notify/pipelines/apps/jobs/build-api-main/builds/289

Don't use freezegun for this test

---

app/dao/fact_billing_dao.py
tests/app/dao/test_fact_billing_dao.py
tests/app/db.py

This report was returning multiple rows for each service where the only difference between them was the free allowance data. We only want it to return one row per service and we only care about the free allowance at the time of the specified end date for the report.
The annual_billing subquery in the `fetch_volumes_by_service` was returning a row for each row in the annual billing table like this:
```
financial_year_start, service_id, free_allowance
(2022, service_1_id, 40000),
(2021, service_1_id, 150000),
(2022, service_2_id, 40000),
(2022, service_3_id, 10000),
(2020, service_3_id, 25000),
(2021, service_3_id, 150000),
```
We now use a window function in the subquery so that it also returns the latest (maximum) financial_year_start for each service ID:
``` …
```

Make volumes by service report return one row per service

---

Makefile
entrypoint.sh
gunicorn_config.py
scripts/run_app_paas.sh
scripts/run_locally_with_docker.sh

The command: make run-gunicorn-with-docker now uses the gunicorn server in front of the flask application in Docker.
Gunicorn error logs are no longer written to file, these are now output as stderr.
The server port variable was defined by the EXPOSED_PORTS parameter.

Run gunicorn in front of flask in Docker entrypoint

---

migrations/.current-alembic-head
migrations/versions/0406_1_april_2023_sms_rates.py

These can be added before they are needed since we check the `valid_from` column when deciding which rate to use.

Add new SMS rates for 1 April 2023

---

app/celery/letters_pdf_tasks.py
app/config.py
tests/app/celery/test_letters_pdf_tasks.py

bypass the ftp app on dev/preview/staging.
This doesn't include any selective enabling (for example per service). The entire env is either FTP or API for now.
also, perhaps slightly more contentious - add an optional print deadline to the collate letter task. This is necessary for running performance tests because when you call `collate-and-send` without any args, it runs for everything ready to send since the _last 5:30 we went past_. So if you run it at midday, it'll only look at letters sent up to 5:30pm yesterday. This makes it tough to manually trigger runs locally/on preview, since you often need to change the created_at in the database, and then move the file in s3, which is a pain.
By allowing us to pass in an optional arg to define when we want the print deadline to be, we can …

Send letters via DVLA api on development, preview and staging

---

app/cloudfoundry_config.py
manifest.yml.j2
tests/app/test_cloudfoundry_config.py

What
----
Currently, when establishing a database connection, the VCAP_SERVICES environment variable is given priority over SQLALCHEMY_DATABASE_URI.
This proposed change would prioritise the SQLALCHEMY_DATABASE_URI variable over VCAP_SERVICES, provided that it is present. In the absence of SQLALCHEMY_DATABASE_URI, VCAP_SERVICES will be used as a fallback.
Why
----
We need to switch to fixed credentials for the database before we do the database cutover, while still using VCAP_SERVICES for Redis. This pull request will facilitate that change.

Allow SQLALCHEMY_DATABASE_URI to override the database settings inside PaaS

---

app/models.py
app/schemas.py
migrations/.current-alembic-head
migrations/versions/0407_letter_attachments.py
tests/app/template/test_rest.py

Build out the DB model for letter attachments with basic fields. This table represents another PDF that has been uploaded to Notify and can be 'attached' to the end of a letter template. This will allow reusable formatted content (eg a form) to be attached to a letter.
---
~The orginal ticket suggests an `archived` field. I've left that off here as I don't think we need to denormalise this information - if there are no records with `template.letter_attachment_id == this_letter_attachment.id` then `this_letter_attachment` isn't in use. It saves us from a potentially-weird situation where we have `archived=true` on a letter attachment but it's still referred to by a live template.~ Added back archived_at/archived_by_id after some discussion

Add letter attachment table

---

app/notifications/validators.py
requirements.in
requirements.txt
tests/app/notifications/test_validators.py

This pulls in a new `normalised_lines` format for BFPO addresses. We now put the BFPO number on the last line, after the postcode (if present).
This is more in line with the format for BFPO addresses as recommended on GOV.UK, so should be preferrable for our print provider/Royal Mail. It also includes some additional utility methods for extracting BFPO information so that we can provide normalised data to our print provider's API to mark up BFPO addresses.
---
See also https://github.com/alphagov/notifications-utils/pull/1022

Bump utils to 62.0.1

---

app/celery/tasks.py
tests/app/celery/test_ftp_update_tasks.py
tests/app/celery/test_nightly_tasks.py

The DVLA response files in production now include the despatch date but this same change doesn't appear to have been made in preview, so we can't make this field required yet.
Reverts alphagov/notifications-api#3749

Revert "Make despatch date in DVLA response files required"

---

app/__init__.py
app/clients/letter/dvla.py
app/config.py
manifest.yml.j2
requirements_for_test.txt
tests/app/clients/test_dvla.py

The DVLA API we will connect to in prod supports a number of insecure
ciphers. It will take some time for them to retire support due to other
clients requiring them, but we want to make sure we aren't able to
connect with those insecure ciphers.
We will supply our own list of acceptable cipher suites via config.

Restrict DVLA API TLS connections to specific ciphers 

---

app/celery/process_ses_receipts_tasks.py
tests/app/celery/test_ftp_update_tasks.py
tests/app/celery/test_letters_pdf_tasks.py
tests/app/celery/test_process_ses_receipts_tasks.py
tests/app/celery/test_process_sms_client_response_tasks.py
tests/app/celery/test_provider_tasks.py
tests/app/celery/test_research_mode_tasks.py
tests/app/celery/test_scheduled_tasks.py
tests/app/test_cronitor.py

And fix a few more parts of the codebase where we just have broken log statements :sad-tear:

Migrate to using caplog instead of mocking loggers

---

app/__init__.py
app/authentication/auth.py
requirements.in
requirements.txt
tests/app/test_logging_filters.py
tests/conftest.py
tests/routes.py

If we're handling API requests from the admin app, it might be sending us a header that indicates the responsible user ID. Let's inject this into any log messages emitted so that it's easier to trace all of the actions a specific user has taken/is responsible for.

Inject user_id into log messages

---

app/config.py
tests/app/test_config.py

We currently schedule celery beat tasks in Europe/London, which means they are scheduled in GMT/BST as appropriate. This means that the hour/minute set in the crontab is the wall-clock time that they will run in reality. This is nice for us as it's predictable and easy to reason about (we don't need to really consider timezones).
Unfortunately, that means celery-beat needs to consider timezones, and it hates doing that: `https://github.com/celery/celery/issues/6438`. This issue has been open on celery for 2.5 years as of writing, and talks about how the celery-beat scheduler can crap the bed when a timezone change occurs, leading to scheduled tasks being skipped. Restarting the celery beat scheduler once the new time zone happens is a workaround, but we don't have a good way to do that. …

Run celery beat in UTC

---

app/dao/fact_billing_dao.py
tests/app/dao/test_fact_billing_dao.py

Ticket: https://trello.com/c/V6vkvxon/254-review-loading-time-for-organisation-page
This is the first in a series of small, incremental improvements to the org dashboard page. This PR focuses on optimising one of the slower queries. This specific query adds a flat latency to the page regardless of which organisation you're viewing, so for small orgs this query takes up a disproportionate amount of the page load. Optimising this query will provide a significant relative increase in page loading for smaller orgs.
**Note**: query plans/timings are from our semi-representative large staging DB
<details><summary>Baseline - SQL</summary>
```sql
SELECT organisation.name               AS organisation_name,
organisation.id                 AS organisation_id,
services.name                   AS …
```

Optimise one of the org dashboard queries

---

app/celery/provider_tasks.py
app/clients/letter/dvla.py
tests/app/celery/test_provider_tasks.py

We were getting the recipient address from the `to` field of the notification if the letter was precompiled, and the personalisation if it wasn't. This was because one-off letters only stored the first line of the address in the `to` field - all other types had the full address in that field.
We've now made a change to store the whole address in the `to` field for one-off letters (https://github.com/alphagov/notifications-admin/pull/4655). This means that we don't need to check how the letter was created in order to see where the address is stored - it will always be in the `to` field.

Only look for address in `to` field for letters we send by DVLA api

---

app/constants.py
app/v2/notifications/post_notifications.py
tests/app/v2/notifications/test_post_notifications.py

**NOTE**: to be merged Wednesday 12 April.
We announced email-as-a-password and retention period changes about 6 months ago, giving services plenty of time to adapt to the new features. Now that this time has passed, we want to update these features to enable email-as-a-password by default and set the default retention period to 26 weeks.

Update document-download security defaults

---

app/dao/annual_billing_dao.py
tests/app/dao/test_annual_billing_dao.py

Adds allowances for FY 2023 so that the service usage page starts to work again. We need to revamp this and move these defined allowances to the DB before next April.

HOTFIX: Add allowances for FY 2023.

---

app/celery/letters_pdf_tasks.py
app/config.py
tests/app/celery/test_letters_pdf_tasks.py

Before the timezone change - and us switching celery-beat onto UTC rather than Europe/London - we were always collating letters at 17:50 local time.
Since changing to BST this has now been happening at 18:50 BST (17:50 UTC). We'd like to make this so that we always send the data over at 17:50 in local time again.
In order to make this happen, we will schedule the task to run twice in UTC in celery-beat. One of these runs will equate to 17:50 GMT and the other to 17:50 BST. The task itself then needs to only process during the correct window and abort if it's processing early or late.
**Note**: need to think about how to update cronitor to track this

Schedule letter collation twice a day; run once

---

app/celery/reporting_tasks.py
app/commands.py
app/config.py
app/dao/fact_billing_dao.py
tests/app/celery/test_reporting_tasks.py

Schedule a new task that updates `ft_billing` with the latest data for today every hour.
Includes a cronitor to make sure this is running hourly.
Ticket: https://trello.com/c/V6vkvxon/254-review-loading-time-for-organisation-page

Hourly ft_billing updates

---

Makefile

This can be useful if jumping between branches with different migrations and the test DBs are on a different migration than the code you've currently got checked out.
```
sam:~/work/gds/notifications-api [SW-make-reset-test-dbs]$ make drop-test-dbs
Dropping test DBs.
NOTICE:  database "test_notification_api_gw0" does not exist, skipping
NOTICE:  database "test_notification_api_gw1" does not exist, skipping
NOTICE:  database "test_notification_api_gw2" does not exist, skipping
NOTICE:  database "test_notification_api_gw3" does not exist, skipping
NOTICE:  database "test_notification_api_gw4" does not exist, skipping
NOTICE:  database "test_notification_api_gw5" does not exist, skipping
NOTICE:  database "test_notification_api_gw6" does not exist, skipping
NOTICE:  database …
```

Add a command to drop all test DBs

---

app/celery/letters_pdf_tasks.py
app/config.py
tests/app/celery/test_letters_pdf_tasks.py

Splits our the `collate_letter_pdfs_to_be_sent` task into two tasks:
1) check_time_to_collate_letters
2) collate_letter_pdfs_to_be_sent
The first is scheduled by celery-beat to execute at 16:50 and 17:50 UTC.
It determines whether the local time is 17:50 and, if so, triggers the
actual collation task.

Split out letter scheduling and collation

---

app/constants.py
app/dao/organisation_permissions_dao.py
app/models.py
app/organisation/organisation_schema.py
app/organisation/rest.py
migrations/.current-alembic-head
migrations/versions/0408_perm_ask_to_join_service.py
tests/app/organisation/test_rest.py

This creates a new table with rows with
- organisation_permmission: A type that represents each permission
- enabled: Whether this organisation permission is enabled or not, I think this might be useful if the default behaviour might change. So even though it might default to off, it might be nice to make it explicitly off
- organisation_id: the organisation this permission applies to
- created_at, updated_at: standard timestamps

Add table for organisation permissions

---

requirements.in
requirements.txt

* Injects the celery task ID into logging output if no requestId is present.
* Add odd/even class to letter pages
Results in log lines such as:
```
{'application': 'delivery',
'levelname': 'INFO',
'lineno': 37,
'logType': 'application',
'message': 'Celery task '
'create-nightly-notification-status-for-service-and-day (queue: '
'reporting-tasks) took 0.0248',
'name': 'delivery',
'pathname': '/Users/sam/work/gds/notifications-api/venv/lib/python3.9/site-packages/notifications_utils/celery.py',
'requestId': '3618a109-5525-430c-a232-10302a679eaa',
'service_id': 'no-service-id',
'time': '2023-04-26T11:40:12',
'user_id': None}
```

Bump utils to 62.2.1

---

app/billing/rest.py
app/commands.py
app/constants.py
app/dao/annual_billing_dao.py
app/dao/organisation_dao.py
app/dao/services_dao.py
app/models.py
app/organisation/organisation_schema.py
app/organisation/rest.py
migrations/.current-alembic-head
migrations/versions/0409_annual_allowance.py
migrations/versions/0410_drop_unused_allowance.py
tests/app/billing/test_rest.py
tests/app/dao/test_annual_billing_dao.py
tests/conftest.py

This moves us from having default annual allowances for free text messages hard-coded to stored in the DB, which more closely follows what we do for text message rates.
Best to go commit-by-commit for this as there's some refactoring in the midst as well.
We also update the function to carry forward 0 allowances. This was previously handled by a special admin command, but it feels like this makes more sense to be default behaviour otherwise we still have to run that command ASAP at the start of each year to make sure zero allowances are carried forward.
---
Ticket: https://trello.com/c/jn2oqao9/335-move-the-default-annual-billing-allowances-from-code-to-the-db-similar-to-billing-rates

Add default annual allowances table

---

app/performance.py
manifest.yml.j2
requirements.in
requirements.txt

Re-configure Sentry to interpret our full suite of env vars and send additional data in non-prod envs to aid in debugging.

Re-configure Sentry

---

.gitignore

If you turn off debug mode locally (eg in order to check JSON-formatted logs), a log file called `application.log.json` will be created. Let's ignore it.

Ignore log file

---

app/celery/reporting_tasks.py
app/constants.py
app/dao/fact_billing_dao.py
app/organisation/rest.py
app/utils.py
tests/app/dao/test_fact_billing_dao.py
tests/app/organisation/test_rest.py

To merge after https://github.com/alphagov/notifications-api/pull/3772
Admin PR: https://github.com/alphagov/notifications-admin/pull/4685
---
Remove the on-demand calculations of ft_billing when the API endpoint is
hit, as this can be a set of heavy queries causing slow page loads. We
now have an hourly celery task that calculates this information for the
current day, so we can use the cached information instead.
To indicate when the data was last updated, we'll return the timestamp
for when the cache was last updated.

Stop on-demand calculation of ft_billing data

---

app/performance.py

We're not seeing the same unusual memory issues we were with Sentry previously (when we had profiling/performance tracing in place), so we are safe to enable it on all instances.

Enable sentry errors on all prod instances

---

tests/app/dao/test_services_dao.py
tests/app/performance_dashboard/test_rest.py

We want to upgrade the database to Postgres 15, but there were a couple of tests that were failing with the new version. These were not failing for any substantial reason, so we can just update the code tests to be compatible with both versions.

Make tests compatible with both Postgres 11 and 15

---

app/celery/research_mode_tasks.py
app/clients/document_download.py
app/v2/notifications/post_notifications.py
scripts/run_locally_with_docker.sh
tests/app/clients/test_document_download.py
tests/app/v2/notifications/test_post_notifications.py

When the apps are deployed on ECS we want to use internal hostnames when talking to other apps where possible, so have split out the environment variables in preparation for this https://github.com/alphagov/notifications-api/pull/3793
This PR changes the code to use the internal hostname where possible when calling itself or document-download-api. When deployed on PaaS both values will be the same, but when deployed on ECS the external and internal hostnames will be different.

Use both internal and external URLs for api and document-download-api

---

app/letter_attachment/rest.py
app/letter_attachment/schema.py
tests/app/letter_attachment/test_rest.py

This endpoint is the one called when removing an attachment from a
template.
As there are multiple versions of the template, which might be reverted
to, the attachment is kept. So this archive endpoint just does a soft
delete.
It does this by removing it from template and updating the
archived_at and archived_by_id in the letter-attachment
db row.

Adding archive endpoint for letter-attachment

---

app/celery/scheduled_tasks.py
app/commands.py
app/config.py
app/dao/annual_billing_dao.py
tests/app/celery/test_scheduled_tasks.py
tests/app/test_commands.py

At the start of each financial year, let's automatically populate AnnualBilling for all services that exist.
This will ensure that the org usage dashboard immediately reflects free allowances for all of its services.
Newly-created services get an AnnualBilling entry added upon creation.
Creds PR: https://github.com/alphagov/notifications-credentials/pull/338

Populate AnnualBilling automatically each year

---

app/models.py
migrations/.current-alembic-head
migrations/versions/0411_contact_list_idx.py

We do a lot of lookups on this field and having an index makes sense. This missing index has eventually caused a (poorly optimised) endpoint (get_contact_list) to start timing out for some users with a lot of contact lists.

Add index to jobs.contact_list_id field

---

app/broadcast_message/utils.py
app/celery/nightly_tasks.py
app/celery/scheduled_tasks.py
requirements.in
requirements.txt
tests/app/celery/test_nightly_tasks.py
tests/app/celery/test_scheduled_tasks.py

* Remove the `technical_ticket` parameter from NotifySupportTicket; replace with an optional `notify_ticket_type` that takes a NotifyTicketType enum value. If provided, this will maintain the existing behaviour where tickets are tagged as technical/non-technical on creation. If omitted, then tickets will have no ticket type, which may help us have a clearer process around triaging tickets.
* Add `class="page--first"` and `class="page--last"` to the first and last pages (respectively) of letters rendered with `LetterImageTemplate`
* Change `logger.exception` to `logger.warning` for log formatting error.
* Adds support for Chinese character sets in letters ***
Complete changes: https://github.com/alphagov/notifications-utils/compare/62.3.1...63.0.0

Bump utils to 63.0.0

---

app/performance.py

Send the current git commit as a release version to sentry when initialised, which will let us track when errors are introduced and mark errors resolved as of a specific commit/release.

Tag releases for Sentry

---

app/celery/tasks.py
app/dao/notifications_dao.py
app/models.py
migrations/.current-alembic-head
migrations/versions/0412_letter_despatch.py
tests/app/celery/test_ftp_update_tasks.py

Adds a new table `NotificationLetterDespatch` that records when we receive confirmation that a letter has been despatched. In the future we will use this to issue billing reports to our print provider.
There are a few refactors in here so best to go commit-by-commit.
There is one WIP/fixme/todo comment that I'm open for thoughts on but also may leave to address separately. For now the implementation is technically fine but if we can tighten up the FK safely then that's also great.

Record letter despatch dates

---

app/performance.py

This app can be deployed in a number of different configurations, eg the API itself or one of the celery workers.
Let's add a tag that will make it more apparent which configuration the error has been raised from.

Add app name tag for Sentry

---

app/dao/notifications_dao.py
tests/app/dao/notification_dao/test_notification_dao_delete_notifications.py

And add a test to validate this works correctly.
In staging the `notifications_history` table may have columns in a different order because of how we migrate+anonymise the table from production. Our nightly process that moves notifications from the live table to the history table still expects those columns to be in the same order; this patch explicitly lists the columns to insert into

Explicitly list columns for notification migration

---

app/__init__.py

when the db goes down (for example during maintenance hours), the connection being checked in (ie: closed) might not have all the variables that we use to measure connection count, duration etc. make sure we don't log another exception in this case (we'll already get an OperationalError from the db connection being closed itself)

handle KeyError 'checkout_at' in db telemetry

---

app/celery/reporting_tasks.py
app/celery/tasks.py
app/dao/fact_billing_dao.py
app/models.py
app/platform_stats/rest.py
migrations/.current-alembic-head
migrations/versions/0413_ft_billing_letter_despatch.py
tests/app/celery/test_ftp_update_tasks.py
tests/app/celery/test_reporting_tasks.py
tests/app/dao/test_fact_billing_dao.py
tests/app/platform_stats/test_rest.py

Add a fact table for billing letters based on despatch date, which we started recording in https://github.com/alphagov/notifications-api/pull/3807. This will run as part of the nightly billing job in a separate celery task.
We then expose the new billing facts on an admin endpoint so that platform admins can download the report via the admin interface (https://github.com/alphagov/notifications-admin/pull/4734).

Letter despatch billing facts

---

requirements.in
requirements.txt

Bump utils so that the API can properly send emails with subheadings.
<details><summary>Utils changelog entries</summary>
<p>
* Allow subheadings via markdown for emails using `##`.
* Only log a warning and no longer raise an error if creating a Zendesk ticket fails because the user is suspended.
* `LetterImageTemplate.page_count` is now a property which can be overriden by subclasses
* New attributes and properties on `BaseLetterTemplate` (and its subclasses):
- `max_page_count`
- `max_sheet_count`
- `too_many_pages` (requires subclasses to implement `page_count`)
* argument `image_url` to `LetterImageTemplate` is now optional unless calling `str(LetterImageTemplate(…))`
</p>
</details>

Bump utils to 63.4.0

---

app/schemas.py
tests/app/template/test_rest.py

previously this was only returned for the nested template object within the GET /notification endpoints - however, we also want it in other places, including notibly `/template/precompiled` that returns a service's magic precompiled template. This fixes a bug where we used the wrong type of utils LetterTemplate class, and only showed the first page of precompiled letters when previewing them

always return is_precompiled_letter

---

requirements.in
requirements.txt
tests/app/v2/notifications/test_post_notifications.py

64.1.0
---
* `RequestCache` now stores items in Redis for 28 days by default (2419200 seconds instead of 7 days or 604800 seconds)
64.0.0
---
_These changes don’t affect the API application._
* Remove the `postage` argument from `LetterImageTemplate` in favour of getting `postage` from the `template` `dict` (can still be overridden by setting `template_instance.postage`)
* The `page_count` argument of `LetterImageTemplate` is now optional until the template is rendered (calling `str(template)`)
***
Complete changes: https://github.com/alphagov/notifications-utils/compare/63.4.0...64.1.0

Bump utils to 64.1.0

---

app/constants.py
app/dao/organisation_dao.py
app/dao/organisation_user_permissions_dao.py
app/models.py
app/organisation/invite_rest.py
app/organisation/organisation_schema.py
app/user/rest.py
app/user/users_schema.py
migrations/.current-alembic-head
migrations/versions/0414_org_user_permissions.py
migrations/versions/0415_org_invite_perms.py
migrations/versions/0416_add_org_user_perms.py
tests/app/dao/test_organisation_user_permissions_dao.py
tests/app/organisation/test_invite_rest.py
tests/app/user/test_rest.py

API PR 1 of 2 (maybe 3)
Adds the table which stores the actions a user can take for a given organisation. Right now we're only adding one permission (the ability to make services live) and everything else is just implicit if you're a member of the org.
So that the new permission is automatically set for new org members.
To prepare for the admin pages that will allow adding/removing permissions.
When inviting a user to an org, in the same way that we do with invited service users, store their eventual permissions on the invited user model.
---
To do in the future (after initial admin release):
- read permissions when adding user to the org (admin sends permissions across from the invite ... for some reason - being consistent with how service user invites work here).
- remove default for …

Org user permissions

---

app/models.py
migrations/.current-alembic-head
migrations/versions/0417_remove_null_constraint.py

I had previously accepted that we wouldn't be able to invite users during the app rollout, but forgot we have a functional test step between migrations and app code deployment that would fail.
So we can't immediately enforce a not-null constraint and will need two separate deployments.

Remove null constraint

---

app/models.py

Until we re-apply the null constraint on permissions they can be null temporarily. Coalesce that to a blank string (the intended target)

Resolve null permissions

---

app/models.py
app/organisation/rest.py
app/organisation/sender.py
tests/app/organisation/test_rest.py

We are rolling out an org-user level permission to say who can make services live. Given this, we should only send emails about services requesting to go live to users with the relevant permission.

Restrict org users that get 'go live' emails

---

entrypoint.sh

The ecs services have had thier names changed.
The workers have "api-" appended to them.
This PR does the same for the commands.

Renamed commands in entrypoint.sh

---

Makefile

Let's use the built droplet when running db migrations, rather than making a new one from scratch (which involves pulling+installing dependencies etc). Should make deploys faster when we have migrations to run.

Use droplet for db-migration paas app

---

manifest-droplet.yml
scripts/create-droplet.sh

Makes the package and droplet retrieval steps more reliably fetch the latest package/droplet.
Provides a manifest-droplet.yml file so that we can specify the buildpack we want to use. This is somewhat redundant for the API because CloudFoundry already detects python correctly, so only adding for consistency.

Update create-droplet script

---

app/v2/notifications/post_notifications.py
tests/app/v2/notifications/test_post_notifications.py

In some cases, a client may send `confirm_email_before_download` as `None`. In these cases we should apply a default of `True`, enabling email confirmation.
We were only enabling this as a default if the `confirm_email_before_download` wasn't present at all.

Fix default confirmation for doc download

---

manifest.yml.j2

We want 0 in preview because we are now running 1 instance in preview ECS and we only want 1 instance in total.
For staging and production, they stay on their default behaviour which is 1 instance per environment (this isn't defined in code but I checked how many we run in staging and prod and it is currently 1). We only want 1 instance so we don't have multiple of the same tasks being created at the same time.
For context, see
https://github.com/alphagov/notifications-aws/pull/1579

Run 0 instances of celery beat in preview and run 1 in other envs

---

scripts/deploy.sh

https://github.com/alphagov/notifications-api/pull/3837 In this PR we previously found out that `cf restart` will scale up to 1 instance the notify-api-db-migration app when we don't want that to happen (it should run 0 instances). The solution was to add the if statement based on the app name.
In https://github.com/alphagov/notifications-api/pull/3844 we now desire 0 instances of celery beat for preview and 1 instance for staging and production. When we deploy the API using this script, it will scale preview up to 1 instance when it runs the `cf restart` command.
We put in place a flexible solution that checks how many instances are desired (set in the apply-manifest step above) and decides not to restart if the desired number of instances is 0. This should nicely handle both the case …

Don't restart the app if 0 instances are required

---

requirements.in
requirements.txt

* Require phonenumbers >= 8.3.18 (changes how some numbers are formatted.
* Render placeholder `((` and `))` as HTML-encoded characters in templates, fixing some display issues for links including placeholders and static text.

 Bump utils to 66.0.1

---

requirements.in
requirements.txt

Shouldn’t mean any functional changes for this repo, but just so some else doesn’t have to do it…
66.1.0
---
* Add a simpler syntax for QR codes in letters (QR: http://example.com)
66.0.2
---
* Style the QR code placeholder so it looks better when the placeholder text is long
***
Complete changes: https://github.com/alphagov/notifications-utils/compare/66.0.1...66.1.0

Bump utils to 66.1.0

---

app/constants.py
app/notifications/process_notifications.py
app/template/rest.py
app/v2/errors.py
requirements.in
requirements.txt
tests/app/notifications/test_process_notification.py
tests/app/template/test_rest.py
tests/app/v2/notifications/test_post_notifications.py

Validate QR code length when:
* creating/updating a template
* sending a notification via the API
Importantly, this validation happens up front. If a notification with a
QR code that is 'too long' did manage to get accepted by the API,
template-preview *would* render a QR code for it and the letter would be
sent. This is so that we don't have to handle moving letters with QR
codes into `permanent-failure` and then explain why that has happened.
We may revisit this in the future, but for now we are preferring to stop
'bad QR codes' getting into the system at all, rather than handling
errors further downstream and having to bubble them back up.

QR code validation

---

app/constants.py
app/notifications/validators.py
app/schema_validation/__init__.py
app/schemas.py
app/v2/errors.py
requirements.in
requirements.txt
tests/app/v2/test_errors.py

70.0.0: updates validation messages for invalid phone numbers; we override these to retain API backwards compatibility
70.0.1: fixes `<strong>` tagging around QR codes during validation
---
We override the updated content for invalid phone errors so as to keep our API interface the same. We may unroll this in the future.

Bump utils to 70.0.1

---

app/celery/scheduled_tasks.py
tests/app/celery/test_scheduled_tasks.py

they're now specifically lowercase so the old links didn't work

make anchors in team wiki links lowercase

---

Makefile
app/config.py

When running Celery beat on ECS we've noticed the `backend_cleanup` task
running at 0400 each morning and being put on the default queue. This
task is a built in Celery task that cleans up expired results ("task
tombstones") from the results backend database. We don't have a results
backend, so don't need the task to run - there's nothing for it to clean up.
We can disable it by setting the value of `results_expires` to 0 to
show that task results never expire and so don't need cleaning.
https://docs.celeryq.dev/en/stable/userguide/configuration.html#result-expires
It's not clear why this task is running on ECS but wasn't running on the PaaS
since we've not changed any settings when migrating.

Set `result_expires` to 0 in Celery config

---

requirements.in
requirements.txt

70.0.2
---
- Update sanitising of SMS content to include more obscure whitespace
***
Complete changes: https://github.com/alphagov/notifications-utils/compare/70.0.1...70.0.2

Bump utils to 70.0.2

---

docker/Dockerfile

This is the build stage that we use for local development, so having access to root privileges will be useful - eg to install extra dependencies or edit OS files.

Allow passwordless sudo in test image

---

docker/Dockerfile

Copying the directory via a Dockerfile command is faster than running a command inside the build container to update ownership
```
=> [notify-api test 3/6] COPY --from=python_build --chown=notify:notify /opt/venv /opt/venv        2.8s
```
vs
```
=> [notify-api test 1/6] RUN chown -R notify:notify /opt/venv                                      9.2s
```

Chown /opt/venv faster

---

app/config.py
app/delivery/send_to_providers.py
tests/app/celery/test_scheduled_tasks.py
tests/app/delivery/test_send_to_providers.py
tests/app/notifications/test_validators.py
tests/app/organisation/test_invite_rest.py
tests/app/organisation/test_rest.py
tests/app/service_invite/test_service_invite_rest.py
tests/app/user/test_rest.py
tests/app/user/test_rest_verify.py
tests/conftest.py

When running inside docker we have different hostnames for our apps, so we can't hardcode them inside tests. We can add a fixture that pulls the hostnames for our apps from environment variables, allowing tests to pass either locally or inside docker.

Allow tests to run in or out of docker

---

app/__init__.py
app/authentication/auth.py
app/config.py
app/functional_tests/__init__.py
app/functional_tests/testing_schemas.py
tests/__init__.py
tests/app/conftest.py
tests/app/functional_tests/test_functional.py
tests/app/test_app.py

Adds an endpoint to the API, only available in development and preview
environments, which can create users for the functional tests.
These users are created against a pre-seeded organisation/service, so
that is expected to exist in the DB already. But creating users on
demand allows us to run tests interacting with that org/service in
parallel, which should lead to much faster run times for our common
journeys

Create functional test seeded users endpoint

---

requirements.in
requirements.txt

* Remove empty table cell from 'branding only' branding HTML to fix bug with JAWS screen reader
***
Complete changes: https://github.com/alphagov/notifications-utils/compare/70.0.2...70.0.3

Bump utils to 70.0.3

---

app/notifications/receive_notifications.py
tests/app/notifications/test_receive_notification.py

We recently encountered the case where a service set up inbound sms and then turned off permission to send sms. This means it has the `inbound-sms` permission but not the `sms` permission.
When you turn off SMS in the admin app for your service, it hides all the SMS related settings, including inbound sms. This is probably not ideal. We should consider changing this in the future so that the admin interface allows you to configure inbound and outbound sms separately.
We also had some discussion about whether turning off outbound sms should also turn off inbound sms but decided this was not the best for the users and we should allow them the flexibility.
Given that we want services to still be able to receive inbound sms, even if they have outbound sms turned off, it requires this change …

Allow inbound sms if sending sms permission is off

---

requirements.in
requirements.txt

See also:
* https://github.com/alphagov/notifications-admin/pull/4822
* https://github.com/alphagov/notifications-utils/pull/1064
v70.0.5 of utils ensures that we always get/set redis cache data using lowercase UUIDs. We store template data in redis to reduce DB load. Previously, when sending notifications, the `template_id` in the JSON paylod would be used as-is to check redis for a cached version of the template. This means that posting with a lowercase template UUID might be in the cache, but an uppercase template UUID might not be present and end up hitting the DB. This could cause older versions of the template to be used to send messages if:
1) A notification is sent via the API using an uppercase UUID, caching v1 in redis with the uppercase ID.
2) The template is updated via admin …

Bump utils to 70.0.5

---

app/models.py
app/schemas.py
app/service/rest.py
migrations/.current-alembic-head
migrations/versions/0420_unique_service_name_1.py
tests/app/service/test_rest.py

this is the first in a process to rename `email_from` to
`normalised_service_name`.
1. **add new column as nullable**
4. **write new values to both new and old column**
6. migrate old data. add unique and not null constraints.
7. delete references to old column in code
8. drop old column

Rename email_from to normalised_service_name

---

app/dao/organisation_dao.py

We have a flaky test due to not ordering organisations consistently in our response. It's nice to do this, so let's, even though we could just fix the test to not expect order.

Order organisations consistently

---

requirements.in
requirements.txt

This reverts the changes introduced by commit
6d80b03c577bb47cd09ac3e49a4b30284179832b.
In a recent load test we identified a huge drop-off in performance that has been traced back to this dependency bump. Until we can investigate further and work out exactly why - and potentially get it fixed up stream - we will go back to our previously-pinned version.

Revert "Bump gunicorn to 21.2.0"

---

entrypoint.sh
scripts/paas_app_wrapper.sh

when sending 100k letters with 2 instances of 4 concurrency, we saw 177k requests (77k requests hit the rate limit).
reducing the number of processes from 8 to 6 should help manage this.
if we continue having issues we may want to look at a more sophisticated way of throttling

reduce concurrency of dvla api worker

---

requirements.in
requirements.txt

* Fix QR code rendering for old-style syntax `[QR]()`
***
Complete changes: https://github.com/alphagov/notifications-utils/compare/70.0.5...70.0.6

Bump utils to 70.0.6

---

migrations/.current-alembic-head
migrations/versions/0423_notify_user_name.py

So that if any actions are ever attributed to this user it’s clearer that they are being done by the platform itself, not some kind of generic/anonymous user.

Rename ‘Notify service user’ to ‘GOV.UK Notify’

---

app/service/rest.py
tests/app/service/test_rest.py

This PR is for [this](https://trello.com/c/3JRlqM43/496-update-reply-to-email-address-already-in-use-validation-error-message) ticket.
It updates the InvalidRequest error message for reply-to email address validation.

update InvalidRequest error message for reply-to email address

---

app/models.py
migrations/.current-alembic-head
migrations/versions/0424_n_history_created_at.py

We want to add this index because at the moment it the table is too big to query based on created_at (we do have some indexes on this table already but those are multi column indexes so are not often able to be used when querying just on created_at).
We choose to create our index concurrently. This is backed by https://medium.com/paypal-tech/postgresql-at-scale-database-schema-changes-without-downtime-20d3749ed680#04b4.
Importantly it says:
This lower lock level allows reads and writes to continue against the table while the index is built.
You can also read the postgres documentation on it at: https://www.postgresql.org/docs/current/sql-createindex.html#SQL-CREATEINDEX-CONCURRENTLY
Creating an index concurrently needs to be done outside of a transaction. We can use an alembic feature to …

Add index concurrently on created_at to notification_history table

---

manifest.yml.j2

What
----
Switch the db migration task to use cflinuxfs4
Why
----
cflinuxfs3 is currently the default on the PaaS. This is based off ubuntu 18.04. This stopped receiving updates after Apr 2023.
cflinuxfs4 will become the default on the PaaS after 27 Nov 2023.
The intention is to migrate all applications to cflinuxfs4. This change is the start of that process, where the db migration app is our canary.

Switch the db migration task to use cflinuxfs4

---

app/models.py
tests/app/organisation/test_rest.py
tests/app/template_folder/test_template_folder_rest.py

This relationship was set up to perform a SQL query for every template folder individually. By setting the relationship to load via a join we can instead emit a single SQL statement.
https://govuk-notify-gds.sentry.io/issues/4474807382/?project=4504949325824000

Resolve an n+1 queries on endpoint

---

app/models.py
app/serialised_models.py
app/service/rest.py
migrations/.current-alembic-head
migrations/versions/0425_unique_service_name_2.py
tests/app/conftest.py
tests/app/dao/test_services_dao.py
tests/app/db.py
tests/app/organisation/test_rest.py
tests/app/service/test_rest.py

Finally getting back at this!
Migrate the old email_from to new normalised_service_name column. 
1. ~~add new column as nullable~~ (https://github.com/alphagov/notifications-api/pull/3865)
2. ~~write new values to both new and old column~~ (https://github.com/alphagov/notifications-admin/pull/4824)
3. **migrate old data. add unique and not null constraints.**
4. delete references to old column in code
5. drop old column

normalised_service_name migration

---

migrations/alembic.ini
migrations/versions/0425_unique_service_name_2.py

we ran into deadlocks when running this script on production. adding a constraint acquires an access-exclusive lock. This is fine on its own, to add a not-null constraint is a relatively quick operation for a table of this size (27k services, 100k services_history). however, because the query was trying to acquire locks to both services and services_history, it ran in to a deadlock with another process where that process was also trying to acquire locks on both tables - each process acquired one of the locks, and was stuck waiting for the other to be released, so a deadlock was identified and the migration failed.
even if the other process wasn't doing anything big and dramatic, nothing can acquire a lock alongside an access-exclusive lock.
normally alembic wraps the entire upgrade script …

run upgrades in separate transactions to remove deadlock

---

manifest-droplet.yml
manifest.yml.j2
paas-failwhale/manifest.yml

What
----
Switch to use the PaaS cflinuxfs4 stack.
Why
----
cflinuxfs3 is currently the default on the PaaS. This is based off ubuntu 18.04. This stopped receiving updates after Apr 2023.
cflinuxfs4 will become the default on the PaaS after 27 Nov 2023.
The intention is to migrate all applications to cflinuxfs4 eventually.

Switch to using cflinuxfs4

---

migrations/alembic.ini

This logs all of the actual SQL that runs on the DB and is useful to see. It can get a bit noisy, but since it's only during migrations that's fine - and probably more useful than not.

Enable the SQLAlchemy logger during migrations

---

app/celery/provider_tasks.py
app/clients/letter/dvla.py
tests/app/celery/test_provider_tasks.py
tests/app/clients/test_dvla.py

Couple of things that became apparent from load test:
* we don't catch connection errors or timeouts currently, they just sent a letter into temp failure
* we didn't have any code blocks for sending a letter that isn't created, or isn't a normal type. technically the collate task won't gather them, but thought it wise to put some extra checks in the deliver_letter task

Dvla error handling

---

app/config.py

THIS PR IS PART OF STEP 2
This PR is part of a set of PRs to be merged during the proposed migration of PaaS apps to start using redis from notify-staging
The steps agreed on the document are:
1. **Change Credentials REPO** - This PR adds the redis_url to the credentials repo
2. **Disable redis** (by setting REDIS_ENABLED to false on API, ADMIN and DOCUMENT_DOWNLOAD_API)
3. **Enable redis** (by removing REDIS_ENABLED line on staging class on API, ADMIN and DOCUMENT_DOWNLOAD_API

disable redis for staging

---

app/template_folder/rest.py
tests/app/organisation/test_rest.py
tests/app/template_folder/test_template_folder_rest.py

I tried to fix an n+1 queries on the `get_template_folders_for_service` endpoint with a generalised change to how the relationship on `TemplateFolder` joins to `User` (in https://github.com/alphagov/notifications-api/pull/3885), but this cascaded to cause massive queries on other endpoints when services have thousands of templates/users.
Let's fix this endpoint more specifically by loading the relationships we know we are going to use, in advance.

Apply localised fix for n+1 queries

---

manifest-droplet.yml
manifest.yml.j2
paas-failwhale/manifest.yml

What
----
Rollback to cflinuxfs3
Why
----
Unfortunately we are seeing significant performance issues with cflinuxfs4 in production.

Rollback to cflinuxfs3 due to performance issues

---

app/template/template_schemas.py
tests/app/template/test_rest.py

When a user changes a template from welsh then english back to just english, we should be able to clear the welsh letter data entirely by setting it to null. This updates the schema to allow that.

Allow clearing welsh letter subject and content

---

manifest.yml.j2

we now have redis_enabled set in the credentials file. We need to add an IF statement to the manifest for the value to be picked up by the container

set redis_enabled IF to set the env

---

app/celery/nightly_tasks.py
app/config.py
app/dao/notification_history_dao.py
tests/app/celery/test_nightly_tasks.py
tests/app/dao/test_notification_history_dao.py

https://trello.com/c/8qFHZC6a/353-delete-data-from-notificationhistory-older-than-april-2023
Please pay particular attention to:
- have I got the correct retention limit that matches what is expected in our decision record? If we get this wrong, we could delete a big bunch of data we actually want
- is the logic for knowing when not to delete records correct? If we get this wrong, we could delete a big bunch of data we actually want
- are you happy with the log statements? Will they make these easy to debug if we need to?
This will run at 9pm (a quietish time but hopefully not going to conflict with the other nightly tasks that start around midnight, although if it does conflict it should still be OK).
This will start at 9pm on the day of merging and then should run for 14 days, each time …

Add celery task to delete one quarter of old notification history

---

app/celery/nightly_tasks.py
app/config.py

We had lots of email alerts over the weekend. This was because the delete_oldest_quarter_of_unneeded_notification_history task was accidentally being run every minute from 21:00 to 21:59. This was causing a variety of knock on effects as the periodic worker was blocked up running these tasks, rather than the other tasks it should be running.
I've also added in some additional logging for better debugging in the future if needed.
Note, this does not solve the problem of the task failing due to sqlalchemy statement timeout errors (queries can only run for up to 20 minutes) which is going to be addressed in a subsequent PR (but I wanted to get this quick fix in which would stop any further production impact tonight first).

Stop task running 60 times per night, rather than once 

---

tests/app/dao/notification_dao/test_notification_dao_delete_notifications.py

This also adds the `notify_db_session` fixture to fix an error when the test is run as a single test.

Fix typo in test assertion

---

app/dao/notification_history_dao.py
tests/app/dao/test_notification_history_dao.py

This is because the query is currently taking over 20 minutes which is longer than our statement timeout limit and so is being cancelled.
We split it into smaller chunks so that we don't run into this problem. 50,000 has been chosen fairly arbirtrarily and is used as a query_limit elsewhere in our codebase.
We commit after each one so we commit progress regularly rather than just at the end.
We choose synchronize_session False as we do not need to access those notifications again that have been deleted.
https://docs.sqlalchemy.org/en/14/orm/session_basics.html#selecting-a-synchronization-strategy

Delete rows from notification_history in 50,000 chunks

---

app/celery/nightly_tasks.py

This will enable us to retain about 1 billion notifications in our staging notification_history table, which is roughly the same number that will be in production after this task has run against prod. This is important for our testing this week of migrating Postgres which will benefit from having staging look similar to production in size.
We did also consider taking a fresh copy of production, redacting the personal data and attaching it to the staging apps, but decided that was too much work and this is a quicker fix.

Don't run notification_history purge task in staging

---

app/performance.py

We've bumped the memory on API instances. We previously tried to run sentry profiling on API in production and it spiked memory use. Now that we have more memory available, let's see if we can enable profiling on the API again.

Test sentry profiling on API in production

---

app/dao/notification_history_dao.py

Getting some mixed results still in our logs where this isn't super speedy and sometimes doesn't appear to finish.
These two small changes may help us.
Best reviewed commit by commit

Try to debug and speed up delete_notification_history_older_than_datetime

---

app/schemas.py
tests/app/job/test_rest.py

4 days is sometimes not enough if there is a weekend with a bank holiday before and after it.
7 days is a sensible new limit because it:
- accounts for these longer weekends or holiday periods like Christmas
- without introducing any ambiguity about which ‘Thursday’ is meant (because only one of each weekday will ever be shown at once)

Let jobs be scheduled up to 7 days in the future 

---

app/config.py
app/dao/notification_history_dao.py

The task is currently going fairly slowly, deleting about 6 million rows per hour. It is also at risk of getting disrupted by a deploy which will stop it until it is kicked off again this evening.
At this pace, it will take about 83 nights to delete all the needed notifications (we need it to be done in about 10 days time).
Firstly, I've changed the task to start at 7pm. This will give us an extra 2 hours for it to run overnight before someone comes in the next day and potentially deploys the API.
Secondly, I've got it kicking off the task 4 times per evening. This will mean we get roughly 4 times the deletion which will be quicker. To support this, I've removed the requirement that it deletes the oldest notifications first and instead picks them as it wants. This should mean that 4 …

Run delete notification history task 4 times per night

---

app/dao/notifications_dao.py
tests/app/dao/notification_dao/test_notification_dao.py

We've seen a lot of timeouts on the NHS service "view notifications" page, when they try to view failed letters.
The pseudo-SQL query for this page is:
select * from notifications where service_id=x, key_type in (a,b), status in (a, b, c), created_at >= date limit x offset y;
We have a composite index on these fields and the query will occasionally make use of this, which is great.
However, sometimes it instead chooses to do a backwards index scan on another index with just (service_id, created_at). The reason it does this is that it seems to think that, when fetching only a few results (ie for low limit values), it should be quick to just go back through that index and find the first few matches. Where there are only very few matches, this ends up not working. For example, NHS sends a …

Promote use of specific notifications index

---

app/celery/nightly_tasks.py
app/dao/notification_history_dao.py
tests/app/celery/test_nightly_tasks.py
tests/app/dao/test_notification_history_dao.py

This changes the approach in
delete_oldest_quarter_of_unneeded_notification_history which was too slow because it couldn't be run in parralell on multiple workers.
Instead, we queue up lots of small tasks that can be run in parraell which will each delete only a single hour of data.
I've tested some of these queries manually on production and for the 4 different 1 hour slots I tried, the queries took less than 10 seconds each.
The plan is to kick this task off once manually by logging into production and creating a task (rather than scheduling a task that we only want to run once which is a bit hard to do with cron).
If people are happy with this pull request, I'll merge it, run it and then come back to delete all the code for the old way of doing things.

Delete notification_history in hour chunks

---

migrations/env.py

Postgres has a variety of lock levels that different commands acquire. Per row or per table. Generally they're in a relatively linear hierarchy (where ACCESS SHARE is the most permissive, up to ACCESS EXCLUSIVE being the most restrictive). You can read more about the specifics and when they're used at the postgres docs [^1].
Many commands have ways to not acquire wide-reaching locks. You should always seek to avoid ACCESS EXCLUSIVE where possible, and where not possible, to minimise time spent with such a lock acquired. For example, using `ADD CONSTRAINT NOT VALID` will skip validating a constraint on existing rows - you can then run `VALIDATE CONSTRAINT <name>` later to validate.
However, ACCESS EXCLUSIVE locks are often hard to avoid altogether.
We've seen cases where:
* long running …

add a lock timeout of one second to migrations

---

app/celery/nightly_tasks.py
app/dao/notification_history_dao.py
tests/app/celery/test_nightly_tasks.py
tests/app/dao/test_notification_history_dao.py

It turns out that when we pass datetimes as args to the next task, celery behind the scenes must be converting them into strings in what appears to be using `isoformat()`.
This makes it explicit that
delete_unneeded_notification_history_for_specific_hour expects and requires strings because this is what it will actually receive from celery.
This updates the tests to correspond as well.

Make conversion from datetimes to strings clearer

---

app/performance.py

Trial using Sentry to automatically monitor our scheduled tasks. At the moment this is _in addition_ to Cronitor, so we can just test whether Sentry meets all of our needs without interrupting our current workflow with Cronitor.
https://govuk-notify-gds.sentry.io/crons/?environment=development&project=4504949325824000&statsPeriod=7d

Use Sentry to monitor celery beat tasks

---

app/__init__.py

Set `application_name` on postgres connections
Setting this attribute may help us narrow down/debug which apps are running
queries that hold locks in contention.
See also:
* https://postgresqlco.nf/doc/en/param/application_name/
* https://wiki.postgresql.org/wiki/Lock_Monitoring

Set `application_name` on pg connections

---

requirements.in
requirements.txt

After upgrading from pg11->pg15 locally, we started to see the following error: `sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) SCRAM authentication requires libpq version 10 or above`.
A suggested fix for this is to upgrade to psycopg2(-binary)==2.9.6, so that's what we do here.
---
If using `notifications-local`, you'll need to do a `make down`, `docker-compose build notify-api`, `make <opts> up` again to make sure your API container(s) get updated.

Bump to psycopg2==2.9.6

---

app/config.py
tests/app/clients/test_cbc_proxy.py
tests/app/organisation/test_rest.py
tests/app/template_folder/test_template_folder_rest.py
tests/utils.py

Disables the CBC test which has code that breaks tracking SQLAlchemy queries during test runs.
Then refactors the query tracking code to expose the actual queries that were executed, as well as limit the queries to only those executed within the context manager.

Enable SQL query tracking under test

---

app/schemas.py
tests/app/template/test_rest_history.py

We now rely on this attribute when rendering letter template history versions.
Fixes: https://govuk-notify-gds.sentry.io/issues/4586197393/?end=2023-10-30T23%3A59%3A59&project=4504949328838656&referrer=issue-stream&start=2023-10-01T00%3A00%3A00&stream_index=0&utc=true
Tested locally and does fix the admin pages.

Add 'is_precompiled_letter' to template history

---

requirements.in
requirements.txt
requirements_for_test.txt

Fixes #3936
***
This causes Werkzeug to be upgraded, fixing a security vulnerability.
The newest version of Werkzeug moves some package names around, which means we also need to upgrade pytest-httpserver to avoid a broken import.

Upgrade Flask to latest version

---

app/config.py
tests/app/test_config.py

In order to run the email-provider-stub locally, the `ses-callbacks` queue needs to be added to the list of queues. The worker watches all queues defined here when running locally.

Add "ses-callbacks" to list of queues

---

requirements.in
requirements.txt

Brings in updates to the email template, moving it to a HTML5 doctype.
More details of the changes in https://github.com/alphagov/notifications-utils/pull/1069.

Bump utils to 72.1.0

---

app/celery/scheduled_tasks.py
tests/app/celery/test_scheduled_tasks.py

After some more discussion, we want to settle on requiring 10 consecutive breaches before triggering an error to reduce potential false positives.

Require 10 consecutive minutes of slow delivery

---

manifest.yml.j2

https://trello.com/c/IXguDClO/467-stop-trying-to-send-logs-from-our-apps-into-splunk
We no longer need to log to splunk.

cf manifest: remove notify-splunk service binding

---

requirements.txt

This should fix an issue with cron monitoring not pulling timezones correctly, leading to inconsistent reporting on our cron jobs.
https://github.com/getsentry/sentry-python/pull/2497

Bump sentry-sdk to 1.35.0

---

migrations/.current-alembic-head
migrations/versions/0431_migrate_email_local_part.py
migrations/versions/0432_s_add_not_null_check.py
migrations/versions/0433_sh_add_not_null_check.py
migrations/versions/0434_validate_not_null_check.py
migrations/versions/0435_s_swap_check_for_not_null.py
migrations/versions/0436_sh_swap_check_for_not_null.py

this is super simple - we already set new values via the sqlalchemy column properties, so all we need to do to bring this column up to date is to migrate old data. I decided to make the services_history column _not null_ and migrate all data over for old columns (so that current code can work with old history columns if that's ever a requirement) even though we didn't always have the concept of a email sender separate to normalised service name
this is a super complex and weird process. I've tried to break it into five (!) separate migrations, partially to keep each migration easy to read and also to keep transactions small and easy to reason about
First, create check constraints that check for not null with the postgresql_not_valid flag[^1]. This creates a check constraint but doesn't …

Make email_sender_local_part not null

---

migrations/.current-alembic-head
migrations/versions/0437_min_numeric_scl_aux_tbls.py

https://trello.com/c/cAARpLJ2/501-fix-numerics-which-were-converted-to-6dp-by-dms
This sets values of the `rate` columns in `letter_rates` and `rates` to their minimum necessary scale following the DMS migration.
Wanting to get this one applied well before doing similar things to the `notifications` and `notifications_history` tables to avoid having to concern myself with race conditions.

migrations: add `0437_min_numeric_scl_aux_tbls`

---

app/functional_tests/__init__.py
tests/app/functional_tests/test_functional.py

For functional test users, whenever we start a test run, reset `email_access_validated_at`. Otherwise, 3 months later, the users will require email validation to login, which breaks our functional tests.

Always reset email_access_validated_at

---

app/delivery/send_to_providers.py
app/models.py
app/schemas.py
app/serialised_models.py
app/v2/notifications/post_notifications.py
tests/app/conftest.py
tests/app/dao/test_services_dao.py
tests/app/service/test_archived_service.py
tests/app/service/test_rest.py
tests/app/v2/notifications/test_post_notifications.py

also clean up todos of removing normalised_service_name - it's no longer in the admin app so is safe to not expect in json

use email_sender_local_part to send messages

---

Makefile
app/celery/letters_pdf_tasks.py
tests/app/celery/test_letters_pdf_tasks.py

When we are generating letters via celery in preparation for printing via DVLA, we need to send across Welsh content (if any is present), so that Welsh pages can be generated.

Send bilingual letter content to template-preview

---

app/config.py

We've had 154 letters in the past 7 days get caught in pending-virus-check and need kicking off again by this job.
I've made it run every day of the week. If a letter gets stuck in pending virus scan on Friday evening, the user doesn't want to wait until Monday morning for it to get rescanned and then sanitised (so they can be told if it passed validation or not).
I've also set it to run every hour. A user doesn't want to upload at 9am and have to wait until 3pm for it to get kick started again. The task looks back at letters 90 minutes or older that are still pending a virus scan and so this should mean no letter waits more than 2.5 hours to get kicked off after being given to us (90 mins to look back plus up to 1 hour based on at what point it was sent).
These are hopefully small …

Run `check-if-letters-still-pending-virus-check` more often.

---

app/schemas.py
tests/app/test_schemas.py

The template serialisation in notification schema didn't have the language related fields in it, so Welsh pages were not rendering on the notification preview page.

Fix preview of letter notification for bilingual letters

---

requirements.txt

In another attempt to fix their cron monitoring. Sentry support has indicated that the fix should be in this release.

Bump sentry-sdk to 1.38.0

---

app/celery/scheduled_tasks.py
app/config.py
app/dao/notifications_dao.py
tests/app/celery/test_scheduled_tasks.py

currently we run every hour, and wait for a letter to be stuck for 90 minutes before we kick it off again.
We don't think this is necessary, and is causing issues where, for example, a letter passed virus scan and was sent to template preview for sanitising at 4:30pm. the template preview task crashed, and we didn't pick up the letter to scan/sanitise it again until 7pm, causing it to miss the cutoff.
it isn't the end of the world if a letter is processed/scanned twice as this should be relatively idempotent, so we can just check every ten minutes if something has been stuck for ten minutes

run the letter still pending virus scan check every ten minutes

---

app/template/template_schemas.py
tests/app/template/test_rest.py

When we added support for bilingual letters, we didn't allow creating them (via the admin API) from scratch. You would need to create a basic letter template, then POST an update with bilingual fields.
In order to allow efficient copying of templates, let's make it possible to create a letter template with bilingual fields in a single request.

Allow creating letters with bilingual fields

---

requirements.in
requirements.txt

Removes Emergency-Alerts-related code
* the `polygons` module has been removed
* `template.BroadcastPreviewTemplate` and `template.BroadcastMessageTemplate` have been removed
* Fix utils packaging to allow access to subpackages again.
* Adds a `include_notify_tag` parameter to `LetterPrintTemplate` so that bilingual letters can disable the NOTIFY tag on the English pages of a letter.
* Add compatibility with Python 3.11 and 3.12
* Change how utils is packaged to exclude tests.
(no info)
***
Complete changes: https://github.com/alphagov/notifications-utils/compare/73.1.0...74.0.0

Bump utils to 74.0.0

---

scripts/check_if_new_migration.py

We prefer to use internal routes where possible, and it makes no difference to use the internal vs external route when checking if migrations should run.

Use internal api route when checking if migrations should run

---

scripts/check_if_new_migration.py

Reverts alphagov/notifications-api#3973
We don't have access to the `API_HOST_NAME_INTERNAL` environment variable because it gets set in the manifest and this script is run before the app is deployed. We'll need to make sure it is available first by adding it to the credentials repo before this change can be made.

Revert "Use internal api route when checking if migrations should run"

---

app/config.py
app/service_invite/rest.py
migrations/.current-alembic-head
migrations/versions/0438_request_invite_templates.py
migrations/versions/0438_request_invite_to_a_service_templates.py
tests/app/conftest.py
tests/app/service_invite/test_service_invite_rest.py

This PR adds the endpoint to support the work being done in this [PR](https://github.com/alphagov/notifications-admin/pull/4912), as described in [this](https://trello.com/c/rYMOdCYZ/578-email-selected-team-members-when-someone-asks-to-join-a-service) card.
An alteration has been made to the expected JSON content, `from_user_ids ` has now been replaced with `service_managers_ids` which is a better description.
Also the new endpoint will only return a status code.
Also for now all request invite emails are being sent to `notify-join-service-request@digital.cabinet-office.gov.uk` as prescribed in the ticket, instead of service managers.

Email selected team members when someone asks to join a service

---

app/service_invite/rest.py
tests/app/service_invite/test_service_invite_rest.py

Allows us to use the content in https://docs.google.com/document/d/1arlgMdIQ0RGwDqL_g9WC6unpUyoTTuNzz_2f3m-6E_Q/edit#heading=h.sjzrkf18frnj
Also fixes a name mixup in the personalisation for the existing request email.
Not adding a migration here because it’s more faff than it’s worth with the template history etc. We can just edit the template in production usng the Notify website instead.

Add more personalisation to join service receipt

---

app/service_invite/rest.py
tests/app/service_invite/test_service_invite_rest.py

This helps differentiate the text we put in the email from the text that the user makes the request has entered.
Looks like this:

Put reason for request to join service in a callout

---

app/dao/notifications_dao.py

This has now been successfully replaced by
https://github.com/alphagov/notifications-api/blob/main/app/celery/scheduled_tasks.py#L211
We are no longer using the old gauge in our dashboards so it can be removed

Remove old statsd gauge for sms slow delivery

---

app/celery/process_sms_client_response_tasks.py
app/delivery/send_to_providers.py

This will allow us to see how many messages are being sent to different countries and their success rates.
We have to record a metric when we send the message and not just rely on `_process_for_status`. This is because some international messages don't get delivery receipts so they will get put into `sent` and will never change status and so `_process_for_status` won't run for every text message we send.
I've chosen to use the country_prefix. This is 1-4 digits long. It will require the interpretation of which country that is later on in the monitoring pipeline. We may want to change that in the future so we instead put something more readable in the metric upfront (like 'america-canada-dominican-republic' instead of '1') but lets see how this goes (mostly how easy it will be to get …

Add statsd statement for international sms per country code

---

app/dao/notifications_dao.py
app/models.py
tests/app/job/test_rest.py

So we can put that field in the report our users download.

Add API key name to notifications serialisation for CSV

---

app/celery/process_sms_client_response_tasks.py
app/delivery/send_to_providers.py

We don't want to log all 44 numbers on this metric as it dwarfs all the other metrics (we send the vast majority of our traffic to 44).
We use the `international` flag because messages send to Jersey, Isle of Mann, Guernsey do start with 44 but are still classed as international.

Only incr international sms metric if number is international

---

app/__init__.py
app/dao/letter_rate_dao.py
app/letters/rest.py
app/models.py
tests/app/letters/test_rates.py

This means we don’t have to keep them in two places (database and admin app) and means the rates displayed on the frontend will update automatically as soon as new ones come into effect.
I’ve chosen a format which will work well with https://github.com/alphagov/notifications-admin/pull/4960

Add an endpoint to get current letter rates

---

tests/app/service_invite/test_service_invite_rest.py

This test was relying on `Notification.query.all()` returning three notifications in the same order, but they are occasionally returned in a different order.

Fix flaky test

---

app/dao/service_callback_api_dao.py
app/schemas.py
app/service/callback_rest.py
tests/app/dao/test_service_callback_api_dao.py
tests/app/test_schemas.py

We have a bug where editing the delivery status callback for a service
can actually overwrite the complaint callback instead. We don't have a
proper UI for changing or adding complaing callbacks - there is only one
team that has this set up.
The `get_service_callback_api` function wasn't filtering by callback
type, so could return the delivery status callback or could return the
complaint callback, leading to the wrong type being updated. This adds
an extra filter to the function so that we have to specify the type of
callback we are updating.

Fix delivery callbacks sometimes updating complaints callbacks instead

---

app/job/rest.py
app/letters/utils.py
tests/app/job/test_rest.py
tests/app/letters/test_letter_utils.py

We store a Redis key for the total daily notifications sent by a service and for each notification type so that we can ensure that services don't exceed their rate limits. If a large batch of letters is cancelled, we should adjust these values in Redis so that cancelled letters do not count as part of the rate limit.
This adds a function to update the values in Redis for total daily notifications sent and total daily letters sent by service if a letter job is cancelled. This could be added to the endpoint to cancel a single letter, but cancelling individual letters is unlikely to cause a service to falsely appear to go over its limit.
It makes use of a new `decrby` method in the `RedisClient`. It would be possible to just use `set` to re-set the value, however the benefit of using …

Adjust values in Redis if letters are cancelled

---

entrypoint.sh

What
----
Switch to using an exec in entrypoint.sh
The exec will replace the the entrypoint pid (usually 1) with the main gunicorn or flask one.
Why
----
Following guidance [from aws](https://aws.amazon.com/blogs/containers/graceful-shutdowns-with-ecs/) we should use exec to prevent the shell script middleman from consuming SIGTERM signals and not passing them to child processes.

Switch to using an exec in entrypoint.sh

---

requirements.in
requirements.txt

* Include remote_addr in request logs
* NotifyRequest: handle trace ids when not handed X-B3-TraceId by paas
***
Complete changes: https://github.com/alphagov/notifications-utils/compare/74.4.0...74.5.0

Bump utils to 74.5.0

---

app/service/rest.py
tests/app/service/test_rest.py

https://github.com/alphagov/notifications-api/pull/3997 added a new function, `adjust_daily_service_limits_for_cancelled_letters`, to adjust the Redis values for total notifications sent and total letters sent when a letter job is cancelled.
This change calls the function when cancelling a single letter too.

Adjust Redis when a single letter is cancelled

---

docker/Dockerfile

* we don't need to copy across the makefile as we copy everything on the next line
* we dont need the port/flask_app/etc as they're defined in pytest.ini
* we don't need the notifciation_api db in the sqlalchemy URI as the tests don't use that
* we don't need to create the notification_api db either

remove unnecessary db lines

---

app/clients/document_download.py
app/template/rest.py
requirements.in
requirements.txt
tests/app/clients/test_document_download.py
tests/app/conftest.py
tests/app/template/test_rest.py

https://trello.com/c/n4FmWuff/585-annotate-logs-with-cloudfront-http-request-ids
Two obvious other apps the API calls out to - document-download-api and template-preview. One has a pseudo-client, t'other just makes ad-hoc `requests` calls.
If the API makes requests to any _other_ (internal) apps I can't see where gets the related configuration from.
Also bump notifications-utils to get more logging of tracing-related values.

forward onwards request headers to other notify apps

---

manifest.yml.j2
scripts/paas_app_wrapper.sh

This is the "combined app" approach to https://trello.com/c/TSJ74HqV/533-create-a-deployment-in-paas-of-the-workers-that-is-scaled-down-to-0-which-has-the-queue-prefix-for-ecs-production-instead-of-paa

paas manifest: handle notify-delivery-worker-ecs-fixup app

---

manifest.yml.j2

when creating `-ecs-fixup` apps
https://trello.com/c/TSJ74HqV/533-create-a-deployment-in-paas-of-the-workers-that-is-scaled-down-to-0-which-has-the-queue-prefix-for-ecs-production-instead-of-paa
Inconsistent naming schemes keep life interesting I suppose.

paas manifest: use correct `NOTIFICATION_QUEUE_PREFIX` for prod ecs queues

---

requirements.in
requirements.txt

* NotifyRequest: generate own span_id if none provided in headers
* Include onwards request headers in AntivirusClient requests
***
Complete changes: https://github.com/alphagov/notifications-utils/compare/74.6.0...74.8.0

Bump utils to 74.8.0

---

scripts/paas_app_wrapper.sh

https://trello.com/c/q5ehwcty/628-try-and-get-full-celery-logs-for-the-paas-into-logit
Though ugly and unstructured, these include worker-level logs which can contain important error information. We're receiving them on ECS and seeing some errors during worker shutdown. To find out whether we're _always_ been getting these errors we need to be able to see these logs in PaaS.

paas_app_wrapper: don't discard celery worker stderr logs

---

scripts/paas_app_wrapper.sh

Reverts alphagov/notifications-api#4014
That was a fun experiment but it means we get duplicate celery worker messages.

Revert "paas_app_wrapper: don't discard celery worker stderr logs"

---

requirements.in
requirements.txt

* logging: also attach handlers etc. to celery.worker and celery.redirected
* Always hide barcodes when printing a letter - not only when adding a NOTIFY tag
***
Complete changes: https://github.com/alphagov/notifications-utils/compare/74.8.0...74.9.0

Bump utils to 74.9.0

---

app/config.py

For some reason this was never set for this app, so on PaaS the app just has an empty value.
This configuration should continue to produce `app.request` post-request log messages on PaaS.

config: set `NOTIFY_RUNTIME_PLATFORM` and `NOTIFY_REQUEST_LOG_LEVEL`

---

requirements.in
requirements.txt

To stop logging sensitive information.
***
Complete changes: https://github.com/alphagov/notifications-utils/compare/74.9.0...74.9.1

Bump utils to 74.9.1

---

entrypoint.sh

Celery sets up its own (unstructured) logging handler outputting to stderr, and we can't be certain it won't try to emit potentially sensitive values.
We already discard stderr for celery workers on PaaS, but for some reason never have on ECS.

docker entrypoint: send celery worker stderr to /dev/null

---

entrypoint.sh

For whatever reason, a lot of celery's worker logs are being sent to stdout despite what documentation says.
~No easy way to pre-merge test, so :shrug:~

docker entrypoint: use `--quiet` flag & `--logfile` option to send celery worker logs to `/dev/null`

---

requirements.in
requirements.txt
tests/app/delivery/test_send_to_providers.py

* Remove celery.* structured logging for now. It can return when we have more certainty over what values it will log or can rule out that it is ever given sensitive values.
* Add option to ignore list of web paths from request logging. Defaults to /_status and /metrics.
* Add new fields to web request log messages (user_agent, host, path)
***
Complete changes: https://github.com/alphagov/notifications-utils/compare/74.9.1...74.12.0

Bump utils to 74.12.0

---

app/service_invite/rest.py
tests/app/service_invite/test_service_invite_rest.py

When a user requests to join a service, the person responding to that request might want to follow up with the user.
By making the reply-to address the email address of the user making the request they can do this just by hitting reply.
We will also add content to the email later telling them they can do this.
It also means that if the email bounces then that message goes back to the user who made the request, not us.

Set reply to address on join service request as user making the request

---

manifest.yml.j2

As per plan:
https://docs.google.com/document/d/1YlyzUrsxT3wyS2PoT9RzWO651yXRcLXBt3KyzAv7rGs/edit#heading=h.x0lgwjmc38xw

Turn off celery beat running in prod PaaS

---

docker/Dockerfile

This was missing but is relied upon in production. We saw this for the first time when it was run in ECS last night.
https://govuk-notify-gds.sentry.io/issues/5018435002/?alert_rule_id=14332219&alert_timestamp=1709080207374&alert_type=email&environment=production&notification_uuid=8193ee42-da5f-4053-8ec8-c8daa327e3d1&project=4504949325824000&referrer=alert_email
I wonder if there is a more defensive way to write our dockerfile so that we don't run into similar problems in the future if someone added a new folder (and didn't realise/forgot to add it to the dockerfile) but I haven't pondered it for long and so no immediate good ideas.

Add `templates` directory to docker prod build

---

app/dao/templates_dao.py
app/models.py
tests/app/template/test_rest.py

if you update a template to update the sms sender, email reply_to, or letter contact_block, we call a special function
`dao_update_template_reply_to`.
this function has not been kept up to date with changes to the template model, and as a result, when people edited their templates, other bits of data got removed and left the template in an inconsistent state.
the reasons we added this function are complex and to do with nuances of versioning that i haven't fully digested[^1]
this bug has appeared before[^2]
We should fix this function properly in the near future, but for now the priority is to make sure this doesn't reoccur.
[^1]: #1556
[^2]: #2347
we should fix this properly by refactoring update_template

fix bug with setting letter contact block deleting some fields

---

app/dao/services_dao.py
app/service/send_notification.py

https://trello.com/c/fZVZvLHh/691-fix-the-5xx-errors-on-notification-check-admin-app-route
A `Service`'s `users` aren't needed until the recipient is validated, at which point `service_allowed_to_send_to` does a re-fetch of the service anyway. So whether or not performing an eager load of all users is the most efficient way of performing this check, there's no need to do it twice.
This is likely what was causing some requests to fail on ECS (though the exact mechanism is unclear) - but all services for which this view caused a segfault had a ridiculous number of users (>500) which could have been causing memory issues for the process.
I put together a version of this that used `raiseload` in place of `joinedload` and it passed the tests (which I'm fairly confident exercise this code). So …

send_one_off_notification: don't eager-load users on initial load of service

---

app/celery/process_ses_receipts_tasks.py

So that when investigating, we are reassured that we got the delivered receipt for the email.
This makes logs for emails more consistent with logs for sms.
Consider: this means we will produce more logs.

Log successful delivery for emails

---

migrations/.current-alembic-head
migrations/versions/0440_new_sms_allowance_n_rate.py

through a migration.
New sms rate: 2.27p
New allowances:
- 30,000 free text messages for `central`, `nhs_central`
- 10,000 free text messages for `local`, `nhs_local`, `emergency_service`
- 5,000 free text messages for `school_or_college`, `other`
- 0 free text messages for `nhs_gp`
My local db after migration:

Add new sms rate and allowances into the database

---

app/celery/scheduled_tasks.py
tests/app/celery/test_scheduled_tasks.py

The `run_populate_annual_billing` scheduled task was calling the wrong function - itself intead of `populate_annual_billing`. It hasn't been run yet (it only runs once a year) so we hadn't seen errors.

Fix `run_populate_annual_billing` task

---

app/__init__.py
app/dao/sms_rate_dao.py
app/models.py
app/sms/rest.py
tests/app/sms/test_rates.py

This mirrors what we did for letter rates in https://github.com/alphagov/notifications-api/pull/3994
It’s simpler here because there’s only one rate for SMS, rather than letters which have different sheet counts, postage classes, etc.

Return current text message rate from API

---

app/dao/api_key_dao.py
app/dao/service_callback_api_dao.py
app/dao/service_inbound_api_dao.py
app/dao/services_dao.py
app/dao/templates_dao.py
app/history_meta.py
app/template/rest.py
tests/app/conftest.py
tests/app/db.py

Objects that have a corresponding `…History` object must have a value for their `id` property. This is how we know they are versions of the same object, because they have the same value for their primary key.
We assign the value of the `id` property in the DAO layer, for example:
https://github.com/alphagov/notifications-api/blob/492143312cd5ad75775f49c8fd7d3037370115fd/app/dao/templates_dao.py#L17
This is assumed to be the last code that is run before the object is persisted. If we didn’t do this then SQLAlchemy would generate the ID for us at the time we `commit`.
However there is a problem if – earlier in the process – the REST layer creates other objects which have a foreign key relationship to an object which has not been persisted.
What happens in this case is:
1. primary object …

Late-assign IDs to objects with history

---

app/notifications/rest.py
app/notifications/validators.py
app/serialised_models.py
app/service/send_notification.py
app/template/rest.py
app/v2/notifications/post_notifications.py

Using the method on the service model itself is less verbose.
Some detail of specific changes in individual commits.

Remove `service_has permission` function

---

app/dao/templates_dao.py
app/models.py
app/template/rest.py
tests/app/dao/test_templates_dao.py

See individual commits.
The aim of this is to get rid of the separate method with its hand-crafted `dict` of properties, and prevent a re-occurrence of bugs like https://github.com/alphagov/notifications-api/pull/4032
I would have liked to go further and re-use the same code path as other updates but was defeated by schema weirdness (something to do with `reply_to`, `service_letter_contact_block` and `service_letter_contact_block_id` being sort of the same things but sort of different).

Simplify how we update contact blocks on letter templates

---

app/template/rest.py

In https://github.com/alphagov/notifications-api/pull/361 we introduced a check to see if a template had changed before saving a new version of it.
That pull request introduced a list of fields to check for changes. This list needed to be maintained and added to over time, otherwise changes to a new field wouldn’t be considered a material change (for example if only `letter_attachment` changed).
Rather than maintaining a custom list of which fields to check for changes, let’s check all of them. This also enables some refactoring, which I’ve split into separate commits.
Things which change a template but don’t create a new version (for example moving it from one folder to another) go through different routes anyway, so I don’t think there’s a concern about accidentally creating spurious …

Check every field to see if a template has changed 

---

scripts/lint_sql_migrations.sh

squawk can take a sql file and lint it for common errors, such as renaming a column in an unsafe way or running a command that might acquire a wide-reaching long-lasting lock.
this commit wraps squawk in a little bash script that gets the alembic upgrades output as sql
there doesn't appear to be an obvious way to `#noqa` style "accept" a squawk warning if we know it's okay (for example, dropping a column we know is no longer written to or read from), so we can't immediately integrate this in to our CI pipeline or pre-commit hooks unfortunately.
typical output:
```
❯ ./scripts/lint_sql_migrations.sh
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Generating static SQL
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO …
```

lint alembic migrations with squawk

---

entrypoint.sh

https://trello.com/c/o5DyzyFT/740-investigate-performance-of-messages-sent-within-10-seconds
They don't use much memory and spend most their time waiting for responses from calls to providers. These instances rarely even hit 20% memory usage at the moment.
With the CPU autoscaling trigger kept as it is, we should still autoscale to a similar number of instances for a given load, but cases of immediate demand, this should make the existing instances able to take on more load until the new instances have started.

entrypoint.sh: set `CONCURRENCY` of 12 for `api-worker-sender`

---

entrypoint.sh

This logic belongs better in infra code & passed in as an environment variable. 4 is a sensible default otherwise.
Depends on https://github.com/alphagov/notifications-aws/pull/2161 to provide this env var.

entrypoint.sh: refactor, removing `CONCURRENCY` logic

---

app/notifications/receive_notifications.py
tests/app/notifications/test_receive_notification.py

they were prev on the catch all internal queue but they fit better here (and we can scale sms-callback queue better to deal with potential spikes in volumes based on 3rd party inputs)

send inbound sms tasks to service-callback queue

---

Makefile

`API_HOST_NAME` is set to the full URL in the Concourse pipelines, so it is already in a format like `https://api.notify.works`. By setting it to `API_HOST_NAME=https://api.${DNS_NAME}` we were ending up with it being set to `https://api./_status`, and the check to see if migrations should run was always returning true.

Fix check to see if migrations should run

---

app/dao/users_dao.py
tests/app/dao/test_users_dao.py

This means we won’t need to access the database to remove people’s access when they leave GDS.

Remove platform admin when a user is archived

---

requirements.in
requirements.txt

* linting changes
* Reject Gibraltar’s postcode (`GX11 1AA`) when validating postal addresses
***
Complete changes: https://github.com/alphagov/notifications-utils/compare/76.0.0...76.0.2

Bump utils to 76.0.2

---

app/authentication/auth.py
app/config.py
tests/app/authentication/test_authentication.py

https://trello.com/c/wZF8EJLW/706-see-if-we-should-remove-the-checkproxyheader-code-from-our-apps-and-remove-it
This removes the check for the proxy header that was used to stop people accessing the apps via CloudFront when deployed on the PaaS. We can also get rid of the environment variables that were used for the check.

Stop checking proxy header before requests

---

migrations/.current-alembic-head
migrations/versions/0443_drop_ix_letter_cost.py

We did an audit of indexes in our database and found that some of them have not been used at all.
Here is the list of all unused insexes: https://docs.google.com/spreadsheets/d/1Eqfze5WTXM4LDIFDqPcfQ_7axnaodC0zzOz5eFmCU-U/edit?usp=sharing (look at 2nd tab)
In this PR I am removing one of those indexes, just to cautiously dip a toe. If that goes well, we will remove all the rest of them.
More context about decision to remove unused indexes is explained in this blog post: https://www.cybertec-postgresql.com/en/get-rid-of-your-unused-indexes/

Drop unused index on letter despatch cost threshold

---

app/clients/email/aws_ses.py
app/delivery/send_to_providers.py
tests/app/clients/test_aws_ses.py
tests/app/delivery/test_send_to_providers.py

This is probably worth a separate pull request to anything around custom headers, as it makes a big change - using SESv2 (https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sesv2.html), which has a new format.
Also do some refactoring to make it clearer what is being passed in and around this function

Move to using SES v2 API

---

app/clients/email/aws_ses.py
app/delivery/send_to_providers.py
requirements.in
requirements.txt
tests/app/clients/test_aws_ses.py
tests/app/db.py
tests/app/delivery/test_send_to_providers.py

Requires the following to be merged (split into two PRs to keep PRs focused, and risk lower)
-----------
[bump boto3 (and celery) to bring in latest ses API](https://github.com/alphagov/notifications-api/commit/3bc9a759ca44f4e9e93c6acd98681fbcf94fdeac) 
we need to bump boto3 to bring in the changes to the sesv2 API to add
support for custom headers.
I went through the boto3 changelogs with a fine toothcomb - nothing
there is particularly alarming. Here's a filtered list of just the lines
i think will affect our apps. Note that we only use boto3 for
interacting with things programatically, so while there may have been
changes to, eg, boto3's ecs API, since we don't interact with ECS from
our apps we don't need to worry about that. See the filtered list[^1].
Notably there were some changes …

Send unsubscribe header

---

app/v2/notifications/notification_schemas.py
tests/app/v2/notifications/test_notification_schemas.py

This is to enforce https urls for unsubscribe links posted to the post_notification endpoint.

Add https validation for unsusbscribe links

---

app/models.py
migrations/.current-alembic-head
migrations/versions/0444_user_features_email_column.py

This adds the `receives_new_features_email` column to the users table so that we can store whether or not people want to receive emails about new features in the database. It has a default of true, but we will need to manually update the data before using it since we have a list of people who have opted out.
While this migration will require an access exclusive lock, it does pass the Squawk linting and it is running it on a small table.

Add column to User table to show if user receives features email

---

app/models.py
migrations/.current-alembic-head
migrations/versions/0445_drop_unused_indexes_1.py
migrations/versions/0446_drop_unused_indexes_2.py

I divided them into two migration files for better readability.
Info on droping many indexes at once concurrently: https://dba.stackexchange.com/questions/319720/multiple-drop-index-concurrently-running-on-the-same-table-in-postgres
Here is the list of all unused indexes: https://docs.google.com/spreadsheets/d/1Eqfze5WTXM4LDIFDqPcfQ_7axnaodC0zzOz5eFmCU-U/edit?usp=sharing
Why it's good to remove unused indexes: https://www.cybertec-postgresql.com/en/get-rid-of-your-unused-indexes/

Remove 9 biggest remaining unused indexes

---

app/models.py
app/v2/notifications/create_response.py
app/v2/notifications/notification_schemas.py
app/v2/notifications/post_notifications.py
tests/app/v2/notifications/test_get_notifications.py
tests/app/v2/notifications/test_notification_schemas.py
tests/app/v2/notifications/test_post_notifications.py

This is:
- more correct (it’s a URL designed for machine consumption, not a link in a web page)
- less likely to be confused with the manual unsubscribe links we talk about in our guidance<sup>1</sup>
This will mean a bit of work to rename the parameter in all the clients, but easier to do it now than after we’ve released them (when it would be a breaking change)
***
Internally we retain `unsubscribe_link`. We will make it consistent later, in order to avoid any need for updates to the `notifications` table (which would require locks, multiple migrations, etc).
***
1. https://www.notifications.service.gov.uk/using-notify/unsubscribe-links or
snapshotted at https://github.com/alphagov/notifications-admin/blob/20fd4424d613d256e02284cc7c523392c18e8b8c/app/templates/views/guidance/using-notify …

Rename `unsubscribe_link` to `one_click_unsubscribe_url`

---

app/dao/notifications_dao.py

Only check FactNotificationStatus table for last used date if there are any notifications at all for that template in that table.
Ticket: https://trello.com/c/RyEMRpQw/719-find-out-why-template-last-use-query-is-slow-and-fails
Possible other solutions: we could only search through data from last 6 months or last year. Then we would have to change current warning text: "This template has never been used." to something like: "This template has not been used within last 6 months."
Here is the screenshot with the warning text for context:
I think changing the text would make it a bit more confusing - do we mean the template was used before last 6 months, or that we just don't know (that second interpretation would be more true).
So I vote for just making this little change for now and keeping …

Speed up 'last used' query by only checking table when needed

---

app/config.py

We already had a manually set FROM_NUMBER of `development`, but when we updated the root config to be environment-agnostic[^1] we missed this. As such, when FROM_NUMBER isn't set manually in the environment (which it isn't on dev envs), we'd error because it'd default to None rather than to `development`.
Move this declaration to the `Development` config where it fits anyway
[^1]: https://github.com/alphagov/notifications-api/pull/4078

move FROM_NUMBER override from root Config to Development

---

app/celery/nightly_tasks.py
app/commands.py
app/config.py
tests/app/celery/test_nightly_tasks.py

We stopped receiving ack files from the DVLA when we switched to sending letters using their API, so no longer need the nightly task to check that we have them.
We will need to update Cronitor too to remove this task.

Delete unused `raise-alert-if-no-letter-ack-file` nightly task

---

app/celery/nightly_tasks.py
app/celery/scheduled_tasks.py
requirements.in
requirements.txt
tests/app/celery/test_nightly_tasks.py
tests/app/celery/test_scheduled_tasks.py

Every ticket type is now a "task" and should have the `notify_task_type`
drop down menu populated instead of the `ticket_categories` dropdown,
which has been removed.
Needs https://github.com/alphagov/notifications-utils/pull/1121 to be merged first

Update code to use new Zendesk form 

---

app/models.py

Fix a couple of warnings you could observe when running `flask db heads` to run alembic
-------------
[set NotificationAllTimeView relationships viewonly](https://github.com/alphagov/notifications-api/commit/4122625a4a8438575433053257abf7c5a986d435) 
NotificationAllTimeView is a view (quelle surprise). You can't edit a view rather than the underlying table.
Sqlalchemy doesn't have a way to mark a model as a view, so there's nothing stopping you writing `NotificationAllTimeView(id=..., ...)`. This would error when sqlalchemy tried to execute the sql.
However, as sqlaclhemy doesn't know this it's printing out lots of warnings about UnsubscribeRequest.notification conflicting with NotificationLetterDespatch.notification. We can solve these warnings by marking the relationships to the …

Fix sqla warnings

---

app/models.py
migrations/.current-alembic-head
migrations/env.py
migrations/versions/0448_t_has_unsub_link_backfill.py
migrations/versions/0449_t_has_unsub_link_constraint.py
migrations/versions/0450_t_has_unsub_link_validate.py
migrations/versions/0451_t_has_unsub_link_not_null.py
migrations/versions/0452_th_has_unsub_link_backfill.py
migrations/versions/0453_th_has_unsub_link_constrain.py
migrations/versions/0454_th_has_unsub_link_validate.py
migrations/versions/0455_th_has_unsub_link_not_null.py
migrations/versions/0456_t_unsub_constraint.py
migrations/versions/0457_th_unsub_constraint.py
migrations/versions/0458_validate_unsub_constraints.py
tests/app/dao/test_templates_dao.py

I heard you like migrations. so I made eight of them.
this follows the same four step plan as we did in migrations 0431-0435.
See https://github.com/alphagov/notifications-api/pull/3954 for more details
(I also tweaked alembic to make squawk check against the same alembic config as when we actually run against real envs)

Set templates/templates_history has_unsubcribe_link boolean to be not null

---

requirements.in
requirements.txt

* Restrict postcodes to valid UK postcode zones
***
Complete changes: https://github.com/alphagov/notifications-utils/compare/78.0.0...78.1.0

Bump utils to 78.1.0

---

app/celery/service_callback_tasks.py
app/celery/tasks.py
app/notifications/receive_notifications.py
tests/app/celery/test_service_callback_tasks.py
tests/app/celery/test_tasks.py
tests/app/notifications/test_receive_notification.py

Best reviewed commit by commit.
See https://trello.com/c/KQ6vP4EK/770-incident-action-review-if-we-can-make-inbound-sms-callbacks-more-similar-to-how-we-do-delivery-notification-callbacks for context
Very open to critique on my test coverage here please

Make service callback sending consistent

---

requirements.txt

Versions 2.32.0 and 2.32.1 were yanked and are no longer available from PyPI

Bump requests to the latest version

---

app/service_invite/rest.py
tests/app/service_invite/test_service_invite_rest.py

If someone isn’t getting a response to their request they could try:
- requesting again
- asking a different team member
This pull request adds a link to the personalisation in the receipt email which will let them do this.
It doesn’t change the text of the email itself since that isn’t version controlled.

Add link to re-request invite to join service receipt email

---

app/celery/service_callback_tasks.py
tests/app/celery/test_service_callback_tasks.py
tests/app/celery/test_tasks.py

This reverts commit b877f233945a2fc4680f3f3fed4f8520eee26b0f.
The service ID isn't being logged. Although the service id is being added to `extra`, it isn't appearing in our logs. My hunch is that the it is being replaced afterwards by our generic service-id adding logging:
https://github.com/alphagov/notifications-utils/blob/main/notifications_utils/logging/__init__.py#L217
For the moment, let's revert this code because it isn't doing anything and then I'll hope to find time to find a fix/alternative for this.
Here is one of the logs in logit that I'd expect to have service-id set appropriately but is not:
https://kibana.logit.io/s/4c3b5032-5afa-42e5-8211-bcba010be352/app/kibana#/doc/8ac115c0-aac1-11e8-88ea-0383c11b333a/logstash-2024.06.14/doc?id=vppKFpABBlR3BSkAAkK4&_g=(refreshInterval:( …

Revert "Log service ID as part of sending callbacks if possible"

---

app/clients/sms/firetext.py
app/clients/sms/mmg.py
app/config.py
tests/app/clients/test_firetext.py
tests/app/clients/test_mmg.py
tests/app/conftest.py

What
----
Add config option to set receipt callback urls for firetext and mmg.
FIRETEXT_RECEIPT_URL : Set firetext parameter 'receipts' when sending sms messages
MMG_RECEIPT_URL : Set mmg parameter 'devurl' when sending sms messages
These options override account wide callback urls for Firetext and MMG.
Why
----
Having the option to override these settings allows us to share accounts for development environments.
These options are not intended to be used in non-development accounts.

Add config option to set receipt callback urls for firetext and mmg

---

app/celery/tasks.py
tests/app/celery/test_tasks.py

This PR fixes a bug that was noticed by a user as described in [this](https://trello.com/c/VRzsixUp/59-add-unsubscribelink-to-saveapiemailorsms) card, by adding `unsubscribe_link` to the persisted notification in `save_api_email_or_sms`.
I have added an assertion to `test_save_api_email_or_sms` to test that a provided `unsubscribe_link` is set on the notification.

add unsubscribe link to save_api_email_or_sms

---

scripts/process_sender_names.py

```
C417 Unnecessary `map` usage (rewrite using a generator expression)
```
This slipped through because it was introduced at the same time as new stricter linting rules.

Appease ruff

---

app/utils.py
tests/app/dao/test_organisation_dao.py
tests/app/dao/test_users_dao.py
tests/app/email_branding/test_rest.py
tests/app/service/test_archived_service.py

- by archiving service fields with a date suffix, this means that if we archive more than one service with the same name in one day, we get a constraint error
- here, this is being change to datetime to avoid the issue
[Change archive name format from date to datetime](https://trello.com/c/xAjLBYtE/794-change-archive-name-format-from-date-to-datetime)

fix(utils): change archived field nomanclature from date to datetime

---

app/dao/users_dao.py
tests/app/dao/test_users_dao.py

When archiving a user, we were removing them from their services and removing all service permissions. We were also removing them from any organisations that they were a member of, but we were not removing their organisation permissions which gave an error when trying to serialize the user.
This change ensures we now remove an archived user's organisation permissions too.

Remove org permissions when archiving a user

---

app/celery/tasks.py
app/config.py
app/delivery/send_to_providers.py
app/serialised_models.py
app/v2/notifications/post_notifications.py
tests/app/celery/test_tasks.py
tests/app/v2/notifications/test_post_notifications.py

we have no high volume services defined in our creds at all so we can simply remove the entire codebase without worrying about deprecation orders of task definitions
Here are some reasons I think we should remove it:
1. There’s two queues (save-api-email-tasks and save-api-sms-tasks and a worker (api-worker-save-api-notifications)  that we pay money for
1. Code complexity - this was raised when @BlessedDev tried to update when we save notifications to handle unsubscribe links (which we will need to make sure work for [GOV.UK](http://gov.uk/) Email!), and it’s more nuanced because this json blob is passed on a celery task.
1. We have other services we consider as large such as NHS login, NHS Notify, DWP Prod, that we do not have on this queue and we have been fine
1. I don’t think we’ve …

remove high volume queues

---

app/celery/service_callback_tasks.py
app/notifications/receive_notifications.py
tests/app/celery/test_service_callback_tasks.py
tests/app/notifications/test_receive_notification.py

The service-callbacks worker now has database access: https://github.com/alphagov/notifications-aws/pull/2284
We can now make the change to put inbound SMS tasks on the service-callbacks queue, with retries on the service-callbacks-retry queue for consistency with other callback tasks.

Send inbound sms callback tasks to service-callback queue

---

app/models.py
tests/app/test_model.py

Even though we send the rate as a float to Redis, redis then gives it back to us as a byte-string.
We did not take it into consideration when building the test data, and it broke our deploy sadly.
So now we update the unit tests mocks to behave more realistically, and we cast the rates we are getting back from redis to float to fix the issue.

When getting rate from Redis cache, cast it to float

---

app/models.py
tests/app/test_model.py
tests/app/v2/notifications/test_get_notifications.py

This is following missed piece of content review. We are renaming it so it's more specific, and so users do not get confused.

When serializing cost info for notification, rename rate to sms_rate

---

app/schema_validation/__init__.py
app/service/send_pdf_letter_schema.py
tests/app/template/test_rest.py
tests/app/v2/notifications/test_post_letter_notifications.py

The postage validator allowed the value to be "first", "second", "europe" or "rest-of-world", however when sending a letter using the API or setting the postage on a template you should not be able to use the international postage options.
We use the postage validator in a number of places and there is one of those that _does_ need to allow international postage - when the admin app sends a precompiled letter it can use the international postage types. This splits the postage validator into two - one for the UK types of postage (used in most places) and one for the admin app to use (used in one place).

Fix postage validation in schemas

---

app/dao/users_dao.py
app/user/rest.py
tests/app/dao/test_users_dao.py
tests/app/user/test_rest.py

This function isn’t called without an ID anywhere.
It was introduced without explanation in January 2016 (a327702ad011db87e2e26a6281177adfdb9d8185)
It wouldn’t be very useful now because we have tens of thousands of users.

Remove no-argument form of `get_user_by_id`

---

app/config.py
entrypoint.sh
tests/app/test_config.py

Here are some reasons I think we should remove it:
1. There’s two queues (save-api-email-tasks and save-api-sms-tasks and a worker (api-worker-save-api-notifications)  that we pay money for
1. Code complexity - this was raised when @BlessedDev tried to update when we save notifications to handle unsubscribe links (which we will need to make sure work for [GOV.UK](http://gov.uk/) Email!), and it’s more nuanced because this json blob is passed on a celery task.
1. We have other services we consider as large such as NHS login, NHS Notify, DWP Prod, that we do not have on this queue and we have been fine
1. I don’t think we’ve ever tested that this actually increased performance of Notify. Our current DB connection usage is pretty low and even at peak times we’re no-where near our hard limit …

Remove high volume worker

---

app/constants.py
app/notifications/validators.py
app/schema_validation/__init__.py
app/schemas.py
app/v2/errors.py
requirements.in
requirements.txt
tests/app/v2/notifications/test_notification_schemas.py
tests/app/v2/notifications/test_post_notifications.py
tests/app/v2/test_errors.py

Update to API to use utils 80.1.1, makes changes to v2 schema validation and tests to support breaking changes to how exception objects are instantiated, and makes changes to tests using invalid (but previously uncaught) numbers.

use new phone number validation code

---

app/one_click_unsubscribe/rest.py
tests/app/one_click_unsubscribe/test_one_click_unsubscribe.py

We want to cache a summary of unsubscribe requests for each service to make the dashboard load quickly.
We need to invalidate this cache whenever:
1. a new requst comes in
2. some requests are marked as completed
3. some old requests are cleaned up according to our data retention policy
This commit does 1., as a start

Delete cache when processing new unsubscribe request

---

app/dao/unsubscribe_request_dao.py
app/service/rest.py
tests/app/dao/test_unsubscribe_request_dao.py
tests/app/service/test_rest.py

The dashboard says:
> ## In the last 7 days
>
> **1,234** email unsubscribe requests
> Latest report 3 weeks ago
At the moment the 1,234 number will go down when requests are marked as completed. This doesn’t feel right, because those requests have still been received in the last 7 days.
This pull request changes the query to count all requests from the last 7 days, whether or not they have been marked as completed.
This is consistent with received text messages and returned letters (although we don’t have a similar concept of marking these are completed at the moment).

Count all unsubscribe requests from last 7 days on dashboard

---

app/notifications/validators.py
requirements.in
requirements.txt
tests/app/v2/notifications/test_post_letter_notifications.py

This brings in the new `has_no_fixed_abode_address ` method added to the `PostalAddress` to validate that letters are sent to real addresses.

Add validation for letters sent to "no fixed abode" addresses

---

app/clients/letter/dvla.py
tests/app/clients/test_dvla.py

This changes the JSON keys to match the new names that the DVLA will use. It also changes the value of the retry window to be the default value for their API.

Update callback params when sending letters to DVLA

---

app/celery/service_callback_tasks.py

We changed this from warning to error in june[^1], however, in practice this just massively obscures other errors in our logs to the order of tens of thousands, and in practice we aren't doing anything about these errors. We're not routinely contacting services or otherwise tracking these issues to see if they're growing/shrinking/etc.
Our solution should perhaps involve some way to alert services automatically to their failures. Either proactively (eg via email) or reactively (an alert on their dashboard). 
[^1]: https://github.com/alphagov/notifications-api/commit/3600d123e5e2c061d357312b34a93a892d1aa7ef

downgrade callback log message

---

app/notifications/notifications_letter_callback.py
tests/app/service/test_rest.py

This is only temporary code, since we have a separate story to handle callbacks properly. However, this change stops the endpoint from giving an error while testing.

Fix letter callback endpoint

---

app/service/rest.py
tests/app/service/test_rest.py

We changed the query and renamed this column, but missed changing the reference here.

Fix reference to ‘unprocessed’ unsubscribe requests

---

app/dao/unsubscribe_request_dao.py
app/service/rest.py
tests/app/service/test_rest.py

This PR adds a `process_unsubscribe_request_report` endpoint which supports the work done in [this](https://github.com/alphagov/notifications-admin/pull/5152) PR to facilitate a user being able to mark an `unsubscribe_request_report` as completed by updating the `processed_by_service_at` value of an `unsubscribe_request_report` as described in [this](https://trello.com/c/5hJS5Oia/54-let-users-mark-email-unsubscribe-requests-as-completed) card.

Add process unsubscribe request report endpoint

---

app/delivery/send_to_providers.py
app/models.py
app/notifications/process_notifications.py
requirements.in
requirements.txt
tests/app/delivery/test_send_to_providers.py
tests/app/notifications/test_process_notification.py

Best reviewed commit-by-commit.
When  a user has provided us an unsubscribe link through an API call we need to store it. But where we are generating the link we don’t need to store it, because we already store all the information needed to generate it.
By not storing it we make it easy to differentiate which notifications have user-supplied unsubscribe links and which have ones which we are generating.
We have started sending list-unsubscribe headers if a user marks a template as unsubscribeable, for teams who aren’t using the API.
However we are already telling these teams to add unsubscribe links to the body of their emails.
This means:
- there are two different ways to add unsubscribe links
- users will have to manage requests to unsubscribe coming from two different places
This will …

Add unsubscribe link to body of emails

---

app/one_click_unsubscribe/rest.py
tests/app/one_click_unsubscribe/test_one_click_unsubscribe.py

When a user unsubscribes we delete the cahce of statistics which populates the dashboard.
We also cache the summary of unsubscribe reports that the person running the service has batched up.
When we get a new request to unsubscribe it goes into the ‘unbatched’ report, so we need to delete the cache of reports for it to appear.

Purge additional Redis cache when user unsubscribes

---

app/dao/unsubscribe_request_dao.py
app/service/rest.py
tests/app/dao/test_unsubscribe_request_dao.py
tests/app/service/test_rest.py

This PR adds the endpoints to support downloading an `unsubscribe-request-report` as described in [this](https://trello.com/c/BeZGTW0E/53-let-users-download-email-unsubscribe-requests) card.

Enable download of unsubscribe request reports

---

app/celery/letters_pdf_tasks.py

This adds a log line for precompiled API letters that were sent to addresses which were no fixed abode addresses. This will allow us to look up the address of the notification and check for false positives.
For templated letters sent via the API, we can already see from the logs if any failed validation due to having a no fixed abode address. We won't be able to see the address that was used, but can check which services are sending them.

Add log line for letters that failed validation due to no fixed abode

---

app/models.py
app/one_click_unsubscribe/rest.py
app/service/rest.py
tests/app/service/test_rest.py

Originally we thought it would be nice and clean to extend the end dates of the reports so there were no gaps between them.
On second thought I think this will be confusing where the latest report claims to run up to the current time. In this case:
- the report, when downloaded might not even contain requests from today so it could look like requests are missing from the report
- the report might claim to have requests up until now, but if any new ones come in between the user clicking on the page and generating the report then they wouldn’t be included
In could also be confusing when a report is cleaned up by data retention. Adjacent reports would then appear to expand to fill the gap, even though they gain no new requests.

Tweak start and end dates of unsubscribe request reports

---

requirements.in
requirements.txt

* Add support for sending SMS to more international numbers. Sending to Eritrea, Wallis and Futuna, Niue, Kiribati, and Tokelau is now supported.
* Extends the validation logic for the `PhoneNumber` class to disallow premium rate numbers
Complete changes: https://github.com/alphagov/notifications-utils/compare/82.2.1...82.4.0

Bump utils to 82.4.0

---

app/models.py
app/service/rest.py
tests/app/service/test_rest.py

When passing dates between the API and admin app we should always do so in UTC with no timezone information, otherwise we risk entering a world of pain.
This is consistent with how other models’ `serialize` methods work.

Fix serialised timestamps of unsubscribe request reports

---

app/functional_tests_fixtures/__init__.py

The token isn't actually needed here, we just need to provide _some_ value because the field is required and the minimum length is 10 characters.
The value 1234567890 is already used in preview (where it's hardcoded in the database)

Don't use pipedream API token in FT fixtures

---

migrations/alembic.ini
tests/conftest.py

Without these, a migration failure (particularly during the unit tests) is a puzzling thing to encounter with little information to go on.
More detail in commit messages.

Improve alembic error output

---

app/dao/unsubscribe_request_dao.py
app/service/rest.py
tests/app/dao/test_unsubscribe_request_dao.py
tests/app/service/test_rest.py

This PR adds an `unsubscribe_request_received_at` column to unsubscribe request reports as described [here](https://trello.com/c/mkDkkHgX/85-update-unsubscribe-request-report-to-include-when-unsubscribe-request-was-received)

Add unsubscribe request received at column to reports

---

app/schemas.py
app/service/rest.py
app/utils.py
tests/app/service/test_rest.py

Paginating by page numbers made us use offset, which makes large queries quite expensive: https://use-the-index-luke.com/no-offset
This caused issues for notifications CSV reports that services can download. If a service has sent many notifications, the report will be very big - even above 1,000,000 rows.
To prevent it, for this use case we will use older_than parameter to paginate instead - that is - we get our notifications sorted by created_at date. So if we set older_than parameter to the id of the oldest notification in a current page/batch, we know where to start our next batch without using the inefficient offset mechanism.
For now, for other use cases, this query will still use offset
- this is to get the improvement out quickly where it's needed and prevent future incidents. …

Use older_than to paginate get_all_notifications_for_service

---

app/celery/scheduled_tasks.py
app/config.py
app/dao/users_dao.py
migrations/.current-alembic-head
migrations/versions/0461_user_research_email.py
tests/app/celery/test_scheduled_tasks.py
tests/app/conftest.py
tests/app/dao/test_users_dao.py

https://trello.com/c/RyvaiUpK/890-automate-email-to-send-out-new-user-survey
We want to send out a survey to users roughly 2 weeks after signing up to Notify. This adds a migration to create the template, and a scheduled task to send the email.
To give examples of which users will be receiving the email:
- The task run on Wednesday 14 August will get users created between Monday 29th July and Sunday 4th August inclusive
- The task run on Wednesday 21st August will get users created between Monday 5th August and Sunday 11th August inclusive
- The task run on Wednesday 28th will get users created between Monday 12 August and Sunday 18th August inclusive.

Add automated email to send out new user survey

---

app/dao/unsubscribe_request_dao.py
tests/app/dao/test_unsubscribe_request_dao.py
tests/app/service/test_rest.py

When we start to delete old unsubscribe requests we will leave behind the reports to which they were joined.
We don’t want to delete these reports completely, since it’s useful for us to keep a record of what happened when, and how many requests there were. We do a similar thing for `Job` objects, where they stay in the database for all time.
However it’s not useful to show these old reports on the dashboard, because if a user clicks through to them they won’t be able to access the underlying requests.
So this pull request modifies the function which returns the list of reports to the admin app, excluding those which no longer have any requests attached to them.

Only return unsubscribe reports with requests

---

migrations/.current-alembic-head
migrations/versions/0462_unsubscribe_created_at.py

So we can perform actions a certain nuber of days after a report is first downloaded, we need to know when it was first downloaded. This is also the same time it gets created. Therefore we can use the pattern of a `created_at` column.
Need to deploy this as a migration first before adding the column to the model.

Add `created_at` column to unsubscribe request reports

---

requirements.in
requirements.txt
tests/app/v2/notifications/test_post_notifications.py

Provides a fix for an edge case was discovered where errors returned from json validation on the v2 API were inconsistent with the old validatio method if an empty string was passed as a phonenumber. The new code returned an INVALID_NUMBER error when it should return a TOO_SHORT error.

Fix v2 api to return consistent error messages when empty strings are passed as phone numbers

---

app/models.py
migrations/.current-alembic-head
migrations/versions/0463_backfill_created_at.py
tests/app/service/test_rest.py

So that the codebase doesn’t have to deal with null values in this column we need to make sure every row has a value. The value chosen is the date when the table was first created. So it’s impossible for any reports to have this as their real `created_at` date.
Secondly we can modify the table to make the column non-nullable.
Now that we know the column will always have a value, we can start returning it in the serialised response.

Backfill `created_at` dates for unsubscribe request reports

---

app/celery/nightly_tasks.py
app/config.py
app/dao/unsubscribe_request_dao.py
app/models.py
tests/app/celery/test_nightly_tasks.py
tests/app/db.py
tests/app/service/test_rest.py

This PR adds celery tasks to cleanup unsubscribe requests that are beyond the data retention period of 7 days for processed requests and 90 days for unprocessed requests.
This [card ](https://trello.com/c/X2Y9Zn26/84-clean-up-old-email-unsubscribe-requests-after-7-days-or-3-months)has more details.

Clean up old unsubscribe requests

---

app/models.py
tests/app/job/test_rest.py

Related to, and needs to go in before this admin PR: https://github.com/alphagov/notifications-api/pull/4175

Return id for serialize_for_csv - so that admin app can determine older_than arg

---

app/dao/unsubscribe_request_dao.py

Maybe this is why the task says it’s run successfully but hasn’t done anything?

Add missing `db.session.commit()` when archiving unsubscribe requests

---

app/dao/unsubscribe_request_dao.py
tests/app/celery/test_nightly_tasks.py

If we don’t do this the numbers on the dashboard and in the reports won’t update.
Unfortunately we need to do this twice per service, since we can’t guarantee execution order of the two Celery tasks.

Delete Redis cache after archiving unsubscribe requests

---

app/dao/unsubscribe_request_dao.py
app/one_click_unsubscribe/rest.py
tests/app/dao/test_unsubscribe_request_dao.py

This PR updates unsubscribe request statistics shown on the dashboard to now show all unprocessed unsubscribe request reports received by a service as described in [this](https://trello.com/c/xgMVnhmV/89-change-the-count-of-unsubscribe-requests-on-the-dashboard-to-include-all-un-completed-ones) card.

Update unsubscribe request statistics

---

requirements.in
requirements.txt

t was discovered that a subset of valid Jersey phone numbers were being incorrectly invalidated by the phone_numbers library code due to a bug in the regex phone numbers were being validated against for the Jersey region. The latest version provides a fix

Updates utils to 84.0.0 to fix a validation bug with the phone_numbers library preventing sending to certain Jersey phone numbers

---

.gitignore
requirements_for_test_common.txt

We excluded this file from version control because it’s copied automatically from utils, so we only need to modify it and track changes there. In theory at least.
In practice Dependabot cannot:
- cope with having a requirements file which isn’t in the repo
- be configured to only look at certain requirements files
So I think the best thing to do is keep this file in version control. It already has an automatically generated comment to suggest it shouldn’t be edited manually.
Dependabot may try to raise PRs against it, but we can resolve these by updating the upstream version in utils. We can then roll out several version bumps in a single PR per app, rather than several.

Version control `requirements_for_test_common.txt`

---

app/models.py
tests/app/user/test_rest.py

We want to be able to use the date that a user was created in admin (for adding as a field to Zendesk tickets), so this change adds it to the user fields that get returned.

Return `created_at` field for users

---

app/celery/process_letter_client_response_tasks.py
app/dao/notifications_dao.py
app/notifications/notifications_letter_callback.py
tests/app/celery/test_process_letter_client_response_tasks.py
tests/app/dao/notification_dao/test_notification_dao.py
tests/app/notifications/test_notifications_letter_callbacks.py

https://trello.com/c/rpy5t1Dh/887-make-dvla-callback-api-update-notificationletterdespatch
For each letter notification, we store in the `notifications_letter_despatch` table the notification ID, the despatchDate (ie: the date when it was printed, which is the date that DVLA will bill us for in their invoice), and the costThreshold which is one of sorted or unsorted - these refer to two different pricing models that DVLA apply based on volumes of letters that we send.
Best reviewed commit by commit, but change now ensures that we write to the `notifications_letter_despatch` table when we get a letter callback from the DVLA.
Still to do: We need to think more about error handling and what happens if the `process_letter_callback_data` task fails part way through - what do we do about …

Make DVLA callback API update `NotificationLetterDespatch`

---

app/models.py
app/service/rest.py
app/utils.py
tests/app/service/test_rest.py

We don’t want people who download spreadsheets having to wonder about what UTC time is.
Originally I thought it would be better for the admin app to do this conversion, but:
- it would be a more fiddly change
- this follows the pattern set by the notifications reports, which return data from the API to the admin app with the UTC/GMT/BST conversion already done: https://github.com/alphagov/notifications-api/blob/526f1ed4d6748e8f83fa72dc119792dee39680e5/app/models.py#L1584-L1599
I’ve also rewritten the test assertion to be hard coded because this makes it harder for bugs to hide.
***
https://trello.com/c/fD9FsfWc/92-fix-times-in-unsubscribe-request-reports

Return local times in unsubscribe request report

---

app/constants.py
app/dao/service_join_requests_dao.py
app/models.py
app/schema_validation/service_join_request.py
app/service/rest.py
migrations/.current-alembic-head
migrations/versions/0464_create_svc_join_requests.py
requirements_for_test_common.txt
tests/app/dao/test_service_join_requests_dao.py
tests/app/service/test_rest.py

As part of the new flow for Service Join Request, we want to start storing the data for join requests on our DB
**DAO**
Defined `ServiceJoinRequest` for interacting with DB data models.py
Methods available:
- dao_create_service_join_request
- dao_get_service_join_request_by_id
**SERVICE (rest)**
Defined`ServiceJoinRequestSchema` for data validation schemas.py
Methods available:
- dao_create_service_join_request
- dao_get_service_join_request
[Update "join a service" flow to persist data
](https://trello.com/c/iI2xFQq9/907-update-join-a-service-flow-to-persist-data)

feat: join service requests

---

app/serialised_models.py
requirements.in
requirements.txt
requirements_for_test_common.txt
tests/app/celery/test_scheduled_tasks.py

* Removes `SerialisedModel.ALLOWED_PROPERTIES` in favour of annotations syntax
* Reverts 84.1.0
* The Zendesk client takes a new optional argument, `user_created_at` which populates a new field on the Notify Zendesk form if provided.
* Remove GIR 0AA from valid postcodes
* Bump versions of common test dependencies (run `make bootstrap` to copy these into your app)
***
Complete changes: https://github.com/alphagov/notifications-utils/compare/84.0.0...85.0.0

Bump utils to 85.0.0

---

app/notifications/process_notifications.py
app/notifications/validators.py
app/schema_validation/__init__.py
requirements.in
requirements.txt
requirements_for_test_common.txt

Two changes:
1) Adds permissions (international and landline) as flags to the phonenumbers validation method so that it can be used universally for all validation.
2) Separates out validation from parsing so that an instance of a phonenumber object represents a possible number, and validation is called explicitly to check whether this possible number can be sent to by a service. This makes the class more flexible and improves code readability.

Updated phonenumber validation code to use allow_landline flag

---

app/__init__.py
app/celery/research_mode_tasks.py
app/celery/service_callback_tasks.py
app/clients/__init__.py
app/clients/document_download.py
app/clients/email/aws_ses.py
app/clients/email/aws_ses_stub.py
app/clients/letter/dvla.py
app/clients/sms/__init__.py
app/clients/sms/firetext.py
app/clients/sms/mmg.py
app/delivery/send_to_providers.py
tests/app/celery/test_research_mode_tasks.py
tests/app/celery/test_service_callback_tasks.py
tests/app/clients/test_document_download.py
tests/app/clients/test_dvla.py
tests/app/clients/test_sms.py
tests/app/conftest.py
tests/app/v2/notifications/test_post_notifications.py
tests/conftest.py

https://trello.com/c/ORGrd1jn/498-upgrade-docker-images-for-our-ecs-apps-to-debian-bookworm
~Depends on https://github.com/alphagov/notifications-utils/pull/1147~
An alternative to https://github.com/alphagov/notifications-api/pull/4165 - the principal difference being that this references `current_app` in the lazy-construction of the clients, which means:
- we can do away with the weird error-throwing early-factory thing that otherwise needs to be replaced in `current_app`
- however, the clients can only ever be accessed from within an app context
- it has sensible(ish) behaviour when multiple app contexts are pushed
This last point might not seem hugely relevant on this app, but when it comes to the `admin` app, the test fixtures do all sorts of funny things with app contexts.
The main …

API clients: make thread-local, allowing use of persistent requests sessions (app context version)

---

app/service/rest.py
app/utils.py
tests/app/service/test_rest.py

Start splitting of get_all_notifications_for_service() into two endpoints:
- one that returns notifications batches for SCV reports
- one that returns notifications batches to show on the page
Why is this - having one endpoint with so many options and flags is confusing. So to simplify - we split it into two leaner endpoints.
In this commit we split out the new endpoint, but the old one stays as is. Once admin app knows to use the new endpoint for CSVs, we will make the old endpoint leaner, too.
Needs to go in before https://github.com/alphagov/notifications-admin/pull/5212

Start split of get_all_notifications_for_service()

---

app/dao/fact_billing_dao.py

...rather than performing a query mentioning every `service_id` by uuid. This might not speed the query up but will at least make it more digestible in rds insights.

fetch_billing_data_for_day: omit service id filter clause if `None`

---

app/celery/nightly_tasks.py
tests/app/celery/test_nightly_tasks.py

To hopefully avoid saturating database iops when thousands of these tasks are requested simultaneously.
Using a `stagger_total_period` instead of an individual step size to avoid a huge number of sub-tasks being spread over an excessively long time. Making this configurable should allow us to trigger ad-hoc invocations with different periods.
~Untested :muscle:~

nightly notification deletion: stagger sub-task invocations over 1h

---

app/clients/sms/firetext.py

Temporarily revert `FiretextClient`'s use of persistent sessions (from #4179) to try and narrow down an issue.

Revert "FiretextClient: use persistent requests session"

---

app/__init__.py
application.py
requirements.in
requirements.txt

See https://github.com/alphagov/notifications-utils/pull/1157
~This successfully raises an exception after 30s, which is what we previously expected our gunicorn timeouts to be set to everywhere (and is what they're set to on our non-eventlet gunicorn apps - template-preview-web & antivirus-web). Perhaps we should be setting it to 60s though - what our cloudfront and ALBs supposedly use - because this will cause the same visible behaviour as we currently get.~
:point_up: Changed my mind - switched this to 60s for the reasons suggested above.
I can demonstrate this working on dev-a to anyone interested.
Note that even though it will stop this app processing a request after N seconds, that doesn't mean this cancellation will necessarily be propagated to whatever this app is waiting on …

use `EventletTimeoutMiddleware` if using eventlet

---

app/models.py
tests/app/service/test_rest.py

This is kind of a convention we follow. It makes it easier to code in the admin app’s model layer when objects are aware of which service they belong to, without having to get this info from the view layer.

Serialize `service_id` in unsubscribe request reports

---

app/celery/nightly_tasks.py
app/dao/notifications_dao.py
tests/app/celery/test_nightly_tasks.py
tests/app/dao/notification_dao/test_notification_dao_delete_notifications.py

Best reviewed commit-by-commit
The commits:
we're concerned that we can't delete 50,000 letters from s3, and move their notifications, within the two minute time during celery shutdown between a worker being told gracefully and firmly (SIGTERM and SIGKILL).
reduce the limit to 5k for letters only, since they have to fetch all the notifications into python to look at s3
this has the advantage that if the worker executing the task downscales, then we won't lose work - instead, we'll just queue up a new task to be executed by another worker.
after the refactor to multiple tasks we would have ended up deleting test notifications every single time we hit the query limit.
now we just do it when the move task returns 0 - ie all the real notifications have already been processed by earlier tasks …

Delete nightly letters fixes

---

app/schemas.py
tests/app/service/test_rest.py

Otherwise when we view a sent notification in the admin app it won’t display the preview of the unsubscribe link.

Return unsubscribe link property of template when getting notification

---

migrations/versions/0464_create_svc_join_requests.py

there's a bug/design flaw in alembic where if you autogenerate a migration script, it'll create the enum implicitly, but won't include it in the downgrade. This is due to complex reasons that I kinda glazed over.[^1][^2]
With this migration, if you run downgrade and then upgrade again it fails due to the enum not being dropped by the downgrade, and thus already existing for the upgrade.
Lets drop the enum manually in the downgrade script. create the enum manually (not because we need to, but just to give a bit of clarity as to what's going on behind the scenes)
[^1]: https://github.com/sqlalchemy/alembic/issues/89
[^2]: https://github.com/sqlalchemy/alembic/issues/868#issuecomment-867914756

manually create and delete enum in existing alembic migration

---

scripts/test_sql_migration_downgrade.sh

if this script finds new migration files, it will
* create a blank DB
* upgrade to the latest head (ie: all new migration files)
* downgrade to the current main to make sure the downgrade scripts run
* upgrade again to make sure the downgrade scripts left things in a sensible state
* fail if there were any sql errors etc
as this just runs the whole branch's diff, this _doesn't_ cover cases where an individual downgrade script is bad, but all when combined with the other downgrade scripts in that branch it works out ok (imagine if you have two versions in a PR, but the downgrade for both alembic versions only happens in the function for one of them).
But i think this is okay as a first step
next steps:
- fail concourse

add script that tests downgrade scripts for new migrations

---

app/models.py
tests/app/dao/test_service_join_requests_dao.py

We have requirement to display the name of service, requester and status_changed_by. Updated db query to include the user and service and also updated response payload.
https://trello.com/c/pQovKftH/976-create-new-approver-flow-for-request-to-join-a-service

Update get service-join-request to include requester and updated_by

---

app/celery/nightly_tasks.py
app/celery/reporting_tasks.py
tests/app/celery/test_nightly_tasks.py

Fixups for #4207 and  #4210
Celery/kombu's SQS support is imperfect and the [caveats note](https://docs.celeryq.dev/en/v5.4.0/getting-started/backends-and-brokers/sqs.html#caveats) that using a `countdown` greater than the `visibility_timeout` will likely cause duplicate tasks. It looks like this is happening to us (though luckily it hasn't caused drastic ill effects so far).
So reduce the max `countdown` time we're using to less than 5 minutes as we're currently using a 5 minute 10 second `visibility_timeout`.
Going further it may be nice if we found a way to issue a warning if trying to use a task `countdown`/`eta` beyond the `visibility_timeout`, but let's get this fixed in the meantime.

nightly tasks: don't use a `countdown` greater than `visibility_timeout`

---

.gitignore
.pre-commit-config.yaml
Makefile
pyproject.toml

So that every time you bump the utils version you get the correct corresponding files and the build is more reproduceable.

Copy common config files from utils in freeze step

---

migrations/versions/0438_request_invite_templates.py

Email 1 and Email 2 templates were created few months back (`0438_request_invite_templates`) and there have been changes in the email content. This PR is to update the email template contents. More info on [this card](https://trello.com/c/tjMqekh0/1016-update-email-1-and-email-2-migrations-for-service-join-request)

Update service-join-request template 0438

---

app/notifications/notifications_letter_callback.py
app/schema_validation/__init__.py
tests/app/conftest.py
tests/app/notifications/test_notifications_letter_callbacks.py

DVLA have informed us that their `Print Date` variable is actually `productionRunDate`, and is in local time rather than UTC. This updates the callback to use the new name and timezone.
We can no longer use the built-in JSON schema validator of `date-time`, so have to use a custom validator.

Update DVLA letter callback spec 

---

app/__init__.py
app/config.py
application.py
gunicorn_config.py

Doing a few things here to make some of the database tweaks we do and timeouts we set more consistent and controllable via environment variables (which will become useful when we e.g. want to use different `statement_timeout` values for different daemons.
Replacement for  #4218
See commits for individual detail..
Successfully tested on dev-a https://concourse.notify.tools/teams/dev-a/pipelines/deploy-notify/jobs/test/builds/52

control timeout configuration using config/env vars

---

app/dao/service_join_requests_dao.py
app/models.py
app/schema_validation/service_join_request.py
app/service/rest.py
tests/app/dao/test_service_join_requests_dao.py
tests/app/service/test_rest.py

This PR introduces a new endpoint that allows updating the status of a service join request. The endpoint also handles assigning permissions to users when the request is approved.
POST /update-service-join-request-status/<uuid:request_id>
**Service Join Request Status Update:**
- Accepts a request to update the status of a service join request (pending, approved, rejected).
- Handles validation of the input payload using service_join_request_update_schema.
- If the service join request is not found, returns a 404 response.
**Add user to service:**
- When the status is set to approved, it adds the user to a service and sets the permission
- This is applied by dao_add_user_to_service
**Send approved email**
- If the user request is approved, an email is sent to the user 
- This is handled …

feat: update service join request

---

app/errors.py
app/v2/errors.py

Turns out handlers added in #4209 aren't enough - several blueprints register their own handlers on `Exception` which has higher priority than our `EventletTimeout` app-level handlers.
Someone with some knowledge/opinion about the v2 api and how it's supposed to behave should weigh in on this, because I just made it mostly mimic the general `Internal server error` handler.
_Are there any more places I need to install this handler...?_

v2 api errors, other blueprint errors: add handler for `EventletTimeout` returning 504

---

app/__init__.py
requirements.in
requirements.txt
tests/app/celery/test_scheduled_tasks.py

On the long road to https://trello.com/c/ORGrd1jn/498-upgrade-docker-images-for-our-ecs-apps-to-debian-bookworm
These are basically the api changes needed to handle the breaking changes in https://github.com/alphagov/notifications-utils/pull/1152. ~Draft because that isn't merged yet.~

notifications-utils: 86.1.0 -> 87.0.0, use thread-local `ZendeskClient`

---

app/models.py
migrations/.current-alembic-head
migrations/versions/0468_add_notifications_trgm_normto_cref_idxs.py

https://trello.com/c/sHzruWY5/929-add-pgtrgm-index
These fields are searched by `dao_get_notifications_by_recipient_or_reference` with `LIKE`/`ILIKE` operators, which are unable to use a btree index as the search terms aren't left-anchored. A `pg_trgm` index can be used by these queries to massively reduce the number of rows that need to be scanned.
Using a GIN index as, despite the documentation suggesting it have slightly faster insertion performance than GiST (which is probably more critical to us), most peoples' real world experiences seem to favour GIN by a significant margin for all operations.
One poster even claims they've *never* managed to get GiST to outperform GIN for `pg_trgm` in any scenario.
Migration adds it with a `CREATE INDEX CONCURRENTLY` command to avoid locking …

models: add `pg_trgm` indexes for `Notification`'s `normalised_to` & `client_reference` fields

---

migrations/.current-alembic-head
migrations/versions/0468.py
tests/test_migrations.py

unfortunately we accidentally merged a PR with a migration that just had "0468" as the reference, rather than a name with a description. This has been deployed through to production now, so rather than updating the alembic_version field in the database, we should just change the filename and the .current-alembic-head file so we (and our unit tests and migration CI checks) don't get confused about which file is the most recent migration head

rename migration file to just 0468.py

---

app/clients/sms/__init__.py
app/clients/sms/firetext.py
app/clients/sms/mmg.py

These are quite aggressive tcp keepalive options, but the http keepalives we're dealing with are on quite a short timescale anyway.
This is extremely hard to test via unit tests, but it has "passed" dev-a.

`SmsClient`: take over `requests_session` construction, configure tcp keepalive

---

docker/Dockerfile

Not having `requirements_for_test_common.txt` in the list of files to copy across before running bootstrap caused an error when building the image.

Add common requirements file to Docker build

---

app/celery/process_letter_client_response_tasks.py
app/config.py
app/dao/notifications_dao.py
app/notifications/notifications_letter_callback.py
entrypoint.sh
tests/app/celery/test_process_letter_client_response_tasks.py
tests/app/notifications/test_notifications_letter_callbacks.py
tests/app/test_config.py

being a bit more explicit with type hints should hopefully remind us that the values in the task are just json dumped, so aren't rich enums or date objects
----
note: i've tested this manually locally by using `curl` and sending an example payload they provided us, but with my own db's UUID swapped. seems to work end-to-end (as well as my local setup works, which is barely at all)

in task, expect values deserialised from json

---

app/service_invite/rest.py
tests/app/service_invite/test_service_invite_rest.py

- Request of join service currently has a mock email address 
- this PR changes this to the actual recipient address

fix: Recipient of join request email

---

app/models.py
migrations/.current-alembic-head
migrations/versions/0469_notifications_xstats_dep.py
migrations/versions/0470_notifications_xstats_mcv.py
tests/app/test_model.py

Individual commits have more detail.
The more interesting thing here is the addition of `__extended_statistics__` on a model, which is something that's only consumed by the new `test_extended_statistics_presence` test to ensure this "declaration" of extended statistics matches those as provisioned by the migrations.
Running these migrations should take negligible time - the new statistics aren't actually collected until the database does its next `ANALYZE` run for the table.

Notification: add multi-variate extended statistics including basic declarative/testing mechanism

---

app/models.py
migrations/.current-alembic-head
migrations/versions/0471_notifications_xstats_dep2.py

Following https://github.com/alphagov/notifications-api/pull/4250, I spotted a couple more relationships I didn't cover in that PR.
All three of these attributes should have a functional dependency between each of them. This is the most concise way to express this, and the planner is still able to use the pairwise relationships when the third attribute isn't involved in the query: https://github.com/postgres/postgres/blob/3cc5e51ab4507b33acc82684b7d79ac43b8a6b5d/src/backend/statistics/dependencies.c#L1555

Notifications: include `job_id` in (`template_id`, `notification_type`) dependency statistic

---

app/constants.py
app/delivery/send_to_providers.py
tests/app/delivery/test_send_to_providers.py

We were reducing priority for a single 5xx error, which meant that a very low percentage of errors when sending SMS could result in a large drop in traffic to a provider which then takes hours to be restored to the resting points.
This reuses the function we have for rate limiting to check for a number of events over an interval. In this case, we check for 50 errors over 60 seconds and only reduce the priority if this rate is exceeded. There are no changes to how we handle provider priority if SMS delivery is slow.

Only reduce SMS provider priority for 50 errors in a minute

---

app/schema_validation/service_join_request.py
app/service/rest.py
tests/app/service/test_rest.py

- Include folder permissions update during service join request flow
- We do this in the current invite-user journey, we just need to make sure the same is done for the service request journey
[Let folder permissions be selected when approving a service join request](https://trello.com/c/70y7hQOW/1021-let-folder-permissions-be-selected-when-approving-a-service-join-request)

feat: Add folder permissions for service join update

---

app/models.py
migrations/.current-alembic-head
migrations/versions/0474_ntfcn_hist_xstats_dep.py
migrations/versions/0475_ntfcn_hist_xstats_mcv.py
tests/app/test_model.py

The same statistics as recently added for `Notification`, though they will likely be less effective what with the statistics being diluted over a longer period.

`NotificationHistory`: add dependency & most-common-value extended statistics

---

.pre-commit-config.yaml
pyproject.toml
requirements.in
requirements.txt
requirements_for_test.txt
requirements_for_test_common.in

* Allow leading empty columns in CSV files
* Change second argument of `formatters.strip_all_whitespace` (this argument is not used in other apps)
* Use github API rather than fetching from their CDN in version_tools
* Change version_tools to a package that uses importlib to grab common reqs/config, rather than fetching common files from github. This repo's usage of those common files are now symlinks to the sources of truth found within notification_utils/version_tools/
* Raise an exception if we cant fetch remote github files in version_tools.py
***
Complete changes: https://github.com/alphagov/notifications-utils/compare/89.0.0...90.0.0

Bump utils to 90.0.0

---

app/constants.py
app/models.py
migrations/.current-alembic-head
migrations/versions/0476_notifications_failed_idx.py

Notifications with failed status are comparatively rare and tend to sit in cold regions of the table. Added to them being composed of several different individual status types (which, searched for together, rules out a lot of standard index operations), postgres finds it hard to query these efficiently.
This is a partial index only covering `NOTIFICATION_STATUS_TYPES_FAILED` (which conveniently at time of writing is the same set of status types requested together by admin), so it should be a small index that should allow such a query to completely disregard the `notification_status` clause and start reading out the results in `created_at` order with very little more filtering.
This is aimed at speeding up pages such as `/services/.../notifications/email?status=failed` which can be very …

`Notification`: add `ix_notifications_failed_service_id_composite`

---

app/models.py
migrations/.current-alembic-head
migrations/versions/0477_create_sjr_contacted_users.py

- Created a new table service_join_request_contacted_users.
- Copied data from soon to be deprecated contacted_users to newly created table (PR that [follows this one](https://github.com/alphagov/notifications-api/pull/4270))
- Refactored ServiceJoinRequest model to reference new table.
- downgrade [script passes](https://github.com/alphagov/notifications-api/blob/fe6f9bf14e97261344ba21fc2b207ff8b105a657/scripts/test_sql_migration_downgrade.sh) with success
https://trello.com/c/kgwSzxw2/1051-rename-contactedserviceusers-table

Refactor: create table service_join_request_contacted_users

---

app/celery/tasks.py
tests/app/celery/test_ftp_update_tasks.py

Instead of reverse-constructing the bucket name from the `NOTIFY_EMAIL_DOMAIN`, which is a technique that fails as soon as e.g. we have to deviate from this naming scheme due to bucket length limitations.

parse_dvla_file: use `S3_BUCKET_DVLA_RESPONSE` to determine bucket

---

app/config.py
tests/app/celery/test_ftp_update_tasks.py
tests/app/celery/test_letters_pdf_tasks.py
tests/app/celery/test_nightly_tasks.py
tests/app/celery/test_process_ses_receipts_tasks.py
tests/app/celery/test_reporting_tasks.py
tests/app/celery/test_research_mode_tasks.py
tests/app/celery/test_scheduled_tasks.py
tests/app/celery/test_tasks.py
tests/app/conftest.py
tests/app/job/test_rest.py
tests/app/letters/test_returned_letters.py
tests/app/notifications/test_notifications_letter_callbacks.py
tests/app/notifications/test_notifications_ses_callback.py
tests/app/notifications/test_notifications_sms_callbacks.py
tests/app/v2/notifications/test_notification_schemas.py
tests/conftest.py

I was getting frustrated that we had some unit tests that were saying
```
@celery.task
def some_task(arg1, arg2):
pass
def foo():
some_task.apply_async(args=[1, 2, 3], queue='some-queue-name')
def test_foo(mocker)
mock_task = mocker.patch('some_task.apply_async')
mock_task.assert_called_with(args=[1, 2, 3], queue=ANY)
```
There's a bug here - This code'll never work as `some_task` has two arguments but we're trying to call it with three args!
So, I wrote a `mock_celery_task` fixture that does some clever bits. It will:
* make sure your args and kwargs match up with the underlying task definition
* make sure your arguments are json serializable (so that they could be sent to SQS)
* make sure your args and kwargs match the type hints in the task definition (if there are any)
----
This isn't …

Create new celery mock and fix some tests

---

.pre-commit-config.yaml
app/dao/notifications_dao.py
app/inbound_sms/rest.py
app/models.py
app/notifications/process_notifications.py
app/notifications/receive_notifications.py
app/notifications/validators.py
app/schemas.py
app/user/rest.py
app/utils.py
app/v2/notifications/post_notifications.py
pyproject.toml
requirements.in
requirements.txt
requirements_for_test.txt
requirements_for_test_common.in
tests/app/delivery/test_send_to_providers.py
tests/app/notifications/test_process_notification.py
tests/app/service/send_notification/test_send_one_off_notification.py
tests/app/service/test_service_guest_list.py
tests/app/test_schemas.py
tests/app/user/test_rest.py

Reverts the revert of `remove-old-phonenumber-validation` branch and adds a fix for tv numbers that was causing functional tests to fail, OFCOM TV numbers are now considered as non-international UK numbers by `notifications_utils.recipient_validation.phone_number.PhoneNumber`

Tv number international info fix

---

migrations/.current-alembic-head
migrations/versions/0478_drop_contacted_users.py

- Drop deprecated contacted_users table
- This is part of a table renaming process. At a [previous PR](https://github.com/alphagov/notifications-api/pull/4265) we created a table called service_join_request_contacted_users and copied the data from contacted_users there.
- Now, we are simply deleting the depracted table
Note: The following error comes from lint
```
/tmp/upgrade.sql:2:2: warning: ban-drop-table
```
As explained, at this point the data from the table has been copied over and it's no longer in use.
**Data was copied successfully from contact_users to service_join_request_contacted_users, which means we can deprecate the table**
**Also, after making a request, the request is being saved on the new table**
https://trello.com/c/kgwSzxw2/1051-rename-contactedserviceusers-table

chore: remove deprecated contacted_users table

---

app/celery/scheduled_tasks.py
app/config.py
app/dao/notifications_dao.py
tests/app/celery/test_scheduled_tasks.py

previously, we were just selecting all letters more than 10 mins old with status pending_virus_check. However, this involves checking statuses all the way back through time - given this task runs every ten minutes, we don't need to check the status of letters created a day ago as they'll already have been fixed for example.
For now, just start with 30 minutes as the maximum time, in case the scheduled task doesn't run for any reason.
If it doesn't run multiple times in a row, then we'd need to run the task manually with a longer margin at least once - so I've made it an optional parameter so we can manually trigger the task

skip old letters in still_pending_virus_check task

---

app/models.py
migrations/.current-alembic-head
migrations/versions/0480_ntfcns_cpst_idx_nostatus.py

Create this index alongside `ix_notifications_service_id_composite` to see which gets more extended use over time, then we can consider which to keep.
Most notifications queries are for more than one status type, which means the existing index almost never uses its ability to scan in `created_at` order.

Notification: add `ix_notifications_service_id_ntype_created_at`

---

app/functional_tests_fixtures/__init__.py

[Trello card](https://trello.com/c/D1m5uleD/952-run-api-client-integration-tests-as-part-of-new-pipeline)
We're working to update the API client integration tests to use the same set of fixtures as the functional tests, so that they can be run in every environment (instead of being tied specifically to preview), without needing to manually "clickops" the required services and templates into each environment.
This will be useful when testing changes in a dev environment, and will also be necessary before we can achieve our goal of retiring the preview environment.
This PR adds the necessary additional fixtures to get the API clients working. It'll be followed up by PRs in each of the API client repos to make the necessary adjustments to have them use these new fixtures.

Add fixtures for API client integration tests to functional test fixtures

---

app/history_meta.py

When we cleaned up this function in 7ea5474a96dd7ef3b3c6dfa17d7ef08b9ad51a85 we made it a lot simpler.
It now passes the cyclomatic complexity check, so we don’t need a comment to exclude it from that check.

Remove unneeded `noqa` comment

---

app/celery/tasks.py
tests/app/celery/test_tasks.py

First part of #4284 to ensure a smooth deployment of the second half.
Doesn't introduce anything that actually _uses_ `shatter_job_rows` yet

job tasks: introduce `shatter_job_rows`

---

app/config.py
tests/app/celery/test_nightly_tasks.py

DVLA send us files starting ~4:30pm, and it often takes over an hour to send them completely, resulting in us sending DVLA an email while files are still in flight.
we can just run the check later in the day, thus avoiding sending premature warning emails to DVLA.
we won't do anything ourselves until the next morning so for us it doesn't make much difference

move check-letters-in-sending task from 5pm to 7pm

---

app/dao/unsubscribe_request_dao.py
app/one_click_unsubscribe/rest.py
tests/app/dao/test_unsubscribe_request_dao.py
tests/app/db.py
tests/app/one_click_unsubscribe/test_one_click_unsubscribe.py

Currently duplicate requests can be made using the same unsubscribe link, hence there are occurrences of multiple instances of unsubscribe requests with the same `notification_id` in the `unsubscribe_request` table.
The changes proposed in this PR would prevent duplicate unsubscribe requests from being entered into the `unsubscribe_request` and being added to an unsubscribe request report, as described in this [card](https://trello.com/c/2rwsxzZd/165-duplication-of-one-click-unsubscribe-links-issue)
For the purpose of the work, a duplicate unsubscribe request is being defined as an unsubscribe_request that has
the same notification_id of a previously received unsubscribe request that has not yet been processed by the service that initiated the notification.

Handling duplicate unsubscribe requests

---

app/dao/unsubscribe_request_dao.py
app/one_click_unsubscribe/rest.py
tests/app/db.py
tests/app/one_click_unsubscribe/test_one_click_unsubscribe.py

Reverts alphagov/notifications-api#4298
The `test_unsubscribe_request_flow` needs to be updated first

Revert "Handling duplicate unsubscribe requests"

---

app/functional_tests_fixtures/__init__.py

Functional tests for join-a-live-service failing because of the can_ask_to_join_a_service flag is not enabled initially and domain does not exist. Update the org fixture to create org with required flag and domain.

Fix join-live-service functional tests

---

migrations/versions/0481_receipt_service_live_req.py

Skip receipt email template for service-live-request if already exists.

Skip template insert if already exists

---

app/dao/notifications_dao.py
app/template_statistics/rest.py
tests/app/dao/notification_dao/test_notification_dao_template_usage.py

Beyond last midnight we should have a record of any notifications in `ft_notification_status`, which should be faster to search (if it isn't, we can address that easily). As long as we ensure we can search notifications in `created_at` order (hence targeting it at a specific index), we can avoid scanning old, cache-cold rows.
Taking the template instance as an argument allows us to extract all the field values we need to fill out these queries while maintaining a convenient calling interface.

`dao_get_last_date_template_was_used`: restrict `notifications` table search to midnight

---

app/celery/research_mode_tasks.py
tests/app/celery/test_research_mode_tasks.py
tests/app/v2/notifications/test_post_letter_notifications.py

We want to mark a letter as being delivered if it's sent using a test key and the `SEND_LETTERS_ENABLED` flag is False. This was being done by putting a fake response file in S3, but now that we are removing the code related to response files we can no longer use this method. This adds a task to create a fake callback instead.
In later PRs, we will then start using the new task and delete the code related to response files.

Add new task for generating fake letter responses

---

app/models.py
migrations/.current-alembic-head
migrations/versions/0482_ft_ntfcn_stat_tpt_date_idx.py

Aimed at improving search time of `dao_get_last_date_template_was_used`. See also https://github.com/alphagov/notifications-api/pull/4300

`FactNotificationStatus`: add index on `template_id`, `bst_date`

---

app/celery/research_mode_tasks.py
app/v2/notifications/post_notifications.py
tests/app/celery/test_research_mode_tasks.py
tests/app/v2/notifications/test_post_letter_notifications.py

The `create-fake-letter-callback` task was [previously added to the code](https://github.com/alphagov/notifications-api/pull/4303), this change starts using it to generate fake letter responses.
The exception it catches has been changed from to `HTTPError`, since `Exception` was not specific enough.

Start using new task to generate fake letter callbacks

---

app/dao/jobs_dao.py
app/job/rest.py
app/upload/rest.py
tests/app/dao/test_jobs_dao.py

This is called repeatedly by `get_uploads_by_service`.
Filtering by `service_id` makes postgres use two indexes rather than one, resulting in a more complex query that touches more data.
(incidentally, it does this because multi-column statistics have limitations with nullable columns - otherwise I'd hope postgres' extended statistics for the notifications table would see that a simple filter in an index scan would probably remove 0 rows)
The added safety of filtering these results by service is a nice-to-have but I'd argue here we're only returning aggregated counts, not including any sensitive data, which hugely limits the worst-case-scenario.
It's hard to get exact performance figures for queries like this that "warm up" very quickly, but an `EXPLAIN (ANALYZE, BUFFERS) ...` showed that …

`dao_get_notification_outcomes_for_job`: omit redundant `service_id` condition

---

app/models.py
migrations/.current-alembic-head
migrations/versions/0483_rm_ntfcn_service_composite.py

The vast majority of uses of this index have been taken over by `ix_notifications_service_id_ntype_created_at` - let's see if we can do without it.

`Notification`: remove `ix_notifications_service_id_composite` index

---

app/celery/scheduled_tasks.py
app/dao/provider_details_dao.py
tests/app/celery/test_scheduled_tasks.py
tests/app/dao/test_provider_details_dao.py

Instead of every 10 minutes - this way we react faster, and fewer text messages get delayed.
This becomes more important as we now send lots of login codes for various organisations.
Also rebalance back to the middle every 15 minutes, instead of every 1 hour.
Those two changes together make our providers balancing act more dynamic - hopefully it will help us deliver messages quickly when one of the providers has delivery issues, while also giving them traffic back more quickly when they recover.
Check commit messages for more detail.

Change provider balance on slow delivery every 5 minutes

---

app/models.py
tests/app/dao/test_services_dao.py
tests/app/delivery/test_send_to_providers.py
tests/app/service/test_rest.py

For new services, text messages now won't start with the service name by default. The setting to start text messages with the service name can still be toggled on or off on the settings page.
https://trello.com/c/gSnH4310/1093-switch-off-start-text-messages-with-service-name-by-default

Stop SMS from starting with the service name by default

---

scripts/test_sql_migration_downgrade.sh

`flask db heads` was failing on concourse becasue it couldn't find the FLASK_APP environment variable
Turns out, `$(<command>)` executes its contents inside a subshell
subshells are passed in any variables that were defined with `export`.
if the variable was just defined FOO=bar, then subshells won't receive that variable, UNLESS it's a simple bash function like `$(echo $FOO)`
this means that those FLASK_APP and NOTIFY_ENVIRONMENT will be set in whatever shell you call ./scripts/test_sql_migration_downgrade.sh from, but that's just a sacrifice we have to make to ensure that the script works

export flask env vars to ensure subshells pick them up

---

scripts/test_sql_migration_downgrade.sh

psql by default connects to a socket /var/run/postgresql/.s.PGSQL.5432 This checks the auth of the linux user running psql (in our docker images, root) and tries to find a matching user in the database. We only have a postgres database user however, so this fails in docker.
If we pass psql a URI that includes a username and password, it'll use those to connect instead, allowing us to succeed

always provide URI for psql

---

migrations/versions/0438_request_invite_templates.py
migrations/versions/0467_svc_join_approved_tmp.py

The contents for join a service templates have been updated in prodution and current versions of dev are out dated. Update the migration files so dev templates are updated when creating new environment.

Update join a service templates

---

app/clients/email/aws_ses.py
tests/app/celery/test_provider_tasks.py
tests/app/clients/test_aws_ses.py

the class is actually TooManyRequestsException, and we don't need to check for the message content
lil thing i noticed when we hit these errors the other day

fix SES rate limit exception handling

---

app/commands.py
app/dao/services_dao.py
app/dao/users_dao.py
tests/app/dao/test_services_dao.py
tests/app/dao/test_users_dao.py

i've tested this locally (and you can to!)
```sh
SQLALCHEMY_DATABASE_URI="postgresql://notify:notify@localhost:5433/notification_api" flask command functional-test-fixtures
psql postgresql://notify:notify@localhost:5433/notification_api -c "select id from services where id != 'd6aa2c68-a2d9-4437-ab19-3ae8eb202553'"
SQLALCHEMY_DATABASE_URI="postgresql://notify:notify@localhost:5433/notification_api" flask command delete-functional-test-service --service-id <id from prev thing>
```
this is idempotentish - in that you can then create fixtures successfully again, and then tear them down successfully.
my ambition is to run this on preview 💣 🚮

Purge seeded user for functional tests

---

app/models.py
migrations/.current-alembic-head
migrations/versions/0484_rm_daily_sorted_letter.py

We stopped writing to this table when we started receiving letter delivery status via HTTPS callback instead of via response files in S3. However, since 2023 we've been using the `ft_billing_letter_despatch` table for letter billing and to store more detailed information about which letters were classed as `sorted` vs `unsorted` so this data is not needed.

Drop `daily_sorted_letter` table

---

app/dao/unsubscribe_request_dao.py
app/one_click_unsubscribe/rest.py
tests/app/db.py
tests/app/one_click_unsubscribe/test_one_click_unsubscribe.py

This PR prevents duplicate unsubscribe requests.
A previously mereged [PR](https://github.com/alphagov/notifications-api/pull/4298) was reverted because functional tests had to be updated first.
Reverts alphagov/notifications-api#4299

Prevent duplicate unsubscribe requests

---

.pre-commit-config.yaml
pyproject.toml
requirements.in
requirements.txt
requirements_for_test.txt
requirements_for_test_common.in

* Downgrade minimum version of `requests` to 2.32.3
* Bumps core dependencies to latest versions
* Restores old validation code so later utils changes can be added to api, admin etc.
* Adds rule N804 (invalid-first-argument-name-for-class-method) to linter config
* Remove hangul filler character from rendered emails
* bump all libs in requirements_for_test_common.in
* Don’t copy config when bumping utils version
* Fix validating supported international country codes for phone numbers without a leading "+" that look a bit like UK numbers
* Bumps requests to newer version
* Adds public utility method to check if a phonenumber is international (with correct handling for OFCOM TV numbers)
* Updates PhoneNumber.get_international_phone_info to return the correct info for OFCOM TV numbers
* …

Bump utils to 92.0.2

---

requirements.in
requirements.txt
requirements_for_test.txt

We don’t use this directly in our application code.
Looks like it’s only a subdependency of our test code (via `cryptography` and then `moto`).
We can remove the line which specifies it and let pip’s dependency resolution handle which versions we need and where.
***
We pinned this in 2017 because a later version failed to build:  https://github.com/alphagov/notifications-api/commit/c362bd06b0e6c111a523af0f339471dbf91474f2
In 2018 a newer version fixed this failure but we never removed the pin: https://github.com/alphagov/notifications-api/pull/1718/commits/a29f4ed117dc7fc19eaee58abf22cfc06b00af4f

Remove cffi from production dependencies

---

requirements.in
requirements.txt
requirements_for_test.txt
tests/app/service/test_rest.py
tests/app/template_folder/test_template_folder_rest.py
tests/app/webauthn/test_rest.py

SQLAlchemy and it’s related dependencies have more breaking and interdependent changes which will take time to unpick.
These changes are straightforward and don’t seem to break things.
There are some changes to error messages from JSONSchema but these are ok because:
- they’re only on our internal APIs
- the admin app doesn’t seem to be parsing the content of these error messages: https://github.com/search?q=repo%3Aalphagov%2Fnotifications-admin%20%22is%20too%20short%22&type=code

Bump non-SQLAlchemy dependencies to latest versions

---

requirements.in
requirements.txt
requirements_for_test.txt
tests/conftest.py

3.1 and higher require SQLAlchemy 2.x which we don’t want to upgrade to yet: https://flask-sqlalchemy.readthedocs.io/en/stable/changes/#version-3-1-0
3.0.3 introduced a check to make sure an app can’t have multiple SQLAlchemy instances bound to it: https://github.com/pallets-eco/flask-sqlalchemy/pull/1151
We were falling foul of this check, so let’s make sure we have an entirely fresh instance of SQLAlchemy for each test.
This doesn’t seem to have a performance implication on how long the tests take to run.

Bump Flask-SQLAlchemy to highest version that supports SQLAlchemy 1.x

---

app/functional_tests_fixtures/__init__.py
tests/app/functional_test_fixtures/test_functional_test_fixtures.py

https://trello.com/c/8kQqSeHv/974-enable-the-functional-tests-smoke-tests-provider-tests-in-the-new-deploy-pipeline-on-staging-and-make-sure-they-pass
With these extra env vars set, using https://github.com/alphagov/notifications-functional-tests/pull/555 with `FUNCTIONAL_TESTS_ENABLE_EDIT_REPLY_TO` explicitly set, this allows `test_can_add_and_update_reply_to` to _actually_ pass on dev (and presumably other) environments (rather than just saying it passed having just omitted the body of the test): https://concourse.notify.tools/teams/dev-a/pipelines/deploy-notify/jobs/test/builds/217#L677f545d:54
See also https://concourse.notify.tools/teams/dev-a/pipelines/deploy-notify/jobs/test/builds/215#L677f4457:48, the result of doing the above without this change.
Simply appending `+2` etc. to …

functional test fixtures: include multiple addresses for reply-to email testing

---

docker/Dockerfile
requirements_for_test.in
requirements_for_test.txt

The change is part of the removing nvm as part of ITHC report. More details on [this card](https://trello.com/c/jFpYYlGh/1087-remove-nvm-from-docker-images-verify-shell-script-before-executing). We use node only for `squawk-cli` so removing the installation via npm and installing via pip/uv.
squawk-migration-check has been successful with this change.

Remove nvm

---

app/authentication/auth.py

This means the log should be annotated with the `service_id`, which is useful.
Ideally we'd be using a logging system where "request-global" parameters like this could be easily queried, but we're not (yet), so this tweak should make life a little easier in the meantime.

auth: move "API authorised.." log message to after assigning `service_id`

---

.pre-commit-config.yaml
app/config.py
pyproject.toml
requirements.in
requirements.txt
requirements_for_test.txt
requirements_for_test_common.in

Depends on https://github.com/alphagov/notifications-utils/pull/1185
It would appear `NOTIFY_LOG_LEVEL` was previously not controllable via env vars.

config: read `NOTIFY_LOG_LEVEL` and `NOTIFY_LOG_LEVEL_HANDLERS` env vars

---

migrations/.current-alembic-head
migrations/versions/0486_letter_rates_feb_2025.py

International letter rates are changing on 6 February 2025, so this adds a migration to update them.
See https://trello.com/c/qZb1RQL8/1123-update-the-prices-in-the-notify-database-royal-mail-price-increase for details of the date and price changes to double check

Add new international letter rates for 6 Feb 2025 onwards

---

gunicorn_config.py
requirements.in
requirements.txt
requirements_for_test.txt

https://trello.com/c/M4vBaTPb/971-instrument-eventlet-to-get-to-the-bottom-of-0900-glitches
This is ugly and nasty and should be removed as soon as we've finished using it. we have to perform our own request timing because we can't reasonably access the flask-level annotations from the gunicorn side.
Performing this from gunicorn has the advantage of being executed *after* a response is sent, and so the 100ms delay this causes (or unexpected errors this results in for that matter) shouldn't prevent a user from getting their response.

gunicorn: use `psutil` to emit post-request log output for long requests

---

entrypoint.sh
gunicorn_config.py

https://trello.com/c/M4vBaTPb/971-instrument-eventlet-to-get-to-the-bottom-of-0900-glitches
This is something that contributes to the error splurge we get every time our applications start - fixing this rules out the possibility of the early-import-of-unpatched-io-routines being related to our issues.
(I have also explicitly tested killing a worker process unexpectedly, hence discovering we need to set `PROMETHEUS_MULTIPROC_DIR` more aggressively)

gunicorn: use local copy of `child_exit` instead of importing from `gds_metrics`

---

.pre-commit-config.yaml
pyproject.toml
requirements.in
requirements.txt
requirements_for_test.txt
requirements_for_test_common.in

* Replaces symlink at `./pyproject.toml` with a duplicate file
***
Complete changes: https://github.com/alphagov/notifications-utils/compare/93.2.0...93.2.1

Bump utils to 93.2.1

---

gunicorn_config.py

A low value for this setting, this is to limit the effect of runaway greenthread creation when we're doing expensive per-thread lazy resource initialization (think api clients..)
Ideally we'd have some mechanism for throttling greenthread creation instead, but in normal circumstances use we don't get anywhere near 8 simultaneous connections per worker pid.

gunicorn: set `worker_connections` to 8

---

gunicorn_config.py

We may need this amount of concurrency for the functional tests to pass in preview.
Which itself is mildly concerning.

gunicorn: set `worker_connections` to 16

---

gunicorn_config.py

Due to functional tests' extreme concurrency.

gunicorn: set `worker_connections` to 32

---

gunicorn_config.py

I have a better theory now as to why we "need" so many connections and think we should go back to the original value until we have thought this out a bit more.

gunicorn: revert `worker_connections` to original 256

---

gunicorn_config.py

This is intended to be a temporary measure to show whether an issue is keepalive-related or not.

gunicorn: disable keepalive

---

gunicorn_config.py

Before I get out the sharp knife of profiling production, let's try one more possibility. A double un-reversion here :)

gunicorn: re-disable keepalive with `worker_connections` set to 8

---

app/constants.py
app/dao/service_callback_api_dao.py
app/schemas.py
app/service/callback_rest.py
tests/app/dao/test_service_callback_api_dao.py
tests/app/db.py
tests/app/notifications/test_notifications_ses_callback.py
tests/app/platform_admin/test_rest.py
tests/app/service/test_callback_rest.py
tests/app/test_schemas.py
tests/app/v2/inbound_sms/test_get_inbound_sms.py

This PR makes service callback rest methods generic as described in [this](https://trello.com/c/bNai6vrs/213-make-servicecallback-methods-generic) ticket.
Currently those methods deal specifically with delivery-receipts. This lays a foundation for the work to add a returned letter callback  feature.
A `ServiceCallbackTypes` enum has also been added.

Make service callback methods generic

---

app/billing/rest.py
app/dao/annual_billing_dao.py
app/service/rest.py
tests/app/billing/test_rest.py
tests/app/dao/test_annual_billing_dao.py
tests/app/service/test_rest.py

Best reviewed commit by commit.
This tidies up the code around updating the free SMS fragment limit to remove the ability to update future years, which isn't something we currently do or plan to do. There's a corresponding admin change here https://github.com/alphagov/notifications-admin/pull/5365
It also removes unused code relating to the `service_domain` argument when creating a service

Remove unused code relating to SMS free allowance and service_domain

---

app/constants.py
app/letters/rest.py
app/service/callback_rest.py
app/service/rest.py
migrations/.current-alembic-head
migrations/versions/0847_returned_letter_callback.py
tests/app/service/test_callback_rest.py

This PR adds the necessary endpoints for the returned letter callback feature as described in [this](https://trello.com/c/6qK45O5W/182-when-new-returned-letters-added-to-the-database-send-callbacks-to-services-that-have-callbacks-set-up-for-returned-letters) card.
It also implements the migration to add a `returned_letter` callback_type to the `service_callback_type` table.
The celery tasks will be addressed in another PR.

Add endpoints for returned letter callback

---

migrations/.current-alembic-head
migrations/versions/0487_returned_letter_callback.py

This fixes the typo in the name of the migration script and keeps it consistent with current naming convention

Rename 0847_returned_letter_callback to 0487_returned_letter_callback

---

app/commands.py
app/dao/organisation_user_permissions_dao.py
app/dao/services_dao.py
app/dao/users_dao.py

There are lots of test data in preview environment. This PR is for the removing the test data ([card](https://trello.com/c/bH9JnDjZ/1117-clear-functional-test-data-in-preview)) and re-creating the some of the fixture data.
Steps to removing the test data in preview environment: 
1. Merge this PR
2. Take the snapshot of notify-db in rds and also take database dump locally
3. ssh into ecs `api-web` service
4. Run `flask command purge-functional-test-data -u notify-tests-preview` to delete user data objects.
* note: takes a while! multiple hours!
> Additional steps for Preview:
a. Remove https://www.notify.works/organisations/63b9557c-22ea-42ac-bcba-edaa50e3ae51/settings/ and https://www.notify.works/organisations/9b37efda-5855-4b18-bc37-6752f95994cb/settings/ Orgs
6. Run `flask command …

remove functional test data

---

docker/Dockerfile

As suggested in https://github.com/astral-sh/uv/issues/11214#issuecomment-2633899802
Without this we’re making an assumption about the venv existing (that we know because we just created it) that uv doesn’t know.
This is one of the recommended ways to install uv in their documentation: https://docs.astral.sh/uv/guides/integration/docker/#installing-uv
It means we don’t need to specify the version number 3 times.
We can safely do this because:
- we added the location of the venv to an environment variable in this commit’s grandparent
- the regression in 0.5.27 was fixed in 0.5.28 via https://github.com/astral-sh/uv/pull/11218

Install uv using `COPY` and bump to latest version

---

app/config.py
entrypoint.sh
tests/app/test_config.py

This adds the settings for a new worker, `api-worker-report-requests-notifications`, and a queue that it will pull messages from `report-requests-notifications-tasks`.
These will be used for the tasks of generating large notification reports.

Add settings for new queue and worker

---

app/schemas.py
tests/app/test_schemas.py

service_callback_api now also includes returned_letter callback type, so this field is no longer a list of ids filtered on the delivery_status callback type.
The choice of representing the data in dicts, with callback_id and callback_type as keys, is to aid filtering in the front end as to what type of callback is being considered ie
delivery_status or returned_letter.
Needs to wait until this PR is deployed: https://github.com/alphagov/notifications-admin/pull/5382

Update service_callback_api field in ServiceSchema

---

app/billing/rest.py
app/constants.py
app/dao/annual_billing_dao.py
app/dao/fact_billing_dao.py
app/models.py
migrations/.current-alembic-head
migrations/versions/0488_add_annual_billing_columns.py
migrations/versions/0489_populate_new_billing_cols.py
tests/app/billing/test_rest.py
tests/app/dao/test_annual_billing_dao.py
tests/app/dao/test_fact_billing_dao.py
tests/app/db.py

See individual commits for details.
Our current code to set the free allowance for a service either gives the service the default its organisation type or keeps the free allowance as zero if it was zero for previous years. This has a couple of issues:
- services with a different custom allowance didn't have this persisted to future years
- services which a free allowance of 0 due to being a high volume sender never had this reset if they stopped sending so many messages
Two extra columns have been added to the annual billing table, `high_volume_service_last_year` and `has_custom_allowance`. These let us automatically set the free allowance to 0 for high volume senders and to persist custom free allowances.

Automate setting the free allowance for high volume services

---

app/dao/date_util.py
app/dao/users_dao.py
app/models.py
app/platform_admin/platform_admin_schemas.py
app/platform_admin/rest.py
app/utils.py
tests/app/dao/test_date_utils.py
tests/app/dao/test_users_dao.py
tests/app/platform_admin/test_rest.py
tests/app/test_model.py

This PR introduces a new API endpoint (`/users-list`) for platform admins to fetch a filtered list of users based on various criteria. The filtered data is used to generate a CSV export.
Users can be filtered by:
- Creation date (created_start, created_end)
- Last login date (logged_in_start, logged_in_end)
- Research opt-in status (take_part_in_research)
- User state (defaults to "active")
[Add getting list  users and emails for yearly survey to platform admin](https://trello.com/c/qeSQJ5XB/1138-add-getting-list-users-and-emails-for-yearly-survey-to-platform-admin)

feat: Create Users List Endpoint for Platform Admins

---

app/celery/letters_pdf_tasks.py
tests/app/celery/test_letters_pdf_tasks.py

When delivering letters to DVLA we are bottlenecked by the speed at which we can create SQS messages. This is a problem because we have one task which delivers all the letters, and it creates one SQS message at a time. This task runs for a long time, and we can’t deploy while it’s running.
This change makes it so that one new task (and SQS message) is created for each 100 letters. Each of these new tasks – which can be picked up asynchronously – then create individual tasks for each of its 100 letters.
The overall time taken will probably be about the same, but the maximum time taken by any one task should be greatly reduced.
  | Number of  letters<sup>1</sup>  | Database time | Time talking to SQS | Total task time
-- | -- | -- | -- | -- 
**Before** | 166,936  | 11 seconds<sup>2</sup> | …

Shatter letter delivery tasks

---

app/dao/fact_billing_dao.py
app/dao/organisation_dao.py
tests/app/dao/test_fact_billing_dao.py
tests/app/dao/test_organisation_dao.py
tests/app/organisation/test_rest.py

Update the free allowance when updating organisation type. If the service free allowance has been updated manually then it should keep the manual allowance, this requirement should be handled as part of [this story](https://trello.com/c/i67GtAIi/1113-figure-out-how-to-automatically-handle-high-volume-service-free-allowances). More details on [this card](https://trello.com/c/31ksdlS9/1147-if-you-update-organisation-type-it-doesnt-update-services-free-allowances-for-that-org).
This PR needs to be merged after https://github.com/alphagov/notifications-api/pull/4375

Update service free allowance when organisation type change

---

app/user/rest.py

This todo is no longer accurate and misrepresents that we have a ‘security hole’.
The admin app has taken care of authorizing which users can change permissions since https://github.com/alphagov/notifications-admin/commit/9e710711cb9c9da723c8cb8d540592cb57d1754c
The `TODO:` was added 2 days previously in the _Functionality added and all tests working_ commit:
https://github.com/alphagov/notifications-api/commit/918d40cc9da7ff819ca399ee173f21a725501883#diff-856770ce1eee6ec9509abce6fde06d0f795d88514f04c6ab6518697a9e3bcc08R203-R204

Remove outdated todo

---

app/user/rest.py
migrations/versions/0461_user_research_email.py
tests/app/conftest.py
tests/app/test_utils.py

**Update URL used to generate an email when a user's email changes**
We send users an email to confirm if they change their email address. This updates the link in this email to the new URL of `/your-account/email/confirm`.
**Update URL in migration that creates new user research email**
This updates the content to contain the new URL. This will only apply to dev environments where the migrations get run from scratch (we'll need to manually make the change in other environments). We don't actually send the email in dev environments, but updating the template keeps things consistent.
---
**Merge after**

Update the "user-profile" URLs to the new version, "your-account"

---

app/clients/document_download.py
app/v2/errors.py
app/v2/notifications/post_notifications.py
tests/app/clients/test_document_download.py
tests/app/v2/test_errors.py

add a test for it too
this means we don't throw a 500 internal server error. rather than returning 413, it feels a bit simpler for users who aren't using our rest clients to just get a 400 the same as they would for other issues with the file relevant message to display

Doc dl bug

---

app/celery/tasks.py

This will probably be needed until we can get dynamic shatter batch size working, though throughput for many-rows jobs will probably suffer in the meantime.

jobs: set `DEFAULT_SHATTER_JOB_ROWS_BATCH_SIZE` to 8

---

app/celery/tasks.py
tests/app/celery/test_tasks.py

See https://trello.com/c/umdHKBfA/1053-dynamic-shatter-job-rows-batch-size
This introduces a wrapper function, `_shatter_job_rows_with_subdivision` which will catch an exception caused by an oversized SQS message and split the batch in half before trying again, recursing if it too throws the same error.
Uses this in both `process_job` and `process_incomplete_jobs`. In the latter case, catch the exception raised when a batch can't be subdivided any further, log an exception and continue with the next incomplete job. this is unusual in that it's the only exception we treat like this - perhaps we should be catching more exceptions like this and proceeding with the next job(s) to avoid a single bad job stopping all incomplete jobs being re-processed, but in this specific case it became clear …

shatter_job_rows: recursively subdivide batches if SQS message too big

---

.pre-commit-config.yaml
gunicorn_config.py
requirements.in
requirements.txt
requirements_for_test.txt
requirements_for_test_common.in
ruff.toml

* Bump minimum jinja2 version to 3.1.6
* Fix external link redirect
* Fix QR code URL with '&' encoded as '&amp;'
* for bilingual letters preview, only show barcodes on the first page (patch).
* rename `include_notify_tag` argument to `includes_first_page` (major).
* BREAKING CHANGE: the `gunicorn_defaults` module has been moved to `gunicorn.defaults` to make space for gunicorn-related utils that don't have the restricted-import constraints of the gunicorn defaults. Imports of `notifications_utils.gunicorn_defaults` should be changed to `notifications_utils.gunicorn.defaults`.
* Added `ContextRecyclingEventletWorker` custom gunicorn worker class.
* Implement `InsensitiveSet.__contains__`
* Fix to the number of arguments the `on_retry` of the `NotifyTask` class takes.
* Add `RUF100` rule …

Bump notify-utils to 97.0.3

---

migrations/.current-alembic-head
migrations/versions/0491_letter_rates_april_2025.py

First and second class letter rates are increasing from 1st April 2025, so this adds the new rates to the database.
[Trello card](https://trello.com/c/Mk5arZ2z/1232-letter-price-changes)

Add new letter rates valid from April 2025

---

migrations/.current-alembic-head
migrations/versions/0492_sms_rate_april_2025.py

The base SMS rate is changing from 1 April 2025
[Trello card](https://trello.com/c/orF9qBDa/1231-sms-price-changes)

Add new SMS rate valid from 1 April 2025

---

app/service/callback_rest.py
app/service/service_callback_api_schema.py

This PR updates the create_service_callback_api_schema and `update_service_callback_api_schema` to accommodate 
`callback_type`.
This is lays the foundation for consolidating the service callback endpoints, where filtering will be done on `callback_type`.
`callback_type` is an attribute of the `service_callback_api table` its inclusion makes logical sense.

Update create service callback api schema

---

.pre-commit-config.yaml
requirements.in
requirements.txt
requirements_for_test.txt
requirements_for_test_common.in
ruff.toml

* Fix mailto: URLs in Markdown links
***
Complete changes: https://github.com/alphagov/notifications-utils/compare/97.0.4...97.0.5

Bump utils to 97.0.5

---

.pre-commit-config.yaml
requirements.in
requirements.txt
requirements_for_test.txt
requirements_for_test_common.in
ruff.toml
tests/app/notifications/test_process_notification.py

This brings in the international text message rate multipliers for 1 April 2025 onwards.

Major utils bump to 98.0.0

---

app/constants.py
app/service/callback_rest.py
tests/app/service/test_callback_rest.py

This PR updates the service callback helper methods to also support inbound sms callback api.
This helps to keep the code DRY and is also a first step towards potentially merging `inbound_sms_api` into `service_inbound_api`.
This PR is dependent on these 2 PRs being merged in first https://github.com/alphagov/notifications-api/pull/4405 and https://github.com/alphagov/notifications-admin/pull/5417.

Refactor api callback endpoints

---

app/models.py
migrations/.current-alembic-head
migrations/versions/0493_unique_org_permissions.py

At the moment, there's nothing to stop an organisation having lots of rows for the same permission in the database. While the frontend code shouldn't be adding duplicate rows let's make sure that scenario doesn't occur and give unexpected behaviour.
If creating the table from scratch this could have worked like the `service_permissions` table, with the `organisation_id` and `permission` columns forming a composite primary key. However, since the table exists it's a lot of effort to change it to that format.
There is only one type of organisation permission available, `can_ask_to_join_a_service`, and it's for a feature that has not launched, so making this change now is safe - the organisation_permission table only has a couple of rows of data.

Add unique constraint to OrganisationPermission model

---

app/constants.py
app/service/report_request_schema.py
app/service/rest.py
tests/app/service/test_rest.py

POST report-request endpoint deals with different types of reports. For now it would only handle the necessary logic for 'notifications_report'. More details on [this card](https://trello.com/c/sgeh0FH8/1183-post-endpoint-for-report-request).
At this stage we are not looking to implement the queue function (that’s part of a task) or a lock mechanism.

Add create report-request POST endpoint

---

app/models.py

The default value should be a function, but shouldn't _call_ the function. Fixing this means that the `created_at` column now has the datetime that the join request was created, not when the app started up.

Fix default value for `ServiceJoinRequest.created_at column`

---

app/schemas.py
tests/app/test_schemas.py
tests/app/user/test_rest.py

(to `False` only, for safety)
Supports https://github.com/alphagov/notifications-admin/pull/5427

Allow the admin app to update a user’s platorm admin flag

---

app/service/callback_rest.py

As of https://github.com/alphagov/notifications-admin/pull/5425 the admin app is no longer using these specific URLs. Instead it’s using the generic `/callback-api` one.
***
How this fits into the overall refactor:
***
See this document for more context: https://docs.google.com/document/d/1Oo8VbB3tdJMLPM6WslJlbbwANA33_lJcN3a6AKkCL7A/edit?tab=t.0

Remove old callback URLs

---

app/models.py
migrations/.current-alembic-head
migrations/versions/0494_add_intl_sms_limit_column.py
tests/app/service/test_rest.py

The column is non-nullable and defaults to 250k.
In separate PRs, we will:
- create an endpoint to update the new limit
- expose this endpoint to our users (in admin app)
- set the actual limits for services who have not updated it themselves, based on their historical international sms usage.
- check if the services are within the limit when they send international sms, and show them an error message if they are not.

Create international_sms_message_limit column for services table

---

app/schemas.py
tests/app/job/test_rest.py
tests/app/service/test_rest.py
tests/app/upload/test_rest.py

Otherwise the admin app won’t always be able to sort things in the correct order.
Looking at examples of `def serialize()` in `models.py` we seem to prefer the timestamp with the timezone. So let’s go with that.
The admin app uses the forgiving [`dateutil.parser`](https://dateutil.readthedocs.io/en/stable/parser.html) (via [`notifications_utils.utc_string_to_aware_gmt_datetime`](https://github.com/alphagov/notifications-utils/blob/e4b6f3f3ab8944f760987af3f3039dfeb2910ff2/notifications_utils/timezones.py#L9C5-L18)) to deserialize the strings it gets from the API back into `datetime` objects. So it doesn’t need the string to be in an exact format.

Serialize timestamps for admin app with subsecond precision

---

app/celery/service_callback_tasks.py
app/models.py
app/schemas.py
app/service/rest.py
app/upload/rest.py
app/utils.py
tests/app/celery/test_service_callback_tasks.py
tests/app/service/test_rest.py
tests/app/template/test_rest_history.py
tests/app/upload/test_rest.py

It’s confusing that we arbitrarily serialize datetimes for the admin app in 2 different formats.

Kill `DATETIME_FORMAT_NO_TIMEZONE`

---

app/dao/service_join_requests_dao.py
app/service/rest.py
app/service/service_join_request_schema.py
tests/app/dao/test_service_join_requests_dao.py
tests/app/service/test_rest.py

This moves code around and temporarily duplicates it so that we can rename the join a service URLs before the feature goes live. See individual commits for full details.
**The route to create a join request**
We had a 2 routes to create a join request
1. `/service/<uuid:service_id>/service-join-request` - this is the URL we want, but didn't contain much functionality
2. `/service/<service_id>/invite/request-for/<user_to_invite_id>` this contained the functionality, but we decided not to use this URL
This moves the functionality from 2. into 1.
**The routes to get and update a join request**
We decided we wanted to change the URLs from 
* `GET /service/service-join-request/<uuid:request_id>` to `GET /service/<service_id>/service-join-request/<uuid:request_id>`
* `POST …

Rename join a service routes

---

migrations/.current-alembic-head
migrations/versions/0495_update_inbound_callback.py
migrations/versions/0496_update_inbound_callback.py

This PR adds `inbound_sms` to the `service_callback_type` table.  This is in preparation for writing `inbound_sms` callback data to the `service_callback_api` table.

Add inbound_sms to service_callback_type table

---

app/dao/service_join_requests_dao.py
app/service/rest.py
app/service_invite/rest.py
tests/app/dao/test_service_join_requests_dao.py

- Extended service join requests to persist the `reason` field when we create the request
- Previously we persisted the data during the update of a request, but not during the creation. Now we do it for both.
- The field is by default None if no value is available.
[Join a service dev work](https://trello.com/c/ozzxcO3o/1221-join-a-service-dev-work)

feat: Persist  reason field on service join request creation

---

app/constants.py
migrations/.current-alembic-head
migrations/versions/0497_add_economy_letter_flag.py

We have added a service-level permission economy letter feature flag to make sure other teams do not accidentally use the economy rates or options while we are still developing the feature. [Card](https://trello.com/c/k2L5QcH2/1249-service-level-permission-for-economy-rates) for this PR.

Add economy letter feature flag

---

app/dao/organisation_dao.py
app/functional_tests_fixtures/__init__.py
tests/app/organisation/test_rest.py

This will become the default for all organisations, so when an organisation is created we now automatically give them the join a service organisation permission.

Give all new orgs the join a service permission

---

migrations/.current-alembic-head
migrations/versions/0498_join_a_service_for_all.py

https://github.com/alphagov/notifications-api/pull/4437 adds the "can_ask_to_join_a_service" to all new organisations that get created.
This PR now adds a migration to add the "can_ask_to_join_a_service" organisation permission to any organisation that doesn't already have it.
https://trello.com/c/ozzxcO3o/1221-join-a-service-dev-work

Migration to add join a service permission to all orgs

---

.pre-commit-config.yaml
app/celery/process_ses_receipts_tasks.py
app/celery/process_sms_client_response_tasks.py
app/celery/provider_tasks.py
app/celery/service_callback_tasks.py
app/celery/tasks.py
requirements.in
requirements.txt
requirements_for_test.txt
requirements_for_test_common.in
ruff.toml

This brings in the utils change https://github.com/alphagov/notifications-utils/pull/1213 which means we should get early-log-messages for celery tasks and also should have celery task identifiers available on log messages.
Stop early-log-messages for all tasks we call very heavily to reduce the effect this change has on our log volumes.

notifications-utils: 98.0.0 -> 99.0.0, reduce early log level for heavily-called celery tasks

---

app/schemas.py
tests/app/service/test_rest.py

Also test updating service daily message limits.
This PR needs to be merged in before the admin one: https://github.com/alphagov/notifications-admin/pull/5437

Add international_sms_message_limit to ServiceSchema

---

app/config.py
app/dao/report_requests_dao.py
app/service/rest.py
tests/app/dao/test_report_requests_dao.py
tests/app/service/test_rest.py

- Duplicate detection logic: When a request is submitted, we now check for an existing request with the same user, service, report type, and parameter values (notification_type, notification_status). If a matching request is already in a non-final state (pending or in progress) and is within the timeout window, we return that instead of creating a new one.
- Stale request handling: Requests are considered stale if updated_at is older than the configured timeout. If updated_at is null, we fall back to using created_at.
- Validation-first approach: Only notifications_report is supported at the moment. Any unsupported or invalid inputs will be rejected during schema validation.
- Test coverage: Added and extended tests
[Lock mechanism to prevent duplicate …

feat: Add duplication check and stale timeout logic to report-requests 

---

migrations/.current-alembic-head
migrations/versions/0499_merge_callback_tables.py

This moves over data from the service_inbound_api and service_inbound_api_history tables to
the service_callback_api and service_callback_api_history tables.
The the service_inbound_api and service_inbound_api_history tables will be dropped in a future migration.
***
[Overall plan](https://docs.google.com/document/d/1Oo8VbB3tdJMLPM6WslJlbbwANA33_lJcN3a6AKkCL7A/edit?tab=t.0):

Copy service_inbound_api data to service_callback_api table

---

app/clients/email/aws_ses_stub.py

What
----
Fixing email stub provider after sesv2 upgrade and unsubscribe header changes
Why
----
Looks like this was broken by the following PRs:
https://github.com/alphagov/notifications-api/pull/4079
https://github.com/alphagov/notifications-api/pull/4082
https://github.com/alphagov/notifications-api/pull/4179

Fixing email stub provider

---

requirements.in
requirements.txt
requirements_for_test.txt

https://trello.com/c/u5f3qgz9/48-upgrade-gunicorn-from-1299ea9e967a61ae2edebe191082fd169b864c64-to-2300
What
----
Upgrade gunicorn and eventlet
Why
----
We are still using a very old version.
Notes
----
[Functional tests passing](https://concourse.notify.tools/teams/dev-d/pipelines/deploy-notify/jobs/functional-tests/builds/59)

Upgrade gunicorn and eventlet

---

migrations/.current-alembic-head
migrations/versions/0500_update_intl_limit_values.py

First get services that sent international SMS in the last 12 months, and how many they sent on their busiest day.
Then for each of those services, if they sent more than 50 on their busiest day, and if they are still at default limit, set their new international_sms_message_limit to busiest day * 2.
Then get all remaining services that have their international_sms_message_limit set to default value (250,000) and set their limit to 100 per day.
This has been tested locally:
- for service with default limit that did not send any intl sms (updates to 100)
- for service with default limit that sent 200 intl sms on busiest day (updates to 400)
- for service with default limit that sent 49 intl sms on busiest day (updates to 100)
- for service not on default limit (it shouldn't update)
The …

Set default limits for existing services

---

app/notifications/process_notifications.py
app/notifications/validators.py
tests/app/notifications/test_process_notification.py
tests/app/notifications/test_validators.py

When checking and adding to daily international sms limit.

Treat crown dependency numbers as domestic when checking limits

---

app/celery/service_callback_tasks.py
app/dao/services_dao.py
app/functional_tests_fixtures/__init__.py
app/platform_admin/rest.py
app/service/callback_rest.py
tests/app/celery/test_service_callback_tasks.py
tests/app/platform_admin/test_rest.py
tests/app/service/test_callback_rest.py

Now that that the migration has completed and the `service_callback_api` and `service_callback_api_history` tables both contain `inbound_sms` data, we want to decouple `service_inbound_api` from all callback code.
The redundant `service_inbound_api` code will not be removed in this PR, that will be done in a subsequent PR.
This PR is dependent on this PR https://github.com/alphagov/notifications-admin/pull/5451 being merged in first as this would be a breaking change for the Admin app.
***
[Overall plan](https://docs.google.com/document/d/1Oo8VbB3tdJMLPM6WslJlbbwANA33_lJcN3a6AKkCL7A/edit?tab=t.0):

Update callback endpoints to only use service callback api

---

app/notifications/validators.py

`UK_PREFIX` is not used here. If someone wants to know exactly what `is_uk_phone_number` does the best and most up-to-date way to find out is look at its code

Remove outdated comment

---

app/notifications/process_notifications.py
tests/app/notifications/test_process_notification.py

we were inadvertently doing this for all notifications. previously we used `notification.international` which resolves to False for emails, but we switched to checking if the prefix is NOT uk - the prefix for emails is None so this was resolving as true.
(fun fact: it would have continued to resolve false for international letters)

only increment international SMS limit cache for SMS notifications

---

app/celery/research_mode_tasks.py
app/notifications/notifications_letter_callback.py
app/schema_validation/__init__.py
tests/app/celery/test_research_mode_tasks.py
tests/app/conftest.py
tests/app/notifications/test_notifications_letter_callbacks.py

Since February 2025, we have noticed a mismatch between the GDS ft_billing report and the DVLA billing report. After looking into it, we found that the issue is linked to a callback change we made at the end of 2024. At that time, we were told to use productionRunDate (Print Date), but the problem started when DVLA changed their report or began using transitionDate instead.
The change we are now making updates the despatched_on value from productionRunDate to transitionDate.
When DVLA sends a callback, details like notification_id, despatched_on, and cost_threshold are stored in the notifications_letter_despatch table. A nightly task then runs to calculate billing and stores it in ft_billing.
Each time we get a callback for a letter, we receive a despatched_on date (previously …

Update from productionRunDate to transitionDate

---

app/celery/research_mode_tasks.py
app/clients/letter/dvla.py
app/constants.py
app/notifications/notifications_letter_callback.py
tests/app/celery/test_research_mode_tasks.py
tests/app/clients/test_dvla.py
tests/app/notifications/test_notifications_letter_callbacks.py

There is new "economy" postage option available for letters. Updating the DVLA API request payload to send "ECONOMY" in the despatchMethod. All other logic for the existing postage classes will stay the same.
For the callback the mailingProduct will be shown as 'UNSORTEDE' for UNSORTED ECONOMY and 'MM ECONOMY' for Mailmark Economy.  The postage class will be '2ND' for both.
More details on the [card](https://trello.com/c/zY3ijvpi/1245-send-economy-postage-to-dvla)

Send economy postage to dvla

---

app/constants.py
app/dao/services_dao.py
app/functional_tests_fixtures/__init__.py
app/utils.py
migrations/versions/0317_uploads_for_all.py
tests/app/dao/test_services_dao.py
tests/app/service/send_notification/test_send_pdf_letter_notification.py
tests/app/service/test_rest.py

This removes service permissions that had been used as feature flags in the past but which are no longer used.
After this change, they can be removed from the database.
To be merged after https://github.com/alphagov/notifications-admin/pull/5462

Remove unused service permissions

---

app/celery/letters_pdf_tasks.py
app/constants.py
migrations/versions/0347_add_dvla_volumes_template.py
tests/app/celery/test_letters_pdf_tasks.py
tests/app/conftest.py

The automated email we send to the DVLA each night needs updating to
include economy mail letters, otherwise these will be counted in the
international letters section.
The templates will need to updated manually. Updating the template in
the migration ensures that new environments that are created will have
the correct content.

Add economy mail postage to letters volume email

---

app/celery/tasks.py
app/dao/report_requests_dao.py
app/service/rest.py
tests/app/celery/test_tasks.py
tests/app/dao/test_report_requests_dao.py
tests/app/db.py
tests/app/service/test_rest.py

We have an endpoint to create report requests, and a class which generates the data. This connects the two bits by creating a task which, when called from the endpoint, uses our existing code to generate the data.
The task does nothing if the report request is already in "pending" status. Otherwise it, calls the code to generate the data and updates the status of the report request appropriately.
https://trello.com/c/ubo67aY3/1265-celery-task-report-data-processing

Add task to generate report requests

---

app/models.py
app/schemas.py
migrations/.current-alembic-head
migrations/versions/0501_drop_inbound_api_table.py
tests/app/service/test_rest.py

This PR contains a migration to drop both the `service_inbound_api` and `service_inbound_api_history` tables.
It also updates the DetailedServiceSchema.
There are a few sqauwk-migration-checks warnings that may need to be silenced.
This PR is dependant on https://github.com/alphagov/notifications-api/pull/4466 being merged in first. It is also linked to this PR https://github.com/alphagov/notifications-admin/pull/5465

Drop service inbound api table

---

.pre-commit-config.yaml
app/models.py
requirements.in
requirements.txt
requirements_for_test.txt
requirements_for_test_common.in
ruff.toml
tests/app/v2/notifications/test_get_notifications.py

- By providing latest delivery date we are trying to set a more realist expectation for users  for when they should receive their letters by
- [Update delivery estimates code to accomodate economy postage](https://trello.com/c/JngKcHSO/1272-update-delivery-estimates-code-to-accomodate-economy-postage)

refactor: Return latest delivery date for letters instead of earliest

---

app/notifications/process_notifications.py

By splitting the code which talks to Redis from the code which figures out which caches to set it should be easier to follow what is going on.
It also reduces duplication of the Redis-talking code and lets us put all the logic for international SMS in one place, rather than double-checking and using [flag arguments](https://martinfowler.com/bliki/FlagArgument.html).

Refactor `increment_daily_limit_cache` to be easier to follow

---

app/notifications/process_notifications.py
tests/app/notifications/test_process_notification.py

We stopped checking the overall message limit in https://github.com/alphagov/notifications-api/pull/3706
We dropped the database column entirely in https://github.com/alphagov/notifications-api/pull/3712
This was part of the work to move to a per-channel message limit.
We are still keeping track of how many messages each service has sent each day in Redis, but we never look at this value.
This is an unnecessary extra call to Redis each time a message is sent, and [confuses](https://github.com/alphagov/notifications-api/pull/4465#discussion_r2099846523) people reading the code.

Stop incrementing overall message limit for services

---

app/notifications/process_letter_notifications.py
app/service/send_notification.py
app/utils.py
tests/app/notifications/test_process_letter_notifications.py
tests/app/service/send_notification/test_send_one_off_notification.py
tests/app/service/send_notification/test_send_pdf_letter_notification.py
tests/app/v2/notifications/test_post_letter_notifications.py

This stops using the economy mail permission feature flag now that it should be rolled out to all services, undoing the work in https://github.com/alphagov/notifications-api/pull/4450
Database permissions will need to be removed separately

Remove economy mail feature flag and permission checks

---

app/config.py
tests/app/test_config.py

https://trello.com/c/joBsPfMJ/955-move-sqs-queue-creation-into-terraform-and-clean-up-old-queues
What
----
Add predefined queue names so celery will not try to create queues
Why
----
We want all queues to be created and managed through terraform
Note
----
This change should not be merged before [this pr](https://github.com/alphagov/notifications-aws/pull/2564).

Add predefined queue names so celery will not try to create queues

---

app/models.py
migrations/.current-alembic-head
migrations/versions/0502_add_confirmed_unique.py
tests/app/service/test_rest.py

Migration to add new column for `services` and `services_history` table. This will be used to know if users have confirmed their unique service already when trying to change the Service name on the dashboard during the "make service live" journey
- [Confirm Service is Unique](https://trello.com/c/vG9OowgU/1302-make-your-service-live-5-6-add-the-confirm-your-service-is-unique-task)

feat: Add service column confirmed_unique

---

app/report_requests/process_notifications_report.py
tests/app/report_requests/test_process_notifications_report.py

For large datasets, using page and skip slows down the query because it needs to count and skip many rows. Cursor-based pagination is faster since it jumps directly to the next item using a cursor. It works by taking the notification ID from the last batch and passing it as `older_than` to get the next set. This avoids scanning unnecessary data and also used by get notifications API.
Tested locally and the output file looks identical before and after changing to older_than.

Fix batch time for report request

---

app/letters/utils.py
tests/app/letters/test_letter_utils.py

We stopped incrementing the overall cache in https://github.com/alphagov/notifications-api/pull/4479 because it was no longer being checked.
This also means we don’t need to decrement it when cancelling letters (because it will never have been set).

Don’t decrement overall cache when letters are cancelled

---

requirements.txt
requirements_for_test.txt

The versions we were using don’t install on newer versions of Python because of the way they are packaged.

Bump greenlet, pycurl and cffi to the latest versions

---

tests/app/db.py

This had 2 problems:
- starting from `1` meant that it could generate a non-valid phone number like `071`, except for the use of 0-padded string formatting (which is a pretty niche/non-intuitive feature)
- ending with a number specified in scientfic notation means that number is a float, and floats are not valid arguments to `randint` as of Python 3.12
`randint` is an alias of `randrange`, and _What’s new in Python 3.12_ says:
> Formerly, randrange(10.0) losslessly converted to randrange(10). Now, it raises a TypeError. 
– https://docs.python.org/3/whatsnew/3.12.html#changes-in-the-python-api

Fix generation of random phone numbers in test data

---

app/functional_tests_fixtures/__init__.py
tests/app/functional_test_fixtures/test_functional_test_fixtures.py

https://trello.com/c/BGgPtUux/1147-make-a-dev-environment-like-staging-and-test-functional-tests
What
----
Add an option to override the organisation name inside the functional test fixtures.
Why
----
This will allow the functional tests to run against different environments that have different setups regarding their databases. 
This is part of the work to remove the preview environment and run the functional tests in staging.

Add functional test organisation name override inside the functional tests fixtures

---

migrations/.current-alembic-head
migrations/versions/0506_n_history_job_id_index.py

This is a temporary change to allow us to delete the old emergency alerts data. The `job_id` foreign key constraint on the `notification_history` table means that when attempting to delete the jobs, Postgres also needs to check the `notification_history` table which is taking too long without an index.
It was not possible to send a broadcast as a job, but there are still broadcast services in the database which have rows in the `jobs` table because in some cases, we converted an existing "normal" service to a broadcast service.

Add job_id index to notification_history

---

migrations/.current-alembic-head
migrations/versions/0506_n_history_job_id_index.py
migrations/versions/0507_n_history_service_id_index.py

This is a temporary change to allow us to delete the old emergency alerts data.
The service_id foreign key constraint on the notification_history table means
that when attempting to delete the services, Postgres also needs to check the
notification_history table which is taking too long without an index.

Add service_id index to notification_history 

---

app/celery/nightly_tasks.py
app/config.py
app/dao/report_requests_dao.py
app/service/rest.py
tests/app/celery/test_nightly_tasks.py
tests/app/dao/test_report_requests_dao.py

Generated report request files are stored in an S3 bucket with a 1-day lifecycle policy. After the files are deleted from S3, the related database entries become redundant, so we mark them as 'deleted'. We keep these deleted report requests for a while to support stats or investigations. More info on this [card](https://trello.com/c/qsDngRr6/1349-daily-job-to-update-s3-files-as-deleted-phase-1b).
First need to merge https://github.com/alphagov/notifications-api/pull/4506

Set the status of outdated report requests to deleted

---

migrations/.current-alembic-head
migrations/versions/0509_delete_broadcast_data.py

This is a data migration (so no downgrade) that deletes broadcast services and all associated data - this includes obvious things like broadcast events and templates, but also everything connected to those services.
Although some of these theoretically shouldn't exist for broadcast services (eg returned_letters), we attempt to delete them out of an abundance of caution.
[This work is based off an older PR](https://github.com/alphagov/notifications-api/pull/4201), which was tested against a copy of the staging database. That PR was reverted because it was taking too long to delete from the `notification_history` table due to the foreign key constraints - since then, indexes have been added to notification_history to make deleting from the table faster.
Differences between this PR and the …

Remove emergency alerts data

---

.pre-commit-config.yaml
requirements.in
requirements.txt
requirements_for_test.txt
requirements_for_test_common.in
ruff.toml
tests/app/v2/notifications/test_get_notifications.py

* Updated the estimated letter delivery timings to take into account the change that first class letters are now the only postage class to be delivered on Saturdays, and delivery times for second class and economy mail are slower.
* add `x_forwarded_for_{0..3}` fields to pre/post request flask logs

Bump utils to 101.0.0

---

.pre-commit-config.yaml
requirements.in
requirements.txt
requirements_for_test.txt
requirements_for_test_common.in
ruff.toml

Adds updated redis_client with token bucket algorithm. Needed for the work on migrating from sliding window to token bucket for rate limiting. The version bump alone doesn't change how we are doing rate limiting, the redis_client wrapper method for token bucket needs to be explicitly called.

bump utils to 101.1.0

---

app/schemas.py
app/serialised_models.py
tests/app/test_serialised_models.py

Gets a serialised template version from here:
https://github.com/alphagov/notifications-api/blob/12b0aebfca0d2a1506cb208c12a58022b52c9c40/app/template/rest.py#L206-L208
Caches this in Redis here:
https://github.com/alphagov/notifications-admin/blob/cdd2286251446a04d2ae885cfc0da79acc39cb9e/app/notify_client/service_api_client.py#L256
Gets serialised template version from here:
https://github.com/alphagov/notifications-api/blob/12b0aebfca0d2a1506cb208c12a58022b52c9c40/app/serialised_models.py#L69
Caches this in Redis here (against the same key used by the admin app):
https://github.com/alphagov/notifications-api/blob/12b0aebfca0d2a1506cb208c12a58022b52c9c40/app/serialised_models.py#L58
***
The API is using:
- `TemplateHistorySchema` to serialise a template version for the admin app
- …

Use `TemplateHistorySchema` to serialise template versions

---

migrations/.current-alembic-head
migrations/versions/0510_delete_broadcast_tables.py

Now that there's no data that depends on these, we can delete the tables completely. This was important to do as separate steps, or we could end up in a case where have have fragments of broadcast services sitting in our database but without the broadcast-specific tables, which would leave us unsure as to what those services were.
This commit is taken from https://github.com/alphagov/notifications-api/pull/4202. The earlier work in that PR has already been merged, and this is the first stage of removing the database schema, which I'm splitting into separate PRs instead of doing in one.

Remove emergency alerts database tables

---

app/schemas.py
tests/app/template/test_rest_history.py
tests/app/test_serialised_models.py

This could result in massive response sizes if a template gets a lot of unsubscribes.
It’s only here because Marshmallow includes everything by default, and we forgot to exclude it.
***
This PR also does some refactoring to make things like this less likely happen in the future.
***
Doesn’t affect the public API because it does its own serialisation here: https://github.com/alphagov/notifications-api/blob/31fcf69395b6e46ebac4b6852d23d96adcd2c293/app/models.py#L1132-L1151

Don’t serialise unsubscribe requests in template version response

---

app/notifications/validators.py
tests/app/notifications/test_validators.py

This was added in https://github.com/alphagov/notifications-api/pull/1500 for the internal API, as part of the work to add contact blocks for letters.
The original intention was that a default reply-to could be set on any type of template. We never went through with this and to this day only letters can have a per-template reply-to address (the contact block).
To clean things up we stopped using the generic function in https://github.com/alphagov/notifications-api/pull/4037
We still use the letter-specific function in 2 places on the internal API:
- https://github.com/alphagov/notifications-api/blob/6857eeac6fdf8f54c20f9016c30aa5a49f1b9d7d/app/template/rest.py#L106
- https://github.com/alphagov/notifications-api/blob/6857eeac6fdf8f54c20f9016c30aa5a49f1b9d7d/app/template/rest.py#L131
We …

Remove unused `check_reply_to` function

---

migrations/.current-alembic-head
migrations/versions/0512_drop_process_type_1.py
migrations/versions/0513_drop_process_type_2.py
migrations/versions/0514_drop_process_type_3.py

This is the final step in removing the priority queue entirely:
***
Squak issues:
```
/tmp/upgrade.sql:2:2: warning: ban-drop-column
2 | -- Running upgrade 0511_process_type_nullable -> 0512_drop_process_type
3 | 
4 | ALTER TABLE templates DROP COLUMN process_type;
note: Dropping a column may break existing clients.
/tmp/upgrade.sql:6:2: warning: ban-drop-column
6 | ALTER TABLE templates_history DROP COLUMN process_type;
note: Dropping a column may break existing clients.
/tmp/upgrade.sql:8:2: warning: ban-drop-table
8 | DROP TABLE template_process_type;
note: Dropping a table may break existing clients.
find detailed examples and solutions for each rule at https://squawkhq.com/docs/rules
Found 3 issues in 1 file (checked 1 source file)
```

Drop `process_type` columns and table

---

migrations/.current-alembic-head
migrations/versions/0515_token_bucket_permission.py

So that:
- we can test in production with our own services
- we can release the new algorithm without a code change
- we can roll back particular services if they have problems

Add service permission for token bucket rate limit 

---

app/celery/tasks.py
app/delivery/send_to_providers.py
app/serialised_models.py
app/utils.py
tests/app/test_serialised_models.py

Inspired by [recent template preview changes](https://github.com/alphagov/notifications-template-preview/pull/896).
A given version of a template will never change (changes to a template always create a new version).
So we can cache it in memory for longer because the cache will never become stale.
Going from 2 to 30 seconds here as it is:
- an order of magnitude bigger so should be a big performance increase (more chance of a cache hit)
- not wildy big that it might cause memory problems
- not wildly long that it might somehow cause timeouts/shutdown problems

Cache template version in memory more aggressively

---

app/celery/scheduled_tasks.py
app/config.py
app/dao/jobs_dao.py
tests/app/celery/test_scheduled_tasks.py
tests/app/dao/test_jobs_dao.py

Every minute, run a task that updates the status for jobs that finished processing all rows to the following status: JOB_STATUS_FINISHED_ALL_NOTIFICATIONS_CREATED.
This is so cancelling letter jobs works as expected.
Before this PR, users would have to wait around 30 minutes after sending a job before being able to cancel letters. This is a confusing experience, and it has led to a user thinking they cancelled their letters when they have not.
To test this code, I have:
1. run the apps locally with the celery beat (`make beat up`)
2. created a letter job
3. tried to cancel, failed
4. waited a couple minutes, succeeded

Promptly update the status for jobs that completed processing

---

Makefile

When `psutil` is installed `-n auto` causes the tests to only run in 1 worker on Concourse.
We should revert the PR which introduced psutil<sup>1</sup> at some point. In the meantime we can change the flag to `logical` which chooses the same number of workers as the number of logical CPU cores<sup>2</sup>. If `psutil` is uninstalled at any point then `-n logical` will fall back to the same behaviour as `-n auto`.
TL;DR this makes sure we always run the tests across 2 workers on Concourse which is quicker than 1 worker.
***
1. https://github.com/alphagov/notifications-api/pull/4348
2. https://pytest-xdist.readthedocs.io/en/stable/distribution.html

Run Python tests with `-n logical` instead of `-n auto`

---

app/dao/returned_letters_dao.py
app/service/rest.py
tests/app/service/test_rest.py

Related to https://trello.com/c/CQp2fcic/1297-work-out-if-we-can-purge-history-table-and-do-it
These are letters that have a `ReturnedLetter` but the corresponding notification has been purged from history. If we're considering purging more notification history, we're going to end up with more of these "orphaned" `ReturnedLetter` entries, which currently produce subtly illogical results in the admin UI. It's not 100% decided how to handle orphaned returned-letters in the UI, but it's certainly going to need the information to work with.
This is an api-breaking change because this endpoint previously returned a raw json array, with no way to provide extra data in the payload. ~This will need modifications to the admin app before we can consider merging.~ These modifications have been …

`get_returned_letters`: also return count of "orphaned" returned letters

---

migrations/.current-alembic-head
migrations/versions/0518_drop_n_hist_templates_index.py

This was [added to allow the emergency alerts data to be deleted](https://github.com/alphagov/notifications-api/pull/4514). Now that this has been done, we can drop the index.

Drop composite template index on notification history
