alphagov/notifications-api

app/__init__.py, app/service/__init__.py, app/service/rest.py, app/status/__init__.py, app/status/healthcheck.py, app/template/__init__.py, app/template/rest.py, app/user/__init__.py, app/user/rest.py
Flatten the structure.
Still an issue where create_app is being called twice
=> Remove the view packages

app/__init__.py, db.py, requirements.txt, scripts/aws_install_dependencies.sh, wsgi.py
- upgrade database
- use credstash for secret overrides
=> Added AWS files to

app/__init__.py, tests/app/authentication/test_authentication.py
- auth tests now use service endpoints
- one test commented out and needs reworked
=> Removed Status endpoints from requiring Auth tokens

app/schemas.py, app/service/rest.py, tests/app/service/test_api_key_endpoints.py, tests/app/service/test_rest.py
Created a new endpoint to return all api keys for a given service
=> Get api keys for service

app/service/rest.py, tests/app/service/test_api_key_endpoints.py, tests/app/user/test_rest.py
For /service/<service_id>/api_keys/<key_id>, key_id is optional. If key id exists it will return a list of one for the given key id. If key id does not exist it will return a list for the given service.
=> Updated get_api_keys endpoint 

app/service/rest.py, tests/app/dao/test_services_dao.py, tests/app/service/test_rest.py
Need to add this query param for the services page on the admin app.
Do not add the query param to path in the token.
=> Added user_id as a query param for get_services.

app/dao/users_dao.py, app/user/rest.py, tests/app/dao/test_users_dao.py, tests/app/user/test_rest_verify.py
This pr should wait until after hack day
=> Record and persist failed login count on api.

app/dao/users_dao.py, app/user/rest.py, tests/app/dao/test_users_dao.py, tests/app/user/test_rest_verify.py
=> If failed login count > 0 and user subsequently logs in sucessfully,

app/models.py, app/schemas.py, app/user/rest.py, tests/app/user/test_rest_verify.py
Previously we were using a schema that mapped onto db.Model. However, the json
in the request did not reflect the VerfiyCode db Model.
I did not add validation on the to field, we did not have that previously.
=> Create schema for RequestVerifyCodeSchema

app/notifications/rest.py, tests/app/notifications/test_rest.py
Removed the logic to check the api_user is the admin client user name.
There is another controller method to handle sending the verification codes.
=> Update to create_sms_notification

app/dao/jobs_dao.py, app/job/rest.py, tests/app/job/test_job_rest.py
need to be sent with update.
Also bug in not committing update fixed.
=> As job update is a PUT then all non nullable fields

app/authentication/auth.py, tests/app/authentication/test_authentication.py
- Add logging for auth errors
- Added a test for the case when there is no secret for the api client
=> Update the error response from the authentication method

app/dao/notifications_dao.py, app/models.py, tests/app/conftest.py, tests/app/dao/test_notification_dao.py
This makes it more consistent with other model classes with respect
to marhmallow serialisation/deserialisation.
=> [WIP] Added service and template relationship to notification model.

config.py, wsgi.py
If file does not exist default to live config.
=> Added code to read environemnt from a file

app/dao/notifications_dao.py, app/job/rest.py, app/schemas.py, tests/app/dao/test_notification_dao.py, tests/app/job/test_job_rest.py
=> [WIP] Added endpoints under /job for creating, updating and reading

requirements.txt
Brings in the API leeway on the JWT token.
=> Updated python client verion

app/aws_sqs.py, app/notifications/rest.py, tests/app/job/test_job_rest.py, tests/app/notifications/test_rest.py, tests/app/service/test_rest.py
- Return notification_id on create notification endpoints
- /notification/sms
- /notification/email
- /notificaiton/sms/service/<service_id>
- Update message attribute on SQS to notification_id from message_id
- Fixed intermittent test
=> Return notification is when adding notification to queue

app/service/rest.py, tests/app/service/test_rest.py, tests/app/service/test_url_for.py
New endpoint: /service/<service_id>/users returns a list of all users associated with the service
=> New endpoint to get users for service id.

app/dao/invited_user_dao.py, app/invite/rest.py, tests/app/conftest.py, tests/app/dao/test_invited_user_dao.py, tests/app/invite/test_invite_rest.py
=> [WIP] added dao and rest endpoint for retrieving invited users

app/dao/permissions_dao.py, tests/app/conftest.py, tests/app/user/test_rest.py
Refactor user/test_rest
Remove conftest/sample_admin_service
=> Fix bug in PermissionDAO

app/invite/rest.py, tests/app/dao/test_invited_user_dao.py, tests/app/invite/test_invite_rest.py
Can be used to update status on invited user.
=> New endpoint to update invited user.

app/__init__.py, app/accept_invite/rest.py, app/dao/invited_user_dao.py, app/service/rest.py, tests/app/dao/test_invited_user_dao.py, tests/app/service/test_rest.py
This only handles the case of an existing user being invited and added to an existing service.
=> [WIP] Start of api for accepting invite.

app/clients/email/aws_ses.py, app/clients/sms/firetext.py, app/clients/sms/twilio.py, requirements.txt
- time SES, Twilio, fire text calls
- use monotonic for accuracy
=> Add logging around 3rd party delivery calls

config.py, scripts/run_celery.sh
NOTE: make sure upstart script on preview is updated before merging.
=> Add routing keys to celery queues.

app/__init__.py, app/status/healthcheck.py, app/version.py, application.py, scripts/update_version_file.sh
Minor re-jig of status page
- fixed bug on date
- added build number
- fixed path
- moved code from __init__ to healthcheck
=> Status page

app/template/rest.py, requirements.txt, tests/app/template/test_rest.py
Reverts alphagov/notifications-api#130
=> Revert "Strip HTML from template content"

app/service/rest.py, tests/app/service/test_rest.py
of permissions instead of invitation json
This pr goes with: https://github.com/alphagov/notifications-admin/pull/234
=> [WIP] Changed add user to service to take list

app/template/rest.py, requirements.txt, tests/app/template/test_rest.py
This is a https://github.com/alphagov/notifications-api/pull/130 reopened, but using a different HTML parsing library which will hopefully install on AWS with no additional dependencies.
=> Strip HTML from template content

app/accept_invite/rest.py, app/dao/invited_user_dao.py, app/dao/jobs_dao.py, app/dao/services_dao.py, app/dao/templates_dao.py, app/dao/users_dao.py, app/errors.py, app/invite/rest.py, app/job/rest.py, app/notifications/rest.py, app/permission/rest.py, app/service/rest.py, app/template/rest.py, app/user/rest.py, tests/app/dao/test_invited_user_dao.py, tests/app/dao/test_services_dao.py, tests/app/dao/test_templates_dao.py, tests/app/dao/test_users_dao.py, tests/app/invite/test_invite_rest.py, tests/app/job/test_rest.py, tests/app/notifications/test_rest.py, tests/app/service/test_rest.py, tests/app/template/test_rest.py, tests/app/user/test_rest.py, tests/app/user/test_rest_verify.py
Changed db queries to use one, which throws NoResultFound exception, this exception is dealt with in our error handlers. Now a lot of the if none checks can be removed.
=> Error handing

app/dao/jobs_dao.py, app/models.py, tests/app/conftest.py, tests/app/dao/test_jobs_dao.py
Jobs order by created at date, newest first
=> Order jobs

app/models.py
Pass the utcnow function, rather than the result of executing the function.
=> Fix dates in the models

.travis.yml
Updated travis to deploy to all deployment groups.
=> Add all deplpyment groups to travis

app/celery/tasks.py, app/notifications/rest.py, app/validation.py, tests/app/celery/test_tasks.py, tests/app/test_validation.py
- Use the same validation in the endpoint and the task to validate the phone number is ok to send to.
- Format the phone number before sending it to the sms provider.
=> Format and validate phone number

db.py
update db script to use env file to select environment
=> Bring DB script into line with other prod scripts

.travis.yml, db.py
=> Live release

app/celery/tasks.py, app/schemas.py, requirements.txt
Implements (and depends on):
- https://github.com/alphagov/notifications-utils/pull/14
- https://github.com/alphagov/notifications-utils/pull/15
=> Strip trailing CSV rows, relax phone validation

app/__init__.py, app/dao/notifications_dao.py, app/job/rest.py, app/models.py, app/schemas.py, app/template_statistics/rest.py, tests/app/dao/test_notification_dao.py, tests/app/template_statistics/test_rest.py
Added dao method and rest endpoint for getting template statistics by service.
Added transactional decorator in notifications dao.
Some cosmetic changes to imports across various files.
Added fix for job rest not correctly returning errors.
=> [WIP] Added dao method and rest endpoint

app/dao/notifications_dao.py, tests/app/dao/test_notification_dao.py
Sort was previously on date only. This pr adds case insensitive additional ordering on template name.
=> Additional sort order by template name for template statistics.

requirements.txt
Implements https://github.com/alphagov/notifications-utils/pull/17
=> Fix bug with whitelist

app/dao/templates_dao.py, tests/app/dao/test_templates_dao.py
The template you want to send/edit is probably one of the ones you recently created or edited.
https://www.pivotaltracker.com/story/show/117159263
=> Order templates by last updated date

app/clients/sms/mmg.py, app/notifications/process_client_response.py, app/notifications/rest.py, tests/app/clients/test_mmg.py, tests/app/notifications/test_process_client_response.py, tests/app/notifications/test_rest.py
MMG changed the datatype and the status codes they send us for the delivery receipts.
This PR accounts for that change.
=> Update to processing the the response from MMG

app/clients/sms/mmg.py, tests/app/clients/test_mmg.py, tests/app/notifications/test_rest.py
Status codes from MMG are:
2: UNDELIVERABLE Message is undeliverable.
3: DELIVERED Message is delivered.
4: EXPIRED Message is expired.
5: REJECTED Message is rejected.
=> Update MMG responses so that 3 is success.

app/authentication/auth.py, requirements.txt, tests/__init__.py, tests/app/authentication/test_authentication.py, tests/app/events/test_rest.py, tests/app/invite/test_invite_rest.py, tests/app/job/test_rest.py, tests/app/notifications/test_rest.py, tests/app/permissions/test_rest.py, tests/app/service/test_api_key_endpoints.py, tests/app/service/test_rest.py, tests/app/service/test_service_fragment_count.py, tests/app/template/test_rest.py, tests/app/template_statistics/test_rest.py, tests/app/user/test_rest.py, tests/app/user/test_rest_verify.py
This version of the client removed the request method, path and body from the encode and decode methods.
The biggest changes here is to the unit tests.
=> Update python client to version 1.0.0.

app/commands.py, app/dao/notifications_dao.py, app/dao/provider_statistics_dao.py, app/dao/services_dao.py, app/dao/users_dao.py, application.py, tests/app/conftest.py, tests/app/dao/test_services_dao.py, tests/app/permissions/test_rest.py
=> Purge functional tests command added with passing test.

requirements.txt
=> Make email template more GOV.UK-y

app/celery/tasks.py, tests/app/celery/test_tasks.py
If reply to email exists on service when job is processed. Use it in place of email from.
=> Send using reply to

README.md, app/commands.py, app/dao/api_key_dao.py, app/dao/services_dao.py, server_commands.py, tests/app/dao/test_services_dao.py
The server commands is a file to run management commands on the servers.
I will look to remove the db.py file when I get back.
=> Add server_commands and update readme.md

tests/app/notifications/test_rest.py
Refers to the pivotal task #119746991
=> Fix test to check for decrypted dictionary value.

migrations/versions/0020_template_history_fix.py
There was a bug that was not setting the updated_at for the history table.
=> Data migration script to fix templates_history.updated_at.

app/dao/__init__.py, app/dao/jobs_dao.py, app/dao/notifications_dao.py, app/job/rest.py, tests/app/dao/test_jobs_dao.py, tests/app/job/test_rest.py
https://www.pivotaltracker.com/story/show/119369811
=> Add a limit days query param for get all jobs.

app/template/rest.py, tests/app/template/test_rest.py, tests/app/template/test_rest_history.py
Do not create a new version of the template if there is no change to the template.
https://www.pivotaltracker.com/story/show/120427863
=> Check for an update before saving template

app/__init__.py, app/clients/sms/firetext.py, app/clients/sms/mmg.py, requirements_for_test.txt, tests/app/clients/test_firetext.py, tests/app/clients/test_mmg.py, tests/app/conftest.py
cleaned up the send_sms functions in firetext.py and mmg.py, and wrote some tests to validate current behaviour
=> send_sms tests

.travis.yml
[good to merge]
https://docs.travis-ci.com/user/caching/
not quite the speed improvements i was hoping for (since we're still spending quite a bit of time, by the looks of it, installing C modules), but a few seconds is a few seconds.
new speed: ![image](https://cloud.githubusercontent.com/assets/5020841/15741967/0ff7f48a-28b4-11e6-8552-3c7d8ac6d304.png)
=> caching in travis

app/user/rest.py, tests/app/conftest.py, tests/app/user/test_rest_verify.py
- Update /sms-code endpoint to use the GOV.UK Notify service and it's sms code template, send the sms code via the send_sms task. 
- The GOV.UK Notify service and template data was added in a pervious merge.
Part of story https://www.pivotaltracker.com/story/show/120282429
=> Use notify to send sms codes

requirements.txt
=> Make URLs appear as links in email clients

app/celery/tasks.py
Remove the extra task created to handle the change to the send_email signature
=> Remove the extra task

app/celery/tasks.py, tests/app/celery/test_tasks.py
Final PR for https://www.pivotaltracker.com/story/show/120282429
=> Remove the invitation email and reset password email tasks.

config_live.py, config_staging.py
Live and staging configs had incorrect settings for the SQS connection. Fixed.
=> Update visibility timeout on staging and live

app/__init__.py, app/spec/rest.py, requirements.txt, requirements_for_test.txt, tests/app/spec/test_rest.py
Adds a new endpoint (`/spec`) which returns a the specification of the API in Swagger-formatted JSON.
This means we will have something to point frontends at, so we can evaluate which ones we like.
Right now it’s all hand-defined. If we were consistent about our use of Marshmallow we could generated the spec from the Marshmallow schemas.
Copy and paste the following JSON into [editor.swagger.io](http://editor.swagger.io)
```json
{
"definitions": {
"Error": {
"properties": {
"message": {
"description": "description of the error",
"type": "string"
},
"result": {
"description": "will say \u2018error\u2019",
"type": "string"
}
}
},
"NotificationSchema": {
"properties": {
"notification": {
"$ref": "#/definitions/NotificationStatusSchema"
}
}
},
"NotificationSentSchema": {
"properties": { …
```
=> Publish a Swagger specification

app/celery/provider_tasks.py, app/celery/tasks.py, tests/app/celery/test_provider_tasks.py, tests/app/celery/test_tasks.py, tests/app/clients/test_aws_ses.py
also added a test for aws_ses.send_email to prove it handles reply_to_address correctly
=> remove reply_to_addresses from task kwargs

app/celery/provider_tasks.py, app/notifications/rest.py, requirements.txt
Functional changes:
- adds the blue bar
Performance changes
- faster CSV processing
Depends on:
=> Bring in changes to template and CSV processing

requirements.txt
=> Fix Markdown/HTML email oddities

requirements.txt
=> Fix newlines in HTML emails

README.md, app/__init__.py, app/dao/organisation_dao.py, app/history_meta.py, app/models.py, app/organisation/rest.py, app/schemas.py, migrations/versions/0046_organisations_and_branding.py, tests/app/dao/test_services_dao.py, tests/app/organisation/test_rest.py, tests/conftest.py
`organisation` is a new table that holds an organisation's branding details - its colour, a path to its logo and its display name.
services now have a nullable organisation_id. 
branding refers to how the service interprets the org's branding. it can be one of three strings (backed by a foreign key to a static table)
* `govuk` - (default) GOV.UK branding, as current
* `org` - Only use the organisation's branding
* `both` - use both the gov.uk branding and the org's branding.
the history meta wasn't ready for nullable foreign keys. now it is!
=> Organisations

app/schemas.py, tests/app/notifications/test_rest.py
=> re-add Content char count

app/celery/provider_tasks.py, app/models.py, app/schemas.py, config.py, migrations/versions/0046_organisations_and_branding.py, tests/app/celery/test_provider_tasks.py, tests/app/service/test_rest.py
=> Render organisational branding in emails

requirements.txt
=> actually bump version

migrations/versions/0047_ukvi_spelling.py
was previously UK Visas and Immigration
now UK Visas & Immigration
=> update ukvi org branding spelling

app/models.py, migrations/versions/0044_jobs_to_notification_hist.py, migrations/versions/0048_job_scheduled_time.py, tests/app/job/test_rest.py
This will replace the job_status enum type.
=> Adds new job_status table and FK to jobs.

app/schemas.py
Added in [January](49e98c21e74e4bdcb8ad63223a46170d05f9182d) and (for better or worse) it got done.
=> Remove outdated comment

migrations/versions/0052_drop_jobs_status.py
This allows existing code to run.
=> Changed 0052 to not drop the column, rather set it to allow nulls.

app/celery/tasks.py, tests/app/celery/test_tasks.py, tests/app/public_contracts/test_POST_notification.py
- Fix issue where sending messages to external numbers with a test key fails
- Add corresponding tests
@servingUpAces does this work as expected?
=> Fix test key external number issue

requirements.txt
=> Fix HTML lists in Microsoft Outlook

app/celery/provider_tasks.py, app/dao/provider_statistics_dao.py, tests/app/celery/test_provider_tasks.py, tests/app/notifications/rest/test_callbacks.py
The provider_statistics table is no longer being populated, get rid of any reads from this table.
=> Remove provider_statistics_dao.get_provider_statistics

app/authentication/auth.py, tests/app/authentication/test_authentication.py
- Improve the error message when the service id is not the right data type.
- Improve the error message is the api key is not valid.
=> Improve authentication error message

requirements.txt
Also please have a look at my boto changes: https://github.com/alphagov/boto/pull/1/files
=> Use custom patched boto: 2.42.0-patch1

app/models.py, migrations/versions/0058_add_letters_flag.py, tests/app/service/test_rest.py
defaults to false
pretty boring otherwise
=> add can_send_letters flag to services

tests/app/notifications/rest/test_send_notification.py, tests/conftest.py
```
tests/app/service/test_rest.py F
================================================ FAILURES ================================================
_____________________ test_get_service_list_should_return_empty_list_if_no_services ______________________
notify_api = <Flask 'app'>, notify_db = <SQLAlchemy engine='postgresql://localhost/test_notification_api'>
notify_db_session = None
def test_get_service_list_should_return_empty_list_if_no_services(notify_api, notify_db, notify_db_session):
with notify_api.test_request_context():
with notify_api.test_client() as client:
auth_header = create_authorization_header()
response = client.get(
'/service',
headers=[auth_header]
)
>               assert response.status_code == 200
E               assert 500 == 200
E                +  where 500 = …
```
=> remove 500/unplanned exception handlers in test

app/authentication/auth.py, app/errors.py, app/schema_validation/__init__.py, app/schema_validation/definitions.py, app/v2/errors.py, tests/app/notifications/test_validators.py, tests/app/v2/notifications/test_notification_schemas.py, tests/app/v2/notifications/test_post_notifications.py, tests/app/v2/test_errors.py
update V2 error response to  …
{
status_code: 403,
errors: [error: AuthError, message: token has expired}]
}
=> Change v2 error resp

app/authentication/auth.py, app/dao/dao_utils.py, app/dao/services_dao.py, app/models.py, app/service/rest.py, migrations/versions/0059_set_services_to_active.py, tests/__init__.py, tests/app/authentication/test_authentication.py, tests/app/conftest.py, tests/app/dao/test_services_dao.py, tests/app/service/test_deactivate.py, tests/app/service/test_rest.py, tests/conftest.py
new endpoint which deletes templates, revokes keys, and archives a service.
there aren't any checks in the code anywhere to prevent inactive services doing things, however, without a template and/or an api key there's not much we want to block them from so i think that's okay (unless i'm forgetting something really obvious, in which case checks will be pretty trivial to put in).
=> deactivate a service

app/__init__.py
This should catch any unexpected exceptions.
=> Add application level error handler.

app/notifications/validators.py, tests/app/notifications/test_validators.py
=> Refactored a couple of tests that were slightly testing the wrong thing.

requirements.txt
Slightly improves statsd logging.
=> Latest version of utils included

app/accept_invite/rest.py, tests/app/accept_invite/test_accept_invite_rest.py
Update the error message that a user will see if the invitation is expired.
=> Invite expiry message

app/clients/sms/firetext.py, app/clients/sms/mmg.py, app/delivery/send_to_providers.py
- help tie things together  in Kibana.
=> Log notification ID on deliver tasks and in clients.

app/celery/research_mode_tasks.py, tests/app/celery/test_research_mode_tasks.py
This updates them to the dedicated "TV" numbers. Should never be real.
=> Turns out the numbers in the research mode task were delivering.

app/service/rest.py, tests/app/service/test_rest.py
fixes 500 on platform admin page
=> make sure we convert strings to dates before we use them

app/config.py
Small change to reset performance update task to run at 00:30 each day.
=> Reset schedule to run at 00:30 daily

scripts/aws_install_dependencies.sh
Reverts alphagov/notifications-api#831
=> Revert "Ensure all wheels are installed offline from the wheelhouse directory"

app/models.py, app/user/rest.py, migrations/versions/0065_users_current_session_id.py, tests/app/user/test_rest_verify.py
when we change the last logged in time, set the current session id to
a random uuid
this way, we can compare it to the cookie a user has, and if they
differ then we can log them out
also update user.logged_in_at at 2FA rather than password check, since
that feels more accurate
=> Add current_session_id to the user model, update on login

app/user/rest.py, tests/app/user/test_rest_verify.py
2FA is the grand daddy of "has this user logged in recently", not email codes. i hadn't realised that email codes used the same function
=> dont set session_id or logged_in_at if user provides email code

migrations/versions/0066_add_dvla_provider.py, tests/app/dao/test_provider_details_dao.py, tests/app/provider_details/test_rest.py
=> Added the provider details for DVLA.

app/cloudfoundry_config.py, app/notifications/rest.py, manifest-api-base.yml, manifest-delivery-base.yml, tests/app/test_cloudfoundry_config.py
also we log the confirmation url for SNS subscriptions
=> Get Redis config from PaaS

app/__init__.py, app/notifications/rest.py, tests/app/notifications/test_receive_notification.py
Created an endpoint to test how the incoming messages from MMG will work.
So this just prints the response to logs, removing the phone number first. Then returns the requested RECEIVED.
=> Initial creation of the endpoint to receive sms messages

app/job/rest.py
Reverts alphagov/notifications-api#857
=> Revert "Add temporary logging for job notifications' retrieval"

app/celery/tasks.py, app/statsd_decorators.py
Added logging for the build_dvla_file task
=> Update statsd decorator so that it will log on error.

app/celery/tasks.py, requirements.txt, tests/app/celery/test_tasks.py, tests/app/conftest.py
There was a problem with the address block for the DVLATemplate.
Added a countdown to the build_dvla_file.
=> Update the version of notifications-utils.

app/__init__.py, app/utils.py, app/v2/template/__init__.py, app/v2/template/get_template.py, app/v2/template/post_template.py, app/v2/template/template_schemas.py, tests/app/v2/template/test_get_template.py, tests/app/v2/template/test_post_template.py, tests/app/v2/template/test_template_schemas.py
Added v2 template preview endpoint and schema with supporting tests
Specification outlined in this document [Notify V2 API](https://docs.google.com/document/d/1EuCipShwpZKVPQp3N0j7yRKazS34v5Bj5E9epl89iqY/edit#heading=h.pdggcx1vfo8x)
execute py.test tests/app/v2/template/
=> Add v2 template preview endpoint and schema

migrations/versions/0070_fix_notify_user_email.py
=> fix notify service user email

requirements.txt, tests/app/notifications/rest/test_send_notification.py
Reverts alphagov/notifications-api#867
Causing a production issue for one of our users.
=> Revert "Bump utils to allow lists as placeholder values"

requirements.txt, tests/app/celery/test_tasks.py, tests/app/notifications/rest/test_send_notification.py
Reverts alphagov/notifications-api#883
=> Revert "Revert "Bump utils to allow lists as placeholder values""

app/celery/tasks.py, app/dao/jobs_dao.py, tests/app/celery/test_tasks.py, tests/app/dao/test_jobs_dao.py
Update job status to `ready to send`, indicating the file for the job has been uploaded to S3.
Leave a letter job in  progress until it is ready to send.
=> Update job status for letter jobs.

app/__init__.py, app/letters/letter_schemas.py, app/letters/send_letter_jobs.py, tests/app/letters/test_letter_schemas.py, tests/app/letters/test_send_letter_jobs.py
The task will be picked up by the FTP app. Given the list of job ids the tasks will get all the files from s3, aggregate them then send to dvla
=> Api to start dvla file sending

app/v2/template/post_template.py, app/v2/template/template_schemas.py, tests/app/db.py, tests/app/v2/template/test_post_template.py, tests/app/v2/template/test_template_schemas.py
Personalisation in v2 preview for the subject line was not correctly handled and the preview schema was expecting personalisation when it is legitimate to not provide it for a preview.
pytest -k test_valid_post_template_returns_200
[V2 API specification](https://docs.google.com/document/d/1EuCipShwpZKVPQp3N0j7yRKazS34v5Bj5E9epl89iqY/edit#heading=h.pdggcx1vfo8x)
=> V2 preview subject personalisation

app/letters/send_letter_jobs.py, tests/app/letters/test_send_letter_jobs.py
Updated the response from send_letter_jobs to return json block rather than plain text.
execute `pytest tests/app/letters/test_send_letter_jobs.py`
=> Update letter jobs

requirements.txt
=> Bump utils to fix problems with our output to DVLA

app/__init__.py, tests/app/celery/test_tasks.py
as DVLA need upper case only or the barcode doesn't generate.
=> Upper case only in the random notification id generator

app/__init__.py, app/celery/tasks.py, app/dao/dvla_organisation_dao.py, app/dvla_organisation/rest.py, app/models.py, app/schemas.py, tests/app/celery/test_tasks.py, tests/app/dao/test_services_dao.py, tests/app/dvla_organisation/test_rest.py, tests/app/service/test_rest.py, tests/conftest.py
Reopens https://github.com/alphagov/notifications-api/pull/906 but without the database migration.
https://github.com/alphagov/notifications-api/pull/911 should be deployed first.
=> Revert "Revert "add DVLA organisations to API""

tests/app/service/test_rest.py
Update tests to include `can_send_international_sms`flag
=> Update tests to include international sms flag

app/__init__.py, app/notifications/notifications_letter_callback.py, tests/app/notifications/rest/test_callbacks.py
S3 will send a message when a file lands - which will trigger processing of DVLA responses.
=> Wired in a simple callback to handle SNS notifications from S3

app/dao/date_util.py, app/dao/notification_usage_dao.py, app/dao/notifications_dao.py, app/dao/services_dao.py, tests/app/dao/test_date_utils.py, tests/app/dao/test_notification_usage_dao.py
Fix the logic getting the rates for a financial year.
=> Fix get rates for year

migrations/versions/0079_update_rates.py, tests/app/dao/test_notification_usage_dao.py, tests/app/service/test_rest.py
Rates are currently not in sync with what Admin expects meaning that the cost applied is 100x out, this db script will correct that in the database.
Tests have also been updated to reflect the expected rate in admin
=> Udpate rates

app/dao/notifications_dao.py, app/schemas.py, app/service/rest.py, requirements.txt, tests/app/dao/test_notification_dao.py, tests/app/service/test_rest.py
New endpoint to search for notifications given an email address or phone number. 
The query ignores case and spaces.
=> Search for notification by number or email

app/schemas.py, tests/app/job/test_rest.py, tests/app/test_schemas.py
now return `status`, as they should
=> marshmallow schemas no longer return _status_enum column

migrations/versions/0082_add_golive_template.py
This adds a template in a migration that will be sent automatically when a service goes live. 
_Note: This will also include some personal information that'll be added separately._
=> Add go live template (Migration)

app/aws/s3.py, app/celery/tasks.py, app/dao/notifications_dao.py, app/notifications/notifications_letter_callback.py, app/notifications/notifications_ses_callback.py, app/notifications/utils.py, tests/app/celery/test_tasks.py, tests/app/notifications/rest/test_callbacks.py
One of the functions being refactored missed the require params. I'll add tests for this next week.
Reverts alphagov/notifications-api#939
=> Revert "Process SNS request triggered by a DVLA S3 update"

app/__init__.py, app/authentication/auth.py, app/config.py, app/dao/services_dao.py, app/notifications/process_notifications.py, app/notifications/rest.py, app/notifications/validators.py, app/v2/notifications/get_notifications.py, app/v2/notifications/post_notifications.py, app/v2/template/get_template.py, app/v2/template/post_template.py, app/v2/templates/get_templates.py, requirements.txt, tests/app/notifications/test_process_notification.py, tests/app/notifications/test_validators.py
Optimise auth code to store service on the request context on a successful auth.
this removes the need to fetch the service on every subsequent controller method.
=> Load service on auth

Makefile, scripts/check_if_new_migration.py
This adds a script (with make command) to detect if there are any new migrations that need to be run. This can be used by our Jenkins jobs to determine whether we need to run migrations.
This is currently just an idea, thoughts around the script itself?
=> POC: Add a script to check if there are new migrations

.gitignore, scripts/delete_sqs_queues.py
Wrapped it in docopts so we can choose to list or delete queues. Basic functionality the same.
- list generates a csv
- delete reads the csv and deletes each queue in it.
Use with caution.
=> Did some work around the delete queues script

app/models.py, migrations/versions/0088_govuk_sms_sender.py, tests/app/delivery/test_send_to_providers.py, tests/app/service/test_rest.py
Reverts alphagov/notifications-api#1001
=> Revert "Revert "Remove nulls from sms_sender""

app/notifications/receive_notifications.py, tests/app/notifications/test_receive_notification.py
=> mmg spell received incorrectly, lets use that

app/config.py, app/dao/notification_usage_dao.py, app/models.py, app/schemas.py, tests/app/dao/test_notification_usage_dao.py, tests/app/service/test_rest.py, tests/conftest.py
This PR adds the billing amount correctly to the API - takes into account free tier.
Additionally adds free tier to the service API calls, so the service now owns it's free tier.
=> Remove nasty query from dashboard

app/dao/notifications_dao.py, tests/app/dao/test_notification_dao.py, tests/app/template_statistics/test_rest.py
Fix for:
https://www.pivotaltracker.com/story/show/146615775
Note needs further work in:
https://www.pivotaltracker.com/story/show/146850973 to have a longer term solution.
=> Template query to not limit by days

migrations/versions/0098_tfl_dar.py
=> Add organisation for TFL Dial a Ride

app/celery/tasks.py, app/dao/service_inbound_api_dao.py, app/notifications/receive_notifications.py, app/service/rest.py, tests/app/celery/test_tasks.py, tests/app/dao/test_service_inbound_api_dao.py, tests/app/notifications/test_receive_notification.py
New task to send the inbound sms to the service. If the service has not set the url then nothing happens. If the request to the service url returns with 500 or greater the task is retries. The task is created when the SMS provider post the inbound SMS
=> Push inbound sms

app/models.py, app/notifications/process_notifications.py, tests/app/notifications/test_process_notification.py
(also make sure it's well tested :tada: )
=> ensure created_by_id is being persisted correctly

migrations/versions/0093_data_gov_uk.py
Reverts alphagov/notifications-api#1044
=> Revert "Remove name from organisation"

app/notifications/receive_notifications.py
Some test codes to inject the inbound sms sender's IP address to the log
=> add logs to see the IP address of the inbound sms

app/__init__.py, app/authentication/auth.py, app/notifications/receive_notifications.py, app/status/healthcheck.py
Some test code to inject IP addresses into logger
=> IP restriction for inbound sms test 2

app/authentication/auth.py
Very minor change on the displayed message
=> Inboundsms checkip

app/commands.py
This adds a custom Flask-Script command to backfill the `_status_fkey` for all the `NotificationHistory` notifications from the old `_status_enum`. 
`Notification` has a new column called `_status_fkey` which is currently populated in sync with `_status_enum`. This happens behind the scenes and is read/written from `Notification.status`. The new field was not populated when the migration so this adds a script to do this.
Additionally the script file has been customised so in the future if we want to add more scripts, we define a function e.g. `def populate_foo()` and then run with `python application.py custom_db_script -n populate_foo` where for `-n` we specify the name of the function.
To ensure no downtime, a test was run locally with 8m notifications populated with an empty …
=> Add script to backfill new Notification.status

app/__init__.py, app/authentication/auth.py, app/config.py
1 step before blocking the sms from unknown IP address. We are just checking right now.
=> Check inbound sms IP address stage 1

app/models.py, tests/app/dao/test_jobs_dao.py, tests/app/dao/test_notification_dao.py
Reverts alphagov/notifications-api#1057
=> Revert "1/4 Stop updating old Notification status column"

app/authentication/auth.py, app/config.py, tests/app/authentication/test_authentication.py
=> IP address in config file uses comma rather than full stops

app/config.py
=> IP address checked

requirements.txt
=> Update the notifications-utils version.

app/authentication/auth.py, app/cloudfoundry_config.py, app/config.py, tests/app/authentication/test_authentication.py, tests/app/test_cloudfoundry_config.py
retrieve ip whitelist from credentials
=> retrieve sms ip whitelist from credentials on paas

app/dao/services_dao.py, app/models.py, app/schemas.py, migrations/versions/0106_drop_template_stats.py, migrations/versions/0107_drop_template_stats.py, tests/app/dao/test_notification_dao.py, tests/app/dao/test_services_dao.py
The last time the table we updated was August 30 2016, it's safe to say we are done with it.
I updated the InboundSms and TemplateRedacted model to include an index in the db.
Dropped service_permissions.updated_at column since we are not auditing the table
=> Remove the archived table template_statistics. 

app/__init__.py, app/celery/__init__.py, app/celery/celery.py, app/celery/provider_tasks.py, app/celery/research_mode_tasks.py, app/celery/scheduled_tasks.py, app/celery/statistics_tasks.py, app/celery/tasks.py, app/config.py, app/delivery/rest.py, app/invite/rest.py, app/job/rest.py, app/letters/send_letter_jobs.py, app/notifications/notifications_letter_callback.py, app/notifications/process_notifications.py, app/notifications/receive_notifications.py, app/notifications/rest.py, app/service/send_notification.py, app/service/sender.py, app/user/rest.py, app/v2/notifications/post_notifications.py, docker/Dockerfile, requirements.txt, tests/app/celery/test_statistics_tasks.py, tests/app/service/test_send_one_off_notification.py
Brought in martyn's changes - had to do some hefty conflict resolution. Got rid of his definitions.py change cos it was just a bit too big.
* There are some *gross* problems related to imports. I'd like to sort them out before 
* Priority queue locally seems absolutely fine. sent_at - created_at is ~99% < 1 second. Am seeing prod-like times when running celery 3 (15, 20 seconds etc).
=> Celery 4 (attempt 2)

requirements.txt, requirements_for_test.txt
also ignore celery improvements
this just consolidates all of the changes that were easy to test from the pyup swarm
=> bump test requirements

app/dao/monthly_billing_dao.py, app/dao/notification_usage_dao.py, tests/app/dao/test_monthly_billing.py, tests/app/dao/test_notification_usage_dao.py
- Add transactional
- Rename function for clarity
=> Add transactional for new query

app/commands.py, app/dao/monthly_billing_dao.py, app/models.py, migrations/versions/0112_add_start_end_dates.py, tests/app/celery/test_scheduled_tasks.py, tests/app/dao/test_monthly_billing.py
This will allow us to sort the data properly.
Also updated the updated_at timestamp when the row is updated.
=> Removed month and year and replaced it with start_date and end_date.

aws_run_celery.py, db.py, requirements.txt, server_commands.py, wsgi.py
we don't need it now that we're on the glorious PaaS
=> remove credstash

aws_run_celery.py, db.py, requirements.txt, server_commands.py, wsgi.py
This reverts commit 7db1bfbb774ca222855cbaf47366477d7134a675.
=> Revert "remove credstash"

app/config.py, aws_run_celery.py, db.py, manifest-delivery-base.yml, requirements.txt, run_celery.py, server_commands.py, wsgi.py
removed aws_run_celery because it's confusing and doesn't need to exist anymore
don't remove `notify_celery` import!
=> Remove credstash without breaking celery

requirements.txt
Was accidentally removed here #33cfe3955723df4bcc9bd015917080e3035f953c
=> Fix - Add celery back

requirements.txt
Bumped to fix dash formatting issue
=> Bump version to pick up fix for dashes

app/schema_validation/definitions.py, tests/app/v2/notifications/test_post_letter_notifications.py
whoops, wasn't checking for it in the schema
=> address_line_2 is a required field

app/models.py, app/v2/template/get_template.py, tests/app/test_model.py, tests/app/v2/template/test_get_template.py
=> make sure template serialises letter subjects

app/config.py
wasn't setting log path properly
=> fix broken cloudfoundry logs

requirements.txt
=> Bump utils to 18.0.1

migrations/versions/0114_another_letter_org.py
=> Add letter organisation for Companies House

app/commands.py
This updates the existing `PopulateMonthlyBilling` to get and update the billing data for all services that need it.
The command can be run as follows:
`python application.py populate_monthly_billing -y 2016`
This will still update per year just to ease the database update.
=> Update command populate billing data for services that require it

requirements.txt, tests/__init__.py
accidentally removed in a bad merge - jenkins didn't notice and the tests worked because jenkins re-uses the previous environment 😬
=> re-introduce flask-marshmallow

requirements.txt
Brings in:
https://github.com/alphagov/notifications-utils/compare/18.0.1...19.0.0
=> Bump utils to 19.0.0

requirements.txt
=> Bump utils to 19.0.2

requirements.txt, scripts/run_app_paas.sh
Supercedes https://github.com/alphagov/notifications-api/pull/1211
Brings in:
=> Letter fixes and multi-process logging

app/commands.py, app/performance_platform/processing_time.py, application.py, tests/app/test_commands.py
to run this on a server:`cf run-task notify-api "python application.py backfill_processing_time -s='2017-07-01' -e='2017-09-01'"`
=> Backfill perf stats

requirements.txt, scripts/run_app_paas.sh
This removes the PID from the log files
=> Bump notifications-utils version to 21.0.0

app/authentication/auth.py, tests/app/authentication/test_authentication.py
Using 24 bit mask to monitor IP traffic for inbound sms.
=> Inbound sms monitoring update

requirements.txt
This will stop logging the request, as it is logged by nginx-access logs
=> Bump utils to 21.2.0

app/models.py, app/v2/notifications/notification_schemas.py, scripts/bootstrap.sh, tests/app/dao/test_monthly_billing.py, tests/app/test_model.py, tests/app/v2/notifications/test_get_notifications.py, tests/app/v2/notifications/test_notification_schemas.py
`accepted` to be specific.
From there, they don't change at all when we send to DVLA - but may go to `technical failure` if we mess up somewhere
=> Letters are accepted, not created or sending

app/models.py, app/schemas.py, migrations/versions/0122_add_service_letter_contact.py, tests/app/db.py, tests/app/test_model.py
Step 1 / 3 from https://www.pivotaltracker.com/story/show/151287398 to create table to store letter contact details for services
- added data model & migration script
- added tests
=> Add ServiceLetterContact data model and migration script

app/dao/services_dao.py, app/schemas.py, app/service/rest.py, tests/app/service/test_rest.py
**Why**
Platform Admin takes too long to load
**Changed**
1. /service/ end point pass live or trial mode as a parameter to limit the number of returned items. 
2. Simplified DetailedServiceSchema
**Story**
**Related PRs**
https://github.com/alphagov/notifications-admin/pull/1506
=> Platform Admin Timeout problem

app/commands.py, application.py
Migration server command to create one row in Service_sms_senders for each service.
=> Migration for Service SMS senders 

app/authentication/auth.py
**Why:**
Not seeing log messages for Inbound IP sms monitoring on Kibana
**What:**
Change the logic sequence
=> Inbound sms ip messages

Makefile
This should cause the app to get new credentials for the database upon
pushing.
=> Unbind the db service before pushing the app

app/config.py
Updated the scheduled time as we will lose a day in processing letters
=> Update ftp tasks to send in the evening rather than the morning

app/dao/service_letter_contact_dao.py, app/service/rest.py, app/service/service_senders_schema.py, tests/app/dao/test_service_letter_contact_dao.py, tests/app/service/test_rest.py
**Why:** 
Add new letter contact api end points for multiple addresses
**What has been changed:**
New API end points, new daos and new tests
**Pivotal story:** 
https://www.pivotaltracker.com/story/show/151287663
=> Add new letter contact block endpoints (multiple addresses)

app/celery/provider_tasks.py, app/celery/scheduled_tasks.py, app/celery/statistics_tasks.py, app/celery/tasks.py, gunicorn_config.py
-Added extra logging to celery and gunicorn tasks, specifically to capture when SIGTERM and SIGINIT are received, so that we can track better when an app restarts and if it has been restarted ungracefully.
=> Adding extra logging to celery tasks and gunicorn

app/delivery/send_to_providers.py, tests/app/delivery/test_send_to_providers.py, tests/app/v2/notifications/test_post_notifications.py
else we ignore it when retrying
=> reset notification to created if fake callback throws exception

app/celery/tasks.py
Deleted three Celery tasks (`send-email`, `send-sms` and `persist-letter`).
These are not being used anymore - we replaced them in commit
0c9a4bce595f4e186c6e0fc4d29eb1439eec4103.
=> Remove unused Celery tasks

tests/app/dao/test_services_dao.py
`test_fetch_stats_by_date_range_for_all_services_returns_test_notifications` was failing when the test was run between 11pm and 12am during BST as the expected results did not match due to time adjustment when retrieving stats.
- So time was fixed so that the test would not fail
- New test for the BST hour with similar data injection to make sure that the function works.
=> Add stats test for BST and fix existing stat test

app/models.py, migrations/versions/0128_noti_to_sms_sender.py
There is also some minor db model updates here so that the python db model match the db
=> Create a new table to map a notification to a SMS sender.

app/authentication/auth.py
This small PR remove printing the route secret into logs, as preparation for this pivotal story:
https://www.pivotaltracker.com/story/show/146688097
=> removed printout of route secret

tests/app/service/test_rest.py
This was already working, but adds a test to make sure that it works as expected.
Still to do:
- migrate all services to having `True` or `False` in this column
- make column non-nullable
- start rejecting `None` as a possible value for this update
=> Allow updates to the SMS prefix setting

app/authentication/auth.py, app/cloudfoundry_config.py, app/config.py, tests/app/authentication/test_authentication.py, tests/app/test_cloudfoundry_config.py
Continue from PR #1365
This PR retrieve from environment variable and test it again the x.44 header; and log the results.
**Related PR:** 
https://github.com/alphagov/notifications-api/pull/1365
**pivotal story:**
https://www.pivotaltracker.com/story/show/146688097
=> initial logging for route protection

app/billing/rest.py, app/service/rest.py, tests/app/billing/test_billing.py
This PR is part of the organisation type changes in this pivotal story:
https://www.pivotaltracker.com/story/show/152067121
In this step, we create bridging code to update the annual_billing table from the service end point, before the admin code is deployed and the data is migrated.
=> Bridging API to update annual_billing table

app/celery/tasks.py, tests/app/celery/test_tasks.py
If the post to a url for the inbound sms message to the service throwns an unknown exception - or RequestException, the base exception for request, the error will be logged and retried.
=> Retry unknown exceptions for send_inbound_sms_to_service task

app/notifications/receive_notifications.py
This PR verifies that authorisation token is sent as claimed by the provider. 
Pivotal story: https://www.pivotaltracker.com/story/show/152964252
=> Inbound sms pre-implementation test 1

app/delivery/send_to_providers.py, app/models.py, app/schemas.py, tests/app/service/test_rest.py
=> Remove computed SMS prefix

app/dao/services_dao.py, app/service/rest.py, tests/app/dao/test_services_dao.py, tests/app/service/test_rest.py
Removed the REST endpoint and the DAO that it uses as the endpoint is
no longer used by the Admin UI and the DAO is not reused anywhere
else.
- Removed REST endpoint
- Removed DAO which gets the stats
- Removed associated tests of both methods
=> Removed the templates/monthly endpoint

app/models.py
This was missed out of the previous PR and needs to be there before the next PR is merged.
=> Add reply_to_text to Notification model.

app/config.py
=> Remove SQLALCHEMY_ECHO for test

tests/app/inbound_sms/test_rest.py
=> fix linter stuff

app/config.py, app/notifications/process_notifications.py, app/notifications/validators.py, app/v2/notifications/create_response.py, app/v2/notifications/post_notifications.py
- Disable Redis as there is a current connection limit of 256 which
could slow down the request if they are all used
- Added statd to methods in the post to help spot any bottlenecks
=> Disable Redis for Staging added statsd for post methods

app/models.py, migrations/versions/0148_add_letters_as_pdf_svc_perm.py
Adds `letters_as_pdf` to `service_permission_types`
https://www.pivotaltracker.com/story/show/151511579
=> Add letters_as_pdf service permission

requirements.txt
It needs setting to the new one in both places.
=> Fix incomplete version number specification

app/service/rest.py
It does not make sense there and the page is broken (this is not a publicly know url).
=> Removed the events data for the service/{id}/history page. 

app/celery/service_callback_tasks.py, tests/app/celery/test_service_callback_tasks.py
Update the json in the service callback task to read completed_at rather than updated_at
=> Update JSON in callback task

Makefile
=> fix makefile syntax

app/aws/s3.py, tests/app/aws/test_s3.py
So if someone sends a letter in the evening, it gets picked up the
next day
=> put pdfs in tomorrow's dvla bucket after 17:30

app/aws/s3.py, app/celery/scheduled_tasks.py, app/config.py, app/dao/notifications_dao.py, manifest-delivery-base.yml, tests/app/celery/test_scheduled_tasks.py, tests/app/dao/notification_dao/test_notification_dao.py, tests/app/test_config.py
Added a scheduled task which will run at 17:50 in order to kick off processing for zipping letter pdfs.
Step 1 / 5 - https://www.pivotaltracker.com/story/show/151511632
=> Add run letter pdfs

app/invite/rest.py, tests/app/invite/test_invite_rest.py
When we’re doing user research we often:
- start the task by inviting the participant to a service on Notify
- have them use a prototype version of the admin app, hosted on a different domain
Currently we can’t do both of these things together, because the invite emails always send people to `notifications.service.gov.uk` (because it’s the API that sends the emails, and the prototype admin app points at the production API).
This commit changes the API to optionally allow an instance of the admin app to specify which domain should be used when generating invite links.
=> Allow admin to specify domain to use for invite links

app/models.py, app/notifications/rest.py, app/service/send_notification.py, tests/app/celery/test_tasks.py, tests/app/template/test_rest.py, tests/app/v2/notifications/test_post_letter_notifications.py
If template has a default address use that address ELSE the address is blank.
=> Change for template default address

app/celery/letters_pdf_tasks.py, tests/app/celery/test_letters_pdf_tasks.py
this means if we end up with some notifications sending and others not, due to problems with the ftp connectivity for example, we don't re-send those that worked.
As a reminder, letter pdf notifications start as created and stay that way until we have sent the zip file to DVLA, at which point they are updated to sending
=> only send letters in created state to ftp app for zipping

requirements.txt
Brings in:
Changes: https://github.com/alphagov/notifications-utils/compare/23.5.0...23.5.2
=> Be stricter about length of phone numbers

migrations/versions/0160_another_letter_org.py
=> Add letter logo for environment agency

app/__init__.py, app/email_branding/rest.py, app/models.py, app/schemas.py, app/service/rest.py, tests/app/email_branding/test_rest.py, tests/app/service/test_rest.py
=> Email branding remove org

app/__init__.py, app/errors.py, app/v2/errors.py
most of them are 400s for badly inputted phone numbers etc
=> downgrade lots of routine logging from error/exception to info

migrations/versions/0165_another_letter_org.py
=> Add letter logo for Welsh Revenue Authority and East Riding of Yorkshire Council

app/models.py, migrations/versions/0118_service_sms_senders.py, migrations/versions/0166_add_org_user_stuff.py, requirements.txt, tests/conftest.py
just wanted to open up this PR early (before adding all the new endpoints) to keep the reviewability easy
=> Org user DB models

app/commands.py
Expected file format is one number per line, each phone number should be 07... not 447..
=> Added a command to insert inbound numbers from file.

app/dao/notifications_dao.py, tests/app/dao/notification_dao/test_notification_dao.py
also make sure that the service isn't in research mode
=> send letters for services without letters_for_pdf

app/schemas.py, tests/app/service/test_rest.py
it's no longer a field on the service
=> don't return or accept sms_sender in update service anymore

app/v2/notifications/post_notifications.py, tests/app/v2/notifications/test_post_notifications.py
We were already counting the billable units in PDFs that we generate.
We are now also counting the number of billable units in pre-compiled letters
and saving the result.
=> Count the number of pages in pre-compiled letters

app/celery/service_callback_tasks.py, app/letters/utils.py
Added notification id to the log message for upload pdf to make it easier to search for the letter notification in the logs.
=> Update log message

app/template/rest.py, tests/app/celery/test_letters_pdf_tasks.py, tests/app/celery/test_tasks.py, tests/app/template/test_rest.py
Moved some logic from Admin to API to generate preview images for created PDFs
This needs to be merged in before the refactored Admin gets merged.
https://www.pivotaltracker.com/story/show/155323846
=> Add get template preview

app/celery/scheduled_tasks.py, app/performance_platform/total_sent_notifications.py, tests/app/performance_platform/test_total_sent_notifications.py
Now we’ve been sending real letters for quite a while it would be nice to show how many.
=> Send count of sent letters to performance platform

app/models.py, requirements.txt, tests/app/celery/test_tasks.py
=> Remove anything to do with DVLA format letters

app/celery/tasks.py, requirements.txt, tests/app/celery/test_tasks.py
_Branched off https://github.com/alphagov/notifications-api/pull/1733_
---
Shouldn’t be any functional changes here, just things being named more clearly.
Brings in:
=> Bring in refactored CSV processing

app/dao/api_key_dao.py, tests/app/dao/test_api_key_dao.py
Currently there is no filter on the api_keys query. In certain cases, it clutters the admin panel with redundant api keys. This PR filters out any revoked API keys that are older than 7 days.
=> Filter revoked api keys older than 7 days

app/dao/users_dao.py, app/models.py, app/organisation/rest.py, app/schemas.py, app/service/rest.py, app/user/rest.py, tests/app/user/test_rest.py
New endpoint that returns a user's organisations and services. It groups services by organisation - provided that the user knows about that organisation. It only returns active services/orgs.
=> User orgs and services

migrations/versions/0180_another_letter_org.py
=> Add Rother District Council logo for letters

app/commands.py
Add statd to monitoring the length of task
=> Add statd to monitoring the length of task

app/dao/inbound_sms_dao.py, app/inbound_sms/rest.py, app/v2/inbound_sms/get_inbound_sms.py, tests/app/dao/test_inbound_sms_dao.py
Adjusted the old inbound sms endpoint to allow for a page to also be given, this gives the flexibility to create a paginated inbox page without also changing the conversation page.
=> Update inbound sms method

app/celery/provider_tasks.py, app/celery/scheduled_tasks.py, app/config.py, app/dao/notifications_dao.py, tests/app/celery/test_scheduled_tasks.py, tests/app/dao/notification_dao/test_notification_dao.py
If a sms or email has not been sent after 4 hours and 15 minutes then put it on the delivery queue.
=> Replay emails and sms that are still in created

migrations/versions/0184_alter_primary_key_1.py
Alter primary key for ft_billing table to include international
As international can be true and rate_multiplier can be 1
=> Alter primary key for ft_billing table to include international

requirements.txt
To bring in:
Changes:
- https://github.com/alphagov/notifications-utils/compare/25.2.2...25.2.3
=> Bump utils to 25.2.3

app/dao/inbound_sms_dao.py, app/inbound_sms/rest.py, tests/app/dao/test_inbound_sms_dao.py, tests/app/inbound_sms/test_rest.py
Updated paginated inbound sms message endpoint to get the most recent message for 50 users ( rather than the most recent 50 messages). 
Also removed page and limit from old `get_inbound_sms_for_service` method because they were never used.
=> Added new paginated inbound endpoint

app/v2/notifications/post_notifications.py, tests/app/v2/notifications/test_post_letter_notifications.py
Reverts alphagov/notifications-api#1820
=> Revert "Fix research mode preview of precompiled letters"

app/utils.py, requirements.txt, tests/app/delivery/test_send_to_providers.py, tests/app/notifications/rest/test_send_notification.py, tests/app/notifications/test_rest.py, tests/app/v2/notifications/test_get_notifications.py, tests/app/v2/notifications/test_post_notifications.py
Brings in:
Changes:
- https://github.com/alphagov/notifications-utils/compare/25.3.0...26.2.0
=> Bump utils to improve plain text email formatting

requirements.txt
=> Bump utils to normalise newlines in text messages

app/commands.py
We need to rebuild the monthly billing for one service for the month of March.
This change makes that possible without affecting any other data in the table.
=> Update populate_monthly_billing to take a service_id and month

app/celery/scheduled_tasks.py, tests/app/celery/test_scheduled_tasks.py
Fix the query that raises the alert for letters still in sending.
If Monday or Tuesday check for letters still sending after 4 days.
If Saturday or Sunday do nothing
If Wed, Thurs, Fri check for letters still sending after 2 days
Added test for Tuesday, corrected tests after the correction to query.
=> Fix alert for letters still in sending

app/commands.py
This will allow us to rebuild the data if there is an issue with the data that is older than the past 3 days.
=> Added a command to rebuild the data for a given service_id and date

migrations/versions/0187_another_letter_org.py
ID of 505 matches https://github.com/alphagov/notifications-template-preview/pull/124
=> Add letter organisation for CADW

app/service/rest.py, tests/app/service/test_rest.py
the admin app currently calls get_detailed_service, which gets notification stats, adds them on to the rest of the detailed service endpoint, and returns them. However, the admin app then only looks at the stats - it doesn't look at the rest of the service object.
This is called in a few high profile places - the dashboard, the notification summary page, and when you send a job. By creating a separate endpoint that ignores the rest of the service object (and no marshmallow too!), the hope is that we'll improve (or at least understand) some of the slowness we've been seeing.
Note: The old detailed function will still need to stay - it's used by `get_services(detailed=True)` for the platform admin page.
=> create new stats endpoint

app/dao/fact_billing_dao.py, migrations/versions/0191_ft_billing_pkey.py
Use the primary key constraint in the upsert statement (easier to read than listing all the columns)
=> Add rate to the primary key of ft_billing.

app/__init__.py, app/complaint/complaint_rest.py, app/models.py, app/notifications/notifications_ses_callback.py, tests/app/celery/test_process_ses_receipts_tasks.py, tests/app/complaint/test_complaint_rest.py, tests/app/dao/test_complaint_dao.py, tests/app/db.py, tests/app/notifications/test_notifications_ses_callback.py
New endpoints to retrieve all complaints. A new platform admin page will be added to report all complaints. 
Fix to handle complaints. 
The request from SES was not quite as expected and the update was failing. The test data now better reflects the actual data. Updates to the code have been made to save the complaint.
=> Get all complaints

app/notifications/notifications_ses_callback.py, tests/app/celery/test_process_ses_receipts_tasks.py, tests/app/notifications/test_notifications_ses_callback.py
Fix unit test to actually test the right thing
=> Add some useful information to the log.

app/dao/notifications_dao.py, tests/app/dao/notification_dao/test_notification_dao.py
The caseworking view is going to have a page which displays emails and text messages combined together.
In order for the search to work on this page the user needs to be able to search for an email or a text message. This commit makes it guess what to search for when the `notification_type` isn’t known (basically by saying ‘if the search term is only digits they’re probably looking searching by phone number’).
=> Search for emails or texts, depending on term

migrations/versions/0199_another_letter_org.py
`009` matches the ID defined in https://github.com/alphagov/notifications-template-preview/pull/143
***
=> Add letter logo for HM Passport Office

app/commands.py
Update to the command to migrate data for ft_notification_status.
Removed the initial queries - I don't think they are helpful.
Ready to run and test the migration.
=> Complete the migration command for ft_notification_status.

app/celery/reporting_tasks.py, app/config.py, app/dao/fact_notification_status_dao.py, tests/app/celery/test_reporting_tasks.py, tests/app/dao/test_fact_notification_status_dao.py
Created a task to update ft_notification_status for the last three days.
=> Nightly task for updating ft_notification_status

migrations/versions/0200_another_letter_org.py
=> Add Ofgem letter logo

app/commands.py, app/invite/rest.py
Added a one off command to add many invited user to a service.
It would be nice to add something that can do this from the Admin app.
=> Command to add invited users from a CSV file

requirements.txt, tests/app/v2/notifications/test_notification_schemas.py
There has been an update to the email validation code.
Added an extra test for email validation.
=> Updated notifications-util to the latest version

app/dao/notifications_dao.py, app/dao/users_dao.py, app/schemas.py, app/user/rest.py, app/utils.py, tests/app/user/test_rest.py
Pivotal ticket: https://www.pivotaltracker.com/n/projects/1443052/stories/158497234
Related Admin pull request: https://github.com/alphagov/notifications-admin/pull/2158
=> Add data endpoint for finding users by full or partial email

docker/Dockerfile, requirements-app.txt, requirements.txt
=> Bump utils to fix smart quotes in email addresses

requirements-app.txt, requirements.txt
Depends on:
***
Changes: https://github.com/alphagov/notifications-utils/compare/29.3.3...bullet-for-bullet
=> Bump utils to 29.3.4

app/dao/notifications_dao.py, tests/app/dao/notification_dao/test_notification_dao_delete_notifications.py
Deal with letters that have not been sent, this can be test letters or letters in tech-failure.
Fix deleted count.
=> Fix deleted count for logs and delete with letters that have not been sent

app/aws/s3.py, app/dao/notifications_dao.py, tests/app/dao/notification_dao/test_notification_dao_delete_notifications.py
=> Fix bug with deleting the S3 file.

app/aws/s3.py, app/dao/notifications_dao.py, tests/app/dao/notification_dao/test_notification_dao_delete_notifications.py
If there are no files to delete we won't get an excpetion.
Wrap the delete file in a try/except to avoid stopping the entire task.
Fix the missing slash for the file name.
=> Fixes to the delete letter notifications.

app/email_branding/email_branding_schema.py, app/models.py, migrations/versions/0214_email_brand_type.py, migrations/versions/0215_email_brand_type.py, tests/app/email_branding/test_rest.py
It makes more sense to put the brand_type with EmailBranding rather than in Service.
Next step is to add the new type to the form in admin app.
=> Add brand_type to EmailBranding.

migrations/versions/0218_another_letter_org.py
Matches: https://github.com/alphagov/notifications-template-preview/pull/192
=> Add NHS logo for letters

migrations/versions/0222_drop_service_branding.py
_This is branched off https://github.com/alphagov/notifications-api/pull/2072 and will need rebasing before merging._
We’re not using this column any more, so let’s clean up after ourselves.
=> Drop service branding column 

app/models.py, tests/app/job/test_rest.py
The concern about performnace degrading has been thought through. We do not believe there will be an adverse effect since the high volume users do not send off messages.
=> Add created_by_name to the Notification.serialize_for_csv.

app/notifications/process_letter_notifications.py, app/notifications/process_notifications.py, app/v2/notifications/post_notifications.py, tests/app/notifications/test_process_letter_notifications.py, tests/app/notifications/test_process_notification.py
It's a small change, but we should remove any db operations that are not necessary.
=> Reduce updates to notification

app/commands.py
sets all letters in notification history (and notifications) to `"second"`, so that there's no null letters for billing etc. Commits in ten day chunks (up to ~30k letters)
=> populate historic notification postage data

app/letters/utils.py, app/models.py, tests/app/job/test_rest.py, tests/app/letters/test_letter_utils.py
Set the postage in the filename based on the postage set on the notification.
=> Set postage on PDF filename from notification

requirements-app.txt, requirements.txt
https://github.com/alphagov/notifications-utils/compare/30.4.0...30.5.2
=> Bump utils to 30.5.2

requirements-app.txt, requirements.txt, tests/app/user/test_rest_verify.py
Brings in:
---
Changes: https://github.com/alphagov/notifications-utils/compare/30.5.3...30.5.4
=> Bump utils to 30.5.4

app/config.py, app/letters/utils.py, tests/app/conftest.py, tests/app/letters/test_letter_utils.py
it was crashing on admin.
Note: The page still doesn't suggest that the letter failed validation, but at least it loads.
=> make sure validation_failed notifications still return pdf

app/celery/letters_pdf_tasks.py
it doesn't match a string 😩. I couldn't think of a good way to test this in a unit test, since it involves changing the service id on all of the components of a service.
=> compare service id to UUID

app/celery/letters_pdf_tasks.py, tests/app/celery/test_letters_pdf_tasks.py
Also fixed the spelling error, why not.
=> Reduce the error logging for sanitse method

app/celery/tasks.py
the extra information may help when trying to help debugging an issue.
=> Added inbound_sms_id to log output

requirements-app.txt, requirements.txt
This brings in the change to email validation which removes obscure white space from email addresses.
[Pivotal story](https://www.pivotaltracker.com/story/show/161290942)
=> Update notifications-utils to 30.5.6

app/service/statistics.py, tests/app/service/test_statistics.py
Add validation-failed and virus-scan-failed in the failed counts for stats
=> Add new failed stats to statistic counts

app/authentication/auth.py, app/celery/process_ses_receipts_tasks.py, app/celery/provider_tasks.py, app/clients/email/__init__.py, app/clients/sms/__init__.py, app/commands.py, app/utils.py, requirements-app.txt, requirements.txt, requirements_for_test.txt, setup.cfg
* fix pyflake8 things
* unpin botocore/awscli - we were pinning it because newer versions weren't compatible with moto's requests patch
=> bump requirements

README.md
Added note about installing Postgres 9.6
=> Update README.md to reflect Postgres version needed

app/template_folder/rest.py, tests/app/template_folder/test_template_folder_rest.py
Change the error message, the folder id is not useful information to the user
=> Update error message

migrations/versions/0244_another_letter_org.py
=> Add letter logos for Bournemouth and Hants

app/celery/tasks.py, app/dao/jobs_dao.py, tests/app/celery/test_ftp_update_tasks.py, tests/app/dao/test_jobs_dao.py
The ftp app once updated the status of a job, since we no longer call the task we can delete it.
=> Remove unused task

app/__init__.py
Once the DB upgrade is complete we no longer want the added
overhead of "pre-ping" connection check.
=> Revert "Enable pessimistic DB connection disconnect handling"

app/template_folder/rest.py, tests/app/template_folder/test_template_folder_rest.py
these get shown on the front-end so make sure their content is good
=> template folder error messages

app/user/rest.py, tests/app/user/test_rest.py
We need this so we can check in the admin whether users have any live services.
=> Include live/trial mode in list of services

migrations/versions/0247_another_letter_org.py
=> Add letter logo for Neath Port Talbot Council

app/dao/notifications_dao.py, tests/app/dao/notification_dao/test_notification_dao_delete_notifications.py
Updated the query to improve the performance. 
The scheduled job for deleting emails has failed silently for many nights now.
=> Update delete notifications query

app/celery/scheduled_tasks.py, app/dao/notifications_dao.py
=> Commit the deletes every 10,000 rows.

app/dao/notifications_dao.py
Did a bit of refactoring.
Fixed the delete query to use the subquery, rather than a list, it should be more efficient and prevent a big list of ids being stored in memory.
=> Added the limit to the query for the services with data retention.

scripts/run_multi_worker_app_paas.sh
previously the script would:
try and SIGTERM each celery process every second for the 9 second
timeout, and then SIGKILL every second after, with no upper bound.
This commit changes this to:
* SIGTERM each process once.
* Wait nine seconds (checking if the pid files are still present each
second)
* SIGKILL any remaining processes once.
* exit
=> fix multi worker exit script

tests/app/conftest.py, tests/app/dao/notification_dao/test_notification_dao_template_usage.py, tests/app/db.py, tests/app/notifications/test_rest.py, tests/app/template_statistics/test_rest.py
This brings the number of warnings down from 1551 to 613.
=> Preparation for pytest 4 by sorting our use of fixtures in conftest

requirements-app.txt, requirements.txt
brings in https://github.com/alphagov/notifications-utils/pull/563
=> bump utils

requirements-app.txt, requirements.txt
while we sort out v3 compatibility
=> pin redis to 2.x

app/service/statistics.py, tests/app/service/test_statistics.py
Pivotal ticket: https://www.pivotaltracker.com/story/show/162310324
Connected admin PR: https://github.com/alphagov/notifications-admin/pull/2646
=> Remove cancelled from requested statuses in service statistics

migrations/versions/0249_another_letter_org.py
=> Add letter logo for North Somerset council

app/celery/letters_pdf_tasks.py, tests/app/celery/test_letters_pdf_tasks.py
If a precompiled letter can't be opened (e.g. because it isn't a valid
PDF) we were setting its billable units to 0, but not moving it to the
invalid PDF bucket. If a precompiled letter failed sanitisation, we were
moving it to the invalid PDF bucket but not setting its billable units
to 0.
This commit makes sure that we always set the billable units to 0
and move the PDF to the right bucket if it fails sanitisation or can't be
opened.
=> Move letters which can't be opened to invalid PDF bucket

app/v2/notifications/post_notifications.py, tests/app/v2/notifications/test_post_letter_notifications.py
Pivotal ticket: https://www.pivotaltracker.com/story/show/160231957
=> Return notification postage in response for .post_precompiled_letter_notification

migrations/versions/0251_another_letter_org.py
=> Add 5 new letter logos

scripts/run_multi_worker_app_paas.sh
This addresses some problems that existed in the previous approach:
1. There was a race condition that could occur between the time we were
looking for the existence of the .pid files and actually reading them.
2. If for some reason the .pid file was left behind after a process had
died, the script would never know because we do:
```
kill -s ${1} ${APP_PID} || true
```
=> Handle celery PIDs more reliably

lambda_function/README.md
I don’t think this is still current. It hasn’t been updated in 2 years.
=> Remove outdated folder

requirements-app.txt, requirements.txt
=> Bump utils to 30.7.5

app/template/rest.py, tests/app/template/test_rest.py
- ensure all new templates are  created with postage set to `second` and get rid of checks for CHOOSE_POSTAGE permission when creating
and updating a template.
https://www.pivotaltracker.com/n/projects/1443052/stories/162959391
https://github.com/alphagov/notifications-admin/pull/2695
- set postage for all existing templates to service default
- get rid of service default in separate PRs (first stop using `service.postage` in admin, then in api, and then migrate it out of our database)
- turn off "choose_postage" feature flag when all ready and tested
=> Set postage to second class when creating new letter template

migrations/versions/0254_folders_for_all.py, migrations/versions/0255_another_letter_org.py
Step 2 of 2 of shipping folders.
***
Depends on:
=> Give folders to all existing services

app/notifications/process_notifications.py, app/v2/notifications/post_notifications.py, tests/app/celery/test_tasks.py, tests/app/conftest.py, tests/app/db.py, tests/app/notifications/test_process_notification.py, tests/app/template/test_rest.py, tests/app/v2/notifications/test_post_letter_notifications.py, tests/app/v2/template/test_get_template.py
This PR will make choosing postage live for all our users.
To be released together with this PR: https://github.com/alphagov/notifications-admin/pull/2735
Part of this story: https://www.pivotaltracker.com/story/show/162959391
=> Set postage on basis of postage argument or template postage

migrations/versions/0257_letter_branding_migration.py
This PR is a follow on from https://github.com/alphagov/notifications-api/pull/2318.
Only thing new here is 0253_letter_branding_migration
For deploy 3 of https://www.pivotaltracker.com/story/show/163230257
=> Letter branding data migration

app/dao/services_dao.py, tests/app/dao/test_services_dao.py, tests/app/service/test_rest.py
We need another PR to remove it from ServicePermissionTypes and remove the data in service_permissions. And to remove it from models.py
=> Remove the need for the edit_folders service permission.

app/models.py, migrations/versions/0264_add_folder_permissions_perm.py
[#163755302](https://www.pivotaltracker.com/story/show/163755302)
Adds a new temporary service permission for enabling folder permission
editing.
=> Add folder permissions permission

migrations/versions/0278_add_more_stuff_to_orgs.py
Have to drop constraint before dropping columns.
=> Fix organisation domain migration

app/template_folder/rest.py, app/template_folder/template_folder_schema.py, tests/app/template_folder/test_template_folder_rest.py
Pivotal ticket: https://www.pivotaltracker.com/story/show/163755347
=> Update folder viewing permissions when updating a folder

tests/app/template_folder/test_template_folder_rest.py
Additional testing to see how update_template_folder handles simultaneous editing of viewing permissions for multiple users
Part of this story: https://www.pivotaltracker.com/story/show/163755347
=> Test update_template_folder can manage multiple users at once

app/celery/tasks.py, tests/app/celery/test_ftp_update_tasks.py
we failed when we received UNSORTED instead of Unsorted
=> ignore case in the cost_threshold in dvla response files

app/dao/inbound_sms_dao.py, app/inbound_sms/inbound_sms_schemas.py, app/inbound_sms/rest.py, tests/app/dao/test_inbound_sms_dao.py, tests/app/inbound_sms/test_rest.py
also removed the limit/limit_days args as they're not used by admin
=> combine post + get inbound, and make them respect data retention

app/dao/fact_notification_status_dao.py, tests/app/billing/test_billing.py, tests/app/dao/test_fact_notification_status_dao.py
=> Fix BST date bug for platform admin summary page.

app/celery/nightly_tasks.py, tests/app/celery/test_nightly_tasks.py
Update letter_raise_alert_if_no_ack_file_for_zip for new DVLA file format
When we send a zip file of letters to DVLA we expect them to send back an acknowledgement of those files.
Previously they named the files like NOTIFY.20180202091254.ACK.TXT and the contents would contain the name of the zip file we sent with a date of when they got it.
They have updated this format to mirror the format of the zip file because there was an instance where they sent 2 files of the same name so the later overwrote the first.
Since the name matches our name, there is no need to get the file from S3 but just compare file names.
=> Update alert for new DVLA file format

app/commands.py
Added a command to get more detailed information about the letters that
are listed in the files of 'zip files sent' that are stored on S3. This takes
one or more file paths as arguments and creates a CSV file with a row for each
letter.
=> Add command to get notification details from 'zips sent' files

app/commands.py
Update the migration so that if the boolean columns are set properly. 
'0' == False
'1' == True
'' == None
=> Fix boolean columns for organisation migration

app/commands.py
The association is based on the email address of the user that created the service, meaning we need to look at version 1 of the service_history.
Then use the existing methods to find the organisation by email address, then add the association.
=> Command to associate services to organisations.

app/dao/organisation_dao.py, app/dao/services_dao.py, app/status/healthcheck.py, tests/app/db.py, tests/app/status/test_status.py
So that we don’t have to update the home page manually any more.
=> Add method to count of live services and orgs

app/commands.py
https://www.pivotaltracker.com/story/show/164399003
=> Command to populate the volume intentions for services.

scripts/paas_app_wrapper.sh
=> add delivery-celery-beat to paas_app_wrapper

app/organisation/rest.py, tests/app/organisation/test_rest.py
This corrects it to look for the unique constraint.
=> The previous PR added a error handler for the wrong db exception.

app/celery/reporting_tasks.py, app/utils.py, tests/app/test_utils.py
last_n_days was only being used in a test.
=> Remove unused method.

app/commands.py
New command to populate the go live user and date from the beta partners spreadsheet.
=> Populate go live user and date

Makefile, app/config.py, manifest.yml.j2, scripts/run_app_paas.sh, scripts/run_multi_worker_app_paas.sh, statsd_mapping.yml
Downloads a linux binary from Github and puts it in the scripts folder This should add it to the package CI uploads to CF during deploy …
=> Local statsd exporter

app/commands.py
We want to continue not break.
=> Fix command to populate go live data

app/dao/services_dao.py, tests/app/dao/test_services_dao.py, tests/app/db.py, tests/app/service/test_rest.py
Story ticket: https://www.pivotaltracker.com/n/projects/1443052/stories/165791164
=> Add organisation type to live services report

Makefile, README.md, manifest.yml.j2
For implementation details and decisions made, see:
* https://github.com/alphagov/document-download-api/pull/54
* https://github.com/alphagov/document-download-api/pull/59
=> Zero downtime deploy

Makefile, README.md, manifest.yml.j2
Reverting to unblock pipeline while we investigate whether the v2 -> v3 transition causes one-off issues
=> Revert "Zero downtime deploy"

Makefile
this way we keep db bindings etc, and avoid accidentally dropping connections.
=> update manifest file to use zdt-push

application.py, run_celery.py
please don't deploy this to production
=> testing build failure

application.py, run_celery.py
Reverts alphagov/notifications-api#2508
=> Revert "testing build failure"

Makefile, manifest.yml.j2, scripts/run_app_paas.sh, scripts/run_multi_worker_app_paas.sh
Reverts alphagov/notifications-api#2516
=> Revert "AUTO-413: Use an internal app for statsd preview"

app/dao/notifications_dao.py, tests/app/dao/notification_dao/test_notification_dao_delete_notifications.py
Fortunately this bug only affected reporting complaints that came in after a notification was deleted.
=> Add missing reference to the update statement.

app/dao/annual_billing_dao.py, app/dao/services_dao.py, tests/app/dao/test_services_dao.py, tests/app/service/test_rest.py
adds a new column called free_sms_fragment_limit to the csv
=> Free sms allowance in billing report

app/celery/nightly_tasks.py, app/performance_platform/processing_time.py, tests/app/performance_platform/test_processing_time.py
make it easier to replay sending data for a day if it failed the first time round
=> allow you to pass in date to send perf stats

app/dao/templates_dao.py, tests/app/v2/template/test_get_template.py
Reverts alphagov/notifications-api#2536
=> Revert "Ensure dao_create_template doesn't clash with new trigger"

app/notifications/process_client_response.py, tests/app/notifications/test_process_client_response.py
We occasionally get an SMS with 0 `billable_units` if the `delivery-sender-worker` is stopped in the middle of processing a notification - we have to fix these manually. This change checks the billable units when we get the response from our SMS provider and sets the correct billable units if it's 0.
=> Fix 0 billable units on provider callback

migrations/versions/0298_add_mou_signed_receipt.py
* tell the user that clicks the button
* tell the notify team
* tell the person that the button was clicked on behalf of
(there are two templates for the first case)
=> add emails to send when an MOU is signed

requirements-app.txt, requirements.txt
Brings in:
Full changes:
https://github.com/alphagov/notifications-utils/compare/33.1.0...33.2.1
=> Bump utils to bring in changes to email HTML

app/models.py, app/organisation/organisation_schema.py, tests/app/organisation/test_rest.py
The admin app is passing these in as of https://github.com/alphagov/notifications-admin/pull/3038
=> Add extra fields to create/update organisation

requirements-app.txt, requirements.txt
Changes:
- https://github.com/alphagov/notifications-utils/compare/33.2.1...33.2.2
=> Bump utils to 33.2.2

app/dao/service_letter_contact_dao.py, tests/app/dao/test_service_letter_contact_dao.py, tests/app/service/test_rest.py
Otherwise you can’t archive it.
=> Dissociate letter contact blocks before archiving

app/__init__.py, tests/app/v2/test_errors.py
Handle werkzeug http errors separately. Also, improve the generic `Exception` handler to be more flexible when exceptions don't look like http errors.
note: because they're 405s the route isn't matched, so the v2 error handlers don't trip properly. this might be an issue because the internal endpoints expect a different return format. Might have to think about how to handle this.
=> handle 405s

app/clients/email/aws_ses.py, tests/app/clients/test_aws_ses.py
amazon SES only accepts domains encoded in punycode, an encoding that converts utf-8 into an ascii encoding that browsers and mailservers recognise.
We currently just send through emails as we store them (in full unicode), which means any rogue characters break SES and cause us to put the email in technical-failure. Most of these appear to be typos and rogue control characters, but there is a small chance that it could be a real domain (eg [https://🅂𝖍𝐤ₛᵖ𝒓.ⓜ𝕠𝒃𝓲/🆆🆃🅵/](https://🅂𝖍𝐤ₛᵖ𝒓.ⓜ𝕠𝒃𝓲/🆆🆃🅵/)).
We should encode to and reply-to-address emails as punycode to make sure that they can always be sent. The chance that anyone actually uses a unicode domain name for their email is probably pretty low, but we should allow it for completeness.
=> punycode encode emails before sending

app/celery/reporting_tasks.py, app/config.py, manifest.yml.j2, scripts/paas_app_wrapper.sh, tests/app/celery/test_reporting_tasks.py, tests/app/test_config.py
also remove references to unused statistics queue
=> Add reporting worker

app/dao/services_dao.py, app/service/rest.py, tests/app/dao/test_services_dao.py, tests/app/service/test_rest.py
Part of this story: https://www.pivotaltracker.com/story/show/167806249
=> Find services by partial name

app/service/rest.py
Find services by name feature was timing out for big collections of results.
=> Use serialize instead of marshmallow schema for lighter query

app/models.py, app/user/rest.py
This should make 'find users by email' query faster.
=> Leaner serialize for user model for displaying list of users

app/celery/reporting_tasks.py, app/config.py, app/dao/fact_notification_status_dao.py, tests/app/celery/test_reporting_tasks.py
to try and speed up overall time by parallelising the tasks.
=> split up reporting tasks in to separate tasks per day

app/celery/letters_pdf_tasks.py, tests/app/celery/test_letters_pdf_tasks.py
We are changing response format in template preview ( here: https://github.com/alphagov/notifications-template-preview/pull/367 ). We want API to handle both new and old response type for a smooth deploy of those changes.
Story ticket: https://www.pivotaltracker.com/n/projects/1443052/stories/168057359
=> Handle both new and old response type from template preview's sanitise method

app/letters/utils.py, tests/app/celery/test_letters_pdf_tasks.py
they just go in the test bucket's root
=> make sure test notifications don't get date subfolders

app/celery/letters_pdf_tasks.py, app/dao/notifications_dao.py, app/letters/utils.py, app/service/send_notification.py, tests/app/celery/test_letters_pdf_tasks.py, tests/app/dao/notification_dao/test_notification_dao_delete_notifications.py, tests/app/letters/test_letter_utils.py
rebased from https://github.com/alphagov/notifications-api/pull/2611
=> Use created at 2

migrations/versions/0306_letter_rates_price_rise.py, tests/app/dao/notification_dao/test_notification_dao_delete_notifications.py
<details>
<summary>Before</summary>
|     start_date      |      end_date       | sheet_count | rate | crown | post_class
|---------------------|---------------------|-------------|------|-------|------------
| 2016-03-31 23:00:00 | 2018-09-30 23:00:00 |           1 | 0.33 | f     | second
| 2016-03-31 23:00:00 | 2018-09-30 23:00:00 |           2 | 0.33 | t     | second
| 2016-03-31 23:00:00 | 2018-09-30 23:00:00 |           2 | 0.39 | f     | second
| 2016-03-31 23:00:00 | 2018-09-30 23:00:00 |           3 | 0.36 | t     | second
| 2016-03-31 23:00:00 | 2018-09-30 23:00:00 |           3 | 0.45 | f     | second
| 2016-03-31 23:00:00 |                     |           1 | 0.30 | t     | second
| 2018-06-30 23:00:00 | 2018-09-30 23:00:00 |           4 | 0.39 | t     | second
| 2018-06-30 …
=> letter rates go up by 5p as of 1st october 2019

Makefile
- Adds help text for freeze-requirements
- moves help text into correct position for upload-paas-artifact
=> Improve help comments for makefile

migrations/versions/0308_delete_loadtesting_provider.py, tests/app/dao/test_provider_details_dao.py, tests/app/provider_details/test_rest.py
requires https://github.com/alphagov/notifications-api/pull/2638
=> remove loadtesting from the database

app/celery/scheduled_tasks.py
Fix log message when a missing row is processed.
=> Add the missing format for the log message

app/notifications/rest.py, app/template/rest.py, requirements-app.txt, requirements.txt, requirements_for_test.txt
most of the bumps come from https://github.com/alphagov/notifications-api/pull/2648, except for marshmallow which broke some stuff so i left it out
=> Utils bump

app/dao/provider_details_dao.py
it was saying "from 40 to 50" when actually it changed from 50 to 40.
d'oh
=> fix log line for provider switch

app/__init__.py, app/dao/uploads_dao.py, app/upload/rest.py, tests/app/dao/test_uploads_dao.py, tests/app/upload/test_rest.py
We need a page on the admin app to show both uploaded csv files and uploaded letters (excluded uploaded letters from the api). 
This endpoint combines the data for jobs and uploaded letters in one resultset for the admin app. 
The admin PR is here: https://github.com/alphagov/notifications-admin/pull/3219
=> Uploads endpoint

requirements-app.txt, requirements.txt
Fixes a formatting bug to templates: alphagov/notifications-utils#679
=> Bring in utils version 36.3.1

requirements-app.txt, requirements.txt
=> Remove extraneous spacing characters from text messages

.coveralls.yml, Makefile, README.md, requirements_for_test.txt
=> Remove coveralls

app/dao/jobs_dao.py, tests/app/job/test_rest.py
Update the `dao_get_notification_outcomes_for_job` to return the stats from either the notification table or the ft_notification_status table.
Currently if you visit the job page and the job is older than the data retention the totals on the page are all wrong because this query gets the counts from the notification table. With this change the data should always be correct. It also eliminates the need for looking at data retention. If the job is new and nothing has been created yet (i.e. the job hasn't started yet) then the page should show the correctly because the outcomes are empty (as expected), once the notifications for the jobs are created the numbers will start going up.
=> Fix job counts for older jobs

app/dao/notifications_dao.py, app/template_statistics/rest.py, tests/app/dao/notification_dao/test_notification_dao.py, tests/app/dao/notification_dao/test_notification_dao_template_usage.py, tests/app/template_statistics/test_rest.py
A new endpoint to return the last date a template was used which means the old endpoint can be removed.
=> Remove unused methods.

app/user/rest.py, tests/app/user/test_rest.py
It was broken because of unhappy marshmallow schema and flag name
mismatch
=> Fix reset password flow

app/dao/fact_billing_dao.py, app/dao/fact_notification_status_dao.py
Some performance stats on these queries will come in handy when trying to optimise the queries.
=> Add statsd annotations for the fact table queries.

requirements-app.txt, requirements.txt
=> Bump utils to fix bleach security vulnerability

app/dao/notifications_dao.py, tests/app/dao/notification_dao/test_notification_dao_delete_notifications.py
Need to test the performance of this function, then we can call it from the task.
- Create a temporary table to insert ids of the desired rows, limit by 10K (might be too low).
- Insert into NotifcationHistory select from notification where id in temp table
- Delete from Notifications where id in temp table
- drop temp table
We should be able to iterate of this. The query stats for the query to create the temp table are very good, 17ms.
Next PR will call this code in the loop to delete/insert notifications.
=> Transaction to insert history and delete notifications.

app/v2/notifications/post_notifications.py, tests/app/v2/notifications/test_post_notifications.py
SQS fails if the message body is over 256kb. Normally our messages are quite small, but if we're using the new save-api-email task with an email that has a large body, we can get over that limit. If so, handle the exception and fall back to the existing code path (saving to the database and sending a deliver-email task, which only has a notification id.
=> if message too big to put on high volume queue then save to queue

app/celery/scheduled_tasks.py, tests/app/celery/test_scheduled_tasks.py
Please also review the content in the runbook
=> Add runbook link to resolve letters pending virus scan

app/celery/letters_pdf_tasks.py, tests/app/celery/test_letters_pdf_tasks.py
This task didn't have retries before, based on the assumption that if
the task failed it was likely to be due to a Boto error, so retrying
would not help because a file was probably not in the expected bucket.
During an incident with the database, we had some letters that were
stuck in the `pending-virus-check` state because this task failed.
This change adds retries to the task if there was an Exception that was
not a `BotoClientError`.
=> Add retries to process_sanitised_letter task

app/celery/nightly_tasks.py, tests/app/celery/test_nightly_tasks.py
=> Link to runbook

requirements-app.txt, requirements.txt, tests/app/dao/test_jobs_dao.py, tests/app/service/test_rest.py
bugs bug bugs!
also would have bugged out on single notification pages, except the button to cancel wasn't visible due to the bug on admin
=> fix timezone related cancel letter job bug

app/celery/nightly_tasks.py, app/config.py
Please read https://github.com/alphagov/notifications-api/pull/2788 and then review this commit by commit
=> Delete notifications older than retention

app/dao/notifications_dao.py, tests/app/notifications/test_process_client_response.py
Also degrade logs from error to warning
000 code means "no errors"
=> Take into consideration Firetext 000 code - no error. 

Makefile, app/status/healthcheck.py, app/version.py.dist, tests/app/status/test_status.py
Story ticket: https://www.pivotaltracker.com/story/show/170997266
Other PR in series: https://github.com/alphagov/notifications-admin/pull/3423
=> Update _status page - remove references to Travis

app/config.py, manifest.yml.j2, scripts/paas_app_wrapper.sh
Please review commit by commit.
=> Reduce concurrency and optimise prefetching behaviour for the celery reporting app

requirements-app.txt, requirements.txt
Fixes a bug with address validation.
=> Bump utils to 39.0.1

app/clients/document_download.py, app/v2/notifications/post_notifications.py, tests/app/v2/notifications/test_post_notifications.py
=> Add support for CSV files

app/commands.py, app/dao/services_dao.py
Hopefully fix the purge functional test data command. Please review commit by commit
=> Purge command

requirements-app.txt, requirements.txt
Adds delivery estimates for letters posted to Europe or the rest of the world.
=> Bump utils to 39.4.0

requirements-app.txt, requirements.txt
Brings in a bug fix for when a personalisation value is an empty list.
=> Bump utils to 39.4.3

app/delivery/send_to_providers.py, requirements-app.txt, requirements.txt
statsd timing should always be in seconds, not milliseconds
=> bump utils to fix statsd timing bug

app/authentication/auth.py, app/v2/notifications/post_notifications.py
Two new metrics:
wraps the first DB call of post notifications. This includes waiting to get a connection from the pool, and also making the actual request to the db to retrieve the service and api keys. (i'm not sure there's an easy way to separate these two things)
wraps parsing the v2 post notifications json parsing and schema validation. Shouldn't include any async code
=> add more prometheus metrics

app/celery/tasks.py
multi line strings don't handle indentation
=> remove whitespace from log line

app/notifications/receive_notifications.py, tests/app/notifications/test_receive_notification.py
As we gradually move from statsd to prometheus, we change the metric to
be a prometheus metric rather than statsd.
The change worth pointing out is that we have dropped the 'successful'
and 'failed' statuses from the metrics. I don't think it's useful to
have these statuses. It's very rare for an inbound message to fail when
we receive it and when it does, we raise an error and see it in our
logs. We aren't going to be looking at a graph of it as it's a rare
event, not typical behaviour that we want to monitor with a graph.
=> Add prometheus client metric for number of inbound text messages

app/serialised_models.py, requirements-app.txt, requirements.txt
Changes: https://github.com/alphagov/notifications-utils/compare/40.0.0...40.2.1
=> Bump utils to 40.2.1

app/celery/letters_pdf_tasks.py, app/dao/notifications_dao.py, tests/app/celery/test_letters_pdf_tasks.py
Split letters into zips based on postage:
- first class
- second class
- Europe
- the rest of the World
Also start adding postage to zips filenames.
=> Split letters into zips based on postage

scripts/check_if_new_migration.py
normally we check the app's status page to see if migrations need running. However, if the _status endpoint doesn't respond with 200, we don't necessarily want to abort the deploy - we may be trying to deploy a code fix that fixes that status endpoint for example.
We don't know whether to run the migrations or not, so err on the side of caution by re-running the migration. The migration itself might be the fix that gets the app working after all.
had to do a little song and dance because sometimes the response won't be populated before an exception is thrown
```
 leohemsted ~/dev/api $ export API_HOST_NAME=https://api.notify.works
 leohemsted ~/dev/api $ MIGRATIONS_TO_RUN=$(make check-if-migrations-to-run)  # this is what we run on concourse
 leohemsted ~/dev/api $ echo $MIGRATIONS_TO_RUN …
```
=> always run migrations if app is down

app/broadcast_message/rest.py, tests/app/broadcast_message/test_rest.py
=> set finishes_at correctly

app/__init__.py, requirements-app.txt, requirements.txt
Similar to https://github.com/alphagov/notifications-admin/pull/3510
Because of https://github.com/alphagov/gds_metrics_python/pull/8
=> Fix risk of uncaught exceptions due to gds metrics

migrations/versions/0325_int_letter_rates_fix.py
These were not taking timezones into account before.
=> Fix international letter rate start dates

app/config.py
What
----
Each environment to use isolated CBC stub so we can break preview without breaking staging or production
How to review
----
Review and merge https://github.com/alphagov/notifications-cbc-proxy/pull/7
=> Isolated CBC stubs

app/config.py
Turns redis off for cred rotation and also tidys up the config file for how we enable redis.
=> Turn redis off

app/config.py
Will need rebasing after first two commits have been merged
=> Turn redis back on

app/__init__.py
We don't want an exception while recording metrics to affect a user action. A KeyError exception was thrown today, that meant that a user say a 500, the action being performed was to download a document from the document-download-frontend app. By catching the error we prevent the user from seeing a 500 when a recording the connection metric fails.
=> Catch and log any exception thrown in the checkin event method.

app/celery/broadcast_message_tasks.py, requirements-app.txt, requirements.txt, tests/app/broadcast_message/test_rest.py, tests/app/celery/test_broadcast_message_tasks.py, tests/app/db.py
Fixes https://github.com/alphagov/notifications-utils/pull/784
Note, also is a breaking change of the utils, see
https://github.com/alphagov/notifications-utils/pull/769
but I don't believe it requires any changes on the API because of this
=> Bring in latest version of utils to fix link breaking bug

app/celery/tasks.py
The log message is not necessary, let's get rid.
=> Reduce logs

requirements-app.txt, requirements.txt
Changes: https://github.com/alphagov/notifications-utils/compare/42.2.0...42.2.1
=> Bump utils to 42.2.1

app/celery/scheduled_tasks.py, app/dao/jobs_dao.py, tests/app/dao/test_jobs_dao.py
For every missing row this was:
- downloading the CSV file from S3
- looping through every row in it until it found the one matching the index of the missing row 
`RecipientCSV` [implements `__getitem__`](https://github.com/alphagov/notifications-utils/blob/5ae0572d4188483fa140bccc128ecf80f3473000/notifications_utils/recipients.py#L78-L79) (which maybe it didn’t before) so we can create it once, then index the relevant row directly.
=> Improve efficiency of process missing rows task

app/celery/letters_pdf_tasks.py, tests/app/celery/test_letters_pdf_tasks.py
When letters are sent to DVLA, we will now put them in a separate ZIP file for each service, so that if there are printing issues due to bad files from one service, other services will hopefully not be affected by that.
EDIT: reintroducing letters from Insolvency Service back to DVLA moved to this PR: https://github.com/alphagov/notifications-api/pull/3006
=> Divide letters by service when putting in ZIP files

app/celery/tasks.py, app/config.py, app/v2/notifications/post_notifications.py, scripts/paas_app_wrapper.sh, tests/app/celery/test_tasks.py, tests/app/test_config.py, tests/app/v2/notifications/test_post_notifications.py
Reverts alphagov/notifications-api#3000
Deploy is failing on staging... reverting until I can figure out why.
=> Revert "Add a task to save-api-sms for high volume services."

app/cloudfoundry_config.py, tests/app/test_cloudfoundry_config.py
Reverts alphagov/notifications-api#3029
=> Revert "Specify sslmode in Cloud Foundry environment variables"

app/__init__.py, app/clients/__init__.py, app/clients/cbc_proxy.py, app/delivery/send_to_providers.py, tests/app/clients/test_cbc_proxy.py, tests/app/dao/test_provider_details_dao.py, tests/app/delivery/test_send_to_providers.py
A couple of refactors that were necessary before starting work on https://github.com/alphagov/notifications-api/pull/3035
=> Cbc proxy refactor

app/config.py
Reverts alphagov/notifications-api#3041
=> Revert "Turn on SMS and email stubs on staging"

app/celery/broadcast_message_tasks.py, app/dao/broadcast_message_dao.py, app/models.py, app/schemas.py, migrations/versions/0333_service_broadcast_provider.py, tests/app/celery/test_broadcast_message_tasks.py, tests/app/service/test_rest.py
We'll just insert manually in the DB for now since this is such a low volume thing.
returns via api so admin app can style appropriately.
=> Restrict providers per service

Makefile
a bug in cf-cli v6 caused us to get rate limited, one solution to this is to bump the version of cf-cli we're using to version 7. This has a few syntax changes as the old v3 commands become mainline.
To upgrade locally, grab the latest version from brew.
```sh
brew install cloudfoundry/tap/cf-cli@7
```
I've tested:
=> use cf-cli@v7 in makefile

Makefile
for reasons unknown, using a file descriptor no longer works on concourse (or in that docker container generally). It might be a change within cf-cli v7 vs v6.
Either way, it does't work, so use a temporary file. Clean up the temporary file afterwards.
If the command fails, the temporary file will still stick around, so I've added the file to the /tmp/ folder instead. it's full of secret
keys and things so if you do have a deployment error while running locally, you should make sure you clean up the file (make cf-rollback and make clean will both do this for you).
=> put manifest in tmp folder

app/celery/provider_tasks.py, app/clients/email/__init__.py, app/clients/email/aws_ses.py, tests/app/celery/test_provider_tasks.py, tests/app/clients/test_aws_ses.py
=> SES error logs

scripts/run_multi_worker_app_paas.sh
Reused the existing `ensure_celery_is_running` function to terminate the
script
Complementary of #3076
=> Add disk space check for sender worker

app/clients/cbc_proxy.py
Should have been `lambda_name` not `self.lambda_name`.
=> Fix incorrect log line

app/celery/provider_tasks.py, app/clients/sms/firetext.py, app/clients/sms/mmg.py, tests/app/celery/test_provider_tasks.py
=> Downgrade SMS provider request exceptions to warnings

migrations/versions/0345_move_broadcast_provider.py
Concourse had passed the tests before someone elses migration had beaten
me to getting merged. So I merged and got an error.
This should fix it
=> Bump the migration revision ID by 1

app/celery/scheduled_tasks.py, app/config.py, tests/app/celery/test_scheduled_tasks.py
=> Improvements to our letter checking tasks

app/broadcast_message/rest.py, app/celery/broadcast_message_tasks.py, app/clients/cbc_proxy.py, app/dao/broadcast_message_dao.py, app/models.py, manifest.yml.j2, tests/app/celery/test_broadcast_message_tasks.py, tests/app/clients/test_cbc_proxy.py, tests/app/db.py
unrevert #3101 and #3123. Also, add a couple of quality of life things I found helped when testing locally.
=> Bring back retry logic

app/config.py
Supporting infrastructure is ready for these two mnos
=> Turn on o2 and three mnos in prod

app/celery/broadcast_message_tasks.py, app/models.py, app/schemas.py, migrations/versions/0348_migrate_broadcast_settings_migrate_broadcast_settings.py, tests/app/celery/test_broadcast_message_tasks.py, tests/app/service/test_rest.py
https://www.pivotaltracker.com/story/show/176459886
This is the final piece of the puzzle and will complete the above pivotal ticket.
Relies on https://github.com/alphagov/notifications-admin/pull/3794 being merged first
=> Backfill services_broadcast_settings table

app/celery/letters_pdf_tasks.py, app/config.py, manifest.yml.j2, tests/app/celery/test_letters_pdf_tasks.py
DVLA would like to get the daily volume messages sent to a list of people.
=> Change DVLA_EMAIL_ADDRESS to a list

app/dao/broadcast_service_dao.py, tests/app/service/test_rest.py
=> Email auth broadcast bug

app/celery/scheduled_tasks.py, tests/app/celery/test_scheduled_tasks.py
We have a scheduled task that was checking for jobs still in progress.
We saw a case where a scheduled job was stuck in a `pending` status as a
result of an app shutting down. This changes the `check_job_status` task
so that it also checks for scheduled jobs which are still pending after
30 minutes.
[Pivotal story](https://www.pivotaltracker.com/story/show/177095265)
=> Check for incomplete pending jobs

app/notifications/receive_notifications.py
This could help identify issues with inbound SMS for a service.
=> Log service ID for invalid inbound SMS

migrations/versions/0350_update_rates.py
Downgrade script isn't necessary.
=> Add new SMS rate for April 1 2021.

app/celery/broadcast_message_tasks.py, tests/app/celery/test_broadcast_message_tasks.py
it's important to keep tabs on when these things leave our system. Sending a zendesk ticket that triggers a P1 is probably our simplest way of notifying the team when this happens (it's what we do with out of hours emergencies on the admin app too). We don't have any direct pagerduty integrations from the api app, but we already have the zendesk client hooked up.
After broadcasts go live, we may want to change this to a P2 (but even then, there's arguments for keeping it P1 to start with I think).
=> send a p1 when a broadcast goes out

app/__init__.py, app/celery/celery.py, tests/app/celery/test_celery.py
=> Small refactor for new Celery / StatsD code

app/v2/notifications/post_notifications.py, tests/app/v2/notifications/test_post_letter_notifications.py
Wrap the saving the notification and uploading the precompiled letter to s3 in a transaction.
If the upload to s3 fails the notification will not be saved to the
database.
=> Introduce transaction for precompiled letters

app/dao/fact_billing_dao.py, app/dao/inbound_sms_dao.py, app/dao/notifications_dao.py, app/dao/service_user_dao.py, app/dao/templates_dao.py, app/models.py, app/template/rest.py, app/user/rest.py, requirements-app.txt, requirements.txt, tests/app/dao/test_invited_user_dao.py, tests/app/dao/test_services_dao.py, tests/app/dao/test_templates_dao.py, tests/app/template/test_rest.py
Reverts alphagov/notifications-api#3219
=> Revert "Scheduled weekly dependency update for week 16"

app/cloudfoundry_config.py, app/dao/fact_billing_dao.py, app/dao/inbound_sms_dao.py, app/dao/notifications_dao.py, app/dao/service_user_dao.py, app/dao/templates_dao.py, app/models.py, app/template/rest.py, app/user/rest.py, requirements-app.txt, requirements.txt, tests/app/dao/test_invited_user_dao.py, tests/app/dao/test_services_dao.py, tests/app/dao/test_templates_dao.py, tests/app/template/test_rest.py, tests/app/test_cloudfoundry_config.py
The update to SQLAlchemy 1.4.10 has introduced some restrictions/changes. 
This PR resolves all errors and warnings. Details in each commit message.
=> SQLAlchemy update

requirements-app.txt, requirements.txt
Reverts #3235 due to https://github.com/benoitc/gunicorn/pull/2581
=> Revert "Bump eventlet from 0.30.2 to 0.31.0"

app/__init__.py, app/notifications/validators.py, app/v2/notifications/get_notifications.py, requirements-app.txt, requirements.txt, requirements_for_test.txt, tests/app/celery/test_scheduled_tasks.py, tests/app/dao/test_fact_notification_status_dao.py, tests/app/user/test_rest.py, tests/app/v2/notifications/test_post_letter_notifications.py, tests/app/v2/test_errors.py
Bump utils version which contains `~` as an invalid first character for a postal address.
=> Bump utils version for new invalid address character

app/service/service_broadcast_settings_schema.py, migrations/versions/0358_operator_channel.py, tests/app/celery/test_broadcast_message_tasks.py, tests/app/service/test_rest.py
Similar changes are needed to the admin app and the CBC proxy but I think this can be merged in any order as long as we don't try and use the operator channel ourselves until all have been done
=> Operator channel

app/models.py, tests/app/broadcast_message/test_rest.py
=> Broadcast status transition tests

app/notifications/validators.py, tests/app/notifications/test_validators.py
This has been properly tested locally with redis enabled.
=> Convert value from redis to an int.

app/config.py, manifest.yml.j2
https://www.pivotaltracker.com/story/show/179039225
Relates to: [1]
[1]: https://github.com/alphagov/notifications-credentials/pull/231
=> Switch to per-app secrets from internal APIs

app/commands.py
=> Remove redundant command to migrate area data

app/broadcast_message/rest.py, app/models.py, tests/app/broadcast_message/test_rest.py, tests/app/v2/broadcast/test_post_broadcast.py
Depends on: https://github.com/alphagov/notifications-admin/pull/4014
=> Remove remaining areas migration scaffolding

app/commands.py, tests/app/conftest.py, tests/app/db.py, tests/app/test_commands.py
Previously I had to handcraft some SQL to give myself access to a
broadcast service I created locally. I've done this enough times
that I think it's worth automating.
=> Make it easy to develop with broadcast services

app/celery/celery.py, app/celery/letters_pdf_tasks.py, app/config.py, app/v2/notifications/post_notifications.py, requirements-app.txt, requirements.txt, scripts/paas_app_wrapper.sh, tests/app/v2/notifications/test_post_notifications.py
https://www.pivotaltracker.com/story/show/180017131
=> Upgrade to Celery 5

app/celery/celery.py, tests/app/celery/test_celery.py
https://www.pivotaltracker.com/story/show/180213914
This is a prerequisite to enabling task argument checking -
a Celery 4+ feature we disabled as it's not compatible with
the old approach we had here. See the commit message for more
details about how the new approach works.
I've left a single line of code that means we still cope with
in-flight tasks that were created with the old approach. We'll
lose Request ID traces for those tasks, but I don't think that's
a big issue - it's a nice-to-have feature.
=> Move Celery task Request ID injection into headers

app/celery/celery.py
https://www.pivotaltracker.com/story/show/180213914
See the commit messages for details. This should be especially 
useful for the log we get if the task fails.
=> Extend request tracing to cover Celery logs

scripts/paas_app_wrapper.sh
https://www.pivotaltracker.com/story/show/180116935
This got missed in [1].
[1]: https://github.com/alphagov/notifications-api/pull/3355/commits/9e9091e980c6c2a10a47cc7c443ecadbcaf29512
=> Reduce concurrency to match number of CPUs

app/dao/notifications_dao.py
Update the query to only return the count from the table since that is all we care about.
https://www.pivotaltracker.com/story/show/180262357
=> Small update to query to reduce load on the task.

app/dao/notifications_dao.py, tests/app/dao/notification_dao/test_notification_dao_delete_notifications.py
TLDR: Don't return as many services, and only return their IDs and not the whole service objects.
Context:
the delete notifications nightly task has been taking longer and longer, and to delete all three notification types in sequence it now takes up to 8 hours.
This is because we were retrieving all services, loading them into memory on the worker, and then trying to delete notifications for each service in turn.
While it does use a fair chunk of IOPS/CPU on our postgres db, we're not anywhere close to capacity on those (20% CPU, 4k IOPS out of 30k max)[1]
The real issue appears to be that the task is CPU bound on the periodic worker - we see the worker spike up to 100% CPU regularly across the whole 3am-11am period.
We also noticed that for each notification type the task first …
=> reduce number of services we try and delete notifications for

app/dao/notifications_dao.py, app/service/rest.py, tests/app/service/test_rest.py
https://www.pivotaltracker.com/story/show/179338377
There is some room for more potential refactoring after this, for example
- to fix the TODO comment
- to rename `count_pages` to `include_pagination`
But I want to first 
- get this reviewed to validate the approach I'm taking
- get this released to confirm it does indeed improve performance on this endpoint
=> Pagination approach change for `get_notifications_for_service`

requirements.in, requirements.txt
https://www.pivotaltracker.com/story/show/177535141
This includes performance improvements for RecipientCSV, which may
reduce the processing time in some edge cases - this depends on if
the Admin app rejects CSVs with these edge cases.
=> Bump utils to 51.2.1

app/dao/notifications_dao.py, app/service/rest.py, app/utils.py, tests/app/dao/notification_dao/test_notification_dao.py, tests/app/service/test_rest.py
Near identical to https://github.com/alphagov/notifications-api/pull/3391
=> Improve response times for figuring out pagination links by doing it ourselves rather than use Flask-Sqlalchemy

app/delivery/send_to_providers.py, tests/app/delivery/test_send_to_providers.py
At the moment, when we are processing and sending an SMS we open
a DB connection at the start of the celery task and then close it
at the end of the celery task. Nice and simple.
However, during that celery task we make an HTTP call out to our
SMS providers. If our SMS providers have problems or response times
start to slow then it means we have an open DB connection sat waiting
for our SMS providers to respond which could take seconds. If our
SMS providers grind to a halt, this would cause all of the
celery tasks to hold on to their connections and we would run out
of DB connections and Notify would fall over.
We think we can solve this by closing the DB session which releases
the DB connection back to the pool.
Note, we've seen this happen in staging during load testing if our
SMS …
=> Close DB connection whilst making HTTP to SMS providers

app/celery/reporting_tasks.py
This relates to the performance optimisation work we're doing [1].
Before optimising the task, it's worth asking if we can do less -
the comment explains why it has to be this way.
Some references to back up the comment:
- We do status updates in either table [2].
- We don't allow duplicate receipts for emails [3].
- We don't allow duplicate receipts for SMS [4].
- We don't expect duplicate receipts for letters.
This is something we would need to revisit if we want to support
additional status updates - we could reject based on the age of the
notification, rather than the status.
[1]: https://github.com/alphagov/notifications-api/pull/3417
[2]: https://github.com/alphagov/notifications-api/blob/20ead82463a9df1ce3a6325d103a00306609f5fb/app …
=> Add comment to explain status aggregation approach

app/models.py
This is identical to the declaration a few lines above.
=> Remove duplicate declaration for reference column

app/user/rest.py, tests/app/user/test_rest.py
This follows the pattern for invite emails where the admin app tells the API which domain to use when generating the link.
This will starting working once this admin change is merged:
It won’t break anything if it’s merged before the admin change.
=> Allow admin app to specify domain for password reset

app/dao/notifications_dao.py, tests/app/celery/test_letters_pdf_tasks.py, tests/app/dao/notification_dao/test_notification_dao.py
Can't see these being used anywhere so lets get rid of them
=> Remove unused functions

app/celery/reporting_tasks.py
=> Fix task name and action in status task logs

app/celery/nightly_tasks.py, app/dao/services_dao.py, app/dao/uploads_dao.py, requirements.in, requirements.txt, requirements_for_test.txt
This brings in the safer and more minor dependencies from https://github.com/alphagov/notifications-api/pull/3475 so that we're not bumping everything in one go.
=> Upgrade some dependencies

app/dao/fact_billing_dao.py, app/platform_stats/rest.py, tests/app/dao/test_ft_billing_dao.py, tests/app/db.py, tests/app/platform_stats/test_rest.py
Daily volumes report: total volumes across the platform aggregated by whole business day (bst_date)
Volumes by service report: total volumes per service aggregated by the date range given.
NB: start and end dates are inclusive
=> Report for total notifications sent per day for each channel.

app/dao/annual_billing_dao.py, tests/app/dao/test_annual_billing_dao.py
Update the map for determine the free allowance (aka: free SMS fragments) for services.
=> Free allowance rates for 2022

requirements.in, requirements.txt, requirements_for_test.txt
This bumps the dependencies which don't need code changes in order to fix. Two of these are major version bumps, but I can't see anything in them which should affect our code.
=> Bump straightforward dependencies

migrations/versions/0370_fix_apr_2022_sms_rate.py
this will update about 80-90k rows in ft billing.
Can be merged whenever - before or after. as long as it's not deploying while we're creating ft billing rows, it should be fine
=> add revision to fix apr rate

tests/app/user/test_rest.py
an API build failed because one of the tests expected the database to be empty, but it actually wasn't. This is probably because another test run earlier on that worker did not clear down properly. i'm not 100% sure which test this was but i've fixed a couple of tests in this file. I've also changed those particular tests to delete any users at the beginning of the test.
I took the opportunity to refresh all of these tests to ensure they all correctly tear down, and also use the more modern admin_request fixture ratehr than the old client one that required us to specify headers and do json parsing etc.
=> clean up user tests

app/events/rest.py, app/job/rest.py, app/notifications/rest.py, app/provider_details/rest.py, app/schemas.py, app/serialised_models.py, app/service/rest.py, app/service_invite/rest.py, app/template/rest.py, app/upload/rest.py, app/user/rest.py, requirements.in, requirements.txt, tests/app/dao/test_templates_dao.py, tests/app/delivery/test_send_to_providers.py, tests/app/service/test_rest.py, tests/app/template/test_rest.py, tests/app/test_schemas.py, tests/app/user/test_rest.py, tests/app/v2/notifications/test_post_notifications.py
See commits for details, and the [upgrade guide](https://marshmallow.readthedocs.io/en/stable/upgrading.html) since there were lots of breaking changes.
=> Upgrade Marshmallow to version 3

app/dao/services_dao.py, tests/app/dao/test_services_dao.py
The tests were previously covering a shared function that's now
only used once, so I've inlined it and merged the tests together
with a common naming that's consistent with the code under test.
=> Remove redundant DAO function / consolidate tests

app/dao/organisation_dao.py, app/organisation/rest.py, tests/app/dao/test_organisation_dao.py, tests/app/organisation/test_rest.py
The new endpoint checks that an org has no users, pending invited users,
or services (in any state). If it does, admin will display an error message
so that the platform admin user archiving the org can manually reassign
/ remove the team members and services.
Assuming that the org can be archived, we remove its email branding,
letter branding and domains, and set its state to `active=False`.
[Pivotal story](https://www.pivotaltracker.com/story/show/178519743)
=> Add endpoint to archive an organisation

app/platform_stats/rest.py
Part of https://github.com/alphagov/notifications-api/pull/3548 that we can split out.
=> Remove unused route

app/aws/s3.py, app/dao/annual_billing_dao.py, app/dao/complaint_dao.py, tests/app/dao/test_complaint_dao.py
I can't see these being used anywhere so think they are good to delete and their related tests
Review commit by commit for an easier review
=> Remove a few unused functions

Makefile
Something seems to be going wrong when building droplet from concourse,
need to investigate further
=> Revert droplet usage for preview and staging

app/config.py
https://www.pivotaltracker.com/story/show/182662326
=> Update resting points as requested

app/notifications/validators.py, tests/app/v2/notifications/test_post_notifications.py
This should be merged on friday 29th, along with some documentation changes that will be coming to a client repo near you shortly
=> allow Document download by email only

app/authentication/auth.py
This will hopefully let us get some more useful information to share with AWS about why some requests to the API seem to be reaching/transitting CloudFront slowly.
Logs something like:
Error: Your system clock must be accurate to within 30 seconds(you: 1667977240, us: 1667977272) [X-Amz-Cf-Id: oMuw1qhJrBzOpJcRhhavISwB950YwYTubdTAVGuX2iBPWUNmBMqN0w==]
We can then share the cf-id with AWS.
=> Log iat/epoch time and cf request id

migrations/versions/0383_webauthn_cred_logged_in_at.py
need to figure out an automated way to handle this or something
=> fix migrations

templates/tasks/scheduled_tasks/new_email_brandings.html, tests/app/celery/test_scheduled_tasks.py
=> Add guidance to the daily branding pool review ticket

app/celery/tasks.py, app/service/send_notification.py, tests/app/celery/test_tasks.py, tests/app/service/send_notification/test_send_one_off_notification.py, tests/app/service/send_notification/test_send_pdf_letter_notification.py
We updated the order of arguments to this call, but missed some code paths. Let's update them, and update the tests to assert on the args.
=> Fix cache limit checking, update tests

requirements.in, requirements.txt
This pulls in the new cached bank holidays
=> Bump utils to 61.0.0

app/letter_branding/letter_branding_rest.py, app/letter_branding/letter_branding_schema.py, app/models.py, migrations/.current-alembic-head, migrations/versions/0394_letter_branding_cols.py, tests/app/letter_branding/test_letter_branding_rest.py
This adds new nullable columns to the letter branding table for auditing and allows them to be used when updating and creating a brand:
* created_by_id
* created_at
* updated_by_id
* updated_at
=> Add new columns to letter branding table

migrations/.current-alembic-head, migrations/versions/0397_drop_research_mode.py
=> drop research mode column

app/models.py, app/schemas.py
To be followed up by a separate deployment with the migration.
=> Remove message limit from python code

app/commands.py, app/dao/fact_billing_dao.py, tests/app/dao/test_fact_billing_dao.py
This command no longer matched how we populate the ft_billing table in the overnight task. If no service_id was provided, it would use the `get_service_ids_that_need_billing_populated` function to find out which data to populate the table with. However, this only looks in notification_history, and we now look in the notifications table too.
This changes the dao function that is used to delete the billing data for a day so that the service_ids argument is optional, which means we no longer need to use `get_service_ids_that_need_billing_populated`.
=> Update `rebuild_ft_billing_for_day` command

app/aws/s3.py, app/celery/letters_pdf_tasks.py, app/celery/nightly_tasks.py, app/celery/research_mode_tasks.py, app/celery/scheduled_tasks.py, app/commands.py, app/config.py, app/letters/utils.py, app/service/send_notification.py, tests/app/celery/test_letters_pdf_tasks.py, tests/app/celery/test_nightly_tasks.py, tests/app/celery/test_provider_tasks.py, tests/app/celery/test_research_mode_tasks.py, tests/app/dao/notification_dao/test_notification_dao_delete_notifications.py, tests/app/letters/test_letter_utils.py
To be consistent with the changes to admin.
Also removes a duplicated env var
=> Rename S3 bucket env vars

app/celery/scheduled_tasks.py, tests/app/celery/test_scheduled_tasks.py
So that we don't get emails on Friday afternoons about this.
https://gds.slack.com/archives/CADFJBDQU/p1681203805597679
=> Delay DWP due date

entrypoint.sh
modified:   entrypoint.sh
Modified entrypoint.sh to cater for all queues
=> Added queues to entrypoint.sh

requirements.in, requirements.txt
This will ensure we always get the correct dependencies installed.
=> Include extras for sentry

entrypoint.sh
We need to have log messages of any error to bug fix the service-worker service.
=> Remove all  2> /dev/null

app/dao/organisation_dao.py, app/organisation/rest.py, tests/app/organisation/test_rest.py, tests/app/service/test_rest.py
This will let us update the platform-admin search page to lookup organisations.
=> Add an admin search endpoint for organisations

entrypoint.sh
This way the entrypoint command and the ECS service name will match
=> Removed the work "delivery-" from workers

requirements.in, requirements.txt, tests/app/notifications/test_process_notification.py
* Update international billing rates for new text message costs from MMG.
* Add a few more mappings to the list of countries for postage
=> Bump utils to 65.2.0

Makefile, docker/Dockerfile
Follows in the footsteps of https://github.com/alphagov/notifications-template-preview/pull/752 and https://github.com/alphagov/notifications-antivirus/pull/121.
I've tested this a bit locally and it seems good ... but validating it _actually_ works on ECS, I'm not sure how to do yet...
---
Corresponding CI PR: https://github.com/alphagov/notifications-aws/pull/1595
=> Refactor dockerfile

app/celery/tasks.py
Just some extra logs to help us debug when response files from DVLA are not processed correctly
=> Additional logging for processing DVLA response files

gunicorn_config.py
This follows
https://github.com/alphagov/notifications-admin/pull/4826
=> Increase gunicorn keepalive to 90 seconds

app/models.py, tests/app/organisation/test_rest.py, tests/app/template_folder/test_template_folder_rest.py
Reverts alphagov/notifications-api#3882
=> Revert "Resolve an n+1 queries on endpoint"

manifest.yml.j2
Reverts alphagov/notifications-api#3883
=> Revert "Switch the db migration task to use cflinuxfs4"

app/clients/letter/dvla.py, tests/app/clients/test_dvla.py
10 characters for postcode
255 for country
45 for all other lines
we don't use this address anywhere so it's okay if things are truncated, as we've already created the PDF with the full address at this point
=> truncate address lines to match dvla's json schema

app/dao/services_dao.py, app/models.py, app/schemas.py, app/serialised_models.py, app/service/rest.py, tests/app/conftest.py, tests/app/dao/test_services_dao.py, tests/app/dao/test_templates_dao.py, tests/app/db.py, tests/app/service/send_notification/test_send_notification.py, tests/app/service/test_rest.py, tests/app/template/test_rest.py, tests/app/v2/notifications/test_post_notifications.py
1. ~~add new column as nullable~~ (https://github.com/alphagov/notifications-api/pull/3865)
2. ~~write new values to both new and old column~~ (https://github.com/alphagov/notifications-admin/pull/4824)
3. ~~migrate old data. add unique and not null constraints.~~ (https://github.com/alphagov/notifications-api/pull/3881)
4. ~~use new column~~ (https://github.com/alphagov/notifications-api/pull/3868)
5. ~~delete references to old column in admin~~ (https://github.com/alphagov/notifications-admin/pull/4848) 
6. **delete references to old column in code** 
7. drop old column
it shouldn't break anything, but we'll probs want to clear the cache _after_ this is deployed
=> Remove email from

README.md
We are upgrading the postgres version on Notify to 15. This changes the documentation on this repo to reflect that
=> Change README.md to use new postgres version 15

app/celery/scheduled_tasks.py, app/config.py, tests/app/celery/test_scheduled_tasks.py
none of these work anymore, and they'll just produce error logs
=> remove periodic broadcast tasks

app/celery/nightly_tasks.py, app/config.py, app/dao/notification_history_dao.py, tests/app/celery/test_nightly_tasks.py, tests/app/dao/test_notification_history_dao.py
This has been replaced by
https://github.com/alphagov/notifications-api/pull/3921
=> Remove deletion of notification history by quarter task

migrations/.current-alembic-head, migrations/versions/0426_drop_email_from.py
it's no longer used anywhere 🎉 
this has taken a while to get to
=> drop email-from

migrations/.current-alembic-head, migrations/versions/0427_letter_rates_from_1_11_23.py
To review:
- compare prices with [the spreadsheet](https://docs.google.com/spreadsheets/d/1ANZavv1jzbT8lvtiMRgOy04Oe4MRGocKnMMwkWpZkO8/edit?usp=sharing)
- check that migration works ok for you (it does for me)
=> New letter rates active from 1st November 2023

app/models.py
quick and simple optional code tidyup. it was only used in one place (ProviderDetailsHistory), and could be simpler anyway
pros: gets rid of some lines of code
cleans up some cruft (a debug log that we'd never hit)
cons: doesn't actually do anything to make how we manage ProviderDetailsHistory more closely aligned with how we manage Service or Template - two other history classes.
the columns are still duplicated between the two models with the differences (some default values, and a primary key on `version` on the history table) are quite hard to spot amongst the repeated lines
=> remove HistoryModel

app/template/template_schemas.py, tests/app/template/test_rest.py
The previous schema had a flaw: if `letter_languages` was not passed, the schema was unintentionally requiring `letter_welsh_subject` and `letter_welsh_content` to be null values, if present.
The new schema allows any of the following options:
* The three "letter" language keys are missing
* `letter_languages` to be missing, in which case the pair of `letter_welsh_subject` and `letter_welsh_content` can be present, together, with matching data types (both null or both strings).
* `letter_languages` to be `english`, then both `letter_welsh_subject` and `letter_welsh_content` must be present and null
* `letter_languages` to be `welsh_then_english`, then both `letter_welsh_subject` and `letter_welsh_content` must be present and strings
=> Fix POST template schema for bilingual letters

app/delivery/send_to_providers.py, tests/app/delivery/test_send_to_providers.py
the point of this whole piece of work :facepalm:
=> use custom email sender name if provided

app/models.py
Keep all of the column declarations together so they're easier to see in a list. Follow those with hybrid properties, then any other model properties.
=> Shift properties down below list of columns

app/commands.py
Replaces #3952, an attempt to do this in migrations.
https://trello.com/c/cAARpLJ2/501-fix-numerics-which-were-converted-to-6dp-by-dms
These commands update the numerics in `Notification`, `NotificationHistory` and `FactBilling` to their `min_scale` following the DMS migration.
For `FactBilling` and `Notification`, performs updates in blocks (partitioned on a pseudorandom uuid) to avoid locking any whole tables (or even one specific time-period) at once.
For `NotificationHistory`, partition the blocks on `created_at` as that is more closely correlated to the physical layout of the table, and accesses to it (outside the periodic update tasks) aren't particularly clustered around any one point in time that we should avoid locking.
=> commands: add commands for updating numeric scale for large tables

migrations/env.py
https://trello.com/c/35GEi5aB/548-remove-risk-of-api-code-being-deployed-to-production-before-the-alembic-migrations-have-been-applied
See inline comment for more detail.
The `lock_timeout` setting needs to be moved to after this lock is taken as we'd rather this didn't apply to the advisory lock itself - there's no harm in making a migration process that hasn't taken any other locks out yet wait.
I've tested this by deliberately spawning a duplicate migration container running a dummy slow migration (`sleep(60)`) and ensuring that the two attempts queue up after each other and the second one doesn't find it needs to do anything.
Any other way of testing anyone can think of?
=> migrations: use advisory lock to prevent concurrent migration processes

app/organisation/invite_rest.py, app/user/rest.py, tests/app/user/test_rest.py
See individual commits for details
=> Get rid of three `TODO` comments by removing some unneeded code

app/commands.py
https://trello.com/c/cAARpLJ2/501-fix-numerics-which-were-converted-to-6dp-by-dms
This was too slow to be worth it, so let's not bother and save ourselves fragmenting the tables in the process.
=> Revert "commands: add commands for updating numeric scale for large tables"

migrations/.current-alembic-head, migrations/versions/0439_intl_letters_jan_24.py
Happy new year 😩
doesn't depend on, but should be merged around
* https://github.com/alphagov/notifications-admin/pull/4958
=> add new international letter rates

docker/Dockerfile
copying the file version.py that was not present in the concourse_tests layer
=> copy version.py

app/dao/services_dao.py
Changes the data access object to streamline the background sql for the live_services.csv, this should make it faster than the gunicorn timeout of 30s
=> sql change to speed it up

app/models.py, migrations/.current-alembic-head, migrations/versions/0441_add_unsubscribe_link.py, tests/app/dao/notification_dao/test_notification_dao.py
As a new column in notifications table. Also add a constraint that forces the link to be null for non-email notifications.
=> Add unsubscribe link to our models and database

app/dao/notifications_dao.py
Background: When deleting templates, we find out when it was most recently used so that we can inform the user.
Problem: This query can be extremely slow, sometimes timing out. A couple of random picks showed it to be slow when templates haven't been used recently at all (so it needs to search through lots of notifications to see if there's a match so it can find the most recent created_at timestamp)
Reckon: templates that people want to delete probably haven't been used recently most of the time (or they wouldn't want to delete them).
Theory: if we search using the `ix_notifications_template_id` index just to see if any row exists at all, we can bypass this query for a decent chunk of template delete queries, thus improving performance.
=> try and improve template delete performance

app/clients/email/aws_ses.py, app/clients/sms/__init__.py
This will make it a bit easier to pick out extreme cases for investigation.
We shouldn't have to do this kind of ad-hoc thing once we have observability sorted out properly.
=> SmsClient, AwsSesClient: emit success logs with structured fields

app/constants.py, migrations/.current-alembic-head, migrations/versions/0442_add_new_service_permission.py
Adding this to the database and constants. Not much to say.
=> Adding new permission for sending SMS to UK landlines

app/notifications/receive_notifications.py, tests/app/notifications/test_receive_notification.py
Reverts alphagov/notifications-api#4062
=> Revert "send inbound sms tasks to service-callback queue"

tests/app/user/test_rest.py
This makes minor changes to test all the fields that are returned when a User is serialized. It also tests that more user properties can be updated.
=> Add test coverage for getting a user

app/schemas.py
Following advice from the internet to avoid flaky errors we're seeing occasionally in our unit tests[^1]
[^1]: https://github.com/marshmallow-code/flask-marshmallow/issues/44#issuecomment-1980157832
=> set sqla_session on marshmallow schemas

app/__init__.py, app/models.py, app/protected_sender_id/protected_sender_schema.py, app/protected_sender_id/rest.py, migrations/.current-alembic-head, migrations/versions/0459_tbl_for_protected_senders.py, scripts/README.md, scripts/process_sender_names.py, tests/app/protected_sender_id/test_rest.py
This has
1) A script for processing csvs from BT to give insert statements 
2) A database table called protected_sender_ids that holds a list of
sender_ids.
3) A protected_sender_id/check get endpoint that can be used by admin to
check whether a sender_id is protected (true, i.e. in the list) or not.
4) Tests for that endpoint
=> Adding protected Sender ids, scripts, DB tbl endpoint and test

docker/Dockerfile, migrations/.current-alembic-head, migrations/versions/0460_letter_rates_july_2024.py
https://trello.com/c/LTcHxYV9/819-update-new-letter-prices-on-notify
This adds the new rates for first and second class letters that will be valid from 1 July 2024. There will be no changes to the international letter prices.
=> Migration to add new first and second class letter rates

tests/app/test_model.py
=> Fix failing test - pass in date dynamically into value in test

app/dao/unsubscribe_request_dao.py, app/one_click_unsubscribe/rest.py, app/service/rest.py, tests/app/service/test_rest.py
This PR builds the endpoints needed for the work done in this [PR](https://github.com/alphagov/notifications-admin/pull/5139).
=> Add unsubscribe request reports summary endpoints

app/commands.py, app/functional_tests_fixtures/__init__.py, entrypoint.sh, requirements_for_test.txt, tests/app/celery/test_letters_pdf_tasks.py, tests/app/celery/test_provider_tasks.py, tests/app/clients/test_dvla.py, tests/app/dao/notification_dao/test_notification_dao_delete_notifications.py, tests/app/functional_test_fixtures/test_functional_test_fixtures.py, tests/app/letters/test_letter_utils.py
[Trello Card](https://trello.com/c/GA0r5iXd/766-get-functional-tests-to-work-in-dev-env-bootstrap-an-empty-database)
What
----
Upgrade moto to 5.0.11.
Add flask task to create the functional test fixtures
It will output a file (and/or write to ssm) at the end of the task with all the variables required to run the functional tests.
Why
----
This will allow us the automate the dev environments setup so they are ready for the functional tests.
It will also work for local environment setup to run the functional tests.
=> Add flask task to create the functional test fixtures

app/notifications/process_notifications.py, app/notifications/validators.py, requirements.in, requirements.txt, tests/app/notifications/test_process_notification.py, tests/app/v2/notifications/test_post_letter_notifications.py
Awaiting https://github.com/alphagov/notifications-api/pull/4136 approval and merge prior to review.
(will also do a squash/rebase once this is merged)
=> Landline validation feature flagged sms

app/functional_tests_fixtures/__init__.py
[Trello](https://trello.com/c/a4q9X0Tf/850-carry-out-integration-testing)
What
----
Functional test fixture fixes after additional testing:
- Set postage correctly for functional test fixtures
- Add contact_link to functional test fixtures service. Required for document download tests
=> Functional test fixture fixes

tests/app/dao/test_unsubscribe_request_dao.py, tests/app/db.py, tests/app/service/test_rest.py
For lots of objects we create reguarly in tests we have a little helper function that:
- makes the code less verbose
- handles creating the associated objects automatically
We didn’t have this for unsubscribe requests. Now we do.
I’ve also modified some of the tests to assert against actual hard values, rather than results of queries. This makes them less brittle and harder to hide bugs in.
=> Rewrite unsubscribe requests tests to use a helper

app/__init__.py
https://trello.com/c/AGXtyaAe/887-disable-parallel-query-by-default
See extensive inline comment.
This has absolutely no test coverage, same as all of the sqlalchemy engine hooks in the unit tests.
I made an attempt at making the hooks work for the unit tests, but the result is ugly and has a number of caveats which would add to the complexity of the fixtures.
=> connection pool: effectively disable parallel query by default

app/service/rest.py
After it has been split into two endpoints:
get_all_notifications_for_service() AND
get_all_notifications_for_service_for_csv()
=> Remove redundant code from get_all_notifications_for_service()

app/celery/reporting_tasks.py
This should give the database some relief while still not delaying things more than max 50 minutes.
=> create_nightly_billing: stagger `_for_day` tasks by 5 minutes each

tests/app/celery/test_nightly_tasks.py
=> nightly notification deletion: make tests more tolerant of iteration order

app/clients/sms/firetext.py
Reverts alphagov/notifications-api#4214
Merge this in a day or so.
=> Revert "Revert "FiretextClient: use persistent requests session""

.pre-commit-config.yaml, pyproject.toml, requirements.in, requirements.txt, requirements_for_test_common.txt
Incorporating https://github.com/alphagov/notifications-utils/pull/1160 & https://github.com/alphagov/notifications-utils/pull/1161
=> notifications-utils: 87.0.0 -> 88.0.1

tests/app/dao/notification_dao/test_notification_dao.py
now we don't order, it randomly got through in PR and then failed on the main build as it was trying to check order. lets make this a bit simpler and just one test now that the fn is simpler
=> fix unit test to not care about ordering

app/service_invite/rest.py, tests/app/service_invite/test_service_invite_rest.py
to match https://github.com/alphagov/notifications-admin/pull/5284
=> update request-again URL for join a service

app/dao/fact_notification_status_dao.py
We don't need to join to `Template` until after the aggregation is done, which reduces the size of the join and means we don't have to include all the desired columns from Template in `group_by`. This should be a bit faster and is less likely to confuse the planner.
=> `fetch_notification_status_for_service_for_today_and_7_previous_days`: perform `Template` join late

app/service_invite/rest.py, tests/app/service_invite/test_service_invite_rest.py
Update approve or refuse link for email2 (https://docs.google.com/document/d/15jG6UW7aoCQ15E8uTVfpMG_lEYtCbJueEg-ww2O-6Nc/edit?tab=t.0#heading=h.jwc26ypjgczj)
=> Update approve or refuse link for join service request email2

.pre-commit-config.yaml, app/dao/notifications_dao.py, app/inbound_sms/rest.py, app/models.py, app/notifications/process_notifications.py, app/notifications/receive_notifications.py, app/notifications/validators.py, app/schemas.py, app/user/rest.py, app/utils.py, app/v2/notifications/post_notifications.py, pyproject.toml, requirements.in, requirements.txt, requirements_for_test_common.in, tests/app/delivery/test_send_to_providers.py, tests/app/notifications/test_process_notification.py, tests/app/service/send_notification/test_send_one_off_notification.py, tests/app/service/test_service_guest_list.py, tests/app/test_schemas.py, tests/app/user/test_rest.py
Reverts validation removal changes until we can fix TV numbers bug
=> Revert remove old phonenumber validation

scripts/test_sql_migration_downgrade.sh
we were manually definining the SQLALCHEMY_DATABASE_URI in the script as it needs to operate on a specific db name. However, this meant we were ignoring any local config, which may contain noteworthy modifications to the db URI: what URL/port it's on, or username/password details.
This commit changes so that if SQLALCHEMY_DATABASE_URI is not specific, we'll use `postgresql://postgres:postgres@localhost/migration_test` as before (but with explicit postgres:postgres username/password). If a SQLALCHEMY_DATABASE_URI is passed in, then we'll take that postgres server, but replace the database name with `migration_test` to ensure we're not splatting over someone's regular or test notify database.
=> made sqlalchemy database uri modifiable in test_downgrade

app/dao/notifications_dao.py
Performing a separate fetch of the reference notification and specifying its `created_at` literally allows the planner to see the value and make adaptations appropriately.
Also ensure we're only allowing reference notifications from the same service lest someone use it to probe for things outside their service.
Maintain existing behaviour if reference notification is not found
=> `get_notifications_for_service`: use literal timestamp for `older_than` clause

scripts/test_sql_migration_downgrade.sh
you cant delete the db you're currently connected to
```
❯ scripts/test_sql_migration_downgrade.sh
POSTGRES_SERVER_URI=postgresql://postgres:postgres@localhost/
MIGRATION_TEST_DATABASE_URI=postgresql://postgres:postgres@localhost/migration_test
❯ SQLALCHEMY_DATABASE_URI="postgres://un:pw@db:1234/db_name" scripts/test_sql_migration_downgrade.sh
POSTGRES_SERVER_URI=postgres://un:pw@db:1234/
MIGRATION_TEST_DATABASE_URI=postgres://un:pw@db:1234/migration_test
❯ SQLALCHEMY_DATABASE_URI="postgres://un:pw@db:1234/" scripts/test_sql_migration_downgrade.sh
POSTGRES_SERVER_URI=postgres://un:pw@db:1234/
MIGRATION_TEST_DATABASE_URI=postgres://un:pw@db:1234/migration_test
```
=> when creating/dropping db connect with default db

gunicorn_config.py
This runs eventlet's adapted profiling code for the 100ms post-request wait to sample what this particular python process is doing - during a degradation there are usually other requests in flight being slowed down by _something_. So while this will not capture useful information about why the triggering request was slowed down, it should hopefully provide information about the cause of the following requests being held up.
=>  gunicorn: add post-request profiling to `NOTIFY_GUNICORN_DEBUG_POST_REQUEST_LOG_THRESHOLD_SECONDS`

gunicorn_config.py
If I'm going to need to use the sharp knife let's make sure I get the information I need
=> gunicorn post-request profiling: add some more useful information

app/celery/nightly_tasks.py, app/dao/notifications_dao.py, tests/app/celery/test_nightly_tasks.py, tests/app/dao/notification_dao/test_notification_dao_delete_notifications.py
When deleting the test letters from the Notifications table as part of the `delete-notifications-for-service-and-type` task we weren't deleting the test files from S3. We do delete the files in S3 for real letters, so not deleting the files for test letters appears to have been an oversight.
This copies the approach we take for real letters and their files, and deletes the test letter files in batches.
https://trello.com/c/iHHjm2fs/1149-investigate-nightly-job-for-deleting-test-letter-objects-from-s3-after-the-retention-period-expires
=> Delete test letter files from S3

.pre-commit-config.yaml, requirements.in, requirements.txt, requirements_for_test.txt, requirements_for_test_common.in, ruff.toml
* Fix inset text block styling
=> Bump notify-utils to 97.0.4

app/clients/__init__.py, app/clients/email/__init__.py, app/clients/sms/__init__.py, app/models.py, tests/app/clients/test_sms.py
In one case there’s a better way of doing things than using a `TODO`. In another it was already done.
=> Remove a couple more `TODO`s

app/dao/service_callback_api_dao.py, app/service/callback_rest.py, tests/app/service/test_callback_rest.py
This PR refactors `create_service_callback_api`, `update_service_callback_api`, `remove_service_callback_api` to write to the `service_callback_api` table alongside the `service_inbound_api` for `inbound_sms` callback.
This is to facilitate the merge of the `service_inbound_api` table data into the `service_callback_api` table.
`fetch_service_callback_api` remains unchanged and retrieves `inbound_sms` callback data from the `service_inbound_api` table. This has ramifications for the updating `inbound_sms` callback data stored in the `service_callback_api` table as `update_service_callback_api` utilises `service_inbound_api` `id` which would be different from the `id` of the same callback data in the `service_callback_api` table.
Additionally there will be callback data that is present in …
=> Write to both callback tables

.pre-commit-config.yaml, app/service/statistics.py, requirements.in, requirements.txt, requirements_for_test.txt, requirements_for_test_common.in, ruff.toml
* Normalise unusual dashes and spacing characters in phone numbers
* Bump ruff to latest version
***
Complete changes: https://github.com/alphagov/notifications-utils/compare/99.1.0...99.1.2
=> Bump utils to 99.1.2

app/constants.py, app/dao/services_dao.py, app/functional_tests_fixtures/__init__.py, app/utils.py, migrations/versions/0317_uploads_for_all.py, tests/app/dao/test_services_dao.py, tests/app/service/send_notification/test_send_pdf_letter_notification.py, tests/app/service/test_rest.py
Reverts alphagov/notifications-api#4464
=> Revert "Remove unused service permissions"

tests/app/dao/test_service_callback_api_dao.py
Making the tests more expansive to cover all the callback types
=> Update service_callback_api_dao tests

app/config.py, app/exceptions.py, tests/app/public_contracts/__init__.py
Details in the commit messages
=> Remove small bits of unused code

app/config.py
What
----
Fix local setup after predefined queues change
=> Fix local setup after predefined queues change

app/__init__.py
Without this `COMMIT`, a new connection that happens to receive a `ROLLBACK` of its first transaction will revert all the connection parameters we've tried to set up.
See description of https://www.postgresql.org/docs/current/sql-set.html for explanation of this behaviour.
An alternative would be to create the connection in initial auto-commit mode, but seeing as open-transaction is the "normal" mode for psycopg2, let's stick with that instead of making things ever more unusual.
For a demonstration of this in action, see dev kibana for api-web instance `a4ca1122c13a4abe8291bbbcc7fb7d5e` on dev-e vs. its predecessor `c0160b1c1d984d9fb540cded3f4ad72a`. Both images built from #4580 with additional diagnostic log messages added. Note how predecessor had many connections that got "checked out" …
=> sqlalchemy: perform initial `COMMIT` when setting up session parameters
